### ISSUE TITLE
What Does "Benchmarks with issues" Mean?

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1000]
I have some benchmarks that use to work and now does not. All I see is something like this:

LongRunningPerfTestRunner.'COLLECTION CREATION: Without Capacity': Clr                    -> 2 outliers were removed

But I have no idea what is wrong that is causing BenchmarkDotNet to remove it from the test?

Thanks,
David

**Comment by adamsitnik** [comment]
Hi @RealDotNetDave 

From the [Wikipedia](https://en.wikipedia.org/wiki/Outlier)

> In statistics, an outlier is an observation point that is distant from other observations

Example: you run your benchmark, the results are 10, 10.5, 9.5 and 17. 17 is an outlier, it gets removed by default.

See our docs page for more: https://benchmarkdotnet.org/articles/samples/IntroOutliers.html?q=outlier

**Comment by adamsitnik** [comment]
> What Does "Benchmarks with issues" Mean?

It's our way to say "warning"

**Comment by adamsitnik** [comment]
@RealDotNetDave I am closing this issue now, please feel free to reopen if something is not clear.
