### ISSUE TITLE
improve MinIterationTime and MultimodeDistribution warnings

### ISSUE THREAD

**Issue by JakenVeina** [dotnet/BenchmarkDotNet#1003]
So, I feel like I'm getting some invalid benchmark results, and if so, I'm out of ideas on how to address it.

What I'm seeing is about a dozen warnings of the following form...

```
Add.Dictionary: InvocationCount=1, UnrollFactor=1 -> MinIterationTime = 768.2200 ns which is very small. It's recommended to increase it.
...
Add.Dictionary: InvocationCount=1, UnrollFactor=1 -> It seems that the distribution is bimodal (mValue = 3.49)
```
([FULL BENCHMARK LOG](https://hastebin.com/kemetevuda.makefile))

I had a look at #767 where the author was having what appears to be the exact same issue, on account of a manual configuration, and the fact that the benchmark in question produced side affects.

I have no customized configuration, so I figure my issue has GOT to be the fact that my benchmark also produces side-effects. I attempted to counter the side-effects by use of an `[IterationSetup]` method, but I can only assume I don't know what I'm doing there, since I still get warnings, AND since another benchmark in this same project, which doesn't produce side-effects, doesn't generate any warnings, and takes MUCH longer to run (presumably because it's doing more than 1 iteration).

[Here's the benchmark in question](https://github.com/JakenVeina/ImmutableHashDictionary/blob/master/ImmutableHashDictionary.Benchmark/Add.cs)

Alternatively, the entire [codebase](https://github.com/JakenVeina/ImmutableHashDictionary) should be cloneable and runnable, as-is, to reproduce the issue.

Am I just completely misunderstanding how to counteract side-effects?

**Comment by adamsitnik** [comment]
Hi @JakenVeina 

When you use `[IterationSetup]` BDN executes the benchmark once per iteration. If this a very short operation, the result is unstable. This is why we produce this warning.

However, I agree that the warning does not explain where is the problem.

In your case you should redesign you benchmark to not use `[IterationSetup]` at all or make it execute more operations.

If you are looking for some examples of similar benchmarks, you can find them in https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/corefx/System.Collections/Add

**Comment by JakenVeina** [comment]
I did some more re-reading of docs and the log over the last few days, and it makes sense to me now. But yeah, I suppose the warning could be better. Essentially, it's warning that the iteration count is low, and I was missing the fact that the library usually executes the benchmark method up to hundreds of thousands of times, per iteration (enough to reach a target execution time).

The examples you linked are definitely helpful, but they all include object allocations within the benchmarked code, in addition to the `.Add()` operation. Ideally, I'd like to come up with some metrics for JUST the .Add() portion. Given what I've learned over the last few days, I have a couple thoughts:

1. What I was doing to avoid side-effects is pre-allocating a `Dictionary<TKey, TValue>` UUT, during setup, so that the benchmark operation itself can just perform the `.Add()` that I care about. So, if I need to perform many operations per iteration, the solution seems to be simply "Pre-allocate more than one UUT. Then, for each call to the benchmark method, use a different UUT."
-  I tried a rudimentary version of this idea, but quickly ran into `OutOfMemoryException`s.
2. I could include the setup as part of the real benchmark, and then also benchmark the setup by itself, and attempt to subtract out the setup from the total, when benchmarks are complete.
- I tried this last night, and it actually worked okay, but has a problem with compounding error, and also makes it impossible to have a `Baseline = true` benchmark to compare against.

Is there any way I can get the number of iterations that BTN PLANS to execute injected into the class, so I can pre-allocate just that many objects?

Alternatively, is there any way to "offset" the results of one benchmark by another benchmark? I.E. `AddBenchmarks = CreateAndAddBenchmarks - CreateBenchmarks`?

**Comment by adamsitnik** [comment]
> Is there any way I can get the number of iterations that BTN PLANS to execute injected into the class, so I can pre-allocate just that many objects

No, we don't have such option.

However, I think that should reconsider the design and most probably include the cost of allocating the collection in the benchmark itself.

In the real-life scenarios, the developers are going to create the collection first and then add the items. If you want to optimize the code, you should focus on the entire scenario, not only on a part of it. Also, if the number of elements you want to add is going to be large enough, the cost of creating the collection is going to be very small compared to the cost of all the `.Add()` calls.

BTW. I am going to change the title of this issue from "MinIterationTime and MultimodeDistribution warnings" to "improve MinIterationTime and MultimodeDistribution warnings"

**Comment by JakenVeina** [comment]
The benchmarks here are less about trying to optimize existing code, and more about trying to compare the performance of different classes implementing the same interface, with different underlying algorithms, so consumers can decide which is going to best fit their use scenarios. In that context, I think more granular metrics on the different operations makes a lot of sense. Making individual `.Add()` calls on existing collections is definitely something that can happen frequently in an application.

If it's really not feasible, though, rolling up the setup times into the metric itself is probably not the worst thing in the world. It's definitely a fair point.

Thanks again for all your time and thoughts. I'll see what I can come up with.

**Comment by AArnott** [comment]
> The minimum observed iteration time is 98.4273 ms which is very small. It's recommended to increase it.

I see messages like this frequently. But it doesn't tell me what number would be good. So I blindly add more loops to my iteration method to add more time until the message goes away, but it's a blind guessing game of doubling, then reducing the number, till I get something that satisfies but doesn't overdo it. Can the message be modified to say "try to get it over 120ms" or whatever number it's testing against?

**Comment by jzabroski** [comment]
@AArnott  I believe what you are looking for is pretty much what Expecto expect.isFasterThan does. See https://github.com/haf/expecto#performance-module
