### ISSUE TITLE
C# 8.0 and NullableReferenceTypes in BenchmarkDotNet

### ISSUE THREAD

**Issue by wojtpl2** [dotnet/BenchmarkDotNet#1004]
I know that 8.0 is beta but I think it is a good time to start refactoring project to using NullableReferenceTypes. @AndreyAkinshin, @adamsitnik What do you think about it? If you agree I can start this refactoring. 

e.g. Json.net is already ready https://github.com/JamesNK/Newtonsoft.Json/pull/1950.

**Comment by AndreyAkinshin** [comment]
@wojtpl2 I think we should wait until C# 8.0 is released. If we start to use C# 8.0, it will complicate the initial setup for the contributors. On Windows, they will need VisualStudio 2019 Preview. On Linux and macOS, it will be really hard to work with the C# 8.0 code base right now.

**Comment by adamsitnik** [comment]
@wojtpl2  I agree with @AndreyAkinshin , we should wait until C# is released and supported by all major IDEs (VS, VS+R#, Rider, Code)

**Comment by wojtpl2** [comment]
I mean working on the branch and approving changes when C# 8 will be
released.
But of course I understand your arguments.

śr., 9 sty 2019, 18:01: Adam Sitnik <notifications@github.com> napisał(a):

**Comment by AndreyAkinshin** [comment]
@wojtpl2 I'm afraid it will be hard to merge such branch. I appreciate your enthusiasm, but it will be better to wait.
