### ISSUE TITLE
Use the built-in msbuild extensibility hook "Directory.Build.props"

### ISSUE THREAD

**Issue by CodeTherapist** [dotnet/BenchmarkDotNet#1011]
I would like to propose to replace the [build/common.props](https://github.com/dotnet/BenchmarkDotNet/blob/master/build/common.props) with the [MSBuild built-in extensibility hook](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017#directorybuildprops-and-directorybuildtargets). 

Of course it's more implicit than the current solution - but it simplifies the workflow for new projects to be automatically setup the right way.

```
\
  BenchmarkDotNet.sln
  Directory.Build.props     (Common for all projects)
  \src
    Directory.Build.props   (Common for all src projects)
    \BenchmarkDotNet
    \BenchmarkDotNet.Disassembler.x64
    \...
  \test
    Directory.Build.props   (Common for all test projects)
    \BenchmarkDotNet.Tests
    \BenchmarkDotNet.IntegrationTests
    \…
```

**Comment by adamsitnik** [comment]
Hi @CodeTherapist 

I don't like this approach. The idea is cool, but people tend to add more and more `.props` and `.targets` files and at some point of time you end up with a lot of settings imported from many files. The folder structure matters, the order of loading the settings etc. 

I prefer the simpler approach we have today: everything needs to be explicit but it's very easy to find out the imported files. 

Having said that, I am going to close this issue. Thank you for your proposal and time!
