### ISSUE TITLE
Errors using undefined enum values as benchmark arguments

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/BenchmarkDotNet#1020]
Consider the following benchmark.

```c#
[Benchmark]
[Arguments((DayOfWeek)(-1))]
public int GetHashCode(Enum value) => value.GetHashCode();
```

Specifying undefined enum values as benchmark arguments causes the following build errors.

```
// Build Exception: The build has failed!
CS1001: Identifier expected
CS0117: 'DayOfWeek' does not contain a definition for ''
```

**Comment by AndreyAkinshin** [comment]
@TylerBrinkley thanks for the bug report!

**Comment by Rizzen** [comment]
I believe I can do it.

**Comment by AndreyAkinshin** [comment]
@Rizzen great!

**Comment by TylerBrinkley** [comment]
Would the related change occur at https://github.com/dotnet/BenchmarkDotNet/blob/04747a34fb03f2752b51f27fc233d8672c82248b/src/BenchmarkDotNet/Helpers/SourceCodeHelper.cs#L36

**Comment by adamsitnik** [comment]
@Rizzen when I took #1071 it turned out that both issues can be fixed with a single fix, so I just fixed it. Sorry for taking your issue.

**Comment by TylerBrinkley** [comment]
I think this will still error for negative values. The value portion needs to be wrapped in parentheses as well.

**Comment by adamsitnik** [comment]
@TylerBrinkley good catch! thanks!

fixed with https://github.com/dotnet/BenchmarkDotNet/commit/c5c4c4dab89c1842f06fe45fdddbdf3271255137
