### ISSUE TITLE
Out of process benchmarks fail with ASP.NET Core SDK reference

### ISSUE THREAD

**Issue by JamesNK** [dotnet/BenchmarkDotNet#1023]
I am running into this error when benchmarking a project that references the ASP.NET Core SDK: https://github.com/aspnet/grpc-dotnet/pull/5#discussion_r249236799

The error only happens when the tests are run out of process. They run perfectly when in-process.

A possible cause could be the new ASP.NET Core SDK. In .NET Core 3 the ASP.NET bits are distributed as an SDK instead of NuGet packages, i.e. `<FrameworkReference Include="Microsoft.AspNetCore.App" />`.

Is it possible the csproj file that BenchmarkDotNet generates for out of process doesn't have the framework reference?

// @JunTaoLuo

**Comment by adamsitnik** [comment]
hi @JamesNK !

> Is it possible the csproj file that BenchmarkDotNet generates for out of process doesn't have the framework reference?

yes, it does not generate it. 

I cloned the repo and was able to reproduce the problem. Adding reference to `Microsoft.AspNetCore.App` in the auto-generated project solves the problem. However, I need to verify one thing before I add such thing to BDN:

If project `A` references `Microsoft.AspNetCore.App` and project `B` references project `A` I would assume that project B does not need to have an explicit reference to `Microsoft.AspNetCore.App`. Should I expect that `FrameworkReference` is a very new thing and the behaviour is going to change soon (no need for a change on BDN side) or it's never gonna change and I should add it to BDN?

**Comment by JamesNK** [comment]
> If project A references Microsoft.AspNetCore.App and project B references project A I would assume that project B does not need to have an explicit reference to Microsoft.AspNetCore.App.

I think so, however I believe there is a bug in 3.0 preview 1 that stopps it from being transitive.

> Should I expect that FrameworkReference is a very new thing and the behaviour is going to change soon (no need for a change on BDN side) or it's never gonna change and I should add it to BDN?

I'm not sure. It is new to me as well. It will become very common as any benchmarks that use ASP.NET components will need to use `FrameworkReference`.

@natemcmaster do you know, or know who would know the answers here? 😄

**Comment by natemcmaster** [comment]
FrameworkReference is very new, and will churn a fair amount over the next for .NET Core 3 previews. Flowing FrameworkReference's from project to project is not yet supported: https://github.com/dotnet/sdk/issues/2420 - I don't have an ETA for when this will be fixed.

**Comment by adamsitnik** [comment]
As discussed offline today with @JamesNK I would prefer not changing anything on BDN side and wait until dotnet cli makes the new `FrameworkReference` transitive.

I will keep this issue open until dotnet cli fixes it so ppl can google it.

**Comment by adamsitnik** [comment]
@JamesNK do you know if this is still a problem?

**Comment by JamesNK** [comment]
It now works.

**Comment by adamsitnik** [comment]
@JamesNK thanks!
