### ISSUE TITLE
Add new template for "dotnet new benchmark"

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1028]
I think that we should add a new template for dotnet cli that would create following app when used:

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace BenchmarkApp
{
    class Program
    {
        static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);
    }

    public class TypeWithBenchmarks
    {
        [Benchmark]
        public int YourBenchmark()
        {
            // implement your benchmark here
            return 0;
        }
    }
}
```

@AndreyAkinshin what do you think?

**Comment by AndreyAkinshin** [comment]
@adamsitnik I like this idea!

**Comment by adamsitnik** [comment]
btw the .csproj should be:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$whatUserHasAskedFor</TargetFramework>
    <OutputType>Exe</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.1*" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.1*" />
  </ItemGroup>

</Project>
```

**Comment by CodeTherapist** [comment]
I would like to do this :)

**Comment by adamsitnik** [comment]
@CodeTherapist awesome! please let me know if you need anything

**Comment by dzmitry-lahoda** [comment]
Would it be possible to have template for F# and with more code (i.e. template with examples) like next https://github.com/TheAngryByrd/BenchmarkDotNet.Template/issues/3 ?

**Comment by TheAngryByrd** [comment]
I'd be happy to just port the code I have in that repo to something under here as it will get more love and attention.

**Comment by JamieKeeling** [comment]
I've written a template or two before but could do with a bit of information from yourselves that would help shape the output.

1. Where would you prefer the template content to be stored within the repository? Alternatively would a separate repository be better and ownership transferred.
2. Templating supports [file system or Nuget installation](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template). File system is a low bar of entry but Nuget is ultimately more flexible and easier for consumers.

**Comment by Kavignon** [comment]
How can I be of help here?

**Comment by AndreyAkinshin** [comment]
@Kavignon we already have a pull request by @CodeTherapist with basic template support: https://github.com/dotnet/BenchmarkDotNet/pull/1044 However, I raised some concerns about the current PR status: https://github.com/dotnet/BenchmarkDotNet/pull/1044#pullrequestreview-261539007 . I think it will be better to continue discussion there and finish the PR.
@CodeTherapist do you need any help with the PR?

**Comment by CodeTherapist** [comment]
@AndreyAkinshin No help needed, thanks - I will finish it this week(end).

**Comment by AndreyAkinshin** [comment]
@CodeTherapist awesome, thanks!

**Comment by am11** [comment]
@AndreyAkinshin, when would the official template package made available on nuget.org?

e.g.

* https://www.nuget.org/packages/NUnit3.DotNetNew.Template/
* https://www.nuget.org/packages/giraffe-template/

and unofficial packages of BenchmarkDotNet:
* https://www.nuget.org/packages/AtleX.BenchmarkDotNet.Template.CSharp/
* https://www.nuget.org/packages/TheAngryByrd.BenchmarkDotNet.Templates/

**Comment by AndreyAkinshin** [comment]
@am11 official template was published a few days ago: https://www.nuget.org/packages/BenchmarkDotNet.Templates/

**Comment by TheAngryByrd** [comment]
I just marked my github repo as archived and my nuget package as deprecated.

**Comment by AndreyAkinshin** [comment]
@TheAngryByrd great, thanks!

**Comment by am11** [comment]
Thank you @AndreyAkinshin! 🎉

[maybe not a huge deal but..]
IMHO, the template should be in a runnable state with these additions:

<details>
  <summary>Click to expand</summary>

```diff
--- a/Benchmarks.cs
+++ b/Benchmarks.cs
using System;
using BenchmarkDotNet;
using BenchmarkDotNet.Attributes;
+using BenchmarkDotNet.Running;
 
 namespace Sample
 {
+    class Program
+    {
+        static void Main() => BenchmarkRunner.Run<Benchmarks>();
+    }
+
     public class Benchmarks
     {
         [Benchmark]

--- a/Sample.csproj
+++ b/Sample.csproj
 <Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
-    <TargetFrameworks>netstandard2.0</TargetFrameworks>
+    <TargetFramework>netcoreapp3.0</TargetFramework>
+    <OutputType>Exe</OutputType>
   </PropertyGroup>
   <PropertyGroup>
     <PlatformTarget>AnyCPU</PlatformTarget>
```
</details>

So the getting started steps would look like:

```sh
dotnet new benchmark --name Sample
cd Sample
dotnet run
```

**Comment by TheAngryByrd** [comment]
there's a CLI flag for that with the template `--console-app`

```
dotnet new benchmark --console-app
```

I know I missed it the first time.  I could argue for it being the default too :)

**Comment by CodeTherapist** [comment]
Thanks @am11 and  @TheAngryByrd for your feedback and question. I'm happy to help.
The template has this "runnale state" as an option when you create the new project (docs):

```
dotnet new benchmark --name Sample --console-app
cd Sample
dotnet run
```

Alternatively, you could install and use the the global [BenchmarkDotNet tool](https://www.nuget.org/packages/BenchmarkDotNet.Tool/) and invoke the benchmarks from the CLI (Docs).

BenchmarkDotnet will strengthen it's integration with leading IDE's in the future to provide better user experience and workflow - similiar to unit tests.
Neverless, any feedback is appreciated and will be considered for further releases.

**Comment by am11** [comment]
Great! Thanks for your help and documentation. 👍
