### ISSUE TITLE
Something is wrong with our Ubuntu CI

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1051]
I have noticed that our Ubuntu CI is unstable.

From time to time it fails with an exception that seems to be "impossible".

Example: https://github.com/dotnet/BenchmarkDotNet/pull/1050/checks?check_run_id=59120862

```log
// Build Error: Exception! 
Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength,
Stack trace:
   at System.Text.StringBuilder.ToString()
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliCommandExecutor.Execute(DotNetCliCommand parameters) in /home/vsts/work/1/s/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs:line 56
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliCommand.RestoreThenBuild() in /home/vsts/work/1/s/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs:line 50
```

Our code:

https://github.com/dotnet/BenchmarkDotNet/blob/f9c8cc5b835a3635adf1606440f10873015f5058/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs#L139-L146

CoreFX code:

https://github.com/dotnet/corefx/blob/fc9ba56ce0384b58f1ce81647ac2d3b8b49ef8fa/src/Common/src/CoreLib/System/Text/StringBuilder.cs#L381-L389

The problem is that this code should not throw in our case, because we create a local instance of StringBuilder and don't share it with other threads.

**Comment by adamsitnik** [comment]
I updated the dotnet cli and removed the capacity for StringBuilders, but our tests can still run from 32minute (green) to 1.5h (red)

**Comment by 0xd4d** [comment]
You're looking at the wrong method, it's this one: https://github.com/dotnet/BenchmarkDotNet/blob/f9c8cc5b835a3635adf1606440f10873015f5058/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs#L19-L55

It writes to the string builders asynchronously on a worker thread.

**Comment by adamsitnik** [comment]
@0xd4d thanks for pointing this out!!
