### ISSUE TITLE
Disassembly diagnoser should be kept in a separate directory to avoid dependency conflicts

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1059]
From @ericstj

> we hit an issue yesterday when @tarekgh was running some tests where the test workflow copied the test application and the Disassembly Diagnoser to the same folder.  They happened to have the same dependencies and the test-app’s version of the dependencies overwrote the Diagnoser’s depedendencies.  Since the Diagnoser was running on desktop it wasn’t resilient to getting a newer version of the dependency.  In general it seems like more bad things can happen here, rather than just getting a different version it could have also gotten the “wrong” version (core vs desktop).  I think benchmark dotnet should put this diagnoser in a separate directory from the test app.

**Comment by ericstj** [comment]
Thanks for a quick fix!
