### ISSUE TITLE
[Question] How does virtualization affect measurements?

### ISSUE THREAD

**Issue by ladeak** [dotnet/BenchmarkDotNet#1060]
What does the following notification mean?
>Benchmark was executed on the virtual machine with Hyper-V hypervisor. Virtualization can affect the measurement result.

Is there any good source about how virtualization can affect the measurement? I have not seen anything about this topic in the documentation. Could you please point me to some pivot points?

**Comment by adamsitnik** [comment]
@AndreyAkinshin do you have some good reads?

**Comment by adamsitnik** [comment]
Hi @ladeak 

Please excuse us for not responding for so long. I don't have any good references, but I am sure that if you ask this question at StackOverflow someone is going to provide a great answer.

Thank you,
Adam
