### ISSUE TITLE
Write the GitHub table format to the console by default

### ISSUE THREAD

**Issue by eerhardt** [dotnet/BenchmarkDotNet#1062]
By default, if I take the console output of running a benchmark:

```
                 Method |       Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
----------------------- |-----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
      ArrowStreamReader | 110.018 ms | 1.8017 ms | 1.6853 ms |  21000.0000 |           - |           - |        110693.78 KB |
 ArrowRecordBatchReader |   6.789 ms | 0.1569 ms | 0.4603 ms |           - |           - |           - |            63.52 KB |
```

And paste that into GitHub, it doesn't recognize it as a table.

For example:

                 Method |       Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
----------------------- |-----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
      ArrowStreamReader | 110.018 ms | 1.8017 ms | 1.6853 ms |  21000.0000 |           - |           - |        110693.78 KB |
 ArrowRecordBatchReader |   6.789 ms | 0.1569 ms | 0.4603 ms |           - |           - |           - |            63.52 KB |

I think the default format that gets written to the console should be the GitHub format. What's even worse is that folks like me (who don't have the format memorized) will think this table looks like it should work, paste it into GitHub, and then have to fix it up after they realize that this isn't the right format.

**Comment by adamsitnik** [comment]
I totally agree, I am going to change it to make GH the default format we print to the console (it should be one liner)

**Comment by adamsitnik** [comment]
That was most probably the best UX improvement made in BDN with single code line change ;)

https://github.com/dotnet/BenchmarkDotNet/blob/61f56318ba53d5ad4ef8ea6cf62ba8e77b65fbdb/src/BenchmarkDotNet/Exporters/MarkdownExporter.cs#L37
