### ISSUE TITLE
Provide an API for setup/cleanup shared across all parameter values

### ISSUE THREAD

**Issue by TheJakeSchmidt** [dotnet/BenchmarkDotNet#1064]
BenchmarkDotNet runs methods marked `[GlobalSetup]` and `[GlobalCleanup]` once per set of parameter values. We have a benchmark that does some even-more-global-than-that setup (deploying some code to a load-testing server), which doesn't need to be re-run for each parameter setting. It would be good to have a hook (`[SeriouslyGlobalSetup]`?) that runs only once for all benchmark runs, in addition to the existing setup/cleanup hooks.

**Comment by jzabroski** [comment]
@TheJakeSchmidt Something like what [Xunit.Performance](https://github.com/Microsoft/xunit-performance) does? Example below:

```csharp
[Benchmark(InnerIterationCount=500)]
void TestMethod()
{
    // The first iteration is the "warmup" iteration, where all performance
    // metrics are discarded. Subsequent iterations are measured.
    foreach (var iteration in Benchmark.Iterations)
        using (iteration.StartMeasurement())
            // Inner iterations are recommended for fast running benchmarks
            // that complete very quickly (microseconds). This ensures that
            // the benchmark code runs long enough to dominate the harness's
            // overhead.
            for (int i=0; i<Benchmark.InnerIterationCount; i++)
                // test code here
}
```

**Comment by adamsitnik** [comment]
@TheJakeSchmidt In such a case you should move the even-more-global-than-that logic outside of the type that defines benchmarks

Something like this:

```cs
Setup-even-more-global-than-that();

BenchmarkRunner.Run(); 

Cleanup-even-more-global-than-that();
```

I just don't see a good justification for us to add one more type of a setup method. As you have noticed, even finding a good name would be hard. We would also need to ensure that there is only one such setup and cleanup per assembly etc. It's rather not worth adding to BDN.

Having said that I am going to close the issue.

Thank you for your proposal,
Adam
