### ISSUE TITLE
Improve API for job environment variables

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#1069]
Consider the following job:

```cs
var job = new Job()
    .With(new[] { new EnvironmentVariable("a", "b") })
    .With(new[] { new EnvironmentVariable("c", "d") });
```

The corresponding `With` method is defined as follows:

```cs
public static Job With(this Job job, IReadOnlyList<EnvironmentVariable> environmentVariables) =>
    job.WithCore(j => j.Environment.EnvironmentVariables = environmentVariables);
```

It means that it always override the whole `EnvironmentVariables` list. In the above example, `job` has only one a single environment variable `"c"`. I think that this behavior looks pretty confusing. It will be better to add new environment variables instead of rewriting the whole list.

I want to make a breaking change and replace the "overriding" logic by "adding" logic. However, we also should provide a way to remove an environment variable from a job. I was thinking about the following API:

```cs
// Add the specified environment variables
With(this Job job, IReadOnlyList<EnvironmentVariable> environmentVariable)
// Add the specified environment variable
WithEnvironmentVariable(this Job job, EnvironmentVariable variable)
WithEnvironmentVariable(this Job job, string key, string value)
// Remove the specified environment variable
WithoutEnvironmentVariable(this Job job, string key)
// Remove all environment variables
WithoutEnvironmentVariables(this Job job)
```

Also, if an environment variable is previously defined, it should be overridden by the new value (instead of having two variables with the same key in the `EnvironmentVariables` list).

@adamsitnik what do you think?

**Comment by adamsitnik** [comment]
@AndreyAkinshin I think that we should keep the existing logic (when a whole collection is provided, overwrite the list), but also add `With(this Job job, EnvironmentVariable variable)` which would just add it to the list

**Comment by adamsitnik** [comment]
the other overloads are nice to have, but I am not sure if we need them (imho  `With(this Job job, EnvironmentVariable variable)` should be enough, the most common case is just to add env vars)
