### ISSUE TITLE
Results should be exported to a file with unique name

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1074]
One of the common problems with BDN is that users re-run the benchmarks and the results get overwritten.

I think that we should change the default behaviour, the file name should not only be full benchmark name but also date. 

@AndreyAkinshin what do you think?

**Comment by AndreyAkinshin** [comment]
It's an interesting idea: it would be nice to have such an option. However, I'm not sure about the default behavior. I have two "cons":

* Currently, I can open an editor with some files from the `Results` folder (both plain text and plots) and get updates on the fly after each benchmark run.
* When `RPlotExporer` is enabled, BenchmarkDotNet creates tons of different plots. If it will put plots in a new folder each time, the `BenchmarkDotNet.Artifacts` folder will consume a lot of disk space pretty quickly.

@adamsitnik could we try to introduce an option, play with it, and make a decision about the default behavior later?

**Comment by adamsitnik** [comment]
@AndreyAkinshin good points, I have create a PR #1083
