### ISSUE TITLE
Test method name shown even when it's the same for all tests (and Type isn't)

### ISSUE THREAD

**Issue by Zhentar** [dotnet/BenchmarkDotNet#1076]
Showing the method when there's only one benchmark makes sense, but it doesn't work as well when the type is the variable:

|                    Type | Method |      Mean |     Error |    StdDev |
|------------------------ |------- |----------:|----------:|----------:|
|      Asm<Baseline_1024> |   Test | 20.206 ns | 0.2821 ns | 0.2639 ns |
|       Asm<Baseline_128> |   Test | 11.372 ns | 0.6563 ns | 0.9619 ns |
|       Asm<Baseline_256> |   Test | 13.294 ns | 0.7331 ns | 0.7528 ns |
|        Asm<Baseline_32> |   Test | 14.580 ns | 0.4403 ns | 0.3677 ns |
|       Asm<Baseline_512> |   Test | 15.250 ns | 0.5218 ns | 0.4626 ns |
|        Asm<Baseline_64> |   Test | 11.739 ns | 0.6649 ns | 1.1645 ns |
| Asm<ImprovedStosB_1024> |   Test | 16.386 ns | 0.4398 ns | 0.4114 ns |
|  Asm<ImprovedStosB_128> |   Test | 10.525 ns | 0.5997 ns | 0.8006 ns |
|  Asm<ImprovedStosB_256> |   Test | 13.196 ns | 0.7413 ns | 1.3177 ns |
|   Asm<ImprovedStosB_32> |   Test | 11.144 ns | 0.6387 ns | 1.0672 ns |
|  Asm<ImprovedStosB_512> |   Test | 14.573 ns | 0.7976 ns | 0.7461 ns |
|   Asm<ImprovedStosB_64> |   Test | 11.593 ns | 0.6573 ns | 1.2506 ns |
| Asm<ImprovedStosD_1024> |   Test | 20.170 ns | 0.3780 ns | 0.3536 ns |
|  Asm<ImprovedStosD_128> |   Test | 10.463 ns | 0.5887 ns | 0.7229 ns |
|  Asm<ImprovedStosD_256> |   Test | 12.746 ns | 0.5993 ns | 0.5313 ns |
|   Asm<ImprovedStosD_32> |   Test | 11.537 ns | 0.6705 ns | 1.5405 ns |
|  Asm<ImprovedStosD_512> |   Test | 14.017 ns | 0.4450 ns | 0.4162 ns |
|   Asm<ImprovedStosD_64> |   Test | 11.174 ns | 0.5104 ns | 0.4524 ns |
| Asm<ImprovedStosQ_1024> |   Test | 19.654 ns | 0.2912 ns | 0.2431 ns |
|  Asm<ImprovedStosQ_128> |   Test | 11.275 ns | 0.6457 ns | 1.3043 ns |
|  Asm<ImprovedStosQ_256> |   Test | 12.788 ns | 0.7138 ns | 0.7011 ns |
|   Asm<ImprovedStosQ_32> |   Test | 11.339 ns | 0.6560 ns | 1.0404 ns |
|  Asm<ImprovedStosQ_512> |   Test | 15.022 ns | 0.8259 ns | 0.9180 ns |
|   Asm<ImprovedStosQ_64> |   Test | 10.728 ns | 0.4377 ns | 0.4094 ns |
|           Asm<Overhead> |   Test |  1.781 ns | 0.1919 ns | 0.3309 ns |
|          Asm<SSE2_1024> |   Test | 23.180 ns | 0.1789 ns | 0.1673 ns |
|           Asm<SSE2_128> |   Test |  3.113 ns | 0.2420 ns | 0.3313 ns |
|           Asm<SSE2_256> |   Test |  6.521 ns | 0.4130 ns | 0.6551 ns |
|            Asm<SSE2_32> |   Test |  1.770 ns | 0.1706 ns | 0.2501 ns |
|           Asm<SSE2_512> |   Test | 11.777 ns | 0.2834 ns | 0.2651 ns |
|            Asm<SSE2_64> |   Test |  2.453 ns | 0.2152 ns | 0.4857 ns |

**Comment by adamsitnik** [comment]
I believe that this is an edge case and I don't see us having any free time to add special handling of it anytime soon. So I am closing the issue.
