### ISSUE TITLE
Visual Studio Code Extension

### ISSUE THREAD

**Issue by mantzas** [dotnet/BenchmarkDotNet#1085]
A extension in Visual Studio Code for running benchmark would be nice.
The idea is to recognize benchmarks, run them (single, multiple) and provide a report on the results.

**Comment by AndreyAkinshin** [comment]
@mantzas thanks for the PR! However, we are not going to keep any kinds of IDE extension/plugins in this repository, so I close this issue. You are free to create your own repositories for such projects.
