### ISSUE TITLE
XmlExporter.Full fails with StackOverflowException

### ISSUE THREAD

**Issue by szehetner** [dotnet/BenchmarkDotNet#1086]
Running a Benchmark with the fullxml exporter ("-e fullxml") causes the benchmark process to terminate with the message:
`Process is terminated due to StackOverflowException.`

Benchmark code (though it doesn't seem to matter, failed with all benchmarks I tried):
```csharp
public class BenchmarkSample
{
    [Benchmark]
    public int Parse() => int.Parse("1");
}
```

Version: 0.11.4

**Comment by daveMueller** [comment]
I made pull request for this #1090 . Would be cool if somebody will review.
I adapted the `XmlExporterBase` in the same way as `JsonExporterBase` by excluding the `Encoding` property. Please tell me if this is sufficient.

**Comment by adamsitnik** [comment]
> Please tell me if this is sufficient.

@daveMueller I tested it locally and it works. Thank you for providing the fix!
