### ISSUE TITLE
Installing from nuget downloads deluge of files?

### ISSUE THREAD

**Issue by Fritzoid** [dotnet/BenchmarkDotNet#1087]
Hi,

I tried installing BenchmarkDotNet 0.11.4 today using 'Manage NuGet packages for solution...' in visual studio 2017. After a long while , it went well, except that it downloaded and referenced several files I didnt expect. Things like System.IO, System.Reflection, System.Collections and several other standard .NET libraries???? What is going on?

Im using visual studio 2017 enterprise and targeting the .NET 4.7 framework.

**Comment by adamsitnik** [comment]
Hi @Fritzoid 

Please read following blog to get a better understanding:

https://weblog.west-wind.com/posts/2019/Feb/19/Using-NET-Standard-with-Full-Framework-NET

**Comment by Fritzoid** [comment]
Ok ty :) Its not really obvious from your docs, but I get it now. To avoid it, just target 4.7.2 ...

**Comment by adamsitnik** [comment]
You can contribute to our docs and improve them if you believe that this is important. You could add this question and answer to our FAQ: https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/faq.md

**Comment by Fritzoid** [comment]
Except that it didnt help to target 4.7.2 instead. Several standard assemblies are still being pulled in. Maybe I just don't understand the blogpost you linked. oh well, never mind.
