### ISSUE TITLE
Does - in allocated memory column means 0 bytes allocated ?

### ISSUE THREAD

**Issue by kshyju** [dotnet/BenchmarkDotNet#1089]
Does `-` in the allocated column means 0 bytes allocated in managed heap ? I am confused because @adamsitnik 's [blog post](https://adamsitnik.com/the-new-Memory-Diagnoser/#how-to-read-the-results) shows explicitly 0 B in the allocated column. It is clear that `0` represents `0` in the the gen columns(from the blog post). What about the "Allocated memory" column ?

![image](https://user-images.githubusercontent.com/144469/53689961-2290ca80-3d16-11e9-9297-fd25638d168a.png)

Version 0.11.4, if that matters.

**Comment by adamsitnik** [comment]
@kshyju yes, `-` means `0`. Sorry for the inconvenience, I am going to update the description on my blog.

**Comment by adamsitnik** [comment]
Fixed with https://github.com/adamsitnik/adamsitnik.github.io/commit/824e531f8d52b506ba8cdc9bfa750960301d10c2

**Comment by kshyju** [comment]
Thanks Adam.
