### ISSUE TITLE
Unable to build project due to .NETStandard dependency error

### ISSUE THREAD

**Issue by aparajit-pratap** [dotnet/BenchmarkDotNet#1091]
I see the following errors on a build machine with `BenchMarkDotNet` attributes used in my code. I'm able to build and run on my local machine however (using VS2017 and .NET fx 4.7). 
```
PerformanceTestFramework.cs(43,10): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```
I tried adding a reference to netstandard to my csproj file but to no avail:
```
<Reference Include="netstandard" />
```

However after adding the reference above I saw these additional errors:
```
 "E:\Builds\Jenkins\Dynamo_master\Dynamo\src\build.xml" (default target) (1) ->
"E:\Builds\Jenkins\Dynamo_master\Dynamo\src\Dynamo.All.sln" (Rebuild target) (2) ->
"E:\Builds\Jenkins\Dynamo_master\Dynamo\test\Performance\DynamoPerformanceTests\DynamoPerformanceTests.csproj" (Rebuild target) (94) ->
  C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "netstandard". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [E:\Builds\Jenkins\Dynamo_master\Dynamo\test\Performance\DynamoPerformanceTests\DynamoPerformanceTests.csproj]
  C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190. [E:\Builds\Jenkins\Dynamo_master\Dynamo\test\Performance\DynamoPerformanceTests\DynamoPerformanceTests.csproj]
  C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [E:\Builds\Jenkins\Dynamo_master\Dynamo\test\Performance\DynamoPerformanceTests\DynamoPerformanceTests.csproj] 
```

I suspect this could be due to the fact that the build machine does not have VS2017? 

Any help with what could be going wrong here?

**Comment by aparajit-pratap** [comment]
Installing BenchmarkDotNet version 0.11.3 instead worked.

**Comment by mjkkirschner** [comment]
Is it intentional that the latest Nuget only has a target version for net standard 2.0?

**Comment by adamsitnik** [comment]
Hi @aparajit-pratap 

I think that this is more a .NET Standard specific issue than BenchmarkDotNet. Could you try to install a newer Full .NET Framework SDK?

**Comment by adamsitnik** [comment]
hi @mjkkirschner 

> Is it intentional that the latest Nuget only has a target version for net standard 2.0?

yes, we want to keep our code simple and avoid targeting multiple frameworks if we can.

We used to target `net46` as well, but Roslyn, one of our key dependencies in now going to support .NET Standard 2.0 only. So even if we would add `net461` target the users would end up using .NET Standard 2.0 anyway.

**Comment by aparajit-pratap** [comment]
@adamsitnik thanks for your response. At the moment we have gotten around this issue by reverting to an older version of BDM, 0.11.3 to get it to build instead of installing new SDK's.
