### ISSUE TITLE
Detected package downgrade: Microsoft.NETCore.App from 2.0.9 to 2.0.0 issue.

### ISSUE THREAD

**Issue by alexeybut** [dotnet/BenchmarkDotNet#1099]
This issue occurs on NetCore 2.0 projects.
Adding the following properties to autogenerated csproj file fixes this issue.
\<RuntimeFrameworkVersion\>2.0.9\</RuntimeFrameworkVersion\>
or
\<TargetLatestRuntimePatch\>true\<TargetLatestRuntimePatch\>

Test Name:	SimpleTestWithCustomSettings
Test Outcome:	Failed
Result Message:	
System.Exception : Test has not been executed. It may be an unhandled exception raised in the test code or incorrect benchmark settings.
See output for details.
Result StandardOutput:	
// Validating benchmarks:
No exporters defined, results will not be persisted.
No column providers defined, result table will be empty.
Assembly Sample.netstandard2.0 which defines benchmarks is non-optimized
Benchmark was built without optimization enabled (most probably a DEBUG configuration). Please, build it in RELEASE.
// ***** BenchmarkRunner: Start   *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet restore  /p:UseSharedCompilation=false in X:\test\Sample\bin\Debug\netcoreapp2.0\win10-x64\Job-MKODDJ
// command took 2.33s and exited with 1
// ***** Done, took 00:00:02 (2.46 sec)   *****
// Found benchmarks:
//   PerformanceTestSample.SimpleTestWithCustomSettingsMethod: Job-MKODDJ(IterationCount=10, LaunchCount=2, RunStrategy=Monitoring, WarmupCount=0)

// Build Exception: Standard output: 
   Restoring packages for X:\test\Sample\bin\Debug\netcoreapp2.0\win10-x64\Job-MKODDJ\BenchmarkDotNet.Autogenerated.csproj...
  Restoring packages for X:\test\Sample\Sample.netstandard2.0.csproj...
  Generating MSBuild file X:\test\Sample\obj\Sample.netstandard2.0.csproj.nuget.g.props.
  Restore completed in 818.5 ms for X:\test\Sample\Sample.netstandard2.0.csproj.
X:\test\Sample\bin\Debug\netcoreapp2.0\win10-x64\Job-MKODDJ\BenchmarkDotNet.Autogenerated.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.App from 2.0.9 to 2.0.0. Reference the package directly from the project to select a different version. 
X:\test\Sample\bin\Debug\netcoreapp2.0\win10-x64\Job-MKODDJ\BenchmarkDotNet.Autogenerated.csproj : error NU1605:  Job-MKODDJ -> Sample.netstandard2.0 -> Microsoft.NETCore.App (>= 2.0.9) 
X:\test\Sample\bin\Debug\netcoreapp2.0\win10-x64\Job-MKODDJ\BenchmarkDotNet.Autogenerated.csproj : error NU1605:  Job-MKODDJ -> Microsoft.NETCore.App (>= 2.0.0)
  Generating MSBuild file X:\test\Sample\bin\Debug\netcoreapp2.0\win10-x64\Job-MKODDJ\obj\BenchmarkDotNet.Autogenerated.csproj.nuget.g.props.
  Generating MSBuild file X:\test\Sample\bin\Debug\netcoreapp2.0\win10-x64\Job-MKODDJ\obj\BenchmarkDotNet.Autogenerated.csproj.nuget.g.targets.
  Restore failed in 1.04 sec for X:\test\Sample\bin\Debug\netcoreapp2.0\win10-x64\Job-MKODDJ\BenchmarkDotNet.Autogenerated.csproj.

 
 Standard error: 
 

// ***** BenchmarkRunner: Finish  *****

// * Export *

// * Detailed results *
PerformanceTestSample.SimpleTestWithCustomSettingsMethod: Job-MKODDJ(IterationCount=10, LaunchCount=2, RunStrategy=Monitoring, WarmupCount=0)
Runtime = ; GC = 
There are not any results runs

// * Summary *

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17763.348 (1809/October2018Update/Redstone5)
Intel Core i7-3610QM CPU 2.30GHz (Ivy Bridge), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=2.1.503
  [Host] : .NET Core ? (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT

Benchmarks with issues:
  PerformanceTestSample.SimpleTestWithCustomSettingsMethod: Job-MKODDJ(IterationCount=10, LaunchCount=2, RunStrategy=Monitoring, WarmupCount=0)

// * Legends *
  1 ns : 1 Nanosecond (0.000000001 sec)

// ***** BenchmarkRunner: End *****
Run time: 00:00:00 (0.48 sec), executed benchmarks: 0

// * Artifacts cleanup *

**Comment by wojtpl2** [comment]
Are you build project in RELEASE mode? 

>Assembly Sample.netstandard2.0 which defines benchmarks is non-optimized
Benchmark was built without optimization enabled (most probably a DEBUG configuration). Please, build it in RELEASE.

**Comment by AndreyAkinshin** [comment]
@alexeybut is your problem still actual?

**Comment by adamsitnik** [comment]
No response since September, closing.
