### ISSUE TITLE
Add Exporter for Excel format files (.xlsx and maybe .xls)

### ISSUE THREAD

**Issue by Motvin** [dotnet/BenchmarkDotNet#1100]
This could be done with npoi.
Currently I manually cut and paste the .html output file into an Excel worksheet, add some comments at the top, and format some things.  It would be nice if there was an Excel based file exporter that did this instead of having to do this manually.

The default output could be similar to the .html file output except I think only a single header line at the top (BenchmarkDotNet version, brief cpu info, and brief Host info) instead of the 5 or so in the .html file, which is really too verbose seeing the same thing over and over for all of my benchmarks at the very top.

It would also be nice to have a description of the benchmark appear as a second row.

Then the header as a 3rd/4th row.  Put all units in the header by default.  Format N with commas - not sure why the html output doesn't do that already since the measurement values do have commas?

By default show each benchmark as a separate column (along with its measurements).  This format would be nicer to compare and chart the benchmarks.  N would only have to be shown in a single column, but Mean etc. would have a separate column for each benchmark.  The 3rd row would show the benchmark name (centered and merged), then the 4th row would show the column measurement name (Mean, etc.).  These would be in bold and frozen so they would remain at the top when scrolling vertically.

Could add some highlighting with colors and charting.

I could work on this.  I have some experience with writing Excel files using npoi.

**Comment by Motvin** [comment]
Thinking about this more, it would be better to have BenchmarkDotNet output to a database (SQLite or whatever) and then do reporting off of that, or just parse the existing .csv files and produce nicer Excel file reports from that.  That way the Excel report creation program could be separate from BenchmarkDotNet code.  Maybe I'll try writing this reporter program if I end up doing lots of benchmarking again.

**Comment by adamsitnik** [comment]
Hi @Motvin 

Thank you for your proposal.

In general, we try to focus mostly on performance-related features and just provide an extensible architecture for those who need more. Our free time that we spend on the development of  BDN is simply limited and we have to limit the new features (and size of the maintained code).

In your case, you could just import the produced `.csv` files to Excel, or as you said write your own reporting. For that, you would need to implement a type that implements the `IExported` interface:

https://github.com/dotnet/BenchmarkDotNet/blob/cd0bda41dce2f266bc09900e31d8f0d4f52eedec/src/BenchmarkDotNet/Exporters/IExporter.cs#L7

An example implementation can be found [here](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Exporters/Csv/CsvExporter.cs)

and use it in your config:

```cs
DefaultConfig.Instance.AddExporter(new YourExporter());
```

Thank you,
Adam
