### ISSUE TITLE
Difficulties debugging benchmark crashing

### ISSUE THREAD

**Issue by sebas77** [dotnet/BenchmarkDotNet#1101]
The code doesn't crash outside the benchmarks, so I am trying to figure out what's going on. The Benchmarkdonet debugging option should surely be more intuitive, in fact I was expecting to be able to debug it from the project itself.
I think now I have figure out how to do it, but I get another problem. First of all I configure it in this way:

    [MonoJob()]
    [MaxWarmupCount(2)]
    [MaxIterationCount(2)]
    [MinWarmupCount(1)]
    [MinIterationCount(1)]
    [GroupBenchmarksBy(BenchmarkLogicalGroupRule.ByCategory)]

and

BenchmarkRunner.Run<ArrayBenchmark>(new DebugBuildConfig());

second I put this in the global setup:

while(!System.Diagnostics.Debugger.IsAttached)
                Thread.Sleep(TimeSpan.FromMilliseconds(100));

however when I run the build I get

// ***** Failed to build in Parallel, switching to sequential build..   *****
// ***** Done, took 00:00:29 (29.35 sec)   *****
// Found 2 benchmarks:
//   ArrayBenchmark.StandardArrayInsert: Job-TUPGEH(BuildConfiguration=Debug, Toolchain=net472, MaxIterationCount=2, MaxWarmupIterationCount=2, MinIterationCount=1, MinWarmupIterationCount=1)
//   ArrayBenchmark.StandardArrayInsert: Job-BAGQKI(Runtime=Mono, MaxIterationCount=2, MaxWarmupIterationCount=2, MinIterationCount=1, MinWarmupIterationCount=1)

// Build Error: Standard output:

 Standard error:
 Time Elapsed 00:00:11.07
    2 Error(s)
    10 Warning(s)
C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\Microsoft.Common.CurrentVersion.targets(4203,5): error MSB3021: Unable to copy file "obj\Debug\net472\FasterDictionaryBenchmarks.exe" to "bin\Debug\net472\FasterDictionaryBenchmarks.exe". The process cannot access the file 'd:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\bin\Debug\net472\FasterDictionaryBenchmarks.exe' because it is being used by another process. [d:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\FasterDictionaryBenchmarks.csproj]

please advise

(not I am not sure why it uses the latest preview SDK and if it's a bad thing)

**Comment by adamsitnik** [comment]
Hi @sebas77 

You are getting an error in the host process that is trying to build the benchmarking process but fails due file in use exception.

```log
The process cannot access the file 'd:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\bin\Debug\net472\FasterDictionaryBenchmarks.exe' because it is being used by another process. 
```

could you try to remove `bin\Debug\net472\FasterDictionaryBenchmarks.exe` and try again?

**Comment by sebas77** [comment]
yes I noticed and tried that, I delete the whole folder, built again, run and happens again.

**Comment by sebas77** [comment]
moreover the actual crash is inside mono.exe

**Comment by adamsitnik** [comment]
could you try to set UseSharedCompilation to false in your project with benchmarks?

```xml
<UseSharedCompilation>false</UseSharedCompilation>
```

**Comment by sebas77** [comment]
yes better, now the benchmarks run, but I still get weird errors:

 Standard error:
 Time Elapsed 00:00:11.33
    2 Error(s)
    10 Warning(s)
C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\Microsoft.Common.CurrentVersion.targets(4374,5): error MSB3021: Unable to copy file "d:\Robocraft\Svelto\Svelto.Benckmarks\Svelto.Common\bin\Debug\netstandard2.0\Svelto.Common.dll" to "bin\Debug\net472\Svelto.Common.dll". The process cannot access the file 'd:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\bin\Debug\net472\Svelto.Common.dll' because it is being used by another process. [d:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\FasterDictionaryBenchmarks.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\Microsoft.Common.CurrentVersion.targets(4374,5): error MSB3027: Could not copy "d:\Robocraft\Svelto\Svelto.Benckmarks\Svelto.Common\bin\Debug\netstandard2.0\Svelto.Common.dll" to "bin\Debug\net472\Svelto.Common.dll". Exceeded retry count of 10. Failed.  [d:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\FasterDictionaryBenchmarks.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\Microsoft.Common.CurrentVersion.targets(4374,5): warning MSB3026: Could not copy "d:\Robocraft\Svelto\Svelto.Benckmarks\Svelto.Common\bin\Debug\netstandard2.0\Svelto.Common.dll" to "bin\Debug\net472\Svelto.Common.dll". Beginning retry 10 in 1000ms. The process cannot access the file 'd:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\bin\Debug\net472\Svelto.Common.dll' because it is being used by another process.  [d:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\FasterDictionaryBenchmarks.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\Microsoft.Common.CurrentVersion.targets(4374,5): warning MSB3026: Could not copy "d:\Robocraft\Svelto\Svelto.Benckmarks\Svelto.Common\bin\Debug\netstandard2.0\Svelto.Common.dll" to "bin\Debug\net472\Svelto.Common.dll". Beginning retry 9 in 1000ms. The process cannot access the file 'd:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\bin\Debug\net472\Svelto.Common.dll' because it is being used by another process.  [d:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\FasterDictionaryBenchmarks.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\Microsoft.Common.CurrentVersion.targets(4374,5): warning MSB3026: Could not copy "d:\Robocraft\Svelto\Svelto.Benckmarks\Svelto.Common\bin\Debug\netstandard2.0\Svelto.Common.dll" to "bin\Debug\net472\Svelto.Common.dll". Beginning retry 8 in 1000ms. The process cannot access the file 'd:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\bin\Debug\net472\Svelto.Common.dll' because it is being used by another process.  [d:\Robocraft\Svelto\Svelto.Benckmarks\FasterDictionaryBenchmarks\FasterDictionaryBenchmarks.csproj]

**Comment by adamsitnik** [comment]
It looks like you got the same error, but for different .dll. Could you apply this setting to all projects?

**Comment by sebas77** [comment]
of course, why do you think this happens?

**Comment by sebas77** [comment]
it's mono holding the process
![image](https://user-images.githubusercontent.com/945379/54430317-1e53ac80-471b-11e9-93eb-a9e71c22b34c.png)

**Comment by adamsitnik** [comment]
could you kill mono.exe and see if it helps?

From your logs I can see that you fail to build the benchmark process, the thing is that we don't use mono for that. We use it in the next step to run the built program. It looks like mono is holding if from previous run?

**Comment by sebas77** [comment]
yes done. with the property used everywhere there are no more errors and I can now attach the debugger. What you say may be right about mono, as the crash I need to debug is happening inside mono.

**Comment by adamsitnik** [comment]
great, I am glad I was able to help. However I don't have any experience with debugging Mono so I can't help you with that ;(

**Comment by sebas77** [comment]
the property change was the solution for the crash too, although now it's crashing after the global cleanup. I will try to find out why.

**Comment by sebas77** [comment]
ok cool it's something in the code now, thanks for the help!
