### ISSUE TITLE
Allow user defined namespace filter for InliningDiagnoser

### ISSUE THREAD

**Issue by Zhentar** [dotnet/BenchmarkDotNet#1106]
When I'm working on something that I want to optimize & test with BenchmarkDotNet, I usually set up a solution with a pair of projects, with a library DLL that I'm testing & a console app test harness that runs BenchmarkDotNet. Unfortunately this means my benchmarks are by default in a different namespace than the code I want to test; it would be convenient if I could choose which namespace is used by the InliningDiagnoser to filter inlining messages.

**Comment by adamsitnik** [comment]
@Zhentar good idea, I have marked it as up for grabs. Hopefully someone is going to implement it soon (it should be easy)

**Comment by MarekM25** [comment]
@adamsitnik, @AndreyAkinshin, could I give it a try?

**Comment by AndreyAkinshin** [comment]
@MarekM25 sure!
