### ISSUE TITLE
DisassemblyDiagnoser assumes indentation uses spaces

### ISSUE THREAD

**Issue by Zhentar** [dotnet/BenchmarkDotNet#1110]
The carets don't line up right if you use tabs:
```cs
       			Span<ulong> acc = stackalloc ulong[8];
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       			acc[0] = seed;
   ^^^^^^^^^^^^^^
```

(if you look carefully, you can also see a second issue here - at least for the markdown formatter, the code gets indented with 7 spaces in addition to the pre-existing indentation, while the carets do not)

**Comment by AndreyAkinshin** [comment]
@Zhentar thanks for the report. The fix will be available in BenchmarkDotNet v0.11.5.
