### ISSUE TITLE
Should we exclude outliers from the overhead?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1116]
I just had a conversation with @AndyAyersMS and Andy asked if we remove the outliers from the overhead.

I did check our code and it looks like we don't:

https://github.com/dotnet/BenchmarkDotNet/blob/52eca7a626599fc1a2fab68b37c8aca77a65b6f2/src/BenchmarkDotNet/Engines/RunResults.cs#L40

Andy has run into a case where it would make a lot of sense:

```log
1.69
1.65
1.70
1.83
2.60 <-- an outlier -->
1.76
1.69
1.69
1.73
1.64
1.66
1.67
1.71
1.68
1.64
```

@AndreyAkinshin I think that we should remove the outliers from the Overhead. Do you agree?

**Comment by AndreyAkinshin** [comment]
@adamsitnik thanks for report, it's a good point. However, I decided that it will be better to just use Median instead of Mean.

**Comment by adamsitnik** [comment]
> Median instead of Mean

the simplest solutions are always the best! thanks!
