### ISSUE TITLE
MemoryDiagnoserAttribute on methods

### ISSUE THREAD

**Issue by Rizzen** [dotnet/BenchmarkDotNet#1119]
I noticed that ```MemoryDiagnoserAttribute``` has no ```AttributeUsage``` restrictions. But it works only when placed on class. In case of wrong usage benchmark runs with no errors or warnings but produces no memory diagnoser output.
Example of such usage:
``` C#
public class Bench
{
    [Benchmark]
    [MemoryDiagnoser]
    public int Method() => 100;
}
```
I believe it's a bit confusing and might be improved by restricting ```MemoryDiagnoserAttribute``` usage on class.
@adamsitnik @AndreyAkinshin what do you think?

**Comment by AndreyAkinshin** [comment]
@Rizzen it's a good idea! Do you want to create a pull request?

**Comment by Rizzen** [comment]
Sure!

**Comment by adamsitnik** [comment]
@Rizzen great catch! it explains one of the mysterious bugs I have seen few times but did not understand
