### ISSUE TITLE
Tiered Jit Benchmarking

### ISSUE THREAD

**Issue by yahorsi** [dotnet/BenchmarkDotNet#1125]
Hi

I just wonder is that possible at all to benchmark code jitted as non optimised vs fully optimized?
Like in 1st case as baseline I'd like code to be jitted with no any optimizations, just like it is produced when app it just started and then against fully optimized just to make sure, and to understand, how faster optimized code is.

Thanks

**Comment by AndreyAkinshin** [comment]
@yahorsi why do want to benchmark unoptimized code? What kind of valuable information do you want to get? How do you plan to use this information?
It's possible to benchmark unoptimized code with BenchmarkDotNet, but this feature is disabled by default because the corresponding results are not relevant to the actual application performance. E.g., some microbenchmarks can work ~100 times slower in the DEBUG mode than in the RELEASE mode because runtime emits a lot of instructions which are required by the debugger.

**Comment by yahorsi** [comment]
> @yahorsi why do want to benchmark unoptimized code? What kind of valuable information do you want to get? How do you plan to use this information?

By unoptimized code I mean unoptimized by jit compiler, not by C# compiler.
Main use case for such scenario os to understand how good/faster code is produced by tiered jit. I bet there are scenarios when tiered jid will produce code that is actually worse than non optimized.

**Comment by AndreyAkinshin** [comment]
@yahorsi ok, now I get it, you want to compare performance results for different JIT tiers. I'm not sure that it's correct to call the first tier of the JIT "unoptimized code." Each tier of the JIT-compiler can work in both optimized and unoptimized mode. The first tier doesn't produce very smart native code, but it doesn't mean that it's "unoptimized code" in general case because optimizations can be enabled or disabled.

Currently, it's impossible to compare different tiers with the help of BenchmarkDotNet because we can't control the tier for each method. I guess we need some advanced API for that on the CoreCLR/CoreFX side.

**Comment by yahorsi** [comment]
> because we can't control the tier for each method

Well, then we cannot compare apples to apples. We don't know how the target method will be optimized and simply cant compare. Looks like that is what's going on in my benchmark

**Comment by AndreyAkinshin** [comment]
When tiered jitting is enabled, it's a good idea to manually increase the total number of warmup iterations to be sure that we use the last tier everywhere. I will think what can we don on the BenchmarkDotNet side, to improve the user experience.

**Comment by yahorsi** [comment]
> that we use the last tier everywhere.

Tooo what?

I actually was trying to do this and in samples found SimpleJob, but, I didn't find any docs on SimpleJob and it members and have no idea what's are the best values to force the benchmark to run on most optimized jitted code.
And, there is ShortRunJob that is not documented as well. Just 1 QA without mentioning what these 2 guys are

**Comment by AndreyAkinshin** [comment]
Yeah, there’s room for improvement in the documentation.
`SimpleJob` allows setting the number of warmup iterations as follows:
```cs
[SimpleJob(warmupCount: 100)]
```

**Comment by yahorsi** [comment]
warmupCount is more or less easy to understand :)
How about others, like targetCount, invocationCount and launchCount? :)

Do you think 100 for warmupCount will be enouth?

**Comment by AndreyAkinshin** [comment]
You can find a description of these terms here: https://benchmarkdotnet.org/articles/guides/how-it-works.html

> Do you think 100 for warmupCount will be enough?

I hope so. =) By default, BenchmarkDotNet performs only 15 warmup iteration, but this number may be increased if observed measurements are "not stable enough".

**Comment by yahorsi** [comment]
Well, as I understand:
1. launchCount - How many times we create process. Once we have created process we
2. run warming up, count is defined in the warmupCount 
3. run benchmark , count is defined in the invocationCount 

But, what is targetCount? It is not mentioned on the article you mention

**Comment by AndreyAkinshin** [comment]
We had a huge renaming recently; however, we missed a few occurrences. =(
`TargetCount` or `IterationCount` is the number of actual iteration which will be measured (all warmup iterations don't affect results).
`invocationCount` is the number of benchmark method invocation inside each iteration.

**Comment by yahorsi** [comment]
Well I run my benchmark with manually set WithLaunchCount=1, WithWarmupCount=1000, WithInvocationCount=1000000 and for the case when tiered jit is enabled results are very different comparing to the run with default values. Basicly, for the tiered comp = 1 benchmark reports 0 durations.

**Comment by AndreyAkinshin** [comment]
> for the case when tiered jit is enabled results are very different comparing to the run with default values

Well, it should be a tiered jitting effect.

> Basicly, for the tiered comp = 1 benchmark reports 0 durations.

What do you mean?

**Comment by yahorsi** [comment]
> What do you mean?

Ignore
The outcome of the todays research is following:
Currently DotnetBenchmark produces the results that cannot be trusted because it does not explicitly control how code is jitted. Number of warmup iterations may vary from benchmark to benchmark and from run to run and that, currently, significantly affects code performance. One benchmark could be jitted with minimum optimisations, another with more optimisations. If current .NET Core does not allows to set the tier explicitly then IMHO it must be raised as an seriouse issue as does not allow to build robust benchmarks.

**Comment by AndreyAkinshin** [comment]
> If current .NET Core does not allows to set the tier explicitly then IMHO it must be raised as an seriouse issue as does not allow to build robust benchmarks.

Agree, I will try to figure out how to resolve this problem. Currently, BenchmarkDotNet should work fine on stable versions of the .NET Core (In .NET Core 2.x, the tiered jitting is disabled by default; .NET Core 3.0 is not released yet). However, we definitely should find a solution before .NET Core 3.0 is released.

**Comment by Mrnikbobjeff** [comment]
I have looked into Tiered Compilation, here is some Information I could gather:
Typical slot value transitions when tiered compilation is enabled:
- Initially, the slot contains the method's temporary entry point, which always points to the prestub
- After the tier 0 JIT completes, the slot is transitioned to the tier 0 entry point, and the slot is recorded for backpatching
- When tiered compilation decides to begin counting calls for the method, the slot is transitioned to the temporary entry point (call counting currently happens in the prestub)
- When the call count reaches the tier 1 threshold, the slot is transitioned to the tier 0 entry point and a tier 1 JIT is scheduled
- After the tier 1 JIT completes, the slot is transitioned to the tier 1 entry point

To determine whether a method is elligable for tiered compilation: 
- It can not be zapped (Functional requirement) NGEN images embed direct calls that we would be unable to detect and redirect
- The profiler has not given the command to disable tiered compilation
- Not debug mode
- If quick JIT is disabled for the startup tier and the module is not ReadyToRun the method would not be tiered currently, making it inelligable for tiering
- Is a native method (obviously)
Gleaming over ICorProfiler and the [Code Versioning Spec](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/code-versioning.md) it seems we can gather information about the current version of the method invoked. This is definitely doable with the information provided, but it sure will be a challenge to get right.

**Comment by AndreyAkinshin** [comment]
It seems that the tiered jitting is not such a big issue since .NET Core 3.0 preview 4 (after https://github.com/dotnet/coreclr/pull/23599 was merged). I close this issue but feel free to create a new one if you notice any problems with tiered jitting on .NET Core 3.0 preview 6+. Also, you can track https://github.com/dotnet/coreclr/issues/25680 for further discussion about BenchmarkDotNet and tiered jitting.

**Comment by EgorBo** [comment]
@AndreyAkinshin btw, QuickJit is enabled by default again (see https://github.com/dotnet/coreclr/pull/24576) 🙂 even if it's disabled you still should see some fluctuations because of R2R vs tier1.

**Comment by AndreyAkinshin** [comment]
@EgorBo in my experiments I have fluctuations during the warmup stage. I'm curious if it's possible to get a noticeable impact on the actual iterations.

**Comment by EgorBo** [comment]
I guess in general R2R code is as fast as IL-to-tier1 but there can be differences, e.g. R2R doesn't use the System.Runtime.Intrinsics API (it's used in some BCL stuff under the hood). so e.g. you benchmark some code and at some point (at the 30th iteration) it recompiles that R2R code, enables intrinsics and the code becomes a bit faster.

**Comment by yahorsi** [comment]
Ideally, we need a way to explicitly tell how to jit the benchmark. E.g. imagine you have benchmarked code being jitted using tier X and on production it is actually jitted using tier Y, results might be very different...

**Comment by AndreyAkinshin** [comment]
@yahorsi for such a feature, we need the corresponding API on the runtime side. I already asked a similar question in this issue: https://github.com/dotnet/coreclr/issues/25680 (please, use it for further discussions).
