### ISSUE TITLE
[Question] 2 different Benchmarks with 2 different environment variables

### ISSUE THREAD

**Issue by lydonchandra** [dotnet/BenchmarkDotNet#1128]
Trying to benchmark a function, drawManaged(), running under two different DLLs:

    drawManaged() function in C#
    drawManaged() calls drawNative() in native1base.dll (or other native dlls) through swig-interface
    which native DLL to load is configurable using environmental variables, %NATIVE_DLL_PATH%
    want to benchmark drawManaged() running in 2 different native DLL: native1base.dll and native2optimized.dll

how can I do this using benchmarkdotnet ?

also posted in https://stackoverflow.com/questions/55508994/2-different-benchmarks-with-2-different-environment-variables

**Comment by AndreyAkinshin** [comment]
@lydonchandra sorry for the late reply. I see that you already got an [answer](https://stackoverflow.com/a/55892005/184842) on StackOverflow. Did it resolve your problem?

**Comment by lydonchandra** [comment]
Yes it did thamks
