### ISSUE TITLE
The power management feature extension

### ISSUE THREAD

**Issue by MarekM25** [dotnet/BenchmarkDotNet#1132]
As I mentioned earlier (https://github.com/dotnet/BenchmarkDotNet/pull/952#issuecomment-447627638) we could extend our power management feature. Currently, we have two values in enum: HighPerformancePowerPlan and UserDefinedPowerPlan. We could also add there two popular power plans: balanced and power saver. Additionally, it will be simple to allow setting power mode by the custom GUID. It could be valuable when someone wants to target their app to the specific device which power mode is known, for example, a laptop usually only on battery or mobile phone.

What do you think? Is it possible that someone has a benefit from this feature? If it sounds useful, I will enjoy implementing it.

**Comment by adamsitnik** [comment]
@MarekM25 I like this idea! Please send a PR and tag me when you need the review

**Comment by adamsitnik** [comment]
Fixed by #1139
