### ISSUE TITLE
The default file logger and summary title are out of sync

### ISSUE THREAD

**Issue by Darcara** [dotnet/BenchmarkDotNet#1135]
Affected Versions 11.5 and nightly 11.5.1068

I want to archive the automatically created log file (type-timestamp.log), but I cannot find the name anywhere in config or summary. There is `summary.Title` but it's timestamp is always a few seconds off. I'm using a config derived from `ManualConfig `and adding `DefaultConfig.Instance` manually.

I tried using a `StreamLogger `but ran into #1134

I tried working around that using the `PlainExporter` but that is missing a lot of information, most notably the summary and diagnostic output.

**Comment by adamsitnik** [comment]
Hello @Darcara 

> but it's timestamp is always a few seconds off

This is expected because when you run benchmarks for multiple types, we produce a summary per type but only a single log file.

I have extended the Summary type with `LogFilePath` property, I hope that it's going to solve the problem.
