### ISSUE TITLE
[Discussion] Improve search experience in the documentation

### ISSUE THREAD

**Issue by Ant-hem** [dotnet/BenchmarkDotNet#1137]
Hi team :wave:,

I am member of the .NET foundation and I am working at Algolia on a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [brew](https://brew.sh/), [Bootstrap](https://getbootstrap.com/), [React](https://reactjs.org/) or [jQuery](https://jquery.com/).

I have created [a preview of the search experience](https://docsearch-benchmarkdotnet.netlify.com/) and what DocSearch on the BenchmarkDotNet
website could will look like here. Feel free to try it and let us know what you think. Please not the learn-as-you-type experience and the typo tolerance:

[![demo of DocSearch + benchmarkdotnet](https://cl.ly/c32b07e9cfaa/download/Screen%20Recording%202019-04-23%20at%2001.29%20PM.gif)](https://docsearch-benchmarkdotnet.netlify.com/)

The way DocSearch works is by crawling your content, pushing the results into an Algolia index, and then requesting this index directly from the website front-end through JavaScript.

We'll take care of crawling your website and populating the Algolia index with the latest changes every 24h for you. You don't need to change anything to your deployment process. The only thing you need to add are the following CSS and JS snippets that will bind the dropdown to your searchbox.

We built DocSearch with the idea of giving back to the Open-Source community. This is why your [crawling configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/benchmarkdotnet.json) is available on GitHub if you want to change it. We also have our own [documentation](https://community.algolia.com/docsearch/documentation/) to help you tweak the dropdown to your needs. You'll also have access to *analytics on the most searched terms* or those with *no results*. All of this is of course *entirely free*.

**Comment by AndreyAkinshin** [comment]
Hello @Ant-hem!

Thank you very much for this issue, search in your live preview works super fast! It will be awesome to integrate it with our official docs! I have only one concern about the search results: sometimes it doesn't include some important pages. Let's try to search for "orderers". Here is the current search output:
![image](https://user-images.githubusercontent.com/2259237/57080599-7eb6a180-6cfb-11e9-8d36-21edff993340.png)
As you can see, it found the "Orderers" page. And here is the output in your live demo:
![image](https://user-images.githubusercontent.com/2259237/57080650-9ee66080-6cfb-11e9-9c49-0c40d66b1632.png)
However, we have the index for the "Article" pages:
![image](https://user-images.githubusercontent.com/2259237/57080732-cb9a7800-6cfb-11e9-9be2-a1403e69e001.png)

If we can resolve this problem somehow, I will be happy to accept a PR with DocSearch integration!

**Comment by s-pace** [comment]
👋 @AndreyAkinshin ,

Sure done [thanks to this update](https://github.com/algolia/docsearch-configs/commit/8ab1f7d5aa05649d86aea18e14d2e36656fae248). Feel free to [provide us a sitemap](https://community.algolia.com/docsearch/tips.html#use-a-sitemapxml) so that we do not miss anything.

Can you point us out a repo on which we can offer you a PR. We need to be able to build the html pages.

🚀

**Comment by AndreyAkinshin** [comment]
@Ant-hem, @s-pace sitemap.xml is ready (URL: https://benchmarkdotnet.org/sitemap.xml, source: https://github.com/dotnet/BenchmarkDotNet/blob/gh-pages/sitemap.xml)

We keep docs sources in this repo and use [docfx](https://dotnet.github.io/docfx/) to build it.
Here is the template for page headers: https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/template/partials/head.tmpl.partial
See also: https://benchmarkdotnet.org/articles/contributing/documentation.html

**Comment by s-pace** [comment]
PR done https://github.com/dotnet/BenchmarkDotNet/pull/1148 @AndreyAkinshin cc @shipow @adamsitnik

**Comment by AndreyAkinshin** [comment]
Resolved in #1148

**Comment by AndreyAkinshin** [comment]
@Ant-hem it's already live!
