### ISSUE TITLE
Benchmarkdotnet not respecting framework target net462

### ISSUE THREAD

**Issue by thulani-chivandikwa** [dotnet/BenchmarkDotNet#1140]
I have a small benchmark project that is targeting netcoreapp2 and net462.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2;net462</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.11.5" />
  </ItemGroup>

</Project>
```

However when running this benchmark it only seems to respect the netcoreapp target and not the full framework one. It states that the CLR job was run targeting net472. Could I be doing this wrong or is this an issue? I have targeted only two jobs [CoreJob, ClrJob].

>   [Host] : .NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT
>   Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3394.0
>   Core   : .NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT

**Comment by thulani-chivandikwa** [comment]
I have also noticed that even if I remove the explicit job attributes and only target my project to net462 the run summary still shows it executes with net472.

**Comment by thulani-chivandikwa** [comment]
After asking on SO someone pointed out that unlike .net core the full framework does not have side by side installs but a runtime that is upgraded in place. So even with net462 but having 4.7.2 installed means that will be the runtime. Makes sense.

**Comment by adamsitnik** [comment]
This is the default behaviour of Full .NET Framework. No matter what version your app targets, it's always executed with the latest .NET Runtime installed on your machine.

You can test it with following example

```cs
void Main() => System.Console.WriteLine(Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.FrameworkDescription);
```
