### ISSUE TITLE
Should the tests not be targeting all the supported runtimes?

### ISSUE THREAD

**Issue by thulani-chivandikwa** [dotnet/BenchmarkDotNet#1141]
I think the tests and samples should multi-target to all the supported runtimes. This may be useful in picking up any issues with a specific platform early.

Ideally I think the tests should have:
`<TargetFrameworks>net461;netcoreapp2.0;netcoreapp2.1;netcoreapp2.2</TargetFrameworks>`

I could not see how to add a question flair for this issue, it is possible on creating a new issue or only reviewers can do this?

**Comment by AndreyAkinshin** [comment]
Hello @thulani-chivandikwa!

Currently, both tests and samples target `net461;netcoreapp2.0;netcoreapp2.1`. Thus, you are suggesting to add `netcoreapp2.2` to this list. Do you have any specific use cases when it will be useful? Additional target framework increases the project processing time in IDEs (VS/Rider) which may slow down the development process. It's OK to add `netcoreapp2.2` if we really need it, but I don't want to do it for no reason.

**Comment by adamsitnik** [comment]
@AndreyAkinshin .NET Core 2.0 has reached the end of life: https://dotnet.microsoft.com/platform/support/policy/dotnet-core Maybe we should target .NET Core 2.1 only in the tests and samples project and add 3.0 when it's shipped?

**Comment by AndreyAkinshin** [comment]
@adamsitnik, yes, it makes sense. I removed netcoreapp2.0 in 6f91ea59474bf6cce2d7ff8de422854cb4a61b06
@thulani-chivandikwa I close this issue since we don't have any reasons to add additional TFMs in test projects. If you find some use cases which shows that we really need additional TFMs, please let me know.
