### ISSUE TITLE
Only the first of multiple custom columns is included in the summary table

### ISSUE THREAD

**Issue by BACONputing** [dotnet/BenchmarkDotNet#1146]
I am using `BenchmarkDotNet` v0.11.5 with `[Host] : .NET Core 2.1.9 (CoreCLR 4.6.27414.06, CoreFX 4.6.27415.01), 64bit RyuJIT`.  I have written a class implementing `IColumn` and if I add multiple instances of it to an `IConfig` then only the first column added is present in the summary table.  If I change the order in which the columns are added, then only the new first column is shown.

I am seeing the same behavior with the [`IntroTagColumn` sample](https://benchmarkdotnet.org/articles/configs/columns.html#sample-introtagcolumn).  Here is the code I am running (the same as the sample except with a `Program` class added)...

    using System.Threading;
    using BenchmarkDotNet.Attributes;
    using BenchmarkDotNet.Columns;
    using BenchmarkDotNet.Configs;
    using BenchmarkDotNet.Jobs;

    namespace BenchmarkDotNet.Samples
    {
        // You can add custom tags per each method using Columns
        [Config(typeof(Config))]
        public class IntroTagColumn
        {
            private class Config : ManualConfig
            {
                public Config()
                {
                    Add(Job.Dry);
                    Add(new TagColumn("Kind", name => name.Substring(0, 3)));
                    Add(new TagColumn("Number", name => name.Substring(3)));
                }
            }

            [Benchmark]
            public void Foo1() => Thread.Sleep(10);

            [Benchmark]
            public void Foo12() => Thread.Sleep(10);

            [Benchmark]
            public void Bar3() => Thread.Sleep(10);

            [Benchmark]
            public void Bar34() => Thread.Sleep(10);
        }

        public static class Program
        {
            public static void Main()
            {
                BenchmarkDotNet.Running.BenchmarkRunner.Run<IntroTagColumn>();
            }
        }
    }

The [sample output](https://benchmarkdotnet.org/articles/configs/columns.html#output) shows `Kind` and `Number` columns, yet I'm seeing this...

    | Method |     Mean | Error | Kind |
    |------- |---------:|------:|----- |
    |   Foo1 | 12.03 ms |    NA |  Foo |
    |  Foo12 | 12.08 ms |    NA |  Foo |
    |   Bar3 | 11.99 ms |    NA |  Bar |
    |  Bar34 | 11.61 ms |    NA |  Bar |

If I change the order the columns are added in the `Config` constructor to this...

    public Config()
    {
        Add(Job.Dry);
        Add(new TagColumn("Number", name => name.Substring(3)));
        Add(new TagColumn("Kind", name => name.Substring(0, 3)));
    }

...then I get this summary...

    | Method |     Mean | Error | Number |
    |------- |---------:|------:|------- |
    |   Foo1 | 11.71 ms |    NA |      1 |
    |  Foo12 | 11.30 ms |    NA |     12 |
    |   Bar3 | 11.55 ms |    NA |      3 |
    |  Bar34 | 12.10 ms |    NA |     34 |

I have also tried...

- Using a different-but-identically-implemented class for each column instance (thinking that maybe only one column of a given type is allowed)
- Passing all column instances as multiple parameters to `Add()` instead of one instance per call
- Using `With()` instead of `Add()`
- Returning different values from the `IColumn.Priority` property
- Returning `ColumnCategory.Params` instead of `ColumnCategory.Custom` from the `IColumn.Category` property (since my column returns a value based on `benchmarkCase.Parameters` - this only moved the column, if displayed, from the end to right after `Method`)
- Returning `true` from the `IColumn.IsDefault` property

...but get the same results.

**Comment by AndreyAkinshin** [comment]
@BACONputing thanks for the report! The fix will be available in v0.11.6. It was a bug in the `TagColumn` implementation, other custom columns should work fine. As a temporary workaround, you can copy-paste the fixed `TagColumn` implementation from here: https://github.com/dotnet/BenchmarkDotNet/blob/9065c7305e00881b11d31606a698fda08dc30a7d/src/BenchmarkDotNet/Columns/TagColumn.cs
