### ISSUE TITLE
Update benchmark switcher instructions to work on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/BenchmarkDotNet#1147]
It currently outputs:
```
You can also provide the class name in console arguments by using --filter. (e.g. '--filter *Program*'):
```
but on Linux the `*Program*` needs to be surrounded by quotes.

**Comment by AndreyAkinshin** [comment]
@stephentoub thanks for the report; the fix will be available in BenchmarkDotNet v0.11.6.

---
Related: #842, https://github.com/dotnet/BenchmarkDotNet/commit/1b805115f6e4558208b69fa2e55edc8d46a0f556
