### ISSUE TITLE
Ambiguous hour component in log file name timestamp

### ISSUE THREAD

**Issue by BACONputing** [dotnet/BenchmarkDotNet#1149]
I noticed that the `.log` file created in the `BenchmarkDotNet.Artifacts` directory uses a 12-hour clock for hours.  For example, I just ran a benchmark at 1:50 PM and the resulting log file is named `MyProject.Benchmarks-20190510-015028.log` instead of `MyProject.Benchmarks-20190510-135028.log`.

**Comment by AndreyAkinshin** [comment]
@BACONputing thanks for the report. The fix will be available in BenchmarkDotNet v0.11.6.
