### ISSUE TITLE
Order of parameter columns changes with different Params* attribute usage

### ISSUE THREAD

**Issue by BACONputing** [dotnet/BenchmarkDotNet#1150]
In trying to force an `enum` parameter to be output in an order different than that of the `enum` values (which I think might be #660) I found that the order of the parameter columns in the summary table is not consistent between different usages of the `Params`, `ParamsAllValues`, and `ParamsSource` attributes.  For example, with this code...

    using BenchmarkDotNet.Attributes;

    public enum SomeEnum
    {
        First,
        Second,
        Third
    }

    [DryJob()]
    public class Benchmarks
    {
        [Params(1, 10, 100)]
        public int X
        {
            get; set;
        }

        [ParamsAllValues()]
        public SomeEnum Y
        {
            get; set;
        }

        [Benchmark()]
        public void Method1()
        {
        }

        [Benchmark()]
        public void Method2()
        {
        }
    }

    static class Program
    {
        static void Main()
        {
            BenchmarkDotNet.Running.BenchmarkRunner.Run<Benchmarks>();
        }
    }

...I get this output (`Mean` and `Error` columns omitted)...

    |  Method |   X |      Y |
    |-------- |---- |------- |
    | Method1 |   1 |  First |
    | Method2 |   1 |  First |
    | Method1 |   1 | Second |
    | Method2 |   1 | Second |
    | Method1 |   1 |  Third |
    | Method2 |   1 |  Third |
    | Method1 |  10 |  First |
    | Method2 |  10 |  First |
    | Method1 |  10 | Second |
    | Method2 |  10 | Second |
    | Method1 |  10 |  Third |
    | Method2 |  10 |  Third |
    | Method1 | 100 |  First |
    | Method2 | 100 |  First |
    | Method1 | 100 | Second |
    | Method2 | 100 | Second |
    | Method1 | 100 |  Third |
    | Method2 | 100 |  Third |

In most cases that's the output I get, however if I change `Y` from a property to a field and apply the `[Params(...)]` attribute...

    [Params(SomeEnum.First, SomeEnum.Second, SomeEnum.Third)]
    public SomeEnum Y;

...then the two parameter columns get swapped...

    |  Method |      Y |   X |
    |-------- |------- |---- |
    | Method1 |  First |   1 |
    | Method2 |  First |   1 |
    | Method1 |  First |  10 |
    | Method2 |  First |  10 |
    | Method1 |  First | 100 |
    | Method2 |  First | 100 |
    | Method1 | Second |   1 |
    | Method2 | Second |   1 |
    | Method1 | Second |  10 |
    | Method2 | Second |  10 |
    | Method1 | Second | 100 |
    | Method2 | Second | 100 |
    | Method1 |  Third |   1 |
    | Method2 |  Third |   1 |
    | Method1 |  Third |  10 |
    | Method2 |  Third |  10 |
    | Method1 |  Third | 100 |
    | Method2 |  Third | 100 |

I get the same result when `[ParamsSource(...)]` is applied to `X` and `Y` is a property or field with the `[Params(...)]` attribute...

    public static int[] XValues { get; } = new[] { 1, 10, 100 };

    [ParamsSource(nameof(XValues))]
    public int X
    {
        get; set;
    }

    [Params(SomeEnum.First, SomeEnum.Second, SomeEnum.Third)]
    public SomeEnum Y
    {
        get; set;
    }

...or when `[ParamsSource(...)]` is applied to `X` and `Y` is a field with the `[ParamsSource(...)]` attribute...

    public static int[] XValues { get; } = new[] { 1, 10, 100 };

    [ParamsSource(nameof(XValues))]
    public int X
    {
        get; set;
    }

    public static SomeEnum[] YValues { get; } = new[] { SomeEnum.First, SomeEnum.Second, SomeEnum.Third };

    [ParamsSource(nameof(YValues))]
    public SomeEnum Y;

Here's a summary of the different permutations and the resulting column order...

| X member type |    X attribute   | Y member type |     Y attribute     | Parameter columns |
|:-------------:|:----------------:|:-------------:|:-------------------:|:-----------------:|
|    Property   |    `Params()`    |    Property   | `ParamsAllValues()` |        X, Y       |
|    Property   |    `Params()`    |     Field     | `ParamsAllValues()` |        X, Y       |
|    Property   |    `Params()`    |    Property   |      `Params()`     |        X, Y       |
|    Property   |    `Params()`    |     Field     |      `Params()`     |      **Y, X**     |
|    Property   |    `Params()`    |    Property   |   `ParamsSource()`  |        X, Y       |
|    Property   |    `Params()`    |     Field     |   `ParamsSource()`  |        X, Y       |
|    Property   | `ParamsSource()` |    Property   | `ParamsAllValues()` |        X, Y       |
|    Property   | `ParamsSource()` |     Field     | `ParamsAllValues()` |        X, Y       |
|    Property   | `ParamsSource()` |    Property   |      `Params()`     |      **Y, X**     |
|    Property   | `ParamsSource()` |     Field     |      `Params()`     |      **Y, X**     |
|    Property   | `ParamsSource()` |    Property   |   `ParamsSource()`  |        X, Y       |
|    Property   | `ParamsSource()` |     Field     |   `ParamsSource()`  |      **Y, X**     |

**Comment by adamsitnik** [comment]
Hi @BACONputing 

This is by design, there is no way of getting the information about Field/Properties declaration order in given type: https://stackoverflow.com/questions/5473455/c-sharp-get-fieldinfos-propertyinfos-in-the-original-order

I tried the approach described at https://stackoverflow.com/a/17998371

```cs
 public ParamsAttribute([CallerLineNumber]int order = 0, params object[] values)
```

But the problem are integer Params, for example:

```cs
public class TheType
{
    [Params(1, 2, 3)] // 1 is used as order, 2 & 3 become params
    public int First { get; set; }

    [Params(3, 2, 1)] // 1 is used as order, 2 & 3 become params
    public int Second;
```

I also tried overload for params of integers (hoping that the first integer would be passed as param, not order):

```cs
public ParamsAttribute([CallerLineNumber]int order = 0, params object[] values) : base(order)

public ParamsAttribute([CallerLineNumber]int order = 0, params int[] values) : base(order)
```

But I ended up with compiler error for `[Params(123)]`

```log
The call is ambiguous between the following methods or properties: 'ParamsAttribute.ParamsAttribute(int, params object[])' and 'ParamsAttribute.ParamsAttribute(int, params int[])'
```

I give up on this. If you want to give it a try the code that controls the order is here: https://github.com/dotnet/BenchmarkDotNet/blob/db3a8fc0e74229f14ffcc532e3d655256e38d559/src/BenchmarkDotNet/Running/BenchmarkConverter.cs#L165-L193

**Comment by JohannesDeml** [comment]
Sorry I'm resurrecting the issue again. I just hit the same limitation. Having some control of the order for params in the results would be great. Since it seems hard (or even not doable) to do this with their line definition order, how about giving the option to change the order manually?

My idea would be to intruduce a Property in the Params attributes like so:

```
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
    public class ParamsAttribute : Attribute
    {
        public int Order { get; set; } = 0;
        public object[] Values { get; }

        // CLS-Compliant Code requires a constructor without an array in the argument list
        public ParamsAttribute() => Values = new object[0];

        public ParamsAttribute(params object[] values)
            => Values = values ?? new object[] { null }; // when users do Params(null) they mean one, null argument
    }
```

Then you could do:
´´´
public class IntroParams
    {
        [Params(100, 200)]
        public int A { get; set; }
        
        // Make sure column B is before column A
        [Params(10, 20, Order = -100)]
        public int B { get; set; }

        [Benchmark]
        public void Benchmark() => Thread.Sleep(A + B + 5);
    }
´´´

Would that be an option?

**Comment by adamsitnik** [comment]
> Would that be an option?

@JohannesDeml yes, as long as you are willing to work on this and provide a PR ;)

**Comment by JohannesDeml** [comment]
@adamsitnik Sounds good to me, even though it might take me some time.
Here are some quick thoughts after evaluating the task.

## Attributes that can be ordered
* `ArgumentsAttribute`
* `ArgumentsSourceAttribute`
* `GenericTypeArgumentsAttribute`
* `ParamsAllValuesAttribute`
* `ParamsAttribute`
* `ParamsSourceAttribute`

I will start with Params*.

As for naming: I think `Oder` would b e a fitting name, but I noticed, that there is `IColumn.PriorityInCategory` which is kind of what the value results to in the end. So possible names would be `Order`, `ColumnOrder`, `Priority`, `PriorityInCategory`.

Is there a reason why `ParamsAllValuesAttribute` is not in BenchmarkDotNet.Annotations like the others or can I move the file?

**Comment by adamsitnik** [comment]
> GenericTypeArgumentsAttribute

I am not sure about this one as it affects the result class name:


```cs
[GenericTypeArgumentsAttribute(typeof(int))]
public class B<T>
```

is translated to a `B<int>` type by the runner

> Order, ColumnOrder, Priority

for me the best ones are `Order` and `Priority`. Perhaps as you have noticed it would be nice to be consistent with the existing naming (Priority).

>  Is there a reason why ParamsAllValuesAttribute is not in BenchmarkDotNet.Annotations like the others or can I move the file?

Great catch! It's most probably a mistake on our side, please move it.

Thank you for working on this!
Adam
