### ISSUE TITLE
How to read BenchmarkDotNet output?

### ISSUE THREAD

**Issue by juniormayhe** [dotnet/BenchmarkDotNet#1151]
Here is a piece of my output:
```
// AfterActualRun
WorkloadResult   1: 1 op, 219057201300.00 ns, 219.0572 s/op
WorkloadResult   2: 1 op, 218636850500.00 ns, 218.6369 s/op
WorkloadResult   3: 1 op, 218243751300.00 ns, 218.2438 s/op
WorkloadResult   4: 1 op, 219833440200.00 ns, 219.8334 s/op
WorkloadResult   5: 1 op, 218569013200.00 ns, 218.5690 s/op
WorkloadResult   6: 1 op, 219578847100.00 ns, 219.5788 s/op
WorkloadResult   7: 1 op, 217864016800.00 ns, 217.8640 s/op
WorkloadResult   8: 1 op, 218305837300.00 ns, 218.3058 s/op
WorkloadResult   9: 1 op, 218339590400.00 ns, 218.3396 s/op
WorkloadResult  10: 1 op, 218571199200.00 ns, 218.5712 s/op
WorkloadResult  11: 1 op, 218343199400.00 ns, 218.3432 s/op
WorkloadResult  12: 1 op, 218580669900.00 ns, 218.5807 s/op
WorkloadResult  13: 1 op, 218261187700.00 ns, 218.2612 s/op
WorkloadResult  14: 1 op, 219213553700.00 ns, 219.2136 s/op
WorkloadResult  15: 1 op, 218342389700.00 ns, 218.3424 s/op
GC:  3 1 0 10707640 1
```
Is it correct to say that this benchmark had 15 iterations (15 calls to target method)?
And since I am benchmarking a method that connects to a remote cache server to persist and read some information, each iteration took around 218 seconds ? Maybe due to network latency?

**Comment by AndreyAkinshin** [comment]
Hello @juniormayhe!

> Is it correct to say that this benchmark had 15 iterations (15 calls to target method)?

Yes, it's correct.

> each iteration took around 218 seconds?

Yes, it's also correct. You can find the full statistics and the summary table at the end of BenchmarkDotNet output.

> Maybe due to network latency?

Maybe.

**Comment by bitbonk** [comment]
But what does Workload*Result* tell me? As opposed to Workload*Actual*.

**Comment by bitbonk** [comment]
https://github.com/dotnet/BenchmarkDotNet/issues/1282
