### ISSUE TITLE
Failed to test Roslyn.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/BenchmarkDotNet#1152]
The source code is [here](https://github.com/NMSAzulX/BenchmarkRoslyn).

Can be used without benchmark testing. Is there another way to test roslyn?
![image](https://user-images.githubusercontent.com/16236903/57835238-ad9b4000-77f0-11e9-9950-30c1333ec538.png)

![image](https://user-images.githubusercontent.com/16236903/57835026-45e4f500-77f0-11e9-9e06-500ce90c9b8f.png)
![image](https://user-images.githubusercontent.com/16236903/57835107-73ca3980-77f0-11e9-9509-956707246947.png)

**Comment by adamsitnik** [comment]
Hello @NMSAzulX 

Thank you for a great repro case. I was able to reproduce it and fix it right away.

As soon as [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/24684299 build finishes the CI should produce a '0.11.5.1086' package which is going to be obtainable from the following feed:

```xml
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

If can wait, it's going to be a part of 0.11.6 release which should be published to nuget.org in a few weeks
