### ISSUE TITLE
Add a ConcurrencyDiagnoser?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/BenchmarkDotNet#1154]
.NET Core 3.0 adds several members that would be useful to be exposed for use with certain kinds of performance tests, e.g. Monitor.LockContentionCount and ThreadPool.CompletedWorkItemCount.  Would it make sense to add a ConcurrencyDiagnoser that exposed (end - start) reads of these?

**Comment by AndreyAkinshin** [comment]
@stephentoub it's a pretty interesting idea, I like it!
