### ISSUE TITLE
Workload Jitting takes very long time for F# async function

### ISSUE THREAD

**Issue by MikaelUmaN** [dotnet/BenchmarkDotNet#1159]
Hi.

I am microbenchmarking a matrix multiply algorithm. The single threaded version works fine. But the multithreaded version incurs a problematic delay in the "workload jitting" stage. Here is an example from my logs:

> // Benchmark: Benchmark.DivideAndConquerParallel: Core(Runtime=Core) [Size=1024, MinBlockSize=8]
> // *** Execute ***
> // Launch: 1 / 1
> // Execute: dotnet "31cb0608-0f43-48ba-b02f-5fdc354c2c10.dll" --benchmarkName "DivideAndConquerBenchmark+Benchmark.DivideAndConquerParallel(Size: 1024, MinBlockSize: 8)" --job "Core" --benchmarkId 9 in C:\Users\mikae\dev\MatrixMatrix\MatrixBenchmark\bin\Release\netcoreapp2.2\31cb0608-0f43-48ba-b02f-5fdc354c2c10\bin\Release\netcoreapp2.2
> // BeforeAnythingElse
> 
> // Benchmark Process Environment Information:
> // Runtime=.NET Core 2.2.4 (CoreCLR 4.6.27521.02, CoreFX 4.6.27521.01), 64bit RyuJIT
> // GC=Concurrent Workstation
> // Job: Core(Runtime=Core)
> 
> OverheadJitting  1: 1 op, 317700.00 ns, 317.7000 us/op
**> WorkloadJitting  1: 1 op, 5454393251000.00 ns, 90.9066 m/op**
> 
> WorkloadWarmup   1: 1 op, 16441209600.00 ns, 16.4412 s/op
> ...

The next run, using a size of 2048, doesn't complete.

The code is written like this:
```

namespace ManagedMultiply
module DivideConquerParallel =

    // Recursively computes matrix matrix multiply. Stops recursion at size T (should fit into L1 cache)
    let divideAndConquer  (A: float[]) (B: float[]) (C: float[]) (N: int) (T: int) =
        let rec divConquer (A: float[]) (B: float[]) (C: float[]) (N: int) (T: int) (n: int) (cr: int) (cc: int) (ar: int) (ac: int) (br: int) (bc: int) =
            if (n <= T) then
                // Base case, standard naive multiply
                ThreeLoops.multFlat A B C N n cr cc ar ac br bc
            else
                // Assume square matrix of size N, divisible by two.
                // Divide A,B,C into four blocks each.
                let n2 = n / 2

                //c00 = a00*b00 + a01*b10
                let c00 = async {
                    divConquer A B C N T n2 cr cc ar ac br bc
                    divConquer A B C N T n2 cr cc ar (ac+n2) (br+n2) bc
                }

                //c01 = a00*b01 + a01*b11
                let c01 = async {
                    divConquer A B C N T n2 cr (cc+n2) ar ac br (bc+n2)
                    divConquer A B C N T n2 cr (cc+n2) ar (ac+n2) (br+n2) (bc+n2)
                }

                //c10 = a10*b00 + a11*b10
                let c10 = async {
                    divConquer A B C N T n2 (cr+n2) cc (ar+n2) ac br bc
                    divConquer A B C N T n2 (cr+n2) cc (ar+n2) (ac+n2) (br+n2) bc
                }

                //c11 = a10*b01 + a11*b11
                let c11 = async { 
                    divConquer A B C N T n2 (cr+n2) (cc+n2) (ar+n2) ac br (bc+n2)
                    divConquer A B C N T n2 (cr+n2) (cc+n2) (ar+n2) (ac+n2) (br+n2) (bc+n2)
                }

                [c00; c01; c10; c11]
                |> Async.Parallel 
                |> Async.RunSynchronously
                |> ignore

        divConquer A B C N T N 0 0 0 0 0 0  
```

And the benchmark:

```
module DivideAndConquerBenchmark

open BenchmarkDotNet.Attributes
open BenchmarkDotNet.Running
open MathNet.Numerics
open MathNet.Numerics.Providers
open MathNet.Numerics.LinearAlgebra
open ManagedMultiply

[<CoreJob>]
type Benchmark() =

    let mutable A: float[] = null
    let mutable B: float[] = null
    let mutable C: float[] = null

    [<Params(2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048)>] //, 4096)>]
    member val Size = 0 with get, set

    [<Params(8)>]   //[<Params(4, 8, 16, 32, 64, 128, 256)>]
    member val MinBlockSize = 0 with get, set

    [<GlobalSetup>]
    member this.Setup() =
        let a = DenseVector.randomStandard<float> <| this.Size*this.Size // Unnecessary memory consumption...
        let b = DenseVector.randomStandard<float> <| this.Size*this.Size
        A <- a.AsArray()
        B <- b.AsArray()
        C <- Array.zeroCreate <| this.Size*this.Size

    [<Benchmark>]
    member this.DivideAndConquerParallel() =
        DivideConquerParallel.divideAndConquer A B C this.Size this.MinBlockSize
        C
```

How can I understand what's going on here? How can I control the execution so workload jitting does not take such a long time?

**Comment by adamsitnik** [comment]
Hello @MikaelUmaN 

The `WorkloadJitting 1: 1 op` means that the benchmarked code is executed once in order to JIT it and exclude JIT cost from the actual measurements taken later.

> But the multithreaded version incurs a problematic delay in the "workload jitting" stage

How long does it take to run the multithreaded version with Size=2048 without BenchmarkDotNet involved? 

Most probably it just takes a lot of time to execute, there is a bug in your multithreaded implementation or BDN has a bug (it's very unlikely, the code is very mature and such bug would be detected long time ago).

**Comment by MikaelUmaN** [comment]
Hmm. Yes. I was positive a single run was not taking very much time, but some more testing revealed that the async{} constructs really don't work with this kind of CPU-bound workload.

Rewriting using the Task Parallel Library worked better. https://github.com/MikaelUmaN/MatrixMultiply

Closing this one, thanks for the quick response.
