### ISSUE TITLE
How do I test different versions of the. Net Core at the same time? 

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/BenchmarkDotNet#1165]
How do I test different versions of the. Net Core? I mean, test the performance of core2.0, core2.1, and core2.2 at the same time.

**Comment by adamsitnik** [comment]
Hi @NMSAzulX 

First of all, you need to make sure that the project which defines benchmarks targets ALL frameworks that you want to test:

```xml
<TargetFrameworks>netcoreapp2.0;netcoreapp2.1;netcoreapp2.2</TargetFrameworks>
```

Then, use `BenchmarkSwitcher` type and pass `args` to the `Run` method:

```cs
class Program
{
    static void Main(string[] args) 
        => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args); // you MUST pass the args to the Run method
}

public class Sample
{
    [Benchmark] public void TheCodeGoesHere() { }
}
```

And use `--runtimes` command to specify the target framework monikers to run:

```cmd
dotnet run -c Release -f netcoreapp2.0 --runtimes netcoreapp2.0 netcoreapp2.1 netcoreapp2.2
```

You can read more about it in our docs: https://benchmarkdotnet.org/articles/guides/console-args.html#runtimes

**Comment by NMSAzulX** [comment]
Thank you very much.Succeed.
