### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1170]

**Comment by RealDotNetDave** [comment]
I'm trying to do a benchmark test that tests two versions of the CLR and two of Core. I have my project file setup like this:

 <TargetFrameworks>netcoreapp2.2;netcoreapp3.0;net472;net48</TargetFrameworks>

In my benchmark class file, I am using these two attributes:

    [ClrJob()]
    [CoreJob()]

When when I run the project, it only tests two of the frameworks above (see below). How do I get BenchmarkDotNet to test all four at one time?

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17763.503 (1809/October2018Update/Redstone5)
Intel Core i7-7660U CPU 2.50GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=3.0.100-preview5-011568
  [Host]     : .NET Core 2.2.0 (CoreCLR 4.6.27110.04, CoreFX 4.6.27110.04), 64bit RyuJIT
  Job-OVYGEY : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.3761.0
  Job-XPBDTG : .NET Core 2.2.0 (CoreCLR 4.6.27110.04, CoreFX 4.6.27110.04), 64bit RyuJIT

**Comment by adamsitnik** [comment]
Hello @RealDotNetDave 

You can find the answer here: https://github.com/dotnet/BenchmarkDotNet/issues/1165#issuecomment-495731010
