### ISSUE TITLE
Possibility to compare previous with current benchmark

### ISSUE THREAD

**Issue by msedi** [dotnet/BenchmarkDotNet#1171]
I want to supervise performance drop in our components.
Therefore we wanted to use BenchmarkDotNet in our nightly builds additionally to our test environment.

What we would need is the possibility that BenchmarkDotNet is able to do a comparison of last (previous) benchmark(s) with the newest. The result should be how much time each step took longer/shorter and maybe also an decrease/increase in percent.

Does this make sense?

**Comment by AndreyAkinshin** [comment]
@msedi yes, it makes sense, and it's a work-in-progress feature. I guess, the main show-stopper here is the serialization format for benchmark results (see also https://github.com/dotnet/BenchmarkDotNet/issues/305). Also, I want to introduce smart algorithms for reliable performance testing which allows avoiding frequent false-positive alarms.

**Comment by msedi** [comment]
@AndreyAkinshin: Thanks for the feedback. I'm really happy when this feature arrives ;-)
