### ISSUE TITLE
Option to strip localsinit from benchmarks

### ISSUE THREAD

**Issue by stephentoub** [dotnet/BenchmarkDotNet#1174]
The C# compiler will automatically add `localsinit` into most methods that perform stackallocs.  This can have a measurable impact on microbenchmarks, and that's problematic when the benchmark is being used to analyze code that will ultimately be added to an assembly that disables such zero'ing, e.g. via https://github.com/mono/linker/blob/e883bd175a73916612a6b1df8ef3007020d663c2/src/ILLink.Tasks/LinkTask.cs#L55-L58, as is done for coreclr and corefx.  To more accurately measure code that uses stackallocs in microbenchmarks, until the C# compiler enables disabling emitting `localsinit`, it'd be great if Benchmark.NET offered a mechanism by which `localsinit` could similarly be cleared.

**Comment by adamsitnik** [comment]
I would be happy to implement that, the problem is that I am not sure how I could do that without [SkipLocalsInitAttribute](https://github.com/dotnet/csharplang/blob/master/proposals/skip-localsinit.md) as of today. Is it possible to control this behavior via some MSBuild parameter?

/cc @VSadov

**Comment by stephentoub** [comment]
Until it's supported by the language, I think you would need to rewrite the IL, either manually or with a tool like ILLink, which does have msbuild tasks.

**Comment by VSadov** [comment]
I thought the compiler has support for this for about a year now.

You will have to use the attribute. I do not think there is a compiler switch, but you can put the attribute in the whole module.

**Comment by stephentoub** [comment]
> I thought the compiler has support for this for about a year now.

I don't think that work was ever integrated into master: https://github.com/dotnet/roslyn/commits/features/localsinit.

**Comment by adamsitnik** [comment]
It has been a while since the issue was created and there was some progress made. The attribute is now public and can be used in C# source code including benchmarks:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.12.1" />
  </ItemGroup>

</Project>
```

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.Runtime.CompilerServices;

namespace ConsoleApp50
{
    class Program
    {
        static void Main(string[] args) => BenchmarkRunner.Run<Test>();
    }

    public class Test
    {
        [Benchmark]
        public void Default() => Consume(stackalloc byte[512]);

        [Benchmark]
        [SkipLocalsInit]
        public void Skip() => Consume(stackalloc byte[512]);

        private void Consume(Span<byte> span) { }
    }
}
```

```ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1139 (1909/November2018Update/19H2)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.100-rc.2.20479.15
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.47505, CoreFX 5.0.20.47505), X64 RyuJIT
  DefaultJob : .NET Core 5.0.0 (CoreCLR 5.0.20.47505, CoreFX 5.0.20.47505), X64 RyuJIT


|  Method |       Mean |     Error |    StdDev |
|-------- |-----------:|----------:|----------:|
| Default | 16.3864 ns | 0.0496 ns | 0.0414 ns |
|    Skip |  0.7574 ns | 0.0073 ns | 0.0064 ns |
```

@stephentoub is that enough or perhaps you wanted us to add a mode that would apply this attribute to the entire auto-generated assembly?

**Comment by stephentoub** [comment]
> is that enough

Yup, that's what I've been doing.  We can close this.  Thanks.
