### ISSUE TITLE
Raw data in CSV reports

### ISSUE THREAD

**Issue by omariom** [dotnet/BenchmarkDotNet#118]
CSV files is target for tools. So values in columns suffixed  with unit (like `ns`) is an inconvenience.
Can the unit be moved to column names in the header?

**Comment by nietras** [comment]
+1 I would second that, it really should be in the header.

**Comment by AmadeusW** [comment]
@AndreyAkinshin I see you removed up-for-grabs label. Is someone working on this? Can I take it?

**Comment by AndreyAkinshin** [comment]
> Can I take it?

@AmadeusW, ok.

**Comment by AmadeusW** [comment]
This bug is little harder to resolve because the exporters act on already formatted data.
In current implementation, a run `Summary` has a specific time unit and stores formatted data in `FullContentWithHeader`, that the `CsvExporter` consumes. The data becomes formatted when we call `SummaryColumn.GetValue`.

As a possible solution, we add `GetRawContentWithHeader()` method to `SummaryTable`. This method recalculates the table data just like we built `FullContentWithHeader`, but the summary would use `ns` and `kB` units, it wouldn't append the units to the numbers, and place them in table's column instead. We overload `IColumn.GetValue` so that we can request unit-free version. 

Interested exporters call `GetRawContentWithHeader()` instead of `FullContentWithHeader`
What do you think?

**Comment by AndreyAkinshin** [comment]
I want to support different summary table styles. We can start with something like this:
```cs
public class SummaryTableStyle
{
    public bool PrintUnitsInHeader { get; }
    public bool PrintUnitsInContent { get; }
    public MemoryUnit? MemoryUnit { get; }
    public TimeUnit? TimeUnit { get; }
}
```
The `MemoryUnit == null` and `TimeUnit == null` means that BenchmarkDotNet should choose the best unit automatically (current behaviour), but user can specifiy this value manually (here we also resolve https://github.com/dotnet/BenchmarkDotNet/issues/146). By default, `PrintUnitsInContent == true` and `PrintUnitsInHeader == false`. Our raw csv exporer will use the following values: `PrintUnitsInContent == false`, `TimeUnit == Nanoseconds`, `MemoryUnit == Byte` (by the way, we also have to introduce the `MemoryUnit` class, use `TimeUnit` and `FrequencyUnit` as examples).

**Comment by AmadeusW** [comment]
So there would be still single Summary shared by all reports and exporters, but this time user will be able to customize the appearance of this summary?

**Comment by AndreyAkinshin** [comment]
For the first implementation, we can use the following approach: each table exporter should have a second constructor with a SummaryTableStyle as an argument. If a user didn't specify the style manually, we will use the default style for this exporter.

**Comment by AmadeusW** [comment]
I've got it working, but I'm setting style for the single `Summary` that all exporters share.
![image](https://cloud.githubusercontent.com/assets/1673956/23889290/86ca03ee-0849-11e7-9c97-7aa5e9b54727.png)

All data (including table headers, its units and contents) is produced at creation of the `Summary`, and changing this would mean a larger refactoring. If we want to support individual style per exporter, we would need to create a new summary for each exporter with custom style, and so. 
```csharp
var summary = new Summary(title, reports, HostEnvironmentInfo.GetCurrent(), config, GetResultsFolderPath(rootArtifactsFolderPath), clockSpan.GetTimeSpan(), validationErrors);
foreach (var file in config.GetCompositeExporter().ExportToFiles(summary, logger))
{
   // ...
```
would change into
```csharp
var summary = new Summary(title, reports, HostEnvironmentInfo.GetCurrent(), config, GetResultsFolderPath(rootArtifactsFolderPath), clockSpan.GetTimeSpan(), validationErrors);
foreach (var exporter in config.GetCompositeExporter().GetExporters())
{
  string file;
  if (exporter.CustomStyle != null)
  {
    var newSummary = new Summary(title, reports, HostEnvironmentInfo.GetCurrent(), config, GetResultsFolderPath(rootArtifactsFolderPath), clockSpan.GetTimeSpan(), validationErrors, exporter.CustomStyle);
    file = exporter.ExportToFiles(newSummary, logger)
  }
  else
  {
    file = exporter.ExportToFiles(summary, logger)
  }
  // ...
```
Do you want to go ahead with this, use the same style (and the same instance of Summary) for all outputs, or is there a different way to achieve this?

**Comment by AndreyAkinshin** [comment]
I think we could replace the property `Summary.Table` by a method `Summary.GetTable(SummaryTableStyle style)`. Each exporter will request own table for the specific style.
