### ISSUE TITLE
Benchingmarking .NET 4.8 Causes Errors

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1182]
I am trying to run my benchmark test for .NET Core 3 and Clr 4.8 Preview 6 and am experiencing errors.

In the csproj file, I have it set up like this:
    <TargetFrameworks>netcoreapp3.0;net48</TargetFrameworks>

These same benchmarks work fine for .NET Core 3 and Clr 4.7.2.

Standard error: 
   Restore failed in 113.2 ms for C:\src\Books\RockYourCode\CodePerformance\src\PerfBin\netcoreapp3.0\286d48e8-ea59-4a4d-91cf-74303b8dcad7\BenchmarkDotNet.Autogenerated.csproj.
C:\src\Books\RockYourCode\CodePerformance\src\PerfBin\netcoreapp3.0\286d48e8-ea59-4a4d-91cf-74303b8dcad7\BenchmarkDotNet.Autogenerated.csproj : error NU1201:   - netcoreapp3.0 (.NETCoreApp,Version=v3.0)
C:\src\Books\RockYourCode\CodePerformance\src\PerfBin\netcoreapp3.0\286d48e8-ea59-4a4d-91cf-74303b8dcad7\BenchmarkDotNet.Autogenerated.csproj : error NU1201:   - net48 (.NETFramework,Version=v4.8)
C:\src\Books\RockYourCode\CodePerformance\src\PerfBin\netcoreapp3.0\286d48e8-ea59-4a4d-91cf-74303b8dcad7\BenchmarkDotNet.Autogenerated.csproj : error NU1201: Project dotNetTips.CodePerf.Example.App is not compatible with net472 (.NETFramework,Version=v4.7.2) / win7-x64. Project dotNetTips.CodePerf.Example.App supports:
C:\src\Books\RockYourCode\CodePerformance\src\PerfBin\netcoreapp3.0\286d48e8-ea59-4a4d-91cf-74303b8dcad7\BenchmarkDotNet.Autogenerated.csproj : error NU1201:   - netcoreapp3.0 (.NETCoreApp,Version=v3.0)
C:\src\Books\RockYourCode\CodePerformance\src\PerfBin\netcoreapp3.0\286d48e8-ea59-4a4d-91cf-74303b8dcad7\BenchmarkDotNet.Autogenerated.csproj : error NU1201:   - net48 (.NETFramework,Version=v4.8)
C:\src\Books\RockYourCode\CodePerformance\src\PerfBin\netcoreapp3.0\286d48e8-ea59-4a4d-91cf-74303b8dcad7\BenchmarkDotNet.Autogenerated.csproj : error NU1201: Project dotNetTips.CodePerf.Example.App is not compatible with net472 (.NETFramework,Version=v4.7.2). Project dotNetTips.CodePerf.Example.App supports:

**Comment by AndreyAkinshin** [comment]
@RealDotNetDave, thanks for the report!
1. Why do you use 4.8 Preview instead of the stable version which was released in April?
2. Could you please paste the content of the generated `BenchmarkDotNet.Autogenerated.csproj`?

**Comment by adamsitnik** [comment]
How exactly do you run the benchmarks?

The following command should work:

```cmd
dotnet run -c Release -f net48
```

**Comment by RealDotNetDave** [comment]
I am using the release version of 4.8. Below is the csproj file for the clr benchmark test:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImportDirectoryBuildProps>false</ImportDirectoryBuildProps>
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
    <AssemblyTitle>Job-DNRYOK</AssemblyTitle>
    <TargetFramework>net472</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>Job-DNRYOK</AssemblyName>
    <OutputType>Exe</OutputType>
    <OutputPath>bin\Release</OutputPath>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <UseSharedCompilation>false</UseSharedCompilation>
    <CodeAnalysisRuleSet></CodeAnalysisRuleSet>
    
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Job-DNRYOK.notcs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="C:\src\Books\RockYourCode\CodePerformance\src\dotNetTips.CodePerf.Example.App\dotNetTips.CodePerf.Example.App.csproj" />
  </ItemGroup>
  <PropertyGroup>
<ServerGarbageCollection>true</ServerGarbageCollection>
<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
<RetainVMGarbageCollection>false</RetainVMGarbageCollection>
</PropertyGroup>


</Project>

**Comment by RealDotNetDave** [comment]
Any ideas?

**Comment by adamsitnik** [comment]
![obraz](https://user-images.githubusercontent.com/6011991/60193045-4765fc00-9837-11e9-97bd-91a7b027a6e3.png)

**Comment by RealDotNetDave** [comment]
Any ideas?

**Comment by RealDotNetDave** [comment]
I just run the console app EXE.

**Comment by RealDotNetDave** [comment]
I read the other issues and ran my test with this: 

BenchmarkRunner.Run<GeneralPerfTestRunner>(DefaultConfig.Instance.With(Job.Default.With(CsProjCoreToolchain.NetCoreApp30)).With(Job.Default.With(CsProjClassicNetToolchain.Net48)));

This seems to work. It would be nice if this could be done with attributes similar to the suggestions in the other issues you mentioned.

**Comment by adamsitnik** [comment]
@RealDotNetDave  Thanks for the feedback. I've proposed a solution to these problems in https://github.com/dotnet/BenchmarkDotNet/pull/1188 which would simply require the users to provide Full TFM and make BDN stop trying to figure it out

**Comment by RealDotNetDave** [comment]
Is the fix implemented? I tried to use it but the RuntimeMoniker isn't found.

**Comment by adamsitnik** [comment]
I've just merged #1188 with the fix.
