### ISSUE TITLE
Comparing project reference against package reference

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/BenchmarkDotNet#1192]
I know it is possible to compare between different NuGet versions, but is it possible to compare a local build of a library (a ProjectReference to Foo.csproj) against an existing NuGet package reference.

If not, is it possible to emit a custom MSBuild define on a Job that could be used in a csproj condition for the Reference block?

**Comment by wojtpl2** [comment]
I don't know about normal solution for this. But you can try to use local feeds as a workaround. You can publish new version of your package to local directory and then configure your nuget.config in benchmark project to use it.

**Comment by MihaZupan** [comment]
I thought about doing this but didn't think of the nuget config, thanks.

**Comment by MihaZupan** [comment]
Tested it on a few projects and it seems to be working. Thanks again.

**Comment by wojtpl2** [comment]
@MihaZupan Thanks for the information.
