### ISSUE TITLE
RunAll with ToolChains

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1194]
Is there a way to run all benchmarks in a project and configure ToolChains? Similar to this:

`BenchmarkRunner.Run<ValueTypePerfTestRunner>(DefaultConfig.Instance.With(Job.Default.With(CsProjCoreToolchain.NetCoreApp30)).With(Job.Default.With(CsProjClassicNetToolchain.Net48)).With(Job.Default.With(CsProjClassicNetToolchain.Net472)).With(Job.Default.With(CsProjCoreToolchain.NetCoreApp22)));`

But using `BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).RunAll()`?

**Comment by adamsitnik** [comment]
Hi @RealDotNetDave 

Ups, we forgot to add the possibility to pass `IConfig` to `RunAll`. I have fixed that in https://github.com/dotnet/BenchmarkDotNet/commit/ae23bddebe49cd66a9627790c073b7bc45ccbf5c

Until we ship a new NuGet version you can use the following code:

```cs
var config = DefaultConfig.Instance
    .With(Job.Default.With(CsProjCoreToolchain.NetCoreApp30))
    .With(Job.Default.With(CsProjClassicNetToolchain.Net48))
    .With(Job.Default.With(CsProjCoreToolchain.NetCoreApp22));

BenchmarkSwitcher
   .FromAssembly(typeof(Program).Assembly).
   .Run(new[] { "--filter", "*" }, config);
```

or just pass the args to BenchmarkSwitcher:

```cs
class Program
{
    static void Main(string[] args) 
        => BenchmarkSwitcher
            .FromAssembly(typeof(Program).Assembly)
            .Run(args);
}
```

and use following command from console:

```cmd
dotnet run -c Release -f net48 --filter * --runtimes netcoreapp2.2 netcoreapp3.0 net48
```

**Comment by RealDotNetDave** [comment]
Awesome. Thanks!
