### ISSUE TITLE
Why Error is bigger than StdDev?

### ISSUE THREAD

**Issue by astef** [dotnet/BenchmarkDotNet#1205]
Standard error should be always smaller than Standard deviation. I've found [this line](https://github.com/dotnet/BenchmarkDotNet/blob/0e4b8e69d10e73a83fce3ce3980497ee7798bc87/src/BenchmarkDotNet/Mathematics/Statistics.cs#L75) with the correct formula, but it seems to be not what is shown in the summary table:

| Method | Runtime |     N |       Mean |     Error |    StdDev | Ratio | Rank |
|------- |-------- |------ |-----------:|----------:|----------:|------:|-----:|
| Sha256 |     Clr |  1000 |   8.009 us | **0.0370 us** | **0.0346 us** |  1.00 |    3 |
| Sha256 |    Core |  1000 |   4.447 us | **0.0117 us** | **0.0110 us** |  0.56 |    2 |
| Sha256 |  CoreRT |  1000 |   4.321 us | **0.0139 us** | **0.0130 us** |  0.54 |    1 |
| Sha256 |    Mono |  1000 |  14.924 us | **0.0574 us** | **0.0479 us** |  1.86 |    4 |

**Comment by AndreyAkinshin** [comment]
@astef in the "Legend" section under the summary table, you can find the legend for each column. "Error" is not the standard error, it's "Half of 99.9% confidence interval", this metric is more useful for the analysis than the raw standard error. I know that the current title may be misleading, but we don't have enough space for "Half of 99.9% confidence interval" in the summary table header row. If you have an idea of a better term for such a column (it should be less than 10 symbols), let me know.

**Comment by astef** [comment]
Sorry, I've missed the legend, now it makes sense, unless...

I'm not a statistics expert, but for me it's suspicious that you're using [Student's t-distribution](https://github.com/dotnet/BenchmarkDotNet/blob/60eca005326970202a33891e5aecd2ef6b7e4cd0/src/BenchmarkDotNet/Mathematics/ConfidenceInterval.cs#L92) for this purpose. Data is presumably normally distributed and you're using standard deviation for normal distribution function, so I personally feel something is not right.

May be it's the reason why sometimes "Error" is less than "StdDev" value? From "Showtime" example:

| Method | Runtime |     N |       Mean |     Error |    StdDev | Ratio | Rank |
|------- |-------- |------ |-----------:|----------:|----------:|------:|-----:|
|    Md5 |     Clr |  1000 |   3.051 us | **0.0604 us** | 0.0742 us |  1.00 |    3 |

**Comment by astef** [comment]
But for me the issue is solved, thanks for your help

**Comment by AndreyAkinshin** [comment]
@astef to be honest, I don't see any problems with the math, everything looks OK to me. If you want to improve your statistics skills, I can recommend my book [Pro .NET Benchmarking](https://aakinshin.net/prodotnetbenchmarking/), it has a whole chapter about statistics and how to correctly interpret statistical metrics.

**Comment by airbreather** [comment]
> I know that the current title may be misleading, but we don't have enough space for "Half of 99.9% confidence interval" in the summary table header row. If you have an idea of a better term for such a column (it should be less than 10 symbols), let me know.

"CI Dist."?
"99.9% Dst"?
"CI Spread"?
"99.9 Sprd"?
