### ISSUE TITLE
Strange # of "Launches" chosen with Count.Auto

### ISSUE THREAD

**Issue by mattwarren** [dotnet/BenchmarkDotNet#121]
I'm using this benchmark in [this gist](https://gist.github.com/mattwarren/cbca3d2c70c47b39e480) and then I'm running it on the cmd line with `jobs=clr` or `jobs=LegacyX86` (it's probably the same with any `job` that defaults to having `LaunchCount` = `Count.Auto`)

It runs for 35 launches, i.e. it gets up-to  `// Launch: 33 / 35`, which seems a bit excessive! I wonder if this is hitting some sory of edge case in the logic that calculates `launchCount`? The fact that `idleApprox` is larger than `mainApprox` is also a bit weird!!

I added some debugging code and the following is printed out:

```
// Calculating Launch value:
// percent = 100.36 (idleApprox = 315,800,257.04, mainApprox = 314,664,654.07)
// launchCount = 35 (2 + (percent - 1) / 3 = 35.1202976936782)
// Launch: 3 / 35
```

I've also attached the log [Framework_AppDomainOverhead.zip](https://github.com/PerfDotNet/BenchmarkDotNet/files/179856/Framework_AppDomainOverhead.zip)

**Comment by AndreyAkinshin** [comment]
@mattwarren, `RegularMethodCall` in your example takes 0ns (because we substract BenchmarkDotNet overhead + I suspect that `Testing.Run` was inlined; you can improve the code with help of `[MethodImpl]`). I suggest to detect such methods on the Pilot iterations and mark it as "unmeasurable" or set `0ns` as a result without main iterations. What do you think?

**Comment by mattwarren** [comment]
> I suggest to detect such methods on the Pilot iterations and mark it as "unmeasurable" or set 0ns as a result without main iterations. What do you think?

That seems sensible do you mean via an Analyser?

I also think that we need to have an upper limit on the `launchCount`, something like `launchCount = Math.Min(5, launchCount)` for other scenarios (maybe not `5` but you get the idea).

**Comment by AndreyAkinshin** [comment]
I suggest to try MaxLaunchCount=15 for now. Also, I will detect 0ns-method on pilot stage, disable warmup/main iteration, and mark it as "unmeasurable" in an analyser.
