### ISSUE TITLE
Comparing runs between machines?

### ISSUE THREAD

**Issue by natiki** [dotnet/BenchmarkDotNet#1216]
Hi,

If I have the same benchmark code that I run on Machine A and Machine B. Is there any reasonable way I can compare the results? 

Obviously different hardware will produce different outcomes, but lets assume that all the hardware is the same except for the model of the CPU. In my case I have a work machine (machine A) and a home machine (machine B( and whatever results I have reaped on one I "kind of" have to disregard and start again on the new machine.

**Comment by adamsitnik** [comment]
Hi @natiki 

You can use a tool that I've build on top of BenchmarkDotNet: https://github.com/dotnet/performance/tree/master/src/tools/ResultsComparer

We are planning to add such feature to BDN global tool itself: https://github.com/dotnet/BenchmarkDotNet/issues/973
