### ISSUE TITLE
[Docs] RScript / R_HOME setup

### ISSUE THREAD

**Issue by tebeco** [dotnet/BenchmarkDotNet#1220]
Hello,

As part of an experimentation we tried to see how data were exported using `RExporter`.
Was hit by 2 little things :
* the link to `R` installer is a bit small since it'as applied on "one letter only" (barelly visible on High Res).
* Took me time to understand what was intended in `R_HOME` (it was already updated here #339)

Finally managed to work but i had to open the source code to understand that it would concat `/bin` to this value ^^.

#### Side note
Even with `RScript.exe` in the `PATH`, it seems that if `R_HOME` exist and points to a wrong path (i initially tried `C:\Program Files\R\R-3.6.1\bin`) it won't try to check in the `PATH`.
If a run takes few hours, the error appears latter :

* Should the Rscript detection fallback to the `PATH` is `R_HOME` seems wrong ?
* Could the `RExporter` be detected before the `Benchmark` start
  * Should it output an error / warning
  * Should it prompt the User to continue or not ?
  * What to do on the CI ? (would waste ~xxx Min on the CI to fail at the end)

**Comment by AndreyAkinshin** [comment]
> Should the Rscript detection fallback to the PATH is R_HOME seems wrong ?

I'm OK with such a fallback.

> Could the RExporter be detected before the Benchmark start

Yes, it's a good idea. We have validators for such tasks (check out SetupCleanupValidator as an example). PR with such checks is welcome!

**Comment by adamsitnik** [comment]
Fixed by #1222 a while ago, closing
