### ISSUE TITLE
Will the Error time be included if no errors are thrown?

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/BenchmarkDotNet#1223]
If there is a better place to ask a 'How To' question for BenchMarkDotNet please tell me where.

I was super excited when I completed my first benchmark and my project DataTiet.Net beat Entity Framework by a landslide:

Method | Mean | Error | StdDev
-- | -- | -- | --
LoadDTNSetting | 14.24 us | 0.0181 us | 0.0169 us
LoadEFSetting | 195.93 us | 0.5839 us | 0.5462 us

(simple test finding one record in a table by the primary key. If the EF Data Context creation was included, EF went to over 700).

I am curious about one thing

I see the error times listed, but I do not believe either product threw any errors. How is this number determined if no errors are thrown, or will it show zero if no errors are actually thrown?

Thanks.

**Comment by adamsitnik** [comment]
Hi @DataJuggler 

BenchmarkDotNet prints a Legend under the table with the results. It contains some basic  explanation:

```log
 // * Legends *
   Mean      : Arithmetic mean of all measurements
   Error     : Half of 99.9% confidence interval
   StdDev    : Standard deviation of all measurements
   Median    : Value separating the higher half of all measurements (50th percentile)
   Min       : Minimum
   Max       : Maximum
   Gen 0     : GC Generation 0 collects per 1000 operations
   Gen 1     : GC Generation 1 collects per 1000 operations
   Gen 2     : GC Generation 2 collects per 1000 operations
   Allocated : Allocated memory per single operation (managed only, inclusive, 1KB = 1024B)
   1 ms      : 1 Millisecond (0.001 sec)
```

[This](https://github.com/dotnet/BenchmarkDotNet/issues/1205#issuecomment-513495371) answer explains what the "Error" means in greater deatils

**Comment by DataJuggler** [comment]
I missed the legend also and not really sure I understand the answer.

Is there some documentation somewhere? 

I watched a YouTube video and the [benchmark] tag was so easy I jumped right in the deep end without those little floaty things on my arms.

Thanks for the reply. 

Corby

**Comment by adamsitnik** [comment]
> and not really sure I understand the answer

To tell the long story short, BenchmarkDotNet was designed for microbenchmarks, it does not have any exception/error handling mechanism. If your benchmark method throws, then BDN just fails. The "Error" is one of the statistics BDN displays.

> Is there some documentation somewhere?

**Comment by DataJuggler** [comment]
I didn’t think any errors were thrown, that is why I was surprised to see Error.

I don’t understand the label being ‘Error’ for half of 99.9%. That sounds like 1/1000 operation speed, not error.

**Comment by adamsitnik** [comment]
> Is there some documentation somewhere?

Andrey has written an excellent [book](https://aakinshin.net/prodotnetbenchmarking/) which has an entire chapter dedicated for Statistics. You can also google for "confidence interval" and read/watch some explanations on the internet.

> I didn’t think any errors were thrown, that is why I was surprised to see Error.

I understand, however, I am not sure what else we can do on BDN side. We already print a Legend below the results. @AndreyAkinshin is there any better name for the "Error" to avoid users confusion?

**Comment by DataJuggler** [comment]
I wasn't complaining, I was just explaining why I was confused because my component has the errors trapped pretty well and shouldn't ever throw any.

Thanks for all the answers.
