### ISSUE TITLE
Strong type fluent API proposal

### ISSUE THREAD

**Issue by WojciechNagorski** [dotnet/BenchmarkDotNet#1234]
## Current API ##
```c#
Add(Job.ShortRun.With(Jit.LegacyJit).With(Platform.X86).With(ClrRuntime.Net461));
Add(Job.ShortRun.With(Jit.LegacyJit).With(Platform.X64).With(ClrRuntime.Net461));
//
Add(Job.ShortRun.With(Jit.RyuJit).With(Platform.X64).With(ClrRuntime.Net461));

// RyuJit for .NET Core 2.0
Add(Job.ShortRun.With(Jit.RyuJit).With(Platform.X64).With(CoreRuntime.Core20));
// RyuJit for .NET Core 2.1
Add(Job.ShortRun.With(Jit.RyuJit).With(Platform.X64).With(CoreRuntime.Core21));

Add(ANALIZER);
Add(DIAGNOSER);
Add(COLUMN);
Add(HardwareCounter);
```
The biggest issue for me are methods `Job.With()` and method `ManualConfig.Add()`. These methods have many versions of overloads.

## API Proposal ##
I would like to propose new, strongly typed, fluent API.

```C#
AddJob(Job.ShortRun.UseLegacyJit().UseX86().UseClrRuntime(ClrVersion.Net461);

AddJob(Job.ShortRun.UseLegacyJit().UseX86().UseClrRuntime(ClrVersion.Net461);
AddJob(Job.ShortRun.UseLegacyJit().UseX64().UseClrRuntime(ClrVersion.Net461);

AddJob(Job.ShortRun.UseRyuJit().UseX64().UseClrRuntime(ClrVersion.Net461);

// RyuJit for .NET Core 2.0
AddJob(Job.ShortRun.UseRyuJit().UseX64().UseCoreRuntime(CoreVersion.Core20);
// RyuJit for .NET Core 2.1
AddJob(Job.ShortRun.UseRyuJit().UseX64().UseCoreRuntime(CoreVersion.Core21);

AddAnalyzer(...);
AddDiagnoser(...);
AddColumn(...);
AddHardwareConter(...);
```

`AddJob(Job.ShortRun.Use... )` could be replaced by:
- `AddJob(JobType.ShortRun).UseLegacyJit().UseX86().UseClrRuntime(ClrVersion.Net461);`
- `AddShortRunJob().UseLegacyJit().UseX86().UseClrRuntime(ClrVersion.Net461);`

**Comment by adamsitnik** [comment]
I really like this idea!!!

@AndreyAkinshin what do you say?

**Comment by AndreyAkinshin** [comment]
I also like this idea. It wasn't a problem several years ago (when we have a small number of API method), but now we have the overload hell. The suggested changes should simplify the user experience.
P.S. The old API method shouldn't be deleted or changed; they should be just marked with the `Obsolete` attribute and the proper messages about the new API.

@wojtpl2 do you want to create a pull request?

**Comment by wojtpl2** [comment]
@AndreyAkinshin Yes, I will be very happy if I can do it.
