### ISSUE TITLE
RunAllJoined Causing Exception

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1238]
If I run my benchmarks with Run or RunAll, they both work fine. If I run RunAllJoined (below) it causes an exception. I'm using version 0.11.5.1161

```
var config = DefaultConfig.Instance.With(Job.Default.With(CsProjCoreToolchain.NetCoreApp22)).With(Job.Default.With(CsProjClassicNetToolchain.Net48));
BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).RunAllJoined(config);

Unhandled Exception: System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Reports.Summary.GetConfiguredOrdererOrDefaultOne(IEnumerable`1 configs)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, ImmutableArray`1 reports, HostEnvironmentInfo hostEnvironmentInfo, String resultsDirectoryPath, String logFilePath, TimeSpan totalTime, ImmutableArray`1 validationErrors)
   at BenchmarkDotNet.Reports.Summary.Join(List`1 summaries, ClockSpan clockSpan)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunAllJoined(IConfig config)
   at dotNetTips.Utility.Benchmarks.Program.Main() in C:\src\git\dotNetTips.Utility\Benchmarks\dotNetTips.Utility.Benchmarks\dotNetTips.Utility.Benchmarks\Program.cs:line 24
```

**Comment by adamsitnik** [comment]
Hi @RealDotNetDave 

Are you using `[OrdererAttribute]` in some of your benchmarks? If so, how many?

**Comment by RealDotNetDave** [comment]
Yes I am using:
`[Orderer(SummaryOrderPolicy.Method)]`

**Comment by RealDotNetDave** [comment]
I ran the tests without using `[OrdererAttribute]` and it worked fine. Seems to be a bug to me.

**Comment by AndreyAkinshin** [comment]
I was able to reproduce the problem, here is a repro:
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Order;
using BenchmarkDotNet.Running;

namespace BenchmarkDotNet.Samples
{
    [Orderer(SummaryOrderPolicy.Method), DryJob]
    public class BenchmarkClass1
    {
        [Benchmark]
        public void Foo() { }
    }

    [Orderer(SummaryOrderPolicy.Method), DryJob]
    public class BenchmarkClass2
    {
        [Benchmark]
        public void Bar() { }
    }

    class Program
    {
        static void Main(string[] args)
        {
            BenchmarkSwitcher
                .FromTypes(new[] { typeof(BenchmarkClass1), typeof(BenchmarkClass2) })
                .RunAllJoined();
        }
    }
}
```
I'm not sure what should we do in such cases. Such problem is also related to situations when different benchmark classes with conflicting configs (e.g., now it's possible to provide conflicting `SummaryStyle`, `Encoding`, etc.). I see the following options:
1. We can write a validator which checks for conflicting configs in advance, stops the benchmark executing, and prints a nice user-friendly message about the problem.
2. We can execute all the benchmarks, take the first declared `IOrderer` and use it for the summary table formatting (with a proper warning under the table).
3. We can introduce additional arguments for `RunAllJoined` that will say BenchmarkDotNet what should we do with conflicted orderers.

**Comment by adamsitnik** [comment]
> We can write a validator which checks for conflicting configs in advance, stops the benchmark executing, and prints a nice user-friendly message about the problem.

I think that this is the best option. Users can not use few different orderers if they want to join all the results into a single summary.

**Comment by andresrsanchez** [comment]
> I think that this is the best option. Users can not use few different orderers if they want to join all the results into a single summary.

And cannot be done with the actual [ConfigValidator](https://benchmarkdotnet.org/api/BenchmarkDotNet.Validators.ConfigValidator.html)?

**Comment by adamsitnik** [comment]
> And cannot be done with the actual ConfigValidator

Most probably it should be possible to extend `ConfigValidator` to implement this

**Comment by gsomix** [comment]
Please assign it to me. Thanks!

**Comment by adamsitnik** [comment]
> Please assign it to me.

@gsomix done! Once again thank for working on this!

**Comment by RealDotNetDave** [comment]
Awesome. Let me know when it's completed, so I can test.
