### ISSUE TITLE
Can BenchmarkDotNet be enabled for LINQPad 6?

### ISSUE THREAD

**Issue by albahari** [dotnet/BenchmarkDotNet#1241]
When you use BenchmarkDotNet in LINQPad 6, you get the following error:

Currently LINQPad does not support .NET Core benchmarks (see dotnet/BenchmarkDotNet#975), benchmark 'Md5VsSha256.Sha256: DefaultJob' will not be executed

This is because of a check in BenchmarkDotNet.Toolchains.CsProj.CsProjCoreToolchain.IsSupported:

```
if (benchmarkCase.Descriptor.Type.GetTypeInfo().Assembly.IsLinqPad())
{
	logger.WriteLineError("Currently LINQPad does not support .NET Core benchmarks (see dotnet/BenchmarkDotNet#975), benchmark '" + benchmarkCase.DisplayInfo + "' will not be executed");
	return false;
}
```

This check makes sense when running under LINQPad 5 which targets .NET Framework, but not with LINQPad 6, which targets .NET Core 3:
https://www.linqpad.net/LINQPad6.aspx

(You can determine whether an assembly is generated specifically by LINQPad 5 by checking whether the path contains %temp%\LINQPad5\.)

**Comment by AndreyAkinshin** [comment]
@albahari thanks for the report! I reproduced the problem with LINQPad 6 (had to upgrade my LINQPad 5 license for that 😃). I'm going to introduce LINQPad version detection and update the checks.

**Comment by adamsitnik** [comment]
The problem is that our .NET Core toolchains expect to find a `.csproj` of a project that defines the benchmark. The auto-generated project references it.

Adding LINQPad 6 support would require to either support referencing just a `.dll` like we do for Full .NET Framework.  This would make another scenario work: publish a self-contained app, copy to other machine and run the benchmark without sources.

The alternative it to use the new `InProcessEmitToolchain` when we detect `Linqpad 6`

**Comment by AndreyAkinshin** [comment]
@adamsitnik I think, it's OK to enable `InProcessEmitToolchain` as the default toolchain for LINQPad 6.

**Comment by albahari** [comment]
I've just tested the latest CI build and it seems to work well.

Is there any chance that you could also update LinqpadLogger.lazyInstance?

Here's the code you need to make it work with both LINQPad5 and LINQPad6:

 ```
if (AppDomain.CurrentDomain.FriendlyName.StartsWith ("LINQPad", StringComparison.OrdinalIgnoreCase))
 {
     try
     {
     	var utilType = 
            Type.GetType ("LINQPad.Util, LINQPad, Version=1.0.0.0, Culture=neutral, PublicKeyToken=21353812cd2a2db5") ??
            Type.GetType ("LINQPad.Util, LINQPad.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=21353812cd2a2db5");
        
        methodInfo = utilType?.GetMethod ("WithStyle", BindingFlags.Static | BindingFlags.Public);
     }
     catch (Exception)
     {
     }
 }
```

**Comment by adamsitnik** [comment]
@albahari done, we should have a `0.11.5.1171` package as soon as [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/27409065) build finishes green
