### ISSUE TITLE
bug JSON Exporter exports NaN for some properties. This fails most JSON parsers

### ISSUE THREAD

**Issue by jafin** [dotnet/BenchmarkDotNet#1242]
The JSON Exporter writes NaN values in some properties.  This is invalid according to online JSON Parser, and fails with the javascript JSON.Parse.

Properties found with NaN:

```
Statistics.Skewness
Statistics.Kurtosis
ConfidenceInterval.Margin
ConfidenceInterval.Lower
ConfidenceInterval.Upper
```

**Comment by marcnet80** [comment]
Hello, @AndreyAkinshin, @adamsitnik. Please review PR:  Json exporter fix #1581 
Thanks.
