### ISSUE TITLE
No GCs Invoked During Benchmarking

### ISSUE THREAD

**Issue by luckerby** [dotnet/BenchmarkDotNet#1250]
I'm benchmarking some very simple C# code that essentially boxes 10 mil int values.
```
            const int noNumbers = 10000000;  // 10 mil
            object o = null;
            for (int i = 0; i < noNumbers; i++)
            {
                o = i;
            }
            int v = (int)o;
```
 The machine that's running this is a Windows 10 64-bit box, with no particular changes done to the .NET Framework 4.7.2, so GC should be running in workstation mode.

After running BenchmarkDotNet against the code above (AnyCPU/Prefer 32-bit mode) I get the output below, signalling that no GC occurred for either gen0/1/2:
![image](https://user-images.githubusercontent.com/31319583/65612889-bcbfa500-dfbd-11e9-804d-18eb1b01843d.png)

However if I take the same code and place it in a new C# project (AnyCPU/Prefer 32-bit mode) in the Main function and run this, I get a considerably different outcome. Note the 57 gen0 GCs reported by PerfView:
![image](https://user-images.githubusercontent.com/31319583/65613185-3f486480-dfbe-11e9-95df-674ef74a65ab.png)

I've checked the code generated by BenchmarkDotNet using the `[DisassemblyDiagnoser(printAsm: true, printSource: true)]` attribute and I've also looked at the code generated by the standalone app using WinDbg. Here they are side-by-side, showing identical assembly instructions (minus the hex addresses, of course):
![image](https://user-images.githubusercontent.com/31319583/65613494-ceee1300-dfbe-11e9-843f-903081ca3b25.png)

Details about the runtime used, as reported by BenchmarkDotNet :
![image](https://user-images.githubusercontent.com/31319583/65613699-1a082600-dfbf-11e9-873e-063c5c45348a.png)

The difference between the number of gen0 GCs is quite big. Am I doing something wrong here, that would explain the results ?

**Comment by wojtpl2** [comment]
Did you try to use different GC mode settings of your benchmark configuration?
https://benchmarkdotnet.org/articles/samples/IntroGcMode.html

**Comment by luckerby** [comment]
I was happy that the same GC mode was used in both my standalone app and in the BenchmarkDotNet profiled one - Concurrent Workstation. For my app I know this is the case, since there's no specific entry in the App.config file that would change the default, while for BenchmarkDotNet it's clearly mentioned in the output visible in my original post.
If I go ahead and change the GC mode - eg to Server - I'm worried of running into other issues (eg multiple managed heaps, one per core).
I've also thought of trying to profile the memory used by the child process invoked by BenchmarkDotNet when it's doing the profiling. JetBrains dotMemory would work just fine, but the trouble is I don't know how to hook to the child process only (representing my app); plus I imagine this is invoked a lot of times, which complicates matters.

**Comment by luckerby** [comment]
I went ahead and ran PerfView at the same time that the BenchmarkDotNet profiling was running, in order to capture the ETW for the GC. Sure enough, there are a lot of gen0 GCs happening, but BenchmarkDotNet doesn't report any at the end (below). Is there some sort of threshold maybe over which a GC is reported in the results ?

![image](https://user-images.githubusercontent.com/31319583/65796656-dc013280-e175-11e9-99f9-b0ab2932dc3d.png)

**Comment by adamsitnik** [comment]
Hello everyone!

To capture the number of total allocated bytes on Full .NET Framework we need to enable monitoring for AppDomain:

https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Engines/Engine.cs#L229-L230

This adds some overhead, this is why we do it in a **single extra iteration run after all benchmark iterations**:

https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Engines/Engine.cs#L131-L133

In this particular case the problem is that GCs occure during the benchmark iterations, but GC is self-learning, changes the generation budgets and does not perfom any work when we run the one extra iteration at the end.

The fix would be to capture the GC counts for every benchmark workload iteration, and just extend the data with the total number of allocated bytes captured in the last iteration. I currently don't have time to fix it, but I am going to mark this issue as up-for-grabs and hope that some #Hacktoberfest contributors are going to fix it. If not, I am going to fix it after Dotnetos Conference ;P

**Comment by wojtpl2** [comment]
I wanted to fix this issue but my investigation shows that there is no bug.

My benchmark:
```c#
using BenchmarkDotNet.Attributes;

namespace BenchmarkDotNet.Samples
{
    [MemoryDiagnoser] // <-- I added MemoryDiagnoser here
    public class Issue1250
    {
        [Benchmark]
        public int Benchmark()
        {
            const int noNumbers = 10000000;  // 10 mil
            object o = null;
            for (int i = 0; i < noNumbers; i++)
            {
                o = i;
            }
            return (int)o;
        }
    }
}
```

Then I run benchmark from the console:
```powershell
dotnet run -c Release -f net472 -- --filter *Issue1250*
```
I got a result:
![image](https://user-images.githubusercontent.com/17333903/66460590-83843c00-ea77-11e9-87ed-79b78b645328.png)
![image](https://user-images.githubusercontent.com/17333903/66460650-a0b90a80-ea77-11e9-80e9-71f883a4afe1.png)

When I run this benchmark without `[MemoryDiagnoser]` I got a result:
![image](https://user-images.githubusercontent.com/17333903/66460713-c6461400-ea77-11e9-9f98-93199aab0f43.png)
![image](https://user-images.githubusercontent.com/17333903/66460724-cba35e80-ea77-11e9-9fad-9d2fccc860e2.png)

@luckerby Did you use `[MemoryDiagnoser]` in your benchmark? if not, could you check if that solves your problem?

@adamsitnik I think that BenchmarkDotNet should not print information about GC if it doesn't run extra iteration. I mean this line:
```
GC:  0 0 0 0 0
Threading:  0 0 0
```
Extra iteration runs only when user adds `MemoryDiagnoser` or `ThreadingDiagnoser`. In other cases we shouldn't print these lines:

https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Engines/RunResults.cs#L71-L72

Or even more precisely:
`GC:  0 0 0 0 0` should print only with `MemoryDiagnoser`
`Threading:  0 0 0` should print only with `ThreadingDiagnoser`
@adamsitnik What do you think?

**Comment by luckerby** [comment]
@wojtpl2 I'm on a different machine than the one I used to initially run the code, and to be honest I don't remember the attributes used, aside from the disassembly one.

However, I've recreated the project, and first used `MemoryDiagnoser` against the class with the method under test, and got the results below similar to yours:
![image](https://user-images.githubusercontent.com/31319583/66464187-298b7280-ea87-11e9-8f4c-747c25d27d9c.png)

Removing the `MemoryDiagnoser` attribute resulted in an outcome, again, similar to yours:
![image](https://user-images.githubusercontent.com/31319583/66463978-d5808e00-ea86-11e9-8638-deda654aa499.png)

The value of gen0 collections however looks fishy - if I understood correctly the output in BenchmarkDotNet is how many collections are done per 1000 runs, which would indicate an average of less than 1 collection.

I will check in a few hours how the original code looked like - particularly if the `MemoryDiagnoser` was used or not - just to be sure.

**Comment by luckerby** [comment]
@wojtpl2 The original code didn't have the `MemoryDiagnoser` attribute applied either, which makes the outcomes so far consistent.

I've looked at the source code, but couldn't figure this one out: how can you tell that not using `[MemoryDiagnoser]` results in `includeExtraStats` eventually being null when the stats get prepared ?
https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Engines/Engine.cs#L131-L133

**Comment by luckerby** [comment]
Running again on the original machine, and I've used just one single run - using `[SimpleJob(RunStrategy.ColdStart, targetCount: 1)]` in order not to allow the GC to tweak itself in any way by "observing" subsequent runs of the same code. A result of 57 is shown for gc0 collections:

![image](https://user-images.githubusercontent.com/31319583/66682224-3a9dd480-ec7d-11e9-9b8c-c1215269e573.png)

Immediately running PerfView againt the individual project doing the same exact thing shows again 57 gc0, just as the value observed ealier, and the same seen in the first post of this thread (number is 114 since both GC start and stop is captured):

![image](https://user-images.githubusercontent.com/31319583/66682605-463dcb00-ec7e-11e9-9381-fc057904dfa2.png)

Therefore things are quite consistent.


As a side note, I initially thought that 57 in BenchmarkDotNet's output is the number _per 1000 runs_, but I've later discovered that's just the case in the function output, not the overall GC stats.

**Comment by adamsitnik** [comment]
If you want BDN to produce memory statistics then you have to use `MemoryDiagnoser`, either via attribute, fluent config API or console line argument. The final results are printed in the Summary table, the intermediate output is **only** for the purpose of the Host and Benchmark process exchanging information.

You can read more about `MemoryDiagnoser` in our [docs](https://benchmarkdotnet.org/articles/configs/diagnosers.html) and on my [blog](https://adamsitnik.com/the-new-Memory-Diagnoser/)
