### ISSUE TITLE
Language wars c# vs c++

### ISSUE THREAD

**Issue by JanEggers** [dotnet/BenchmarkDotNet#1251]
I had some discussions and im sure im not the only one: whats the best language (perf wise)?

c# vs c++

I know that there are things that cannot be done in c# that can be done in c++.

But I wonder if it would be possible to compare  dotnet core libs with lets say c++ std library.

I guess its out of scope but just wanted to know if this topic came up on your end.

**Comment by adamsitnik** [comment]
Hello @JanEggers 

I've never done such comparison myself. The closest thing that comes to my mind are [The Computer Language Benchmarks Game](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/csharpcore-gpp.html)

I think that the best place to ask this question would be most probably StackOverflow where both C# and C++ experts share their knowledge. Having said that, I am going close this issue as it's not related directly to BenchmarkDotNet.
