### ISSUE TITLE
Params attribute doesn`t work in F# if you specify more than one enum value in constructor

### ISSUE THREAD

**Issue by isaevdan** [dotnet/BenchmarkDotNet#1262]
Benchmark fails with error:   
Cannot implicitly convert type 'int' to 'Test.TestParam'. An explicit conversion exists (are you missing a cast?)

Here is code:

```
type TestParam = | A = 0 | B = 1

type IntroParams() =
    [<Params(TestParam.A, TestParam.B)>]
    member val A = TestParam.A with get, set

    [<Benchmark>]
    member this.Benchmark() =  Thread.Sleep((int)(this.A));
```

If you specify only  `[<Params(TestParam.A)>] `works fine. Looks like it converts values to int if there is more that one value. In C# everything works good

**Comment by gsomix** [comment]
@isaevdan I'll take a look. Thanks for reporting!

**Comment by gsomix** [comment]
Currently blocked on https://github.com/dotnet/fsharp/issues/995

**Comment by isaevdan** [comment]
@gsomix is there a way to workaround this in BenchmarkDotNet? If we know a type of a field to which this attribute is attached we can explicitly cast in case of enums

**Comment by gsomix** [comment]
@isaevdan Yes, indeed. But it may require substantial changes in the code. I'd prefer fix F# compiler instead, but, yeah, let me see. I will write you little later.

P.S. You may also try `ParamsAllValues` attribute for when you need all values from enum.

**Comment by isaevdan** [comment]
Thanks for reply. 
Yes I know about `ParamsAllValues` , but it is not always a case that you want to test it with all values. And if you use `ParamsAllValues` and then want to experiment with couple of values you need to change your test back to use int.

Indeed fix of F# compiler sounds like right solution, however I see this related issue is open for more than 3 years. So I`m not sure if it is something visible in near future or at all :(

**Comment by gsomix** [comment]
@isaevdan OK, let's fix it in BenchmarkDotNet then. It seems I figured out what to do. :)

**Comment by isaevdan** [comment]
@gsomix Great, thank you :)
