### ISSUE TITLE
Unable to Build Solution

### ISSUE THREAD

**Issue by luckerby** [dotnet/BenchmarkDotNet#1267]
I'm using Visual Studio Enterprise 2019 Preview (v16.4.0 Preview 1.0 - current as of today 10/2/2019). I've made sure both .NET Core SDK 2.1 (v2.1.802 is current) and the "F# language support" was installed (according to option A [here](https://benchmarkdotnet.org/articles/contributing/building.html)), cloned the BenchmarkDotNet repository and then tried building the solution.

Didn't make it very far though - ran into a block of errors (below). The one highlighted typically complains that the output dll for at least one project (I believe) wasn't generated.
![image](https://user-images.githubusercontent.com/31319583/66057441-5f899d80-e541-11e9-96d2-5bbf28e5ae19.png)

I've uploaded the complete VS build output [here](https://gist.github.com/luckerby/3d2df9b8e8e7f251c545d8b47fab6d32).

Dose anyone have any pointers into what I might be doing wrong ? I'm suspecting it's something simple that ripples into those 66 errors seen.

**Comment by stanciuadrian** [comment]
@luckerby : you could try to apply the fixes from the referenced PR.

**Comment by andresrsanchez** [comment]
There is the [roslyn bug](https://github.com/dotnet/roslyn/issues/39007), i think that we can build the solution without VS v16.4.0 Preview 1.0 version specifically

**Comment by adamsitnik** [comment]
@luckerby could you please download the latest changes and test if #1268 has solved the problem for you?

**Comment by luckerby** [comment]
@adamsitnik @andresrsanchez @stanciuadrian thank you for your quick replies. I've just got the latest commit and tried building: the operator errors are indeed gone, but I still run into the missing DLLs issues:

![image](https://user-images.githubusercontent.com/31319583/66114021-a1185800-e5d6-11e9-82f4-ab2466f2b82c.png)

Verbose output build is [here](https://gist.github.com/luckerby/1cd67e77f8b659dbc7b7bb56bba85ac9).

**Comment by stanciuadrian** [comment]
If I look at the end of the verbose output I understand the build was successful but somehow VS keeps showing errors:

```
17>Build succeeded.
[...]
17>    54 Warning(s)
17>    0 Error(s)
17>
17>Time Elapsed 00:00:21.12
========== Build: 18 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

Does `msbuild BenchmarkDotNet.sln` indicate success when executed from the solution directory?

**Comment by luckerby** [comment]
@stanciuadrian Good catch ! It looks like all the errors are due to the F# tests (below). There are some C# issues as well, but only warnings.

![image](https://user-images.githubusercontent.com/31319583/66120141-db87f200-e5e2-11e9-864c-074a73f980e3.png)

**Comment by luckerby** [comment]
I'm starting to suspect a VS glitch. Out of the blue there are no more errors:
![image](https://user-images.githubusercontent.com/31319583/66132634-092e6480-e5fe-11e9-920c-ca82167d0eb3.png)

Most of the tests are also passing as well:
![image](https://user-images.githubusercontent.com/31319583/66132724-2e22d780-e5fe-11e9-9298-28cc23619e0d.png)


I will test in a few hours on a different machine and post back the results.

**Comment by luckerby** [comment]
Just opened the latest version of `BenchmarkDotNet.sln` using the same versions of the components (VS v16.4.0 Preview 1.0 / .NET Core SDK 2.1 (v2.1.802)) on a second machine with the same OS (Windows 10 x64). No attempt to build the solution was made - as a matter of fact, no key was pressed to interfere in any way. After NuGet finished processing packages (Package Manager output [here](https://gist.github.com/luckerby/83d4a4fe34e4224cad50d4f0b73ba34e)), the same set of errors were displayed. All errors pertain to F#, while the 2 warnings are visible below: 
![image](https://user-images.githubusercontent.com/31319583/66147787-338d1b80-e618-11e9-92db-b8b2d15d53ae.png).

Next, the solution is built. This completes successfully, with only some C# warnings, plus the original 2 NuGet warnings and 63 errors displayed previously:
![image](https://user-images.githubusercontent.com/31319583/66148077-d04fb900-e618-11e9-9c94-20b718069fa4.png)

Next, all the tests are run. 13 are still failing. The first 2 seem to have a clear cause, and would probably go away if the folder is moved closer to the root. For the other, not so sure:
![image](https://user-images.githubusercontent.com/31319583/66152041-3a6c5c00-e621-11e9-9da5-7f570914daca.png)

**Comment by luckerby** [comment]
Despite the solution building ok now, there are still tests failing. For the ones that failed with a "path too long exception", I easily fixed it by moving the solution folder directly under root (+ensured correct permissions).

I'm still seeing 8 failing, out of which 4 seem to reference a hard-coded folder path:
![image](https://user-images.githubusercontent.com/31319583/66468294-95250e00-ea8e-11e9-8fcf-4686f186adf9.png)

It appears that there aren't a contiguous group of tests that fail - pointing to a missing artifact that gets invoked (eg a disassembler). An example below:
![image](https://user-images.githubusercontent.com/31319583/66468356-b0901900-ea8e-11e9-8129-76b4b4a2a1d1.png)

**Comment by stanciuadrian** [comment]
Regarding the `DirectoryNotFoundException` exceptions you can read about the test requirements in the top comments of the files:

Here is one for reference:

```csharp
    /// <summary>
    /// to run these tests please clone and build CoreRT first,
    /// then update the hardcoded path
    /// and run following command from console:
    /// dotnet test -c Release -f netcoreapp2.1 --filter "FullyQualifiedName~BenchmarkDotNet.IntegrationTests.ManualRunning.LocalCoreRtToolchainTests"
    ///
    /// in perfect world we would do this OOB for you, but building CoreRT
    /// so it's not part of our CI jobs
    /// </summary>
```

I didn't have time to investigate the other 4 tests. Maybe @adamsitnik  can help?

**Comment by adamsitnik** [comment]
@stanciuadrian is right about the `ManualRunning` benchmarks which have simply some hardcoded values

the `ImmutableConfig` test is most probably failing due to running it `Debug` configuration:

https://github.com/dotnet/BenchmarkDotNet/blob/64cc94a8c9b22acebf7f43124929fe39c309c8e1/src/BenchmarkDotNet/Configs/DefaultConfig.cs#L62-L64

to make it easier to contribute to BDN we just disable the validator for that enforces optimized builds in Debug (which is tested by the failing tests)

The `DisassemblyDiagnoser` and `TailCallDiagnosers` are  failing either due to `Debug`  or lack of Admin privileges.

You can use these two scripts to run the tests locally:

https://github.com/dotnet/BenchmarkDotNet/blob/64cc94a8c9b22acebf7f43124929fe39c309c8e1/tests/runClassicTests.cmd
https://github.com/dotnet/BenchmarkDotNet/blob/64cc94a8c9b22acebf7f43124929fe39c309c8e1/tests/runCoreTests.cmd
