### ISSUE TITLE
Unable to show full param string in the report

### ISSUE THREAD

**Issue by valentinoNguyen** [dotnet/BenchmarkDotNet#1269]
I need to run benchmark against some sql queries which have a complex type input parameter. I override the ToString() on the class, but in the report (in any type, my target type is csv and html), the param column is truncated by `(...)`, for ex `[Meas(...)mber] [61]`
Is there any config that allow library to show full param text there?
Thank you!!!

**Comment by adamsitnik** [comment]
Hello @valentinoNguyen 

I've run into the same problem recently and fixed it today with #1265 

Before we release the official package to NuGet.org you can download our latest bits from our [CI feed](https://benchmarkdotnet.org/articles/guides/nuget.html#nightly):

```xml
<packageSources>
  <add key="bdn-ci" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

With the latest bits you can set the max width (so far it was hardocded to 20):

```cs
var config = DefaultConfig.Instance.With(SummaryStyle.Default.WithMaxParameterColumnWidth(100));
```

**Comment by valentinoNguyen** [comment]
I set new nuget source to https://ci.appveyor.com/nuget/benchmarkdotnet
But cannot see the nightly build there, latest version is still 0.11.5.1189
When is it available ? 
Thank you !

**Comment by adamsitnik** [comment]
`0.11.5.1189` is the version that contains the new feature. Could you give it a try and let me know if it works as expected?

**Comment by valentinoNguyen** [comment]
worked as expected ;-) Thank you !

**Comment by bitbonk** [comment]
I just hit the same problem. When will we see this `WithMaxParameterColumnWidth` in package on nuget.org?

**Comment by valentinoNguyen** [comment]
I afraid there are no way to disable it. You can try `0.11.5.1189`
But be careful, I got a big problem on that version when the same code but the test run hundred of time even if I am using Dry mode :(
