### ISSUE TITLE
Docs for SummaryStyle

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1270]
While working on #1265 I've realized that we don't have any docs for `SummaryStyle` which allows for few interesting customizations. It would be great to have some.

**Comment by wojtpl2** [comment]
How about adding Hacktoberfest label?

Info from https://hacktoberfest.digitalocean.com/faq
>**As a maintainer, how do I encourage contributions to my repos?**
>Create issues for anything you’d like contributors to help with, making sure to give them a Hacktoberfest label so they’re easier to discover.
>You can also share issues or repositories on Twitter, using #Hacktoberfest where we’ll retweet as many as we can for contributors to see.

**Comment by adamsitnik** [comment]
@wojtpl2 done!

**Comment by Oxylibrium** [comment]
Hihi, noticed your project on the Hacktoberfest site - can I work on it over the weekend after I get familiar with the docstyle and stuff?

**Comment by adamsitnik** [comment]
@Oxylibrium sure!

Our samples are typically C# code added to our samples project [here](https://github.com/dotnet/BenchmarkDotNet/tree/master/samples/BenchmarkDotNet.Samples) and an `.md` page added [here](https://github.com/dotnet/BenchmarkDotNet/tree/master/docs/articles/samples)

Please let me know if you need any help and thanks in advance!

**Comment by Oxylibrium** [comment]
Sorry I had to drop out on it :(
Fell really ill and now I need to catch up on IRL stuff too, apologies ,w,

**Comment by adamsitnik** [comment]
@Oxylibrium no problem! thanks for letting me know
