### ISSUE TITLE
[Question] Multithreading configuration

### ISSUE THREAD

**Issue by MBurtsev** [dotnet/BenchmarkDotNet#1271]
Hi. I am trying to make a benchmark for a multi-threaded data structure. After reading the documentation, I still have a misunderstanding about the configuration.

1. The first is how to run without source. I have several hardware (x64), everywhere windows and netcore 3. I need to run the benchmark without source.
2. No parallel processes, only one process.
3. Only one thread should run the benchmark at some time. There should be no parallel start.

Thanks

**Comment by adamsitnik** [comment]
Hello @nim !

> The first is how to run without source.

By default BenchmarkDotNet generates, builds and run every benchmark in a stand-alone process. We do that to achieve process-level isolation which helps to prevent one benchmark affect another (imagine few benchmarks executed in the same process and one of them having a memory leak, or opening too many files etc)

To run without source you need to use [InProcessToolchain](https://benchmarkdotnet.org/articles/samples/IntroInProcess.html), publish a self-contained app (`dotnet publish -c Release --self-contained -r win-x64`), copy the files to given machine and run the self-contained app.

> No parallel processes, only one process.
> Only one thread should run the benchmark at some time. There should be no parallel start.

BenchmarkDotNet runs the benchmarks sequentially by default and as of today, this is the only option.

**Comment by adamsitnik** [comment]
The question was answered a long time ago but the issue was not closed, so I am closing it now.
