### ISSUE TITLE
How to config running each test only 1 time

### ISSUE THREAD

**Issue by valentinoNguyen** [dotnet/BenchmarkDotNet#1274]
Hi, Is there any way to config benchmark run each test only 1 time or at least very small number of time running each test?

I tried to setup benchmark under `Job.ShortRun` or `[SimpleJob(launchCount: 1, warmupCount: 1, targetCount: 1, invocationCount:100, id: "QuickJob")]`

But it still runs a lot of time for each test. 
Thank you!

**Comment by AndreyAkinshin** [comment]
@valentinoNguyen before BenchmarkDotNet starts to execute actual iterations, it performs a few additional stages like Jitting, Pilot, and Warmup. Plus, we have additional iterations for overhead evaluation. If you want to disable all of these iterations, you should use `RunStrategy.ColdStart`. Here is an example:
```cs
[SimpleJob(RunStrategy.ColdStart, launchCount: 1, warmupCount: 0, targetCount: 1, invocationCount:100, id: "QuickJob")]
```
It will perform a single iteration that contains 100 invocations of your method. If you want to invoke your method only once, you should set `invocationCount = 1`. Here is an example:
```cs
[SimpleJob(RunStrategy.ColdStart, launchCount: 1, warmupCount: 0, targetCount: 1, invocationCount:1, id: "QuickJob")]
```

See also some relevant pages in the official BenchmarkDotNet documentation: [IntroColdStart](https://benchmarkdotnet.org/articles/samples/IntroColdStart.html), [How it works](https://benchmarkdotnet.org/articles/guides/how-it-works.html).
