### ISSUE TITLE
Why the report doesn't show values for allocated memory on mono

### ISSUE THREAD

**Issue by mariangemarcano** [dotnet/BenchmarkDotNet#1275]
Hi!, in this [repo](https://github.com/mariangemarcano/mariangemarcano.github.io/tree/master/projects/C%23/Algorithms) I'm trying out benchmarks for .net core versus mono, but I don't get any allocated memory results on mono, do you know why?

Thanks!

**Comment by wojtpl2** [comment]
There you can find information https://benchmarkdotnet.org/articles/configs/diagnosers.html
>Mono currently [does not](https://stackoverflow.com/questions/40234948/how-to-get-the-number-of-allocated-bytes-in-mono) expose any api to get the number of allocated bytes. That's why our Mono users will get ? in Allocated column.
