### ISSUE TITLE
Loading embedded resource

### ISSUE THREAD

**Issue by AlexeyLyndin** [dotnet/BenchmarkDotNet#1278]
Hi all! Are there any known issues with loading embedded resources in benchmark method?
I got small method that loads embeded resource:

using (var stream = GetType().Assembly.GetManifestResourceStream("SomeResource"))
using (var reader = new StreamReader(stream))
{
    return reader.ReadToEnd();
}
 Benchmark class marked with `InProcessAttribute`
As a result of benchmark run I see `System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
at System.Reflection.Emit.InternalAssemblyBuilder.GetManifestResourceStream(String name)
at ResourceLoad.SqlRetriever.GetSqlAsEmbeddedResource()
` 
![image](https://user-images.githubusercontent.com/10416269/66707652-650a9300-ed4c-11e9-8b54-644e3cdfb239.png)

**Comment by wojtpl2** [comment]
You can try to use typeof(YOURTYPE).GetType().... instead of GetType().

**Comment by AlexeyLyndin** [comment]
@wojtpl2 thanks a lot! Closing this.
