### ISSUE TITLE
Understanding the BenchmarkDotNet output

### ISSUE THREAD

**Issue by bitbonk** [dotnet/BenchmarkDotNet#1282]
When I run a simple benchmark I get an output that starts with *WorkloadWarmup* iterations output followed by *WorkloadActual* iterations output followed by *WorkloadResult* iterations output and at the end there is always an entry about garbage collection in the form *GC:*  *3* *1* *0* *10707640* *1*.

I have the following questions about this:

1. Why are there warmup iterations? Is it to make sure the tiered JIT compilation has really compiled the actual benchmark method to its full extend? Is there a list of things that potentially can make a warmup phase necessary?
2. What is *WorkloadResult* for? I understand that the actual measurement is done in *WorkloadActual*. Why these extra iterations at the end after everything has seemingly been done.
3. What do space separated numbers in *GC:*  *3* *1* *0* *10707640* *1* mean?
4. How do you measure the time of an operation? Are you simply calculating the average from all operations in an iteration? Are you using the `StopWatch` class for measurement? What additional trickery are you doing to get a good time measurement?

**Comment by adamsitnik** [comment]
Hi @bitbonk 

We have an explanation for that in our docs: https://benchmarkdotnet.org/articles/guides/how-it-works.html

Please let me know if the doc page answers all your questions.

**Comment by bitbonk** [comment]
I have read this documentation and also tried to parse the pseudocode there before I came here. I don't think it answers any of my specific questions.

**Comment by adamsitnik** [comment]
> I'd be interested to understand why it is necessary to have warmup iterations. Is it just for the JIT compilation?

We can't make any assumptions about the benchmarked code: if it's using some cache or any heuristics that affect the execution time so we run the Wamup stage until the results get stable (afair the minimum number of warmup iterations is six).

The advantage of this is that we got Tiered JIT support out of the box, without any changes to the source code of BenchmarkDotNet.

You obviously might not need 6 warmup iterations for some simple benchmarks, but BDN does not know anything about the code before running it and moreover we don't store any state. If you know that 1 warmup iteration is enough, you can configure BDN to run only 1. This is what do for example in dotnet/performance repo:

https://github.com/dotnet/performance/blob/b4c3472ca63686d2a1824d8237dce1d3a5ea46d7/src/harness/BenchmarkDotNet.Extensions/RecommendedConfig.cs#L24

> What is WorkloadResult for? I understand that the actual measurement is done in WorkloadActual. Why these extra iterations at the end after everything has seemingly been don

From the docs:

> `Result = ActualWorkload - <AverageOverhead>`

No extra work is performed, we just subtract overhead from the workload result and this gives us the final result which is used to calculate the values presented in Summary table

> What do space separated numbers in GC: 3 1 0 10707640 1 mean?

This is just intermediate BenchmarkDotNet output, basically, the benchmark process reports all results to the host process using console output. If are using MemoryDiagnoser you should just focus on the results printed in the Summary table and explanation in the Legend

|    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|---------:|---------:|---------:|----------:|
|   0.0975 |        - |        - |     768 B |
|   0.0978 |        - |        - |     768 B |
|          |          |          |           |
|   0.0631 |        - |        - |     496 B |
|   0.0631 |        - |        - |     496 B |
|          |          |          |           |
|  61.3636 |  61.3636 |  61.3636 |  409992 B |
|  61.6776 |  61.6776 |  61.6776 |  409996 B |
|          |          |          |           |
| 123.9224 | 123.9224 | 123.9224 |  400096 B |
| 124.2284 | 124.2284 | 124.2284 |  400096 B |

```log
// * Legends *
  Gen 0     : GC Generation 0 collects per 1000 operations
  Gen 1     : GC Generation 1 collects per 1000 operations
  Gen 2     : GC Generation 2 collects per 1000 operations
  Allocated : Allocated memory per single operation (managed only, inclusive, 1KB = 1024B)
```

> How do you measure the time of an operation? Are you simply calculating the average from all operations in an iteration? 

Yes. You can read more about central limit theorem in @AndreyAkinshin book: [Pro .NET Benchmarking](https://learning.oreilly.com/library/view/pro-net-benchmarking/9781484249413/html/437795_1_En_4_Chapter.xhtml).

> Are you using the StopWatch class for measurement? What additional trickery are you doing to get a good time measurement?

On Windows we call WinAPI directly, on other systems we use `StopWatch`.

https://github.com/dotnet/BenchmarkDotNet/blob/e8bf99272bc410601863bda338b57d0c46baad70/src/BenchmarkDotNet/Horology/Chronometer.cs#L19-L25

**Comment by bitbonk** [comment]
Thank you very much for the detailed answer. 👍
