### ISSUE TITLE
Group by benchmark class in joined summary

### ISSUE THREAD

**Issue by JeffreyZhao** [dotnet/BenchmarkDotNet#1284]
Let's say I have a benchmark like:

```csharp
public class MyBenchmark1
{
    [Benchmark]
    public int A() { /* ... */ }

    [Benchmark]
    public int B() { /* ... */ }
}

public class MyBenchmark2
{
    [Benchmark]
    public int A() { /* ... */ }

    [Benchmark]
    public int B() { /* ... */ }
}
```

When I run with `--join` it shows a summary like:

|         Type | Method |      Mean |     Error |    StdDev |
|------------- |------- |----------:|----------:|----------:|
| MyBenchmark1 |      A |  6.536 ns | 0.0768 ns | 0.0680 ns |
| MyBenchmark2 |      A | 27.053 ns | 0.2639 ns | 0.2469 ns |
| MyBenchmark1 |      B |  1.450 ns | 0.0439 ns | 0.0411 ns |
| MyBenchmark2 |      B | 33.090 ns | 0.5051 ns | 0.4477 ns |

Is it possible to let it group by benchmark class so it shows like:

|         Type | Method |      Mean |     Error |    StdDev |
|------------- |------- |----------:|----------:|----------:|
| MyBenchmark1 |      A |  6.536 ns | 0.0768 ns | 0.0680 ns |
| MyBenchmark1 |      B |  1.450 ns | 0.0439 ns | 0.0411 ns |
|              |        |           |           |           |
| MyBenchmark2 |      A | 27.053 ns | 0.2639 ns | 0.2469 ns |
| MyBenchmark2 |      B | 33.090 ns | 0.5051 ns | 0.4477 ns |

**Comment by adamsitnik** [comment]
Hi @JeffreyZhao 

Please excuse me for the delay...

It's possible by using `SummaryOrderPolicy.Declared`:

```cs
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Order;

namespace BenchmarkDotNet.Samples
{
    public class Program
    {
        public static void Main(string[] args)
            => BenchmarkSwitcher
                .FromAssembly(typeof(Program).Assembly)
                .Run(args, DefaultConfig.Instance.WithOrderer(new DefaultOrderer(SummaryOrderPolicy.Declared, MethodOrderPolicy.Declared)));
    }

    public class MyBenchmark1
    {
        [Benchmark]
        public void A() { /* ... */ }

        [Benchmark]
        public void B() { /* ... */ }
    }

    public class MyBenchmark2
    {
        [Benchmark]
        public void A() { /* ... */ }

        [Benchmark]
        public void B() { /* ... */ }
    }
}
```

The results I got for the following command:

```cmd
dotnet run -c Release -f net461 --filter *MyBenchmark* --join --job dry
```

|         Type | Method |     Mean | Error |
|------------- |------- |---------:|------:|
| MyBenchmark1 |      A | 296.2 us |    NA |
| MyBenchmark1 |      B | 280.7 us |    NA |
| MyBenchmark2 |      A | 318.6 us |    NA |
| MyBenchmark2 |      B | 436.9 us |    NA |
