### ISSUE TITLE
How to config to not save .log files?

### ISSUE THREAD

**Issue by silkfire** [dotnet/BenchmarkDotNet#1289]
I don't like the .log files littering my output directory, is there a way to not generate them on every benchmark run?

I've tried to disable exporters but that didn't help.

**Comment by adamsitnik** [comment]
This was implemented in https://github.com/dotnet/BenchmarkDotNet/pull/1252 and released as part of 0.12.0 to nuget.org today. Please update.

**Comment by silkfire** [comment]
Thanks, @adamsitnik. I just upgraded to v0.12.0, but it seems that the `Set` method on `Options` doesn't exist. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/1554615/67511604-96ae2300-f697-11e9-92f9-da62fc8ff573.png)

**Comment by adamsitnik** [comment]
ups, the `Set` method is internal

https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Configs/ConfigOptions.cs#L42

The good news is that you can just call `Options = ConfigOptions.DisableLogFile;`

/cc @CodeTherapist
