### ISSUE TITLE
BenchmarkRunner should support parsing console line arguments

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1290]
As of today, only `BenchmarkSwitcher` supports console line arguments.

`BenchmarkRunner` should support it as well.

It would be also great to detect a situation when a user has passed some BDN arguments to the console app but forgot to pass it to BDN. We could do it by checking the `Environment.GetCommandLineArgs()`. I've seen it happen many times ;)

**Comment by chan18** [comment]
Hey, @adamsitnik , looks like pretty good first issue.

if i understand correctly, need to parse/check args passed to ``` BenchmarkRunner  ``` CLI!

What you mean by BDN arguments? BDN?

**Comment by adamsitnik** [comment]
Hello @chan18 

As of today, our users can pass `args` from `Main` only to `BenchmarkSwitcher`:

https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs#L56

The goal of this issue is to extend `BenchmarkRunner.Run` with a possibility to accept `args` as well:

https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Running/BenchmarkRunnerDirty.cs#L20

```cs
Before:

static void Main(string[] args) 
    => BenchmarkRunner.Run(typeof(Program).Assembly);

```

**Comment by chan18** [comment]
i believe passing args to  
```
 static void Main(string[] args) 
    => BenchmarkRunner.Run(typeof(Program).Assembly, args);
``` 
is not enough.

* need to handle them?( implementing what each args need to do) and related test cases!
* What are valid args? for BenchmarkRunner.run().

**Comment by adamsitnik** [comment]
> need to handle them
> What are valid args

I am sorry for not making it clear. Yes, handling the args is part of the task.

You can take a look at how we handle it in BenchmarkSwitcher:

https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs#L69

After the args are parsed successfully, you merge the passed and parsed args:

https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs#L79

And pass it further like BenchmarkRunner was doing so far

**Comment by chan18** [comment]
``` BenchmarkSwitcher.cs `` is using ``` filteredBenchmarks ``` from 
``` 
  var benchmarksToFilter = options.UserProvidedFilters
                ? allAvailableTypesWithRunnableBenchmarks
                : userInteraction.AskUser(allAvailableTypesWithRunnableBenchmarks, logger);
```
 where has  ``` BenchmarkRunner  ``` is using 
``` BenchmarkConverter.TypeToBenchmarks(type, config) ``` 
which intern uses  it's won ``` filteredBenchmarks ``` from config. 
I think it has to be the same for ``` BenchmarkRunner  ```.

**Comment by adamsitnik** [comment]
Hmm I think that if the user has provided some filters, then they should be used first. If none were provided, then we should use the current BenchmarkRunner behaviour

**Comment by chan18** [comment]
so, 
https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs#L109

and 

https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Running/BenchmarkRunnerDirty.cs#L77

is not the same thing?

i mean, ``` BenchmarkRunnerClean.Run(filteredBenchmarks); ``` we just pass it to the Switcher.
in case of runner, it is using, 
``` BenchmarkRunnerClean.Run(new[] { BenchmarkConverter.TypeToBenchmarks(type, config) }).Single() ```, which has it own method.

the only place to check and use user filters or current BenchmarkRunner behaviour is in 
https://github.com/dotnet/BenchmarkDotNet/blob/7e3efce463c8a6d7f54a5022456a15da0f12433d/src/BenchmarkDotNet/Running/BenchmarkConverter.cs#L78

**Comment by chan18** [comment]
@adamsitnik i think this will address the overloading. Please check/review the code. 
Thank you!

**Comment by stanciuadrian** [comment]
can this issue be closed?
