### ISSUE TITLE
MemoryDiagnoser reports weird results for .NET Core 3.0

### ISSUE THREAD

**Issue by antrv** [dotnet/BenchmarkDotNet#1291]
Hi
I'm running the same benchmarks for .NET 4.8 and .NET Core 3.0.
The benchmarked method allocates MemoryStream with 200MB capacity and then fills it with data.

MemoryDiagnoser reports about this allocation correctly for .NET 4.8: Allocated Bytes =  204832.12 KB, but shows strange results for .NET Core 3.0: Allocated Bytes = 27.8 KB.

**Comment by adamsitnik** [comment]
Hello @antrv 

Please see https://github.com/dotnet/BenchmarkDotNet/pull/1155 for a full answer

We have published a `0.12.0` version that uses the new .NET Core 3.0 API 1h ago. Please update.
