### ISSUE TITLE
[Questions] Using BenchmarkDotNet for performance regression tests

### ISSUE THREAD

**Issue by iitaiy** [dotnet/BenchmarkDotNet#1299]
Hi,

I want to use the BenchmarkDotNet for performance regression tests.
For example, check that run of method doesn't take more than 500 ms.
Do you have an example of it?

In addition, how do you measure the time of each operation? Do you use stopwatch? Or do you use Process.TotalProcesserTime?

Thank you for the help,
Itai

**Comment by adamsitnik** [comment]
Hi @iitaiy 

> Do you have an example of it?

We don't have such example. You would have to use the result returned by `BenchmarkRunner` or `BenchmarkSwitcher`, find the results for the given benchmark, and add an assert.

> In addition, how do you measure the time of each operation? Do you use stopwatch? Or do you use Process.TotalProcesserTime?

This doc explains briefly how BDN works: https://benchmarkdotnet.org/articles/guides/how-it-works.html

Thanks,
Adam
