### ISSUE TITLE
Finer-grained test selection on the cmd-line

### ISSUE THREAD

**Issue by mattwarren** [dotnet/BenchmarkDotNet#130]
From @jskeet suggestions in #83, implement:

Finer-grained test selection, when running from the command line, ability to select:
- [X] Individual test methods
- [X] Types in an attribute-based category
- [X] Methods in an attribute-based category
- [X] Individual test classes (already implemented, i.e. `Benchmark.exe #10')
- [X] Test classes/methods matching a pattern (regex or globbing?)

This will extend that work that `BenchmarkSwitcher` already does, therefore it will only apply when running benchmarks with the `BenchmarkSwitcher` class.

**Comment by jskeet** [comment]
Idea as discussed offline - follow the NUnit 3 "general predicate" approach, possibly with common shortcuts. So we could have

```text
foo.exe --where "cat == bar || cat == baz"
```

**Comment by mattwarren** [comment]
wow, that was a quick response, yeah that's a nice api. 

I assume you would also wants things like:

```
foo.exe --where "class == SomeBenchmark"
```
and 
```
foo.exe --where "namespace == NodaTime.PerformanceBenchmarks"
```
and 
```
foo.exe --where "namespace == *PerformanceBenchmarks.*"
```

So the special names (or common shortcuts) could be:
- `class`
- `namespace`
- `attribute`/`category`

Any others that would be useful?

**Comment by adamsitnik** [comment]
I like the xUnit console runner convention:

```
  -method "name"         : run a given test method (should be fully specified;
                         : i.e., 'MyNamespace.MyClass.MyTestMethod')
                         : if specified more than once, acts as an OR operation
  -class "name"          : run all methods in a given test class (should be fully
                         : specified; i.e., 'MyNamespace.MyClass')
                         : if specified more than once, acts as an OR operation
  -namespace "name"      : run all methods in a given namespace (i.e.,
                         : 'MyNamespace.MySubNamespace')
                         : if specified more than once, acts as an OR operation
```

**Comment by jskeet** [comment]
I think it's useful to have shortcut arguments *as well*, but a flexible query format is useful and easily extensible.

As an aside, I'd like to be able to specify a short name for a class or method as well as the fully-qualified name. That's almost *always* more convenient.

**Comment by mattwarren** [comment]
> I think it's useful to have shortcut arguments as well, but a flexible query format is useful and easily extensible.

Yeah I agree, I'll implement short and long arguments, i.e. `--method "name"` (just equals) and `--where "method == name"`. Then in the future I'll might add things like `!=` or `contains` if there's any demand for more flexibility.

> As an aside, I'd like to be able to specify a short name for a class or method as well as the fully-qualified name. That's almost always more convenient.

Yeah I'll implement this as well, it really annoys me when a tool forces my to type the FQN!

**Comment by jskeet** [comment]
Definitely implement `!=` - certainly for unit testing, I find myself wanting to *exclude* things more often than *including* them.

Thanks for all of this - much appreciated :)

**Comment by mattwarren** [comment]
Still W.I.P, but after d6a55c5, we now support methods, classes and namespace (1 or more), i.e. :

- `method=Method1,Method2` and `method=Namespace.Class.Method1`
- `class="ClassB,ClassD` and `class=Namespace.ClassB`
- `namespace=MyNamespace,MyOtherNamespace`

Also allows plurals (just to be nice), i.e. `methods=`, `classes=` and `namespaces=`

**Comment by mattwarren** [comment]
Can now match tests that have a specified attributes, long and short form, i.e.
- `attribute=Run` or `attribute=RunAttribute`

**Comment by AndreyAkinshin** [comment]
@mattwarren, do we have any unresolved problems in this issue?

**Comment by adamsitnik** [comment]
I think that I have fixed the last remaining issues today, closing
