### ISSUE TITLE
Copy UserSecrets from benchmark project

### ISSUE THREAD

**Issue by kant2002** [dotnet/BenchmarkDotNet#1305]
If I understand correctly you create special projects which compiled on the fly to make benchmarking properly. I manage some configuration data using User Secrets and newly created projects does not have User Secrets attribute attached to it.

Would be good to copy UseSecrets attribute to the generated projects so they have access to this features during testing.

**Comment by adamsitnik** [comment]
Hi @kant2002 

Could you please provide a small repro? A simple project file with a benchmark that uses the secrets would be perfect (I don't know how to repro the problem and how to test it)

**Comment by wdolek** [comment]
Hi @kant2002, tried to reproduce your issue using both:

- `<UserSecretsId>...</UserSecretsId>` in `.csproj`
- `[assembly:UserSecretsId("...")]`

but benchmark got loaded properly (and value from user secrets has been read). As you say, there's temporary project created (`BenchmarkDotNet.Autogenerated.csproj`), but that one just references original project.

Could you please provide code which reproduces this issue?

**Comment by kant2002** [comment]
Thanks for reminder. Let me make repro. I temporary forgot about it.

**Comment by kant2002** [comment]
See https://github.com/kant2002/BenchDotNetUserSecrets for example how to reproduce the issue
Expectations after `dotnet run -c Release`

## No override

```
|            Method |          Mean |      Error |     StdDev |        Median |
|------------------ |--------------:|-----------:|-----------:|--------------:|
|  PlaceSimplestBet | 2,241.1217 ns | 38.7874 ns | 55.6278 ns | 2,246.3150 ns |
| PlaceSimplestBet2 |     0.0143 ns |  0.0201 ns |  0.0294 ns |     0.0000 ns |
```

Values significantly different

## Override in UserSecrets

`secrets.json`
```
{
  "UseStatic": "true"
}
```

Expectations
```
|            Method |      Mean |     Error |    StdDev |    Median |
|------------------ |----------:|----------:|----------:|----------:|
|  PlaceSimplestBet | 1.3752 ns | 0.1149 ns | 0.1720 ns | 1.4258 ns |
| PlaceSimplestBet2 | 0.0206 ns | 0.0172 ns | 0.0252 ns | 0.0000 ns |
```
Two values close to each other. Comparable to version without overrides.

Unless I'm missing something very obvious, but I canot make it work.
1. I have launchsettings.sjon with DOTNET_ENVIRONMENT=Development
2. Try set $env:DOTNET_ENVIRONMENT=Development from Powershell

All no luck with released version. Only after small fix in suggested PR it start working.

**Comment by wdolek** [comment]
@kant2002 Nice! Wanted to suggest that change but then wasn't able to reproduce your issue - I was creating configuration (including calling of `AddUserSecrets`) manually, so I _guess_ I didn't mimic host environment behavior properly.

**Comment by kant2002** [comment]
Man find the bug - man fix the bug :smile:
