### ISSUE TITLE
Strange float performance issues near zero

### ISSUE THREAD

**Issue by xposure** [dotnet/BenchmarkDotNet#1308]
Wasn't sure where else to ask this and I figured a lot of people here have experience with benchmarks showing odd behaviors. 

In short, I have a benchmark that does nothing more than multiple a vector float by a const value of 0.016. After several iterations of the benchmark, it becomes almost 10x slower. I must be something to do with the float approaching zero but I have no idea. I couldn't find anything on google that would explain a linear float operation not being a constant operation.

Here is a couple line project that reproduces this issue (the README shows a benchmark log). https://github.com/xposure/FloatPerfIssue

Could anyone provide any insight as to what is happening in .NET or at the CPU level?

**Comment by xposure** [comment]
Just a note, this is on a decent desktop machine with a i7, my initial thought when i came across this is perhaps the fan on my CPU is failing and is being throttled under load or something extreme until I realized how easy this was to reproduce. 

I should note, that if you reset the data between each iteration, the problem does not exist. This is why I am assuming it has something to do with the float approach near zero and some of path being executed in the CPU.

**Comment by xposure** [comment]
Well perhaps I found the answer to my own question, but I'll leave this here for someone else to chime in for a little bit if they'd like.

This seems to be the suspect
https://stackoverflow.com/questions/9314534/why-does-changing-0-1f-to-0-slow-down-performance-by-10x

**Comment by AndreyAkinshin** [comment]
@xposure I'm glad that you found a problem!

By the way, in [Pro .NET Benchmarking](https://aakinshin.net/prodotnetbenchmarking/), you can find a whole section about denormalized numbers with reproducible examples, step-by-step explanations, and description of corner cases.
