### ISSUE TITLE
Add an option to pass environment variables to the default job

### ISSUE THREAD

**Issue by filipnavara** [dotnet/BenchmarkDotNet#1312]
When testing against the mono/netcore runtime we often want to run the actual benchmark with specific runtime configuration. This is achieved through setting the `MONO_ENV_OPTIONS` environment variable. However, we also want to use different `MONO_ENV_OPTIONS` when running `dotnet restore` or `dotnet build` for performance reasons. It would be nice to allow some way to inject the environment variables but only for the actul benchmark job.

What I currently use is the following hack:
https://github.com/filipnavara/performance/commit/d1768c7fdf52cc5905bdefce25964c08ba90f46d

/cc @EgorBo

**Comment by adamsitnik** [comment]
@EgorBo ok, so I've transferred the issue to BDN repo

@filipnavara could you please write some proposal? Would sth like this be enough?

```cmd
--envVars firstKey:firstValue secondKey:secondValue
```

**Comment by filipnavara** [comment]
> Would sth like this be enough?
> 
> ```batchfile
> --envVars firstKey:firstValue secondKey:secondValue
> ```

Yep, it would be.

**Comment by adamsitnik** [comment]
https://github.com/dotnet/BenchmarkDotNet/pull/1313
