### ISSUE TITLE
Best way to benchmark steps of recursive methods

### ISSUE THREAD

**Issue by am11** [dotnet/BenchmarkDotNet#1314]
#### General question

Is it possible to benchmark each step of recursive method separately (using annotations or manual customization)?
more fundamentally; (if we remove the recursion, by duplicating code) is there a way to separately benchmark each method, called by the main/entrypoint benchmark method?

#### Specific scenario

I am trying to benchmark "time spent on each server in HTTP redirect call chain". The method I came up with is recursive in nature (simplified and improved version of https://long2know.com/2016/07/capturing-redirects-with-httpclient/):

```c#
using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using BenchmarkDotNet.Attributes;
public sealed class Benchmarks
{
    private readonly HttpClient client = new HttpClient(new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip });

    [Benchmark]
    [Arguments("https://github.com/dotnet/source-build/archive/v3.0.101-SDK.tar.gz")]
    public async Task MakeRequestAsync(string url)
    {
        using var request = new HttpRequestMessage()
        {
            RequestUri = new Uri(url),
            Method = HttpMethod.Get
        };

        using HttpResponseMessage response = await client.SendAsync(request).ConfigureAwait(false);

        response.EnsureSuccessStatusCode();

        var statusCode = (int)response.StatusCode;

        if (statusCode >= 300 && statusCode <= 399)
        {
            await MakeRequestAsync(response.Headers.Location.ToString()).ConfigureAwait(false);
        }
    }
}
```

in my real scenario, we have fixed number of redirects (2), and thus MakeRequest will be called three times, per URL. (I don't mind having three different signatures, if that helps).

The expected benchmark result is of the form:

| Method |       Mean |     Error |    StdDev | Ratio |
|------- |-----------:|----------:|----------:|------:|
| MakeRequest_{original-url} |    |  |  |   |
| MakeRequest_{first-redirect-url} |    |  |  |   |
| MakeRequest_{second-redirect-url} |    |  |  |   |

**Comment by adamsitnik** [comment]
Hi @am11 

Benchmarking tool can tell you how long it took to execute a given code, while a profiler can tell you where the time was spent exactly.

BenchmarkDotNet was designed to allow for simple micro|nano benchmarks. So we just run the code many times and print statistics. We can't tell where the time was spent exactly, you would need to use a profiler.

If I were you I would check for some web server benchmarking tools. Most probably there is a pythong|Go|Java|.NET|C++ tool that does exactly what you need.

If you really want to use BenchmarkDotNet for this, you could use [EtwProfiler](https://adamsitnik.com/ETW-Profiler/), write your our custom [EventSource](https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Engines/EngineEventSource.cs), emit Start and Stop events, enable the provider using [EtwProfilerConfig](https://github.com/dotnet/BenchmarkDotNet/blob/0768b7206be0078516034f0e6a1690b61561c55c/src/BenchmarkDotNet.Diagnostics.Windows/EtwProfilerConfig.cs) and write your own parser similar to [this](https://github.com/dotnet/BenchmarkDotNet/blob/e92abf845ac916e449bf9d8ccf1d872204951bec/src/BenchmarkDotNet.Diagnostics.Windows/Tracing/EngineEventLogParser.cs). Your parser could do the math and print the stats that you want.

Another thing is that `https://github.com/dotnet/source-build/archive/v3.0.101-SDK.tar.gz` is most probably quite big file and takes a lot of time to download. If you really want to test redirect perf you should most probably measure the perf of hello world Web API. (so the reported time would be more about redirects and less about downloading big file)

Thanks,
Adam
