### ISSUE TITLE
The new benchmarks stuff is confusing.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/BenchmarkDotNet#1317]
Ok so I god an old benchmark project that targets:

```netstandard2.0;netcoreapp3.0;netcoreapp2.2;netcoreapp2.1;netcoreapp2.0;net461;net462;net47;net471;net472```

Before the update to the latest BDN it worked fine; after that it says ``ClrJobAttribute`` is deprecated and now it also says it does not allow ``baselike: true`` passed in it like I do in my code.

Was this change so that I could benchmark for all those targets and only compile the benchmark project in only a single target?

https://github.com/AraHaan/XmlAbstraction/blob/master/src/XmlAbstraction/benchmarks/XmlObjectBenchmarks.cs#L9-#L11

At this time I am not sure what to do. Or what to change these too.

You guys should have walked through the breaking changes and stuff though on the docs.

**Comment by adamsitnik** [comment]
> You guys should have walked through the breaking changes and stuff though on the docs.

You should have read our release notes, everything is explained there: https://benchmarkdotnet.org/changelog/v0.12.0.html

![obraz](https://user-images.githubusercontent.com/6011991/69314267-04685300-0c34-11ea-8e65-19667a8b668c.png)

https://benchmarkdotnet.org/changelog/v0.12.0.html#advanced-multiple-target-frameworks-support
