### ISSUE TITLE
[Questions] Is there a context inside Setup And Cleanup methods

### ISSUE THREAD

**Issue by asen-arizanov-86** [dotnet/BenchmarkDotNet#1319]
Hi,

Is there some kind of context inside the Setup And Cleanup methods? I need to know which is the target benchmark method.

For example NUnit provides NUnit.Framework.TestContext.CurrentContext which can be used by TestContext.CurrentContext.Test.Name.

10xs!

**Comment by adamsitnik** [comment]
Hello @asen-arizanov-86 

There is no Context, but you can tell BDN which setup belongs to which benchmark by using the `Target` property:

https://benchmarkdotnet.org/articles/features/setup-and-cleanup.html#sample-introsetupcleanuptarget

```cs
[GlobalSetup(Target = nameof(BenchmarkA))]
public void GlobalSetupA()
    => Console.WriteLine("// " + "GlobalSetup A");

[Benchmark]
public void BenchmarkA()
    => Console.WriteLine("// " + "Benchmark A");

[GlobalSetup(Targets = new[] { nameof(BenchmarkB), nameof(BenchmarkC) })]
public void GlobalSetupB()
    => Console.WriteLine("// " + "GlobalSetup B");

[Benchmark]
public void BenchmarkB()
    => Console.WriteLine("// " + "Benchmark B");

[Benchmark]
public void BenchmarkC()
    => Console.WriteLine("// " + "Benchmark C");
