### ISSUE TITLE
Surface native code size benchmarked code

### ISSUE THREAD

**Issue by damageboy** [dotnet/BenchmarkDotNet#1325]
As we all know, we all **need** to care more about native code-size of our (benchmarked) code.

Currently, there is not enough attention given to this metric and to its importance in evaluating performance of a given benchmark/alternative. To be more exact, this metric is non-existent when it comes to BDN and most other benchmark harnesses (native and JIT'd).

While I, personally, have been aware of this for a long time to some extent, I was still shocked while reading about Google's own [AsmDB](https://storage.googleapis.com/pub-tools-public-publication-data/pdf/e52f61fd2c51e8962305120548581efacbc06ffc.pdf) from various glorious optimization failures that were shown there.

Section (4) of that paper really provides a wake-up call to all the "optimize at all cost" crowd (present company included, unfortunately) as to the system and fleet wide implications of ignoring code-bloat. Sub-section 4.4, specifically tells the horror story of over-optimizing `memcmp()`, which I'll reprint here for context:

> memcmp clearly stands out of the correlation between call frequency and function size in Figure 8. It is both extremely frequent, and, at almost 6 KiB of code, 10× larger than memcpy which is
conceptually of similar complexity. Examining its layout and execution patterns (Figure 13) suggests that it does suffer from the high amount of fragmentation we observed fleetwide in the previous section.
> While covering 90% of executed instructions in memcmp only requires two cache lines, getting up to 99% coverage requires 41 lines, or 2.6 KiB of cache capacity. Not only is more than 50%
of code cold, but it is also interspersed between the relatively hot regions, and likely unnecessarily brought in by prefetchers. Such bloat is costly – performance counter data collected by GWP indicates that **8.2% of all i-cache misses among the 100 hottest functions are from memcmp alone**.
> A closer look at the actual code from glibc can explain the execution patterns in Figure 13. It is hand-written in assembly and precompiled, with *extensive manual loop unrolling*, *many conditional cases* for the various alignments of the two source arrays, and *large jump tables*.
> In our experience, code usually evolves into similar state from **over-reliance on micro-optimization and micro-benchmarking**.

I think there is a much larger discussion that needs to happen as to how we evaluate the performance of a given benchmark when also trying to incorporate the native code-size into this equation, but that discussion is probably far off into the future, given the state of reporting in this area.  
**This is a situation I'd like to improve upon.**

I'd personally like to become more in-tune to the amount of machine code generated as part of my benchmarks and code that I write, and in particular benchmark with BDN, on a per benchmark basis.

In other words, I'd like to start collecting this information through a new Diagnoser that would be part of BDN in the future. This diagnoser would use one of the available diagnostics packages (I assume this would be ClrMD) and would be able to report the amount of native code JIT'd per module/process for each benchmark case.

This data, once reported and reflected in the summary of a benchmark run, could also be scaled compared to the baseline of the benchmark to provide yet another ratio of amount of generated native code.

Working on this diagnoser might be related to, or independent of #1316 (I tend to think that it is actually independent of it) but it's worthwhile to mention its existence in this context.

I'd like to hear the thoughts of BDN maintainers/users about this before jumping into implementing something like this as a full-blown diagnoser (I'll probably do a hacked out version in the meantime in my own code if I manage to do so).

**Comment by adamsitnik** [comment]
If Iced works on every OS then we can just make it a part of https://github.com/dotnet/BenchmarkDotNet/issues/1316

The new diagnoser can just return a new metric that would be responsible for native code size.

https://github.com/dotnet/BenchmarkDotNet/blob/04a71586206a822bca56f0abdacefdc2e5fc1b01/src/BenchmarkDotNet/Diagnosers/IDiagnoser.cs#L26

The rest of BDN is going to print a nice column

**Comment by damageboy** [comment]
I'm not 100% sure, but I think that just aggregating the information provided by `ClrMD` can be enough here to generate this metric.

The reason I'm making this distinction is that `Iced` is Intel only, while `ClrMD` *might* have a different support matrix.

For example, I have no idea what we'll use for Arm disassembly sometime in the future, but this specific metric might be available just with ClrMD and without doing any disassembly at all.

Do you still think it should be part of the disassembly diagnoser?

**Comment by adamsitnik** [comment]
> Do you still think it should be part of the disassembly diagnoser?

Do you propose to have a simple diagnoser that does not disassemble the code but just checks the native code size using `ClrMd`? I would prefer to just extend the disassembly diagnoser, but if it's hard or not-intutive then I am fine with having a new one.

Another thing to consider is in which methods sizes are we interested? Most probably giving the size of the benchmark method won't be enough in most of the cases.

**Comment by damageboy** [comment]
Right, this is another reason I was thinking about some sort of a separate diagnoser.
The reasoning would be that you would need to configure which assemblies to track.
In some cases it would be the benchmark ("Self"), in other cases you actually don't care at all about about the BDN code, but some specifc module ("SomeModuleName").

If we try to "plan" this feature out, it might look like:

```csharp
    [DisassemblyDiagnoser]
    [NativeCodeSizeDiagnoser(trackSelf = true)]
    public class MicroBenchmarks1
    {
    }

    [DisassemblyDiagnoser]
    [NativeCodeSizeDiagnoser(trackSelf = false, addtionalModules="VxSortResearch,SillyUtilModule")]
    public class MicroBenchmarks1
    {
    }

    [DisassemblyDiagnoser]
    [NativeCodeSizeDiagnoser(trackAll = true)]
    public class MicroBenchmarks1
    {
    }
```

Does this sort of approach look reasonable?

**Comment by adamsitnik** [comment]
I am closing as it was fixed by https://github.com/dotnet/BenchmarkDotNet/pull/1332

@damageboy please feel free to reopen if there is something missing
