### ISSUE TITLE
ConfigOptions.JoinSummary didn't work

### ISSUE THREAD

**Issue by Wizard2007** [dotnet/BenchmarkDotNet#1330]
Hi, 
I want merge benchmark results. 
I use 
BenchmarkDotNet version="0.12.0" 
targetFramework="net461"

` 
        
            BenchmarkRunner.Run<MyBenchmark>(ManualConfig
                    .Create(DefaultConfig.Instance)
                    .With(ConfigOptions.JoinSummary)
                    .With(ConfigOptions.DisableLogFile));

            BenchmarkRunner.Run<MyBenchmark1>(ManualConfig
                    .Create(DefaultConfig.Instance)
                    .With(ConfigOptions.JoinSummary)
                    .With(ConfigOptions.DisableLogFile));
//-------------------------------------------------------------------------

    public class MyBenchmark
    {
        [Benchmark]
        public void Fn1() => Thread.Sleep(10);

        [Benchmark]
        public void Fn2() => Thread.Sleep(10);
    }

    public class MyBenchmark1
    {
        [Benchmark]
        public void Fn__1() => Thread.Sleep(10);

        [Benchmark]
        public void Fn__2() => Thread.Sleep(10);
    }
`

but did'nt obtain merged results in  BenchmarkDotNet.Artifacts . That is correct way to merge benchmarks results?

**Comment by adamsitnik** [comment]
Hello @Wizard2007 

`BenchmarkRunner.Run` stores no state between the runs. 

To join the results from multiple types you need to pass all types|assemblies info to a single `BenchmarkRunner.Run` call.

Example:

```cs
BenchmarkRunner.Run(
    typeof(MyBenchmark).Assembly, // all benchmarks from given assembly are going to be executed
    ManualConfig
                .Create(DefaultConfig.Instance)
                .With(ConfigOptions.JoinSummary)
                .With(ConfigOptions.DisableLogFile));
```

**Comment by Wizard2007** [comment]
Thank you, it was very help full, and  I can solve my issue.
I use such code, to run only this two benchmark and join results.

`            
            
       var config = ManualConfig.Create(DefaultConfig.Instance)
             .With(ConfigOptions.JoinSummary)
             .With(ConfigOptions.DisableLogFile);

        BenchmarkRunner.Run(new[]{
                BenchmarkConverter.TypeToBenchmarks( typeof(XorShiftBenchmarks), config),
                BenchmarkConverter.TypeToBenchmarks( typeof(XorShiftBenchmarks1), config) 
                });

`

**Comment by VAllens** [comment]
> Thank you, it was very help full, and I can solve my issue. I use such code, to run only this two benchmark and join results.
> 
> `
> 
> ```
>    var config = ManualConfig.Create(DefaultConfig.Instance)
>          .With(ConfigOptions.JoinSummary)
>          .With(ConfigOptions.DisableLogFile);
> 
>     BenchmarkRunner.Run(new[]{
>             BenchmarkConverter.TypeToBenchmarks( typeof(MyBenchmark), config),
>             BenchmarkConverter.TypeToBenchmarks( typeof(MyBenchmark1), config) 
>             });
> ```
> 
> `

It's an effective solution and it works for me.
