### ISSUE TITLE
Getting "Unknown Processor" Again

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1333]
You did fix the previous issue where is shows "Unknown Processor" but it looks like it's back.

![String Equals Benchmark](https://user-images.githubusercontent.com/15676130/71044248-06fc8200-20e6-11ea-9230-81c0504796ae.jpg)

**Comment by AndreyAkinshin** [comment]
@RealDotNetDave ok, let's continue our experiments. Could you please run this line
```
Console.WriteLine(HostEnvironmentInfo.GetInformation());
```
in the same program that you use to run the benchmarks (before or after the BenchmarkRunner call).

**Comment by RealDotNetDave** [comment]
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-7660U CPU 2.50GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=3.1.100
  [Host] : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT

**Comment by adamsitnik** [comment]
@RealDotNetDave are you still experiencing this problem?

**Comment by RealDotNetDave** [comment]
Not sure. Let me check.

**Comment by RealDotNetDave** [comment]
Yes, seems to be back. Thanks!

**Comment by adamsitnik** [comment]
@RealDotNetDave thanks!
