### ISSUE TITLE
[question] discard variables

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/BenchmarkDotNet#1341]
Reading good practices doc ( https://benchmarkdotnet.org/articles/guides/good-practices.html ), it's reported to always return a value from our benchmarks (so our benchmarks shouldn't have `void returns`)

does using discard variables in our tested method call leverage this problem?
e.g. does 
```
void Foo()
{
   _ = Math.Exp(1);
}
```

prevent JIT to remove the code?

I'd like to know why and when this could happen, because how does JIT and benchmarkdotnet manage methods that doesn't have a return value?

We are interested just on benchmarking the body method, so excluding the return would make sense to me (even because I'm interested in MemoryDiagnoser)

thanks

**Comment by adamsitnik** [comment]
hi @MithrilMan 

Please excuse me for such a big delay, I've no idea how I've missed this question.

> it's reported to always return a value from our benchmarks (so our benchmarks shouldn't have void returns)

The doc says:

> You should also use the result of calculation

So if given benchmark calculates something, you should return it and allow the harness to consume the results and prevent dead code elimination.

If the given benchmark does not calculate anything and just calls the` void` method, it's perfectly fine to have a `void` benchmark and don't return anything.

> does using discard variables in our tested method call leverage this problem?

I am not familiar with the implementation details of discard variables but I would be very surprised if JIT was eliminating discarded variables. 
FWIW If BenchmarkDotNet reports time close to `0ns` (it warns about it) then most probably given benchmark was optimized by JIT to an empty method. So if you ever see `0ns` in the table with the results, you can be sure that the code got eliminated.
A good way to verify that is to use the [DisassemblyDiagnoser](https://adamsitnik.com/Disassembly-Diagnoser/) and take a look at the produced machine code.

BTW some time ago I've written a doc about Microbenchmark Design Guidelines, you might find it useful: https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md

Thanks,
Adam
