### ISSUE TITLE
Question: possible to use with Xamarin?

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/BenchmarkDotNet#1343]
I think it would be extremely helpful for the Xamarin community to be able to run Benchmarks on a real Android or iOS device. I would send PRs to help get this working. 😄 

Two questions come to mind.

1. It seems BDN launches `mono` out of process. Is that a requirement for BDN to work?

2. Assuming BDN *can* do in-process, is it feasible to run a benchmark within a UI "click" event and display the results in the UI? Console output is not the greatest for mobile.

My first attempt to use BDN from a Xamarin.Android app resulted in a `PlatformNotSupportedException` on this line:

https://github.com/dotnet/BenchmarkDotNet/blob/cf3f8c382a6aab8fbc5c7ce804ef7451a4fdfac7/src/BenchmarkDotNet/Helpers/ConsoleExitHandler.cs#L26

Has anyone attempted this before?

**Comment by jonathanpeppers** [comment]
I got this to work with Xamarin.Android by hacking BDN just a bit:

![image](https://user-images.githubusercontent.com/840039/73128851-a80b1200-3f9b-11ea-953d-2eb9956a53ea.png)

Let me spend some more time to clean this up, and this can be a PR.

**Comment by roji** [comment]
Am also interested this, will probably give the PR a spin soon.
