### ISSUE TITLE
Can I run a CMD command during the toolchain lifecycle?

### ISSUE THREAD

**Issue by DmitrySenin** [dotnet/BenchmarkDotNet#1345]
I'm benchmarking the backend of a web application with PostgreSQL as the db. We use dotConnect but it requires a dll to be signed with a licence key otherwise it fails connecting to the db. I can sign any dll using a set of cmd commands. But the problem here is that BenchmarkDotNet generates a new exe for every run.
So far I'm using the InProcess toolchain and have the benchmark project signed. But InProcess seems to have limits on the benchmark time. Thus, I'm looking for a way to intersect into the toolchain lifecycle, get the target exe name/path, and sign it.
Is it attainable somehow?

**Comment by adamsitnik** [comment]
DmitrySenin I have filled #1403 which should solve this problem

**Comment by timcassell** [comment]
I think this can be done with `MsBuildArgument`.

```cs
Job.Default.WithArguments(new[]
{
    new MsBuildArgument("/p:SignAssembly=true"),
    new MsBuildArgument("/p:AssemblyOriginatorKeyFile=StrongNameKey.pfx")
})
```
