### ISSUE TITLE
Standard error:error NU1201: Project is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0).

### ISSUE THREAD

**Issue by chenjd** [dotnet/BenchmarkDotNet#1347]
On Mac OS 10.14.6.
dotnet version 3.1.100

Using dotnet tool to create a BenchmarkDotNet templates project and run it in console (dotnet new benchmark --console-app). The generated project cann't built and print the error:
_error NU1201: Project XXXX is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0)._

I think the BenchmarkDotNet **version** referenced by the project **is not the right one**. Because I find the BenchmarkDotNet referenced in the .csproj file is **0.11.5**, and I change the version to **0.12.0**. The error is gone.

**Comment by adamsitnik** [comment]
@CodeTherapist could you please take a look?
