### ISSUE TITLE
Different display text for arrays depending on a value source

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/BenchmarkDotNet#1348]
There is a difference of array representation in summaries depending on a value source. In case when `ArgumentsAttribute` is used an array is displayed as `Array[{array.Length}]`, but in case of `ArgumentsSourceAttribute` - the type name is used.

The bug can be simply reproduced using the `IntroArrayParam` sample:

https://github.com/dotnet/BenchmarkDotNet/blob/a3f76beebeaab9a7ff32f3af6a16d79094fea3f6/samples/BenchmarkDotNet.Samples/IntroArrayParam.cs#L10-L31

|                 Method |          array | value |       Mean |     Error |    StdDev |
|----------------------- |--------------- |------ |-----------:|----------:|----------:|
|           ArrayIndexOf | System.Int32[] |     4 |  5.7462 ns | 0.1177 ns | 0.1101 ns |
|           ArrayIndexOf | System.Int32[] |     4 |  3.9955 ns | 0.0771 ns | 0.0602 ns |
|          ManualIndexOf | System.Int32[] |     4 |  0.8766 ns | 0.0274 ns | 0.0243 ns |
|          ManualIndexOf | System.Int32[] |     4 |  2.9022 ns | 0.0588 ns | 0.0550 ns |
|           ArrayIndexOf | System.Int32[] |   101 | 25.7760 ns | 0.5521 ns | 1.4350 ns |
|          ManualIndexOf | System.Int32[] |   101 | 41.9487 ns | 0.3473 ns | 0.3079 ns |

The expected behavior is the same as `ArgumentsAttribute` has:

```csharp
[Benchmark]
[Arguments(new int[] { 1, 2, 3 }, 4)]
public int ArrayIndexOf(int[] array, int value)
    => Array.IndexOf(array, value);
```

|        Method |          array | value |      Mean |     Error |    StdDev |
|-------------- |--------------- |------ |----------:|----------:|----------:|
|  ArrayIndexOf |       Array[3] |     4 |  4.794 ns | 0.1270 ns | 0.2225 ns |

The same issue happens with parameters.

**Comment by WojciechNagorski** [comment]
How about `System.Int32[3]` instead of `Array[3]`? Using `Array[3]` you lose information about the type of elements.

**Comment by YohDeadfall** [comment]
For complex types (classes, structs, named tuples) it won't provide any meaningful information because you have a source code of some test. Therefore, having type names would pollute summary. More interesting information is values which are used in a test since counters depends on them. For arrays it's their size.

**Comment by adamsitnik** [comment]
I agree with @WojciechNagorski , it would be better to have the type name information and just exted what we have with the length:

```diff
- System.Int32[]
+ System.Int32[3]
```

**Comment by YohDeadfall** [comment]
It will be ugly in cases if there is a nested type and/or a long namespace. As I said before, this information gives you nothing valuable because except the type name which can be found in code.

In case of the `ArrayIndexOf` test it makes sense to display a content of the array to understand why a run takes so long. For example, why `ManualIndexOf` for value `4` takes less time than using value `101`? To understand that an user must know values of the used array or take a look at code and see there are elements starting by 0 and ending by 100.

Every time you're working with benchmarks you should keep an eye on code. But if you still want to display a type name, let's not use its full name.

**Comment by YohDeadfall** [comment]
Another option is displaying a count, but in remarks below change description to mention that means an array size.
