### ISSUE TITLE
Disable default exporters

### ISSUE THREAD

**Issue by Symbai** [dotnet/BenchmarkDotNet#1352]
According to the docs https://benchmarkdotnet.org/articles/configs/exporters.html the default exporters are CSV, HTML and Markdown. I only want html but the docs don't say how to disable the rest.

I've tried adding the `[HtmlExporter]` attribute to my test class only but it did not helped. I'm running my tests with fluent style this way:

`var summary = BenchmarkRunner.Run<MyTest>(DefaultConfig.Instance.With(ConfigOptions.DisableLogFile));`

**Comment by adamsitnik** [comment]
Hi @Symbai 

In the code example that you have  provided you are using `DefaultConfig` which defines the list of default exporters:

https://github.com/dotnet/BenchmarkDotNet/blob/0c48c2862f69a63407898680d18dd76b988c4197/src/BenchmarkDotNet/Configs/DefaultConfig.cs#L29-L36

By using the `[HtmlExporter]` you **extend**  the list with an additional exporter. Not replace.

If you don't want to use the default exporters then you should pass an empty config to the `BenchmarkRunner`. Something like this:

```cs
var summary = BenchmarkRunner.Run<MyTest>(
    ManualConfig.CreateEmpty()
        .With(DefaultColumnProviders.Instance) // empty config does not define any columns for the output table, we need to define it manually
        .With(HtmlExporter.Default)
        .With(ConsoleLogger.Default));
```
