### ISSUE TITLE
Errors with updated Microsoft.NET.Test.Sdk nuget package

### ISSUE THREAD

**Issue by ghost** [dotnet/BenchmarkDotNet#1354]
Is it only to me that updating the given nuget package to versions 16.3.0 or 16.4.0, I get the following error?

// Launch: 1 / 1
// Execute: dotnet "508ebb57-d066-4ffa-940a-c5b3428adb4e.dll" --benchmarkName "xxx.Createxxx(quantity: 100)" --job "InvocationCount=1, IterationCount=1, LaunchCount=1, UnrollFactor=1, WarmupCount=0" --benchmarkId 0 in <path>
Unhandled exception. System.BadImageFormatException: Could not load file or assembly '<path>\bin\Release\netcoreapp3.1\508ebb57-d066-4ffa-940a-c5b3428adb4e\bin\Release\netcoreapp3.1\508ebb57-d066-4ffa-940a-c5b3428adb4e.dll'. An attempt was made to load a program with an incorrect format.
File name: '<path>\bin\Release\netcoreapp3.1\508ebb57-d066-4ffa-940a-c5b3428adb4e\bin\Release\netcoreapp3.1\508ebb57-d066-4ffa-940a-c5b3428adb4e.dll'

(I just changed file names and paths).

Reverting back to version 16.2.0 (I think it's the default when creating new projects, at the moment), everything works again.

I'm at the airport, now. Later on I will create a minimal working example to show the problem.

I'm just curious if someone else saw it, or I have some other strange problem (but it's strange, because reverting the version, everything works again...).

**Comment by andreabioli** [comment]
...and after 'cutting' the meaningful part of the names, I realize that there is some problem in the generated path, with the new version: all the '\bin\release\...' is duplicated, for what I can see here.

**Comment by adamsitnik** [comment]
> an attempt was made to load a program with an incorrect format.

such error can be related to bitness differences like having an x86 app trying to load x64 dll.

@ghost are you using any native dependencies? also, are you using x86 version of dotnet?

**Comment by adamsitnik** [comment]
No response since October, closing
