### ISSUE TITLE
SimpleJobAttribute with RunStrategy and RuntimeMoniker

### ISSUE THREAD

**Issue by TSlivede** [dotnet/BenchmarkDotNet#1361]
Is there any way to create a `SimpleJobAttribute` with specific `RunStrategy` and `RuntimeMoniker`?

I only see [constructors](https://benchmarkdotnet.org/api/BenchmarkDotNet.Attributes.SimpleJobAttribute.html#BenchmarkDotNet_Attributes_SimpleJobAttribute__ctor_BenchmarkDotNet_Engines_RunStrategy_System_Int32_System_Int32_System_Int32_System_Int32_System_String_System_Boolean_) with either `RunStrategy` or `RuntimeMoniker`...

**Comment by adamsitnik** [comment]
Hello @TSlivede 

Such ctor is missing.

If you would like to contribute you can add the needed ctor [here](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Attributes/Jobs/SimpleJobAttribute.cs) and send a PR.
