### ISSUE TITLE
Benchmarking c++ code

### ISSUE THREAD

**Issue by nhprog** [dotnet/BenchmarkDotNet#1362]
Hi,
I am trying to benchmark c++ code and looking if BenchmarkDotNet can allow me to do that. If yes, then can anyone help me with an example? I have just started learning about BenchmarkDotNet so if there is reference in the documentation for my question then please point me to that.

**Comment by adamsitnik** [comment]
Hello @nhprog 

You have two options:

* create a managed C++ project that defines the logic that you want to measure (A) and a C# benchmark project (B) that references it and just calls the logic.
* call the native functions from C# benchmarking project using PInvoke. The disadvantage is that **every benchmark result would contain the PInvoke marshaling overhead**  which would make nano-benchmarking impossible.

You can read more about PInvoke here: https://docs.microsoft.com/en-us/cpp/dotnet/calling-native-functions-from-managed-code?view=vs-2019

I think that the best thing you can do is to find some C++ library that was designed to benchmark the C++ code.

**Comment by fandrei** [comment]
@adamsitnik the P/Invoke approach fails if the C++ project is included into the project references.
```
error MSB4278: The imported file "$(VCTargetsPath)\Microsoft.Cpp.Default.props" does not exist and appears to be part of a Visual Studio component. This file may require MSBuild.exe in order to be imported successfully, and so may fail to build in the dotnet CLI.
```
