### ISSUE TITLE
Parameter column doesn't seem to respect culture info

### ISSUE THREAD

**Issue by Tyrrrz** [dotnet/BenchmarkDotNet#1369]
Hi!

Screenshot of what I mean:

![image](https://user-images.githubusercontent.com/1935960/73609119-2d617880-45d3-11ea-924a-1e9e541ad1f3.png)

Here `x` is the parameter column which is formatted with what seems to be `CultureInfo.CurrentCulture` while all other columns use invariant culture, judging by the fractional separator.

Looks like the culprit is here. The culture info is not used anywhere:

https://github.com/dotnet/BenchmarkDotNet/blob/f10752ace1bf4c5e4316c6f9b7b34ca25ac46c19/src/BenchmarkDotNet/Columns/ParamColumn.cs#L19-L20

https://github.com/dotnet/BenchmarkDotNet/blob/0768b7206be0078516034f0e6a1690b61561c55c/src/BenchmarkDotNet/Parameters/ParameterInstance.cs#L49

While, on the other hand, it's used in `BaselineRatioColumn`:

https://github.com/dotnet/BenchmarkDotNet/blob/0c48c2862f69a63407898680d18dd76b988c4197/src/BenchmarkDotNet/Columns/BaselineRatioColumn.cs#L53-L62

If this is accepted as an issue, I can try to submit a PR.

**Comment by adamsitnik** [comment]
> I can try to submit a PR

Yes, please!
