### ISSUE TITLE
Could not load file or assembly using dotnet benchmark

### ISSUE THREAD

**Issue by olivegamestudio** [dotnet/BenchmarkDotNet#1371]
When running the following command line:

> dotnet benchmark XXX.dll

The DLL project is referencing, but tried different versions to no avail:

    <PackageReference Include="BenchmarkDotNet" Version="0.12.0" />

I get the following error:

> Couldn't load the assembly XXX.dll.
> System.IO.FileLoadException: Could not load file or assembly 'XXX, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
>    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
>    at BenchmarkDotNet.Tool.AssemblyResolver..ctor(String path) in W:\Work\BenchmarkDotNet\src\BenchmarkDotNet.Tool\AssemblyResolver.cs:line 21
>    at BenchmarkDotNet.Tool.Program.OnExecute() in W:\Work\BenchmarkDotNet\src\BenchmarkDotNet.Tool\Program.cs:line 44
>

**Comment by justinhachemeister** [comment]
This seems to be an issue with .NET Core: https://github.com/Particular/Workshop/issues/64

**Comment by WojciechNagorski** [comment]
This article can be useful for you https://wojciechnagorski.com/2019/09/using-native-dll-and-resource-files-in-benchmarkdotnet-projects/

**Comment by adamsitnik** [comment]
@olivegamestudio did the link provided by @WojciechNagorski help you to make it work?

**Comment by timcassell** [comment]
@guillaumeagile What issue are you facing? BDN has been updated a lot since 2019.

**Comment by adamsitnik** [comment]
I was able to find a copy in the web archive: https://web.archive.org/web/20210727214959/https://wojciechnagorski.com/2019/09/using-native-dll-and-resource-files-in-benchmarkdotnet-projects/

**Comment by WojciechNagorski** [comment]
I will try to fix my blog, but for now you can read this article at:
https://github.com/WojciechNagorski/blog/blob/master/content/posts/2019-09-30-Using-native-DLL-or-resource-files-in-BenchmarkDotNet-projects.md

**Comment by WojciechNagorski** [comment]
@adamsitnik I created a PR that updates the documentation https://github.com/dotnet/BenchmarkDotNet/pull/2705
