### ISSUE TITLE
Always get: Declaring type must be public

### ISSUE THREAD

**Issue by DeLeneMirouze** [dotnet/BenchmarkDotNet#1374]
I try to test BenchMark but I can't make any simple example working. Event those provided in the documentation.
I consistantely get the error message:

XXXX containing Benchmark method YYYYY has incorrect access modifiers.
Declaring type must be public.

All classes and methode are public. I don't understand this error message

What can I do?

Using c# 3.1 with VS 2019

**Comment by AndreyAkinshin** [comment]
@DeLeneMirouze could you please share the source code of your benchmarks?

**Comment by DeLeneMirouze** [comment]
For instance this one (IntroParamsSource class):

https://benchmarkdotnet.org/articles/features/parameterization.html


gives:
ConsoleApp1.Program containing Benchmark method Benchmark has incorrect access modifiers.
Declaring type must be public.

In fact evey sample I can find have the same issue

**Comment by AndreyAkinshin** [comment]
Could you please share the full project that you are trying to run? Maybe you have some problems on the project configuration level.

**Comment by DeLeneMirouze** [comment]
Hello

Sorry for the late delay

You can clone a version from here:
https://github.com/DeLeneMirouze/TestBenchmark.git

I am using Visual Studio 201916.4.4
Windows 2010 (French)

thank you

**Comment by adamsitnik** [comment]
Hi @DeLeneMirouze 

In your case the `IntroParamsSource` is nested inside `Program` which is internal, and hence not public.

```cs
Console.WriteLine(typeof(IntroParamsSource).IsPublic);
```

You need to either make `Program` class `public` or move `IntroParamsSource` outside `Program` 

```cs
public class Program
{
    public class IntroParamsSource
    {
```

**Comment by DeLeneMirouze** [comment]
thank you
