### ISSUE TITLE
Forward msbuild properties to project reference

### ISSUE THREAD

**Issue by dotMorten** [dotnet/BenchmarkDotNet#1377]
Currently when you set MSBuild properties, they don't get forwarded to the project reference from the autogenerated projects.

In https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Templates/CsProj.txt#L26 it would be nice if we could provide addition properties on the reference. For example if this was added to that template::

```xml
 <ItemGroup>
    <ProjectReference Include="$CSPROJPATH$" AdditionalProperties="$ADDITIONAL_PROPERTIES$"/>
  </ItemGroup>
```

And then a way to set the $ADDITIONAL_PROPERTIES$ (or extract the /p properties from the msbuild properties.
Otherwise the msbuild properties are rather useless if the referenced project isn't rebuilt with the correct properties (it appears it just pulls in the project reference and not building it if it was already built, so multiple jobs with different settings won't get applies).

**Comment by adamsitnik** [comment]
Hello @dotMorten 

I've run into similar issues with MsBuild properties. I was wondering what would be the best way of passing all kinds of custom MsBuild properties to the auto-generated project. Perhaps we should add a possibility to make the auto-generated project include provided `.props` file?

Could you try using the `MsBuildArgument` type as a workaround for now?

```cs
job.With(new Argument[] { new MsBuildArgument("/p:SomeProperty=Value")})
```

**Comment by adamsitnik** [comment]
@dotMorten I have filled #1403 which should solve this problem and a few more similar issues ;)

**Comment by dotMorten** [comment]
Thank you!

**Comment by timcassell** [comment]
I don't think #1403 solves this problem directly, as it would still use a `ProjectReference` (to support F# and VB). I think this problem needs a solution of its own.

I couldn't find any documentation for `AdditionalProperties`. Is that a valid attribute for this purpose? I found https://github.com/dotnet/docs/issues/29781 which mentions `Properties` (also undocumented). Does either one work? What is the format for the value? Semi-colon separated list like this?

```
SomeProperty=Value;SomeOtherProperty=AnotherValue
```

If that's the case, I suspect we could join custom properties and add that to the generated csproj like you suggest.

```xml
<ProjectReference Include="$CSPROJPATH$" Properties="$CSPROJPROPERTIES$"/>
```

@dotMorten

**Comment by timcassell** [comment]
From my testing with simple projects, `Properties="$CSPROJPROPERTIES$"` does nothing. `/p:SomeProperty=Value` also does nothing, but `-p:SomeProperty=Value` made it work for both projects. It seems the solution is to just change the `/p:` to `-p:` in the `MsBuildArgument`.

**Comment by timcassell** [comment]
More chatter about this issue in #1773.

**Comment by timcassell** [comment]
I'm onto a fix for Core, I just need to make it also work for NativeAot, etc.
