### ISSUE TITLE
Run BenchmarkDotNet in GitHub Actions

### ISSUE THREAD

**Issue by jasdefer** [dotnet/BenchmarkDotNet#1378]
I want to run BenchmarkDotNet in a GitHub action to continously measure the performance of some methods. I like the idea of automating the benchmark and illustrating the results.

Are there any recommendations or examples for this approach and is it even reliable, because the benchmark would not run on my local machine?

I am sorry if I missed any information about this topic in the documentation, but I couldn't find anything.

**Comment by AndreyAkinshin** [comment]
@jasdefer 

> I like the idea of automating the benchmark and illustrating the results.

For now, we don't have any out-of-the-box solutions. Please, follow #54.

> Are there any recommendations or examples for this approach and is it even reliable

In general case, you will not get reliable and repeatable results. I'm working on a workflow that will allow getting reliable results (when it's possible) using an adequate number of iterations, but it's a pretty hard task which is still work in progress. Follow #155 for updates.

**Comment by jasdefer** [comment]
Thank you very much, this is exactly the discussion I was looking for. Somehow I didn't find this issue by myself. Sorry for that!

**Comment by bonesoul** [comment]
is appending to buildplots.r is a feasiable solution for this?

**Comment by evilguest** [comment]
Hello everyone, 
I am trying to get exactly this for my project: running the benchmarks as a part of the commit handler in the GitHub workflows: https://github.com/evilguest/linq2d/blob/master/.github/workflows/dotnet-core.yml#L31
(So far I am not expecting any comparisons or failures; it is more of having an access to the history of the benchmark variations over builds for the "manual" review).
However, I am getting stuck with the BDN complaining about missing runtime 2.1, which puzzles me a lot:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.1 at [/opt/hostedtoolcache/dncs/3.1.101/x64/shared/Microsoft.NETCore.App]
```
(https://github.com/evilguest/linq2d/runs/1116039786?check_suite_focus=true#step:9:7)

Is this expected? How do I fix that?

**Comment by adamsitnik** [comment]
@evilguest are you using `dotnet benchmark` command? Please see https://github.com/dotnet/BenchmarkDotNet/issues/1460#issuecomment-646531625

**Comment by evilguest** [comment]
@adamsitnik thanks a lot! This did solve it for me.
