### ISSUE TITLE
Make BaselineCustomColumn.GetValue public

### ISSUE THREAD

**Issue by damageboy** [dotnet/BenchmarkDotNet#1385]
Hi,
Referring to this:

https://github.com/dotnet/BenchmarkDotNet/blob/1d63d666da70530b03e392af23453bf5cd7c1784/src/BenchmarkDotNet/Columns/BaselineCustomColumn.cs#L27

Is there any particular reason the whole class is public while this specific method is kept internal?

Wouldn't it make sense to make the method public so it could be overriden outside of BDN, or is there some sort of an issue with that?

**Comment by adamsitnik** [comment]
Hi @damageboy 

We can make it `public`. Please go ahead and send a PR. You can also add the `[PublicApi] attribute to it (which will increase the chance for the method to stay public in a long-term ;) )

**Comment by damageboy** [comment]
NP, filing a PR
