### ISSUE TITLE
Add an opt-in comparison of each benchmarked version return value

### ISSUE THREAD

**Issue by tkstanczak** [dotnet/BenchmarkDotNet#1391]
I often write a new version of the benchmarked code but I am not sure if it actually does what it needs to do (whether the new version is not buggy). Then I write some code to check the values for each benchmarked method.

It would be a nice to have to have some build in support for results comparer that can launch once before each method is invoked (and for each parameter).

**Comment by adamsitnik** [comment]
Hi @tkstanczak 

We already have such a feature, it's called `ReturnValueValidator`

You can enable it by using an attribute `[ReturnValueValidatorAttribute]` or by using the fluent config API: `config.AddValidator(ReturnValueValidator.FailOnError))`

I am going to close this issue now, feel free to reopen it if you have more questions or there are some issues with `ReturnValueValidator`
