### ISSUE TITLE
Support for .net standard 2.1

### ISSUE THREAD

**Issue by frankhaugen** [dotnet/BenchmarkDotNet#1398]
When will we see support for .net standard 2.1?

**Comment by adamsitnik** [comment]
Hi @frankhaugen 

.NET Standard X library can reference .NET Standard Y library if `X >= Y`.

There is no need for BenchmarkDotNet to upgrade to .NET Standard 2.1, all our key dependencies like Roslyn and TraceEvent support .NET Standard 2.0 and it's all we need.

If there is some specific scenario that is currently not supported, please feel free to reopen the issue.

Have a nice day,
Adam
