### ISSUE TITLE
Executing Benchmark on class utilizing `System.Threading.Channels` takes lots of memory and are slow to run

### ISSUE THREAD

**Issue by SumitMeh** [dotnet/BenchmarkDotNet#1401]
I have created a simple program utilizing `System.Threading.Channels` via `PipelinePattern`. 
Running benchmark on it takes a lot of memory, upto 3-4 GBs. 
Specifying parameters to `SimpleJob` to execute less number of iteration does allow the benchmark to complete but even that takes upto 500-600 MBs of memory.
The program just enumerates over directory, pushes each file to Channel --> on other end file properties are extracted --> then contents of file are parsed to an entity --> then displayed on Console. 
Each Channel has max buffer of 2, total 5 files, each having just 6-7 lines.

> --> means Channel

**Comment by adamsitnik** [comment]
Hi @SumitMeh 

BenchmarkDotNet has no special treatment for any types or namespaces, including `System.Threading.Channels`. It's a benchmarking tool that runs whatever the user has provided.

If you want to find out why so much memory was allocated, you need to use a `memory profiler`. You can use [Visual Studio Memory Profiler](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md#allocation-tracking) to find out which methods are allocating the memory.
