### ISSUE TITLE
BenchmarkSwitcher Throws FileLoadException

### ISSUE THREAD

**Issue by Yamazaki93** [dotnet/BenchmarkDotNet#1406]
## Issue

Building with .NET Framework 4.7.2. After upgrading NuGet package `CommandLine` to version `2.7.82`. Running with `BenchmarkSwitcher` throws `FileLoadException` where it's looking for `CommandLine 2.4.3`. 

## Steps To Reproduce

1. Create a .NET Framework Console App, targeting 4.7.2, add `BenchmarkDotNet` NuGet package.
2. Upgrade `CommandLine` to `2.4.3`
3. Run the following modified version of the sample code 

``` C#
    public class Md5VsSha256
    {
        private const int N = 10000;
        private readonly byte[] data;

        private readonly SHA256 sha256 = SHA256.Create();
        private readonly MD5 md5 = MD5.Create();

        public Md5VsSha256()
        {
            data = new byte[N];
            new Random(42).NextBytes(data);
        }

        [Benchmark]
        public byte[] Sha256() => sha256.ComputeHash(data);

        [Benchmark]
        public byte[] Md5() => md5.ComputeHash(data);
    }
    public class Program
    {
        public static void Main(string[] args)
        {
            var benchmarkSwitcher = new BenchmarkSwitcher(new []{typeof(Md5VsSha256)});
            benchmarkSwitcher.Run(args);
        }
    }
```
Exception occurs at `Run`

## Details

This pops up for us while performing a routine NuGet update. We saw `BenchmarkDotNet` NuGet specifies dependency `CommandLine >= 2.4.3` so we thought `CommandLine 2.7.82` will work. This occurs both on `Release` and `Debug`. Regular `BenchmarkRunner` still runs which I assume does not depend on `CommandLine`. Maybe we are doing something wrong?

Best,
Michael

**Comment by adamsitnik** [comment]
> where it's looking for CommandLine 2.4.3.

It's most probably a binding redirect issue. Could you please check if upgrading CommandLine is also changing the binding redirect for it?

Also, does it work if you just don't update it?

**Comment by Yamazaki93** [comment]
Hi @adamsitnik,
It appears to not change the binding redirect after updating NuGet. And yes it works without updating it.
Best,

**Comment by adamsitnik** [comment]
> It appears to not change the binding redirect after updating NuGet. And yes it works without updating it.

Thank you for the confirmation. In such a case, it's an IDE bug that we can do nothing about.

If you just want to get it working, please update the binding redirect manually (or remove the `CommandLine` entry and install it again).

If you want to get it fixed, please report it as a bug in your IDE bug tracking system.
