### ISSUE TITLE
Support IDisposable on benchmark class

### ISSUE THREAD

**Issue by drieseng** [dotnet/BenchmarkDotNet#1409]
Currently, **BenchmarkDotNet** does not support **IDisposable** on a benchmark class.
I would expect a `IDisposable.Dispose()` method to have similar semantics as a **GlobalCleanup** method.

As a workaround to #1408, I performed "global setup" in the .ctor of my benchmark class. In which case it makes sense to implement **IDisposable** on this class and perform the "global cleanup" in the `Dispose()` method.

Any reason why this is not supported (except for "we haven't gotten around to it") ?

**Comment by adamsitnik** [comment]
Hi @drieseng 

> Any reason why this is not supported

Many years ago we have decided to use attributes for everything (starting from the benchmark method) and to not break the existing users we have to keep it that way.

I know that it's not super intuitive and requires the users to write more code but it has some advantages: a single type can have multiple `GlobalCleanup` methods that target different benchmarks. Having the type implement `IDisposable` is not enough when each benchmark needs a custom cleanup logic.

```cs
public class Sample
{
    [Benchmark]
    public void A() { }

    [GlobalCleanup(Target = nameof(A))]
    public void Cleanup_A() { }

    [Benchmark]
    public void B() { }

    [GlobalCleanup(Target = nameof(B))]
    public void Cleanup_B() { }
}
```

We can't break our users by removing the `[GlobalCleanup]` support and I think that adding the implicit `IDisposable` support would make it only more complex: there would be one more way of a possible cleanup (currently we have globalcleanup, iterationcleanup and finalizers)

If you believe that it would be a valuable addition please send a PR that adds the support. It should be a matter of extending [this](https://github.com/dotnet/BenchmarkDotNet/blob/be769f8e5012cdd818f2af7c6c9d9f18872c054a/src/BenchmarkDotNet/Running/BenchmarkConverter.cs#L47) logic.

Thanks,
Adam

**Comment by Neme12** [comment]
IMO since we can do global setup in the constructor, it should also support global cleanup in a `Dispose` method. That's the standard in .NET for doing cleanup.

**Comment by Neme12** [comment]
> We can't break our users by removing the [GlobalCleanup] support

It doesn't have to be removed. Why not support both?
