### ISSUE TITLE
BenchmarkdotNet result analysis

### ISSUE THREAD

**Issue by rmanjusha** [dotnet/BenchmarkDotNet#1411]
Hi ,

Could you please provide some clarity on how   'Error  : Half of 99.9% confidence interval' is calculated and what it means?
Should it  be lower. 

Thanks,
Manjusha

**Comment by adamsitnik** [comment]
Hi @rmanjusha 

Does https://github.com/dotnet/BenchmarkDotNet/issues/1205#issuecomment-513495371 answer your question?

Thanks,
Adam

**Comment by rmanjusha** [comment]
Thanks Adam
