### ISSUE TITLE
netcore tests hung if COREHOST_TRACE=1

### ISSUE THREAD

**Issue by alexeybut** [dotnet/BenchmarkDotNet#1412]
Version 0.12.
NetCore targetframework.
Any test hungs if environment variable COREHOST_TRACE=1.
DotNetCliCommandExecutor.GetDotNetSdkVersion() can't finish the line
string output = process.StandardOutput.ReadToEnd()

**Comment by adamsitnik** [comment]
Hi @alexeybut 

What .NET Core version are you using? It looks like an old .NET Core bug that BenchmarkDotNet has nothing to do with: https://github.com/dotnet/runtime/issues/2531

**Comment by alexeybut** [comment]
@adamsitnik, 
This happened on any version 2.0, 2.1. 3.1.
Setting COREHOST_TRACE to 0 fixes this issue.

**Comment by alexeybut** [comment]
[error.txt](https://github.com/dotnet/BenchmarkDotNet/files/4408359/error.txt)
[out.txt](https://github.com/dotnet/BenchmarkDotNet/files/4408360/out.txt)

**Comment by adamsitnik** [comment]
I am afraid that we can't fix it on our side.

Could you please create a small repro of what `DotNetCliCommandExecutor.GetDotNetSdkVersion()` does and report an issue in the https://github.com/dotnet/runtime repo?

**Comment by adamsitnik** [comment]
I am closing due to no response for almost a month.
