### ISSUE TITLE
Plot with only one "default" Job

### ISSUE THREAD

**Issue by djfoxer** [dotnet/BenchmarkDotNet#1413]
I have in my class  following attributes:

```
    [SimpleJob(RuntimeMoniker.Net48, baseline: true)]
    [SimpleJob(RuntimeMoniker.NetCoreApp31)]
    [SimpleJob(RuntimeMoniker.NetCoreApp50)]
    [RPlotExporter]
    [CsvMeasurementsExporter]
    [MarkdownExporterAttribute.GitHub]
```
class contains 2 [Benchmark] methods: RegexEmail and RegexStrongPassword.

but output plot (image: boxplot) contains only one (default?) Job:

![image](https://user-images.githubusercontent.com/17012140/78082111-7f93ff80-73b2-11ea-8bba-d5ce19ae1b6d.png)

Missing all 3 Jobs, that should be compared on one plot. It's multi-target project:
`<TargetFrameworks>netcoreapp5.0;netcoreapp3.1;net48</TargetFrameworks>`

**Comment by AndreyAkinshin** [comment]
@djfoxer thanks for the report!
