### ISSUE TITLE
Source data setup

### ISSUE THREAD

**Issue by rmanjusha** [dotnet/BenchmarkDotNet#1414]
Hi,

I `m doing performance test on collections and trying to benchmark for item remove (List.Remove). Could you please advise how to set up  the source data . I tried using Argument Source , but the data will get remove in  before actual run . So during actual run there won`t be data in the list . Any idea how to set the test data in this scenario.

![image](https://user-images.githubusercontent.com/61468185/78325198-96665d80-753c-11ea-98b8-c785146ac1a6.png)

**Comment by Ursanon** [comment]
This is side effect of benchmarking state holding class. Benchmark (iteration) will be executed many times per single global setup.

Try [Iteration options](https://benchmarkdotnet.org/articles/samples/IntroSetupCleanupIteration.html).

**Comment by adamsitnik** [comment]
Hi @rmanjusha 

Yes, BDN is reusing the same instance of arguments created by `[Arguments]`, `[ArgumentsSource]`, `[Params]` and `[ParamsSource]`. We do it to avoid a situation where this cost would be included in the reported time.

To solve the problem you can either use [IterationSetup](https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md#IterationSetup) or create a benchmark that initializes a new list, adds elements, and removes them. This is what we are doing in the official dotnet/performance repository:

https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/libraries/System.Collections/CreateAddAndRemove.cs
https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/libraries/System.Collections/AddRemove/AddRemoveSteadyState.cs

Thanks,
Adam
