### ISSUE TITLE
Make Values properties on ParamsAttribute protected set

### ISSUE THREAD

**Issue by danielmeza** [dotnet/BenchmarkDotNet#1415]
Make Values properties on ParamsAttribute protected set; in order to easy extend custom attributes.

**Comment by adamsitnik** [comment]
@danielmeza could you please send a PR?

**Comment by danielmeza** [comment]
Yes!

**Comment by adamsitnik** [comment]
@danielmeza ping

**Comment by danielmeza** [comment]
@adamsitnik sorry for the delay, I will resume this work as soon as I can.

**Comment by adamsitnik** [comment]
I am closing as there was no progress since April.

@danielmeza please feel free to send a PR.
