### ISSUE TITLE
EventPipeProfiler Documentation

### ISSUE THREAD

**Issue by WojciechNagorski** [dotnet/BenchmarkDotNet#1416]
I would like to write documentation about EventPipeProfiler. 

@adamsitnik I'm also going to create a blog post this weekend if you don't mind?

I want to finish this issue before Monday, it is related with https://github.com/dotnet/BenchmarkDotNet/pull/1399#issuecomment-608601423

**Comment by AndreyAkinshin** [comment]
@WojciechNagorski it would be great! You blog post will be a good addition to the release notes.

**Comment by WojciechNagorski** [comment]
Great. I've done the raw version, I will be polishing it tomorrow.

**Comment by AndreyAkinshin** [comment]
Fixed in #1418
