### ISSUE TITLE
Should minor version cause api breakage?

### ISSUE THREAD

**Issue by Swoorup** [dotnet/BenchmarkDotNet#1424]
It appears that a third party package that I use `Expecto` broke for benchmark 0.12.1, due to a property being removed from IConfig.

https://github.com/haf/expecto/issues/381

Should minor version increments in future cause other libraries to break?

**Comment by adamsitnik** [comment]
> Should minor version increments in future cause other libraries to break?

It should not. We do our best to not break the end-users by making sure we don't rename|remove a very common API, but sometimes we simply have to do it for the greater good. If you are interested in the details, please refer to https://github.com/dotnet/BenchmarkDotNet/pull/1302

Would you be interested in sending a PR that adds an integration test to make sure that we don't break Expecto in the future?

**Comment by adamsitnik** [comment]
No response for two weeks - I am closing it.

@Swoorup please feel free to send a PR that adds and integration test that ensures that we don't break Expecto in the future
