### ISSUE TITLE
How to change output path using the console line arguments?

### ISSUE THREAD

**Issue by bonesoul** [dotnet/BenchmarkDotNet#1425]
[here](https://github.com/dotnet/BenchmarkDotNet/issues/377#issuecomment-365637300) it says that i can use artifacts parameter to change with

`dotnet run -c Release -f net46 -- --artifacts="C:\AdamTest"`

i'm trying it with

`dotnet run -c Release  --project benchmarks\processors\timeseries\HypeEngine.Processors.TimeSeries.Benchmarks.csproj -- --artifacts="c:\test"`

but no luck. any ideas?

**Comment by adamsitnik** [comment]
Hi @bonesoul 

Are you using `BenchmarkSwitcher` and passing the `args` to it?

```cs
static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly)
    .Run(args); // crucial
```

**Comment by bonesoul** [comment]
hmm, seems it's a point.

one thing though i want to RunAll() within switcher (so i don't need any console input), but RunAll from BenchmarkSwitcher doesn't support args?

**Comment by adamsitnik** [comment]
>  RunAll from BenchmarkSwitcher doesn't support args?

good catch, could you please send a PR that adds that?

btw to run all you can just pass `*` as filter:

```cmd
--filter '*'
```

**Comment by adamsitnik** [comment]
I believe that the question was answered, so I am closing the issue.

**Comment by bonesoul** [comment]
yep
