### ISSUE TITLE
NativeMemoryProfiler reports false positive leak

### ISSUE THREAD

**Issue by jjolidon** [dotnet/BenchmarkDotNet#1427]
Hello all,
Thank you for the work on the project, it is much appreciated!

I am reporting an issue we are experiencing with the NativeMemoryProfiler of BenchmarkDotNet. It detects small but constant native memory leaks that seem to be false positives.
The attached reproducer showcases the issue. The benchmark only instantiates a mock object and computes a SHA256 (to avoid spending too little time in the benchmark). The resulting detected native memory leak is 0.06KB on my machine.

I believe the mocking library we use does not do weird things with native memory, so this gives me a strong feeling that this could be a false positive. Please note that this also happens with an industrial library we use in our software and which is heavily tested for memory leaks. While the library is using native memory, we are confident that the provider extensively tested it for any leak, which is another evidence that this could be a false positive. Unfortunately I cannot provide this library for inspection.

I am available for clarifications, should the need arise.

Version of BenchmarkDotNet: 0.12.1
Version of the Windows Diagnostics nuget: 0.12.1
Version of .net: core 3.1
Minimal reproducer: [MemoryProfilerReproducer.zip](https://github.com/dotnet/BenchmarkDotNet/files/4493306/MemoryProfilerReproducer.zip)

**Comment by adamsitnik** [comment]
@WojciechNagorski could you please take a look?

**Comment by WojciechNagorski** [comment]
I started my investigation. 
I run my repro (based on @jjolidon's report) using the following command because I wanted to run a benchmarked method only once. 
```
dotnet run -c Release -f netcoreapp3.1 -- --filter *Just* --launchCount 1 --iterationCount 1 --invocationCount 1 --unrollFactor 1
```
And I got (2320 B memory leak)
![image](https://user-images.githubusercontent.com/17333903/79743809-88b72300-8305-11ea-9623-a8bd1bbdc8d2.png)


Then I use Perfview to analyze a trace file:
![image](https://user-images.githubusercontent.com/17333903/79743315-ad5ecb00-8304-11ea-8fb2-745aef2d6d00.png)

![image](https://user-images.githubusercontent.com/17333903/79743546-0b8bae00-8305-11ea-8e8c-7af3c1870401.png)

@adamsitnik Maybe you know what it is? If not I need more time to understand this problem. 

After I open "Net Os Heap Alloc Stacks" I got a message:
![image](https://user-images.githubusercontent.com/17333903/79744191-3b878100-8306-11ea-9087-721b743f957a.png)

**Comment by WojciechNagorski** [comment]
It is a minimal repro:
```c#
using System.Diagnostics;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Diagnostics.Windows.Configs;

namespace BenchmarkDotNet.Samples
{

    [NativeMemoryProfiler]
    public class JustMock
    {

        [Benchmark]
        public string MyBenchmark()
        {
            var stackTrace = new StackTrace();

            return stackTrace.GetType().Name ;
        }
    }
}
```

The result:
```
--------------------
JustMock.MyBenchmark: Job-SNEMBI(InvocationCount=1, IterationCount=1, LaunchCount=1, UnrollFactor=1)
--------------------
Native memory allocated per single operation: 3544 B
Count of allocated object: 19
Native memory leak per single operation: 2320 B
Count of not deallocated object: 12
```

**Comment by WojciechNagorski** [comment]
After adding additional providers, I received a readable tracking file:
![image](https://user-images.githubusercontent.com/17333903/79963565-dceb1000-8489-11ea-93e2-bf2dcb4798e8.png)
But the memory leak is still there.

**Comment by WojciechNagorski** [comment]
I have a fix for .Net Framework. .Net Core has different behavior, but I know where a problem is and how to fix it. But I have to find free time to implement a fix.

**Comment by WojciechNagorski** [comment]
The following code present starting action:
![image](https://user-images.githubusercontent.com/17333903/80696328-89a33e00-8ad7-11ea-89ea-163a419e18f1.png)

And my calculations take a jitting of method (with their native allocations) between `Start` and `Stop`:
![image](https://user-images.githubusercontent.com/17333903/80696946-7e044700-8ad8-11ea-9fa9-b39a9795456a.png)
![image](https://user-images.githubusercontent.com/17333903/80698301-95443400-8ada-11ea-8bfe-068992baa251.png)
![image](https://user-images.githubusercontent.com/17333903/80701112-2917ff00-8adf-11ea-99bc-17eeda221fa1.png)

**Comment by adamsitnik** [comment]
> I have a fix for .Net Framework. .Net Core has different behavior, but I know where a problem is and how to fix it

Great news!
