### ISSUE TITLE
Wrong OsBrandString for Windows 10 1909

### ISSUE THREAD

**Issue by kapsiR** [dotnet/BenchmarkDotNet#1436]
Windows 10 1909 is the `November 2019 Update`.

`OsBrandStringHelper` reports `November 2018 Update` instead.

Example output:
>
> // * Summary *
>
>BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.778 (1909/**November2018Update**/19H2)
>Intel Core i7-4810MQ CPU 2.80GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
>  [Host]     : .NET Framework 4.8 (4.8.4150.0), X86 LegacyJIT
>  DefaultJob : .NET Framework 4.8 (4.8.4150.0), X86 LegacyJIT

Affected code:
https://github.com/dotnet/BenchmarkDotNet/blob/7902cd6de243c95861aed0b479d6c118d0711755/src/BenchmarkDotNet/Environments/OsBrandStringHelper.cs#L139

https://github.com/dotnet/BenchmarkDotNet/blob/7902cd6de243c95861aed0b479d6c118d0711755/tests/BenchmarkDotNet.Tests/Environments/OsBrandStringTests.cs#L43

**Comment by adamsitnik** [comment]
Hi @kapsiR 

Could you please send a PR with the fix?

Thanks,
Adam

**Comment by kapsiR** [comment]
Yes, sure. I'm on it and will push the PR shortly.
