### ISSUE TITLE
Benchmark-specific diagnostics

### ISSUE THREAD

**Issue by nloum** [dotnet/BenchmarkDotNet#1440]
Thank you for the great library! The attention to detail is very much appreciated.

I'm making a streaming application where it's very important that the streaming framework doesn't fall behind in the event processing. So I would like a benchmark that lets me measure the number of events the pipeline can handle per second. Is there a way to make BenchmarkDotNet benchmark something arbitrary like "number of events processed per second"?

The output of the benchmark should be numbers that would let me make a graph like this:

![2020-04-28 18_03_19-Ubuntu 18 04 vs  20 04 LTS Performance Preview With Intel Xeon Scalable - Phoron](https://user-images.githubusercontent.com/39776302/80546173-98281300-897a-11ea-8839-55b3dd1706e4.png)

Note the "More is better" label. The unit isn't time, it's operations per second. I would like my metric to be "events per second," referring to the number of events the pipeline being benchmarked can process per second.

Is this possible with BenchmarkDotNet? Would I need to make a custom Diagnoser just for my benchmark?

**Comment by adamsitnik** [comment]
Hi @nloum 

> Thank you for the great library!

Thank you!

> measure the number of events the pipeline can handle per second. I

Assuming that your `[Benchmark]` method processes a single event per benchmark, `StatisticColumn.OperationsPerSecond` is what you are looking for.

Example:

```cs
public static void Main(string[] args)
    => BenchmarkSwitcher
        .FromAssembly(typeof(Program).Assembly)
        .Run(args, DefaultConfig.Instance.AddColumn(StatisticColumn.OperationsPerSecond));
```

**Comment by nloum** [comment]
Nice! That might do what I need.

The pipeline processes multiple events simultaneously with multiple threads, so I'd like to test a large number of events in a single benchmark method. In fact one of the benchmark parameters is which threading mode the pipeline should use (single threaded or multi threaded).

So, what if I processed 1000 events in a single benchmark method, and used the `StatisticColumn.OperationsPerSecond` method to measure thousands of operations per second?

Like this:

    // This uses the System.Reactive 4.4.1 and BenchmarkDotNet 0.12.1 nuget packages
    class Program
    {
        static void Main(string[] args)
        {
            BenchmarkRunner.Run<PipelineBenchmarks>(DefaultConfig.Instance.AddColumn(StatisticColumn.OperationsPerSecond));
        }
    }

    public class Event
    {
        public Event(string key, string value)
        {
            Key = key;
            Value = value;
        }

        public string Key { get; }
        public string Value { get; }
    }
    
    [CsvExporter]
    public class PipelineBenchmarks
    {
        private IEnumerable<Event> GenerateEvents(int howMany)
        {
            var source = new[]
            {
                new Event("Key1", "Value"),
                new Event("Key2", "Value"),
                new Event("Key3", "Value"),
                new Event("Key4", "Value"),
                new Event("Key5", "Value"),
                new Event("Key6", "Value"),
                new Event("Key7", "Value"),
                new Event("Key8", "Value"),
                new Event("Key9", "Value"),
                new Event("Key10", "Value"),
            };

            for (var i = 0; i < howMany; i++)
            {
                yield return source[i % source.Length];
            }
        }

        public enum ThreadingMode
        {
            SingleThreaded,
            ThreadPerKey
        }
        
        [Benchmark]
        [Arguments(ThreadingMode.SingleThreaded)]
        [Arguments(ThreadingMode.ThreadPerKey)]
        public void EventProcessingThroughput(ThreadingMode threadingMode)
        {
            var eventPipeline = GenerateEvents(1000)
                .ToObservable()
                .SubscribeOn(NewThreadScheduler.Default)
                .ObserveOn(NewThreadScheduler.Default)
                .GroupBy(x => x.Key)
                .Select(group =>
                {
                    var result = @group.Select(x =>
                    {
                        // Do some processing
                        return new Event(x.Key, x.Value + "V");
                    });
                    
                    // If we're supposed to have a thread for each unique event key, do so here.
                    if (threadingMode == ThreadingMode.ThreadPerKey)
                    {
                        result = result.ObserveOn(NewThreadScheduler.Default);
                    }
                    return result;
                })
                .Merge()
                .Select(x => new Event(x.Key + "K", x.Value))
                .GroupBy(x => x.Key)
                .Select(group =>
                {
                    // Do some more processing
                    var result = @group.Select(x => { return new Event(x.Key, x.Value + "V"); });
                    
                    // If we're supposed to have a thread for each unique event key, do so here.
                    if (threadingMode == ThreadingMode.ThreadPerKey)
                    {
                        result = result.ObserveOn(NewThreadScheduler.Default);
                    }
                    return result;
                })
                .Merge()
                .Publish().RefCount();

            var task = eventPipeline.Take(1000).FirstAsync().ToTask();
            task.Wait();
        }
    }
