### ISSUE TITLE
Error running BDN

### ISSUE THREAD

**Issue by emiliovmq** [dotnet/BenchmarkDotNet#1444]
Don't know what I'm doing wrong here but every time I run BDN it fails with the following exception:
**Note**: I had to recur to insert images as adding content as code didn't work.

![image](https://user-images.githubusercontent.com/28937991/80763778-495eb280-8b0d-11ea-8b45-71ee42835e4e.png)

this is how my csproj file looks like:
![image](https://user-images.githubusercontent.com/28937991/80764280-55973f80-8b0e-11ea-8aea-53e4faea6f74.png)

this is the only benchmark I have so far:
![image](https://user-images.githubusercontent.com/28937991/80764359-89726500-8b0e-11ea-9e29-3a918ce0c6ef.png)

and this is the program.cs content:
![image](https://user-images.githubusercontent.com/28937991/80764422-b0c93200-8b0e-11ea-934d-80194ebdd6b9.png)

and no matter what command I run it always fails (below some of the commands used)
1 - dotnet benchmark Solutions.Benchmarks.dll --job default --runtimes netcoreapp3.1 --memory --exporters HTML --filter Solutions.Benchmarks.SortAlgoritms.MergeSortBenchmarks

2 - dotnet benchmark Solutions.Benchmarks.dll --filter *

3 - dotnet run -c Release -- --job Default --runtimes netcoreapp3.1 --memory --exporters HTML --filter Solutions.Benchmarks.SortAlgoritms.MergeSortBenchmarks

As you can see my setup is very simple, in the past I've configured BDN and it has worked like a charm. Don't know what's happening here. Could you take a look at this, please?

**Comment by adamsitnik** [comment]
Hi @emiliovmq 

Could you please run the following command in a folder with the project that defines the `Program.cs` that you have provided above and share the output?

```cmd 
dotnet run -c Release --filter * --job dry
```

**Comment by emiliovmq** [comment]
Hi @adamsitnik, thanks for your quick reply

I ran your command and, at first instance, it seemed to me the error had to do with the method used as the argument source. I applied a change to the code - following the samples in the documentation - and it worked, but it only works using the command you provided. If I use any of the commands I normally use it fails again. 

So, this is how my benchmark methods look like now:

```C#
[Benchmark]
[ArgumentsSource(nameof(InputData))]
public void Version2(int[] input. int length)
{
    MergeSort.Version2.Sort(input);
}

[Benchmark]
[ArgumentsSource(nameof(InputData))]
public void Version1(int[] input. int length)
{
    MergeSort.Version1.Sort(input);
}
```

This is the input data method:

```C#
public IEnumerable<object[]> InputData()
{
    yield return new object[] { new int[] { 1 }, 1 };
     yield return new object[] { new int[] { 10, 5, 4, 3, 11, 2, 1 }, 7 };
    yield return new object[] { new int[] { 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 }, 12 };
    yield return new object[] { new int[] { -11, 10, 9, -8, 7, 6, 5, -4, 3, 2, -1, 0 }, 12 };

    Random randNum = new Random();
    yield return new object[] { Enumerable.Repeat(0, 200).Select(i => randNum.Next(int.MinValue, int.MaxValue)).ToArray(), 200 };
}
```

If I use your command, everything works as expected:

```markdown
dotnet run -c Release --filter * --job dry
```

but using:

```markdown
dotnet benchmark Solutions.Benchmarks.dll --job default --runtimes netcoreapp3.1 --memory --exporters HTML --filter Solutions.Benchmarks.SortAlgoritms.MergeSortBenchmarks
```
or 

```markdown
dotnet benchmark Solutions.Benchmarks.dll --runtimes netcoreapp3.1 --filter Solutions.Benchmarks.SortAlgoritms.MergeSortBenchmarks
```

or simply

```markdown
dotnet benchmark Solutions.Benchmarks.dll --filter *
```

it always fails with the following exception:

![image](https://user-images.githubusercontent.com/28937991/80848499-809e9380-8be1-11ea-948d-984c592eee39.png)

Nothing changed in my project configuration...

**Comment by emiliovmq** [comment]
Hi, any news on this?

**Comment by adamsitnik** [comment]
Hi @emiliovmq 

There are few ways of running the benchmarks: https://benchmarkdotnet.org/articles/guides/how-to-run.html

I personally recommend using [BenchmarkSwitcher](https://benchmarkdotnet.org/articles/guides/how-to-run.html#benchmarkswitcher) because it's simple and it always works.

When it comes to [dotnet benchmark command](https://benchmarkdotnet.org/articles/guides/how-to-run.html#global-dotnet-tool) it's using dynamic assembly loading which for some reason fails in your case.

Please switch to using `BenchmarkSwitcher` and `dotnet run`

@CodeTherapist could you please take  a look at the error that @emiliovmq is getting?
