### ISSUE TITLE
How to define the argument source method when the methods to benchmark only have one input parameter which is an array?

### ISSUE THREAD

**Issue by emiliovmq** [dotnet/BenchmarkDotNet#1446]
Hi there,

This is an interrogant that surfaced when I was investigating another issue with the BDN dotnet tool. These are my methods:

```C#
[Benchmark]
[ArgumentsSource(nameof(InputData))]
public void Version1(int[] input)
{
    MergeSort.Version1.Sort(input);
}

[Benchmark]
[ArgumentsSource(nameof(InputData))]
public void Version2(int[] input)
{
    MergeSort.Version2.Sort(input);
}
```

**Note:** As you can see they only have one input parameter which is an array. 

If I define the method **InputData** as below, it fails at runtime with ```System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.```:

```C#
public IEnumerable<object> InputData()
{
    yield return new object[] { new int[] { 1 } };
    yield return new object[] { new int[] { 10, 5, 4, 3, 11, 2, 1 } };
    yield return new object[] { new int[] { 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 } };
    yield return new object[] { new int[] { -11, 10, 9, -8, 7, 6, 5, -4, 3, 2, -1, 0 } };

    Random randNum = new Random();
    yield return new object[] { Enumerable.Repeat(0, 200).Select(i => randNum.Next(int.MinValue, int.MaxValue)).ToArray() };
}
```

**Note:** Please, notice that the result type is ```IEnumerable<object>```. I used ```IEnumerable<object>``` instead of ```IEnumerable<object[]>``` because there is only one input parameter.

I also tried with:

```C#
public IEnumerable<object> InputData()
{
    yield return new object { new int[] { 1 } };
    yield return new object { new int[] { 10, 5, 4, 3, 11, 2, 1 } };
    yield return new object { new int[] { 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 } };
    yield return new object { new int[] { -11, 10, 9, -8, 7, 6, 5, -4, 3, 2, -1, 0 } };

    Random randNum = new Random();
    yield return new object[] { Enumerable.Repeat(0, 200).Select(i => randNum.Next(int.MinValue, int.MaxValue)).ToArray() };
}
```

But this fails at compile time because I cannot initialize type **'object'** with a collection initializer because it does not implement 'System.Collections.IEnumerable'

The only way I could make it to work was by introducing a new **unused** input parameter, exactly the same as one of the examples in the documentation:

```C#
[Benchmark]
[ArgumentsSource(nameof(InputData))]
public void Version1(int[] input, int length)
{
    MergeSort.Version1.Sort(input);
}

[Benchmark]
[ArgumentsSource(nameof(InputData))]
public void Version2(int[] input, int length)
{
    MergeSort.Version2.Sort(input);
}
``` 

and the source of data looks like:

```C#
public IEnumerable<object[]> InputData()
{
    yield return new object[] { new int[] { 1 }, 1 };
    yield return new object[] { new int[] { 10, 5, 4, 3, 11, 2, 1 }, 7 };
    yield return new object[] { new int[] { 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 }, 12 };
    yield return new object[] { new int[] { -11, 10, 9, -8, 7, 6, 5, -4, 3, 2, -1, 0 }, 12 };

    Random randNum = new Random();
    yield return new object[] { Enumerable.Repeat(0, 200).Select(i => randNum.Next(int.MinValue, int.MaxValue)).ToArray(), 200 };
}
``` 
Is there any other way to make it work without adding an unused input parameter ?

**Comment by adamsitnik** [comment]
Hi @emiliovmq 

We have an integration test that ensures that it's possible:

https://github.com/dotnet/BenchmarkDotNet/blob/1efd5e1fece3d2b635e9a18c2c20b0af1259bc21/tests/BenchmarkDotNet.IntegrationTests/ArgumentsTests.cs#L346-L353

And a doc page with example that explains how to use it: https://benchmarkdotnet.org/articles/features/parameterization.html#sample-introargumentssource

> for single argument it's an IEnumerable of objects (object)

So in your case it should be:

```cs
public IEnumerable<object> InputData()
{
    yield return new int[] { 1 };
    yield return new int[] { 10, 5, 4, 3, 11, 2, 1 };
    yield return new int[] { 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 };
    yield return new int[] { -11, 10, 9, -8, 7, 6, 5, -4, 3, 2, -1, 0 };
}
```

Thanks,
Adam
