### ISSUE TITLE
Results from BenchmarkDotNet are unstable and slower than debug run.

### ISSUE THREAD

**Issue by Palum12** [dotnet/BenchmarkDotNet#1449]
Hi everyone!

I am benchmarking multithreaded method which basicly counts regex matches in quite big file (~2GB). My problem is that, while results from measuring using stopwatch seem stable (as far as benchmarking with Stopwatch can go) and are hovering around 4-5 seconds, running the same method with BenchmarkDotNet produces slower and more unstable results. Sometimes it's 4-5, sometimes 6-8 and once it managed to hit 12 seconds. By unstable I mean, that the result changes occur after rebuilding project.

Code which is being benchmarked is compiled to .NET Standard 2.0 library in Release mode.  I am running benchmarks with VS closed and using CLI tool with command:

`dotnet benchmark TestSuite.dll --filter SearchTextBenchmark --runtimes netcoreapp3.1`

The "Stopwatch" project I mentioned is simple .NET Core 3.1 console app which has reference to this library.

Another thing I noticed is that the benchmark runs have low cpu usage, something like 30-40% while console app is using 80-90% of cpu resources. I assume this has something to do with the results I am seeing.

I am attaching log from runs which took 7 seconds, and code of benchmark class (low iteration count and disabled overhead counting is only temporary, to produce results faster and debug, however with default settings results were the same).

[TestSuite.SearchText.SearchTextBenchmark-20200503-210722.log](https://github.com/dotnet/BenchmarkDotNet/files/4571453/TestSuite.SearchText.SearchTextBenchmark-20200503-210722.log)

[SearchTextBenchmark.txt](https://github.com/dotnet/BenchmarkDotNet/files/4571454/SearchTextBenchmark.txt)

**Comment by adamsitnik** [comment]
Hello @Palum12 

Without the source code of the `SearchTextThreads` class and the input data file, we won't be able to help. But even if you could provide it, I am afraid that we would not have time to investigate it (we are maintaining this library in our free time which is limited ofc).

If you want to find out why there is a difference between `Stopwatch` and BenchmarkDotNet I recommend using a profiler.

If you are on Windows, the best choice is [ConcurrencyVisualizer](https://adamsitnik.com/ConcurrencyVisualizer-Profiler/#cpu-utilization) or [PerfView](https://adamsitnik.com/Sample-Perf-Investigation/)

I am going to close this issue as there is nothing that we can do on our side.

**Comment by Palum12** [comment]
If someone ever has similar problem. I didn't have time for finding out why this didn't work, but changing to another PC helped. (My config which had problems: Windows 7 x64, I7-4720HQ, .NET Core 3.1)
