### ISSUE TITLE
Totally different results per platform

### ISSUE THREAD

**Issue by stannynuytkens** [dotnet/BenchmarkDotNet#1450]
Hello,

Is it normal that running the same benchmarks using NetCoreApp31 on **Linux** results in

|                  Method |      Mean |    Error |   StdDev | Ratio |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|------------------------ |----------:|---------:|---------:|------:|-----------:|----------:|----------:|----------:|
|       ParseUsingDefault | 196.34 ms | 1.219 ms | 1.081 ms |  1.00 |  8000.0000 | 3000.0000 | 1666.6667 |  59.37 MB |
| ParseUsingTinyCsvParser |  70.86 ms | 0.875 ms | 0.775 ms |  0.36 | 19000.0000 | 4000.0000 | 1285.7143 | 115.99 MB |

and running them on **Windows** results in

|                  Method |      Mean |    Error |   StdDev | Ratio |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|------------------------ |----------:|---------:|---------:|------:|-----------:|----------:|----------:|----------:|
|       ParseUsingDefault | 204.71 ms | 2.208 ms | 1.957 ms |  1.00 |  9500.0000 | 3500.0000 | 1500.0000 |  83909676 B |
| ParseUsingTinyCsvParser |  17.12 ms | 0.134 ms | 0.112 ms |  0.08 | 593.7500 | 562.5000 | 562.5000 | 11426662 B |

What should I look into here?

**Comment by adamsitnik** [comment]
Hello @stannynuytkens 

BenchmarkDotNet runs the benchmarks in exactly the same way for every OS. 

.NET Core has platform-specific code: for example for Unicode (`string`) operations, it's using `WinAPI` on Windows and `icu` on Unix systems. These two have very different performance characteristics hence the reported results might be different as well.

If you would like to find out why there is a difference you need to use a **profiler**. Some time ago I've written down [this](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md) doc, it can be a good starting point for performance analysis.

I am going to close this issue as there is nothing that we can do on our side.
