### ISSUE TITLE
Detected error exit code from one of the benchmarks. It might be caused by following antivirus software:- Windows Defender (windowsdefender://)

### ISSUE THREAD

**Issue by furkanyazgi** [dotnet/BenchmarkDotNet#1453]
Hi!
I have a benchmark that looks like this, but for every run I receive

// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 1 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// ***** Done, took 00:00:00 (0.19 sec)   *****
// Found 1 benchmarks:
//   EFvsEFCore.EF_GetAll: InProcess(Toolchain=InProcessEmitToolchain)

// **************************
// Benchmark: EFvsEFCore.EF_GetAll: InProcess(Toolchain=InProcessEmitToolchain)
// *** Execute ***
// Launch: 1 / 1

// Benchmark Process Environment Information:
// Runtime=.NET Framework 4.8 (4.8.4150.0), X86 LegacyJIT  [AttachedDebugger]
// GC=Concurrent Workstation
// Job: Job-MCCWYP(Toolchain=InProcessEmitToolchain)

OverheadJitting  1: 1 op, 236100.00 ns, 236.1000 us/op

System.Reflection.TargetInvocationException: Özel durum bir çağırma hedefi tarafından oluşturuldu. ---> System.InvalidOperationException: No connection string named 'OracleEntities' could be found in the application config file.
   konum: System.Data.Entity.Internal.LazyInternalConnection.get_ConnectionHasModel()
   konum: System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   konum: System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   konum: System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   konum: System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   konum: System.Data.Entity.Infrastructure.DbQuery`1.System.Collections.Generic.IEnumerable<TResult>.GetEnumerator()
   konum: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   konum: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   konum: OracleEF.Repository.GetAll() C:\Users\furka\source\repos\ConsoleOracleManagedData\OracleEF\Repository.cs içinde: satır 13
   konum: MeasureEF.EFvsEFCore.EF_GetAll() C:\Users\furka\source\repos\ConsoleOracleManagedData\MeasureEF\EFvsEFCore.cs içinde: satır 19
   konum: BenchmarkDotNet.Autogenerated.Runnable_0.WorkloadActionNoUnroll(Int64 invokeCount)
   konum: BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   konum: BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
   konum: BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   konum: BenchmarkDotNet.Autogenerated.Runnable_0.Run(BenchmarkCase benchmarkCase, IHost host)
   --- İç özel durum yığını izlemesinin sonu ---
   konum: System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   konum: System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   konum: System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   konum: BenchmarkDotNet.Toolchains.InProcess.Emit.Implementation.RunnableProgram.Run(BenchmarkId benchmarkId, Assembly partitionAssembly, BenchmarkCase benchmarkCase, IHost host)
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\MeasureEF.EFvsEFCore-report.csv
  BenchmarkDotNet.Artifacts\results\MeasureEF.EFvsEFCore-report-github.md
  BenchmarkDotNet.Artifacts\results\MeasureEF.EFvsEFCore-report.html

// * Detailed results *
EFvsEFCore.EF_GetAll: InProcess(Toolchain=InProcessEmitToolchain)
Runtime = ; GC = 
There are not any results runs

// * Summary *

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18362.778 (1903/May2019Update/19H1)
Intel Core i7-4500U CPU 1.80GHz (Haswell), 1 CPU, 4 logical and 2 physical cores
  [Host] : .NET Framework 4.8 (4.8.4150.0), X86 LegacyJIT  [AttachedDebugger]

Job=InProcess  Toolchain=InProcessEmitToolchain  

|    Method | Mean | Error |
|---------- |-----:|------:|
| EF_GetAll |   NA |    NA |

Benchmarks with issues:
  EFvsEFCore.EF_GetAll: InProcess(Toolchain=InProcessEmitToolchain)

// * Warnings *
Environment
  Summary -> Benchmark was executed with attached debugger
  Summary -> Detected error exit code from one of the benchmarks. It might be caused by following antivirus software:
        - Windows Defender (windowsdefender://)
        - FortiClient AntiVirus (C:\Program Files\Fortinet\FortiClient\FortiClientConsole.exe)
        - ESET Security (C:\Program Files\ESET\ESET Security\ecmds.exe)
Use InProcessEmitToolchain or InProcessNoEmitToolchain to avoid new process creation.

// * Legends *
  Mean  : Arithmetic mean of all measurements
  Error : Half of 99.9% confidence interval
  1 ns  : 1 Nanosecond (0.000000001 sec)

// ***** BenchmarkRunner: End *****
// ** Remained 0 benchmark(s) to run **
Run time: 00:00:02 (2.16 sec), executed benchmarks: 1

Global total time: 00:00:02 (2.37 sec), executed benchmarks: 1
// * Artifacts cleanup *

**Comment by furkanyazgi** [comment]
Ok! İ Fixed it.

**Comment by SivaSankarGorantla** [comment]
Fixed it? but how?

**Comment by ardalis** [comment]
The worst possible forum/issue reply:

"Fixed it" with no additional information.

**Comment by adamsitnik** [comment]
> Fixed it? but how?

From the logs shared by @furkanyazgi I can see that there was a bug in the benchmark itself which was just throwing an exception:

> System.InvalidOperationException: No connection string named 'OracleEntities' could be found in the application config file.

So most likely the fix was reading the log carefully and fixing reported exception.
