### ISSUE TITLE
[Bug] ParamsAttribute is not being applied

### ISSUE THREAD

**Issue by leandromoh** [dotnet/BenchmarkDotNet#1455]
I got the following cenario, where I have 2 methods with `[Benchmark]` attribute, each one depends of 1 property with `[Params(10_000)]` attribute. Looking the output, everything looks normal. 

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18362.720 (1903/May2019Update/19H1)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.100
  [Host]     : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT


```
| Method | Number |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |------- |---------:|---------:|---------:|-------:|------:|------:|----------:|
|    Meu |  10000 | 20.05 μs | 0.528 μs | 1.516 μs |      - |     - |     - |      72 B |
|    Lib |  10000 | 10.84 μs | 0.211 μs | 0.608 μs | 0.0076 |     - |     - |      32 B |

However, when displayed the property value on each method, one prints the expected value (10k), while other prints 0, the default value. 

Removing both `[Params(10_000)]` attributes and setting 10k on the 2 properties with [auto-property initializers](https://csharp.today/c-6-features-auto-property-initializers/), everything works as expected.

Bellow, the code necessary to reproduce the bug.

````c#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    [MemoryDiagnoser]
    public class Program
    {
        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<Program>();

            Console.Read();
        }

        [Benchmark]
        public async Task<string> Meu()
        {
            var file = await ReadAllLinesAsync(null);

            return file;
        }

        [Benchmark]
        public async Task<string> Lib()
        {
            var file = await LibTest.ReadAllLinesAsync(null);

            return file;
        }

        [Params(10_000)]
        public static int Number { get; set; }

        public static async Task<string> ReadAllLinesAsync(object _reader)
        {
            Console.Write("meu" + Number);// prints tons of "meu10000"
            return null;
        }
    }

    public static class LibTest
    {
        [Params(10_000)]
        public static int Number { get; set; }

        public static async Task<string> ReadAllLinesAsync(object _reader)
        {
            Console.Write("lib" + Number); // prints tons of "lib0"
            return null;
        }
    }
}

**Comment by adamsitnik** [comment]
The `Params` attribute is applied only to the current instance of the class that defines the `Benchmark`.

If you use it in any other type it won't have any effect. By design.

In your case, you need to pass the `Number` to `LibTest.ReadAllLinesAsync` like this:

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    [MemoryDiagnoser]
    public class Program
    {
        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<Program>();

            Console.Read();
        }
        
        [Params(10_000)]
        public static int Number { get; set; }

        [Benchmark]
        public async Task<string> Meu()
        {
            var file = await ReadAllLinesAsync(null, Number);

            return file;
        }

        [Benchmark]
        public async Task<string> Lib()
        {
            var file = await LibTest.ReadAllLinesAsync(null, Number);

            return file;
        }

        public static async Task<string> ReadAllLinesAsync(object _reader, int number)
        {
            Console.Write("meu" + number);
            return null;
        }
    }

    public static class LibTest
    {
        public static async Task<string> ReadAllLinesAsync(object _reader, int number)
        {
            Console.Write("lib" + number);
            return null;
        }
    }
}
```

**Comment by leandromoh** [comment]
@adamsitnik , I uderstood, wondered whether was by design or not. 
However, if `Params` did not have any effect over `Lib.Number`, the output table display lies, because 1000 was never applied to `Number` on `Lib`.  

| Method | Number |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |------- |---------:|---------:|---------:|-------:|------:|------:|----------:|
|    Lib |  10000 | 10.84 μs | 0.211 μs | 0.608 μs | 0.0076 |     - |     - |      32 B |

**Comment by adamsitnik** [comment]
> the output table information is not true

It is true because the value of the static field `Number` of `Program` class that was running the `Lib` benchmark was assigned to `10_000`. You were just not using it in your code.

Try to look at this from a different perspective.

Let's say that we are using reflection to find all public types in assembly provided by the user.

```cs
foreach (Type publicType in assembly.GetTypes())
```

And then we search for all public methods with `[BenchmarkAttribute]`

```cs
foreach (MethodInfo benchmarkMethod in publicType
    .GetMethods()
    .Where(publicMethod => publicMethod.GetCustomAttribute<BenchmarkAttribute>() != default))
```

And now we want to check the `Params` used by the given benchmark.

To me the natural way is searching within the type that defines the benchmark method:

```cs
foreach (PropertyInfo paramsProperty in benchmarkMethod.DeclaringType // or just publicType 
    .GetProperties() 
    .Where(property => property.GetCustomAttribute<ParamsAttribute>() != default)
```

How would you expect us to find out that given `benchmarkMethod` of `publicType` is calling a method from a different type that is declaring a `[Params]` property? 
What if it would be in a different assembly?

There is no benchmarking|unit testing framework that does that. It's not intuitive.
