### ISSUE TITLE
Measurement.Parse asked to parse blank line

### ISSUE THREAD

**Issue by bender2k14** [dotnet/BenchmarkDotNet#1456]
When I run the `BenchmarkDotNet.Samples.FSharp` sample and select the case `#0 StringKeyComparison`, the [logs](https://github.com/dotnet/BenchmarkDotNet/files/4623438/Program.StringKeyComparison-20200513-100534.log) include many occurrences of 
```
Parse error in the following line:

```

that come from
https://github.com/dotnet/BenchmarkDotNet/blob/67971e92d9915622bcc44e8e75ed612cb8725e60/src/BenchmarkDotNet/Reports/Measurement.cs#L169-L170

This is happening because `line` is an empty string, so line 128...
https://github.com/dotnet/BenchmarkDotNet/blob/67971e92d9915622bcc44e8e75ed612cb8725e60/src/BenchmarkDotNet/Reports/Measurement.cs#L126-L128
...is throwing an instance of `IndexOutOfRangeException`.

The current behavior makes me think there is a bug.

What is intended behavior?

**Comment by adamsitnik** [comment]
Hi @bender2k14 

BDN is spawning a child process that is running the benchmark. Our Engine is writing the results to the standard output, which is parsed by the parent process. The parsing logic is trying to parse every line that does not start with `//`. If parsing fails, we just ignore the error.

This error is under the `#if DEBUG` condition: https://github.com/dotnet/BenchmarkDotNet/blob/67971e92d9915622bcc44e8e75ed612cb8725e60/src/BenchmarkDotNet/Reports/Measurement.cs#L168 mostly to allow the BDN contributors to debug it|see that something is wrong. The version that is deployed to nuget.org is always a Release version and the warning is never printed to the end-user.

So to tell the long story short, you can ignore this error.

BTW Please do run the benchmarks always in `Release` as the `Debug` builds contain no optimizations

**Comment by adamsitnik** [comment]
If it's annoying to you that the Debug build is throwing so many exceptions please feel free to send a PR with some defensive checks that avoid parsing blank lines.

Thanks!
