### ISSUE TITLE
Ability to specify units / easier comparison

### ISSUE THREAD

**Issue by voltagex** [dotnet/BenchmarkDotNet#146]
I noticed that a report I've generated uses `us` and `ns`. While I can multiply microseconds by 1000 to get nanoseconds, it'd be easier if I could specify the units to use in the report.

I'm currently not able to install the R package to view the plots so I'm not sure if they're better.

I'm using BenchmarkDotNet 0.9.4 from NuGet.

**Comment by mattwarren** [comment]
Hmm, good point. Currently BenchmarkDotNet deliberately scales the values, [taking into account the smallest measurement is has](https://github.com/PerfDotNet/BenchmarkDotNet/blob/ad6be7f7326cd8acbc05565193ccf4acf684a366/BenchmarkDotNet/Horology/TimeUnit.cs#L32-L44). So all the values reported should all be in consistent units.

Could you upload the .csv and .log files from a report you have so that we can see what's going on?

**Comment by voltagex** [comment]
I'm not sure I can share the particular report, I can see if I can write up a "fake" benchmark to show the problem.

**Comment by voltagex** [comment]
Here's a contrived example:
```
// * Summary *

BenchmarkDotNet=v0.9.4.0
OS=Microsoft Windows NT 6.1.7601 Service Pack 1
Processor=Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, ProcessorCount=8
Frequency=3507695 ticks, Resolution=285.0875 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
JitModules=clrjit-v4.6.1055.0

Type=SomeBenchmarks  Mode=Throughput

     Method |          Median |        StdDev |
----------- |---------------- |-------------- |
 FastMethod |       0.0000 ns |     0.0153 ns |
 SlowMethod | 997,114.6918 ns | 6,918.5739 ns |

// ***** BenchmarkRunner: End *****
```

FastMethod just returns, SlowMethod has a Sleep for 1ms.


Log/report attached.
[Release.zip](https://github.com/PerfDotNet/BenchmarkDotNet/files/230980/Release.zip)

**Comment by voltagex** [comment]
Argh, I've just noticed the example I posted doesn't switch units.

**Comment by voltagex** [comment]
Okay, I can't actually reproduce what I saw, even with my original code, but the feature request still stands: e.g.

                     Method |             Median |          StdDev |
--------------------------- |------------------- |---------------- |
  One | 40,866,028.1181 ns | 372,974.0464 ns |
  Two |        940.9016 ns |       9.8611 ns |
 Three |    815,496.1360 ns |  11,435.5779 ns |

might be better in ms.

**Comment by adamsitnik** [comment]
I think that it would help with #118, because right now it is impossible to implement if we can not have the same unit for all measurements

**Comment by Bobris** [comment]
Look at this how much excessive decimal points it has much beyond measurement precision (it could be different request than this, just that it should be probably improved together ...):

 Implementation |       Direction | Byte Size | Complexity |         Median |        StdDev |       Op/s |    Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
--------------- |---------------- |---------- |----------- |--------------- |-------------- |----------- |--------- |------ |------ |------------------- |
           **Btdb** |   **Serialization** |      **4821** |    **Complex** | **20,506.9925 ns** |   **797.1834 ns** |      **48742** |    **41,03** |  **0,46** |     **-** |             **310,71** |
           Btdb | Deserialization |      4821 |    Complex | 19,909.6383 ns | 1,339.2182 ns |   49360.49 | 1 190,97 |  0,72 |     - |           6 728,51 |
       ProtoBuf |   Serialization |      4993 |    Complex | 14,052.1149 ns |   850.7108 ns |   69942.33 | 1 381,15 |  0,66 |     - |           7 958,88 |
       ProtoBuf | Deserialization |      4993 |    Complex | 29,447.6527 ns |   466.8544 ns |   33919.63 | 1 244,00 |  1,00 |     - |           7 034,85 |
           **Btdb** |   **Serialization** |        **65** |     **Simple** |    **397.0839 ns** |    **20.1855 ns** | **2481788.09** |     **0,01** |     **-** |     **-** |               **1,31** |
           Btdb | Deserialization |        65 |     Simple |    466.0449 ns |     7.6932 ns | 2146386.42 |    18,36 |     - |     - |              79,91 |
       ProtoBuf |   Serialization |        74 |     Simple |    637.5732 ns |     7.8627 ns | 1570191.65 |    19,22 |     - |     - |              83,34 |
       ProtoBuf | Deserialization |        74 |     Simple |  1,019.3032 ns |    30.8121 ns |  974224.58 |    19,21 |     - |     - |              83,13 |

**Comment by AmadeusW** [comment]
There is a similar issue that affects measurement of allocated bytes.

Using v0.10.1, `Allocated` column in the reports has data in both `kB` and `MB`
![image](https://cloud.githubusercontent.com/assets/1673956/22126274/ec5b47f4-de4b-11e6-92f9-bcea2d7503f8.png)
