### ISSUE TITLE
LatestCoreRtVersionIsSupported test started failing

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#1461]
While reviewing #1459 I've noticed that our CI is red bacuse `LatestCoreRtVersionIsSupported` fails.

I was able to repro it locally:

```cmd
git clone https://github.com/dotnet/BenchmarkDotNet.git
cd .\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests
dotnet test -c Release -f netcoreapp2.1 --filter "FullyQualifiedName=BenchmarkDotNet.IntegrationTests.CoreRtTests.LatestCoreRtVersionIsSupported"
```

It looks that we don't recognize CoreRT anymore, most probably due to some recent CoreRT changes.

@MichalStrehovsky @jkotas this is the code that we are using to detect CoreRT:

https://github.com/dotnet/BenchmarkDotNet/blob/ccdf229ca82c1f064ee7e43af2d1f10991f247a5/src/BenchmarkDotNet/Portability/RuntimeInformation.cs#L41-L43

I can see that `Environment.Version.Major` is now returning `Unknown` for latest CoreRT. Is this expected?

**Comment by MichalStrehovsky** [comment]
It's the `Environment.Version.Major >= 5` part of the check. I'm not sure how this ever worked since we version as 1.0 since the beginning. I couldn't find the place within the build where this is computed in the time I allocated for myself for it.

**Comment by MichalStrehovsky** [comment]
> I couldn't find the place within the build where this is computed in the time I allocated for myself for it.

Ah, no, had the right place, but this is one of those "this won't invalidate things for incremental build, hahaha" changes.

**Comment by adamsitnik** [comment]
The test is passing again, thank you @MichalStrehovsky
