### ISSUE TITLE
.NET Core 5 rebranding 

### ISSUE THREAD

**Issue by djfoxer** [dotnet/BenchmarkDotNet#1462]
.NET 5.0 Target Framework was rebranded from `netcoreapp5.0` to `net5.0` (https://devblogs.microsoft.com/dotnet/announcing-net-5-preview-4-and-our-journey-to-one-net/). Are you going to change `RuntimeMoniker.NetCoreApp50` to `RuntimeMoniker.Net50`? Because currently all output data from BenchmarkDotNet related to .NET 5.0 is branded as .NET Core 5.0.

**Comment by adamsitnik** [comment]
Hi @djfoxer 

Personally I don't like the rebranding and as long as we can build and run `netcoreapp5.0` benchmarks I am not planning to do any changes myself.

However, if somebody is willing to send a PR that handles that and is not increasing code complexity, then I am fine with that.
