### ISSUE TITLE
Benchmark on kafka consumer get me a strange result

### ISSUE THREAD

**Issue by abbassep3200** [dotnet/BenchmarkDotNet#1467]
Hi my friend.
I'm testing kafka producer and consumer performance. I selected benchmark dot net. I haven't any problem with kafka producer but for kafka consumer and for only 100 messages I get 10 seconds  mean.
It's very strange and completely unreliable.
Also for this small code the bench marking process takes about 15 minutes, which is very long. ّ In real scenarios we need test 1,000,000 messages.
what is the problem?
this is consumer code:

        [Benchmark]
        public void KafkaConsumerUsingNewtonSoft()
        {
            using (var c = new ConsumerBuilder<Ignore, string>(config).Build())
            {
                c.Subscribe(KafkaConfigs.Topic);
                var record = c.Consume(0);
                for (var i = 0; i < 100; i++)
                {
                   record = c.Consume(new CancellationTokenSource().Token);
                    var obj = JsonConvert.DeserializeObject(record.Message.Value);
                }
            }
        }

**Comment by adamsitnik** [comment]
Hi @abbassep3200 

You should most probably move the setup logic to a setup method and remove the loop from the benchmark (BenchmarkDotNet scales the number of benchmark invocations).

You can read more about the design guidelines here: 
* https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md#Setup
* https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md#Loops


```cs
[Benchmark]
public object KafkaConsumerUsingNewtonSoft()
{
   var record = c.Consume(CancellationToken.None);
   return JsonConvert.DeserializeObject(record.Message.Value);
}
```

Once you do that, the reported time will be the cost of calling the `Consume` method and deserializing the result. 

And here the responsibility of a benchmarking tool ends. It can just tell you how long it takes to run a given code, not why. If you want to find out why it takes so long to run given code you need to use a profiler. [This doc](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md) can be a good introduction to using a profiler for the first time.
