### ISSUE TITLE
Add support of Wasm to Benchmark Dotnet

### ISSUE THREAD

**Issue by naricc** [dotnet/BenchmarkDotNet#1472]
Both the .csproj and command line invocation of a project built for wasm are different, so Benchmark Dotnet needs special support in order to be able to run benchmarks with that code generator.

This will require a new ToolChain (generator, builder, and executor).

This work is required to run the Dotnet/Performance microbenchmarks using wasm; the master issue for that is here: https://github.com/dotnet/runtime/issues/37762

**Comment by naricc** [comment]
Hmm, I meant to assign this to myself, but I am not a member of the appropriate team yet.

**Comment by adamsitnik** [comment]
@naricc I've assigned you. Please let me know if you need any help
