### ISSUE TITLE
How to benchmark static methods?

### ISSUE THREAD

**Issue by pprabu** [dotnet/BenchmarkDotNet#1473]
How can I use Benchmark in Generic Extension method and the argument should be dynamic from my application?

        [Benchmark]
        public static string LogEvent(this Enum eventId, string message)
        {
            EventRecord eventRecord = new EventRecord(
                moduleName: GetEnumAttribute<TitleAttribute>(eventId.GetType()).Name,
                eventId: Convert.ToInt32(eventId),
                eventName: $"{eventId}",
                description: message);

            EventLogger.LogMessage(eventRecord);
            return eventRecord.ToString();
        }

**Comment by pprabu** [comment]
Any update about to use Benchmark to the Extension methods?

**Comment by adamsitnik** [comment]
Hi @pprabu 

BenchmarkDotNet supports only non-static, non-sealed public types with instance methods marked as `[Benchmark]` but it does not mean that the benchmark methods can't call static methods.


```cs
public class Instance
{
    [Benchmark]
    public void CallStaticMethod()
    {
        StaticClass.StaticMethod();
    }
}

public static class StaticClass
{
    public static void StaticMethod() { }
}
```

When it comes to getting the arguments for the benchmark, please see our docs about it: https://benchmarkdotnet.org/articles/features/parameterization.html

In this particular case, you are most probably looking for `[ArgumentsSource]`
