### ISSUE TITLE
ArgumentSource with static function cannot be found

### ISSUE THREAD

**Issue by steveoh** [dotnet/BenchmarkDotNet#1476]
```
BenchMark has no public, accessible method/property called X, unable to read values for [ParamsSource]
```

I am hoping to reuse some xunit test data in my benchmarks. The xunit `MemberData` attribute requires a static `IEnumerable<object[]>`. 

It appears that `ArgumentSource` matches the `IEnumerable<object[]>` requirement, but when I try to use the benchmarking attribute on the method in my benchmarking project it fails to find the method with the error above.

I am assuming that since the method is public, it's having issues with the fact that it is static and in a different assembly.

It appears static is in the code where the error is thrown, https://github.com/dotnet/BenchmarkDotNet/blob/3223c94a92050147a02482a3810860703f0c5171/src/BenchmarkDotNet/Running/BenchmarkConverter.cs#L317-L329

but I'm not sure if this is supported or not.

**Comment by adamsitnik** [comment]
Hi @steveoh 

I've tried really hard to reproduce the problem that you got but I've failed. I've found one other edge case that was related to a different problem and fixed it in https://github.com/dotnet/BenchmarkDotNet/pull/1478

I am going to close the issue as it's most probably issue on your side. Please feel free to reopen it **if you can provide a repro case**.

Thanks,
Adam

**Comment by steveoh** [comment]
Ok great, I will look at it with fresh eyes today.
