### ISSUE TITLE
Link exporter, like pastebin or gist

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [dotnet/BenchmarkDotNet#1481]
It would be great to have an option to automatically upload benchmark results to some online storage, like pastebin. I see it very helpful as a teacher, where my student shares it's measurement within the forum comments. Some students prefer to copy raw results, some prefer to use markdown and some of them prefer to put it to pastebin or gist.

Automatic exporter would be a killer feature for this kind of usage of BenchmarkDotNet.

Pastebin has a quite easy API https://pastebin.com/api
GIst on another hand would require integration with GitHub auth, what introduces some complexity.

What do you think?

**Comment by adamsitnik** [comment]
I think that it would be a great feature, as long as it would be easy to setup. 

I am going to mark it as up-for-grabs hoping that someone is going to work on this.

**Comment by YegorStepanov** [comment]
Pastebin already requires registration for the token. But it very unsafe to paste a secret token in the code. 
```C#
[Pastebin("secret-token")]
public class Benchmarks { }
```
So, it remains only through the command line to do it:
```pwsh
dotnet run -c Release --pastebin-token "secret-token"
```
IMO it doesn't look friendly, it much easier to just copy from the console to whatever site you want.
In addition, Pastebin doesn't support folders or something similar, without it you will end up with a thousand gists that you will have to delete manually :)

A much simpler solution is to create a repo on github and commit the benchmark artifacts to it. Others can view the results and check the code of the benchmark + you have the power of the git.

**Comment by lukasz-pyrzyk** [comment]
Hi @YegorStepanov!

Thank you for the investigation. I agree with you, passing a secret token via arguments is not convenient. I guess we could achieve it by reading a value from the environment variables.

However, having spam within the Pastebin account seems to be a bigger problem. It may get really unstructured after running a few benchmarks.

Over these years there was no significant need for the feature (also from my side), so I would vote for closing the feature request.
