### ISSUE TITLE
[GcServer(true)] is ignored with --corerun

### ISSUE THREAD

**Issue by stephentoub** [dotnet/BenchmarkDotNet#1495]
When using `--corerun` to specify the target runtimes, `[GcServer(true)]` isn't respected.  It always ends up using workstation rather than server GC.

**Comment by adamsitnik** [comment]
Hi @stephentoub 

I am afraid I won't be able to fix it within the next few weeks, but I can provide a workaround until then.

You can pass the env vars to BDN by using:

```cmd
 --envVars                Colon separated environment variables (key:value)
```

So in your case it would be:

```cmd
--envVars "COMPlus_gcServer:1"
```

**Comment by stephentoub** [comment]
Thanks

**Comment by stanciuadrian** [comment]
I used this code:

```csharp
    [GcServer(true)]
    public class ServerBench 
    {
        [Benchmark]
        public void Go() { }
    }

    class Program
    {
        static void Main(string[] args)
            => BenchmarkSwitcher
                .FromAssembly(typeof(ServerBench).Assembly)
                .Run(args);
    }
```

and executed it with: `dotnet run -c Release -- --filter ServerBench --corerun C:\runtime\artifacts\bin\coreclr\Windows_NT.x64.Debug\corerun.exe`

It gives:

```
BenchmarkDotNet=v0.12.1.20200926-develop, OS=Windows 10.0.19041.508 (2004/May2020Update/20H1)
Intel Core i7-9700K CPU 3.60GHz (Coffee Lake), 1 CPU, 8 logical and 8 physical cores
.NET SDK=5.0.100-rc.1.20452.10
  [Host]     : .NET 5.0.0 (5.0.20.45114), X64 RyuJIT
  Job-TIRROW : .NET 5.0 (42.42.42.42424), X64 RyuJIT

Server=True  Toolchain=CoreRun
```

@stephentoub was this your scenario?

**Comment by stephentoub** [comment]
> was this your scenario?

Yes, but it's not the "Server=True" that matters, it's this:
```
GC=Concurrent Workstation
```
and if you change your Go method to be:
```
    [Benchmark]
    public void Go() => Console.WriteLine(GCSettings.IsServerGC);
```
it prints out "False".

**Comment by stanciuadrian** [comment]
Thanks for the feedback.
Right! The actual `GCSettings.IsServerGC` is the one that matters.

I'll further investigate this.

**Comment by stephentoub** [comment]
Thanks

**Comment by stanciuadrian** [comment]
The `runtimeconfig.json` file is correctly generated but `corerun` ignores it. It only handles reading the `COMPlus_gcServer` environment variable. I'm afraid this is the only solution.

We could try setting this environment variable when starting the `corerun {GUID}.dll` process.

@adamsitnik what do you think about this idea?
