### ISSUE TITLE
Drastically different results when benchmarking with BenchmarkDotNet and Stopwatch class

### ISSUE THREAD

**Issue by nawfalhasan** [dotnet/BenchmarkDotNet#1505]
When benchmarking the following methods to find the fastest one among:

        [Benchmark]
        public int RemoveAll_IList_O_N2()
        {
            for (var index = list.Count - 1; index >= 0; index--)
            {
                var item = list[index];
                if (predicate(item))
                {
                    list.RemoveAt(index);
                }
            }

            return list.Count;
        }

        [Benchmark]
        public int RemoveAll_ICollection_O_N()
        {
            List<string> nonMatchingItems = new List<string>();

            // Move all the items that do not match to another collection.
            foreach (var element in collection)
            {
                if (!predicate(element))
                {
                    nonMatchingItems.Add(element);
                }
            }

            // Clear the collection and then copy back the non-matched items.
            collection.Clear();
            foreach (string item in nonMatchingItems)
            {
                collection.Add(item);
            }

            return collection.Count;
        }

        [Benchmark]
        public int RemoveAll_ICollection_O_N2()
        {
            foreach (var item in collection.ToList())
            {
                if (predicate(item))
                {
                    collection.Remove(item);
                }
            }

            return collection.Count;
        }

----
I get the following results when running with `Stopwatch` class:

```
RemoveAll_IList_O_N2 - 1033.6409 ms
RemoveAll_ICollection_O_N - 233.6906 ms
RemoveAll_ICollection_O_N2 - 37519.5635 ms
```

This makes sense, because it is along the expected lines. But when running with BenchmarkDotNet, I get:

```
RemoveAll_IList_O_N2 - 15.45 us
RemoveAll_ICollection_O_N - 34.78 us
RemoveAll_ICollection_O_N2 - 19.39 us
```
Screenshot: 
![image](https://user-images.githubusercontent.com/2478860/88121173-8ef9bb80-cbe2-11ea-884f-a803172ce164.png)

Not only the BenchmarkDotNet stat defies my understanding, it returns results way different from Stopwatch's finding.

----
Any idea why this is happening? I am inclined to trust Stopwatch here. 

Details:
Intel core 15 9300H
Windows 10 Home 64 bit
.NET Core 3.1 project
Release build, AnyCPU platform, programs ran without debugger attached.

Sample attached.
[New folder.zip](https://github.com/dotnet/BenchmarkDotNet/files/4957199/New.folder.zip)

**Comment by abelbraaksma** [comment]
How do you run them with the `Stopwatch` class, you didn't show that code, and how do you fill `list` and `collection` and how do you fill it again after each run? My gut tells me you're missing setup code that must run for each benchmark, and that this is the difference with your stopwatch method.

Btw, `Stopwatch` is a bad comparison, because you probably don't account for JIT time.

EDIT: I see you attached the project code, I'll have a look at that tomorrow (or maybe someone else before that time ;).

**Comment by abelbraaksma** [comment]
Had a quick look anyway. If I fix your code by adding this:

```c#
    [IterationSetup]
    public void Setup()
    {
        list = imm.ToList();
        collection = imm.ToList();
    }
```

It runs "normally". In this case, it means you run into an actual bug (at least on my machine), namely: https://github.com/dotnet/BenchmarkDotNet/issues/1338. That means, each iteration is run only once, even if you set the iteration time higher (I tried with 2000ms). But the timings this way are a bit more consistent with your timings when I do it that way.

I don't have a good workaround for the referenced issue yet. @adamsitnik, I often run into the problem of tests only ever running one time, do you know a workaround for #1338?

**Comment by nawfalhasan** [comment]
@abelbraaksma Thank you, thanks a lot.. your solution did work.. But my first assumption was that BDN doesn't use seaprate instances of benchmark class for each run. But what I understand from your words is that it is rather a bug. Glad to know there is a work around.

I will close this now.

**Comment by nawfalhasan** [comment]
Btw, I had always trusted BDN results, didnt know subtleties like this existed. I will be careful to use IterationSetup always :)

**Comment by abelbraaksma** [comment]
> But my first assumption was that BDN doesn't use seaprate instances of benchmark class for each run

Indeed it doesn't, but you change the state and empty the collections. By using `IterationSetup` you make sure you initialize them again.

Don't use that attribute if you don't need it. You're making a macro benchmark, for micro benchmarks, it's better to avoid it if you can, because it adds overhead (which gets calculated and subtracted, but for micro benchmarks it can still add noise). 

> But what I understand from your words is that it is rather a bug 

The behavior you describe isn't a bug, but the problem with running into "1 iteration" only, and not many, is a bug, see the linked issue. You can work around this by setting the iterations manually.

**Comment by nawfalhasan** [comment]
> Indeed it doesn't, but you change the state and empty the collections. By using IterationSetup you make sure you initialize them again.

I see. I misread you then. So now I know the issue obviously. 

> Don't use that attribute if you don't need it. You're making a macro benchmark, for micro benchmarks, it's better to avoid it if you can, because it adds overhead (which gets calculated and subtracted

Got it..

> The behavior you describe isn't a bug, but the problem with running into "1 iteration" only, and not many, is a bug, see the linked issue. You can work around this by setting the iterations manually.

Fully clear. Thanks a lot.
