### ISSUE TITLE
BenchmarkDotNet does not force to High Performance Mode during running

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/BenchmarkDotNet#1506]
![image](https://user-images.githubusercontent.com/4510984/88236075-ca61bc00-ccae-11ea-913f-313129e9c604.png)

**Comment by adamsitnik** [comment]
@MarekM25 could you please take a look?

**Comment by YegorStepanov** [comment]
@adamsitnik You refactored (and broken) code after a month it was added!

[commit](https://github.com/dotnet/BenchmarkDotNet/commit/1578c5c60c3f59f9128f680e35d1db219aa60d8d#)

You replaced:
```C#
PowerPlanModeCharacteristic[this] = new PowerPlanMode();
```

with:
```C#
Register(EnvironmentMode.PowerPlanModeCharacteristic, () => PowerManagementApplier.Map(PowerPlan.HighPerformance));
```

but forgot do something like it:
```C#
job.Run.ResolveValue(EnvironmentMode.PowerPlanModeCharacteristic, EnvironmentResolver.Instance);
```

I don't know how to pass the job to the `static readonly ctor`, so I don't use this.
