### ISSUE TITLE
Changes to Jobs and Toolchain

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1511]
With this code:
 ` var config = DefaultConfig.Instance.With(Job.Default.With(CsProjCoreToolchain.NetCoreApp30));`

I'm getting errors below. Do you have any documentation on these changes and how to fix them? I cannot find anything in your docs.

**Errors:**
1>C:\src\GitHub\dotNetTips.Utility.Core\src\Benchmarking\dotNetTips.Utility.Benchmarks\dotNetTips.Utility.Benchmarks\Program.cs(31,54,31,104): warning CS0618: 'JobExtensions.With(Job, IToolchain)' is obsolete: 'This method will soon be removed, please start using .WithToolchain instead'
1>C:\src\GitHub\dotNetTips.Utility.Core\src\Benchmarking\dotNetTips.Utility.Benchmarks\dotNetTips.Utility.Benchmarks\Program.cs(31,26,31,105): warning CS0618: 'ConfigExtensions.With(IConfig, params Job[])' is obsolete: 'This method will soon be removed, please start using .AddJob() instead.'

**Comment by adamsitnik** [comment]
@RealDotNetDave the answer to your question is in the error message that you have provided:

> 'This method will soon be removed, please start using .WithToolchain instead'
> 'This method will soon be removed, please start using .AddJob() instead.'

Where `WithToolchain` and `AddJob` are new method names. So in your code you should have changes like this:

```diff
- job.With(toolchain);
+ job.WithToolchain(toolchain);
```
