### ISSUE TITLE
Setup/Cleanup once per process

### ISSUE THREAD

**Issue by gpetrou** [dotnet/BenchmarkDotNet#1514]
Currently, we can use GlobalSetup/GlobalCleanup and IterationSetup/IterationCleanup for specific classes and test methods.
In our case, we have some third party graphics libraries that can only be initialized/terminated once per process.
So, we need to initialize them before the first test is executed and terminate them after the last test is executed.
Would it be possible to add some API to achieve that? Or is there an existing (even hacky) way to do that?

**Comment by adamsitnik** [comment]
hi @gpetrou 

BenchmarkDotNet by default executes every benchmark in a standalone process, so using a `[GlobalSetup]` and `[GlobalCleanup]` should be fine.
