### ISSUE TITLE
Benchmark performance between multiple await and Task.WhenAll - Question

### ISSUE THREAD

**Issue by moisoiu** [dotnet/BenchmarkDotNet#1526]
Hello, 

Can someone help me out what am I doing wrong in the bellow tests? I was expecting that if I'm having 2 tasks and I use await on all of them, this will take longer compared of using Task.WhenAll().

I was hoping / expecting that if I'm using

await Get1; //Takes 300 ms
await Get2; //Takes 200 ms

The total duration I thought it would be 500 ms and not 300 ms;

And if i'm using Task.WhenAll(Get1, Get2) it will take 300 ms (the longest task from all of them. And yet, the results are the same 

Initially I thought that maybe I did not setup the test correctly (not using ) but it was the same behavior. 
![AwaitTaskWhenAll](https://user-images.githubusercontent.com/5052365/91812555-f8d1a000-ec39-11ea-90dd-066090391656.PNG)

```
    [MemoryDiagnoser]
    [ThreadingDiagnoser]
    [MediumRunJob]
    [HardwareCounters]
    [Orderer(SummaryOrderPolicy.FastestToSlowest)]
    public class Bench
    {
        [Benchmark]
        public async Task<int> GetResult()
        {
            var aTask = Get1();
            var bTask = Get2();
            await Task.WhenAll(aTask, bTask);
            var result1 = aTask.Result;
            var result2 = bTask.Result;

            return result1;
        }

        [Benchmark]
        public async Task<int> GetAwait()
        {
            var aTask = Get1();
            var bTask = Get2();
            await Task.WhenAll(aTask, bTask);
            var result1 = await aTask;
            var result2 = await bTask;

            return result1;
        }

        [Benchmark]
        public async Task<int> GetAwait_WithoutWhenAll()
        {
            var aTask = Get1();
            var bTask = Get2();
            var result1 = await aTask;
            var result2 = await bTask;

            return result1;
        }

        [Benchmark]
        public async Task<int> GetAwait_WithExtensions_WithResult()
        {
            var aTask = Get1();
            var bTask = Get2();

            var (result1, result2) = await TaskExtensions.WhenAllWithResult(aTask, bTask);
            return result1;
        }

        [Benchmark]
        public async Task<int> GetAwait_WithExtensions_WithoutResult()
        {
            var aTask = Get1();
            var bTask = Get2();

            var (result1, result2) = await TaskExtensions.WhenAll(aTask, bTask);
            return result1;
        }

        static async Task<int> Get1()
        {
            await Task.Delay(300);
            return 1;
        }

        static async Task<int> Get2()
        {
            await Task.Delay(200);
            return 2;
        }
    }

    public static class TaskExtensions
    {
        public static async Task<(T0, T1)> WhenAll<T0, T1>(Task<T0> task0, Task<T1> task1)
        {
            await Task.WhenAll(task0, task1).ConfigureAwait(false);
            return (await task0, await task1);
        }

        public static async Task<(T0, T1)> WhenAllWithResult<T0, T1>(Task<T0> task0, Task<T1> task1)
        {
            await Task.WhenAll(task0, task1).ConfigureAwait(false);
            return (task0.Result, task1.Result);
        }

        public static async Task<(T0, T1, T2)> WhenAll<T0, T1, T2>(Task<T0> task0, Task<T1> task1, Task<T2> task2)
        {
            await Task.WhenAll(task0, task1, task2).ConfigureAwait(false);
            return (await task0, await task1, await task2);
        }
    }
```

**Comment by castholm** [comment]
There's nothing wrong with the tests, you just discovered an aspect of how tasks work in C#: the task starts executing the moment you return from the async method. Because you start both tasks before you await either of them, both of them are already running by the time you begin to await `aTask`.

```csharp
var aTask = Get1(); // aTask starts executing here
var bTask = Get2(); // bTask starts executing here, immediately after aTask
var result1 = await aTask; // Wait for 300 ms for aTask to complete
var result2 = await bTask; // Wait for 0 ms for bTask, since it has already completed

return result1; // Total elapsed time: 300 ms
```

If you instead reorganize the code to await `aTask` before you start executing `bTask`, you get the blocking effect:

```csharp
var aTask = Get1(); // aTask starts executing here
var result1 = await aTask; // Wait for 300 ms for aTask to complete
var bTask = Get2(); // bTask starts executing here
var result2 = await bTask; // Wait for 200 ms for bTask to complete

return result1; // Total elapsed time: 500 ms
```

(Or as you might often see in code bases in the wild, with people awaiting the task immediately without storing the task in a local variable first:)

```csharp
var result1 = await Get1();
var result2 = await Get2();

return result1;
```

So, if possible and if it's critical for performance, you usually want to await tasks as late as possible and start multiple tasks concurrently if the design of a piece of code lets you.

For more information and examples, see https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#start-tasks-concurrently

**Comment by castholm** [comment]
As a side note, I doubt the JIT compiler is able to optimize out async methods, but when writing benchmarks you generally want to ensure you use the results of all method invocations so that they don't get optimized out. For example, you could simply add the results of all invocations by always using `return result1 + result2`.

**Comment by moisoiu** [comment]
@castholm  thanks for the explanation, I will run a couple of times more, in other ways to see how it behaves. 

Because I want to know if it's better to use Task.WhenAll or I can simply use await in terms of performance, especially if I'm not using those variables 

```
await Get1();
await Get2();
```

or 

`Task.WhenAll(Get1(), Get2());`

**Comment by moisoiu** [comment]
@castholm Thanks for the input, you are right. 

I've checked again like you said, and that of course impacts the performance when is used as the example you shown 

```
var aTask = Get1(); // aTask starts executing here
var result1 = await aTask; // Wait for 300 ms for aTask to complete
var bTask = Get2(); // bTask starts executing here
var result2 = await bTask; // Wait for 200 ms for bTask to complete

return result1; // Total elapsed time: 500 ms
```

I've re-run the tests. Thanks !
