### ISSUE TITLE
BenchmarkRunner Run with args

### ISSUE THREAD

**Issue by Wraith2** [dotnet/BenchmarkDotNet#1530]
The documentation for using CoreRun at https://benchmarkdotnet.org/articles/configs/toolchains.html#corerun fails to mention that you have to use an overload of the runner that is passed the args in order for it to pickup and use the corerun path. This may appear obvious but it wasn't. The documentation could be improved here to have a standalone example.

The only way to pass args seems to be to use `BenchmarkSwitcher` but since I have a single benchmark and don't want to switch I used `BenmarkRunner` which can't take args. So, can we have an overload of BenchmarkRunner.Run which takes args?

**Comment by adamsitnik** [comment]
Hi @Wraith2 

> This may appear obvious but it wasn't.

You are right, this is why we have added a warning in 0.12.1: https://github.com/dotnet/BenchmarkDotNet/pull/1359

> So, can we have an overload of BenchmarkRunner.Run which takes args?

there is an existing issue: https://github.com/dotnet/BenchmarkDotNet/issues/1290 and a PR https://github.com/dotnet/BenchmarkDotNet/pull/1292 to address this

I am closing this issue as the remaining part is covered by #1290
