### ISSUE TITLE
[Discussion] - New Mode: Estimate asm throughput

### ISSUE THREAD

**Issue by chrisaut** [dotnet/BenchmarkDotNet#1538]
Ryujit uses what they call "Perfscore" to estimate code quality of the asm they generate. This is done by basically assigning latency, or estimated cycles cost for every possible asm instruction they emit. They then assign a perfscore to a jitted method.

I can't seem to find any docs describing this in more detail, but you can see this in all the jit-diffs, ([example](https://github.com/dotnet/runtime/pull/42295#issuecomment-695015285)) or here is [the pr ](https://github.com/dotnet/runtime/pull/751/files)that enabled it for ARM64.

Obviously this is really only useful for very microlevel optimizations and only really as an additional data point, but I imagine BDN could do here is do something similar. We already have asm output on demand, as an additional step the asm could be analyzed and a score assigned, which could then be compared between runs/benchmarks, basically just another Analyzer. Since this doesn't even have to "run" the code it could also be very fast and thus be used to very quickly iterate on microlevel optimazations as a baseline datapoint before running full benchmarks.

Would this be useful/of interest at all?

**Comment by sandreenko** [comment]
@briansull  do we have documentation about PerfScore? cc @dotnet/jit-contrib

**Comment by jashook** [comment]
Generally these options are only enabled with a checked build of the runtime and JIT.

**Comment by chrisaut** [comment]
I wasn't even really thinking of using the Perfscore the Jit itself generates, although that would obviously save a lot of work, but that would limit it to certain runtimes only. I was more thinking BDN could do it's own calculation on the asm stream. As far as I understand essential you just need an instruction stream and a map with estimated latencies (which BDN could just copy from the runtime since they have already done the research).

**Comment by briansull** [comment]
PerfScore is a very rough estimate for instruction execution performance.
It isn't intended to accurately measure the actual performance, is it is a quick estimate with lots of simplifying assumptions.

To be accurate one would have to model the CPU functional units and measure the cycles between producing an value and using a value.   We don't try to do either with PerfScore.  It is most useful to estimate loop codegen improvements, such as hoisting a load from memory out of a loop and using a register inside the loop.

Such an optimization results in a small code size increase, but also has improved execution performance.

ARM64 latency and throughput numbers are based upon **arm_cortex_a55_software_optimization_guide_v2.pdf**

**Comment by adamsitnik** [comment]
@chrisaut thank you for your proposal and great discussion. 

As a maintainer of BenchmarkDotNet who implemented the DisassemblyDiagnoser, I would prefer to avoid adding such a feature to BDN and instead add it to the library that we are internally using for decoding the instructions - https://github.com/0xd4d/iced

I also don't see us having time to implement it anytime soon (our top priority should be ARM support) so I am going to close the issue.

Thank you all for a great discussion,
Adam
