### ISSUE TITLE
Inconsistency between benchmark filter and hint

### ISSUE THREAD

**Issue by kevingosse** [dotnet/BenchmarkDotNet#1539]
I tried running a benchmark with the command:
```
dotnet run -c Release -f netcoreapp3.1 -- -r net472 netcoreapp3.1 -m -f SpanBenchmark.StartFinishScope
```
But received a puzzling error message:

```
You must have made a typo in 'SpanBenchmark.StartFinishScope'. Suggestions:
        SpanBenchmark.StartFinishScope
```

It turns out that the filter operates on the full type name (in my case, Benchmarks.Trace.SpanBenchmark.StartFinishScope), but the CorrectionSuggester splits the type name on `.` and computes all the possible permutations (Benchmarks, Trace, Benchmarks.Trace, Trace.SpanBenchmarks, ...) , without checking if they're valid.

```
> dotnet run -c Release -f netcoreapp3.1 -- -r net472 netcoreapp3.1 -m -f Trace

You must have made a typo in 'Trace'. Suggestions:
        Trace
```

**Comment by kevingosse** [comment]
The weird part is that it seems to be by design: https://github.com/dotnet/BenchmarkDotNet/blob/master/tests/BenchmarkDotNet.Tests/CorrectionsSuggesterTests.cs#L68

```csharp
        [Fact]
        public void FilterByNamespace_LevenshteinOrdering()
        {
            var suggestedNames = new CorrectionsSuggester(new[]
            {
                typeof(NamespaceA.MyClassA),
                typeof(NamespaceB.MyClassB),
                typeof(AnotherNamespace.MyClassZ),
                typeof(NamespaceB.NamespaceC.MyClassC)
            }).SuggestFor("Nmespace");
            Assert.Equal(new[] { "NamespaceA", "NamespaceB", "NamespaceC" }, suggestedNames);
        }
```
Shouldn't this return "NamespaceA.MyClassA", "NamespaceB.MyClassB", "NamespaceB.NamespaceC.MyClassC" ?

**Comment by adamsitnik** [comment]
> Shouldn't this return

You are right, it should.

I am going to mark it as up-for-grabs and #hacktoberfest as it should be quite simple to fix.

**Comment by stanciuadrian** [comment]
I think `SuggestFor()` should still return `"NamespaceA", "NamespaceB", "NamespaceC"`. The role of `CorrectionsSuggester` is not to return fully-qualified class names with tests, but to suggest alternative filters that would result in at least one test method. Please keep in mind we are actually looking for methods, and not for classes.

Looking at the `FilterByNamespace_LevenshteinOrdering` test in particular, we have the `Nmespace` filter and the following benchmark methods:

    [0]: "AnotherNamespace.MyClassZ.MethodZ"
    [1]: "NamespaceA.MyClassA.MethodA"
    [2]: "NamespaceA.MyClassA.MethodB"
    [3]: "NamespaceB.MyClassB.MethodB"
    [4]: "NamespaceB.MyClassB.MethodC"
    [5]: "NamespaceB.NamespaceC.MyClassC.MethodC"

`Nmespace` is a max-3-letter typo for `NamespaceA` (2 matching tests: [1] & [2]), `NamespaceB` (3 matching tests: [3] & [4] & [5]), `NamespaceC` (1 matching test: [5]).

The source of the puzzling error message is that the filtering and the suggestion mechanisms are not compatible:

- The `SpanBenchmark.StartFinishScope` command line filter is transformed into a regex in `GlobFilter.WildcardToRegex`. This transformation handles file-style wildcard globbing but also adds start/end anchors: `^SpanBenchmark.StartFinishScope$`. Then the non-qualified class name is compared with the original filter (`SpanBenchmark` != `SpanBenchmark.StartFinishScope`) and the fully-qualified class name is matched against the regex (`Benchmarks.Trace.SpanBenchmark.StartFinishScope` doesn't match `^SpanBenchmark.StartFinishScope$`). At this point filtering returns 0 methods so suggestions are tried.
- As you have already noticed, your filter is now matched against fragments of the fully qualified method name: `Benchmarks.Trace.SpanBenchmark.StartFinishScope`. A 0-distance (yay!) suggestion is found and your filter is printed on the screen.

Using the `Trace` filter triggers the same behavior.

Removing the `^$` anchors from the regex will fix the issue. At the same time, [How to use console arguments | BenchmarkDotNet](https://benchmarkdotnet.org/articles/guides/console-args.html) suggests wildcards are mandatory: `*SpanBenchmark.StartFinishScope` and `*Trace*`. Fair enough. If you have a single test method in your class, just use its unqualified name: `SpanBenchmark`.

You have definitely found a bug, but what step do we fix?

**Comment by adamsitnik** [comment]
> suggests wildcards are mandatory

yes, this is by design and I intend to keep it that way so removing the `^$` anchors is rather not an option (it would be a breaking change and the glob pattern matching with `*` was introduced on purpose).

If we have the following type:

```cs
namespace A
{
   public class B
   {
        [Benchmark]
        public void C() { }
   }
}
```

And the user passes filter `B.C`:

```cmd
--filter B.C
```

The hint should mention that either `A.B.C` or `*B.C`.
