### ISSUE TITLE
Is it possible to benchmark an IL interpreter with BDN?

### ISSUE THREAD

**Issue by AxelHu** [dotnet/BenchmarkDotNet#1541]
I'm a game developer using Unity, due to JIT restriction on iOS, our team is currently using an [IL interpreter](https://github.com/Ourpalm/ILRuntime) to do hotfix on iOS.

We're using this for code that will not affect performance too much, but still we want better performance. To do that we need more accurate benchmark, we now use numbers like overall fps or cpu time per frame to check if the performance is good. 

So is it possible to benchmark an IL interpreter with BDN? Which part should I modify to do this?

We want to benchmark with :
- different versions of that IL interpreter
- the .net official one
- currently supported runtimes in BDN

By the way, Unity use IL2CPP to convert IL into cpp code including this IL interpreter, I'm not sure how it will affect the result.

**Comment by adamsitnik** [comment]
Hi @AxelHu 

BechmarkDotNet generates some boilerplate code, builds it, and runs every benchmark as a stand-alone process. Because of that, we support only selected .NET Runtimes (the ones for which we have implemented the support).

As of today, Unity is not supported (https://github.com/dotnet/BenchmarkDotNet/issues/759) and we currently don't plan to add such support. A contribution would be of course welcome ;)

> currently supported runtimes in BDN

this is described in our docs: https://benchmarkdotnet.org/articles/configs/toolchains.html

> the .net official one

I am not sure how to do it, you would most probably need to find out which env vars to set and configure it as explained in this doc:

https://benchmarkdotnet.org/articles/guides/customizing-runtime.html#sample-introenvvars

**Comment by AxelHu** [comment]
@adamsitnik 
Thanks for the links.

It's really good if benchmarking Unity's internal methods is possible, but that's not the point we concern, we're not able to modify Unity engine code and the performance is good using Unity's default setting(IL2CPP).

Using that IL interpreter makes the performance a little bit unacceptable, we use that for code needs to be hotfixed. We need benchmark results to decide which part can be put into the hotfix dll, and that IL interpreter works without Unity.

So we actually want to know the benchmark results of that IL interpreter with some .net code(not the Unity engine code), though the result is not accurate due to Unity's IL2CPP, it's enough for us to make decisions currently.

**Comment by adamsitnik** [comment]
@AxelHu I see.

Let's say I want to run a `Hello World` app using this interpreter. What are the steps that I need to take to make it possible? Set some env vars? 

I am asking this question because BDN needs to do exactly the same and I've never used interpreter so I don't know if it's possible or not.

**Comment by AxelHu** [comment]
@adamsitnik 
That IL interpreter use mono.cecil to analysis target dll, I uploaded a `Hello World` example [here](https://github.com/AxelHu/ILR-HelloWorld).

The way that IL interpreter handles the IL instructions is pretty much like the dotnet [official interpreter](https://github.com/dotnet/coreclr/blob/release/3.1/src/vm/interpreter.cpp). But I'm not an expert in cpp and I don't know how to make the official one run. 

[This](https://mattwarren.org/2017/03/30/The-.NET-IL-Interpreter/) is a blog post about the official interpreter.

**Comment by SingleAccretion** [comment]
Just FYI, the CoreCLR interpreter is not something usable in production currently, the Mono interpreter is what we currently would all "official", as it is used by Blazor and, as you noted, to polyfill dynamic code generation support with Mono's AOT.

**Comment by AxelHu** [comment]
@SingleAccretion Thanks for the tips.

Didn't know that mono has an in production interpreter, I'll check if this can be used in my situation.

**Comment by adamsitnik** [comment]
@AxelHu thanks for providing the example!

In such a case, I think that the easiest way to get some benchmark numbers would be to use the [InProcessToolchain](https://benchmarkdotnet.org/articles/configs/toolchains.html#sample-introinprocess) that uses IL Emit and runs everything in the same process.

The `HelloWorld` should get replaced with something like this:

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);
    }

    public class Demo
    {
        [Benchmark]
        public void Benchmark() { } 
    }
}
```

and when invoking it [here](https://github.com/AxelHu/ILR-HelloWorld/blob/72465598bee273330c2e683331ab2fd18253f5ad/RunHelloWorldWithILR/Program.cs#L370) you would somehow need to pass `new string[] { "--inProcess", "--filter *"  }` to the `Main` method (to make sure that `args` get populated and BDN uses `InProcessToolchain`)

to get the non-interpreted numbers you would just need to run the app directly without the `--inProces` argument

**Comment by AxelHu** [comment]
@adamsitnik Thanks for the solution.

I think this will work with the official interpreter(Mono interpreter) in the previous reply.

But it fails with the ILR, because it's not a full support for IL instructions. The ILR is supported by few people and not all instructions will be used in games(ILR mainly supports Unity games).

I'm not exactly sure how BDN works internally, but I think this solution will run everything with that IL interpreter(ILR)? It's better to just run the method execution part with ILR, and run everything else with supported dotnet runtime.

**Comment by adamsitnik** [comment]
> I'm not exactly sure how BDN works internally, but I think this solution will run everything with that IL interpreter(ILR)?

Yes, this is true.

> It's better to just run the method execution part with ILR, and run everything else with supported dotnet runtime.

For that you would have to implement your own [Toolchain](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Toolchains/IToolchain.cs) which consists of:

* generator - a type that generates benchmarking boilerplate code
* builder - a type that builds the code
* executor - a type that runs the executable

You could reuse the [.NET Core Toolchain](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs) Generator and Builder and write your own Executor that would be loading the produced `.dll` file using ILR like in your example: https://github.com/AxelHu/ILR-HelloWorld/blob/72465598bee273330c2e683331ab2fd18253f5ad/RunHelloWorldWithILR/Program.cs#L16-L39

The boilerplate that we generate looks like this:
https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Templates/BenchmarkProgram.txt
https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Templates/BenchmarkType.txt

It could turn out that the existing auto-generated code uses instructions which are not supported by ILR and it would not work at all ;/

IMO the best way to learn how BDN works would be to clone our repo and debug the sample benchmark from the samples project.

**Comment by AxelHu** [comment]
Thanks I'll give it a try, writing just the Executor part sounds like something possible for me.

By the way, are there any collection of typical methods to benchmark in C#? In my case, I want to get an overall benchmark result. I added typical methods used in my projects and methods collected from internet, but it's far from complete.

**Comment by adamsitnik** [comment]
> By the way, are there any collection of typical methods to benchmark in C#

You could use some of the benchmarks from dotnet/performance repository that are used by the .NET Team to ensure that .NET itself s not regressing perf over time

https://github.com/dotnet/performance/tree/master/src/benchmarks/micro

**Comment by adamsitnik** [comment]
@AxelHu I hope that I have answered all your questions. I am going to close the issue, but please feel free to reopen it if you have more questions.

Thanks!
