### ISSUE TITLE
Nullable Reference Types, setup Attributes vs Constructor+IDisposable

### ISSUE THREAD

**Issue by virzak** [dotnet/BenchmarkDotNet#1551]
Trying to convert a benchmarking sample to be nullable by setting `<Nullable>enable</Nullable>`, and a warning shows up for this line:

https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/samples/BenchmarkDotNet.Samples/IntroSetupCleanupGlobal.cs#L10

```
warning CS8618: Non-nullable field 'data' is uninitialized. Consider declaring the field as nullable.
```

What's the strategy to deal with NRT for a case like this?

Could the xUnit's [approach](https://xunit.net/docs/comparisons) to setup and teardown be leveraged? Instead of attributes Constructor+IDisposable would be used.

**Comment by adamsitnik** [comment]
Hi @virzak

> Trying to convert a benchmarking sample to be nullable by setting

Why are you trying to do it? Our CI uses .NET Core 2.1 and we don't plan to use the `Nullable` feature in the Samples project (we want to keep samples as simple as possible to focus on BDN)

> What's the strategy to deal with NRT for a case like this?

I don't know. Please ask a question on StackOverflow.

>  Instead of attributes Constructor+IDisposable would be used. 

We decided to go with attributes a long time ago and unfortunately, we have to follow this strategy. Otherwise, it would be a big breaking change for our users. 

There is nothing actionable on BDN side, so I am closing this issue.

Have a nice day,
Adam

**Comment by virzak** [comment]
@adamsitnik The project I'm working on uses the latest .Net along with latest features like nullable. Modifying your sample was an exercise in upgrading. Submitting a PR or messing up the CI wasn't the intent.

Since `nullable` will be enabled by default in future releases of .Net, this warning will eventually become a part of this repo.

Asking this question on github seems like an appropriate place. Here are issues [1](https://github.com/dotnet/efcore/issues/10347) and [2](https://github.com/dotnet/efcore/issues/17212) and [docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types) on the same topic from EF Core team.

The obvious answer to my question would be to use ! as in:

```csharp
private int[] data = null!;
```

Just was wondering if there's anything better.

**Comment by aelij** [comment]
@adamsitnik Would it be possible to support the `required` property modifier?
Currently it causes a build error as the generated code doesn't use object initializers:

```cs
BenchmarkDotNet.Autogenerated.Runnable_2 instance = new BenchmarkDotNet.Autogenerated.Runnable_2(); // do NOT change name "instance" (used in SmartParamameter)
instance.Value = ...
```

To support `required` it would need to be:

```cs
BenchmarkDotNet.Autogenerated.Runnable_2 instance = new BenchmarkDotNet.Autogenerated.Runnable_2 { Value = ... };
```

**Comment by adamsitnik** [comment]
> Would it be possible to support the required property modifier?

Yes if you are willing to provide tests and implementations. 

The template is located here:

https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Templates/BenchmarkType.txt#L6-L7

And the actual content is generated here:

https://github.com/dotnet/BenchmarkDotNet/blob/6a7244d76082f098a19785e4e3b0e0f269fed004/src/BenchmarkDotNet/Code/CodeGenerator.cs#L59
