### ISSUE TITLE
Error 42883: Function with smallint parameter does not exist

### ISSUE THREAD

**Issue by zykindmitry** [dotnet/BenchmarkDotNet#1553]
There's a function 
 public.is_access_granted(integer,uuid,uuid,integer,smallint,boolean) returns boolean;
and corresponding .net core static method
    public static class Functions
    {
        private static string NotSupportedExceptionMessage = "This function can be used only in LINQ to SQL";

        public static bool IsAccessGranted(int classId, Guid? id, Guid? ownerId, int? ownerClassId, short? type, bool? propagate)
            => throw new NotSupportedException(NotSupportedExceptionMessage);
    }
with mapping defined like the following:
            modelBuilder
                .HasDbFunction(
                    typeof(Functions).GetRuntimeMethod(
                    nameof(Functions.IsAccessGranted),
                    new[] { typeof(int), typeof(Guid?), typeof(Guid?), typeof(int?), typeof(short?), typeof(bool?) }))
                .HasTranslation(
                    args =>
                        SqlFunctionExpression.Create(
                        modelBuilder.Model.GetDefaultSchema(),
                        "is_access_granted",
                        args,
                        typeof(bool),
                        null));

Using this function in a LINQ-to-SQL query (in where clause) causes an exception:

{"42883: function is_access_granted(integer, uuid, uuid, integer, **integer**, boolean) does not exist"} (_note: exception text is translated into english and may not match the exact message text_)

Also note that adding breakpoint into HasTranslation method shows that the 5th parameter has correct data type (smallint), however (according to the message text pg searches the wrong signature and fails to find one).

The workaround is to change the data type of the 5th parameter (along with other related stuff) to integer. In this case the whole query works without any error.

**Comment by adamsitnik** [comment]
@zykindmitry hi! how is this related to BenchmarkDotNet?

**Comment by zykindmitry** [comment]
> @zykindmitry hi! how is this related to BenchmarkDotNet?

Hi! I apologize, my mistake.
