### ISSUE TITLE
BenchmarkDotNet cannot handle AppendTargetFrameworkToOutputPath set to false

### ISSUE THREAD

**Issue by TimHolzherr** [dotnet/BenchmarkDotNet#1562]
Hi

When running a benchmark it appears that BenchmarkDotNet copies the benchmark code and compiles it with the dotnet cli.
The path resolution to the generated dll assumes that [AppendTargetFrameworkToOutputPath](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-the-build-output-directory?view=vs-2019) is set to true (the default).
An example where this assumption fails is if a [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019) file is present in a parent folder which could set AppendTargetFrameworkToOutputPath to false.
In this case the benchmark fails with the following error because it cannot find the generated dll: 
```
Did not find <myProject>\bin\Release\38540316-12d5-49d8-9cc3-e8bd5cdac8f7\bin\Release\netcoreapp3.1\38540316-12d5-49d8-9cc3-e8bd5cdac8f7.dll, but the folder contained:
38540316-12d5-49d8-9cc3-e8bd5cdac8f7.dll.config
Executable <myProject>\bin\Release\38540316-12d5-49d8-9cc3-e8bd5cdac8f7\bin\Release\netcoreapp3.1\38540316-12d5-49d8-9cc3-e8bd5cdac8f7.dll not found
ExitCode != 0
```
Reproducible example: https://github.com/TimHolzherr/BenchmarkDotNet_AppendTargetFrameworkIssue

**Comment by johnthcall** [comment]
@AndreyAkinshin @adamsitnik Is there a plan for releasing 12.2? I'm unable to multi-target the benchmarks in my repo without this fix.

**Comment by adamsitnik** [comment]
@johnthcall you can use our preview packages from our CI feed: https://benchmarkdotnet.org/articles/guides/nuget.html#nightly

@AndreyAkinshin we should really release a new version ;)
