### ISSUE TITLE
error MSB4086: A numeric comparison was attempted on "$(LangVersion)"

### ISSUE THREAD

**Issue by marek-safar** [dotnet/BenchmarkDotNet#1564]
When having a project with settings like

```
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
```

BDN fails to run because of the following error

```
 /Users/path/Release/net5/aa4bffdc-8430-4262-ae51-d3e2e06d560b/BenchmarkDotNet.Autogenerated.csproj(20,18): error MSB4086: A numeric comparison was attempted on "$(LangVersion)" that evaluates to "latest" instead of a number, in condition "'$(LangVersion)' == '' Or '$(LangVersion)' < '7.3'".
```

**Comment by WojciechNagorski** [comment]
I think that this is fixed by https://github.com/dotnet/BenchmarkDotNet/commit/82b15eec13bc324013cc5089685b1bac4aa5324f

**Comment by adamsitnik** [comment]
@WojciechNagorski is right, this has already been fixed but not released to nuget.org in #1420

I've ensured that it works as expected using our master branch build. What we generate now is:

```xml
<LangVersion Condition="'$(LangVersion)' == '' Or ($([System.Char]::IsDigit('$(LangVersion)', 0)) And '$(LangVersion)' &lt; '7.3')">latest</LangVersion>
```

**Comment by paulegradie** [comment]
Any idea when the next release (0.12.2) is going to make it to nuget? Would be nice to have this fix available. Currently prototyping some benchmarking work and I have to clone and locally install to get around it. 🙏 🙏

**Comment by adamsitnik** [comment]
> I have to clone and locally install to get around it

You can install the latest preview from our CI feed: https://benchmarkdotnet.org/articles/guides/nuget.html#nightly

> Any idea when the next release (0.12.2) is going to make it to nuget? 

@AndreyAkinshin is the best person to answer this question
