### ISSUE TITLE
Benchmark runs failing when using .NET 5 RC2 SDK installed via snap

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/BenchmarkDotNet#1570]
I tried installing .NET 5 RC2 sdk on Ubuntu 20.04 following the [instructions listed here](https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-rc.2-install-instructions.md#install-using-snap). 

When trying to run `net5.0` benchmarks using that SDK I'm getting the following failure:
```
BenchmarkDotNet requires dotnet cli to be installed or path to local dotnet cli provided in explicit way using `--cli` argument, benchmark 'HeapSortBenchmarks.PriorityQueue: DefaultJob [Size=30]' will not be executed
```

I suspect the issue is due to the fact that the snap installation of the sdk relies on symlinks:
```
$ ls -l `which dotnet`
lrwxrwxrwx 1 root root 17 Oct 23 13:33 /snap/bin/dotnet -> dotnet-sdk.dotnet
```
When I try to run the benchmarks using
```
$ dotnet run -c Release --cli dotnet
```
I'm getting a similar error:
```
The provided CliPath "dotnet" does NOT exist.
```
However if I pass the underlying file:
```
$ dotnet run -c Release --cli /snap/bin/dotnet-sdk.dotnet
```
The benchmark executes without issue.

The relevant code doing the detection [is here](https://github.com/dotnet/BenchmarkDotNet/blob/cd0bda41dce2f266bc09900e31d8f0d4f52eedec/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs#L54). It is not clear to me whether it is an issue with the heuristic or a System.Diagnostics.Process bug related to symlinks. cc @adamsitnik

**Comment by rahulpandey1** [comment]
@eiriktsarpalis still facing same issue
removed .net 5 even same issue
![image](https://user-images.githubusercontent.com/12515078/131428937-fa095932-76bf-4d8f-9dea-95feee70a1c4.png)

**Comment by adamsitnik** [comment]
@rahulpandey1 which BDN version are you using? what if you use `dotnet run -c Release` instead of `dotnet $pathToDll`?
