### ISSUE TITLE
can this use profiler mono runtime memory profiler?

### ISSUE THREAD

**Issue by srxqds** [dotnet/BenchmarkDotNet#1578]
as we know the mono vm is difference with coreclr?
but how can we use it to profiler memory allocate on mono vm?

**Comment by adamsitnik** [comment]
Hi @srxqds 

I am not sure if I understand your question but I assume that you speak about `MemoryDiagnoser`.

When I was implementing the MemoryDiagnoser 4 years ago, Mono was throwing `NotImplementedException` for  `AppDomain.MonitoringTotalAllocatedMemorySize` and `GC.GetAllocatedBytesForCurrentThread`

https://stackoverflow.com/questions/40234948/how-to-get-the-number-of-allocated-bytes-in-mono

@egorbo do you know if this has changed? if yes, which Mono version supports it (I would need to be able to test it add and some magic version detection to use it only for newer Mono versions)

**Comment by EgorBo** [comment]
@adamsitnik yep, `GC.GetAllocatedBytesForCurrentThread` and `GC.GetTotalAllocatedBytes` should work fine on Mono but only with .NET 5 and not in interpreter mode.

**Comment by adamsitnik** [comment]
@EgorBo thanks!

Do I understand correctly that Mono 6.12.0 which can be downloaded from https://www.mono-project.com/download/stable/ is not the .NET 5 Mono? How can I get the .NET 5 Mono?

**Comment by EgorBo** [comment]
> @EgorBo thanks!
> 
> Do I understand correctly that Mono 6.12.0 which can be downloaded from https://www.mono-project.com/download/stable/ is not the .NET 5 Mono? How can I get the .NET 5 Mono?

No, that's one is "classic" Mono, I don't think we have any official way to consume mono for .NET 5 atm. For .NET 5 we only ship Mono-wasm for Blazor.

One possible hack to consume Mono-net5 is here: https://github.com/EgorBo/MonoNET5Sample (not Windows-friendly)
AFAIK, @naricc is trying to figure out how to properly consume it for benchmarks now.

**Comment by naricc** [comment]
@adamsitnik 

So, the way we are running benchmarks for  mono in .net5 (except for wasm, which is now supported in BDN) is to build a dotnet host, and then patch it with the mono-runtime bits by overwriting the appropraite dlls. For the runtime tests, we are buildign coreclr and patching it using this target: 

https://github.com/dotnet/runtime/blob/ec26ee542d660d378004633de2eb511d6290a78c/src/mono/mono.proj#L105

For the automated microbenchmarks, we are doing something similar using corerun (if you can parse this yml):

https://github.com/dotnet/runtime/blob/02835913b8304dabe4d6613a080fa21d14fba186/eng/pipelines/coreclr/templates/perf-job.yml#L122

**Comment by srxqds** [comment]
yeah, we also hope it can work in mono interpreter mode.
thank you
