### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by kg** [dotnet/BenchmarkDotNet#1594]
Issue #333 doesn't seem to be fixed. I'm running some benchmarks in wasm, and presumably one of them is failing because I get this:

```
// Job: Job-TVXTDS(PowerPlanMode=00000000-0000-0000-0000-000000000000, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1)

OverheadJitting  1: 1 op, 34000.00 ns, 34.0000 us/op
// Benchmark Process 110732 has exited with code 0
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MicroBenchmarks.Program.Main(String[] args) in /home/kate/Projects/performance/src/benchmarks/micro/Program.cs:line 41
```

I'm not really sure why BDN would silently swallow the exception and then fail like this. Is there some way to get at the actual exception? Before my most recent changes to the test it was running, but I added an error check to it that is probably throwing now.

**Comment by adamsitnik** [comment]
> I'm not really sure why BDN would silently swallow the exception and then fail like this. 

BDN does not swallow any exceptions. The boilerplate code contains a big try-catch block that wraps the entire actual benchmarking and writes output to the console whenever an exception is thrown and just exits.

https://github.com/dotnet/BenchmarkDotNet/blob/0de41c2864de41fef983e55790490f1b3364ccbf/src/BenchmarkDotNet/Templates/BenchmarkProgram.txt#L35-L76

> Is there some way to get at the actual exception? 

For non-WASM apps you can always just attach a VS debugger, but I am not sure how it works with WASM.

> Before my most recent changes to the test it was running, but I added an error check to it that is probably throwing now.

**Comment by kg** [comment]
More testing with --keepfiles revealed that the WASM app was crashing and BDN was swallowing the output. It's not clear whether the exit code was 0 or not. I surrounded it all in a try block and it crashed anyway.

**Comment by adamsitnik** [comment]
In the output that you have provided, there was information about 0 exit code:

> // Benchmark Process 110732 has exited with code 0

> I surrounded it all in a try block and it crashed anyway.

Do you mean the logic inside the method with the `[Benchmark]` attribute? Is such a case it could be only some serious exception that runtime itself can't catch like `StackOverfloweException` or `AccessViolationException`. Is it possible that your code is dealing with some native methods, unsafe memory, or infinite recursion?

**Comment by kg** [comment]
It was an exception in the WASM code for the mono runtime, inside of a JS function call. I had a JS try block in the JS function call in addition to a C# try block in the benchmark method. It seems like it's impossible to catch runtime errors, so it might be good for BDN's wasm support to take this into account somehow. It's unfortunate that v8 produces a 0 exit code in this case (I'll see if there's some way I can fix this in the runtime).

When it crashes in this way, v8 dumps a detailed stack trace. I'm not sure where it goes. (Does BDN generate a log file somewhere I should be checking?)

**Comment by adamsitnik** [comment]
>  I'm not sure where it goes. (Does BDN generate a log file somewhere I should be checking?)

I am not familiar with how v8 exactly works, but they way BDN starts the process is defined here:

@naricc is the best person to provide more details, I was just the person who reviewed his PR and tested it locally
https://github.com/dotnet/BenchmarkDotNet/blob/0de41c2864de41fef983e55790490f1b3364ccbf/src/BenchmarkDotNet/Toolchains/Executor.cs#L118-L121

The values come from:

https://github.com/dotnet/BenchmarkDotNet/blob/0de41c2864de41fef983e55790490f1b3364ccbf/src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs#L398-L399

https://github.com/dotnet/BenchmarkDotNet/blob/13ee8bebd7484fcab007a52d9a5ca4aea5e67b34/src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs#L177-L178

I guess that you should pass something via `--wasmArgs`? Which has a default value of `--expose_wasm`

**Comment by naricc** [comment]
I would expect the stack trace to go to the standard output with everything else. I didn't add anything to explicitly throw stack traces away, but maybe we are losing it accidentally some how.

**Comment by kg** [comment]
I will see if perhaps the stack trace is going to stderr and somehow that's getting blackholed.
