### ISSUE TITLE
Make ClrMd Source diagnoser working with new ClrMD api

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#160]
@mattwarren I have put all the code in clrmd branch. I was able to get the RuntimeDiagnoser running.

When you start working with that please revert [this commit](https://github.com/PerfDotNet/BenchmarkDotNet/commit/27b96c4a1b5e1a128af28382b9ce32c85b6c6526) In general I have just excluded the files that do not compile from compilation 

@AndreyAkinshin this is something that I had discussed first with Matt, now our Diagnostics package has no native dependencies and you should be able to release Diagnostics.Windows. Which BTW is already signed.

**Comment by mattwarren** [comment]
At the same till, also solve item 3) from #53 

>  Now I have troubles with diagnostic of x86 benchmark from the x64 host application. Can we fix it?

**Comment by adamsitnik** [comment]
Fixed with [this](https://github.com/dotnet/BenchmarkDotNet/commit/647a6745da75bf3893f2e9b7ec35b3ff20a14caa) commit
