### ISSUE TITLE
Update API in documentation

### ISSUE THREAD

**Issue by WojciechNagorski** [dotnet/BenchmarkDotNet#1602]
There are many places in the documentation where we use:
* obsolete APIs (e.g. https://benchmarkdotnet.org/articles/configs/configs.html#object-style)
* APIs that have been changed (e.g. https://benchmarkdotnet.org/articles/configs/jobs.html#object-style).

Currently, I don't have enough time to address all of them.

**Comment by WojciechNagorski** [comment]
@adamsitnik You can mark this issue as `Hacktoberfest`, `good first issue`, `help wanted`, `up-for-grabs`. I can't do it.

**Comment by kevinsalimi** [comment]
Evening,
If no one works on this, I would like to take part.

**Comment by adamsitnik** [comment]
> If no one works on this, I would like to take part.

@kevinsalimi great, I've assigned you!
