### ISSUE TITLE
CoreRT / NativeAOT version

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/BenchmarkDotNet#1605]
As per [this issue](https://github.com/dotnet/runtimelab/issues/415#issuecomment-737468088) BDN is using an outdated version by default, and I've not been able to find a way to set the version manually.

**Comment by adamsitnik** [comment]
Hi @HurricanKai 

I've sent a PR that updates the compiler version and feed address: #1606

In the meantime, you can use the following code to get it working:

```cs
var config = DefaultConfig.Instance
    .AddJob(Job.Default
        .WithRuntime(CoreRtRuntime.CoreRt50)
        .WithToolchain(CoreRtToolchain.CreateBuilder()
            .UseCoreRtNuGet(
                microsoftDotNetILCompilerVersion: "6.0.0-*",
                nuGetFeedUrl: "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json")
            .ToToolchain()));

BenchmarkSwitcher
    .FromAssembly(typeof(Program).Assembly)
    .Run(args, config);
```

**Comment by HurricanKai** [comment]
Awesome, thanks!
