### ISSUE TITLE
EventPipeProfiler generating invalid SpeedScope files.

### ISSUE THREAD

**Issue by stebet** [dotnet/BenchmarkDotNet#1613]
Due to a recent change in the SpeedScope app and BenchmarkDotNet using outdated dotnet diagnostics tools, it currently generates invalid SpeedScope files that refuse to load with an error like:
```javascript
Failed to load format Error: Tried to leave frame "system.collections.concurrent.il!System.Collections.Concurrent.ConcurrentDictionary`2[System.__Canon,System.__Canon].GetOrAdd(!0,class System.Func`2<!0,!1>)" while frame "BenchmarkDotNet!BenchmarkDotNet.Characteristics.CharacteristicHelper.GetThisTypeCharacteristicsCore(class System.Type)" was at the top at 34.0138
    at h._leaveFrame (speedscope.44364064.js:174)
    at h.leaveFrame (speedscope.44364064.js:174)
    at speedscope.44364064.js:180
    at a (speedscope.44364064.js:180)
    at speedscope.44364064.js:180
    at Array.map (<anonymous>)
    at s (speedscope.44364064.js:180)
    at import.cf0fa83f.js:113
    at Generator.next (<anonymous>)
    at s (import.cf0fa83f.js:113)
```

Attached is speedscope file generated using BenchmarkDotNet 0.12.1
[speedscope.zip](https://github.com/dotnet/BenchmarkDotNet/files/5666791/speedscope.zip)

 A similar issue was reported here: https://github.com/dotnet/diagnostics/issues/1206

**Comment by adamsitnik** [comment]
@stebet could you please try our latest preview version from our CI feed https://benchmarkdotnet.org/articles/guides/nuget.html#nightly and let us know if you can still repro it?

**Comment by stebet** [comment]
Will do. Otherwise I think I have a PR ready with a fix :)

**Comment by stebet** [comment]
Confirmed fixed in latest nightly :) Thx for the tip.

**Comment by adamsitnik** [comment]
@stebet thank you!
