### ISSUE TITLE
Add an "Allocated Ratio" column when using the memory diagnoser?

### ISSUE THREAD

**Issue by njy** [dotnet/BenchmarkDotNet#1615]
When I try to wrap my head around speed differences I find it helpful to quickly look at the ratio column.

Wouldn't it be helpful to have the same kind of column about memory allocations?

**Comment by adamsitnik** [comment]
Hi @njy 

> Wouldn't it be helpful to have the same kind of column about memory allocations?

Yes!

We alread have an issue that tracks this feature request: #722 (which is `up-for-grabs` BTW) so I am going to close this one.

**Comment by njy** [comment]
Great,thanks!
Before posting I did check and in fact stumbled upon that issue, but was not sure if it was the same request, sorry for the double post.

I'll try to see if I'm able to implement it.
