### ISSUE TITLE
BenchmarkDotNet fail in WPF project with .NET 5.0-windows target

### ISSUE THREAD

**Issue by lindexi** [dotnet/BenchmarkDotNet#1616]
Step:

1. Create a WPF project
2. Add BenchmarkDotNet package
3. Add and run any Benchmark code

Running the Benchmark code that we can find error NU1201: Project Benchmark is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Project Benchmark supports: net5.0-windows7.0 (.NETCoreApp,Version=v5.0)

```
 Standard error:
   Restored f:\Code\lindexi\WpfInk\Benchmark\Benchmark.csproj (in 275 ms).
  Restored f:\Code\lindexi\WpfInk\WpfInk Old\WpfInkOld.csproj (in 84 ms).
  Restored f:\Code\lindexi\WpfInk\WpfInk\WpfInk.csproj (in 84 ms).
  Failed to restore f:\Code\lindexi\WpfInk\Benchmark\bin\Release\net5.0-windows\82790c3e-0ce6-4852-a0db-f9674aea9be3\BenchmarkDotNet.Autogenerated.csproj (in 86 ms).
f:\Code\lindexi\WpfInk\Benchmark\bin\Release\net5.0-windows\82790c3e-0ce6-4852-a0db-f9674aea9be3\BenchmarkDotNet.Autogenerated.csproj : error NU1201: Project Benchmark is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Project Benchmark supports: net5.0-windows7.0 (.NETCoreApp,Version=v5.0)
  Determining projects to restore...

// Build Error: Standard output:

 Standard error:
   Restored f:\Code\lindexi\WpfInk\Benchmark\Benchmark.csproj (in 275 ms).
  Restored f:\Code\lindexi\WpfInk\WpfInk Old\WpfInkOld.csproj (in 84 ms).
  Restored f:\Code\lindexi\WpfInk\WpfInk\WpfInk.csproj (in 84 ms).
  Failed to restore f:\Code\lindexi\WpfInk\Benchmark\bin\Release\net5.0-windows\82790c3e-0ce6-4852-a0db-f9674aea9be3\BenchmarkDotNet.Autogenerated.csproj (in 86 ms).
f:\Code\lindexi\WpfInk\Benchmark\bin\Release\net5.0-windows\82790c3e-0ce6-4852-a0db-f9674aea9be3\BenchmarkDotNet.Autogenerated.csproj : error NU1201: Project Benchmark is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Project Benchmark supports: net5.0-windows7.0 (.NETCoreApp,Version=v5.0)
  Determining projects to restore...
```

Demo: https://github.com/lindexi/lindexi_gd/tree/f0b45eecb63e6ceef7a3abe5b43503abb317fd70/WpfInk

**Comment by adamsitnik** [comment]
Hi @lindexi 

This problem has been already reported (#1535) and fixed (#1560) but we just have not released new version to NuGet.org

To get it working today you need to use the latest preview version from our CI feed: https://benchmarkdotnet.org/articles/guides/nuget.html#nightly

Thanks,
Adam

**Comment by lindexi** [comment]
Thank you @adamsitnik

**Comment by adamsitnik** [comment]
@raffaeler is there a chance you could create a small GitHub repo with a repro?

**Comment by raffaeler** [comment]
Hi Adam, the project looks like straightforward.
Could you try this project configuration first?

All I do is just calling `BenchmarkRunner.Run<MyBenchmark>();` with a very simple test.

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
        <Platforms>x64;x86</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VCRTForwarders.140" Version="1.0.7" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.12.1.1527" />

        <!-- C# projection of my C++ library -->
        <PackageReference Include="WinNativeUtilities" Version="1.0.412.163840" />
    </ItemGroup>
</Project>
```

**Comment by adamsitnik** [comment]
@raffaeler I was able to repro, sent the fix in #1691 I am sorry for the delay but recently I've been 100% busy ;/

**Comment by raffaeler** [comment]
@adamsitnik no worries, I totally understand, I am also on several projects and it's difficult to multiplex the time 
Hope to meet in some conference before or later, toasting with beers :)

**Comment by adamsitnik** [comment]
> Hope to meet in some conference before or later, toasting with beers :)

I am looking forward to that!

**Comment by nick-beer** [comment]
@adamsitnik - I'm still seeing this error with `0.13.0`.  I'm targeting `net5.0-windows`.  I'm using `BenchmarkRunner.Run<T>` from within an xunit test.  The workaround listed in #1535 (explicitly specifying the toolchain) does work for me.

Interestingly, `0.13.0` *does* work when using `BenchmarkSwitcher.FromAssembly().Run()`...

I've attached a very simple repro - a `.csproj` file and the `.cs` file that contains the xunit test that runs the benchmark.  If you just run `dotnet test -c Release`, you should see the familiar error:
```
error NU1201: Project bdn-testing is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Project bdn-testing supports: net5.0-windows7.0 (.NETCoreApp,Version=v5.0)
```
[bdn-testing.zip](https://github.com/dotnet/BenchmarkDotNet/files/6795962/bdn-testing.zip)

**Comment by deeprobin** [comment]
I strangely get no output at all when using WPF with BenchmarkDotNet. Not even an error. Only a "Process exited with exit code 0".
