### ISSUE TITLE
Integrate with msbuild

### ISSUE THREAD

**Issue by ExceptionCaught** [dotnet/BenchmarkDotNet#1623]
Hi:
     As stated in the documentation, BDN supports Full .NET Framework (4.6+) as well. 
     However, most of the classic .net framework uses the old project file. Is there any plan to integrate with msbuild as a custom Task. I think it will dramatically expand the use case of BDN for the classic solution.

**Comment by adamsitnik** [comment]
Hi @ExceptionCaught 

> However, most of the classic .net framework uses the old project file. 

Both old and new project files are supported. Our Full .NET Framework toolchain uses Roslyn to generate and build the assembly, so this is not affecting it.

Is there something that does not work for you? Can you share a repro?

**Comment by ExceptionCaught** [comment]
hi @adamsitnik . I am trying to achieve the same thing for our full .net framework project as `dotnet benchmark MyAssemblyWithBenchmarks.dll --filter *` which is documented on [this page](https://benchmarkdotnet.org/articles/guides/how-to-run.html). unless we can dotnet benchmark on the dll that is generated by msbuild?

**Comment by adamsitnik** [comment]
@ExceptionCaught I see.

The global dotnet benchmark tool was causing too many troubles and we have decided to remove it: https://github.com/dotnet/BenchmarkDotNet/pull/1572

We still have not released a new version, but it's going to be removed officially in the next release.

Please see https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/guides/how-to-run.md for the latest version of the doc (as soon as we release a new version to nuget.org we are going to update the link that you have provided)

**Comment by ExceptionCaught** [comment]
hi @adamsitnik . thanks for the update. I was thinking of a way to run benchmark as part of the CI/CD pipeline without actually create a new console app to run it. I will wait for the new update to come through.

**Comment by adamsitnik** [comment]
> without actually create a new console app to run it

The thing that we had was working only for certain versions of .NET Core. It was a pain for us to maintain for reasons explained [here](https://github.com/dotnet/BenchmarkDotNet/pull/1572#issue-509439490). This is not supported anymore and we don't plan to add re-add it.

All you need to do is to have a console app that defines the benchmarks (or references a library that defines them) and use [BenchmarkSwitcher](https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/guides/how-to-run.md#benchmarkswitcher) to pass the `args` to it. A good example is our samples project: https://github.com/dotnet/BenchmarkDotNet/tree/master/samples/BenchmarkDotNet.Samples or the microbenchmarks used by the .NET Team: https://github.com/dotnet/performance/tree/master/src/benchmarks/micro

Having said that I am going to close this issue as there is nothing actionable for us here.

**Comment by KrisAmp** [comment]
Hi, was there any progress on this? I am looking to use BenchmarkDotNet to diagnose a performance issue in Maui Blazor, but I am not able to benchmark the code in a console application - only live in situ. Is there any way that I can decorate my methods with the benchmark attribute and have the results written to a file?

**Comment by timcassell** [comment]
@KrisAmp You can use an in process toolchain. Either InProcessEmitToolchain if the runtime supports IL emit, or InProcessNoEmitToolchain if it doesn't (I'm unfamiliar with blazor, so I'm not sure of its capabilities).
