### ISSUE TITLE
Running BenchmarkDotNet Tool within Docker container

### ISSUE THREAD

**Issue by tkhametov** [dotnet/BenchmarkDotNet#1638]
Hi there. I've tried to run BenchmarkDotNet Tool within Docker container. Here is my Dockerfile
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /src
COPY . .
ENV PATH="/root/.dotnet/tools:${PATH}"

RUN dotnet tool install BenchmarkDotNet.Tool --global --framework netcoreapp3.1

WORKDIR /src/bin/publish
```

When I enter into the container and try to run `dotnet benchmark --help` I get the following error:
```
root@77613ae18c81:/src/bin/publish# dotnet benchmark --help
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.10 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=debian.10-x64
```

Has anybody else tried to run the tool within a container? Is it a configuration issue of SDK or the tool? As you can see I didn't put any benchmarks into the container, I just try to run the tool within it.

**Comment by adamsitnik** [comment]
Hi @tkhametov 

We have removed the dotnet benchmark global tool and plan to no longer support it: https://github.com/dotnet/BenchmarkDotNet/pull/1572

Please use `dotnet run` combined with `[BenchmarkSwitcher]` as described [here](https://github.com/dotnet/BenchmarkDotNet/blob/2b1d3b509b71592e2390634645da363f79c2f0cf/docs/articles/guides/how-to-run.md#benchmarkswitcher)

I am going to close the issue now as I don't expect that you should run into any new issues with dotnet run, BDN and docker. If you do, please reopen the issue.

Thanks,
Adam
