### ISSUE TITLE
How to eliminate "Extra Premature Test Invocation"?

### ISSUE THREAD

**Issue by pha3z** [dotnet/BenchmarkDotNet#1640]
I have tried numerous attribute configurations including this one:
`[SimpleJob(RunStrategy.Monitoring, launchCount: 0, warmupCount: 0, targetCount: 1, invocationCount: 1)]`

Nothing I can do seems to prevent a benchmark method from being prematurely run once before the test invocations.
I would expect there is a way to accomplish this:

1. Execute GlobalTest method.
2. Execute MethodUnderTest method.
3. Record result.

What I'm seeing instead is this:

1. Execute GlobalTest method.
2. Execute MethodUnderTest method (apparently before the actual test run).
3. Execute MethodUnderTest method.
4. Record result.

**Comment by timcassell** [comment]
Did you try running with `RunStrategy.ColdStart`?

**Comment by adamsitnik** [comment]
@timcassell is right, `RunStrategy.ColdStart` is what you are looking for
