### ISSUE TITLE
does project performance in production get affected if keep [Benchmark] in every functions and publish it to production?

### ISSUE THREAD

**Issue by sgashua** [dotnet/BenchmarkDotNet#1648]
i only want to test benchmark during debug. but would like to disable benchmark in production if it does affect performance. is it possible?

**Comment by adamsitnik** [comment]
Hi @sgashua 

Your product code should not be using `[Benchmark]` annotations. You should rather add a new project to your solution and implement benchmarks there. When deploying to production, you should include just the product, not the benchmarks.

> i only want to test benchmark during debug

Why is that? The debug builds contain zero optimizations enabled and have a very BAD performance. When measuring performance and deploying to production you should be using `Release` builds only`.
