### ISSUE TITLE
Measure a method that spawns Tasks

### ISSUE THREAD

**Issue by goramartin** [dotnet/BenchmarkDotNet#1649]
Hello,
I was wondering If it is a good idea to measure methods containing parallel execution. The methods I want to measure are rather simple... spawn work (ThreadPool), end when all threads are finished and no IO operations.

Example:
The method Insert inserts elements stored in the provided Array into the ConcurrentDictionary.

    [Benchmark]
        public void MeasureInsert()
        {
            Parallel.Invoke(
                () => { Insert(dict, arr, 0, 2_500_000); },
                () => { Insert(dict, arr, 2_500_000, 5_000_000); },
                () => { Insert(dict, arr, 5_000_000, 7_500_000); },
                () => { Insert(dict, arr, 7_500_000, 10_000_000); }
                );
        }
`

I was not able to find anything that would state "do not do it"/"do it" except this 7 years old [issue](https://github.com/dotnet/BenchmarkDotNet/issues/5). I would be glad If I could get more insight.

**Comment by timcassell** [comment]
I tried 2 different methods for measuring threaded work: `Parallel.Invoke` and manually controlling persistent threads. The workload was simply incrementing an integer. Here are the results:

```
|             Type |       Method |     Mean |     Error |    StdDev |
|----------------- |------------- |---------:|----------:|----------:|
| ParallelSchedule | _Interlocked | 6.726 us | 0.1282 us | 0.1200 us |
| ParallelSchedule |     _Monitor | 7.117 us | 0.1078 us | 0.1008 us |
|    ThreadBarrier | _Interlocked | 1.719 us | 0.0239 us | 0.0211 us |
|    ThreadBarrier |     _Monitor | 3.427 us | 0.0636 us | 0.0624 us |
```

You can see that the overhead of scheduling the tasks dwarfs the actual workload, but the standard deviation was acceptable to be confident in the results. Using manual threads with barriers gained us much better standard deviation and lower overhead to get a more accurate assessment of the actual workload.

I think both methods are acceptable for benchmarking, depending on what you're actually trying to measure (you might also try running `Parallel.Invoke` with empty methods to see what the raw overhead is). Also, be wary of running benchmarks like this on different machines that have different core/thread counts.

<details><summary>Benchmark Code:</summary>

```cs
public class ThreadBarrier
{
    Barrier barrierInterlocked = new Barrier(6);
    Barrier barrierMonitor = new Barrier(6);
    object _locker = new object();
    volatile int counter;
    int incrementor;

    [GlobalSetup]
    public void GlobalSetup()
    {
        for (int i = 0; i < 5; ++i)
        {
            new Thread(() =>
            {
                while (counter > -1)
                {
                    barrierInterlocked.SignalAndWait();
                    Interlocked.Increment(ref incrementor);
                    Interlocked.Decrement(ref counter);
                }
            }).Start();
            new Thread(() =>
            {
                while (counter > -1)
                {
                    barrierMonitor.SignalAndWait();
                    lock (_locker)
                    {
                        ++incrementor;
                    }
                    Interlocked.Decrement(ref counter);
                }
            }).Start();
        }
    }

    [GlobalCleanup]
    public void GlobalCleanup()
    {
        counter = -1;
        barrierInterlocked.SignalAndWait();
        barrierInterlocked.Dispose();
        barrierMonitor.SignalAndWait();
        barrierMonitor.Dispose();
    }

    [Benchmark]
    public void _Interlocked()
    {
        counter = 5;
        barrierInterlocked.SignalAndWait();
        Interlocked.Increment(ref incrementor);
        while (counter > 0) { }
    }

    [Benchmark]
    public void _Monitor()
    {
        counter = 5;
        barrierMonitor.SignalAndWait();
        lock (_locker)
        {
            ++incrementor;
        }
        while (counter > 0) { }
    }
}

public class ParallelSchedule
{
    object _locker = new object();
    int incrementor;

    [Benchmark]
    public void _Interlocked()
    {
        Parallel.Invoke(
            () => Interlocked.Increment(ref incrementor),
            () => Interlocked.Increment(ref incrementor),
            () => Interlocked.Increment(ref incrementor),
            () => Interlocked.Increment(ref incrementor),
            () => Interlocked.Increment(ref incrementor),
            () => Interlocked.Increment(ref incrementor)
        );
    }

    [Benchmark]
    public void _Monitor()
    {
        Parallel.Invoke(
            () => { lock (_locker) { ++incrementor; } },
            () => { lock (_locker) { ++incrementor; } },
            () => { lock (_locker) { ++incrementor; } },
            () => { lock (_locker) { ++incrementor; } },
            () => { lock (_locker) { ++incrementor; } },
            () => { lock (_locker) { ++incrementor; } }
        );
    }
}
```

</details>

P.S. There is a thread diagnoser, but I haven't looked at it to see what information it provides.

P.P.S. This seems to only be okay for cpu-bound workloads. With another benchmark where I was doing some allocations in the workloads, the standard deviation went nuts.
