### ISSUE TITLE
Documentation - Obsolete usage of the 'With' method in place of 'WithOptions'

### ISSUE THREAD

**Issue by cedric-cf** [dotnet/BenchmarkDotNet#1655]
**Context**  

- Using last version of BenchmarkDotNet@0.12.1
- Writing a manual Config by using the documentation: 
[https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/configs/configoptions.md/#L1](https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/configs/configoptions.md/#L1)

**Problem**

The section seems to be outdated.

The `public static IConfig With(this IConfig config, ConfigOptions options);` is obsolete. 

But the documentation is mentioning it.

```cs
public class Config : ManualConfig
{
    public Config()
    {
        Options.Set(true, ConfigOptions.JoinSummary);
        Options.Set(true, ConfigOptions.DisableLogFile);

        // or
        Options.Set(true, ConfigOptions.JoinSummary | ConfigOptions.DisableLogFile);

        // or using the With() factory method:
        this.With(ConfigOptions.JoinSummary)
            .With(ConfigOptions.DisableLogFile);

    }
}
```

**Next steps**

- The first step to solve the issue would be to replace `with` by `withOptions`
- Take a look to list outdated informations
- Update the documentation to follow the current way to write `Config`.

**Comment by adamsitnik** [comment]
@cedric-cf would you like to send a PR with the fix? the source code is here: https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/configs/configoptions.md

**Comment by cedric-cf** [comment]
@adamsitnik I will take a look and I will go back to you.
