### ISSUE TITLE
.NET Core Benchmark Test Not Completing

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1656]
I have been trying to run my benchmark app for .NET Core 3.1. At first, I got an error that suggested that I add the InProcessAttribute attribute. After doing that, the benchmark app just disappears with no errors logged. I have attached the log file. 
[dotNetTips.Utility.Benchmarks.Serialization.JsonSerializerPerfTestRunner-20210224-091540.log](https://github.com/dotnet/BenchmarkDotNet/files/6038353/dotNetTips.Utility.Benchmarks.Serialization.JsonSerializerPerfTestRunner-20210224-091540.log)

Please let me know if you need anything else to track this down.

**Comment by adamsitnik** [comment]
Have you tried debugging it? https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/guides/troubleshooting.md#debugging-benchmarks

**Comment by RealDotNetDave** [comment]
I did not know about that. Will try now.

**Comment by RealDotNetDave** [comment]
Does turning this on slow down the benchmark testing?

**Comment by RealDotNetDave** [comment]
Ok, I figured it out. Adding that attribute didn't help since VS would launch and then nothing happened. Nothing in VS and benchmark app froze. I went back to a more manual method and found this issue. Thanks for your help.
