### ISSUE TITLE
--buildTimeout does not seem to work

### ISSUE THREAD

**Issue by danmoseley** [dotnet/BenchmarkDotNet#1669]
I seem to be encountering the issue @adamsitnik pointed out here https://github.com/dotnet/performance/issues/1231#issuecomment-600525198

When running the microbenchmarks script from the dotnet/performance repo on my Intel Atom machine, the build takes ~4 minutes (!), which exceeds the default 2 minutes timeout. So I modified the script to add --buildTimeout but it is ignored.

The command in this case is 
```
dotnet run --project c:\git\performance\src\benchmarks\micro\MicroBenchmarks.csproj --configuration Release --framework net5.0 --no-restore --no-build -- --filter * --packages c:\git\performance\artifacts\packages --buildTimeout 360
...
// command too more that the timeout: 120s. Killing the process tree!
...
The configured timeout 00:02:00 was reached!
...
// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
```

Per the linked issue, a possible workaround is to add `--runtimes` with a value matching `--framework`, which is a bit hacky.

**Comment by danmoseley** [comment]
Incidentally, after this point there is enormous output because BDN tries to run benchmarks, fails, emits the error messages above several times, tries to run benchmarks, etc. Should it be stopping, or is that the wrapper script invoking it again - not sure.

**Comment by adamsitnik** [comment]
@danmoseley Until we fix it, the following workaround should work in the perf repo:

```cmd
py .\scripts\benchmarks_ci.py -f net5.0 --filter * --bdn-arguments "--buildTimeout 300 --runtimes net5.0"
py .\scripts\benchmarks_ci.py -f net6.0 --filter * --bdn-arguments "--buildTimeout 300 --runtimes net6.0"
```

(`--bdn-arguments` is a way to pass any arguments from the python script to bdn)

**Comment by danmoseley** [comment]
I'll do that, thanks!

**Comment by kant2002** [comment]
Is is possible that same issue happens when using ManualConfig + CoreRtToolchainBuilder?
