### ISSUE TITLE
Detect virtual machine environment

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#167]
Some people try to run benchmark on virtual machines. It can affect benchmark results because of virtualization effects and incorrect `Stopwatch.Frequency` value. We should definitely add a line about VM in the environment info. Possibly we also should add a warning.

See also: http://stackoverflow.com/questions/498371/how-to-detect-if-my-application-is-running-in-a-virtual-machine

**Comment by adamsitnik** [comment]
I am one of these people ;) We could add it to the [EnvironmentAnalyser](https://github.com/PerfDotNet/BenchmarkDotNet/blob/e31872d1e521da27d46a919a58fb29253562e56a/BenchmarkDotNet/Analysers/EnvironmentAnalyser.cs)

**Comment by lukasz-pyrzyk** [comment]
I have an idea how to do it,. Can you assign me to this feature?

**Comment by AndreyAkinshin** [comment]
@lukasz-pyrzyk, great! I removed the up-for-grabs issue and send you an invitation to be a collaborator (I need it to put you in the assignees field). Looking forward to the PR.
