### ISSUE TITLE
Cannot override RD.xml for NativeAOT

### ISSUE THREAD

**Issue by kant2002** [dotnet/BenchmarkDotNet#1680]
I would like to be able override RD.xml for the benchmarks,
Right now I do not see how I can do that without manually modifying source code for the BenchmarkDotNet. 
Class `BenchmarkDotNet.Toolchains.CoreRt.Generator` has access only to `BuildPartition` and `ArtifactsPaths` and I cannot detect original project location. Maybe there a way to preserve original rd.xml from the project?

**Comment by kant2002** [comment]
@adamsitnik do you have an idea what would be proper fix? I really like to be able test with NativeAOT. I can implement that myself probably if I see less invasive fix.

**Comment by adamsitnik** [comment]
I was hoping that the `RdXmlFile` properties are transitive, but they are not: https://github.com/dotnet/runtime/issues/66085#issuecomment-1057055013

This should not be hard to implement, I've described how to do it here: https://github.com/dotnet/performance/issues/2338#issue-1186174019
