### ISSUE TITLE
Difference between InProcess toolchains

### ISSUE THREAD

**Issue by SnakyBeaky** [dotnet/BenchmarkDotNet#1682]
Is there a big difference between Emit and NoEmit InProcess toolchains?

https://github.com/dotnet/BenchmarkDotNet/blob/10abc4f4daa5142f0257c9d512a38afc2ab28be1/src/BenchmarkDotNet/Toolchains/InProcess.Emit/InProcessEmitToolchain.cs

https://github.com/dotnet/BenchmarkDotNet/blob/10abc4f4daa5142f0257c9d512a38afc2ab28be1/src/BenchmarkDotNet/Toolchains/InProcess.NoEmit/InProcessNoEmitToolchain.cs

I haven't found any documentation about the differences, I assume NoEmit is inteded for situations where dynamically emitting code is not possible (e.g. AOT).

Related issues:

https://github.com/dotnet/BenchmarkDotNet/pull/1093#issuecomment-470422460

https://github.com/dotnet/BenchmarkDotNet/issues/919

Thanks

**Comment by adamsitnik** [comment]
@ig-sinicyn PTAL

**Comment by ig-sinicyn** [comment]
@SnakyBeaky 

There are two versions of in-process toolchains. The first one, `InProcessEmitToolchain` is preferred as it emits same IL code the default toolchain do. We have a test that should fail if there are any differences in the emitted code. As far as I know there were no changes in the emit logic so far, so it can be considered stable:)

Second one, `InProcessNoEmitToolchain` is a fallback implementation that should be used with runtimes that do not support dynamic codejen (AOT, net native etc). This version is much less effective and may produce inaccurate results for nanosecond benchmarks.
