### ISSUE TITLE
Can't generate a flame graph using BenchmarkDotNet.Diagnostics.Windows

### ISSUE THREAD

**Issue by robertpi** [dotnet/BenchmarkDotNet#1683]
I've tried following the instructions here to generate a flame graph from my benchmark:
https://benchmarkdotnet.org/articles/features/etwprofiler.html

But what ever I try, it seems no stack trace information is included in the output file.

My CPU Stacks window always looks like this:
<img width="483" alt="2021-04-01 10_32_34-CPU Stacks(0 metric) Benchmarks Trace AspNetCore AspNetCoreBenchmark AspNetCoreB" src="https://user-images.githubusercontent.com/51381/113266497-a2af0300-92d5-11eb-8ee4-1c37e9b8e5cb.png">

I noticed there's no "Any Stacks" node, as I would typically see when using `dotnet-trace`:
<img width="107" alt="2021-04-01 10_36_27-Window" src="https://user-images.githubusercontent.com/51381/113267089-3ed90a00-92d6-11eb-9122-1d12b5a420bf.png">

I noticed that by default collecting stack information seems to be disabled, so I tried creating my own code config with it enabled but it didn't make any difference (although oddly the output file does get much larger). This is the config I tried:

```
        private static EtwProfilerConfig CreateDefaultConfig()
        {
            var kernelKeywords = KernelTraceEventParser.Keywords.ImageLoad | KernelTraceEventParser.Keywords.Profile;

            var providers = new (Guid providerGuid, TraceEventLevel providerLevel, ulong keywords, TraceEventProviderOptions options)[]
            {
                // following values come from xunit-performance, were selected by the .NET Runtime Team
                (ClrTraceEventParser.ProviderGuid, TraceEventLevel.Verbose,
                    (ulong) (ClrTraceEventParser.Keywords.Exception
                             | ClrTraceEventParser.Keywords.GC
                             | ClrTraceEventParser.Keywords.Jit
                             | ClrTraceEventParser.Keywords.JitTracing // for the inlining events
                             | ClrTraceEventParser.Keywords.Loader
                             | ClrTraceEventParser.Keywords.NGen
                             | ClrTraceEventParser.Keywords.Threading // extra
                             | ClrTraceEventParser.Keywords.ThreadTransfer), // extra
                    new TraceEventProviderOptions { StacksEnabled = true }),
                (SampleProfilerTraceEventParser.ProviderGuid, TraceEventLevel.Verbose, 0x0000F00000000000, new TraceEventProviderOptions { StacksEnabled = true }),
                (new Guid("0866B2B8-5CEF-5DB9-2612-0C0FFD814A44"), TraceEventLevel.Informational, MatchAnyKeywords, null)
            };

            return new EtwProfilerConfig(
                performExtraBenchmarksRun: false,
                kernelKeywords: kernelKeywords,
                providers: providers);
        }
```

I can use dotnet-trace to collect the information from the benchmark, but it's trick to get it to connect to each new benchmark, so using BenchmarkDotNet.Diagnostics.Windows would be more convenient.

**Comment by adamsitnik** [comment]
Hi @robertpi 

What is the output of the `Log` (button is in the bottom right corner) when you open the trace file with PerfView?

**Comment by robertpi** [comment]
Attached:
[PerfViewLogFile.txt](https://github.com/dotnet/BenchmarkDotNet/files/6242310/PerfViewLogFile.txt)

**Comment by adamsitnik** [comment]
> Total CPU = 0 samples

This looks fishy.

Could you try to use PerfView to collect a simple trace file and see if it contains any CPU samples?

**Comment by robertpi** [comment]
[PerfViewLogFile.txt](https://github.com/dotnet/BenchmarkDotNet/files/6242477/PerfViewLogFile.txt)

This is the log file collected from the same benchmark using: 

`dotnet-trace collect --providers Microsoft-DotNETCore-SampleProfiler:0x0000F00000000000:4,Microsoft-Windows-DotNETRuntime:0x00000014C14FCCBD:4,BenchmarkDotNet.EngineEventSource -p 18876`

There is data under the "Any Stacks" node using this method.

**Comment by adamsitnik** [comment]
`dotnet-trace` uses a different mechanism of CPU samples collection (EventPipe) than PerfView (ETW). I want you to use PerfView (Collect -> Collect) to see if it's a BDN, or ETW bug. A very recent Windows update has introduced an ETW bug and we just need to verify if you are not hitting the Windows bug.

**Comment by robertpi** [comment]
Oh, right, didn't realize the collect method was different. Collect -> Collect from PerfView gives the same results as Etw Profiler included in BenchmarkDotnet. Here's the log:
[PerfViewLogFile.txt](https://github.com/dotnet/BenchmarkDotNet/files/6242739/PerfViewLogFile.txt)

This is my Windows version details:
```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎13/‎12/‎2020
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by robertpi** [comment]
I ended up working round this by adding a new IDiagnostic that launches dotnet-trace in another process. It got me the data I wanted. Would you like a PR with this?

**Comment by adamsitnik** [comment]
We already have a diagnoser that uses EventPipe (it does exactly the same thing dotnet trace does): https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Diagnosers/EventPipeProfiler.cs

But we have not published it to nuget.org yet.

If you want to give it a try, please use our CI NuGet package feed:

```xml
<packageSources>
  <add key="bdn-ci" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

https://benchmarkdotnet.org/articles/guides/nuget.html

**Comment by robertpi** [comment]
Oh right, yes that does look easier. I'll give it ago.

Anything else we need to do to confirm this is the Windows ETW bug? Do you have a link with more info about this?

Otherwise, for me we can consider this closed.

**Comment by adamsitnik** [comment]
@robertpi From the public links all I have is https://twitter.com/austinkinross/status/1372328600167358466

Since this is not a BDN issue, I am going to close it.
