### ISSUE TITLE
Getting System.FormatException when passing certain string as params.

### ISSUE THREAD

**Issue by N0D4N** [dotnet/BenchmarkDotNet#1684]
Passing `\\e\"` with `ParamsAttribute` to string field causes `System.FormatException: Input string was not in a correct format.` on `// BeforeAnythingElse` stage.
However passing `\\\"` works just fine so my guess is - e placed between `\\` and `\"` somehow changes behavior.  
Environment info: 
```
BenchmarkDotNet=v0.12.1, OS=arch 
Intel Core i3-7130U CPU 2.70GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=5.0.104
  [Host]   : .NET Core 5.0.4 (CoreCLR 5.0.421.16601, CoreFX 5.0.421.16601), X64 RyuJIT
  ShortRun : .NET Core 5.0.4 (CoreCLR 5.0.421.16601, CoreFX 5.0.421.16601), X64 RyuJIT
```

Exception stack trace:
```cs
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in /home/nodan/Development/BenchmarkDotNetBug/BenchmarkDotNetBug/bin/Release/net5.0/42637cd8-8147-4be2-a4f5-ceb99df4fb75/42637cd8-8147-4be2-a4f5-ceb99df4fb75.notcs:line 42
```  

Minimal reproducible program:
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Engines;
using BenchmarkDotNet.Running;

namespace BenchmarkDotNetBug
{
	public class Program
	{
		public static void Main(string[] args) => BenchmarkRunner.Run<Benchmark>();
	}
	
	[ShortRunJob]
	public class Benchmark
	{
		private readonly Consumer _consumer = new();

		[Params("\\e\"", "\\\"")]
		public string Data;
		
		[Benchmark]
		public void Run() => this._consumer.Consume(this.Data);
	}
}
```
Full logs: [BenchmarkDotNetBug.Benchmark-20210401-191632.log](https://github.com/dotnet/BenchmarkDotNet/files/6244946/BenchmarkDotNetBug.Benchmark-20210401-191632.log)

**Comment by YegorStepanov** [comment]
Fixed in #2136

**Comment by N0D4N** [comment]
Strange but i dont seem to get this exception even on v0.13.2, but I guess its fine anyway. Closing this.

**Comment by YegorStepanov** [comment]
Hmm, Yesterday I checked your example before and after PR, it generated your exception. Today I cannot reproduce it (in v0.13.2 too) :)

Interestingly, `"\\"` and `"\""` were already escaped (check the PR), they should have worked.

---

```C#
System.FormatException: Input string was not in a correct format.
```

The `.notcs` file was generated correctly, but it could not read some control symbols (like `\0`, I can reproduce it in v0.13.2):

https://github.com/dotnet/BenchmarkDotNet/blob/1f5637c784ad9887a2d5abdba54d1337655281b1/src/BenchmarkDotNet/Templates/BenchmarkProgram.txt#L45-L47

**Comment by YegorStepanov** [comment]
@adamsitnik I forgot to attach a PR to this issue. Add this issue to `v0.13.3` milestone please.
