### ISSUE TITLE
"Unable to find <Project>" when running on another (linux) machine

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/BenchmarkDotNet#1688]
I created a benchmark console app on Windows, and want to run it on linux.

I published the project, copied it to the linux machine and get the above error. Docs never mention that I actually need .csproj and .sln files. What do I need to do to make it work? Copy the .csproj files to linux? What else?

**Comment by adamsitnik** [comment]
By default BDN generates some boilerplate code and builds it with `dotnet cli`. This is why you need the source code and .NET SDK to be present.

You can run all the benchmarks in the same process by using [InProcessToolchain](https://benchmarkdotnet.org/articles/configs/toolchains.html#sample-introinprocess) and then you don't need that, however, if your benchmarks have side effects, then the results won't be 100% reliable.

> Docs never mention that I actually need .csproj and .sln files.

@alex-jitbit  Would you like to send a PR with doc improvement?
