### ISSUE TITLE
Length cannot be less than zero

### ISSUE THREAD

**Issue by verdie-g** [dotnet/BenchmarkDotNet#1694]
Hello, with this benchmark
```csharp
public class Test
{
    [Benchmark]
    public Dictionary<string, int>.Enumerator ConcreteGetEnumerator() => default;
}
```

I get a
```
// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 1 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// ***** Done, took 00:00:00 (0.07 sec)   *****
// Found 1 benchmarks:
//   Test.ConcreteGetEnumerator: DefaultJob

// Generate Exception: Length cannot be less than zero. (Parameter 'length')
```

BenchmarkDotNet: 0.12.1
Target Framework: .NET Core 2.1 (also tested with 3.1)

If you can't reproduce on your side I'll dig deeper.

**Comment by adamsitnik** [comment]
I've made this issue up-for-grabs.

The best way to approach it would be the following:

1. Add provided repro to the `BenchmarkDotNetSamples` project. Example:

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Collections.Generic;

namespace BenchmarkDotNet.Samples
{
    public class Program
    {
        public static void Main(string[] args) => BenchmarkRunner.Run<Test>();
    }

    public class Test
    {
        [Benchmark]
        public Dictionary<string, int>.Enumerator ConcreteGetEnumerator() => default;
    }
}
```

2.  Right click on the project and mark is as startup project:

![image](https://user-images.githubusercontent.com/6011991/194056140-609d4963-02a8-4319-b849-8e46eda1ffbf.png)

3. Hit `Cltr+Alt+E` and ask VS to stop on managed exception by clicking:

![image](https://user-images.githubusercontent.com/6011991/194056581-d6269e72-7209-4458-8a38-2be44c19d9e4.png)

4. Hit F5 and let VS stop on the exception hit by @verdie-g 

![image](https://user-images.githubusercontent.com/6011991/194056745-524f1713-5527-437b-bd83-a6e44da3401c.png)

5. Add a unit test
6. Provide a fix

**Comment by Dartexxy** [comment]
I would like to work on this issue

**Comment by ramkumar-g** [comment]
@adamsitnik - your instructions were very helpful in debugging this issue. Thank you.

I have found that the substring is receiving an invalid length due to IndexOf('`') check in function GetCorrectCSharpTypeName
I wanted to confirm if handling IndexOf here is the right way to resolve this.

![image](https://user-images.githubusercontent.com/4058503/194290121-f7363344-a0e1-4a12-8de1-97d4c22aa419.png)

**Comment by adamsitnik** [comment]
> I wanted to confirm if handling IndexOf here is the right way to resolve this.

I am sorry but I don't remember the exact details behind this implementation. You can take a look at the existing unit tests that cover this code, debug them and somehow figure out why this particular case is special and does not work as expected. 

https://github.com/dotnet/BenchmarkDotNet/blob/c3fb7b9724a62048d27ef5bcaec616117d68b934/tests/BenchmarkDotNet.Tests/ReflectionTests.cs#L15-L32

**Comment by YegorStepanov** [comment]
The fix is not so easy. I'd recommend considering an easier issue for the first contribution.

**Comment by YegorStepanov** [comment]
Sorry for grabbing the issue. 

Indeed, it was easy (I forgot to add the [Benchmark] attribute so I thought a lot of things were broken and they are coupled with the inner project generation)

@ramkumar-g I wanted to add you as a co-author but I don't know your `no-reply-github-email`.

**Comment by ramkumar-g** [comment]
@YegorStepanov - not a problem. will pick up something else. thanks!

**Comment by postmeback** [comment]
If the requested PR serves the purpose, then please merge and close it.
