### ISSUE TITLE
Obtain an average over an ArgumentSource

### ISSUE THREAD

**Issue by lipchev** [dotnet/BenchmarkDotNet#1704]
Related to #258

I'm also trying to obtain a statistic over a range of inputs. I'm currently doing a for-loop iteration of the input array- having previously defined it's size as the `OperationsPerInvoke` (also struggling with the problem of it having to be a constant).

I would love to be able to supply the input array as an `[ArgumentSource(nameOf(StringInputs), joined = true)]` which would be equivalent to the operations-in-a-loop approach (having subtracted the loop overhead).

This would also have the added benefit of returning the complete statistics, instead of just the _average_. 

Here is an example of the old version

```
        [Benchmark(OperationsPerInvoke = NbIterations, Baseline = true)]
        [ArgumentsSource(nameof(ValidStrings))]
        public double Parse_Double(string[] textValues)
        {
            var result = 0.0;

            for (var i = 0; i < NbIterations; i++)
            {
                result += double.Parse(textValues[i]);
            }

            return result;
        }
```

And here is what I would love to have instead:

```
        [Benchmark(Baseline = true)]
        [ArgumentsSource(nameof(ValidStrings), Joined = true)]
        public double Parse_Double(string textValue)
        {
            return double.Parse(textValue);
        }
```

Also note the added overhead of the += which would not be the same if I were instead testing something like `Decimal`.

**Comment by adamsitnik** [comment]
Hi @lipchev 

I am not sure if I understand. What exactly `Joined = true` would do for the following benchmark?

```cs
[Benchmark(Baseline = true)]
[ArgumentsSource(nameof(ValidStrings), Joined = true)]
public double Parse_Double(string textValue)
{
    return double.Parse(textValue);
}
```

**Comment by lipchev** [comment]
Hi @adamsitnik ,

It would execute the benchmark for all inputs of the argument source, but instead of producing N individual results (which for higher values of N would be very hard to read through) - would generate a single result that is the equivalent to running the benchmark as a single job, having an array as input parameter (just like the first example).

Imagine that (for the purposes of this example) we wanted to have an estimate of the time it takes to parse a string of length between 1 and 10, assuming that the result for length 1 is significantly different from the one of size 10. 

I could of course, handle the averaging manually, create pretty plots- investigate linearity etc. But after having done all that once- I want to create a non-regression benchmark, that gives me a single (hopefully the same) average as that which I got from the 'manual' analysis.

**Comment by timcassell** [comment]
If your input is static, you could do this:

```cs
BenchmarkDotNet.Engines.Consumer consumer = new BenchmarkDotNet.Engines.Consumer();

[Benchmark(OperationsPerInvoke = 3)]
public void Parse_Doubles()
{
    consumer.Consume(float.Parse("1"));
    consumer.Consume(float.Parse("10"));
    consumer.Consume(float.Parse("100"));
}
```

**Comment by lipchev** [comment]
> 
> 
> If your input is static, you could do this:
> 
> ```cs
> BenchmarkDotNet.Engines.Consumer consumer = new BenchmarkDotNet.Engines.Consumer();
> 
> [Benchmark(OperationsPerInvoke = 3)]
> public void Parse_Doubles()
> {
>     consumer.Consume(double.Parse("1"));
>     consumer.Consume(double.Parse("10"));
>     consumer.Consume(double.Parse("100"));
> }
> ```
> 
> [Edit] Ah woops, re-read your OP saying it's not constant.

BTW, what would be the correct approach for _consuming_ a struct?

**Comment by lipchev** [comment]
Lol, somehow along the way I went from thinking that it's 'only for IEnumerable' to 'only for primitives and classes'. Right, what else am I missing 😃 ?

**Comment by timcassell** [comment]
I don't think this is worth pursuing. #258 should have the solution.
