### ISSUE TITLE
Benchmark several TFMs of a library on the same runtime

### ISSUE THREAD

**Issue by ltrzesniewski** [dotnet/BenchmarkDotNet#1706]
Let's say I have a `Library` project that targets `net5.0` and `netstandard2.0`, and a `Benchmarks` project that references it.

I could use the following configuration to benchmark the two TFMs:

```C#
[SimpleJob(RuntimeMoniker.Net48)]
[SimpleJob(RuntimeMoniker.NetCoreApp50)]
```

But the underlying runtime wouldn't be the same, and this can have a large impact on the results.

In my understanding, there's currently no _straightforward_ way to benchmark the two TFMs on the same .NET 5 runtime.

---

Here's a solution I found:

```C#
internal class NetCoreAndStandardConfig : ManualConfig
{
    public NetCoreAndStandardConfig()
    {
        AddJob(
            Job.Default.WithId(".NET Core"),
            Job.Default.WithId(".NET Standard").WithArguments(new[] { new MsBuildArgument("/p:ForceNetStandard=true") })
        );
    }
}
```

But this requires adding the following conditional property to the `Library` project:

```XML
<TargetFramework Condition="'$(ForceNetStandard)' == 'true'">netstandard2.0</TargetFramework>
```

While it works, I don't like the fact that a change in the `Library` project is necessary. I'm wondering if BDN could provide an easier way to achieve this.

---

I initially thought that something like `SetTargetFramework="TargetFramework=netstandard2.0"` could be added to the `ProjectReference` item in the generated csproj file, but while this ends up referencing the `netstandard2.0` version of the `Benchmarks` project, the resolved reference to `Library` will still target `net5.0`. This can be solved by adding another `ProjectReference` with `SetTargetFramework` to the `Library` project, but I'm not sure BDN should do this.

Also, while setting the TFM of the generated project to `netstandard2.0` will end up referencing the correct assemblies, BDN will complain about the lack of an exe file.

So I'm not sure what's the best course of action here. While I think that having this feature would be very useful, unless I missed something it looks like implementing it won't be easy, and the workaround is not very straightforward.

**Comment by adamsitnik** [comment]
Hi @ltrzesniewski 

.NET Standard is an abstraction. To run a console app, you need to specify the runtime, which provides the implementation of the abstraction. So there is no way to test .NET Standard performance, you can only test given runtime performance.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net4.8;net5.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
</Project>

```

```cs
using System;

namespace tfms
{
    class Program
    {
        static void Main(string[] args)
        {
#if NETSTANDARD2_0            
            Console.WriteLine("NETSTANDARD2_0");
#elif NETFRAMEWORK
            Console.WriteLine("NET48");
#elif NETCOREAPP
            Console.WriteLine("NET50");
#endif
        }
    }
}
```

```log
PS C:\Projects\repros\tfms> dotnet run -c Release -f netstandard2.0
Unable to run your project.
Ensure you have a runnable project type and ensure 'dotnet run' supports this project.
A runnable project should target a runnable TFM (for instance, net5.0) and have OutputType 'Exe'.
The current OutputType is 'Exe'.
PS C:\Projects\repros\tfms> dotnet run -c Release -f net4.8
NET48
PS C:\Projects\repros\tfms> dotnet run -c Release -f net5.0
NET50
PS C:\Projects\repros\tfms>
```

**Comment by DaveSkender** [comment]
I may have a similar use case that I'm trying to resolve regarding multi-targeting.  Suppose:

```xml
<TargetFrameworks>net6.0;netstandard2.1;</TargetFrameworks>
```

And it produces two DLLs, one for .NET 6.0 and one for .NET Standard 2.1

![image](https://user-images.githubusercontent.com/8432125/144483562-88914316-afb4-4fdc-be51-7d1c1c500013.png)

And now I want to know how they comparatively perform with BenchmarkDotNet, with these attributes?

![image](https://user-images.githubusercontent.com/8432125/144483861-115da0e7-e980-4847-bfe6-c1f8a4472b3f.png)

... I may be confusing the purpose of `RuntimeMoniker`, but I also don't see any other route to do this without creating multiple redundant Benchmark projects.

**Comment by ltrzesniewski** [comment]
Well, we have the same use case actually 😄 

Here's my solution, for reference: [the benchmark config](https://github.com/ltrzesniewski/pcre-net/blob/2d4c01f625e49ef0d6d9ad7f27f5d1ff236c3340/src/PCRE.NET.Benchmarks/Configs.cs#L7-L16), and [the library project settings](https://github.com/ltrzesniewski/pcre-net/blob/2d4c01f625e49ef0d6d9ad7f27f5d1ff236c3340/src/PCRE.NET/PCRE.NET.csproj#L4-L6).

I suppose you could replace `$(ForceNetStandard)` with something like `$(BenchmarkTargetFramework)` to make it more generic if you need more than two target frameworks.

**Comment by timcassell** [comment]
It looks like we can support this by setting the `SetTargetFramework` property of the imported project.

```xml
<ProjectReference Include="$CSPROJPATH$">
    <SetTargetFramework>TargetFramework=netstandard2.0</SetTargetFramework>
</ProjectReference>
```

Of course, it would still require you to include the framework in your csproj.

**Comment by adamsitnik** [comment]
I think this feature is too niche to add it to BDN and make our config even more complex.

We can just document that the users need to use the right `MsBuildArgument` to get it working:

```cs
.WithArguments(new[] { new MsBuildArgument("/p:ForceNetStandard=true") })
```

**Comment by jzabroski** [comment]
Hey! It looks like this feature is now indirectly supported! See https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#multi-targeting-with-duplicate-frameworks

> Benchmarking different versions of a package
XML
> ```xml
> <Project Sdk="Microsoft.NET.Sdk">
>   <PropertyGroup>
>     <TargetFrameworks>benchmark7.0;benchmark8.0</TargetFrameworks>
>  </PropertyGroup>
> 
>   
> 
>   <ItemGroup>
>     <PackageReference Include="BenchmarkDotNet" Version="0.13.9" />
>     <PackageReference Include="Contoso.FastLibrary" Version="7.0" Condition="'$(TargetFramework)' == 'benchmark7.0' "/>
>     <PackageReference Include="Contoso.FastLibrary" Version="8.0" Condition="'$(TargetFramework)' == 'benchmark8.0' "/>
>   </ItemGroup>
> </Project>
> ```


The two aliases resolve to the same actual .NET runtime, but because $(TargetFramework) takes the alias value during the build, you can use MSBuild conditions to pull in different versions of the same package per alias. The result is two separate build outputs — one linking against v7.0 of the library, one against v8.0 — both running on the same runtime.
