### ISSUE TITLE
After how many iterations does a performance test stop?

### ISSUE THREAD

**Issue by naeemakram** [dotnet/BenchmarkDotNet#1708]
Once I've started a performance test, when will it stop? Will it calculate how many times to run automatically? 
Been looking at the screen for about half an hour but the thing keeps running. Am I missing something? 
I've followed the example given in the docs section of this repo and I've also followed another post about creating benchmarks. 
I am combining BenchmarkDotNet with Selenium to open multiple instances of a website and refresh it again and again to regenerate the security token of the website.

**Comment by adamsitnik** [comment]
Hi @naeemakram 

BenchmarkDotNet has a heuristic that decides when to stop:

https://github.com/dotnet/BenchmarkDotNet/blob/f4d99ab7b81cccf9322fe6ae084572d8eeb9cade/src/BenchmarkDotNet/Engines/EngineGeneralStage.cs#L53-L72

It will run no more than 100 iteraitons.

You can configure max iteration count by either using attributes, fluent API or command line args:

```cs
[MaxIterationCount(10)]
public class Benchmarks

// or
job = job.WithMaxIterationCount(10)

// or

--maxIterationCount 10
```

More: https://benchmarkdotnet.org/articles/guides/how-it-works.html
