### ISSUE TITLE
BenchmarkSwitcher executes all benchmarks that share a base class

### ISSUE THREAD

**Issue by aalmada** [dotnet/BenchmarkDotNet#1709]
I have a large set of benchmarks that have common initialization. To avoid having duplicate code I created a base class with the BenchmarkDotNet initialization. Here's a small example that replicates my scenario:

``` csharp
using System.Linq;
using BenchmarkDotNet.Attributes;

namespace TestBenchmarkDotNet
{
    public abstract class TestsBase
    {
        protected int[] source;
        
        [Params(10)]
        public int Count { get; set; }
        
        [GlobalSetup]
        public void GlobalSetup()
            => source = Enumerable.Range(0, Count).ToArray();
    }
}
```

In each test I simply have to inherit from this class. I have many like these:

``` csharp
using System.Linq;
using BenchmarkDotNet.Attributes;

namespace TestBenchmarkDotNet
{
    public class Test01 : TestsBase
    {
        [Benchmark(Baseline = true)]
        public int BaselineTest()
            => source.Sum();

        [Benchmark]
        public int AnotherTest()
            => source.Sum();
    }
}
```

In `Program.cs`, I setup a `BenchmarkSwitcher`:

``` csharp
using BenchmarkDotNet.Running;

namespace TestBenchmarkDotNet
{
    class Program
    {
        static void Main(string[] args)
        {
            BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);
        }
    }
}
```

My issue is that, when I execute and choose an option, it performs all benchmarks that derive from `TestsBase`. Not just the one I chose. Is this an expected behavior?

To easily replicate, here's a minimal example in a repository: https://github.com/aalmada/TestBenchmarkDotNet

**Comment by adamsitnik** [comment]
Hi @aalmada 

What filter are you using?

The following one should run only the benchmarks from `Test01` class:

```cmd
--filter *Test01*
```

**Comment by aalmada** [comment]
I'm typing the number given in the list of benchmarks.
I now tried `--filter *Test01*` and it doesn't run the benchmarks. It simply shows again the list of benchmarks.

**Comment by adamsitnik** [comment]
> It simply shows again the list of benchmarks.

Which BDN version are you using? What command exactly do you run from the command line?

**Comment by aalmada** [comment]
> Which BDN version are you using? What command exactly do you run from the command line?
Ups! So sorry, I forgot to mention that. 🙄 It's BDN 0.12.1.1538

From the command line, I'm simply calling the executable. I then type `1` and `Enter`.

I created a repository with a very simple example that reproduces the behavior: https://github.com/aalmada/TestBenchmarkDotNet

**Comment by adamsitnik** [comment]
> From the command line, I'm simply calling the executable. I then type 1 and Enter

That explains everything. We have recently invested a lot in `--filter` and this is the recommended way of filtering the benchmarks. It needs to be passed to the exe from the command line:

```cmd
dotnet run -c Release --filter *Test01*
pathTo.exe --filter *Test01*
```

Does filter works as expected when you use it?

**Comment by aalmada** [comment]
The filter does work when invoked from the command line.

**Comment by aalmada** [comment]
I now upgraded to `0.13.0` and it has the exact same behaviors

**Comment by YegorStepanov** [comment]
I've sent a PR.


It doesn't relative to base class.

### Problem

```
Available Benchmarks:
  #0 Test01
  #1 Test02
```
if you write `0` it matches:
* Test01 (by benchmark class index)
* Test01 (class name contains `0`)
* Test02 (class name contains `0`)
