### ISSUE TITLE
System.NotSupportedException: Unknown Acknowledgment: ﻿Acknowledgment when running in a github action

### ISSUE THREAD

**Issue by Doraku** [dotnet/BenchmarkDotNet#1713]
Hello there, I am trying to make the github action ci automatically generate benchmarks for every commit so I don't have to manually run them and edit the results. The benchmarks run fine on my computer but nothing happen in the github action.
I just switch to the version 0.13.0 and this is what is happening:
```
// **************************
// Benchmark: CreateEntityWithNoComponent.DefaultEcs: Job-FEFVFA(InvocationCount=1, UnrollFactor=1) [EntityCount=100000]
// *** Execute ***
// Launch: 1 / 1
// Execute: D:\a\Ecs.CSharp.Benchmark\Ecs.CSharp.Benchmark\source\Ecs.CSharp.Benchmark\bin\Release\net48\f559460e-bd0d-41d7-ba8e-934f8dcf89e6.exe --benchmarkName "Ecs.CSharp.Benchmark.CreateEntityWithNoComponent.DefaultEcs(EntityCount: 100000)" --job "InvocationCount=1, UnrollFactor=1" --benchmarkId 0 in 
// BeforeAnythingElse

Unhandled Exception: System.NotSupportedException: Unknown Acknowledgment: ﻿Acknowledgment
   at BenchmarkDotNet.Engines.ConsoleHost.SendSignal(HostSignal hostSignal)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.Main(String[] args)
ExitCode != 0 and no results reported
// Benchmark Process 4364 has exited with code -532462766
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!
```
Before when running version 0.12.1 I had this:
```
// **************************
// Benchmark: CreateEntityWithNoComponent.DefaultEcs: Job-FEFVFA(InvocationCount=1, UnrollFactor=1) [EntityCount=100000]
// *** Execute ***
// Launch: 1 / 1
// Execute: D:\a\Ecs.CSharp.Benchmark\Ecs.CSharp.Benchmark\source\Ecs.CSharp.Benchmark\bin\Release\net48\e07159b2-cf89-4f75-a9e5-5e054c0dac54.exe --benchmarkName "Ecs.CSharp.Benchmark.CreateEntityWithNoComponent.DefaultEcs(EntityCount: 100000)" --job "InvocationCount=1, UnrollFactor=1" --benchmarkId 0 in 
// BeforeAnythingElse
ExitCode != 0
// Benchmark Process 2188 has exited with code -532462766
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!
```

This is the relevant machine information at the end of a run
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.17763.1935 (1809/October2018Update/Redstone5), VM=Hyper-V
Intel Xeon Platinum 8171M CPU 2.60GHz, 1 CPU, 2 logical and 2 physical cores
  [Host] : .NET Framework 4.8 (4.8.4341.0), X64 RyuJIT
```

This is the [CI run](https://github.com/Doraku/Ecs.CSharp.Benchmark/runs/2634101389).

I tried calling the exe directly by the CI and using `dotnet run --project ... -c Release` but same result as above. Am I doing something wrong? Anyway thanks for this beautiful tool :)

**Comment by adamsitnik** [comment]
Hello @Doraku 

It looks like #1487 which in theory got solved by #1491 (cc @lovettchris )

Is there any chance that you could try some of the following workarounds:

* set current culture to `en-US` before calling `BenchmarkRunner` or `BenchmarkSwitcher`
* set the default encoding to `Utf8`, also before calling `BenchmarkRunner` or `BenchmarkSwitcher`

**Comment by Doraku** [comment]
Just tried quickly to set the current culture, no change.
```
CultureInfo cultureInfo = new("en-US");

CultureInfo.CurrentCulture = cultureInfo;
CultureInfo.CurrentUICulture = cultureInfo;
CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;
```
I will try to change the default encoding and report back.

**Comment by Doraku** [comment]
I may be missing something obvious but how do you even change the default encoding? Is it at the github action level? my benchmark.exe level? BenchmarkRunner configuration level? I can't find anything :|

**Comment by adamsitnik** [comment]
@Doraku I was able to repro it, have sent a fix: #1735

**Comment by Doraku** [comment]
Thanks that's great! I patiently await a version with this fix :)

**Comment by adamsitnik** [comment]
@Doraku I am not sure when we are going to publish `0.13.1`, so until then you can use `0.13.0.1560` version from our CI NuGet feed:

```xml
<packageSources>
  <add key="bdn-ci" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
````
