### ISSUE TITLE
How to measure a whole application performance over time?

### ISSUE THREAD

**Issue by p-bojkowski** [dotnet/BenchmarkDotNet#1717]
I need to measure a whole application over (dev) time.
Is the best place to measure the whole app - the unit tests area?
The unit tests area is the only place where the method signature (use cases) not changed only the body.

How would you measure a whole app over time to say how the performance has changed (+/-) over time.

**Comment by adamsitnik** [comment]
You would need to:

1. Identify the most important scenarios for your app
2. Implement benchmarks that cover them
3. Run the benchmarks on exactly same hardware over time
4. Store the results in some database
5. Compare the results and search for regressions.

Currently BDN does not provide any built-in way to do that (#54)
