### ISSUE TITLE
Build on Linux without mono installed

### ISSUE THREAD

**Issue by kant2002** [dotnet/BenchmarkDotNet#1723]
Is there any hard reqiurement on using mono for building on Linux?
I see that mono used for running nuget to install Cake and for running DocFx? 
Can first be replaced with installing cake as local tool?
Second requirement still required until DocFx would work without mono, but at least that allow build executables, if local patch is needed.

**Comment by adamsitnik** [comment]
Hi @kant2002 

It depends on what is your goal.

If you just want to build BenchmarkDotNet from source then all you need is .NET 5 SDK:

```cmd
git clone https://github.com/dotnet/BenchmarkDotNet.git bdn
cd bdn
dotnet build -c Release BenchmarkDotNet.sln
```

Cake and other things are used by our CI and we don't plan to change that.

**Comment by kant2002** [comment]
Thanks. Probably I overthink this one. If I could use just using `dotnet build` for local changes that's fine for me.
