### ISSUE TITLE
BDN needs to disable the self-contained executable check for WASM

### ISSUE THREAD

**Issue by kg** [dotnet/BenchmarkDotNet#1728]
As of a week or two ago, if you use BDN against latest dotnet/runtime, it fails because of the self-contained executable check. Passing ```/p:ValidateExecutableReferencesMatchSelfContained=false``` when building BDN's generated projects works, so BDN probably should either manually pass this when building for wasm, or embed it in the csproj files.

```
/home/kate/Projects/dotnet-runtime-wasm/.dotnet/sdk/6.0.100-preview.4.21255.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1075,5): error NETSDK1150: The referenced project '/home/kate/Projects/performance/src/benchmarks/micro/MicroBenchmarks.csproj' is a non self-contained executable.  A non self-contained executable cannot be referenced by a self-contained executable. [/home/kate/Projects/performance/artifacts/bin/MicroBenchmarks/Release/net6.0/770e52c9-3aed-4b7f-ae13-f921d1299cee/BenchmarkDotNet.Autogenerated.csproj]
Build FAILED.
```

**Comment by adamsitnik** [comment]
@naricc I can see that we are already doing that for Mono AOT: #1707, should we do that for WASM as well?

**Comment by naricc** [comment]
Yes, I was discussing this with @kg; this is now showing up on wasm as well. So we need to enable the same option there. 

Is there any reason not to do `<ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>` on everything? Or should we just do it on an as needed basis for different architectures/confiugrations?
