### ISSUE TITLE
runtime knobs broken link

### ISSUE THREAD

**Issue by juniormayhe** [dotnet/BenchmarkDotNet#1737]
hi guys, hope you are all safe.

On this documentation section https://benchmarkdotnet.org/articles/guides/customizing-runtime.html#sample-introenvvars we have a broken link at runtime knobs:

...how different [runtime knobs](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md) affect.. 

Is it possible for you to update the page to point to an existing link? 🙏

**Comment by YegorStepanov** [comment]
The file has been [deleted](https://github.com/dotnet/runtime/commit/fa25aeaca87d9d37324cd27d7341b6c201179f06?short_path=59f769a#diff-59f769ae0c5cbe17b65d02e24e64534fc46604eb19daea759887ab8d6744b818) and replaced with [the docs](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/).

**Comment by adamsitnik** [comment]
@YegorStepanov would you like to send a PR that updates the docs?
