### ISSUE TITLE
Add .NET Core support for Diagnostics package

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#175]
Currently we are blocked by the fact that [TraceEvent is not available on CoreCLR](https://github.com/dotnet/corefx/issues/4864). As soon as it gets fixed by Microsoft I will implement that.

**Comment by mattwarren** [comment]
More fundamentally they need to port ETW events (or something equivalent) to other OSes first. See [this doc for a discussion](https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/cross-platform-performance-and-eventing.md) of where they are headed.

**Comment by adamsitnik** [comment]
TraceEvent has been ported to [.NET Core](https://github.com/Microsoft/perfview/issues/165).

I am waiting for the NuGet package now.

**Comment by brianrob** [comment]
This should be unblocked now.  This package supports .NET Core: https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.TraceEvent/2.0.4

**Comment by adamsitnik** [comment]
Fixed with [this](https://github.com/dotnet/BenchmarkDotNet/commit/26070478849da25012586737357126d9996e53ad) commit, but needs to wait for v0.11.0 release (it will be one big release with some breaking changes)
