### ISSUE TITLE
[wasm] Publish target circular dependency

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/BenchmarkDotNet#1754]
I see this error when building wasm microbenchmarks without aot locally:

    BenchmarkDotNet.Autogenerated.csproj(31,11): error MSB4006: There is a circular dependency in the target dependency graph involving target "Publish". Since "PublishWithCustomRuntimePack" has "DependsOn" dependence on "Publish", the circular is "Publish<-PublishWithCustomRuntimePack<-_PublishBuildAlternative<-Publish".

@naricc I see it comes from commit 13ee8bebd7484fcab007a52d9a5ca4aea5e67b34, could you please take a look?

**Comment by naricc** [comment]
@radekdoulik Just going through old issues, this is resolved right?

**Comment by radekdoulik** [comment]
Yes, I don't see `PublishWithCustomRuntimePack` in https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Templates/WasmCsProj.txt, so I think this should be gone.
