### ISSUE TITLE
[Suggestion] common messaging API

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#177]
For now benchmark.net has multiple points of failure / informational messages that are passed as a plain text in the log:
- validator warnings | errors
- analyser warnings (no errors?),
- toolchain warnings / errors (not reported at all?)
- exceptions thrown.

I suggest to wrap all these into common interface, IMessage:

``` cs
enum MessageSource
{
    Analyser, Validator, Etc
}
enum MessageKind
{
    ExecutionFailure, InvalidSetup, Error, Warning, Notification, Informational, Debug, Etc
}
interface IMessage
{
    MessageSource Source { get; }

    MessageKind MessageKind { get; }

    // use case: to identify specific messages that can be parsed.
    string MessageCategory { get; }

    string Message { get; }
}
```

and to report all messages using that interface. This will be especially useful for out-of process diagnosers, they will be able to consume notification messages instead of doing weird tricks like this:
(in `SynchronousProcessOutputLoggerWithDiagnoser.cs`)

```
if (diagnosticsAlreadyRun || !line.StartsWith(IterationMode.MainWarmup.ToString()))
{
    continue;
}

try
{
    diagnoser?.AfterBenchmarkHasRun(benchmark, process);
}
finally
{
    // Always set this, even if something went wrong, otherwise we will try on every run of a benchmark batch
    diagnosticsAlreadyRun = true;
}
```

These messages can be passed via pipes, WCF via memorymappedfile + global mutex or via ConcurrentQueue (for in-process messaging). Concrete implementation should be chosen by the toolchain.

Also, the idea can be extended up to two-way messaging (of course, there should be a new interface for the reply messages).

It will allow to fix the #154 as there will be an API to pass arbitrary message into the child process and it'll be possible to move the benchmark dispatching logic into the child process. 

Moreover, we can remove the compilation/code generation part at all and replace it with something [like this](https://github.com/rsdn/CodeJam/blob/master/PerfTests/src/%5BL1_InProcess%5D/Toolchains/RunnableBenchmarkFactory.cs#L14) (prototype code, the API is not stabilized yet).

**Comment by mattwarren** [comment]
Hmm, this is an interesting suggestion, although I'm a bit torn. I actually quite like the simplicity of just parsing the console output of the child process, although that's not 2-way as you state.

However I think that having a proper API for 2-way communication between the host and the child-process will be useful going forward, for instance I *think* that it could also help with #133.

Are you happy to carry on developing a prototype? If you just report back here when you have updates and then @AndreyAkinshin, @adamsitnik or myself can take a look.

**Comment by ig-sinicyn** [comment]
@mattwarren 
Well, I can do it but I'm afraid that it will be not to soon.

I'm quite busy at work for a week or two and also I still had to finish [the competition test runner](https://github.com/rsdn/CodeJam/tree/master/Main/src-perfomance). It's in almost-ready state, need to add some missing features (the main one - annotating perftests with actual timings obtained from ci-server). After that I'll do a post here.

**Comment by mattwarren** [comment]
> Well, I can do it but I'm afraid that it will be not to soon.

Sorry, I wasn't trying to rush you, we're really grateful for all your contributions.

> I'm quite busy at work for a week or two and also I still had to finish the competition test runner. It's in almost-ready state, need to add some missing features (the main one - annotating perftests with actual timings obtained from ci-server). After that I'll do a post here.

Great, BTW the [competition test runner](https://github.com/rsdn/CodeJam/tree/master/Main/src-perfomance) stuff looks great!

**Comment by AndreyAkinshin** [comment]
@adamsitnik, @ig-sinicyn what the current status of this issue? Do we have something else that we are going to implement in this scope?

**Comment by adamsitnik** [comment]
@AndreyAkinshin we could refactor that with the next big release to unify all message-based APIs

**Comment by adamsitnik** [comment]
We have not made any progress on this since 2016. If it ever bites us again, we should just create a new issue, discuss it, and send a PR.
