### ISSUE TITLE
BenchmarkDotNet Wont Compile Assemblies

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1771]
Today, while trying to run a benchmark app (that worked earlier this week). It breaks before it compiles the .NET 5 and .NET 6 assemblies. This is what is shown:

```
***> BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19042.1165 (20H2/October2020Update)
Unknown processor
.NET SDK=6.0.100-preview.7.21379.14
  [Host] : .NET 6.0.0 (6.0.21.37719), X64 RyuJIT
 <***

.ctor
```

I am using VS2022 Enterprise Preview v17.0.0 Preview 3.
I am using v0.31.1 of BenchmarkDotNet

It does not create a log file. I have no idea how to track this down.

**Comment by adamsitnik** [comment]
I am unable to repro, closing
