### ISSUE TITLE
Ability to compare --corerun with --runtimes

### ISSUE THREAD

**Issue by stephentoub** [dotnet/BenchmarkDotNet#1774]
I can list multiple local frameworks to test with --corerun, or I can list multiple installed runtimes to compare with --runtimes, but I can't mix them, which makes it difficult to do things like answer the question "this routine regressed from .NET X to .NET Y... does my local patch to .NET Y fix the regression?"

**Comment by adamsitnik** [comment]
Fixed by #2002
