### ISSUE TITLE
Please add an easy way to remove columns

### ISSUE THREAD

**Issue by stephentoub** [dotnet/BenchmarkDotNet#1775]
For sharing simple results, in a blog post or the like, I don't want to show error, standard deviation, ratio standard deviation, median, nor do I want to show job or toolchain.  Right now I need to manually remove those columns from the resulting data every time I run a benchmark.  I would like to be able to add a one-liner to have the tool simply not output a set of named columns, whereas today it seems I need to instead start with an empty config and manually add all the columns I do care about (which I actually haven't figured out how to comprehensively do yet).

**Comment by mawosoft** [comment]
This might be of interest: https://github.com/mawosoft/Mawosoft.Extensions.BenchmarkDotNet

```cs
using Mawosoft.Extensions.BenchmarkDotNet;

// ...

ManualConfig config = DefaultConfig.Instance
    // Assuming benchmarks for multiple runtimes. See the docs for other job column scenarios.
    .ReplaceColumnCategory(new JobColumnSelectionProvider("-Job -Toolchain"))
    // If the default StatisticsColumnProvider is replaced, ratio column must be added manually (if needed).
    .ReplaceColumnCategory(StatisticColumn.Mean, BaselineRatioColumn.RatioMean);
```
Using the `JobColumnSelectionProvider` this way, would also fix #1603.

I already contemplated proposing some of these for integration into BDM, but I'm afraid it might add too much noise to the API surface.
