### ISSUE TITLE
MemoryDiagnoser Allocation column rounding hides huge discrepancies

### ISSUE THREAD

**Issue by stephentoub** [dotnet/BenchmarkDotNet#1777]
The Allocation column ends up rounding to the nearest KB mark if all entries are at least a KB, but this easily hides significant variance in amounts.  Consider:
```C#
[Benchmark]
public byte[] Allocate1008() => new byte[1008];

[Benchmark]
public byte[] Allocate1475() => new byte[1475];
```
And by default I get this:

|       Method |     Mean |    Error |   StdDev |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|------------- |---------:|---------:|---------:|-------:|-------:|------:|----------:|
| Allocate1008 | 34.23 ns | 0.627 ns | 0.524 ns | 0.1644 | 0.0006 |     - |      1 KB |
| Allocate1475 | 50.10 ns | 1.057 ns | 1.646 ns | 0.2397 | 0.0013 |     - |      1 KB |

It looks like they're allocating the same amount, even though one is allocating almost 50% more than the other.

It's fine to change units, but I think it'd be better if it didn't round to whole numbers, and instead allowed for fractions just like the rest of the columns.

(I also tried using WithSummaryStyle to change it to just always be in bytes, but that then forces me to hardcode the times to also be of a specific unit, which prevents benchmarkdotnet from automatically picking a more appropriate one.)

**Comment by timcassell** [comment]
Duplicate of #1727?
@TenCoKaciStromy was working on #1749 for that, but closed it. I'm not sure if they gave up or are working on another...

**Comment by stephentoub** [comment]
Oops, yes.  I have no recollection of opening it.  At least I'm consistent :-)
