### ISSUE TITLE
Small bug in ImmutableConfigbuilder

### ISSUE THREAD

**Issue by mawosoft** [dotnet/BenchmarkDotNet#1789]
https://github.com/dotnet/BenchmarkDotNet/blob/93786511bf9b2a0e2bdae45c7248ff963a750992/src/BenchmarkDotNet/Configs/ImmutableConfigBuilder.cs#L122-L135

I'm pretty sure Line 132 should be
```C#
if (!builder.Contains(analyser))
```
:wink:

**Comment by adamsitnik** [comment]
@mawosoft would you like to send a PR? Thanks!
