### ISSUE TITLE
Strange behavior of InliningDiagnoser and DisassemblyDiagnoser

### ISSUE THREAD

**Issue by extern-int** [dotnet/BenchmarkDotNet#1791]
I noticed that sometimes when I run the benchmark with dry configuration I do not get information about inlining, moreover, the disasembly code from the DisassemblyDiagnoser is different. The problem surprisingly ceases to occur when I add empty loops to the benchmark methods or when I increase the IterationCount to 300. Could someone explain this behavior and suggest me how can I get rid of it without changing the code benchmark methods?

```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Diagnosers;
using BenchmarkDotNet.Diagnostics.Windows;
using BenchmarkDotNet.Jobs;
using System;
using System.IO;
using System.Runtime.CompilerServices;

namespace Performance.Benchmarks
{
  [DiagnosersOnly]
  public class CastingVsUnsafe
  {
    private object obj = new Type();

    [Benchmark]
    public Type Cast()
    {
      // for (int i = 0; i < 0; i++) ; // Uncommenting this line fixes the problem
      return (Type)obj;
    }

    [Benchmark]
    public Type UnsafeAs()
    {
      // for (int i = 0; i < 0; i++) ; // Uncommenting this line fixes the problem
      return Unsafe.As<Type>(obj);
    }

    public class Type { }
  }

  public class DiagnosersOnlyAttribute : Attribute, IConfigSource
  {
    public IConfig Config { get; }
    public DiagnosersOnlyAttribute()
    {
      var job = new Job("DiagnosersOnly")
      {
        Run = { RunStrategy = BenchmarkDotNet.Engines.RunStrategy.ColdStart, IterationCount = 1 } // Changing IterationCount to a higher one also fixes the problem
      };
      var disassemblerConfig = new DisassemblyDiagnoserConfig(maxDepth: 3, printSource: true, exportHtml: true, exportCombinedDisassemblyReport: true, exportDiff: true);
      var diagnosers = new IDiagnoser[]
      {
        //MemoryDiagnoser.Default,
        new InliningDiagnoser(false, true),
        new DisassemblyDiagnoser(disassemblerConfig)
      };
      Config = DefaultConfig.Instance.AddJob(job).AddDiagnoser(diagnosers);
    }
  }
}
```

**Comment by mawosoft** [comment]
That's due to tiered compilation. The Jitter first generates code very quickly and optimizes it later.
Adding `<TieredCompilation>false</TieredCompilation>` as property to your project file will prevent it at the cost of slower start-up. Alternatively, you can specify it via environment variable or runtimeconfig.
See https://docs.microsoft.com/en-us/dotnet/core/run-time-config/compilation

**Comment by extern-int** [comment]
Switching property in the project and setting it up with runtimeconfig.json didn't help. Probably because these settings do not apply to the code generated by BenchmarkDotNet. However, setting the environment variable fixed my problem. Thank you.
