### ISSUE TITLE
.NET 5 x86 Benchmark failing

### ISSUE THREAD

**Issue by Tatenshi** [dotnet/BenchmarkDotNet#1792]
We have been using BenchmarkDotNet for our Solution and just recently switched from .NET Framework 4.8 to .NET 5. After that our Benchmark is failing.

I have made a simple .NET 5 Benchmark that uses x86, that is just doing a simple Benchmark but that errors too.
(We need to use x86 because of external Dependencies)

`// **************************
// Benchmark: Benchmark.Test1: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "e5dbd844-dc31-4d52-826d-2786c8a63f63.dll" --benchmarkName "TempTest.Benchmark.Test1" --job "Default" --benchmarkId 0 in C:\Users\Franz\source\repos\TempTest\TempTest\bin\x86\Release\net5.0\e5dbd844-dc31-4d52-826d-2786c8a63f63\bin\Release\net5.0
ExitCode != 0 and no results reported
// Benchmark Process 27452 has exited with code -532462766.
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!`

When running the execute command in CMD, it throws a System.BadImageFormatException.

`Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Users\Franz\source\repos\TempTest\TempTest\bin\x86\Release\net5.0\f4b20409-849d-40e8-a155-ba723954cc6c\bin\Release\net5.0\f4b20409-849d-40e8-a155-ba723954cc6c.dll'. Es wurde versucht, eine Datei mit einem falschen Format zu laden.
File name: 'C:\Users\Franz\source\repos\TempTest\TempTest\bin\x86\Release\net5.0\f4b20409-849d-40e8-a155-ba723954cc6c\bin\Release\net5.0\f4b20409-849d-40e8-a155-ba723954cc6c.dll'`
(Dont mind the other Dll-Name. Its the same Build just another run of it, where i interrupted it after the BenchmarkDotNet build)

When selecting AnyCPU no Exception is thrown and it works as intended.

Is this an error from BenchmarkDotNet or are we doing something wrong here?

Demo Testcode is attached below.
Program.cs:
```
using BenchmarkDotNet.Running;

namespace TempTest
{
    public class Program
    {
        static void Main(string[] args)
        {
            BenchmarkRunner.Run<Benchmark>();
        }
    }
}
```
Benchmark.cs:
```
using BenchmarkDotNet.Attributes;
using System.Threading;

namespace TempTest
{
    public class Benchmark
    {
        [Benchmark]
        public void Test1()
        {
            for (int i = 0; i < 25; i++)
            {
                // Do something ...
                Thread.Sleep(10);  
            }
        }
    }
}
```

**Comment by adamsitnik** [comment]
> switched from .NET Framework 4.8 to .NET 5. After that our Benchmark is failing.

For Full .NET Framework, BDN is capable of building and running a process of different architecture than the host process.

For .NET Core, it's impossible. To run benchmarks as `x86`, you need to use `x86` version of `dotnet.exe`.

If you want to run both, you might find this comment useful: https://github.com/dotnet/BenchmarkDotNet/issues/856#issuecomment-715910912

**Comment by Tatenshi** [comment]
I went with the ManualConfig from your linked comment. With that it worked. Thanks :)
