### ISSUE TITLE
Improve build time for wasm-aot benchmarks

### ISSUE THREAD

**Issue by naricc** [dotnet/BenchmarkDotNet#1793]
The building step for wasm-aot is very slow (about an hour locally). This is partially because the AOT step requires a publish, and then aots all the published assemblies. During the publish step, roslyn ends up getting pulled in, contributing a large number of assemblies.

Roslyn is references from the GetToolchain (), which referencss the Roslyn tool chain. But that is not really needed for wasm-aot.

It should be possible to create a method like around the roslyn toolchain:

```
bool IsWasmAot () {}
```

And then use feature switches (https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md) to tell the linker this will return true, thereby avoiding linking in roslyn.

This could probably also be used to guard around things other than roslyn, but that is the biggest item.

**Comment by naricc** [comment]
Please asign this issue to me.

**Comment by adamsitnik** [comment]
> about an hour locally

I've recently tried to build the WASM AOT benchmarks and it took just a few minutes.

I am going to close it, but feel free to send any PRs with improvements.
