### ISSUE TITLE
typo in error message

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/BenchmarkDotNet#1794]
01455d952 src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommandExecutor.cs      (Chris Lovett      2020-07-15 07:13:25 -0700  38)                     parameters.Logger.WriteLineError($"// command took more that the timeout: {parameters.Timeout.TotalSeconds:0.##}s. Killing the process tree!");

The text of the message should be: command took more than the timeout

**Comment by adamsitnik** [comment]
@RobertHenry6bev would you be interested in sending a PR?
