### ISSUE TITLE
Exception thrown: 'System.IndexOutOfRangeException' in BenchmarkDotNet.dll

### ISSUE THREAD

**Issue by gstratigopoulos96** [dotnet/BenchmarkDotNet#1798]
Hello everyone. While i was benchmarking some methods i saw in the Visual Studio 2019 debug output multiple 
`Exception thrown: 'System.IndexOutOfRangeException' in BenchmarkDotNet.dll`.

Code can be found here... [https://pastebin.com/1UGXswJH](url)

**Comment by adamsitnik** [comment]
Hello @gstratigopoulos96 

When you are running the benchmarks with debugger attached (BTW it's not recommended) you might see some of the exceptions that are thrown but also caught by BDN. 

Example: 

https://github.com/dotnet/BenchmarkDotNet/blob/156fd6928c166d2d67fe2262c7304da45503c9db/src/BenchmarkDotNet/Reports/Measurement.cs#L166-L173

If I miss understood your issue description and this was an exception that was stopping the benchmarking process, please reopen the issue.

Thanks,
Adam
