### ISSUE TITLE
Enable interactive, incremental runs through the terminal

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/BenchmarkDotNet#1799]
As a user who occasionally runs a large set of microbenchmarks across all of my machines, I need to run the benchmarks interactively and incrementally so that I can break the run up over several periods without having to start the run over if I need to interrupt it.

Here are some scenarios where this would be helpful:

1. Fire the run off at the end of my work day; but if I end up needing to use my machine for something else that evening, be able to pause and resume the run
2. If the run has not finished by the next morning, be able to terminate the run and restart it from where it left off at the end of that next day
3. If a reboot or Windows Update is forced upon my machine, be able to restart the run and pick up where it was interrupted

To support these scenarios, BenchmarkDotNet could offer the following functionality:

1. Press a key in the terminal window to pause the current run
2. Be presented with an interaction menu when the run is paused
3. From the menu, be able to:
    a. Resume the run
    b. Save state and terminate
    c. See details able the run's progress thus far, ideally with an estimated time to completion
4. Start runs with a command-line argument that indicates an incremental run is desired
    a. This would automatically save the run state periodically so that an unplanned interruption (forced reboot) wouldn't lose too much progress
    b. If previous state is detected, the run would resume from there
    c. Another command-line argument could immediately show the interaction menu instead of auto-resuming

**Comment by adamsitnik** [comment]
Up-for-grabs hints:

- This feature should be exposed by adding new `--resume` command line argument. You can use [CommandLineOptions.KeepBenchmarkFiles](https://github.com/dotnet/BenchmarkDotNet/blob/eda1a412418ba59eda676cd909accbed6756eeee/src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs#L83-L84) as an example of existing boolean flag exposed by command line args and just mimic what we did to add a new argument.
- When user specifies the `--resume` flag, we could do the following:
    - Parse the most recently updated `.log` file stored in the folder to which [rootArtifactsFolderPath](https://github.com/dotnet/BenchmarkDotNet/blob/eda1a412418ba59eda676cd909accbed6756eeee/src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs#L44) is pointing. Search for the last occurrence of `--benchmarkId $number`. Example: `
// Execute: dotnet 6d5b437c-3b30-4851-877d-06035fc8c365.dll --anonymousPipes 3536 1840 --benchmarkName BenchmarkDotNet.Samples.IntroJoin2.B --job Dry --benchmarkId 3 in D:\projects\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Release\net6.0\6d5b437c-3b30-4851-877d-06035fc8c365\bin\Release\net6.0`
    - Use the parsed `benchmarkId` and skip all the benchmarks with smaller id (they are just numbers from range `0...$benchmarkCount-1`). Most likely the best place to do that is [here](https://github.com/dotnet/BenchmarkDotNet/blob/eda1a412418ba59eda676cd909accbed6756eeee/src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs#L80)
    -  Since BenchmarkDotNet stores by default the results per type that defines benchmark, we should re-run all benchmarks executed for given type. So if we have two benchmarks in type `AB`: `A` and `B` and the benchmarking was interrupted with Ctrl+C after running `A`, both `A` and `B` benchmark should be re-run. This could be achieved by sth like:

```diff
foreach (var benchmarkRunInfo in supportedBenchmarks) // we run them in the old order now using the new build artifacts
{
+    var benchmarkWithHighestIdForGivenType = benchmarkRunInfo.BenchmarksCases.Last();
+    if (benchmarkToBuildResult[benchmarkWithHighestIdForGivenType].Id.Value < $parsedId)
+    {
+        continue;
+    }

    var summary = Run(benchmarkRunInfo, benchmarkToBuildResult, resolver, compositeLogger, artifactsToCleanup,
        resultsFolderPath, logFilePath, totalBenchmarkCount, in runsChronometer, ref benchmarksToRunCount);
```
- For testing you just need to run benchmarks defined in multiple files, interrupt the runs with Ctrl+C, re-try with `--resume` and verify the exported files content. A good example of simple benchmarks that run fast are [IntroJoin](https://github.com/dotnet/BenchmarkDotNet/blob/master/samples/BenchmarkDotNet.Samples/IntroJoin.cs) benchmarks.

````cmd
cd samples\BenchmarkDotNet.Samples
dotnet run -c Release -f net6.0 --filter *IntroJoin*
// hit Ctrl+C at some point
dotnet run -c Release -f net6.0 --filter *IntroJoin* --resume
```

**Comment by adamsitnik** [comment]
@melias yes, please!
