### ISSUE TITLE
Benchmark exception stops entire suite run

### ISSUE THREAD

**Issue by deipax** [dotnet/BenchmarkDotNet#1803]
Somewhere between version 0.12.1 and 0.13.1, when a Benchmark throws an exception the entire run is now aborted.  Where I used to receive the message: 

"No more Benchmark runs will be launched as NO measurements were obtained from the previous run!"

and the rest of the benchmarks continued to run, the entire suite now stops and reports the exception.

**Edit** The work around is to use 0.12.1.

**Comment by vvdev** [comment]
I experience the same issue since upgraded to 0.13.1

My problem is, that i'm trying to benchmark my code under .NET 6, and ThreadingDiagnoser from 0.12.1 doesn't work under .NET6 build.

**Comment by vvdev** [comment]
I just want to provide a little bit more context to explain why it can be an important issue:

I have benchmark suite which works about 20 hours per platform, it measures all individual aspects of solution and we run it before we commit each refactoring/change to ensure we didn't introduce any performance degradation.

Normally, after every coding day we run subset of this suite, and it then works for about 10 hours, overnight.
As per normal development process some bugs are time to time introduced and some benchmarks can fail.

And if this is the case - then you simply lost 1 day and should continue development without knowing impact of your last changes.
In situations when you literally hunting microseconds and bytes of allocations it really hurts.


PS: thank you for the great tool :)

**Comment by adamsitnik** [comment]
Hi @vvdev @deipax 

In the near future I won't have time to investigate the problem, but feel free to do it and send a PR with a fix. I'll definitely find some time to review the PR.
