### ISSUE TITLE
Memory diagnoser shows memory allocated but no GC collects for all generations

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/BenchmarkDotNet#1804]
I got some strange results when running benchmarks against the PowerShell compiler. The benchmarking result shows 1MB allocated memory, but no GC collects for all generations (see below for examples).

I wonder why there is no GC collects. Given that there is allocated memory, there should be at least collects for GC-0, right?

```ini
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1165 (21H1/May2021Update)
Intel Core i7-1065G7 CPU 1.30GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100-preview.6.21355.2
  [Host]     : .NET 6.0.0 (6.0.21.35212), X64 RyuJIT
  Job-KKVGUA : .NET 6.0.0 (6.0.21.35212), X64 RyuJIT

EnvironmentVariables=POWERSHELL_TELEMETRY_OPTOUT=1  PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:DebugType=portable

IterationTime=250.0000 ms  MaxIterationCount=20  MinIterationCount=15
WarmupCount=1
```

|             Method |     Mean |    Error |   StdDev |   Median |      Min |      Max | Allocated |
|------------------- |---------:|---------:|---------:|---------:|---------:|---------:|----------:|
| CompileBuildModule | 95.36 ms | 2.668 ms | 2.966 ms | 95.75 ms | 91.22 ms | 100.9 ms |      1 MB |

|             Method |     Mean |    Error |   StdDev |   Median |      Min |      Max | Allocated |
|------------------- |---------:|---------:|---------:|---------:|---------:|---------:|----------:|
| CompileBuildModule | 92.41 ms | 1.843 ms | 2.123 ms | 92.43 ms | 89.01 ms | 97.16 ms |      1 MB |

|             Method |     Mean |    Error |   StdDev |   Median |      Min |      Max | Allocated |
|------------------- |---------:|---------:|---------:|---------:|---------:|---------:|----------:|
| CompileBuildModule | 90.98 ms | 1.352 ms | 1.389 ms | 90.89 ms | 89.49 ms | 94.71 ms |      1 MB |

**Comment by adamsitnik** [comment]
> I wonder why there is no GC collects. Given that there is allocated memory, there should be at least collects for GC-0, right?

Let's consider Gen 0 as an example. 

When we try to allocate a small object (less than 85k bytes), GC checks if there is enough free space available. When there is, it just allocates the object. When there is no enough space available, it starts the garbage collection process and when it frees the memory, it allocates the object.

In your case, the benchmark runs for quite some time (90-95 ms), but does not allocate enough memory to run into a situation where Gen 0 needs a cleanup. Moreover, BDN forces GC cleanup between every iteration (to ensure that each iteration starts with a clean memory)) so that lowers the chances for a need of cleanup. If your benchmark was allocating more memory or taking less time and it would be invoked more times per iteration, you would have observed some GC collects.

**Comment by daxian-dbw** [comment]
> If your benchmark was allocating more memory or taking less time and it would be invoked more times per iteration, you would have observed some GC collects.

Thanks @adamsitnik, that makes sense. It turns out there were only 2 ops per each iteration, and like you said, that's likely too less ops to trigger a GC in my case.

A couple questions about my scenario:
1. Is it OK to have benchmarks with relatively long running time like in this case? (90 - 100ms)
2. If it's OK, then is it recommended to increase the `IterationTime` in cases like this one? Or just leave to the algorithm in BDN to determine the appropriate characteristics?

**Comment by adamsitnik** [comment]
> Is it OK to have benchmarks with relatively long running time like in this case? (90 - 100ms)

The more realistic given scenario is, the better. So it can take even more if needed.

> If it's OK, then is it recommended to increase the IterationTime in cases like this one? Or just leave to the algorithm in BDN to determine the appropriate characteristics?

If you increase the `IterationTime`, it will take more time to run the benchmarks. From my experience, the longer it takes to run the benchmarks, the fewer devs on the Team actually run them.

Personally I always look at the Allocated column and Gen **2**. If some Gen 2 collections happened, it might mean that the code is allocating large objects (> 85k) and it might be issuing [Full GC](https://adamsitnik.com/Array-Pool/#the-problem).

**Comment by daxian-dbw** [comment]
> The more realistic given scenario is, the better. So it can take even more if needed.

The scenario is to track the performance of the powershell compiler that turns PowerShell AST into LambdaExpression's.
We surely need to have simple test scripts to target how compiler handle some specific AST constructs. But I think it would also be useful to have some large-size real world scripts to test the compiler performance as a whole, which results in longer running time. Do you think it's the right thing to do to use large-size real world scripts for this scenario?

> If you increase the `IterationTime`, it will take more time to run the benchmarks. From my experience, the longer it takes to run the benchmarks, the fewer devs on the Team actually run them.

I understand. But in this case, each iteration only contains 2 ops, which doesn't even trigger the Gen 0 collection. Would that be considered missing important information? However, the allocated memory is present, so I guess we are not really missing that information?? Is it really necessary in this case to increase `IterationTime`?

**Comment by adamsitnik** [comment]
> However, the allocated memory is present, so I guess we are not really missing that information?? 

Correct.

> Is it really necessary in this case to increase IterationTime?

It's not. If your benchmark does not allocate a lot of memory, you would need to significantly increase `IterationTime` which would result in way more time needed to run the benchmarks. Moreover GC is self-tunning, so it could use bigger Gen 0 budget size and avoid collecting memory anyway ;)
