### ISSUE TITLE
How to change exporter output path?

### ISSUE THREAD

**Issue by asaf92** [dotnet/BenchmarkDotNet#1819]
The documentation says that "**by default**" the exporters will create a report in the .\BenchmarkDotNet.Artifacts\results path.

Is there a way to override this path (and more specifically for the HTML exporter)?

**Comment by adamsitnik** [comment]
Hi @asaf92 

`IConfig.ArtifactsPath` controls the output path for all exporters:

https://github.com/dotnet/BenchmarkDotNet/blob/24e041cb22f8f5914be32e588b0b890fe093a59c/src/BenchmarkDotNet/Configs/IConfig.cs#L36-L39

You can customize it by using the `WithArtifactsPath` extension method. Please keep in mind that it creates a new config instance and that you need to pass it to `BenchmarkRunner` or `BenchmarkSwitcher`:

```cs
public static void Main(string[] args)
{
    ManualConfig customConfig = DefaultConfig.Instance.WithArtifactsPath(@"/my/custom/path");

    BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args, customConfig);
}
```

**Comment by adamsitnik** [comment]
Fixed by https://github.com/dotnet/BenchmarkDotNet/pull/1850
