### ISSUE TITLE
[Question] Automate BDN reporting in Continuous Integration workflow

### ISSUE THREAD

**Issue by bouchraRekhadda** [dotnet/BenchmarkDotNet#1822]
Hello,

We have recently started exploring BenchmarkDotNet and we would like to set it up in our CI workflow (JetBrains TeamCity). 
We are mainly interested in CPU and memory consumption of certain code areas for a start in the performance testing journey; the idea is to report any regressions (yet to be precisely defined) found upon a commit push (or a range of commits), something like what it was reported by @adamsitnik at https://github.com/dotnet/runtime/issues/59149 could be a great start for us.
Do you mind sharing with us how these issues are created?

One last question, is the CI integration still in your roadmap (cf. this [comment](https://github.com/dotnet/BenchmarkDotNet/issues/566#issuecomment-335757077))?

Thank you in advance.

**PS**: Unfortunately we cannot use [Continuous Benchmark (.NET)](https://github.com/marketplace/actions/continuous-benchmark-net) since we use TeamCity as CI pipeline.

**Comment by bouchraRekhadda** [comment]
Thank you @adamsitnik for your detailed answer; we are indeed considering using the [ResultComparer](https://github.com/dotnet/performance/tree/main/src/tools/ResultsComparer) for now.
@AndreyAkinshin would you be able to provide insights on what Adam has mentioned above regarding TeamCity plugin for regressions identification?
Thank you in advance

**Comment by AndreyAkinshin** [comment]
Currently, we have a standalone service that just fetches data from TeamCity and processes it independently. Sorry, there is no a TeamCity plugin for now.

**Comment by bouchraRekhadda** [comment]
Thank you @AndreyAkinshin for your feedback.
Is there any hope to maybe hear about the plugin in the near future ?

**Comment by AndreyAkinshin** [comment]
Definitely not in the near future, sorry. Our current approach is highly customized to our own needs, and it's too complicated to make a universal solution based on it.

**Comment by adamsitnik** [comment]
I believe that all the questions have been answered. Please follow #54 for updates. But to be honest it's a very big feature and without external funding or major contribution I don't see it happening.
