### ISSUE TITLE
FEAT-REQ: A better HTML Output

### ISSUE THREAD

**Issue by Emasoft** [dotnet/BenchmarkDotNet#1825]
Hi!
Please improve the HTML output with a more meaningful layout. 
What would be optimal is something like this:

C# CODE Function A  ---  DISASSEMBLY Function A
C# CODE Function B  ---  DISASSEMBLY Function B
C# CODE Function C  ---  DISASSEMBLY Function C
....
BENCHMARKS RESULTS TABLE for all FUNCTIONS

Something similar to this infographics from Bartosz ( https://leveluppp.ghost.io/infographics/ ):

![image](https://user-images.githubusercontent.com/713559/138285783-3ef90c19-21d7-4739-bdd7-8705a291e198.png)

**Comment by adamsitnik** [comment]
No progress for a year, closing
