### ISSUE TITLE
[Question] Benchmarking Collection operations

### ISSUE THREAD

**Issue by darthkurak** [dotnet/BenchmarkDotNet#1833]
Hi. I try to benchmark some collection operation like Add on List.
For example, I want to benchmark List<T>.Add on different size of pre-populated collection to show difference in Capacity growing.
Something like this:

```
public class CollectionTests
{
    private static List<Student> _initialList = AutoFaker.Generate<Student>(131071);
    private List<Student> _listA; //adding to this still fit Capacity
    private List<Student> _listB; //adding to this should grow Capacity
    
    public CollectionTests()
    {
        _listA = new List<Student>(_initialList);
        _listB = new List<Student>(_initialList);
        _listB.Add(AutoFaker.Generate<Student>());
    }

    [Benchmark]
    public void List_A()
    {
        _listA.Add(AutoFaker.Generate<Student>());
    }

    [Benchmark]
    public void List_B()
    {
        _listA.Add(AutoFaker.Generate<Student>());
    }
}
```

what is the best approach to this? 
To have pre-defined collections and reuse them between iterations, but do not count collection preparation to execution time? 
This static approach and using GlobalSetup as well, do not give me correct results.

**Comment by adamsitnik** [comment]
```cs
public class CollectionTests
{
    private static Student _student = AutoFaker.Generate<Student>();
    
    [Params(8, 64, 100)]
    public int Count { get; set; }

    [Benchmark]
    public List<Student> DefaultCapacity()
    {
        var list = new List<Student>();
        
        for (int i = 0; i < Count; i++)
            list.Add(_student);
            
        return list;
    }

    [Benchmark]
    public List<Student> PerfectCapacity()
    {
        var list = new List<Student>(Count);
        
        for (int i = 0; i < Count; i++)
            list.Add(_student);
            
        return list;
    }
}
```

You can take a look at the existing `Add` benchmark from the dotnet/performance repo:

https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Add/AddGivenSize.cs
https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/CreateAddAndClear.cs

but foremost read https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md which is the set of guidelines used by the .NET Team
