### ISSUE TITLE
Markdown output should escape the output

### ISSUE THREAD

**Issue by stephentoub** [dotnet/BenchmarkDotNet#1839]
Various characters (e.g. `|`) if used in a Params will end up invalidating the generated markdown, causing it to render incorrectly.  It'd be helpful if benchmarkdotnet could escape the markdown output, e.g. output `\|` instead of `|`.

**Comment by adamsitnik** [comment]
I've marked the issue as up-for-grabs. Here are some hints for contributors interested in fixing the issue:

* The tests for markdown exporter can be found [here](https://github.com/dotnet/BenchmarkDotNet/blob/master/tests/BenchmarkDotNet.Tests/Exporters/MarkdownExporterApprovalTests.cs). Simplest way of testing that would be adding a new type with some `[Params("$needToBeEscaped", "$doesNotNeedToBeEscaped")] public string Name` field. And a file for expected output [here](https://github.com/dotnet/BenchmarkDotNet/tree/master/tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles)
* The logic that needs to be fixed can be found [here](https://github.com/dotnet/BenchmarkDotNet/blob/8a88b4cd0e874e18f2562912916ffc5d0a35e3bd/src/BenchmarkDotNet/Exporters/MarkdownExporter.cs#L133-L195)

**Comment by mawosoft** [comment]
This should IMHO exclude the `Console` Markdown exporter and rely on an escape flag like the existing `EscapeHtml`.
I'm reasonably familiar with GitHub Markdown, but not with the other flavors - there might be different character sets to escape depending on dialect.

(The easiest workaround is to just use the Console exporter and put it in a code fence)

**Comment by YegorStepanov** [comment]
System symbols (`\a`, `\t`, `\n`, etc) also break markdown and most likely other exporters too. Should be they escaped?

If yes, then the following parameters will be the same:
```C#
[Param("\t", @"\t")]
```

System symbols can be colored in a different color, but only for the console.
