### ISSUE TITLE
[Feature] Shows in the Benchmark summary if the Benchmark is running with administrator rights.

### ISSUE THREAD

**Issue by workgroupengineering** [dotnet/BenchmarkDotNet#1843]

**Comment by adamsitnik** [comment]
@workgroupengineering how to implement it in a cross-platform, .NET Standard 2.0 compatible way?

@AndreyAkinshin do you think that we should add such an information to the Summary? I am not convinced myself.

**Comment by workgroupengineering** [comment]
While I was testing this simple bench to figure out how to optimize an app, I didn't see a huge discrepancy between two bach sessions.

```csharp
   [MemoryDiagnoser]    
    [RankColumn(BenchmarkDotNet.Mathematics.NumeralSystem.Arabic)]
    public class Bench
    {
        static readonly List<string> s_data = Enumerable.Range(1, 10000)
            .Select(i => $"{i:00000}")
            .ToList();

        static readonly IList<string> s_iData = s_data;

        [Benchmark(Baseline = true)]
        public void For()
        {
            for (int i = 0; i < s_data.Count; i++)
            {
                Console.WriteLine(s_data[i]);
            }
        }

        [Benchmark()]
        public void For2()
        {
            var count = s_data.Count;
            for (int i = 0; i < count ; i++)
            {
                Console.WriteLine(s_data[i]);
            }
        }

        [Benchmark]
        public void ForEach()
        {
            foreach (var item in s_data)
            {
                Console.WriteLine(item);
            }
        }

        [Benchmark]
        public void Enumerator()
        {
            var enumerator = s_data.GetEnumerator();
            while (enumerator.MoveNext())
            {
                Console.WriteLine(enumerator.Current);
            }
        }

        [Benchmark]
        public void EnumeratorIList()
        {
            var enumerator = s_iData.GetEnumerator();
            while (enumerator.MoveNext())
            {
                Console.WriteLine(enumerator.Current);
            }
        }
    }
```

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1348 (21H1/May2021Update)
Intel Core i7-7700K CPU 4.20GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100
  [Host]     : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
  DefaultJob : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT


```
|          Method |    Mean |    Error |   StdDev |  Median | Ratio | RatioSD | Rank | Allocated |
|---------------- |--------:|---------:|---------:|--------:|------:|--------:|-----:|----------:|
|             For | 1.141 s | 0.0226 s | 0.0582 s | 1.138 s |  1.00 |    0.00 |    1 |     864 B |
|            For2 | 1.152 s | 0.0229 s | 0.0483 s | 1.143 s |  1.02 |    0.07 |    1 |     864 B |
|         ForEach | 1.125 s | 0.0222 s | 0.0383 s | 1.113 s |  0.98 |    0.06 |    1 |     864 B |
|      Enumerator | 1.133 s | 0.0225 s | 0.0484 s | 1.105 s |  1.00 |    0.05 |    1 |     864 B |
| EnumeratorIList | 1.104 s | 0.0211 s | 0.0267 s | 1.109 s |  0.96 |    0.05 |    1 |     904 B |

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1348 (21H1/May2021Update)
Intel Core i7-7700K CPU 4.20GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100
  [Host]     : .NET 6.0.0 (6.0.21.52210), X86 RyuJIT
  DefaultJob : .NET 6.0.0 (6.0.21.52210), X86 RyuJIT


``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1348 (21H1/May2021Update)
Intel Core i7-7700K CPU 4.20GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100
  [Host]     : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
  DefaultJob : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT


```
|          Method |     Mean |    Error |   StdDev | Ratio | RatioSD | Rank | Allocated |
|---------------- |---------:|---------:|---------:|------:|--------:|-----:|----------:|
|             For | 693.2 ms | 13.40 ms | 11.88 ms |  1.00 |    0.00 |    1 |     864 B |
|            For2 | 689.9 ms | 13.49 ms | 25.67 ms |  1.02 |    0.04 |    1 |     864 B |
|         ForEach | 677.3 ms | 13.44 ms | 24.58 ms |  0.98 |    0.04 |    1 |     864 B |
|      Enumerator | 701.0 ms | 13.56 ms | 31.96 ms |  1.00 |    0.05 |    1 |     864 B |
| EnumeratorIList | 727.7 ms | 16.82 ms | 49.07 ms |  1.09 |    0.07 |    2 |     904 B |


After investigating, I found that the difference is that one was being run as an administrator and the other was not.
If there had been an indication in the summary I would not have wasted time.

**Comment by workgroupengineering** [comment]
> @workgroupengineering how to implement it in a cross-platform, .NET Standard 2.0 compatible way? I try to made PR
