### ISSUE TITLE
Different result if running as admin or standard user

### ISSUE THREAD

**Issue by workgroupengineering** [dotnet/BenchmarkDotNet#1845]
When run this bench i have different result if running as admin or standard user

``` csharp
    [MemoryDiagnoser]    
    [RankColumn(BenchmarkDotNet.Mathematics.NumeralSystem.Arabic)]
    [SimpleJob(BenchmarkDotNet.Jobs.RuntimeMoniker.Net50)]
    [SimpleJob(BenchmarkDotNet.Jobs.RuntimeMoniker.Net60)]
    public class Bench
    {
        static readonly List<string> s_data = Enumerable.Range(1, 10000)
            .Select(i => $"{i:00000}")
            .ToList();

        static readonly IList<string> s_iData = s_data;

        [Benchmark(Baseline = true)]
        public void For()
        {
            for (int i = 0; i < s_data.Count; i++)
            {
                Console.WriteLine(s_data[i]);
            }
        }

        [Benchmark()]
        public void For2()
        {
            var count = s_data.Count;
            for (int i = 0; i < count ; i++)
            {
                Console.WriteLine(s_data[i]);
            }
        }

        [Benchmark]
        public void ForEach()
        {
            foreach (var item in s_data)
            {
                Console.WriteLine(item);
            }
        }

        [Benchmark]
        public void Enumerator()
        {
            var enumerator = s_data.GetEnumerator();
            while (enumerator.MoveNext())
            {
                Console.WriteLine(enumerator.Current);
            }
        }

        [Benchmark]
        public void EnumeratorIList()
        {
            var enumerator = s_iData.GetEnumerator();
            while (enumerator.MoveNext())
            {
                Console.WriteLine(enumerator.Current);
            }
        }
    }
```

### Standard User
``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1348 (21H1/May2021Update)
Intel Core i7-7700K CPU 4.20GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100
  [Host]   : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
  .NET 5.0 : .NET 5.0.12 (5.0.1221.52207), X64 RyuJIT
  .NET 6.0 : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT


```
|          Method |           Job |       Runtime |    Mean |    Error |   StdDev |  Median | Ratio | RatioSD | Rank | Allocated |
|---------------- |-------------- |-------------- |--------:|---------:|---------:|--------:|------:|--------:|-----:|----------:|
|             For |      .NET 5.0 |      .NET 5.0 | 1.160 s | 0.0231 s | 0.0543 s | 1.149 s |  1.00 |    0.00 |    2 |         - |
|            For2 |      .NET 5.0 |      .NET 5.0 | 1.136 s | 0.0226 s | 0.0436 s | 1.121 s |  0.98 |    0.06 |    2 |         - |
|         ForEach |      .NET 5.0 |      .NET 5.0 | 1.131 s | 0.0225 s | 0.0370 s | 1.122 s |  0.97 |    0.06 |    2 |         - |
|      Enumerator |      .NET 5.0 |      .NET 5.0 | 1.183 s | 0.0228 s | 0.0651 s | 1.179 s |  1.03 |    0.07 |    2 |         - |
| EnumeratorIList |      .NET 5.0 |      .NET 5.0 | 1.104 s | 0.0125 s | 0.0111 s | 1.100 s |  0.96 |    0.04 |    1 |      40 B |
|                 |               |               |         |          |          |         |       |         |      |           |
|             For |      .NET 6.0 |      .NET 6.0 | 1.139 s | 0.0224 s | 0.0453 s | 1.119 s |  1.00 |    0.00 |    2 |     864 B |
|            For2 |      .NET 6.0 |      .NET 6.0 | 1.190 s | 0.0238 s | 0.0654 s | 1.188 s |  1.03 |    0.06 |    3 |     864 B |
|         ForEach |      .NET 6.0 |      .NET 6.0 | 1.190 s | 0.0238 s | 0.0638 s | 1.178 s |  1.06 |    0.06 |    3 |     864 B |
|      Enumerator |      .NET 6.0 |      .NET 6.0 | 1.155 s | 0.0230 s | 0.0631 s | 1.155 s |  1.02 |    0.07 |    2 |     864 B |
| EnumeratorIList |      .NET 6.0 |      .NET 6.0 | 1.106 s | 0.0220 s | 0.0509 s | 1.094 s |  0.97 |    0.06 |    1 |     904 B |

### Admin 

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1348 (21H1/May2021Update)
Intel Core i7-7700K CPU 4.20GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100
  [Host]   : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
  .NET 5.0 : .NET 5.0.12 (5.0.1221.52207), X64 RyuJIT
  .NET 6.0 : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT


```
|          Method |           Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD | Rank | Allocated |
|---------------- |-------------- |-------------- |---------:|---------:|---------:|------:|--------:|-----:|----------:|
|             For |      .NET 5.0 |      .NET 5.0 | 630.8 ms | 12.34 ms | 12.11 ms |  1.00 |    0.00 |    1 |         - |
|            For2 |      .NET 5.0 |      .NET 5.0 | 624.4 ms | 11.93 ms | 12.76 ms |  0.99 |    0.01 |    1 |         - |
|         ForEach |      .NET 5.0 |      .NET 5.0 | 636.7 ms | 12.57 ms | 21.34 ms |  1.02 |    0.04 |    1 |         - |
|      Enumerator |      .NET 5.0 |      .NET 5.0 | 624.8 ms | 11.92 ms | 12.75 ms |  0.99 |    0.01 |    1 |         - |
| EnumeratorIList |      .NET 5.0 |      .NET 5.0 | 641.7 ms | 12.52 ms | 19.85 ms |  1.02 |    0.04 |    1 |      40 B |
|                 |               |               |          |          |          |       |         |      |           |
|             For |      .NET 6.0 |      .NET 6.0 | 625.1 ms | 11.96 ms | 13.30 ms |  1.00 |    0.00 |    1 |  10,992 B |
|            For2 |      .NET 6.0 |      .NET 6.0 | 628.9 ms | 12.45 ms | 12.79 ms |  1.01 |    0.02 |    1 |     864 B |
|         ForEach |      .NET 6.0 |      .NET 6.0 | 625.3 ms | 12.19 ms | 15.42 ms |  1.00 |    0.01 |    1 |     864 B |
|      Enumerator |      .NET 6.0 |      .NET 6.0 | 626.1 ms | 11.92 ms | 15.07 ms |  1.00 |    0.02 |    1 |     864 B |
| EnumeratorIList |      .NET 6.0 |      .NET 6.0 | 625.3 ms | 11.93 ms | 12.77 ms |  1.00 |    0.01 |    1 |  11,032 B |

**Comment by adamsitnik** [comment]
Hi @workgroupengineering 

BDN just runs the benchmark, we don't treat Admin vs non-Admin accounts differently.

To find out why it's slower|faster you need to use a profiler. Normally I would recommend you to use [EtwProfiler](https://adamsitnik.com/ETW-Profiler/) but it requires you to run the benchmarks as Admin ;)

You can watch my talk about [running a .NET Performance investigation](https://youtu.be/HDbtwTsar1Q?t=84) where I am introducing few profilers or just use [PerfView](https://channel9.msdn.com/Series/PerfView-Tutorial).

BTW when you use a profiler you will notice that your benchmarks dominated by the cost of `Console.WriteLine`. I encourage you to avoid doing that by for example consuming the strings length:

```cs
public int For()
{
    int consume = 0;
    for (int i = 0; i < s_data.Count; i++)
    {
        consume ^= s_data[i].Length;
    }
    return consume;
}
```

Or doing sth like [this](https://github.com/dotnet/performance/blob/e7b505e8a94f6c17fc34b53f1206700f7fccaa79/src/benchmarks/micro/libraries/System.Collections/Iterate/IterateForEach.cs#L90-L96).

And read the doc about [Microbenchmark Design Guidelines](https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md)

Since BDN has no special treatment for Admin, I am going to close the issue. Thanks!
