### ISSUE TITLE
GC Diagnoser should not include allocations done by Setup method

### ISSUE THREAD

**Issue by Bobris** [dotnet/BenchmarkDotNet#186]
See subj.

**Comment by mattwarren** [comment]
Hmm, yeah that's a good point, I'll take a look (also see #133)

**Comment by Bobris** [comment]
I read whole #133 before submitting this one, but because I don't have problem with unstable results and it didn't mentioned Setup method, I though should be good to separate these.

**Comment by mattwarren** [comment]
> I read whole #133 before submitting this one, but because I don't have problem with unstable results and it didn't mentioned Setup method, I though should be good to separate these.

Yeah that's absolutely fine, I wasn't saying it was a dupe, it was more a note to myself to fix that #133 at the same time.

Thanks for reporting this BTW, I didn't even consider the effect of `[Setup]` along with the `MemoryDiagnoser`.
