### ISSUE TITLE
[Question] How to change default time unit for result's grid?

### ISSUE THREAD

**Issue by agolaszewski** [dotnet/BenchmarkDotNet#1862]
| Method |       Runtime |     N |       Mean |     Error |    StdDev | Ratio |
|------- |-------------- |------ |-----------:|----------:|----------:|------:|
| Sha256 |    .NET 4.7.2 |  1000 |   7.735 us | 0.1913 us | 0.4034 us |  1.00 |

For example in this grid every measurement uses us. How to change time unit to ms or s?

**Comment by YegorStepanov** [comment]
@agolaszewski 
```C#
BenchmarkRunner.Run<Benchmark>(
    DefaultConfig.Instance.WithSummaryStyle(
        SummaryStyle.Default.WithTimeUnit(TimeUnit.Millisecond)));
```
