### ISSUE TITLE
Benchmark Run Fails when Using Compiler #if Statement

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#1863]
My benchmark project compiles to .NET 6 and 5. I added new methods that use this compiler switch:

`#if NET6_0`

If I run the benchmark from the .NET 5 exe, these methods are ignored. If I run the benchmark from the .NET 6 exe it failed with messages like this:

`C:\src\Books\RockYourCode\CodePerformance\src\OutputBin\net60\3fe6ea28-7142-489d-873c-272ecc98a472\3fe6ea28-7142-489d-873c-272ecc98a472.notcs(283525,40): error CS0103: The name 'TestParallelChannelQueue03' does not exist in the current context [C:\src\Books\RockYourCode\CodePerformance\src\OutputBin\net60\3fe6ea28-7142-489d-873c-272ecc98a472\BenchmarkDotNet.Autogenerated.csproj]`

TestParallelChannelQueue03 is one of the methods within the #if statement. Any ideas about what is going on?

**Comment by adamsitnik** [comment]
You are most likely hitting https://github.com/dotnet/BenchmarkDotNet/issues/1226#issuecomment-532144829

If you are not, please provide a small repro case and reopen the issue.

**Comment by RealDotNetDave** [comment]
If I'm understanding correctly, I can't just double-click on the EXE? Do I have to use this?

dotnet run -c Release -f net5.0 --runtimes net5.0 net6.0

**Comment by mawosoft** [comment]
> If I'm understanding correctly, I can't just double-click on the EXE? Do I have to use this?
> 
> dotnet run -c Release -f net5.0 --runtimes net5.0 net6.0

No, the command line allows you to use different runtimes without changing your code. You can also
- use attributes
```cs
[SimpleJob(RuntimeMoniker.Net50)]
[SimpleJob(RuntimeMoniker.Net60)]
public class Benchmarks
{
    [Benchmark]
    public int Method1() => new Random().Next(50);
}
```
- use a config
```cs
public static void Main(string[] args)
{
    ManualConfig config = DefaultConfig.Instance /* default for simplicity */
        .AddJob(Job.Default.WithRuntime(CoreRuntime.Core50))
        .AddJob(Job.Default.WithRuntime(CoreRuntime.Core50));
    BenchmarkRunner.Run(typeof(Program).Assembly, config, args);
}
```
- fake a cmdline
```cs
public static void Main(string[] args)
{
    args = "--runtimes net5.0 net6.0".Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
    BenchmarkRunner.Run(typeof(Program).Assembly, null, args);
}
```

**Comment by RealDotNetDave** [comment]
Below is how I have it setup in Program.cs. This worked great until I added the #if methods.

                var config = DefaultConfig.Instance
                    .AddJob(Job.Default.WithToolchain(CsProjCoreToolchain.NetCoreApp50))
                    .AddJob(Job.Default.WithToolchain(CsProjCoreToolchain.NetCoreApp60));

                config.WithOption(ConfigOptions.DisableOptimizationsValidator, true)
                      .WithOption(ConfigOptions.StopOnFirstError, true);

**Comment by mawosoft** [comment]
Yeah, that's fine. I didn't read the beginning of this thread about the conditionals, the answer to which Adam's link covers (shouldn't this be some sort of déjà vu for you ;) )

I assume the .NET 6 code doesn't compile for .NET5? You could put the \#if inside the benchmark methods or add an \#else with the same empty methods, which of course is a bit of a waste of time and may screw up any ratio columns.

**Comment by RealDotNetDave** [comment]
Right, deja vu! I ran the tests last night using the "use a config" above, and those methods inside of the #if statement is still not in the report.

**Comment by RealDotNetDave** [comment]
The only way I got it to work was to remove: .AddJob(Job.Default.WithRuntime(CoreRuntime.Core50))

Wish this was easier!

**Comment by RealDotNetDave** [comment]
Still can't get this to work. I tried:

dotnet run -c Release -f net5.0 --runtimes net5.0 net6.0

And that does not run the .NET 6 method surrounded by #if NET6_0.
