### ISSUE TITLE
Detect ReSharper's Dynamic Program Analysis

### ISSUE THREAD

**Issue by ltrzesniewski** [dotnet/BenchmarkDotNet#1871]
[Dynamic Program Analysis](https://www.jetbrains.com/help/resharper/Dynamic_Program_Analysis.html) is a feature of ReSharper that can detect memory allocation issues. It's enabled by default when running your project from Visual Studio with ReSharper installed, or from Rider.

 Unfortunately, it also impacts benchmark results.

Here's an example with DPA turned on:

![image](https://user-images.githubusercontent.com/7913492/146572319-fb577cd6-ce2e-48d9-97b3-674305dcea2c.png)

And the same benchmark with DPA turned off:

![image](https://user-images.githubusercontent.com/7913492/146572355-ae8e4328-1d82-4a25-ac52-2bb1ba98d9e3.png)

Note that while the `PcreRegex` benchmark is barely affected (it does not allocate), the `Regex` benchmark takes a longer time when DPA is turned on. The difference in ratio between the two runs shows this.

I'm not sure if DPA can be detected, but it would be nice to have a large warning/error of the same kind as when you run benchmarks in debug mode, especially since DPA is turned on by default.

**Comment by Sergey-Masloboev** [comment]
There is a way to detect when DPA is running. When DPA starts it creates named event for windows and semaphore for linux and MacOS. With this event DPA can be detected and shutted down if it is already running.
To prevent DPA launch we should set up “JETBRAINS_DPA_AGENT_ENABLE” to “1”. (Note: don’t use JETBRAINS_DPA_MODE from tools, it is created for manual control)
Also other profiling and monitoring tools can be checked: 
- .NET profiling can be checked by verification profiling environment variables: “COR_ENABLE_PROFILING” and “CORECLR_ENABLE_PROFILING” and corresponding values in the registry.
- ETW monitoring can be checked by ETW session enumeration like Performance Monitor: Performance->Data Collector Set->Event Trace Session. And verify that there doesn’t exist another session with ".NET Common Language Runtime" provider.

**Comment by adamsitnik** [comment]
> To prevent DPA launch we should set up Environment variable “JETBRAINS_DPA_AGENT_ENABLE” to “0”.

@Sergey-Masloboev should this env var be set before the VS is started? I guess that setting it by BDN for the benchmark process would not work?

cc @AndreyAkinshin

**Comment by ltrzesniewski** [comment]
@Sergey-Masloboev sent me [the following message on Twitter](https://twitter.com/SMasloboev/status/1472862106810732550?s=20):

> Another way is to set up this variable in code where you launch benchmarks: Environment.SetEnvironmentVariable("JETBRAINS_DPA_MODE", "DISABLE");
It will be propagated to the benchmark process that will be launched and DPA will be suppressed.

So I suppose we could add `Environment.SetEnvironmentVariable("JETBRAINS_DPA_AGENT_ENABLE", "0");` in the toolchains that execute benchmarks in separate processes. It wouldn't work for the in-process toolchain, but that seems much easier to do than detecting ETW/semaphore usage.

**Comment by Sergey-Masloboev** [comment]
@adamsitnik this variable should be set by profiling/benchmarking tools for profilee process. BenchmarkDotNet creates new process when starts benchmarning and I suppose that JETBRAINS_DPA_AGENT_ENABLE should be set for this process on creation

**Comment by adamsitnik** [comment]
> I suppose that JETBRAINS_DPA_AGENT_ENABLE should be set for this process on creation

@Sergey-Masloboev thanks!

I've sent a PR with the fix: #1874

@ltrzesniewski is there any chance you could test it by installing `0.13.1.1667` from our CI nuget feed once [this build](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/41953812) finishes (should be 30-40 minutes from now)?

```xml
<packageSources>
  <add key="bdn-ci" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

**Comment by Sergey-Masloboev** [comment]
> @Sergey-Masloboev sent me [the following message on Twitter](https://twitter.com/SMasloboev/status/1472862106810732550?s=20):
> 
> > Another way is to set up this variable in code where you launch benchmarks: Environment.SetEnvironmentVariable("JETBRAINS_DPA_MODE", "DISABLE");
> > It will be propagated to the benchmark process that will be launched and DPA will be suppressed.
> 
> So I suppose we could add `Environment.SetEnvironmentVariable("JETBRAINS_DPA_AGENT_ENABLE", "0");` (or rather configure it in `ProcessStartInfo`) in the toolchains that execute benchmarks in separate processes. It wouldn't work for the in-process toolchain, but that seems much easier to do than detecting ETW/semaphore usage.

For the in-process toolchain to stop DPA for our that is already running named event/semaphore should be used.

**Comment by ltrzesniewski** [comment]
@adamsitnik Thanks! Your PR did the job 🙂 

For reference, here are my results (on a different machine, with a different commit):

## v0.13.1

```
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1415 (21H2)
Intel Xeon E-2288G CPU 3.70GHz, 1 CPU, 8 logical and 8 physical cores
.NET SDK=6.0.100
  [Host]     : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
  DefaultJob : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
```

DPA off:

|    Method |     Mean |    Error |   StdDev | Ratio |  Gen 0 | Allocated |
|---------- |---------:|---------:|---------:|------:|-------:|----------:|
|     Regex | 54.66 ns | 0.418 ns | 0.391 ns |  1.00 | 0.0249 |     208 B |
| PcreRegex | 40.85 ns | 0.385 ns | 0.360 ns |  0.75 |      - |         - |

DPA on:

|    Method |     Mean |    Error |   StdDev | Ratio |  Gen 0 | Allocated |
|---------- |---------:|---------:|---------:|------:|-------:|----------:|
|     Regex | 66.20 ns | 0.252 ns | 0.236 ns |  1.00 | 0.0249 |     208 B |
| PcreRegex | 40.91 ns | 0.213 ns | 0.200 ns |  0.62 |      - |         - |

## v0.13.1.1667

```
BenchmarkDotNet=v0.13.1.1667-nightly, OS=Windows 10 (10.0.19044.1415/21H2/November2021Update)
Intel Xeon E-2288G CPU 3.70GHz, 1 CPU, 8 logical and 8 physical cores
.NET SDK=6.0.100
  [Host]     : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
  DefaultJob : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
```

DPA off:

|    Method |     Mean |    Error |   StdDev | Ratio |  Gen 0 | Allocated | Alloc Ratio |
|---------- |---------:|---------:|---------:|------:|-------:|----------:|------------:|
|     Regex | 56.29 ns | 0.339 ns | 0.317 ns |  1.00 | 0.0249 |     208 B |        1.00 |
| PcreRegex | 40.72 ns | 0.244 ns | 0.228 ns |  0.72 |      - |         - |        0.00 |

DPA on:

|    Method |     Mean |    Error |   StdDev | Ratio |  Gen 0 | Allocated | Alloc Ratio |
|---------- |---------:|---------:|---------:|------:|-------:|----------:|------------:|
|     Regex | 55.84 ns | 0.143 ns | 0.126 ns |  1.00 | 0.0249 |     208 B |        1.00 |
| PcreRegex | 41.12 ns | 0.161 ns | 0.143 ns |  0.74 |      - |         - |        0.00 |

---

I also tried to reproduce the issue on Linux, but I only have a VM, and my results were the same with DPA turned off and on with v0.13.1, so I don't have a good test environment on that OS.

**Comment by adamsitnik** [comment]
@ltrzesniewski thank you!
