### ISSUE TITLE
BenchmarkDontNet should make allowance for projects where Preview Features are enabled

### ISSUE THREAD

**Issue by bradykelly** [dotnet/BenchmarkDotNet#1872]
I have a .NET 6 project with _Preview Features_ enabled, i.e. my project file contains the `<EnablePreviewFeatures>True</EnablePreviewFeatures>` property. I have this to use the new C#10 _static abstracts_ feature.

When I try and run benchmarks on my project, BDN tries to build a project for benchmarking and gets a build error for just about everything in my project, and that build error is:

> error CA2252: Using 'Part1' requires opting into preview features

It would be great if BDN could observe this build property in source projects and include it in the build command for the projects that it generates.

**Comment by adamsitnik** [comment]
Hi @bradykelly 

I've sent a fix in #1873

Could you please check if it works? To do that you need to add our [CI NuGet feed](https://benchmarkdotnet.org/articles/guides/nuget.html#nightly) to your nuget.config file:

```xml
<packageSources>
  <add key="bdn-ci" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

And install the `0.13.1.1666` version once [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/41953286) build gets green (it should take around 30-40 minutes from now)
