### ISSUE TITLE
How to enable start/stop the benchmark (Using Front-End : React)

### ISSUE THREAD

**Issue by SidhantUppal** [dotnet/BenchmarkDotNet#1878]
How to enable start / stop  or toggle from client side?

**Comment by adamsitnik** [comment]
Hi @SidhantUppal 

BenchmarkDotNet supports only .NET Console Apps and it stops when the heuristic stopping criteria has been meet.

You can configure it:

https://benchmarkdotnet.org/articles/guides/console-args.html#number-of-invocations-and-iterations

The only way to stop the benchmark run is to interrupt it with `Crl+C`.

We don't intend to add another possibility to stop it, so I am going to close the issue.
