### ISSUE TITLE
Reading result data via C# code

### ISSUE THREAD

**Issue by DrMueller** [dotnet/BenchmarkDotNet#1891]
Hello there

I've set up BenchmarkDotNet, but I would like to use it not via the default exporters and statistics, but more in the means of an integration-test. Unfortunately, I didn't see a way to get the actual results as just plain values via the provided API.
Is this in fact not possible or even a good idea? The statistics and the printing are neat, but I wouldn't want to check the results manually.
I've also tried to toy around with a  custom-exporter and basically make this one the test, but this seems also very complicated and doesn't look to be your intention.

**Comment by mawosoft** [comment]
The BenchmarkRunner/Switcher that you call to execute the benchmarks returns `Summary` or `Summary[]`, which contains all the individual measurements in `BenchmarkReport[] Reports`.

You can also add one of the other existing exporters, like `JsonExporter.Full` to get these data.

**Comment by DrMueller** [comment]
@mawosoft Thank you very much, trying that out as fast as possible.
