### ISSUE TITLE
XUnit c#

### ISSUE THREAD

**Issue by anup1252000** [dotnet/BenchmarkDotNet#1895]
I have been trying to run BenchMarkDotnet by using this command "dotnet test -c Release" but unfortunately, that doesn't seem to work. 
Does Benchmark really support xunit? If so please guide me

**Comment by adamsitnik** [comment]
It does not.

You need to create a console app (not a lib or a test project), install BDN, author some benchmarks and modify the `Main` method so it calls `BenchmarkRunner`  or `BenchmarkSwitcher`: https://benchmarkdotnet.org/articles/guides/getting-started.html

once you do that you run it as every other console app (most likely `dotnet run -c Release` in your case)
