### ISSUE TITLE
Failed to benchmark .NET 7 in release mode

### ISSUE THREAD

**Issue by Symbai** [dotnet/BenchmarkDotNet#1900]
BenchmarkDotNet: 0.13.1
Visual Studio 2022 Preview 2
.NET 7.0-master

I've installed [.NET 7 master SDK](https://github.com/dotnet/installer/blob/main/README.md#installers-and-binaries). My benchmark project runs fine with .NET 6. But with .NET 7 I get a build error:

```
// Build Error: Standard output:

 Standard error:
   Restored C:\Users\Peter\Documents\TestProject\TestProject.Benchmark\TestProject.Benchmark.csproj (in 250 ms).
  Restored C:\Users\Peter\Documents\TestProject\TestProject\TestProject.csproj (in 228 ms).
  Failed to restore C:\Users\Peter\Documents\TestProject\TestProject.Benchmark\bin\Release\net7.0-windows\1d81826c-9275-4f41-bf97-6b046a535809\BenchmarkDotNet.Autogenerated.csproj (in 108 ms).
C:\Users\Peter\Documents\TestProject\TestProject.Benchmark\bin\Release\net7.0-windows\1d81826c-9275-4f41-bf97-6b046a535809\BenchmarkDotNet.Autogenerated.csproj : error NU1201: Project TestProject.Benchmark is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Project TestProject.Benchmark supports: net7.0-windows7.0 (.NETCoreApp,Version=v7.0)
  Determining projects to restore...

// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in C:\Users\Peter\Documents\TestProject\TestProject.Benchmark\bin\Release\net7.0-windows\1d81826c-9275-4f41-bf97-6b046a535809
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html
```

The most interesting sentence here is probably this one: `Project TestProject.Benchmark is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Project TestProject.Benchmark supports: net7.0-windows7.0 (.NETCoreApp,Version=v7.0)`

Which is actually funny because my benchmark project is set to .NET 7 AND debugging it works fine. Even all my tests run in `DEBUG` mode in VS following the [troubleshooting guide](https://benchmarkdotnet.org/articles/guides/troubleshooting.html#in-the-same-process). Its only the `release` mode where the benchmark fails.

```XML
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
```

**Comment by adamsitnik** [comment]
> Project TestProject.Benchmark is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Project TestProject.Benchmark supports: net7.0-windows7.0 (.NETCoreApp,Version=v7.0)

Most likely the auto-generated  contains" net7.0" rather than "net7.0-windows" in the `TargetFramework` node.

Could you please share the `C:\Users\Peter\Documents\TestProject\TestProject.Benchmark\bin\Release\net7.0-windows\1d81826c-9275-4f41-bf97-6b046a535809\BenchmarkDotNet.Autogenerated.csproj` file content?

> Which is actually funny because my benchmark project is set to .NET 7 AND debugging it works fine. Even all my tests run in DEBUG mode in VS following the troubleshooting guide. Its only the release mode where the benchmark fails.

Please move `AllowUnsafeBlocks` from the Debug-only `PropertyGroup` and see if it helps

```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
```

**Comment by Symbai** [comment]
> Please move `AllowUnsafeBlocks` from the Debug-only `PropertyGroup` and see if it helps

Did not helped

It only works in debug and release mode by using `new DebugInProcessConfig()`

> Most likely the auto-generated contains" net7.0" rather than "net7.0-windows" in the `TargetFramework` node.

Exactly this is the case, `Autogenerated.csproj`  contains:

`<TargetFramework>net7.0</TargetFramework>`

**Comment by adamsitnik** [comment]
The problem has most probably been already fixed in #1816:

https://github.com/dotnet/BenchmarkDotNet/blob/625b2cc08871358e34c5290bba49c2a024eec6e2/src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs#L70

The problem is that we have not released a new version to NuGet.org

Please download the preview version from our CI feed: https://benchmarkdotnet.org/articles/guides/nuget.html#nightly and let me know if it helps

**Comment by Symbai** [comment]
Using latest nightly I can confirm the issue is fixed

**Comment by adamsitnik** [comment]
@AndreyAkinshin .NET 7 preview 1 is going to be released in two weeks, we should consider releasing 0.13.2 before it happens so our users have good experience from day 1. What do you think?

cc @stephentoub who asked me for that offline

**Comment by AndreyAkinshin** [comment]
@adamsitnik I guess I can release v0.13.2 next week. Could you help me with the release notes?

**Comment by RealDotNetDave** [comment]
Do you support .NET 7 yet? I don't see a choice in `CsProjCoreToolchain`.

**Comment by Rand-Random** [comment]
@adamsitnik, @AndreyAkinshin
"next week" has been a while
.net 7 preview 1 has been a while (preview 6 is the latest as of writing)

What happened with the plan to release v0.13.2?

**Comment by Rand-Random** [comment]
@adamsitnik, @AndreyAkinshin
thx for the v0.13.2, noticed it got released after reading: https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7
