### ISSUE TITLE
PR builds should not be published to BDN nightly feed

### ISSUE THREAD

**Issue by mawosoft** [dotnet/BenchmarkDotNet#1922]
As the title says.

Currently, the latest version on the nightly feed is 0.13.1.1697, which comes from an unmerged PR that inadvertently reverts changes already commited to master. The version before, 0.13.1.1696, is actually the most recent build from master (at the time I'm writing this, of course).

I would do a PR to fix this myself, but this is probably an AppVeyor settings thing I haven't access to.

**Comment by adamsitnik** [comment]
@AndreyAkinshin could you please take a look?

**Comment by AndreyAkinshin** [comment]
@mawosoft thanks for reporting this! Should be fixed now.
![image](https://user-images.githubusercontent.com/2259237/153854850-d99b5161-3569-4566-a6f8-f7e16c19b45f.png)

**Comment by mawosoft** [comment]
@AndreyAkinshin , @adamsitnik 
This still seems to happen. PR #1935 just published version 0.13.1.1707 on the AppVeyor feed.
