### ISSUE TITLE
BenchmarkDotNet not generating fully optimized x86 assembly compared to other disassemblers

### ISSUE THREAD

**Issue by matthewcrews** [dotnet/BenchmarkDotNet#1924]
I am finding that BenchmarkDotNet is not producing as optimized x86-64 code as what other tools are reporting. SharpLab, Fasmi, and Godbolt show that .NET 6 produces more optimized x86-64 than is being produced by BenchmarkDotNet.

The behavior can be reproduced by cloning this repo:
https://github.com/matthewcrews/TypedArrayIndexing

And running: `dotnet run -c Release`

I found the following results for the two methods:

```
// * Summary *

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
.NET SDK=6.0.101
  [Host]     : .NET 6.0.1 (6.0.121.56705), X64 RyuJIT
  DefaultJob : .NET 6.0.1 (6.0.121.56705), X64 RyuJIT


|       Method |     Mean |    Error |   StdDev | BranchMispredictions/Op | CacheMisses/Op | Code Size |
|------------- |---------:|---------:|---------:|------------------------:|---------------:|----------:|
| ArrayOrdered | 53.08 ns | 0.490 ns | 0.459 ns |                       1 |              0 |      59 B |
| BlockOrdered | 63.83 ns | 0.971 ns | 0.908 ns |                       1 |              0 |      59 B |
```

The assembly that is generated for these tests is:
## .NET 6.0.1 (6.0.121.56705), X64 RyuJIT
```assembly
; Program+Benchmarks.ArrayOrdered()
       sub       rsp,28
       xor       eax,eax
       xor       edx,edx
       mov       rcx,[rcx+8]
       nop       dword ptr [rax]
M00_L00:
       mov       r8d,[rcx+8]
       dec       r8d
       cmp       r8d,edx
       jle       short M00_L01
       mov       rax,rcx
       cmp       edx,[rax+8]
       jae       short M00_L02
       movsxd    r8,edx
       mov       eax,[rax+r8*4+10]
       inc       edx
       jmp       short M00_L00
M00_L01:
       add       rsp,28
       ret
M00_L02:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 59
```

## .NET 6.0.1 (6.0.121.56705), X64 RyuJIT
```assembly
; Program+Benchmarks.BlockOrdered()
       sub       rsp,28
       xor       eax,eax
       xor       edx,edx
       add       rcx,10
M00_L00:
       mov       r8,rcx
       mov       r8,[r8]
       mov       r9d,[r8+8]
       dec       r9d
       cmp       r9d,edx
       jle       short M00_L01
       cmp       edx,[r8+8]
       jae       short M00_L02
       movsxd    rax,edx
       mov       eax,[r8+rax*4+10]
       inc       edx
       jmp       short M00_L00
M00_L01:
       add       rsp,28
       ret
M00_L02:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 59
```

Intuitively I thought the two tests would produce different performances but I wanted to understand why. It is true that BenchmarkDotNet produces more efficient x86-64 code for the `ArrayOrdered` test than it does for the `BlockOrdered` test.

When I tried investigating what x86-64 is generated with other tools, (SharpLab, Fasmi, and Godbolt), I found that the two methods end up generating exactly the same x86-64 assembly.

SharpLab produces different x86 for the two methods when I target `AnyCPU`. You can see it [here](https://sharplab.io/#v2:DYLgZgzgNALiCGEC2AfJB7AJgV2AUwAIAVPCGAWACgqBtAHgFk9FsAnPAPgF0CYBPAA6EAwgAsAlgGMA1ngB2VWnQDKMVtkkwA3AWHYy6JAFEAjtnjBx/HQDl0wwwPitxEdHO5V+QggCFg6DJ09Ews7NwEAOShEGx4UFFEHAQAvFQEGQRk6prpmfkAbhYEAGoW2KQgBM6s8Hx0kUl5+RlyeADuBAAUBVU1dQ1JAJSpBADepeWkowUEAL7NLUh4SABGeKwE4nKWbbwSEAB0AJIwK4stme1WogQA5ngw3eJV2zANMXEcI2mUl/+ZGAHQ5lYAVCA0N5bLiKP4AzLwOSYLKPZ5IvAAD1ecne0WYsXCIyKYMIv3h/yBrhBUwhUO2mExPDoAFoCMSKrCAcs1ht9lSADLyO5A0b8xF3cwPAAKLiQVnEBVIJxxAGYAEwAdRun3YH3xXz5R1B4MOgrkwtEF0yVoy6EVrBcDMNh1M5mAEAIGNGag5cMudo2jsIlKOAHFHgAJRCiBxOro/AgARk5mXkmFh+CeMET3XgfQdAze31Si0zBCQ2Bg8FW+AI7FiwCeKQIAAZS6iK1Wa4RxKM236CO0JLXe3RqqahSLWTnMOgbXXSLgnizqpCYQP8qPWb2ANRJxb1peLKhlmBq3NVfyBaR0MRSWRyBJFp/Y953mTyYtkzJlzvV2uHo2fbtk8f7dlsfa3hIH4eIsQ7iCOBBjvAE7mlOSZQfen4ELO86AcurLwGu85bhBe6JphMEcAei6NlQQA=)

When I tell SharpLab to target `x64`, they produce the same x86-64 assembly. Results [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzmgFxAENcBbAHzIgBMBXDGAAgBUZcCBYAKB4G0APAFkYpOrAB8AXSYEAngAdmAYQAWASzABrGADse/AQGUCUOmAIBuJsrocIZAKIBHOsQzr51gHIRlDhWIodVwIXWkeeSUmACEMCG0BQRExSRkAchTccRg0JnSWCSYAXh4mcqYOMwsyirqAN3cmADV3OnYQJiCoYjkBAolauvLdGAB3JgAKes7u3v7CgEoSpgBvFrb2FfqmAF8h4bIYMmAYKCZ1XQ9R2Q1cADoASQJjg+GKsc9VJgBzGAIpupOpcCP0sjkJMtStx3rCKgQ7vdWhh2rg+CCLlIDDC4RViLoaJV/oCCTAEMDdKDMqJspJlo0UcxobjYQiQkjNmiMZcaGSZAI4EwGe1sXCjiczrd2QAZPQ/BEraX4n5uP4ABWCZE86nq7CelIAzAAmADqX3BsDBNIhUoeyNR91lunlqjeFTd5QguqgwV5tvuLjcGFwTAQK1MIpx7y9Z19zDZDwA4v8ABKkVT+P2TKFMACMooqeho2MYAIIuamxFmPvmIMhJQOpaYZDoBGIwEYTFg2QwAOKTAADI3iS22x3mOoVkOo0wxhpO5OBF1HXKFYKKzQIB6u+wGACBV10ViZ3VF4LJwBqPMHbt7g48JsEI2VzpxBJaARqTQ6XR5Ot/ilQS/bQ9HrZkKibUd207W9eynYcASg8cLinT8NBA8IDjndQFyYJdiBXZ01zzNDv1AphN23WD90FYgj23M8UKvXNSIwwYZ2onggA=)

I'll post the SharpLab x64 results here for convenience:
```asm
; Core CLR 6.0.121.56705 on amd64

Test.t1(System.Int32[])
    L0000: xor eax, eax
    L0002: xor edx, edx
    L0004: mov r8d, [rcx+8]
    L0008: dec r8d
    L000b: cmp r8d, edx
    L000e: jle short L001b
    L0010: movsxd rax, edx
    L0013: mov eax, [rcx+rax*4+0x10]
    L0017: inc edx
    L0019: jmp short L000b
    L001b: ret

Test.t2(Block`1<System.Int32>, System.Int32)
    L0000: xor eax, eax
    L0002: xor edx, edx
    L0004: mov r8d, [rcx+8]
    L0008: dec r8d
    L000b: cmp r8d, edx
    L000e: jle short L001b
    L0010: movsxd rax, edx
    L0013: mov eax, [rcx+rax*4+0x10]
    L0017: inc edx
    L0019: jmp short L000b
    L001b: ret
```

Results from the Fasmi tool can be found at the top of this file [here](https://github.com/matthewcrews/TypedArrayIndexing/blob/main/Scratchpad.asm)

Fasmi results for convenience:
```asm
;Scratchpad.ArrayOrdered(Int32[])
L0000: xor eax, eax
L0002: xor edx, edx
L0004: mov r8d, [rcx+8]
L0008: dec r8d
L000b: cmp r8d, edx
L000e: jle short L001b
L0010: movsxd rax, edx
L0013: mov eax, [rcx+rax*4+0x10]
L0017: inc edx
L0019: jmp short L000b
L001b: ret

;Scratchpad.BlockOrdered(Block`1<Int32>)
L0000: xor eax, eax
L0002: xor edx, edx
L0004: mov r8d, [rcx+8]
L0008: dec r8d
L000b: cmp r8d, edx
L000e: jle short L001b
L0010: movsxd rax, edx
L0013: mov eax, [rcx+rax*4+0x10]
L0017: inc edx
L0019: jmp short L000b
L001b: ret
```

Godbolt is also showing that equivalent loops are generating the same x86. The results from Godbolt can be found [here](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1BUFCJsQAOpJfWQE8Ayo3QBhVLQCuLBnucAZPAZMADkvACNMYhAAJlILVAVCBwY3T289eMT7AQCg0JYIqNibTDtkoQJzAlSvHy5rTFtshgqq3JDwyJjrSuJq91q9BV6CdvzCmIBKa1QPYmR2DhYMD3oAagAVTGGAUg0AQT3DgFYAIR2AZhcAWUwmBTnMS%2Bwd44ARNYIATwtMNZcEHhkABrRhHcFnS4uCrEDx2Z6vN5Hb6/NanWioEFQ17nK63e6PBHvNZgDj4h7ETCkEkcDbPNaXJEHNYstbDWHw5ms7kANzEawAamIPNsQGtzMQmF8oaS6RcXlzuSyggB3NYQHliiVSmW056TBkXD47ADsp0Fwu2ho%2BPIZJqZ%2ByVrLYBUia0CtECfwIgIUADoAJIETAsI5Op0qwgINbATAEdUUd2CXXkwnyg2MsPh7M%2BvD%2BoWebY4wLxvCI8GK7PihjoNlxhM1zDqJMEFN3ClPdNrPmF61ZqtK3P5y0KYuCJNYVSIw0uAC03ctFcd4ZdhU%2Bvr9fkYwB91rWfkMwA8TFjymIeBYSR520Dggu0QA6lHU5S2wTX/L13m/QWRf6t0YPpLtyzhLvQ8YEFw6pMFqxCStKVwlvqfaVuBawsB4lRhOslIPLQ8aMmsGj9msaEYVh6x4HuxGViqgKUTO4qbtuu7zlB6CoCR3K4asBFXPOTDFuWlbclRULzmJ0TmlwJE8fhJFHGhBDRNBYropiwJQgCQKggw1JIfK%2BligZLjaSCYJdpmqH1uRTDYX8cl8R8NHLiyZGYXZDGEcRVxmbpCK0fRfxiVcTEATu0ZsVpgLmQw9IcVxrKOTOAlCe8iUsiFc7ugyUlrDJvkxf58qydsvFHBw0y0Jwxy8D4HBaKQqCcAAYjs0QXGyszzH87UXDwpAEJolXTMCICSAAHH6UgaAAnBoGhcLNxwAGyzZIJr1NVHCSHVw1NZwvAKCAGiDcN0xwLASBoCwFh0JE5CUDdd30FEHEEEEBArYtJhmJYfB0MGxDHRAYT7WEgTmF8nADTdbCCAA8gwtDQw1vBYCwh7iGjpD4JSZTXsdONNqUmGLANJaNPtnphJKxBfG4WD7QQ54sDDlV8AYwAKAKeCYCqCO/PVA38IIIhiOwUgyIIigqOoOO6Fth4gL95hWDTx2QNMqAWM0RNHY0pTNE4NY1OkXCxP4XrjF0XBcMccQJEkAhm3UjtZMkYydFEs2zQ0TTlCMrsSMUhtlAIrR9F7rpRHbDvDFUwf1AnUfW97IC%2B9MCjdQsegs5g5Mc9ttWkPVjXNRwfrBNgGxrCtfoaNNi3qm1HXUrghAkLl/XUm4t33cQ3dcJMvBDWjkyjSAxxcH6E3HPNvsTRokgXBoxzRH7227aX%2B0V0dJ1nePVWcNEe043vh9aBPpDXsDyTjUAA%3D%3D%3D)

I was not able to find a way to configure BenchmarkDotNet to generate the same x86 code as SharpLab-x64, Fasmi and Godbolt. Something very strange is going on because the SharpLab, Fasmi, and Godbolt results suggest that the final code from BenchmarkDotNet should be the same for both tests and therefore the same performance.

The last log file results can be found [here](https://gist.github.com/matthewcrews/9125f386c3dc8a316c04f1332eeef889)

I tried changing my project platform to only target `x64` but I'm still getting different assembly and performance numbers.

**Comment by adamsitnik** [comment]
> I am finding that BenchmarkDotNet is not producing as optimized x86-64 code as what other tools are reporting

BenchmarkDotNet is simply reporting the actual assembly code. What it does:

1. Creates a new project with boilerplate and compile it with Optimizations always enabled
2. Starts the new exe
3. The code performs warmup, pilot stage and actual run. In the meantime the code should get promoted to Tier 1
4. When benchmarking is done but the process is not finished, it attaches disassembler using [ClrMd](https://github.com/microsoft/clrmd)
5. It asks ClrMd for the disassembly for the code that was **executed**.

The only known issue with BDN disassembler is related to Tiered JIT heuristic: sometimes the Tiered JIT does not promote the method to Tier 1 and BDN might report Tier 0 code. This is typically caused by custom BDN settings that limit the number of warmup iterations etc. [Here](https://github.com/dotnet/BenchmarkDotNet/issues/1466#issuecomment-671241848) I've explained how to find out whether it's a problem.

I am 99.99% sure that BDN is correct and that the other tools use different ways of getting the disassembly. The best disassemblers available are provided by Intel VTune, AMD uProof and Visual Studio. Please use them for confirmation.

**Comment by matthewcrews** [comment]
You are correct! Thank you for the feedback. This helped me diagnose the source of the issue.
