### ISSUE TITLE
Is there any issue with dotnet <Benchmark>.dll on Linux arm  or arm64

### ISSUE THREAD

**Issue by Acruval** [dotnet/BenchmarkDotNet#1927]
No problem on windows environment. dotnet <Benchmark>.dll 
I check first https://benchmarkdotnet.org/articles/guides/troubleshooting.htmlbefore write

// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 2 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
Unable to find .sln or .csproj file. Will use current directory /home/********/Benchmark31 to search for project file. If you don't use .sln file on purpose it should not be a problem.
// ***** Done, took 00:00:00 (0.33 sec)   *****
// Found 2 benchmarks:
//   BenchMatchTalib.RecognizeEx: Job-ERJEFG(Platform=Arm, Runtime=.NET Core 3.1)
//   BenchMatchTalib.Recognize: Job-ERJEFG(Platform=Arm, Runtime=.NET Core 3.1)

// Generate Exception: Unable to find Benchmark in /home/*******/Benchmark31 and its subfolders. Most probably the name of output exe is different than the name of the .(c/f)sproj

// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in /home/********/Benchmark31/eb6f0439-1aab-4077-a60d-1cd1d2d33baa
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html
// ***** BenchmarkRunner: Finish  *****

**Comment by adamsitnik** [comment]
Hi @Acruval 

Have you copied the `.dll` from one machine to another?

BenchmarkDotNet generates some code that takes care of common microbenchmark pitfalls, builds it (using .NET SDK) and runs every benchmark in a dedicated process. To build the benchmark it needs the source code.

If for some reason you can't provide the source code or SDK you can use the [InProcessToolchain](https://benchmarkdotnet.org/articles/samples/IntroInProcess.html) that runs the benchmarks in the same process.

**Comment by Acruval** [comment]
Hi Adam Sitnik.
Thanks for your quick reply. I am aware you are working on this in your
sparse time.
If fat I was generating portable core in my windows X64 and deploying it on
ARM64.
Finally, I got thanks for your help.

  public class BenchmarkConfig : ManualConfig
    {
        public BenchmarkConfig()
        {
            var job = new Job
            {
                Environment =
                {
                    // Platform = Platform.Arm64,  //I need to investigate
this
                    //  Runtime = CoreRuntime.Core31,
                }
            };
            job = job.WithToolchain(InProcessEmitToolchain.Instance);
           ddJob(job);

I am not sure how accurate, I am doing this.

Thanks

Antonio de la Cruz

**Comment by adamsitnik** [comment]
> I am not sure how accurate, I am doing this.

As long as your benchmarks don't have any side effects you should be OK with using `InProcessEmitToolchain`.

If they do, you should copy the source code to arm machine and install .NET SDK on that machine (https://github.com/dotnet/installer).

Since the issue seems to be solved, I am going to close it now. Please reopen it if you have more questions/problems.
