### ISSUE TITLE
where can We get the source code of BenchmarkDotNet-v0.13.1.1603?

### ISSUE THREAD

**Issue by HFDude** [dotnet/BenchmarkDotNet#1964]
Hello, we want to support a new architecture called Loongarch64 architecture for .NET,  and we have completed .Net6-LoongArch64 dotnet SDK.
When We use the performance:release/6.0 branch to test the dotnet-sdk for LoongArch64,  the test case in performance:release/6.0 needs to rely on BenchmarkDotNet.dll  to check the arch information. But it seems that performance:release/6.0  is strongly relied on BenchmarkDotNet-v0.13.1.1603.
If we reduced the version v0.13.1.1603  to  v0.13.1 or  v0.13.0 of  the BenchmarkDotnet  to  run performance:release/6.0, a segment fault will be reported. 
So  where can I get the source code of BenchmarkDotNet-v0.13.1.1603 to support LoongArch64? 
Thanks.  Best regards！

**Comment by adamsitnik** [comment]
Hi @HFDude 

BenchmarkDotNet has dedicated NuGet feed where a new package is published after every green build: https://benchmarkdotnet.org/articles/guides/nuget.html#nightly

You need to add the feed to your `nuget.config` file:

```xml
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

You can create `nuget.config`

by running:

```cmd
dotnet new nugetconfig
```

But if you are working with dotnet/performance repository you need to modify this file:

https://github.com/dotnet/performance/blob/release/6.0/NuGet.config

**Comment by HFDude** [comment]
> Hi @HFDude
> 
> BenchmarkDotNet has dedicated NuGet feed where a new package is published after every green build: https://benchmarkdotnet.org/articles/guides/nuget.html#nightly
> 
> You need to add the feed to your `nuget.config` file:
> 
> ```
> <packageSources>
>   <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
> </packageSources>
> ```
> 
> You can create `nuget.config`
> 
> by running:
> 
> ```batchfile
> dotnet new nugetconfig
> ```
> 
> But if you are working with dotnet/performance repository you need to modify this file:
> 
> https://github.com/dotnet/performance/blob/release/6.0/NuGet.config

Hi, @adamsitnik

Yes, I understand. 

But now I need to based on the source code of the BenchmarkDotnet-v0.13.1.1603 to apply the following patch to support the identification of LoongArch64 architecture, and rebuild the BenchmarkDotnet.dll in my local environment. 

At present, the latest official tag of the BenchmarkDotnet is v0.13.1 , I can’t use the BenchmarkDotnet.dll which is compiled based on this tag. Because BenchmarkDotnet.dll-v0.13.1 is not available for  performance:release6.0.

So I want to know whether and where can we get  the source code of BenchmarkDotnet-v0.13.1.1603 ,  or  which commit-id 
 is related to BenchmarkDotnet-v0.13.1.1603 ?

Thanks.  Best regards！

<pre><code class="csharp">
diff --git a/src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs b/src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
index 0295bada..db2918cb 100644
--- a/src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
+++ b/src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
@@ -133,7 +133,7 @@ namespace BenchmarkDotNet.ConsoleArguments
         [Option("strategy", Required = false, HelpText = "The RunStrategy that should be used. Throughput/ColdStart/Monitoring.")]
         public RunStrategy? RunStrategy { get; set; }
 
-        [Option("platform", Required = false, HelpText = "The Platform that should be used. If not specified, the host process platform is used (default). AnyCpu/X86/X64/Arm/Arm64.")]
+        [Option("platform", Required = false, HelpText = "The Platform that should be used. If not specified, the host process platform is used (default). AnyCpu/X86/X64/Arm/Arm64/LoongArch64.")]
         public Platform? Platform { get; set; }
 
         [Option("runOncePerIteration", Required = false, Default = false, HelpText = "Run the benchmark exactly once per iteration.")]
diff --git a/src/BenchmarkDotNet/Environments/Platform.cs b/src/BenchmarkDotNet/Environments/Platform.cs
index d67e22d3..a1be71e3 100644
--- a/src/BenchmarkDotNet/Environments/Platform.cs
+++ b/src/BenchmarkDotNet/Environments/Platform.cs
@@ -35,6 +35,11 @@
         /// <summary>
         /// S390x
         /// </summary>
-        S390x
+        S390x,
+
+        /// <summary>
+        /// LOONGARCH64
+        /// </summary>
+        LoongArch64
     }
-}
\ No newline at end of file
+}
diff --git a/src/BenchmarkDotNet/Extensions/ConfigurationExtensions.cs b/src/BenchmarkDotNet/Extensions/ConfigurationExtensions.cs
index 3cfe73d5..2694cb3d 100644
--- a/src/BenchmarkDotNet/Extensions/ConfigurationExtensions.cs
+++ b/src/BenchmarkDotNet/Extensions/ConfigurationExtensions.cs
@@ -22,6 +22,8 @@ namespace BenchmarkDotNet.Extensions
                     return "ARM64";
                 case Platform.S390x:
                     return "S390x";
+                case Platform.LoongArch64:
+                    return "LOONGARCH64";
                 default:
                     return "AnyCPU";
             }
@@ -29,4 +31,4 @@ namespace BenchmarkDotNet.Extensions
 
         public static string ToConfig(this Jit jit) => jit == Jit.LegacyJit ? "1" : "0";
     }
-}
\ No newline at end of file
+}
diff --git a/src/BenchmarkDotNet/Portability/RuntimeInformation.cs b/src/BenchmarkDotNet/Portability/RuntimeInformation.cs
index 11462e60..77496c97 100644
--- a/src/BenchmarkDotNet/Portability/RuntimeInformation.cs
+++ b/src/BenchmarkDotNet/Portability/RuntimeInformation.cs
@@ -237,6 +237,7 @@ namespace BenchmarkDotNet.Portability
             // https://github.com/dotnet/runtime/blob/d81ad044fa6830f5f31f6b6e8224ebf66a3c298c/src/libraries/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/Architecture.cs#L12-L13
             const Architecture Wasm = (Architecture)4;
             const Architecture S390x = (Architecture)5;
+            const Architecture LoongArch64 = (Architecture)6;
 
             switch (ProcessArchitecture)
             {
@@ -252,6 +253,8 @@ namespace BenchmarkDotNet.Portability
                     return Platform.Wasm;
                 case S390x:
                     return Platform.S390x;
+                case LoongArch64:
+                    return Platform.LoongArch64;
                 default:
                     throw new ArgumentOutOfRangeException();
             }
diff --git a/src/BenchmarkDotNet/Toolchains/Roslyn/Builder.cs b/src/BenchmarkDotNet/Toolchains/Roslyn/Builder.cs
index a020b1c4..30beeccc 100644
--- a/src/BenchmarkDotNet/Toolchains/Roslyn/Builder.cs
+++ b/src/BenchmarkDotNet/Toolchains/Roslyn/Builder.cs
@@ -105,6 +105,8 @@ namespace BenchmarkDotNet.Toolchains.Roslyn
                     return Platform.Arm;
                 case OurPlatform.Arm64:
                     return Platform.Arm64;
+                //case OurPlatform.LoongArch64:
+                //    return Platform.LoongArch64;
                 default:
                     throw new ArgumentOutOfRangeException(nameof(platform), platform, null);
             }
@@ -156,4 +158,4 @@ namespace BenchmarkDotNet.Toolchains.Roslyn
             return message.Split('\'').SingleOrDefault(text => text.Contains("Version="));
         }
     }
-}
\ No newline at end of file
+}
</code></pre>

**Comment by mawosoft** [comment]
You could check the build history at 
https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/history
for the specific build, get the associated commit hash from there, then get the source code at that point.

**Comment by HFDude** [comment]
> You could check the build history at https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/history for the specific build, get the associated commit hash from there, then get the source code at that point.

Thank you very much. 

I have found the commit-id of  BenchmarkDotnet-v0.13.1.1603  following your guidance.

I will try whether the DLL file compiled by this version can be used.
