### ISSUE TITLE
[Feature request] No logger for benchmark run?

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#198]
As a proposal: add an ability to disable [logging for each benchmark run](https://github.com/PerfDotNet/BenchmarkDotNet/blob/571b3dec965d6341ed5a3432c5ac75458f2c7457/BenchmarkDotNet/Running/BenchmarkRunner.cs#L50).

Use case: as usual:)  
Unit test runner, dozens of perftests, tons of garbage in output dir :)
Most of it is removed as we use custom in-process runner, the ones that left are the log files and empty `results` folder (created by [this line](https://github.com/PerfDotNet/BenchmarkDotNet/blob/571b3dec965d6341ed5a3432c5ac75458f2c7457/BenchmarkDotNet/Running/BenchmarkRunner.cs#L98)).

**Comment by CodeTherapist** [comment]
It's time to implement this - can I do it?

**Comment by AndreyAkinshin** [comment]
@CodeTherapist sure!
