### ISSUE TITLE
Way to summarize all the params results

### ISSUE THREAD

**Issue by lucasteles** [dotnet/BenchmarkDotNet#1989]
For some cases would be great to have a way to have a summary result table with an average result for each Benchmark without the Param values. Is it possible now?

**Comment by YegorStepanov** [comment]
closed in https://github.com/dotnet/BenchmarkDotNet/pull/1890

In the new version of BDN (v0.13.2), you can hide any columns using the console option(**--hide** or **-h**) or attribute.

```powershell
dotnet run -c Release -- --hide Param
```

```C#
[HideColumn("Param", Column.Mean)] //Column class is the default set of BDN columns
public class BenchmarkClass{ ...}
```

**Comment by alexpovel** [comment]
For anyone coming across this and wondering why `HideColumn` isn't found (in `BenchmarkDotNet.Attributes`), it's `HideColumns` 😉
