### ISSUE TITLE
Left Justification option for summary table columns

### ISSUE THREAD

**Issue by erichiller** [dotnet/BenchmarkDotNet#1995]
It would be useful if there was an option to align/justify the Method column (leftmost column when there's only one namespace and It would be useful if there was an option to align/justify the Method column (leftmost column when there's only one namespace and class). My use case is that I typically name my methods in order of increasing specificity (opposite of DNS).

eg. this:
```
Method                            | Metric 1
----------------------------------|-------------
MajorMinorSpecificBaseline        | 1
MajorMinorSpecificDoItOneWay      | 2
SomeVeryDifferentMinorSpecific    | 3
MajorMinorSpecificDoItAnotherWay  | 4
```

Rather than the current:
```
Method                            | Metric 1
----------------------------------|-------------
       MajorMinorSpecificBaseline | 1
     MajorMinorSpecificDoItOneWay | 2
   SomeVeryDifferentMinorSpecific | 3
 MajorMinorSpecificDoItAnotherWay | 4
```

With left justification, the bases are aligned which makes it easier for me to quickly scan the column and see what methods are similar. Whereas with right justification there is no alignment between names at all.

My thought was adding something like `DefaultTextColumnJustification` to [`SummaryStyle`] with a type of `TextJustification`.

From a brief glance, I think the following would need to change:
- Currently [`SummaryTableColumn`] has a [`Justify`] property, but it is [set by whether the input `IColumn` is text or numeric], as there's no justify property on [`IColumn`]
- [`SummaryTable`] could pass the new `DefaultTextColumnJustification` from  [`SummaryStyle`] to [`SummaryTableColumn`] [here](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Reports/SummaryTable.cs#L89)

[`Justify`]: https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Reports/SummaryTable.cs#L101
[`SummaryTableColumn`]: https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Reports/SummaryTable.cs#L93

[set by whether the input `IColumn` is text or numeric]: https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Reports/SummaryTable.cs#L114

[`IColumn`]: https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Columns/IColumn.cs

[`TargetMethodColumn`]: https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Columns/TargetMethodColumn.cs

[`SummaryStyle`]: https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Reports/SummaryStyle.cs

[`SummaryTable`]: https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Reports/SummaryTable.csclass

**Comment by adamsitnik** [comment]
@erichiller it sounds reasonable, please send a PR
