### ISSUE TITLE
Cannot implicitly convert type 'object' to 'System.Collections.Generic.IEnumerable<int>' when using IEnumerable as parameter

### ISSUE THREAD

**Issue by nawfalhasan** [dotnet/BenchmarkDotNet#1999]
I need to run benchmarks on multiple settings, so I parameterize the benchmark. E.g.:

		private readonly IEnumerable<int> ParameterNonList = Enumerable.Range(0, 10000000);

		[ParamsSource(nameof(GetParameter))]
		public IEnumerable<int> Parameter { get; set; }

		public IEnumerable<IEnumerable<int>> GetParameter()
		{
			yield return ParameterList;
			yield return ParameterNonList;
		}

You can see `ParameterNonList` is a true sequence. Unfortunately BDN can't figure out the type correctly and it causes benchmarks to fail. I get this error:

> ConsoleApp1\ConsoleApp1\bin\Release\net6.0\86024128-65a6-400c-b237-b783415f7785\86024128-65a6-400c-b237-b783415f7785.notcs(3052,59): error CS0266: Cannot implicitly convert type 'object' to 'System.Collections.Generic.IEnumerable<int>'. An explicit conversion exists (are you missing a cast?) [XXX\ConsoleApp1\ConsoleApp1\bin\Release\net6.0\86024128-65a6-400c-b237-b783415f7785\BenchmarkDotNet.Autogenerated.csproj]

Can this be fixed? Or if it cant be supported, what is the correct way to pass in true IEnumerables as parameters? Attaching a solution reproducing the issue.

[ConsoleApp1.zip](https://github.com/dotnet/BenchmarkDotNet/files/8601901/ConsoleApp1.zip)

**Comment by timcassell** [comment]
#1812

**Comment by nawfalhasan** [comment]
Thank you. I will close this since this is a duplicate.
