### ISSUE TITLE
Freeze benchmark in version 13.1

### ISSUE THREAD

**Issue by MBurtsev** [dotnet/BenchmarkDotNet#2007]
Hi,
![image](https://user-images.githubusercontent.com/41398/168472693-5707e252-0d23-4c91-9f99-b2e80eb70d40.png)

When I switched to a new version(13.1) of the benchmark. It freezes and doesn't move on. You can get source [here](https://github.com/MBurtsev/DataflowChannel). In master branch .net6 and BDN 13.1, in Benchmark12 branch .net3.1 and DBN12. Is it possible to solve this? Also all works fine if I launch without benchmark:

```C#
        public static void Main(string[] args)
        {
            var ben = new OPOCBench();
            ben.ReadSetup();
            ben.Read();

            //BenchmarkRunner.Run<OPOCBench>();

            Console.WriteLine("Press any key for exit");
            Console.ReadKey();
        }
```

Thanks

**Comment by timcassell** [comment]
I have also noticed freezes sometimes and task manager shows 100% CPU usage on all cores during the freeze. It happens pretty randomly for me and I haven't looked into it at all. Definitely not what I would expect from single-threaded benchmarks.

**Comment by adamsitnik** [comment]
Hi @MBurtsev 

I am sorry but I won't be able to take a look in the near future

Could you please attach a Debugger to the benchmark process and see why it's blocked? (In VS you can hit Break All to see what it's currently executing)

https://benchmarkdotnet.org/articles/guides/troubleshooting.html#attach-a-debugger-from-ide

**Comment by MBurtsev** [comment]
Here is code works fine. But if I want initialize threads in the setup method it freezes. I made a simple helper class that allows you to create threads in advance to improve the accuracy of the test. Apparently this will have to be abandoned.

```C#
using BenchmarkDotNet.Attributes;
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;

namespace Benchmark
{
    [Config(typeof(BenchConfig))]
    public class ConcurrentQueueBench
    {
        private const int COUNT = 100_000_000;
        private int threads = 2;
        private ConcurrentQueue<int> _queue;

        [IterationSetup(Target = nameof(Enqueue))]
        public void EnqueueSetup()
        {
            _queue = new ConcurrentQueue<int>();
        }

        [Benchmark(OperationsPerInvoke = COUNT)]
        public void Enqueue()
        {
            var ready = 0;

            for (var n = 0; n < threads; n++)
            {
                Task.Factory.StartNew(() =>
                {
                    for (var i = 0; i < COUNT; i++)
                    {
                        _queue.Enqueue(1);
                    }

                    Interlocked.Increment(ref ready);
                }, CancellationToken.None, TaskCreationOptions.LongRunning, TaskScheduler.Default);
            }

            while(Volatile.Read(ref ready) < threads)
            {
                Thread.Yield();
            }
        }
    }
}

```

**Comment by timcassell** [comment]
@MBurtsev I took a look at your code and I found the culprit causing the freeze. That's quite different from the freezing I have experienced (which I suspect is the JIT).

```cs
        private void Job(Action action)
        {
            Interlocked.Add(ref _ready, 1);

            while (!Volatile.Read(ref _canStart))
            {
            }

            action();

            Interlocked.Add(ref _complate, 1);
        }
```

Your threads are waiting for `_canStart`, but they never yield. So if you started more jobs than you have hardware threads, the other jobs will never be able to start. You could simply add a thread yield in that while loop, but you should instead use a `System.Threading.Barrier` to synchronize your jobs.

Take a look at my [unit test thread helper](https://github.com/timcassell/ProtoPromise/blob/master/ProtoPromise_Unity/Assets/Plugins/ProtoPromiseTests/Helpers/ThreadHelper.cs) if you'd like to see an example of that behavior in action.

**Comment by MBurtsev** [comment]
> but they never yield

I use `Volatile.Write(ref _canStart, true);` in the start method. This is guaranteed to work. 

 ```C#
       [Benchmark(OperationsPerInvoke = COUNT)]
        public void Write()
        {
            _bench.Start();
        }

        public void Start()
        {
            Volatile.Write(ref _canStart, true);

            while (Volatile.Read(ref _complate) < _jobs)
            {
                Thread.Yield();
            }
        }
```

Just try this bench code without BDN.
```C#
            var ben = new Benchmark.Temp.OPOCBench();
            ben.ReadSetup();
            ben.Read();
```

**Comment by timcassell** [comment]
> I use `Volatile.Write(ref _canStart, true);` in the start method. This is guaranteed to work.

No, it's not guaranteed to run with your original code. (The code you just posted does have a thread yield.)

```cs
            // Run producers
            for (var n = 0; n < producers; n++)
            {
                _bench.AddJob(WriteJob);
            }

            // Run consumers
            for (var n = 0; n < consumers; n++)
            {
                _bench.AddJob(ReadJob);
            }

            _bench.WaitReady();
```

I don't know what hardware you are running this on, but consider you are running on a dual-core (2 threads) CPU, with 1 producer and 1 consumer. The main thread is running consuming 1 core. The first job starts running on the 2nd core and busy waits on the `while (!Volatile.Read(ref _canStart))` loop. Then the second job is created on a 3rd thread, but it doesn't actually start executing because the main thread and first job are consuming both physical cores. So then the main thread starts busy waiting on `while (Volatile.Read(ref _ready) < _jobs)` loop, which also does not yield. So now you have 2 cores busy waiting without yields and a third thread waiting to run but it can't.

The solution is to yield the thread while busy waiting. The clean way is to use a barrier to handle that synchronization.

**Comment by timcassell** [comment]
Also bear in mind that, by default, BDN will run the benchmarks in a separate process. So that's an extra core consumed by the original console app that's communicating with the actual benchmark process. If that 1 extra core puts you over that limit described in my last comment, that would explain why it works when you run it directly but not when you run it with BDN. You can force it to run the benchmarks in-process if you want.

**Comment by MBurtsev** [comment]
> the main thread and first job are consuming both physical cores.

In fact, even 16 threads will run on 2 core processors(I have 12). They will work in parallel. Each thread will receive a time quantum, the size of which depends on the thread's priority. No matter how many physical cores and threads you have, each thread will work. There are still a bunch of threads in the system kernel and other processes. If you were right, then multitasking would not be possible. In my case, the threads either do not start or close before they have time to reach the end.
So there is a freeze. Likely DBN closes threads. 99%

**Comment by MBurtsev** [comment]
Play with this code :)
```C#
    public class Program
    {
        public static void Main(string[] args)
        {
            var ready = 0;

            for (var n = 0; n < 4; n++)
            {
                Task.Factory.StartNew(() =>
                {
                    Interlocked.Add(ref ready, 1);

                    while (Volatile.Read(ref ready) != 5)
                    {
                    }

                    Console.WriteLine($"I am done, thread:{Thread.CurrentThread.ManagedThreadId}");

                }, CancellationToken.None, TaskCreationOptions.LongRunning, TaskScheduler.Default);
            }

            Console.WriteLine("Press 5 to stop threads");

            while (true)
            {
                if (Console.ReadLine() == "5")
                {
                    Volatile.Write(ref ready, 5);
                }
                else
                {
                    Console.Clear();
                    Console.WriteLine("Try again.");
                }
            }
        }
    }
```

**Comment by timcassell** [comment]
Ah, my mistake, you are correct, I was wrong. I tweaked your code a bit to match your helper and it still managed to complete even without yields.

<details><summary>code</summary>
<p>

```cs
public static void Main(string[] args)
{
    bool ready = false;
    int threadsReadyCount = 0;
    int threadsCompleteCount = 0;

    Console.WriteLine("Environment.ProcessorCount: " + Environment.ProcessorCount);

    int createdThreadsCount = Environment.ProcessorCount * 2;

    for (var n = 0; n < createdThreadsCount; n++)
    {
        Task.Factory.StartNew(() =>
        {
            Interlocked.Increment(ref threadsReadyCount);

            while (!Volatile.Read(ref ready))
            {
                //Thread.Yield();
            }

            Console.WriteLine($"I am done, thread:{Thread.CurrentThread.ManagedThreadId}");

            Interlocked.Increment(ref threadsCompleteCount);
        }, CancellationToken.None, TaskCreationOptions.LongRunning, TaskScheduler.Default);
    }

    Console.WriteLine("Main Thread, wait for threadsReadyCount");

    while (Volatile.Read(ref threadsReadyCount) != createdThreadsCount)
    {
        //Thread.Yield();
    }

    Console.WriteLine("Main Thread, set ready");
            
    ready = true;

    Console.WriteLine("Main Thread, wait for threadsCompleteCount");

    while (Volatile.Read(ref threadsCompleteCount) != createdThreadsCount)
    {
        //Thread.Yield();
    }

    Console.WriteLine("Main Thread complete");
}
```

</p>
</details>

**Comment by timcassell** [comment]
@MBurtsev I added `System.Diagnostics.Process.GetCurrentProcess().PriorityClass = System.Diagnostics.ProcessPriorityClass.High;` to the beginning of the main method, and it froze before completing. BDN sets the benchmark process priority to high, so that's probably the cause. Oddly, adding yields didn't help, but it did help when I changed `int createdThreadsCount = Environment.ProcessorCount * 2;` to `int createdThreadsCount = Environment.ProcessorCount + 1;`.

Either way, it does eventually complete, but it freezes for a good while with the process priority set to high.

**Comment by timcassell** [comment]
Working example with no freeze:

```cs
public static void Main(string[] args)
{
    Process.GetCurrentProcess().PriorityClass = ProcessPriorityClass.High;

    int threadsCompleteCount = 0;

    Console.WriteLine("Environment.ProcessorCount: " + Environment.ProcessorCount);

    int createdThreadsCount = Environment.ProcessorCount * 2;

    Barrier barrier = new Barrier(createdThreadsCount + 1);

    for (var n = 0; n < createdThreadsCount; n++)
    {
        Task.Factory.StartNew(() =>
        {
            barrier.SignalAndWait();

            Console.WriteLine($"I am done, thread:{Thread.CurrentThread.ManagedThreadId}");

            Interlocked.Increment(ref threadsCompleteCount);
        }, CancellationToken.None, TaskCreationOptions.LongRunning, TaskScheduler.Default);
    }

    Console.WriteLine("Main Thread, wait for barrier");

    barrier.SignalAndWait();

    Console.WriteLine("Main Thread, wait for threadsCompleteCount");

    var spinner = new SpinWait();
    while (Volatile.Read(ref threadsCompleteCount) != createdThreadsCount)
    {
        spinner.SpinOnce();
    }

    Console.WriteLine("Main Thread complete");
}
```

**Comment by timcassell** [comment]
I wrote a [BenchmarkThreadHelper](https://github.com/timcassell/ProtoBenchmarkHelpers/tree/main) to handle this kind of work (very similar to yours, but doesn't freeze the benchmark and supports maxConcurrency and exception propagation).

**Comment by MBurtsev** [comment]
@timcassell  Your solution has a significant impact on the result.

|  Method |     Mean |    Error |  StdDev |      Min |      Max |        Op/s |
|-------- |---------:|---------:|--------:|---------:|---------:|------------:|
| Enqueue | 139.9 ns | 17.45 ns | 4.53 ns | 132.8 ns | 144.4 ns | 7,146,257.9 |

##Reference result obtained without any helpers:

|  Method |     Mean |    Error |   StdDev |      Min |      Max |         Op/s |
|-------- |---------:|---------:|---------:|---------:|---------:|-------------:|
| Enqueue | 67.76 ns | 7.971 ns | 2.070 ns | 65.31 ns | 69.88 ns | 14,757,736.3 |

Here my test with your helper https://github.com/MBurtsev/BenchmarkTimcassell.git
But your example doesn't really freeze, it gives me hope, I'll probably find another way to make a helper.

**Comment by timcassell** [comment]
@MBurtsev I believe your benchmark config is giving you unreliable results. I got similar results when I ran it as-is, but then I changed your config from
```
AddJob(Job.MediumRun
    .WithLaunchCount(1)
    .WithWarmupCount(3)
    .WithIterationCount(5)
    .WithInvocationCount(1)
    .WithUnrollFactor(1)
    );
```
to
```cs
AddJob(Job.Default);
```
I changed the IterationSetup to GlobalSetup so BDN could use its heuristics properly, and I dropped the COUNT from 100_000_000 to 100_000 (100m takes way too long on my old phenom cpu).

These were my results:

|                  Type |  Method |     Mean |   Error |  StdDev |      Min |      Max |        Op/s |
|---------------------- |-------- |---------:|--------:|--------:|---------:|---------:|------------:|
|  ConcurrentQueueBench | Enqueue | 191.0 ns | 3.74 ns | 4.59 ns | 182.6 ns | 200.0 ns | 5,236,076.3 |
| ConcurrentQueueBench2 | Enqueue | 158.0 ns | 0.85 ns | 0.80 ns | 156.9 ns | 159.6 ns | 6,330,999.7 |

Interestingly, bench1 got even slower when dropping COUNT to 100:

|                  Type |  Method |     Mean |   Error |  StdDev |      Min |      Max |        Op/s |
|---------------------- |-------- |---------:|--------:|--------:|---------:|---------:|------------:|
|  ConcurrentQueueBench | Enqueue | 928.0 ns | 8.50 ns | 7.96 ns | 914.9 ns | 939.9 ns | 1,077,633.0 |
| ConcurrentQueueBench2 | Enqueue | 155.8 ns | 3.11 ns | 5.69 ns | 120.9 ns | 159.4 ns | 6,418,354.9 |

I'm not really sure how these results are like this for Bench1. Bench2 seems quite stable around 155ns no matter the count.

Also, even though the actual timing of Bench1 is not _that_ much slower than Bench2 with 100k COUNT, it takes way longer to complete the benchmark run thanks to the threads needing to be cleaned up between each iteration. I looked at my task manager while the benchmark was running, and Bench1 was at 100% CPU across all 6 of my cores (why? The actual benchmark only uses 2 cores), while Bench2 hovered around 65% CPU usage, and the entire run zipped through.

**Comment by MBurtsev** [comment]
The number of iterations greatly affects the accuracy of the results. The bigger it is, the better. I recommend using such an count that the test takes a few seconds.

**Comment by MBurtsev** [comment]
I did a new research on my problem. The write method is never called. All the same, I think that there is a bug in BDN.
![devenv_5iZJpLRxjV](https://user-images.githubusercontent.com/41398/169093580-f3160c9c-a2d0-433a-b46d-aafe26337f53.png)

**Comment by timcassell** [comment]
@MBurtsev The number of manual iterations doesn't really matter if you allow BDN to use its heuristics (which of course it can't if you use IterationSetup, so I understand where you're coming from).

You replaced your old helper with mine for that code? I can't see your whole solution.

**Comment by timcassell** [comment]
@MBurtsev I found a bug where I was creating an extra thread. After fixing that (updated on my repo), my new results are:

|                  Type |  Method |     Mean |    Error |   StdDev |       Min |      Max |        Op/s |
|---------------------- |-------- |---------:|---------:|---------:|----------:|---------:|------------:|
|  ConcurrentQueueBench | Enqueue | 114.0 ns | 17.25 ns |  4.48 ns | 107.25 ns | 117.9 ns | 8,771,223.0 |
| ConcurrentQueueBench2 | Enqueue | 115.9 ns | 41.35 ns | 10.74 ns |  96.76 ns | 121.9 ns | 8,628,836.2 |

That's neck-and-neck, but Bench2 still runs the full benchmark much faster between iterations.

**Comment by MBurtsev** [comment]
> The number of manual iterations doesn't really matter

A large number of iterations simulates highly loaded systems with special performance requirements. The data structures are very different internally. And it depends on the implementation how strongly the threads influence each other. If you have few operations, you will not see this in the benchmark.  

> You replaced your old helper with mine for that code?

Last post about my helper.

**Comment by timcassell** [comment]
> Last post about my helper.

I'm not sure what you mean by that.

But I tried your original benchmark, it froze for me just like it did for you. Then I replaced your thread helper with mine and the benchmarks completed.

|    Method |      Mean |       Error |    StdDev |    Median |       Min |       Max |         Op/s |
|---------- |----------:|------------:|----------:|----------:|----------:|----------:|-------------:|
|     Write |  75.24 ns |   276.53 ns |  15.16 ns |  80.10 ns |  58.25 ns |  87.38 ns | 13,290,331.7 |
|      Read |  64.32 ns |   480.50 ns |  26.34 ns |  50.97 ns |  47.33 ns |  94.66 ns | 15,547,183.1 |
| ReadWrite | 332.52 ns | 2,517.30 ns | 137.98 ns | 262.14 ns | 243.93 ns | 491.50 ns |  3,007,302.0 |

**Comment by MBurtsev** [comment]
This is what I'm talking about. [Here](https://github.com/MBurtsev/DataflowChannel/blob/master/Benchmark/OPOCBench.cs) the bench without any helpers gives a different result. Is it possible to use a helper that distorts the result so much?

|    Method |     Mean |     Error |    StdDev |      Min |      Max |          Op/s |
|---------- |---------:|----------:|----------:|---------:|---------:|--------------:|
|     Write | 5.821 ns | 0.1559 ns | 0.1031 ns | 5.683 ns | 5.953 ns | 171,780,592.1 |
|      Read | 4.893 ns | 0.0888 ns | 0.0588 ns | 4.812 ns | 5.003 ns | 204,367,948.0 |
| ReadWrite | 3.847 ns | 1.6445 ns | 0.9786 ns | 2.366 ns | 5.435 ns | 259,972,854.8 |

**Comment by MBurtsev** [comment]
So I found the problem. In this simple benchmark, I also get a freeze after removing `Thread.Yield()`. I have never come across this before. My helper also work fine now.

```C#
using BenchmarkDotNet.Attributes;
using DataflowBench.Helper;
using DataflowChannel;
using System.Threading;
using System.Threading.Tasks;

namespace DataflowBench.MPOCnoOrder
{
    [Config(typeof(BenchConfigWithTotal))]
    public class MPOCnoOrderWrite
    {
        private const int COUNT = 100_000_000;
        private ChannelMPOCnoOrder<int> _channel;

        [Params(1,2,4,8)]
        public int Threads { get; set; }

        [IterationSetup(Target = nameof(Write))]
        public void WriteSetup()
        {
            _channel = new ChannelMPOCnoOrder<int>();
        }

        [Benchmark(OperationsPerInvoke = COUNT)]
        public void Write()
        {
            var ready = 0;

            // Launch consumers
            for (var n = 0; n < Threads; n++)
            {
                Task.Factory.StartNew(() =>
                {
                    for (var i = 0; i < COUNT; i++)
                    {
                        _channel.Write(1);
                    }

                    Interlocked.Increment(ref ready);
                }, CancellationToken.None, TaskCreationOptions.LongRunning, TaskScheduler.Default);
            }

            // Wait until all write operations are completed
            while (Volatile.Read(ref ready) < Threads)
            {
                Thread.Yield(); // <---- Comment this for get freeze
            }
        }
    }
}
```

**Comment by timcassell** [comment]
It's the process priority. It seems high priority threads do not get time-quantumed like normal priority threads do. I was wondering why yields would even be necessary at all if every thread is always time-quantumed... but now we have both learned that it depends on the process priority. Just never run that code with `RealTime` priority! :stuck_out_tongue:

**Comment by MBurtsev** [comment]
Maybe BDN set RealTime priority )). Because this code works every were. I got rich experience.

**Comment by MBurtsev** [comment]
@timcassell  But my helper has more sexy code. I won't believe if you don't agree. :)
