### ISSUE TITLE
Benchmark execution time is not linear with Params count.

### ISSUE THREAD

**Issue by Kuinox** [dotnet/BenchmarkDotNet#2013]
Hello,
I'm trying to use BenchmarkDotnet to plot various algorithms/patterns execution times on parameters with a big range of values.  
My issue is that the execution time is not linear with the number of arguments:  
When running a benchmark on a void method (with custom config), I got the following timings:  
```
Params count:1000:7379ms
Params count:2000:19893ms
Params count:3000:35960ms
Params count:4000:59002ms
Params count:5000:88472ms
[...]
Params count:19000:1797197ms (that's almost 30 minutes)
```
It's obviously cause big issues for my use case.  
What workflow should I use for what I want to do ?

**Comment by adamsitnik** [comment]
Hi @Kuinox 

BenchmarkDotNet has heuristics for choosing:

- the number of invocations per iteration, 
- the number of warmup iterations
- the number of workload iterations (when to stop benchmarking)

there is no guarantee that if you run the same benchmark multiple times it's going to take similar amount of time. Especially for different parameters, when each case might require more runs to provide stable results. You can read more about how it works in our docs: https://benchmarkdotnet.org/articles/guides/how-it-works.html

To reduce the benchmarking time, you can customize your config. A good example is [this](https://github.com/dotnet/performance/blob/fa737e7d83921d50e744ff215e66469770f41c3d/src/harness/BenchmarkDotNet.Extensions/RecommendedConfig.cs#L37-L41) config from the dotnet/performance repo. Namely you may want to reduce the number of warmup iterations, iteration time and maximum iteration count.

**Comment by Kuinox** [comment]
I did said that I'm using a custom config:  
```
AddJob(Job.ShortRun
                    .WithLaunchCount(1)
                    .WithToolchain(InProcessNoEmitToolchain.Instance)
                    //.WithGcForce(true)
                    .WithWarmupCount(1)
                    .WithEvaluateOverhead(false)
                    //.WithInvocationCount(1)
                    //.WithIterationCount(1)
                    .WithStrategy(BenchmarkDotNet.Engines.RunStrategy.ColdStart)
                );
```

With that, When I add counters, I can see that it always do 3-4 invocations per parameter.

**Comment by adamsitnik** [comment]
> I did said that I'm using a custom config:

You did, but you have not shared it.

> .WithToolchain(InProcessNoEmitToolchain.Instance)

You are using the toolchain that runs all the benchmarks within the same process. If they have side effects (like memory leaks for example) this might be affecting all other benchmarks.

**Comment by Kuinox** [comment]
> You did, but you have not shared it.

Yes sorry, I should had.

> You are using the toolchain that runs all the benchmarks within the same process. If they have side effects (like memory leaks for example) this might be affecting all other benchmarks.

Yes, because I'm running it accross a large amount of parameters, having it spin another process, recompile, warmup again would take too much time (months of runtime). Because I will graph the timings for each parameters, I'm not very interested in high precision for a run.  

When I tried to find out the cause of very long benchmark time I tested with a method, that I think should have the minimum of side effect:  
```
[Benchmark]
public byte Nothing() => 0;
```
So I don't think the method tested itself is causing the non-linearity.

I was a lot tired when I opened my issue -sorry for that-, one of my question that I didn't explicited is: Is BenchmakDotNet the right tool to achieve what I'm trying to do ?  

My objective is to benchmark various algorithm (ie: parsing techniques) with a lot of parameters (caused by a lot of different parameters which combined make a lot of runs to do), and generate shiny graphs with it.

I know that I don't know what I'm doing in the high-performance realm, tell me if what I'm doing is totaly stupid :D

**Comment by adamsitnik** [comment]
BenchmarkDotNet is a high precision tool, and it comes with the price: running the benchmarks takes time.

Are you sure that you want to cover so many test cases? How are you going to visualize a benchmark with 19000 test cases? Will you be able to make the right conclusions based on this data?

If I were you I would narrow down the number of test cases:  https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md#test-cases

**Comment by Kuinox** [comment]
> Are you sure that you want to cover so many test cases?

Do I need it ? Not really, I want it mostly for the fun, this hobby project is fueled by fun.  

> How are you going to visualize a benchmark with 19000 test cases?  

Graphs with dot visualisation mostly.  

> Will you be able to make the right conclusions based on this data?

My objective is to give a general idea of the algorithms performance, not picking the best in a specific scenario.  

An exemple(on this one it's very easy to reduce the number of test case): "checking if the element is in the set", comparing hashset, versus brute force, etc...

With these results I will make a more educated guess: "Given I know this shouldn't contain more XYZ values, I should pick algorithms ABC". I may be wrong on this decision here, but I hope that generally thanks to this information, I will make better decision.

> If I were you I would narrow down the number of test cases

I agree that's would be smarter, but less fun. My only worry is that the results will be wrong or too far from reality.
