### ISSUE TITLE
Question: How can you add data for statistics

### ISSUE THREAD

**Issue by BryanEuton** [dotnet/BenchmarkDotNet#2027]
I would like to be able to view statistics for other aspects of my tests.  I tried to create an IColumn that will perform some calculations but I'm not sure how I can get to the data for each iteration.  I found the ExtraOutput for each Execute Results like below, but I couldn't find a way to add data from the test run to here.  
`public string GetValue(Summary summary, BenchmarkCase benchmarkCase)
        {
            var rtn = string.Empty;
            foreach(var report in summary.Reports)
            {
                foreach(var result in report.ExecuteResults)
                {
                    foreach(var line in result.ExtraOutput)
                    {
                        if(line.StartsWith("// MyTestRunStat"))
                        {
                            //do work
                        }
                    }
                }
            }
            return rtn;
        }`

Essentially what I'm trying to do is add my Cosmos Client return all of the RequestCharges for the run(s) so that I can aggregate that data as well.

**Comment by timcassell** [comment]
#784

**Comment by BryanEuton** [comment]
Thanks @timcassell .  I saw that earlier, but I didn't see any traction.  I should have probably just commented on that ticket instead.  Sorry alll.
