### ISSUE TITLE
How can I define a single baseline for ArgumentsSource?

### ISSUE THREAD

**Issue by Laniusexcubitor** [dotnet/BenchmarkDotNet#2038]
I know, that I can define a baseline for every argument like this:
```CSharp
public class DemoBenchmark
    {
        [Benchmark(Baseline = true)]
        [ArgumentsSource(nameof(Arguments))]
        public void Baseline(TimeSpan ts) => Thread.Sleep(ts / 2);

        [Benchmark]
        [ArgumentsSource(nameof(Arguments))]
        public void Benchmark(TimeSpan ts) => Thread.Sleep(ts);

        public IEnumerable<object> Arguments
        {
            get
            {
                yield return TimeSpan.FromMilliseconds(50);
                yield return TimeSpan.FromMilliseconds(100);
            }
        }
    }
```
|           Type |    Method |               ts |      Mean |    Error |   StdDev | Ratio | RatioSD |
|--------------- |---------- |----------------- |----------:|---------:|---------:|------:|--------:|
|                |           |                  |           |          |          |       |         |
|  DemoBenchmark |  Baseline | 00:00:00.0500000 |  31.26 ms | 0.160 ms | 0.150 ms |  1.00 |    0.00 |
|  DemoBenchmark | Benchmark | 00:00:00.0500000 |  62.68 ms | 0.440 ms | 0.412 ms |  2.01 |    0.02 |
|                |           |                  |           |          |          |       |         |
|  DemoBenchmark |  Baseline | 00:00:00.1000000 |  62.64 ms | 0.493 ms | 0.461 ms |  1.00 |    0.00 |
|  DemoBenchmark | Benchmark | 00:00:00.1000000 | 109.99 ms | 0.457 ms | 0.428 ms |  1.76 |    0.01 |

But can I somehow define a single baseline for all of the arguments?
I tried this
```CSharp
public class DemoBenchmark2
    {
        [Benchmark(Baseline = true)]
        public void Baseline() => Thread.Sleep(TimeSpan.FromMilliseconds(50));

        [Benchmark]
        [ArgumentsSource(nameof(Arguments))]
        public void Benchmark(TimeSpan ts) => Thread.Sleep(ts);

        public IEnumerable<object> Arguments
        {
            get
            {
                yield return TimeSpan.FromMilliseconds(50);
                yield return TimeSpan.FromMilliseconds(100);
            }
        }
    }
```
But the summary wants to compare a combination of arguments and method name.

|    Method |               ts |      Mean |    Error |   StdDev | Ratio | RatioSD |
|---------- |----------------- |----------:|---------:|---------:|------:|--------:|
|  Baseline |                ? |  62.40 ms | 0.522 ms | 0.489 ms |  1.00 |    0.00 |
|           |                  |           |          |          |       |         |
| Benchmark | 00:00:00.0500000 |  62.28 ms | 0.277 ms | 0.259 ms |     ? |       ? |
|           |                  |           |          |          |       |         |
| Benchmark | 00:00:00.1000000 | 109.16 ms | 0.614 ms | 0.574 ms |     ? |       ? |

**Comment by timcassell** [comment]
What is the purpose of that? BDN is designed to measure how long it takes to do the same amount of work over and over. When comparing baseline against other methods, they should be expected to have the exact same input and exact same output. Comparing different inputs is meaningless, as then it's an apples to oranges comparison.

**Comment by Laniusexcubitor** [comment]
In my case I am using the arguments source to build the benchmarks dynamically from a list. So the arguments are baskets of apples. The arguments have no impact on the comparability of the benchmarks.

**Comment by Laniusexcubitor** [comment]
Although I don't need it anymore, I was curious how it could be done.
It can be done using a custom column.

Quick and dirty:
```CSharp
public class RatioColumn : IColumn
{
    public string Id => "Ratio";

    public string ColumnName => "Ratio";

    public bool AlwaysShow => false;

    public ColumnCategory Category => ColumnCategory.Custom;

    public int PriorityInCategory => 0;

    public bool IsNumeric => true;

    public UnitType UnitType => UnitType.Dimensionless;

    public string Legend => "[Current]/[Baseline]";

    public string GetValue(Summary summary, BenchmarkCase benchmarkCase)
    {
        var type = typeof(CustomBaselineAttribute);
        var baselines = summary.BenchmarksCases
            .Where(it => it.Descriptor.WorkloadMethod.GetCustomAttributes(type, false).Length > 0).ToList();
        if(baselines.Count == 1)
        {
            var baseline = baselines[0];
            var baselineReport = summary.Reports.First(it => it.BenchmarkCase == baseline);
            var report = summary.Reports.First(it => it.BenchmarkCase == benchmarkCase);

            return (report.ResultStatistics.Mean / baselineReport.ResultStatistics.Mean).ToString("#.00");
        }

        return "?";
    }

    public string GetValue(Summary summary, BenchmarkCase benchmarkCase, SummaryStyle style) => GetValue(summary, benchmarkCase);


    public bool IsAvailable(Summary summary)
    {
        var type = typeof(CustomBaselineAttribute);
        var baselines = summary.BenchmarksCases
            .Where(it => it.Descriptor.WorkloadMethod.GetCustomAttributes(type, false).Length > 0).ToList();
        return baselines.Count == 1;
    }

    public bool IsDefault(Summary summary, BenchmarkCase benchmarkCase) => false;
}

[AttributeUsage(AttributeTargets.Method)]
public sealed class CustomBaselineAttribute: Attribute
{
}
```
