### ISSUE TITLE
Support .NET Framework 4.8.1

### ISSUE THREAD

**Issue by martincostello** [dotnet/BenchmarkDotNet#2039]
The code that maps servicing versions to release versions currently assumes that .NET Framework 4.8 is the last version of .NET Framework.

https://github.com/dotnet/BenchmarkDotNet/blob/762b76c3685728758e815f6c86cb0da06bdcd180/src/BenchmarkDotNet/Helpers/FrameworkVersionHelper.cs#L52-L53

With the [announcement](https://blogs.windows.com/windowsdeveloper/2022/05/24/create-next-generation-experiences-at-scale-with-windows/) of Visual Studio support for ARM64 on Windows 11 and the release of .NET Framework 4.8.1 to support it ([docs](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-on-arm-devices?view=vs-2022#managed-developers)), this assumption is no longer correct.

The code should be updated as appropriate to return `"4.8.1"` when run on .NET Framework 4.8.1, rather than `"4.8"` to match the conventions used for .NET Framework 4.6.x and 4.7.x.

**Comment by adamsitnik** [comment]
@EgorBo do you know when 4.8.1 is going to get released so we could implement and test the support?

**Comment by martincostello** [comment]
FYI, seems this shipped today: https://devblogs.microsoft.com/dotnet/announcing-dotnet-framework-481/
