### ISSUE TITLE
[Request for help] Measuring timings on Appveyor.

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#204]
UPD: [solved](https://github.com/PerfDotNet/BenchmarkDotNet/issues/204#issuecomment-225393633).
## Part 0: Doing a wrong thing.

Hi!
I've spend last three or four evenings trying to obtain accurate results from benchmarks being run as an Appveyor unit test. I was hoping it is the last thing preventing me from releasing stable version of the perf test runner.
Long story short, it does not:)

Long story long, I wasted a lot of time doing a wrong thing: trying to tune BencmarkDotNet config to get results that I've expected to get from it. 
Let's say you have 
- method1 that calls `Thread.SpinWait(100*1000)` and exits 
- method2 that calls `Thread.SpinWait(200*1000)` and exits 

Can you guess what relative timings for these will be? Something like `~1.95x..2.05x`, right?
Wrong! From appveyor's point of view it's something between `1.7x..10.73x`. 

Yeah, benchmarking is hard and I've just learned it the hard way:)
The initial mistake was pretty simple: the metric was 
`benchmark time (95th percentile) / baseline time (95th percentile)`,
 but there were too few samples (10 afair) and there were significant delays time to time. Screwed up:)

Ok, that's pretty easy to fix. More runs (let's say, `config.TargetCount = 30`) and use median, not percentile. This should work, right?
Fail again, relative timings are now in range `1.8x..3.07x`. And this for a dummy loop code. Err, how can I trust the results if I can't reliably compare two dummy loops? :panicking:
Ok, stopping myself from trying to fit statistics into expected results.

At first I was sure that there's something wrong with the code 
(What was I thinking, man? Is there's even a way to do a mistake with a single 
`Thread.SpinWait()` call??? :))
or with the benchmark config or with appveyor's settings (of course it was not).

And yesterday I've find myself thinking that "found 10000 ways that won't work" achievement was not the thing I'm trying to get.
## Part 1: Timing it.

After that all was pretty simple.
[Here's a code](https://github.com/ig-sinicyn/TimingsAccuracy) that runs a benchmark without using bench.net runner. Just plain old Stopwatch and a callback called in the loop.

The benchmark includes five methods:
- Base - contains single `Thread.SpinWait(100*1000)` call.
- X2, X2-2, X2-3 - all calling `Thread.SpinWait(200*1000)`.
- X5 - `Thread.SpinWait(500*1000)` call.

All targets but X2-3 are run in the same loop, one after another, packed in batches of 50 runs
(50 runs for base, 50 runs for slowerX2, 50 runs for slowerX2-2 etc), repeat 20 times. 1000 samples for each method.

This way any delays caused by environment will be wisible as a simultaneous peaks on the plot.
And to proof that the delays are caused by environment, not the benchmark code, there's X2-3 target that run in separate loop and therefore should not have peaks at the same time.

Here's the plot for the run from appveyor (x - sample number, y - time in nanoseconds).
![appveyor_trimmed](https://cloud.githubusercontent.com/assets/11225241/15928664/f4def188-2e50-11e6-8bce-6cd6f5414f53.png)

**Bad news, number one:**
When run on appveyor there are significant delays and these are not depend on the code being run.
Is there problem with the cpu load or the Stopwatch.Elapsed is broken when run under VM? For now I don't care as I can't change it anyway.
What is important is the fact I can not obtain correct results with small number of runs. Here's a statistics for 10 samples window:
![appveyor_table_10rows](https://cloud.githubusercontent.com/assets/11225241/15929189/3030a7ec-2e54-11e6-93b2-c4871c506799.png)
"Sholuld be 2x" methods is measured as 10.75x slower at 95th percentile? P for precise, yeah.

So, I need to collect hundreds of samples to be more or less accurate. Will it be enough? 

**Bad news, number two:**
Here's the same plot but not trimmed by Y scale.
![appveyor_all_values](https://cloud.githubusercontent.com/assets/11225241/15928735/517500ea-2e51-11e6-84bf-8a70bacea150.png)

Here's statistics for all samples:
![appveyor_all_table](https://cloud.githubusercontent.com/assets/11225241/15928804/d9bfda4c-2e51-11e6-98b0-878dbbb2e766.png)
yep, the first 100 runs or so are screwed, and as a result the 5x method is measured as ~4.75x. To deal with it first runs should be thrown away. 

Huge warmup, huge run count... and a simpliest possible benchmark takes 30 seconds to run. Looks like a trouble if you do want to have hundreds of perf tests.
## Part 2: What can I do with it?

Well, simpliest answer: do not use appveyor as a perftest runner.

Yep, this works. Our local CI server:
graph:
![local_ci](https://cloud.githubusercontent.com/assets/11225241/15928690/1640f042-2e51-11e6-8a9b-fb4ec5a56633.png)

10 samples:
![local_ci_table_10rows](https://cloud.githubusercontent.com/assets/11225241/15929209/5456c7aa-2e54-11e6-828c-c064ca29ec1e.png)

all samples:
![local_ci_table](https://cloud.githubusercontent.com/assets/11225241/15929098/7e6166fa-2e53-11e6-9d7a-21ae9f86f450.png)

Anything else? I don't know. Any ideas are welcome.
## P.S. Proofs:

[Repo](https://github.com/ig-sinicyn/TimingsAccuracy)
[Appveyor build](https://ci.appveyor.com/project/ig-sinicyn/timingsaccuracy/build/artifacts) (timings are in Report.csv artifact).
[Excel file](https://github.com/PerfDotNet/BenchmarkDotNet/files/306845/Data.zip) with plots and tables (change the values in the Rows column to count statistics over these rows).

**Comment by ig-sinicyn** [comment]
**UPD**

Well, turns out the problem with timings is actual for benchmarks being run on notebooks too. Almost same distribution.

HW info:
```
BenchmarkDotNet=v0.9.7.0
OS=Microsoft Windows NT 10.0.10586.0
Processor=Intel(R) Core(TM) i7-3537U CPU 2.00GHz, ProcessorCount=4
Frequency=2435884 ticks, Resolution=410.5286 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1080.0
```

statistics:
```
* Baseline:
Mean = 2,162.7803 us, StdError = 3.9902 us (0.18%); N = 1000, StdDev = 126.1802 us
Min = 1,945.4000 us, Q1 = 2,086.5000 us, Median = 2,105.3500 us, Q3 = 2,201.6000 us, Max = 2,951.2000 us
IQR = 115.1000 us, LowerFence = 1,913.8500 us, UpperFence = 2,374.2500 us
ConfidenceInterval = [2,154.9596 us; 2,170.6010 us] (CI 95%)

* X2:
Mean = 4,339.3244 us, StdError = 7.9395 us (0.18%); N = 1000, StdDev = 251.0702 us
Min = 3,980.0000 us, Q1 = 4,184.1000 us, Median = 4,242.3500 us, Q3 = 4,387.1000 us, Max = 6,042.9000 us
IQR = 203.0000 us, LowerFence = 3,879.6000 us, UpperFence = 4,691.6000 us
ConfidenceInterval = [4,323.7629 us; 4,354.8859 us] (CI 95%)

* X2-2:
Mean = 4,335.9687 us, StdError = 7.8382 us (0.18%); N = 1000, StdDev = 247.8661 us
Min = 3,957.9000 us, Q1 = 4,179.5000 us, Median = 4,244.2000 us, Q3 = 4,395.5000 us, Max = 6,329.9000 us
IQR = 216.0000 us, LowerFence = 3,855.5000 us, UpperFence = 4,719.5000 us
ConfidenceInterval = [4,320.6058 us; 4,351.3316 us] (CI 95%)

* X2-3:
Mean = 4,385.8243 us, StdError = 8.0026 us (0.18%); N = 1000, StdDev = 253.0657 us
Min = 3,939.4000 us, Q1 = 4,194.9000 us, Median = 4,301.7000 us, Q3 = 4,493.8000 us, Max = 5,705.5000 us
IQR = 298.9000 us, LowerFence = 3,746.5500 us, UpperFence = 4,942.1500 us
ConfidenceInterval = [4,370.1391 us; 4,401.5095 us] (CI 95%)

* X5:
Mean = 10,863.1799 us, StdError = 15.7957 us (0.15%); N = 1000, StdDev = 499.5055 us
Min = 10,079.2000 us, Q1 = 10,546.4000 us, Median = 10,694.8000 us, Q3 = 11,019.6000 us, Max = 13,171.3000 us
IQR = 473.2000 us, LowerFence = 9,836.6000 us, UpperFence = 11,729.4000 us
ConfidenceInterval = [10,832.2202 us; 10,894.1396 us] (CI 95%)
```

Timings plot: 
![timings-nb](https://cloud.githubusercontent.com/assets/11225241/15977055/910fef3c-2f67-11e6-9d46-502658995560.png)

[Excel file with results](https://github.com/PerfDotNet/BenchmarkDotNet/files/309665/Data.Notebook.xlsx)


Looks like the percentile is not a best metric for microbenchmarks. Ok, will try CI instead. 

Also, what about including something like plots above into bench.net output? Will be a great thing especially for IO-bound benchmarks.

**Comment by ig-sinicyn** [comment]
**UPD2**

Whoops, my bad. The samples should be sorted by duration. This way all fine, the timings from notebook are the following:
![timings_good](https://cloud.githubusercontent.com/assets/11225241/15987397/b70f1160-3037-11e6-9133-d1400b621e28.png)

Now it's obvious that I should use two metrics, one for lower and one for upper boundary to describe best and worse cases for the perftest. 

One more vote to include the plot like this into benchmark output.

**Comment by mattwarren** [comment]
> One more vote to include the plot like this into benchmark output.

We already have the [`RPlotExporter`](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Exporters/RPlotExporter.cs) that produces nice graphs. If it doesn't give you exactly the graphs you want, it would always be extended to make them

**Comment by AndreyAkinshin** [comment]
I think, we need some good math here. The Scaled value shouldn't be just a Median1/Median2. It should be a result of comparison of two distributions. In this case, we will be able to run performance tests based on our new metric. Unfortunately, benchmark distributions are not normal, so, we can't apply usual statistic here. I'll be looking for a good formula for our situation.

**Comment by mattwarren** [comment]
> Unfortunately, benchmark distributions are not normal, so, we can't apply usual statistic here. I'll be looking for a good formula for our situation.

Will #185 help?

**Comment by ig-sinicyn** [comment]
@mattwarren I'm not sure this will work.

The distribution of the benchmark timings is not normal, therefore all T-test-based checks will lie.
(X - time in Ns, Y - count of samples)
![distr](https://cloud.githubusercontent.com/assets/11225241/16114121/4a2f43a0-33c8-11e6-9922-49d09e2a0a85.png)

The best approach I was able to find is to collect `benchmark / baseline` timing ratio for each sample and to count CI from the ratios.

Yep, this is silly and naive but it provides most accurate results so far. I'm going to use it until will find something better.

**Comment by adamsitnik** [comment]
Closing the issue, as it's a very old discussion ;)
