### ISSUE TITLE
MemoryDiagnoser has no output

### ISSUE THREAD

**Issue by ekutukcu** [dotnet/BenchmarkDotNet#2048]
Hello,

I've been trying to get a memory diagnostic of a program at work but couldn't get it to output anything. From what I can tell this is how the `MemoryDiagnoser` is supposed to work but I've played with the configuration a lot to no avail. 

Reproduction:
1. Create a new .net 6.0 project and add the latest `BenchmarDotNet` and `BenchmarkDotNet.Annotations` packages.
2. In `Program.cs` paste this code:
```using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Columns;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Diagnosers;
using BenchmarkDotNet.Loggers;

namespace MemoryDiagnoserIssue
{
    public class Program
    {
        public static void Main(string[] args)
        {
            RunBenchmarks();
        }

        public static void RunBenchmarks()
        {
            var config = new ManualConfig()
                .AddDiagnoser(new MemoryDiagnoser(new MemoryDiagnoserConfig(true)))
                .AddLogger(ConsoleLogger.Default)
                .AddColumn(TargetMethodColumn.Method, StatisticColumn.Median, StatisticColumn.StdDev,
                    StatisticColumn.Q1, StatisticColumn.Q3, new ParamColumn("Size"));
            BenchmarkDotNet.Running.BenchmarkRunner.Run<ExampleBenchmark>(config);

        }
    }

    [MemoryDiagnoser]
    [ShortRunJob]
    public class ExampleBenchmark
    {
        [Benchmark]
        public void Benchmark()
        {
            int[] x = new int[10000];
            for(int i = 0; i < x.Length; i++)
            {
                x[i] = i;
            }
        }
    }
}
```
3. Run the run the project.

Expected output, something like this:
`           Method |        Mean |     StdErr |      Median |  Gen 0 | Allocated |
----------------- |------------ |----------- |------------ |------- |---------- |
 'new int[40kB]' | 884.4896 ns | 46.3528 ns | 776.4237 ns | 0.1183 |     10 kB |`
 
Actual output:
```
// * Diagnostic Output - MemoryDiagnoser *


// ***** BenchmarkRunner: End *****
```

**Comment by adamsitnik** [comment]
Hi @ekutukcu 

First of all, I want to acknowledge that this behavior sucks.

`new ManualConfig()` creates a completely empty config:

https://github.com/dotnet/BenchmarkDotNet/blob/bd08722ee22fc25a0cf6d389125c5b6eff10cd8f/src/BenchmarkDotNet/Configs/ManualConfig.cs#L234-L238

If no column providers are defined, BDN prints a warning:

![image](https://user-images.githubusercontent.com/6011991/180381027-dc89de27-acae-4634-88fe-028938e1469f.png)

But in your case, you define some columns and hence don't get the warning.

You can use the `CreateMinimumViable` method:

https://benchmarkdotnet.org/changelog/v0.13.0.html#new-api-manualconfigcreateminimumviable

```diff
- new ManualConfig()
+ ManualConfig.CreateMinimumViable
```

or specify the default column providers:

```diff
+ .AddColumnProvider(DefaultColumnProviders.Instance)
```

and then the `MemoryDiagnoser` columns gets displayed, but so are `Mean`, `Error`, `StdDev`. Which you might not want.

I'll take a look and see what it would take to fix it.

**Comment by ekutukcu** [comment]
Thank you that resolved it. I couldn't seem to find this in any of the documentation which I why I posted this issue.
