### ISSUE TITLE
BenchmarkDotNet crashing on Linux with DisassemblyDiagnoser

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/BenchmarkDotNet#2070]
Opening as per https://github.com/dotnet/BenchmarkDotNet/issues/2000#issuecomment-1203883513.

My configuration is:
Kubuntu 20.04
and the provided commands return:
```
xterm-256color


pl_PL.UTF-8
```
(the middle ones don't return anything)

**Comment by MichalPetryka** [comment]
`locale` returns:
```
LANG=pl_PL.UTF-8
LANGUAGE=pl:en_US
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
```

**Comment by adamsitnik** [comment]
@MichalPetryka the issue should got fixed with #2092. Could you please try `0.13.2.1892` and see if it did?

```xml
<packageSources>
  <add key="bdn-ci" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

**Comment by adamsitnik** [comment]
@bartonjs can still reproduce it

**Comment by adamsitnik** [comment]
The issue was partially resolved by @janvorli in #2123

@janvorli has identified a bug in DAC, which will be resolved in dotnet/runtime (calling one of the CLRMD methods ends up with AV while it should not). Since there is nothing actionable on BDN side, I am going to close it. Thank you!

**Comment by ezhevita** [comment]
@adamsitnik hello and sorry for bothering – could you please link an upstream runtime issue to track? Thanks!

**Comment by adamsitnik** [comment]
> could you please link an upstream runtime issue to track?

@janvorli do you have a link to the DAC issue/PR?

**Comment by janvorli** [comment]
@ezhevita, @adamsitnik  I've just created a PR with a fix: https://github.com/dotnet/runtime/pull/79824

**Comment by janvorli** [comment]
Actually, I need to do it differently. In the code review, I was reminded why we don't handle hardware exceptions in the mscordac core - it doesn't always work. But there is a different way that we can use and I am going to make such fix.

**Comment by janvorli** [comment]
The different fix was just merged in https://github.com/dotnet/runtime/pull/79846
