### ISSUE TITLE
BenchmarkDotNet has failed to build the auto-generated boilerplate code.

### ISSUE THREAD

**Issue by MichielVanGasse** [dotnet/BenchmarkDotNet#2077]
Cant seem to get the BenchmarkDotNet working with a console aplication running on net6.0.

Output in the console:
Standard error:
BenchmarkDotNet.Autogenerated.csproj(32,43): error MSB4025: The project file could not be loaded. An error occurred while parsing EntityName. Line 32, position 43.

// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in \bin\Release\net6.0\
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html

**Comment by adamsitnik** [comment]
> BenchmarkDotNet.Autogenerated.csproj(32,43): error MSB4025: The project file could not be loaded. An error occurred while parsing EntityName. Line 32, position 43.

Could you please share the content of the project file?

**Comment by MichielVanGasse** [comment]
Thanks for the response. 
Here is the project: [github link](https://github.com/MichielVanGasse/Benchmark)
It's just a new basic project trying to get it to work.

**Comment by adamsitnik** [comment]
@MichielVanGasse it works on my machine ;)

```cmd
git clone https://github.com/MichielVanGasse/Benchmark.git repro_bdn
cd .\repro_bdn\
dotnet run -c Release
```

![image](https://user-images.githubusercontent.com/6011991/186673655-87de9d35-c036-4696-965b-f3a55ba2c9bd.png)

Could you try to perform a clean build and try again?

**Comment by MichielVanGasse** [comment]
Clean and build/rebuild doesn't affect it. Also started new projects, always the same error.

![Error](https://user-images.githubusercontent.com/81804730/186682168-441aa448-e14f-4856-a647-0b824a4c2257.jpg)

**Comment by adamsitnik** [comment]
@MichielVanGasse Could you please share the content of the `BenchmarkDotNet.Autogenerated`  project file? I am interested in line 32

**Comment by MichielVanGasse** [comment]
Ah yes there was a symbol in my directory, that's why I've got this warning.
After removing it no more error in the auto-generated boilerplate code and it runs perfect.

Thanks for the help Adam!
Problem solved. ;)
