### ISSUE TITLE
Troubles with MemoryDiagnoserTests

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#208]
Subject: https://ci.appveyor.com/project/PerfDotNet/benchmarkdotnet/build/0.9.7.11/tests

@mattwarren, can you take a look?

**Comment by mattwarren** [comment]
yeah, np

**Comment by adamsitnik** [comment]
We no longer test ETW based Diagnoser, so the problems whatever they were are gone ;)
