### ISSUE TITLE
Update SDK to .NET 7

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#2080]
We have a test that ensure that latest NativeAOT is supported:

https://github.com/dotnet/BenchmarkDotNet/blob/c165ba17501626561297a80fe1b05b2400ce8014/tests/BenchmarkDotNet.IntegrationTests/NativeAotTests.cs#L18

Recently it got broken because we can't build a `net6.0` app using .NET 7 NativeAOT bits:

```log
 Unable to optimize assemblies for Ahead of time compilation: a valid runti
me package was not found. Either set the PublishAot property to false, or use a supported runtime identifier when publishing. When targeting .NET 7 or higher, make sure to restore packages with the PublishAot property set to true.
```

So as soon as .NET 7 SDK is shipped, we should just update our CI to use it.

cc @MichalStrehovsky

**Comment by adamsitnik** [comment]
At the time of doing this, we should remove the support for old experimental packages (from the old CoreRT `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json` feed)

**Comment by timcassell** [comment]
Looks like this is already done since https://github.com/dotnet/BenchmarkDotNet/commit/61b3c56d94a4f6f014bb58686f2f19f9268f99cb, right @adamsitnik?

**Comment by adamsitnik** [comment]
@timcassell that is correct, thanks for catching it!
