### ISSUE TITLE
Running on Linux leaves terminal colors changed

### ISSUE THREAD

**Issue by bartonjs** [dotnet/BenchmarkDotNet#2088]
After running BDN on Linux I see my terminal colors modified.

SSH via PuTTY with xterm, .NET 6, BDN 0.13.2, Ubuntu 18.04.  (Similar results were seen with xterm-256color)

* A successful run leaves the foreground color as yellow.
* A filter that has no matches, and no suggestions, leaves the foreground color as red.
* A filter that has no matches, and some suggestions, seems to leave the foreground color alone.
* Using `[DisassemblyDiagnoser]`, which yields `Unknown Acknowledgment` failures, leaves the foreground color as yellow.
* The benchmark throwing an exception leaves the foreground color as yellow.

It's hard to say how many of those yellows are the same, of course.

Filter mismatch:
![image](https://user-images.githubusercontent.com/10642668/186956602-2f93beb5-b3f6-4968-ba2a-88844d52dba7.png)

Successful run start:
![image](https://user-images.githubusercontent.com/10642668/186957111-a9fac68a-040e-436e-af27-e8209e698023.png)

Successful run end:
![image](https://user-images.githubusercontent.com/10642668/186957290-db607b09-62e9-4035-809d-c5dcfcd2d378.png)

**Comment by bartonjs** [comment]
Looking at the pictures again... it may be "the terminal foreground becomes whatever color was the first one written"

**Comment by MichalPetryka** [comment]
The `Unknown Acknowledgment` error is #2070

**Comment by adamsitnik** [comment]
Hint for potential contributor who wants to work on it: we revert the colors here:

https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/src/BenchmarkDotNet/Loggers/ConsoleLogger.cs#L44-L58

and this is most likely the part of the code that needs to be fixed.

**Comment by farQtech** [comment]
I would like to work on this. please assign it to me.

**Comment by adamsitnik** [comment]
> I would like to work on this. please assign it to me.

@farQtech done! Please let me know if you need any help

**Comment by farQtech** [comment]
Sure @adamsitnik , thanks!!

**Comment by farQtech** [comment]
Hi @adamsitnik sorry for the delay, raised PR #2160 to fix above problem. I think it would be better if we restore ForegroundColor to it's original value once we are done

**Comment by adamsitnik** [comment]
Fixed by #2160, thanks a lot @farQtech !
