### ISSUE TITLE
Provide way to avoid command line parameters

### ISSUE THREAD

**Issue by danmoseley** [dotnet/BenchmarkDotNet#2091]
Often I just want all my benchmarks to run. Eg., I just made a simple benchmark in VS and have `static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);`) and some method marked `[Benchmark]` and hit Ctrl-F5.

This will stop and ask me which benchmarks to run (even if there's only one benchmark) because a filter, attribute names, or categories list is required for BDN to run. So I have to go edit the VS launch profile to add `--filter **` (something a new person has to know)

If the default can't be changed to run all benchmarks, what about adding a way in code to indicate I just want all benchmarks to run (declarative or imperative is fine)?

**Comment by YegorStepanov** [comment]
Pass args without "benchmark switcher/selection". (all benchmarks are selected)
```C#
BenchmarkRunner.Run(typeof(Program).Assembly, args: args);
```

or You can inline BDN cmd options in the code:
```C#
BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args: "--filter **".Split());
```

**Comment by danmoseley** [comment]
Thanks @YegorStepanov , just figured that out!
