### ISSUE TITLE
Invalid NativeAOT link in the 0.13.2 changelog

### ISSUE THREAD

**Issue by KeterSCP** [dotnet/BenchmarkDotNet#2103]
[Pre-requisites](https://github.com/dotnet/BenchmarkDotNet/blob/8514b239fea5939f888df2f976d4763a978b5784/docs/_changelog/header/v0.13.2.md?plain=1#L59) link does not work

**Comment by adamsitnik** [comment]
@KeterSCP could you please send a PR with a fix?

**Comment by KeterSCP** [comment]
Sure, but which file should it point to? Is it one from the [compiling section](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#prerequisites)? Or from the [runtimelab](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/prerequisites.md)?

**Comment by adamsitnik** [comment]
@KeterSCP Based on the removed file history I think the new link should point to https://docs.microsoft.com/en-us/dotnet/core/deploying/native-aot/#prerequisites

Thanks!
