### ISSUE TITLE
Tests Just Stop Running During Run

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#2125]
This issue seems to be back where while running a benchmark test, my console app just disappears. No error, nothing even in the BDN log (see below). It seems to be happening randomly, meaning different classes and different methods. Just a week or so ago, they were working fine.

I do have a try/catch set up in the main method. I do have it configured too:

config.WithOption(ConfigOptions.DisableOptimizationsValidator, true)
  .WithOption(ConfigOptions.StopOnFirstError, true);

But I am not seeing anything. The project targets .NET 6 & 7 and I am using BenchmarkDotNet version 0.13.2.1913.

I did find two events in the Event Log that I have attached below.

[dotNetTips.CodePerf.Example.App.BenchmarkTests.CollectionLinqBenchmark-20220927-183242.log](https://github.com/dotnet/BenchmarkDotNet/files/9668922/dotNetTips.CodePerf.Example.App.BenchmarkTests.CollectionLinqBenchmark-20220927-183242.log)

[BenchmarkDotNet.zip](https://github.com/dotnet/BenchmarkDotNet/files/9668970/BenchmarkDotNet.zip)

**Comment by adamsitnik** [comment]
Hi @RealDotNetDave 

I took a look at your log:

![image](https://user-images.githubusercontent.com/6011991/194071424-01f2e18f-c1eb-4c36-bcc7-d25161779aae.png)

Initially I thought that you have hit a bug in .NET.

This call:

https://github.com/dotnet/runtime/blob/dd96637244dbf840a54e08d17606ded0eb17f39e/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/BufferedFileStreamStrategy.cs#L523

calls https://github.com/dotnet/runtime/blob/dd96637244dbf840a54e08d17606ded0eb17f39e/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/BufferedFileStreamStrategy.cs#L990

which most likely got inlined when performing

https://github.com/dotnet/runtime/blob/dd96637244dbf840a54e08d17606ded0eb17f39e/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/OSFileStreamStrategy.cs#L236

and creating the span has thrown:

https://github.com/dotnet/runtime/blob/dd96637244dbf840a54e08d17606ded0eb17f39e/src/libraries/System.Private.CoreLib/src/System/ReadOnlySpan.cs#L75-L78

But I've searched for the thing that called it:  [AsyncStreamReader.FlushMessageQueue](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs). It's the thing that is internally used to read process input. It's running on a separate thread and using something that is not thread safe. I'll send a fix for that soon.
