### ISSUE TITLE
Add ability to force-ignore individual invocations

### ISSUE THREAD

**Issue by BalassaMarton** [dotnet/BenchmarkDotNet#2130]
Currently, if an invocation throws an exception, the whole benchmark is thrown out. I'm using BDN to benchmark code that calls out to network services that are sometimes non-responsive. Unfortunately, this happens so often that I can't run a benchmark project without catching at least one `TimeoutException`. I can swallow these exceptions and hope for BDN to remove the invocation as an outlier, but it would be nice to have some built-in mechanism, either a special exception or a static method I can call like this:

```cs
try 
{
    // ...
}
catch (TimeoutException)
{
    BenchmarkRunner.IgnoreCurrentInvocation();
    return;
}
```

**Comment by adamsitnik** [comment]
Hi @BalassaMarton 

We had similar request in the past and decided not to implement it. Please see #373 for details.

**Comment by BalassaMarton** [comment]
Actually, I remembered that we had this conversation before, but couldn't find it (@mbatms is also me) :) Maybe I should use a profiler instead for this kind of measurement where I want to control what to include and what to ignore on the method call level.
