### ISSUE TITLE
--filter should include argument/params names

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#2131]
Currently the filter provided with `--filter` is applied only to `namespace.typeName.methodName`. It should be applied to full benchmark ID, which includes argument and parameter values, as it's currently impossible to run a single benchmark when it has multiple test cases.

Requirements:
- to remain backward compatibility, using `namespace.typeName.methodName` without an asterisk at the end should still run all benchmarks for given method (treated as `namespace.typeName.methodName*`)
- hints that are printed when filter returns no benchmarks to run should be fixed as well, the person who is willing to work on it can take a look at https://github.com/dotnet/BenchmarkDotNet/pull/1644 to see what was needed in the past to fix the suggestions

Some hints:
- the code lives here: https://github.com/dotnet/BenchmarkDotNet/blob/a78c2e6a6e3db79069fb5bbbd6da6e5cbea8c029/src/BenchmarkDotNet/Filters/GlobFilter.cs#L19
- it should be using https://github.com/dotnet/BenchmarkDotNet/blob/a78c2e6a6e3db79069fb5bbbd6da6e5cbea8c029/src/BenchmarkDotNet/Exporters/FullNameProvider.cs#L50

**Comment by blouflashdb** [comment]
I would like to work on this please.
