### ISSUE TITLE
BenchmarkDotNet.Templates not showing in VS2022(17.3.6) new project dialog

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/BenchmarkDotNet#2149]
Similar question (https://developercommunity.visualstudio.com/t/net-cli-templates-in-visual-studio-missing/1508502), might be helpful to solve this problem, but I can't do anything about it.

**Comment by melias** [comment]
@adamsitnik  Could I help with this?

**Comment by adamsitnik** [comment]
@melias yes of course! The problem is that I am not familiar with the templates myself so I there is very little help I can provide with this issue.

**Comment by melias** [comment]
@adamsitnik I did some modifications on template.json and still don't know how I'll test that.
Have you any idea?

**Comment by adamsitnik** [comment]
@melias to be honest I don't. You can just focus on #1799 and I can unassign you from this one (unless you want to keep digging into the templates)
