### ISSUE TITLE
Command Line Arguments

### ISSUE THREAD

**Issue by ardalis** [dotnet/BenchmarkDotNet#2156]
I'm trying to launch a benchmark run from a .NET 6 console app. I'm pulling in connection information (server and port) using command line arguments so that I can easily reuse the application between environments (rather than hard-coding server IP addresses, etc. in the code). However, even when I set the values from the command line to static variables, they are not set during my benchmark runs. Is there a way to do this?

An option I'm considering is to put the environment-specific values into a config file and read that within the benchmarked method. I don't like this as well but it would let me keep the server details out of the source code. Is there a better way to accomplish this goal that's idiomatic for BenchmarkDotNet? Thanks in advance!

**Comment by adamsitnik** [comment]
Hi @ardalis 

BDN runs every benchmark in a dedicated, stand-alone process, that is why setting static fields does not work.

You can pass them via environment variables:

```cmd
--envVars firstKey:firstValue secondKey:secondValue
```

Console app that defines benchmarks needs to pass the `args` to the `BenchmarkSwitcher`:

```cs
public static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);
```

And then you can read the env var in `[GlobalSetup]` method:

```cs
[GlobalSetup]
public void GlobalSetup()
{
    string value = System.Environment.GetEnvironmentVariable("key");
    // the rest of the logic goes here
}
```

**Comment by ardalis** [comment]
Awesome, thanks for the quick response! I'll give it a shot.

**Comment by ardalis** [comment]
Hi @adamsitnik thanks again for your help. I can't seem to get the env vars into my benchmark. Is there something obvious I'm missing?

![image](https://user-images.githubusercontent.com/782127/197052698-cddefbbf-3d2d-4273-8f14-062585bed975.png)

The constants are defined like this:

```csharp
public static class Constants
{
  public const string REDIS_SERVERS = "REDIS_SERVERS";
  public const string READ_RATIO = "READ_RATIO";
  public const string WRITE_COUNT = "WRITE_COUNT";
  public const string PAYLOAD_BYTES = "PAYLOAD_BYTES";
  public const string SOSS_SERVERS = "SOSS_SERVERS";
}
```

**Comment by timcassell** [comment]
@ardalis Try removing the quotes.

**Comment by ardalis** [comment]
@timcassell good ideas, but neither changes the behavior. I only added the quotes because I saw some code like this and it made me think perhaps the comma-separated values in my env vars were a problem:

![image](https://user-images.githubusercontent.com/782127/197055420-d98cbc75-d0d2-4e3e-8ae5-3eb2c65d8a6e.png)

But the behavior is the same with or without quotes.

**Comment by timcassell** [comment]
I think the issue is that the key:value is separated by `:`, and you have `:` in your value. Can you change that to something else? https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration&view=aspnetcore-3.1#environment-variables recommends changing it to `__` (double underscore).

**Comment by ardalis** [comment]
Oh that's a good catch. Using `:` to separate server:port is pretty standard but I can probably use something else and then unescape it in my code. Let me try that.

**Comment by ardalis** [comment]
Nope. :(
![image](https://user-images.githubusercontent.com/782127/197057402-616ba805-f1d3-40e8-ab06-9b09d4ff37b3.png)

**Comment by ardalis** [comment]
Also posted to SO since that's probably a better place for this at this point: https://stackoverflow.com/questions/74146160/reading-environment-variables-in-benchmarkdotnet

**Comment by timcassell** [comment]
Also you have an extra `--`. Remove that from `-- --envVars`.

**Comment by ardalis** [comment]
Isn't that needed to pass the values my app instead of to `dotnet` ? Trying it anyway...

**Comment by ardalis** [comment]
No dice. 
![image](https://user-images.githubusercontent.com/782127/197058209-7b0dd5ff-2b4d-4827-b3a2-5ca7e11bdec8.png)

**Comment by ardalis** [comment]
Fixed!

Apparently the issue was my use of `[ReturnValidator]` which is covered by this open issue:
https://github.com/dotnet/BenchmarkDotNet/issues/2083
