### ISSUE TITLE
ManualConfig has exporters defined, while it should not have any

### ISSUE THREAD

**Issue by JohannesDeml** [dotnet/BenchmarkDotNet#2157]
BenchmarkDotNet version: 0.13.2
OS: Windows 10
Reference repository: https://github.com/JohannesDeml/MicroBenchmarksDotNet

When running the following simple benchmark:
```
public static class Program
{
	private static int Main(string[] args)
	{
		return BenchmarkSwitcher
			.FromAssembly(typeof(Program).Assembly)
			.Run(args)
			.ToExitCode();
	}
}

[Config(typeof(ManualConfig))]
public class _TestBenchmark
{
	[Benchmark]
	public int InstantReturn()
	{
		return 0;
	}
}
```

I get the following exporter output:
```
// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\MicroBenchmarks._TestBenchmark-report.csv
  BenchmarkDotNet.Artifacts\results\MicroBenchmarks._TestBenchmark-report-github.md
  BenchmarkDotNet.Artifacts\results\MicroBenchmarks._TestBenchmark-report.html
```

This is very much unexpected for me (and I think this also was not the case for the version 0.12.x). If I use a `ManualConfig` or and inheritor from it, I want to start defining it from the ground up, as I do [here](https://github.com/JohannesDeml/MicroBenchmarksDotNet/blob/main/MicroBenchmarks.Extensions/DefaultBenchmarkConfig.cs). However with this setup I now get warnings, that multiple exporters are defined, since apparently some default exporters are added.

Was this behavior added on purpose?

**Comment by adamsitnik** [comment]
Hi @JohannesDeml !

When the user does not provide any config instance to `BenchmarkSwitcher.Run`, a default config is being used:

https://github.com/dotnet/BenchmarkDotNet/blob/28bf214dee0b1f6937851e6f1d09f1f5ae133df1/src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs#L77

which later gets merged with config applied by your attribute.

What you need is to pass an instance of `ManualConfig` to `BenchmarkSwitcher.Run`, I recommend you use https://github.com/dotnet/BenchmarkDotNet/blob/28bf214dee0b1f6937851e6f1d09f1f5ae133df1/src/BenchmarkDotNet/Configs/ManualConfig.cs#L265-L268

```diff
public static class Program
{
	private static int Main(string[] args)
	{
+		var config = ManualConfig.CreateMinimumViable();

		return BenchmarkSwitcher
			.FromAssembly(typeof(Program).Assembly)
+			.Run(args, config)
			.ToExitCode();
	}
}
```

**Comment by JohannesDeml** [comment]
Ah, I see! That makes a lot of sense, thanks a lot for the quick answer @adamsitnik !
Commit fix: https://github.com/JohannesDeml/MicroBenchmarksDotNet/commit/35720bfc0d3a49ec0eff26c6af05777e56238af8
