### ISSUE TITLE
ctrl+c causes crash

### ISSUE THREAD

**Issue by timcassell** [dotnet/BenchmarkDotNet#2159]
It doesn't happen 100% of the time, but it happens often enough. I believe it's caused by the child process not killed gracefully, but it's hard to say. We can hook into `Console.CancelKeyPress` event, so we should be able to gracefully kill the child process instead of it crashing.

**Comment by adamsitnik** [comment]
> We can hook into Console.CancelKeyPress event, so we should be able to gracefully kill the child process instead of it crashing.

We are already doing that, but I am open to any improvements in this space

**Comment by adamsitnik** [comment]
[ConsoleExitHandler](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Helpers/ConsoleExitHandler.cs) is responsible for doing that and it's being used in all executors: https://github.com/dotnet/BenchmarkDotNet/search?q=ConsoleExitHandler

I currently don't see way to improve it so I am going to close the issue, but please feel free to send a PR and prove me wrong ;)

**Comment by timcassell** [comment]
I see, it just calls `process.KillTree()`. I couldn't tell what the actual error is, but I'm guessing the child process still tries to communicate with the host process during the shutdown. Could we disconnect the pipe before killing the process? Would that do anything? Or is that already supposed to safely handle this kind of situation?
