### ISSUE TITLE
Enable Github Discussions

### ISSUE THREAD

**Issue by timcassell** [dotnet/BenchmarkDotNet#2165]
Can the `Discussions` section be opened up? I feel some things I want to discuss aren't worthy of `Issue` status, and some discussions clog up issues and PRs (like in #2114 and #2111).

**Comment by AndreyAkinshin** [comment]
@timcassell thanks for the suggestion! The GitHub Discussions are enabled now:
https://github.com/dotnet/BenchmarkDotNet/discussions
