### ISSUE TITLE
broker.ProcessData() hangs if something wrong is the spawned process

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#2189]
Let us a consider a job with invalid configuration on the current platform. For example, let us run the following benchmark on mac M1:

```cs
public class Bench
{
    [Benchmark] public void Foo() => Thread.Sleep(10);
}

BenchmarkRunner.Run<Bench>(DefaultConfig.Instance.AddJob(Job.Default.WithPlatform(Platform.X64)));
```

In this case, BenchmarkDotNet hangs in `BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute` on `broker.ProcessData()`.

@adamsitnik do you have any thoughs on solving this problem?

**Comment by YegorStepanov** [comment]
Looks like we need to check for any invalid configuration properties in `IToolchain.Validate`

https://github.com/dotnet/BenchmarkDotNet/blob/64c3a3cb4ad4057b6065a2783a4b333206f8b5e5/src/BenchmarkDotNet/Toolchains/Toolchain.cs#L31-L43

**Comment by AndreyAkinshin** [comment]
@YegorStepanov, you are right, we should improve our validators. However, we also need a reliable defense agains hanging behavior in the case if validators failed to detect invalid configurations.
