### ISSUE TITLE
Continous benchmark executions slows down the more benchmarks were run

### ISSUE THREAD

**Issue by DevDrake** [dotnet/BenchmarkDotNet#2197]
Hello,

I am using version 0.13.2 with dotnet fw 4.8 to benchmark wpf control creation.
Benchmark uses MemoryDiagnoser, MemoryRandomizer, STAThread
to create many benchmarks i use Params (two ints) and ParamsSource (a static array of static data)
i run benchmark:
`public static void Main(params string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args, new DebugInProcessConfig());`

I noticed that consecutive benchmarks run slower and slower. This happens to the point that benchmark 50th+ benchmark takes around 10 secs for every workload actual, that from <ops>*<exec time> should take ~1 sec, and this continues to creep,

Benchmarks that supposed to take 1h, takes more than 4h.

**Comment by DevDrake** [comment]
There is also a problem that later benchmarks have weird results
e.g. the same function and conditions tested in big benchmark suits (~60 different runs) give different results when run in small (4 different runs) benchmark suite. 
The difference is huge, and it's repeatable (few big benchmark suits are consistent to each other and small benchmark suite is consistent to each other, but for the same functions produces different results ~x4 times difference)

**Comment by adamsitnik** [comment]
> I noticed that consecutive benchmarks run slower and slower.
> DebugInProcessConfig

By default, BDN runs every benchmark in a dedicated, stand-alone process. This helps us to avoid one benchmark affecting other (example: memory leak). In your case you are using the config that runs all benchmarks within the same process (`DebugInProcessConfig`). It seems that your benchmarks have side effects, and they are affecting each other. You need to use a profiler to find out what is happening.

**Comment by DevDrake** [comment]
Thanks Adam, Indeed my code may have some side effects which would explain consistent difference between big benchmarks and small benchmarks.
However is it expected that "workload actual" to be executed many times longer than reported time of its execution ?

**Comment by adamsitnik** [comment]
> However is it expected that "workload actual" to be executed many times longer than reported time of its execution ?

In the Pilot stage, BDN chooses how many times given benchmark should be executed per single iteration. In the Workload Actual it runs the benchmarks until the results become stable (things like standard error are low). If your code takes longer and longer to run, the heuristic is not stopping as the results are not stable and it might execute up to 100 iterations (this can be configured).

https://benchmarkdotnet.org/articles/guides/how-it-works.html
