### ISSUE TITLE
Is there any method to execute GlobalSetup and GlobalCleanup only once? 

### ISSUE THREAD

**Issue by chenxyzl** [dotnet/BenchmarkDotNet#2198]
``` c#
class IncUpdateBenchmark {
    [Benchmark]
    [Arguments(10 * 1024)]
    [Arguments(100 * 1024)]
    [Arguments(500 * 1024)]
    [Arguments(1024 * 1024)]
    public void BenchmarkInsert(int dataSize){}
    
    [GlobalSetup]
    public void GlobalSetup(){}
    [GlobalCleanup]
    public void GlobalCleanup(){}
}
```
In this test GlobalSetup and GlobalCleanup will run more than one times;
bug i want to run it only once;

**Comment by YegorStepanov** [comment]
As far as I know there is no convenient way to do this.

#### 1) Move the first and last arguments to const fields and compare to them in the global setup and cleanup accordingly 
#### 2) A more generic version (you can move the ugly code to the helper class). This works if you do not have duplicates.
<details>

```C#
[Params(2, 4, 6)]
public int dataSize;

[GlobalSetup]
public void GlobalSetup()
{
    var firstValue = (GetType().GetField(nameof(dataSize))
            .GetCustomAttribute(typeof(ParamsAttribute)) as ParamsAttribute)
        .Values[0];

    if ((int)firstValue != dataSize)
        return;

    //todo
}

[GlobalCleanup]
public void GlobalCleanup()
{
    var lastValue = (GetType().GetField(nameof(dataSize))
            .GetCustomAttribute(typeof(ParamsAttribute)) as ParamsAttribute)
        .Values.Last();

    if ((int)lastValue != dataSize)
        return;

    //todo
}

[Benchmark] public void Benchmark() { }
```
</details>
The version for `ParamSourceAttribute` is simpler, but `GetDataSizes()` must have a deterministic result.
<details>

```C#
[ParamsSource(nameof(GetDataSizes))]
public int dataSize;

public IEnumerable<int> GetDataSizes()
{
    //write "global setup" here
    yield return 10 * 1024;
    yield return 100 * 1024;
}

[GlobalSetup]
public void GlobalSetup()
{
    if (GetDataSizes().First() != dataSize)
        return;
    
    //todo
}

[GlobalCleanup]
public void GlobalCleanup()
{
    if (GetDataSizes().Last() != dataSize)
        return;

    //todo
}
```
</details>

#### 3) When you need only a global setup
<details>

```C#
public IEnumerable<int> GetDataSizes()
{
    //write "global setup" here
    yield return 10 * 1024;
    yield return 100 * 1024;
}

[Benchmark]
[ArgumentsSource(nameof(GetDataSizes))]
public void Method(int dataSize)
{
}
```
</details>

#### 4) You can write benchmark index to the file in and compare by them. The hardest way.

**Comment by timcassell** [comment]
Are you running your benchmarks in-process? By default, benchmarks are ran in a separate process, and each argument you have constitutes a separate benchmark. GlobalSetup/Cleanup are ran once _per benchmark_. It wouldn't make sense to only run it once when each benchmark is ran in a separate process.

Also, even if you are running in-process, a new benchmark class object is created for each benchmark, so the only way to not run duplicate setups is if you store your results in a static field then check to see if it's already set. You can use @YegorStepanov's idea to only run the cleanup once:

```cs
if (GetDataSizes().Last() != dataSize)
    return;
```

(Though I would prefer to use a static counter.)

**Comment by YegorStepanov** [comment]
@timcassell Are there any cons of `InProcessEmitToolchain` over the "standard" approach?

**Comment by timcassell** [comment]
> @timcassell Are there any cons of `InProcessEmitToolchain` over the "standard" approach?

Only if the benchmarks produce side-effects (which is kind of what the OP is trying to do here). see #2197
