### ISSUE TITLE
Setting affinity does not work for Environment.ProcessorCount >= 32

### ISSUE THREAD

**Issue by Donis-** [dotnet/BenchmarkDotNet#2211]
https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Extensions/ProcessExtensions.cs#L48

`int cpuMask = (1 << Environment.ProcessorCount)`
becomes 0 for Environment.ProcessorCount >=32

This works:
`long cpuMask = (1L << Environment.ProcessorCount) - 1;`

**Comment by timcassell** [comment]
Affinity is a bit mask, so it will only work up to 64 cores? We already have processors with more threads than that...

**Comment by adamsitnik** [comment]
Fixed by #2228
