### ISSUE TITLE
Generated .notcs file has compile errors in Release configuration: 'BenchmarkDotNet.Engines' does not exist

### ISSUE THREAD

**Issue by tmbarker** [dotnet/BenchmarkDotNet#2214]
BenchmarkDotNet v0.13.2: Running some simple benchmarks works fine when the solution is using Debug configuration for all projects, however, when changing to Release configuration the benchmarks fail to run, as the generated `.notcs` file fails to compile.

Here is the error, which is that the `BenchmarkDotNet.Engines` namespace cannot be resolved:
```
// Build Error: Standard output: 
  
Standard error: 
MSBuild version 17.3.2+561848881 for .NET
...\bin\Release\net6.0\f4669d73-b4b6-4946-83e3-cec6ca11891a\f4669d73-b4b6-4946-83e3-cec6ca11891a.notcs(306,48): error CS0234: The type or namespace name 'Engines' does not exist in the namespace 'BenchmarkDotNet' (are you missing an assembly reference?) 
[...\bin\Release\net6.0\f4669d73-b4b6-4946-83e3-cec6ca11891a\BenchmarkDotNet.Autogenerated.csproj]
```

**Comment by adamsitnik** [comment]
Hi @tmbarker 

How do you reference `BenchmarkDotNet` NuGet package from the project that defines the benchmarks? I suspect that your project file might be doing it only for `DEBUG` config.

**Comment by tmbarker** [comment]
The solution structure is a little unconventional, but there is one project where the actual benchmarks are defined (i.e. methods with decorated the `Benchmark` attribute) which only has the `BenchmarkDotNet.Annotations/0.13.2` NuGet package imported, and then another project which actually runs the benchmarks (i.e. uses `BenchmarkRunner`) that has the `BenchmarkDotNet/0.13.2` package imported. 

Both of these packages are added using the "regular" flow  of managing NuGet packages in Rider IDE. Is there something I should be looking for which would indicate a package is only added for the `DEBUG` config?

**Comment by timcassell** [comment]
I was able to repro the issue, but I'm not sure how to fix it. It works fine in Full Framework because the default RoslynToolchain explicitly adds the assembly reference, while the default toolchain for Core (CsProjCoreToolchain) only adds the project reference, which in this case does not contain the BenchmarkDotNet reference.

**Comment by timcassell** [comment]
Also you said it works with Debug, I'm guessing you used the `DebugInProcessConfig` which just runs the benchmarks in process. I also tried it with `DebugBuildConfig` and it failed the same way.

**Comment by tmbarker** [comment]
@timcassell That is correct, I am passing a `DebugInProcessConfig` instance to `BenchmarkRunner.Run(...)`

**Comment by timcassell** [comment]
It may be a little heavy-handed, but you could fix the issue locally by explicitly adding BenchmarkDotNet reference in every csproj.

**Comment by tmbarker** [comment]
That's what I've done in the meantime, and I'm unblocked.

**Comment by adamsitnik** [comment]
> but you could fix the issue locally by explicitly adding BenchmarkDotNet reference in every csproj.

This is by design. Users always need to install main `BenchmarkDotNet` package.
