### ISSUE TITLE
Why is custom column not displayed in results

### ISSUE THREAD

**Issue by stevehjohn** [dotnet/BenchmarkDotNet#2215]
Hi,

I've created a custom column that I'd like to be shown in the benchmark results, but it is not being displayed. Any ideas what this might be please?

``` C#
var config = DefaultConfig.Instance;

config.AddColumn(new NameColumn());

BenchmarkRunner.Run<Benchmarks>(config);
```

`NameColumn` does implement `IColumn`.

Thanks,

Steve.

**Comment by YegorStepanov** [comment]
The config is immutable. All methods return a new config.
```diff
- config.AddColumn(new NameColumn());
+ config = config.AddColumn(new NameColumn());
```

We can add JetBrains `Pure` attribute to the immutable methods, but that doesn't work in Visual Studio.

Hmm, maybe write an analyzer for the [Pure] attribute so that it works in any IDE?

**Comment by stevehjohn** [comment]
I've worked around it now. 

Fair enough that the methods are immutable. Just a shame that to set up a new config with extra columns involves configuring all the things that should be there by default.

Happy to close this case if you like.

Thanks,

Steve.

**Comment by timcassell** [comment]
> Fair enough that the methods are immutable. Just a shame that to set up a new config with extra columns involves configuring all the things that should be there by default.

What do you mean? You have the default config to add to.

```cs
var config = DefaultConfig.Instance.AddColumn(new NameColumn());
```

**Comment by stevehjohn** [comment]
@timcassell That's what I was doing that didn't work.

**Comment by stevehjohn** [comment]
@YegorStepanov sorry, I have re-read your post and I understand now. Will close this if no-one objects.
