### ISSUE TITLE
[Question] Night build feed

### ISSUE THREAD

**Issue by workgroupengineering** [dotnet/BenchmarkDotNet#2232]
Is there Night build feed?

**Comment by workgroupengineering** [comment]
Is there Night build feed?

**Comment by AndreyAkinshin** [comment]
The nightly feed is available here: https://ci.appveyor.com/nuget/benchmarkdotnet

You can enable it by adding the following lines in your `NuGet.Config`:
```xml
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

You can match the nightly versions and commits using the AppVeyor history: https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/history
