### ISSUE TITLE
Version 0.13.3 breaks LINQPad (and any non-Console application)

### ISSUE THREAD

**Issue by albahari** [dotnet/BenchmarkDotNet#2237]
BenchmarkDotNet 0.13.3 throws an IOException whenever called from LINQPad. The cause is line 171 of BenchmarkRunnerClean:

`var consoleTitle = RuntimeInformation.IsWindows() ? Console.Title : string.Empty;`

The IOException is thrown when accessing `Console.Title` from a non-Console application in Windows. BenchmarkDotNet is effectively assuming that a Console window will always be available, which is not the case with a Windows Forms, WPF, Windows Service or daemon application. The line of code was introduced by #2140.

An easy way to fix this would be to read and restore the Console.Title property only when console output is not redirected. (This will not change the existing behavior because the same check is also performed before updating Console.Title in line 659 and line 674.) To implement this fix requires two changes. First, line 171 is modified as follows:

`var consoleTitle = RuntimeInformation.IsWindows() && !Console.IsOutputRedirected ? Console.Title : string.Empty;`

We also add the Console.IsOutputRedirected check at line 248:

```
if (RuntimeInformation.IsWindows() && !Console.IsOutputRedirected)
{
   Console.Title = consoleTitle;
}
```

This will get LINQPad working again (because LINQPad redirects console output). It would also provide a workaround for other non-Console apps that wish to call BenchmarkDotNet (by redirecting Console output).

P.S. If you prefer a cleaner solution, with no repetition of logic, how about introducing a class similar to the following:

```
using System;
using System.IO;
using BenchmarkDotNet.Portability;

namespace BenchmarkDotNet.Running
{
    internal class ConsoleTitler : IDisposable
    {
        public bool IsEnabled { get; private set; }

        private string oldConsoleTitle;

        public ConsoleTitler()
        {
            // Return without enabling if Console output is redirected, or if we're not on a platform that supports Console retitling.
            if (Console.IsOutputRedirected || !IsSupportedPlatform())
            {
                return;
            }

            try
            {
                oldConsoleTitle = RuntimeInformation.IsWindows() ? Console.Title : "";
                IsEnabled = true;
            }
            catch (IOException)
            {
                // No Console window is available - return without enabling.
                // This might be due to the hosting application being Windows Forms, WPF, Windows Service or a daemon.
            }
        }

        private bool IsSupportedPlatform() => RuntimeInformation.IsWindows() || RuntimeInformation.IsLinux() || RuntimeInformation.IsMacOS();

        public void UpdateTitle (string title)
        {
            if (IsEnabled)
            {
                Console.Title = title;
            }
        }

        public void Dispose()
        {
            if (IsEnabled && !string.IsNullOrEmpty (oldConsoleTitle))
            {
                Console.Title = oldConsoleTitle;
                IsEnabled = false;
            }
        }
    }
}
```

Instantiate it in line 171 of BenchmarkRunnerClean as follows:

`using var consoleTitler = new ConsoleTitler();`

Pass the instance as a parameter where required; no explicit disposal required.

**Comment by AndreyAkinshin** [comment]
@albahari thank you for the bug report and for the proposed solution! Would you like to send a pull request?

cc @timcassell

**Comment by timcassell** [comment]
I like the class approach, similar to `TaskbarProgress`. Though I'm not sure why you say it should be instantiated on line 171 inside the loop. I would expect it to be instantiated outside the loop.

**Comment by timcassell** [comment]
Also, keep in mind that the `Console.Title` is write-only on Linux, so a single flag like your proposed class will not work there. https://github.com/dotnet/BenchmarkDotNet/pull/2140#discussion_r992677161

**Comment by albahari** [comment]
Done. I've kept with a single flag, but updated the logic so that it can restore Console.Title on platforms where the property is write-only.
