### ISSUE TITLE
BDN throws error 'NuGetSdkResolver did not resolve this SDK'

### ISSUE THREAD

**Issue by Code-Chops** [dotnet/BenchmarkDotNet#2239]
BenchMarkDotNet throws an error when executing a benchmark:
` D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\5f130c80-9236-4b70-bd98-18d9ea5d1a63\BenchmarkDotNet.Autogenerated.csproj : warning : The NuGetSdkResolver did not resolve this SDK because there was no version specified in the project or global.json.
D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\5f130c80-9236-4b70-bd98-18d9ea5d1a63\BenchmarkDotNet.Autogenerated.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.`

My project targets .net 7.0:
`    <TargetFramework>net7.0</TargetFramework>
	<RollForward>LatestMinor</RollForward>`

I also see that the generated project file targets .net 7.0:
`    <TargetFramework>net7.0</TargetFramework>`

My installed .net SDKs:
3.1.100 [C:\Program Files\dotnet\sdk]
3.1.426 [C:\Program Files\dotnet\sdk]
6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
6.0.112 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.307 [C:\Program Files\dotnet\sdk]
6.0.400 [C:\Program Files\dotnet\sdk]
6.0.402 [C:\Program Files\dotnet\sdk]
6.0.404 [C:\Program Files\dotnet\sdk]
7.0.100 [C:\Program Files\dotnet\sdk]
7.0.101 [C:\Program Files\dotnet\sdk]

What is going wrong?
Thank you in advance!

**Comment by AndreyAkinshin** [comment]
@Code-Chops could you please provide the full source code of your benchmark project (including *.csproj files)?

**Comment by Code-Chops** [comment]
Thank you for your fast response. Here is the code:

[SmartEnum.zip](https://github.com/dotnet/BenchmarkDotNet/files/10319091/SmartEnum.zip)

**Comment by AndreyAkinshin** [comment]
The project looks fine. I guess, something is wrong with your environment. Please do the following:
1. Add `this.KeepBenchmarkFiles();` to the constructor of your `Config` class to keep the generated project on disk.
2. Run the benchmarks and share the full output.
3. Find the building section in the logs (something like `Building 1 exe(s) in Parallel: Start`) and manually execute the following commands for restore and build. Share the output.

**Comment by Code-Chops** [comment]
I added `KeepBenchmarkFiles` to the config and ran the benchmark.
Where can I find the logs?

The console output:
`
// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 27 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet  restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\b38e2074-73a2-4541-91ee-9030ae415c32
// command took 0,48s and exited with 1
// ***** Done, took 00:00:00 (0.65 sec)   *****
// Found 27 benchmarks:
//   EqualsBenchmarks.Enum_GetHashCode: DefaultJob
//   EqualsBenchmarks.Enum_Equals_SameValue: DefaultJob
//   EqualsBenchmarks.Enum_Equals_DifferentValue: DefaultJob
//   EqualsBenchmarks.Enum_Equals_DifferentType: DefaultJob
//   EqualsBenchmarks.Enum_EqualOperator: DefaultJob
//   EqualsBenchmarks.Enum_NotEqualOperator: DefaultJob
//   EqualsBenchmarks.Constant_GetHashCode: DefaultJob
//   EqualsBenchmarks.Constant_Equals_Null: DefaultJob
//   EqualsBenchmarks.Constant_Equals_SameValue: DefaultJob
//   EqualsBenchmarks.Constant_Equals_DifferentValue: DefaultJob
//   EqualsBenchmarks.Constant_Equals_DifferentType: DefaultJob
//   EqualsBenchmarks.Constant_EqualOperator: DefaultJob
//   EqualsBenchmarks.Constant_NotEqualOperator: DefaultJob
//   EqualsBenchmarks.SmartEnum_GetHashCode: DefaultJob
//   EqualsBenchmarks.SmartEnum_Equals_Null: DefaultJob
//   EqualsBenchmarks.SmartEnum_Equals_SameValue: DefaultJob
//   EqualsBenchmarks.SmartEnum_Equals_DifferentValue: DefaultJob
//   EqualsBenchmarks.SmartEnum_Equals_DifferentType: DefaultJob
//   EqualsBenchmarks.SmartEnum_EqualOperator: DefaultJob
//   EqualsBenchmarks.SmartEnum_NotEqualOperator: DefaultJob
//   EqualsBenchmarks.MagicEnum_GetHashCode: DefaultJob
//   EqualsBenchmarks.MagicEnum_Equals_Null: DefaultJob
//   EqualsBenchmarks.MagicEnum_Equals_SameValue: DefaultJob
//   EqualsBenchmarks.MagicEnum_Equals_DifferentValue: DefaultJob
//   EqualsBenchmarks.MagicEnum_Equals_DifferentType: DefaultJob
//   EqualsBenchmarks.MagicEnum_EqualOperator: DefaultJob
//   EqualsBenchmarks.MagicEnum_NotEqualOperator: DefaultJob

Setup power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: High performance)
// Build Error: Standard output:

 Standard error:
 D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\b38e2074-73a2-4541-91ee-9030ae415c32\BenchmarkDotNet.Autogenerated.csproj : warning : The NuGetSdkResolver did not resolve this SDK because there was no version specified in the project or global.json.
D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\b38e2074-73a2-4541-91ee-9030ae415c32\BenchmarkDotNet.Autogenerated.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\b38e2074-73a2-4541-91ee-9030ae415c32
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html

// ** Remained 0 (0,0%) benchmark(s) to run. Estimated finish 2022-12-29 18:05 (0h 0m from now) **
Successfully reverted power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: High performance)
// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\SmartEnum.Benchmarks.EqualsBenchmarks-report.csv
  BenchmarkDotNet.Artifacts\results\SmartEnum.Benchmarks.EqualsBenchmarks-report-github.md
  BenchmarkDotNet.Artifacts\results\SmartEnum.Benchmarks.EqualsBenchmarks-report.html

// * Detailed results *
EqualsBenchmarks.Enum_GetHashCode: DefaultJob
Runtime = ; GC =
There are not any results runs

// * Summary *

BenchmarkDotNet=v0.13.3.2064-nightly, OS=Windows 11 (10.0.22621.963)
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.101
  [Host] : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT AVX2


|           Method | Mean | Error | Library |
|----------------- |-----:|------:|-------- |
| Enum_GetHashCode |   NA |    NA |    Enum |

Benchmarks with issues:
  EqualsBenchmarks.Enum_GetHashCode: DefaultJob

// * Legends *
  Mean    : Arithmetic mean of all measurements
  Error   : Half of 99.9% confidence interval
  Library : Custom 'Library' tag column
  1 ns    : 1 Nanosecond (0.000000001 sec)

// * Diagnostic Output - MemoryDiagnoser *


// ***** BenchmarkRunner: End *****
Run time: 00:00:00 (0.1 sec), executed benchmarks: 0

Global total time: 00:00:01 (1.09 sec), executed benchmarks: 0
// * Artifacts cleanup *
`

**Comment by AndreyAkinshin** [comment]
Please, go to `D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\b38e2074-73a2-4541-91ee-9030ae415c32\` and run the restore command:

```sh
dotnet restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true
```
Then, share the output.

**Comment by Code-Chops** [comment]
`
D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\b38e2074-73a2-4541-91ee-9030ae415c32>dotnet restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true
D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\b38e2074-73a2-4541-91ee-9030ae415c32\BenchmarkDo
tNet.Autogenerated.csproj : warning : The NuGetSdkResolver did not resolve this SDK because there was no version specif
ied in the project or global.json.
D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\b38e2074-73a2-4541-91ee-9030ae415c32\BenchmarkDo
tNet.Autogenerated.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

D:\Source\SmartEnum\benchmarks\SmartEnum.Benchmarks\bin\Release\net7.0\b38e2074-73a2-4541-91ee-9030ae415c32>
`

**Comment by Code-Chops** [comment]
Is my .NET SDK corrupt?

**Comment by AndreyAkinshin** [comment]
@Code-Chops it seems that something is wrong with your dev environment. `BenchmarkDotNet.Autogenerated.csproj` is a usual .NET project, you should be able to restore it.

**Comment by Code-Chops** [comment]
You are right; there was something wrong with my dev environment. Uninstalling .NET SDKs and remove environment variables and reinstalling everything did the trick.

**Comment by MrX101** [comment]
Incase it helps anyone, I had the below error, I managed to fix it by going to enviroment variables and changing the path from:

C:\Program Files\dotnet\dotnet.exe

to

C:\Program Files\dotnet\sdk\7.0.304\Sdks

Re-installing all sdks did not solve the issue. Hopefully this doesn't break anything else I use...

"C:\Program Files\dotnet\dotnet.exe" ef migrations add --project TumasPortalBlazorServer.csproj --startup-project TumasPortalBlazorServer.csproj --context TumasPortalBlazorServer.Data.TumasContext --configuration Debug Initial --output-dir Migrations
C:\Users\sborg\RiderProjects\TumasPortalBlazorServer\TumasPortalBlazorServer.csproj : warning : The NuGetSdkResolver did not resolve this SDK because there was no version specified in the project or global.json.
C:\Users\sborg\RiderProjects\TumasPortalBlazorServer\TumasPortalBlazorServer.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
Process terminated with exit code 1
