### ISSUE TITLE
Benchmarking memory bandwidth

### ISSUE THREAD

**Issue by just-ero** [dotnet/BenchmarkDotNet#2244]
Hey, sorry if this isn't a real "issue" and more of a clarifying question.

Is it possible to benchmark memory bandwidth using BenchmarkDotNet? I'm attempting to run some simple [`STREAM2`](https://cs.virginia.edu/stream/stream2) benchmarks and would like to create -- if not automatically, just in Excel -- similar graphs like the ones shown on that website.

Is there a way to track the number of bytes read/written and the number of floating-point operations done? If not, what are my alternatives?

**Comment by adamsitnik** [comment]
Hi @just-ero 

> Is there a way to track the number of bytes read/written and the number of floating-point operations done? 

BenchmarkDotNet does not provide such a functionality, neither we have plans to implement it.

> If not, what are my alternatives?

You can most likely get it from Intel VTune Aplifier profiler, which is now available for free.
