### ISSUE TITLE
The Roslyn toolchain is only supported on .NET Framework

### ISSUE THREAD

**Issue by Marvin-Brouwer** [dotnet/BenchmarkDotNet#2245]
I'm backporting my `net7`/`net6`/`netcoreapp3.1` library to `net48` and I'm running into the following output:
```txt
// Validating benchmarks:
// Benchmark NamingStrategyProfile_CamelCase.CamelCase_ShortNamedClass: BenchmarkDotNet, Version=0.13.3.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4(MaxAbsoluteError=10.0000 ns, MaxRelativeError=0.001, MinIterationTime=10.0000 ms, EnvironmentVariables=COMPlus_gcAllowVeryLargeObjects=1,DOTNET_gcAllowVeryLargeObjects=1, PowerPlanMode=8c5e7fda-e8bf-4a96-9a85-a6e[23](https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/3906421017/jobs/6674585365#step:6:24)a8c635c, AllowVeryLargeObjects=False, Force=True, NuGetReferences=Microsoft.Net.Compilers.Toolset, IterationCount=15, LaunchCount=2, MinIterationCount=1, WarmupCount=10)
//    * The Roslyn toolchain is only supported on .NET Framework

// Benchmark NamingStrategyProfile_CamelCase.CamelCase_ShortNamedClass: BenchmarkDotNet, Version=0.13.3.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4(MaxAbsoluteError=10.0000 ns, MaxRelativeError=0.001, MinIterationTime=10.0000 ms, EnvironmentVariables=COMPlus_gcAllowVeryLargeObjects=1,DOTNET_gcAllowVeryLargeObjects=1, PowerPlanMode=8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c, AllowVeryLargeObjects=False, Force=True, NuGetReferences=Microsoft.Net.Compilers.Toolset, IterationCount=15, LaunchCount=2, MinIterationCount=1, WarmupCount=10)
//    * The Roslyn toolchain does not allow specifying NuGet package dependencies
```

I did a quick google but, I can't find anything on this subject.
Is there something I must reference or configure differently when targeting `netframework`?

**Comment by timcassell** [comment]
How are you running your benchmarks?

**Comment by Marvin-Brouwer** [comment]
I have a helper project for my configuration:
https://github.com/Marvin-Brouwer/FluentSerializer/blob/8-profile-for-dotnet-framework-47/src/FluentSerializer.Core.BenchmarkUtils/Runner/StaticTestRunner.cs
But the gist of it is this part:
```csharp
		var config = ManualConfig.Create(DefaultConfig.Instance)
			.AddJob(CreateJob(arguments))
			.WithCultureInfo(AppCulture)
			.AddExporter(MarkdownExporter.Console)
			.StopOnFirstError(true)
			.WithOptions(ConfigOptions.GenerateMSBuildBinLog)
			.WithSummaryStyle(SummaryStyle.Default
				.WithCultureInfo(AppCulture)
			);
			
// -------

		return CreateBasicJob(runType)
#if (DEBUG)
			.WithToolchain(new InProcessEmitToolchain(TimeSpan.FromHours(1.0), true))
#endif
			.WithMinIterationTime(TimeInterval.FromMilliseconds(10))
			.WithMinIterationCount(1)
			.WithMaxRelativeError(0.001)
			.WithMaxAbsoluteError(TimeInterval.FromNanoseconds(10))
			// Make sure the compile projects have access to the correct build tool
			.WithNuGet("Microsoft.Net.Compilers.Toolset")
			.WithId(typeof(BenchmarkRunner).Assembly!.FullName!)
			.WithEnvironmentVariable("COMPlus_gcAllowVeryLargeObjects", Environment.GetEnvironmentVariable("COMPlus_gcAllowVeryLargeObjects") ?? "0")
			.WithEnvironmentVariable("DOTNET_gcAllowVeryLargeObjects", Environment.GetEnvironmentVariable("DOTNET_gcAllowVeryLargeObjects") ?? "0")
			// This is set to false until the new benchmark dotnet version is released:
			// https://github.com/dotnet/BenchmarkDotNet/issues/1519
			.WithGcAllowVeryLargeObjects(false)
			.WithGcForce(true)
			.WithPowerPlan(PowerPlan.HighPerformance);
			
```

And then I reference those with two lines:
https://github.com/Marvin-Brouwer/FluentSerializer/blob/8-profile-for-dotnet-framework-47/src/FluentSerializer.Core.Benchmark/Program.cs

And that's kicked off in a GitHub Actions pipeline:
https://github.com/Marvin-Brouwer/FluentSerializer/blob/8-profile-for-dotnet-framework-47/.github/workflows/continuous-integration.benchmark.yml

In the pipeline runner, it fails with the error message.
If I run the compiled `.exe` locally on a windows machine it just works, so maybe it's an SDK on linux issue?

**Comment by timcassell** [comment]
> In the pipeline runner, it fails with the error message. If I run the compiled `.exe` locally on a windows machine it just works, so maybe it's an SDK on linux issue?

.Net Framework is windows only, I'm surprised it even got that far.

**Comment by Marvin-Brouwer** [comment]
Aha, well that might be the cause then 😅

**Comment by Marvin-Brouwer** [comment]
Interestingly `dotnet build` with similar parameters does work.
But googling net framework support for linux does indeed tell me that it's not possible.
I guess I could try mono, but, I have a windows runner ready so I'll give that a go

**Comment by adamsitnik** [comment]
> Is there something I must reference or configure differently when targeting netframework?

There is not, by default BDN detects the host process (the process you start) runtime and builds, generates and runs the benchmarks as apps targeting the same runtime.

If you wish to run the same benchmark for more runtimes at the same time you can need to follow these guidelines: https://benchmarkdotnet.org/articles/configs/toolchains.html#multiple-frameworks-support

> .Net Framework is windows only,

As pointed by @timcassell, this is by design. For .NET Framework/Mono BDN chooses RoslynToolchain. It may work on Linux only if you install Mono.

**Comment by majkel89** [comment]
I had the same issue on mac with .NET 8.

I removed `[SimpleJob(RuntimeMoniker.Mono)]` from benchmark class and that solved the problem.
