### ISSUE TITLE
Can a Standard Mean Value Be Set?

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#2247]
In some of my benchmarks, the Mean value shows as `ns `and others are `us`. Is there a way to ensure that all tests use `ns`?

**Comment by timcassell** [comment]
By default, it uses the smallest unit of all the benchmarks. You can override it in the config:
```cs
using BenchmarkDotNet.Configs;
using Perfolizer.Horology;

...

DefaultConfig.Instance.WithSummaryStyle(SummaryStyle.Default.WithTimeUnit(TimeUnit.Nanosecond))
```

**Comment by adamsitnik** [comment]
@timcassell thank you for answering the question!
