### ISSUE TITLE
msbuild binlog for the benchmark projects gets cleaned up too, making diagnosis of build impossible

### ISSUE THREAD

**Issue by radical** [dotnet/BenchmarkDotNet#2252]
If you use `--generateBinLog` for wasm benchmarks, you get:

```
/home/helixbot/work/B78C09A9/p/dotnet/dotnet  restore --packages "/home/helixbot/work/B78C09A9/w/BCE609B9/e/performance/artifacts/packages" /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true
  -bl:8b197aae-5d64-4019-b6f4-46946d02dc65-restore.binlog

in /home/helixbot/work/B78C09A9/w/BCE609B9/e/performance/artifacts/bin/for-running/MicroBenchmarks/8b197aae-5d64-4019-b6f4-46946d02dc65
```

The binlog gets generated in `/home/helixbot/work/B78C09A9/w/BCE609B9/e/performance/artifacts/bin/for-running/MicroBenchmarks/8b197aae-5d64-4019-b6f4-46946d02dc65`, but that is getting cleaned up at the end, thus it is not retrievable later for diagnosis.

It would be useful to maybe use some path in `artifacts` which does not get removed for these files.

cc @adamsitnik

**Comment by radical** [comment]
And related to that, a command line parameter to skip the cleanup would be useful too.

**Comment by adamsitnik** [comment]
> a command line parameter to skip the cleanup would be useful too.

We already have that: `--keepFiles`

I've sent https://github.com/dotnet/BenchmarkDotNet/pull/2254 which basically enables that when ` --generateBinLog` is requested
