### ISSUE TITLE
TaskbarProgressCom is not supported when benchmarking Native AOT

### ISSUE THREAD

**Issue by 3steve3** [dotnet/BenchmarkDotNet#2253]
It appears that [https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Helpers/Taskbar/TaskbarProgress.cs](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Helpers/Taskbar/TaskbarProgress.cs) is using COM Interop, and it not supported by default when using Native AOT.

The output that I'm getting is:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'BenchmarkDotNet.Helpers.TaskbarProgressCom' threw an exception.
 ---> System.NotSupportedException: Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.
   at BenchmarkDotNet.Helpers.TaskbarProgressCom..cctor()
   --- End of inner exception stack trace ---
   at BenchmarkDotNet.Helpers.TaskbarProgressCom.SetState(IntPtr consoleWindowHandle, IntPtr consoleHandle, TaskbarProgressState taskbarState)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MyBenchmarks.Program.Main(String[] args) in C:\Users\Steve\source\repos\BenchmarkTesting\BenchmarkTesting\Program.cs:line 102
```

**Comment by adamsitnik** [comment]
Hi @3steve3 

How do you run your benchmarks?

I would expect your host process (what you start from command line) to be non-NativeAOT and work fine, while the benchmark process that does not use the taskbar be NativeAOT and also work fine.

**Comment by 3steve3** [comment]
I'm using this command `dotnet run -c Release -f net7.0 --runtimes nativeaot7.0` and this main `static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);`

**Comment by adamsitnik** [comment]
Based on https://stackoverflow.com/questions/68110207/system-notsupportedexception-in-taskscheduler-when-using-publishtrimmed-net6-0 I suspect that something sets `PublishTrimmed` to `true` for your project with benchmarks. Could you please try setting `<BuiltInComInteropSupport>true</BuiltInComInteropSupport>` as described in https://stackoverflow.com/a/69200541/5852046 for the benchmarks project?

If it does not help could you please try downloading our samples and running them?

```log
git clone https://github.com/dotnet/BenchmarkDotNet.git
cd .\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\
dotnet run -c Release -f net7.0 --filter *Basic*Sleep* --runtimes nativeaot7.0
```

it works fine on my machine:

![image](https://user-images.githubusercontent.com/6011991/213651426-8470904c-d66f-445d-a745-85e8ffd7c6ec.png)

**Comment by timcassell** [comment]
I was able to repro by adding `<BuiltInComInteropSupport>false</BuiltInComInteropSupport>`. Unfortunately, the `TypeInitializationException` seems to be uncatchable, so I'm trying to figure out another fix.

**Comment by timcassell** [comment]
@adamsitnik Fixed in #2255.

**Comment by ygoe** [comment]
Seriously? You "fix" the bug by not doing what you originally wanted to do? Is BenchmarkDotNet even compatible with AOT? How can I proceed with this exception? I really don't care about taskbar progress. I just want to run realistic benchmarks. Maybe I'll have to run my own Stopwatch loop again. It wasn't that bad last time. Actually I was also interested in memory consumption results.

**Comment by timcassell** [comment]
@ygoe What do you mean? Did you try the nightly build with the fix? If you're running your benchmarks in windows terminal, it should still work. If you're running them in classic console, the fix simply stops the program from exploding so the benchmarks can still run. It's not like there's a way we can force COM to work if it's disabled in the runtime.

**Comment by ygoe** [comment]
What I mean is: My application runs with PublishAOT and I'd like to benchmark two possible implementations of something I want to do in there. To get realistic results, I'm interested in the benchmark running the AOT-compiled code, not the JITed code.

I'm running this from Visual Studio in Release mode. It opens by default in the Windows Terminal app here on Windows 11.

I've used the public NuGet package.

**Comment by timcassell** [comment]
The fix is not on public nuget yet. You will need to use the nightly version to get the fix. https://benchmarkdotnet.org/articles/guides/nuget.html#nightly
