### ISSUE TITLE
Strong name validation failed

### ISSUE THREAD

**Issue by HugoLemieux** [dotnet/BenchmarkDotNet#2258]
Hello,

The strong name does not seem valid anymore (using sn - vf) since 0.13.3 on:
- BenchmarkDotNet.dll
- BenchmarkDotNet.Annotations.dll

It was before with version 0.13.2.

Are you able to fix it?

Regards,

**Comment by adamsitnik** [comment]
@AndreyAkinshin have we changed anything?

**Comment by AndreyAkinshin** [comment]
@adamsitnik the only signing-related issue I remember in the scope of v0.13.3 is https://github.com/dotnet/BenchmarkDotNet/pull/2212   
Could you please check that `Gee.External.Capstone` 2.3.0 is properly signed?

**Comment by adamsitnik** [comment]
Capstone LGTM:

```log
C:\Program Files\Microsoft Visual Studio\2022\Enterprise>sn -vf C:\Users\adsitnik\.nuget\packages\gee.external.capstone\2.3.0\lib\netstandard2.0\Gee.External.Capstone.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'C:\Users\adsitnik\.nuget\packages\gee.external.capstone\2.3.0\lib\netstandard2.0\Gee.External.Capstone.dll' is valid

C:\Program Files\Microsoft Visual Studio\2022\Enterprise>sn -vf C:\Users\adsitnik\.nuget\packages\gee.external.capstone\2.3.0\lib\net5.0\Gee.External.Capstone.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'C:\Users\adsitnik\.nuget\packages\gee.external.capstone\2.3.0\lib\net5.0\Gee.External.Capstone.dll' is valid

C:\Program Files\Microsoft Visual Studio\2022\Enterprise>sn -vf C:\Users\adsitnik\.nuget\packages\gee.external.capstone\2.3.0\lib\net6.0\Gee.External.Capstone.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'C:\Users\adsitnik\.nuget\packages\gee.external.capstone\2.3.0\lib\net6.0\Gee.External.Capstone.dll' is valid

C:\Program Files\Microsoft Visual Studio\2022\Enterprise>sn -vf C:\Users\adsitnik\.nuget\packages\gee.external.capstone\2.3.0\lib\net7.0\Gee.External.Capstone.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'C:\Users\adsitnik\.nuget\packages\gee.external.capstone\2.3.0\lib\net7.0\Gee.External.Capstone.dll' is valid

C:\Program Files\Microsoft Visual Studio\2022\Enterprise>sn -vf C:\Users\adsitnik\.nuget\packages\benchmarkdotnet\0.13.4\lib\netstandard2.0\BenchmarkDotNet.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.

C:\Program Files\Microsoft Visual Studio\2022\Enterprise>
```

When I build BenchmarkDotNet locally in Release it's also OK:

```log
C:\Program Files\Microsoft Visual Studio\2022\Enterprise>sn -vf D:\projects\BenchmarkDotNet\src\BenchmarkDotNet\bin\Release\netstandard2.0\BenchmarkDotNet.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'D:\projects\BenchmarkDotNet\src\BenchmarkDotNet\bin\Release\netstandard2.0\BenchmarkDotNet.dll' is valid
```

@AndreyAkinshin have you used non Windows machine to build the package? My current only guess is that the following condition can be affecting us:
https://github.com/dotnet/BenchmarkDotNet/blob/512413ceb24077154bdf6d6306138accffe64c7a/build/common.props#L32

**Comment by AndreyAkinshin** [comment]
@adamsitnik yes, you are right, I have released v0.13.3 and v0.13.4 using macOS (I was on the road without access to my Windows machine).

Can we make it possible to build strongly signed assemblies on Linux/macOS?

**Comment by adamsitnik** [comment]
I have no idea, let's give it a try: https://github.com/dotnet/BenchmarkDotNet/pull/2260

**Comment by AndreyAkinshin** [comment]
We used `<PublicSign Condition=" '$(OS)' != 'Windows_NT' ">true</PublicSign>` to disable strong names on Linux/macOS in order to allow compiling via mono msbuild. Currently, we compile BenchmarkDotNet using .NET SDK on all OSes, so this hack is not required anymore. I removed it in #2263. Now we are able to produce strong named assemblies on all operating systems.

**Comment by AndreyAkinshin** [comment]
@timcassell 
> Why not use a GitHub action to do it? 
It's in the roadmap. Currently, I'm trying to fully automate the documentation generation process. Once it's done, I will use GitHub actions for NuGet packing and publishing. My ultimate goal is to make the release workflow completely automatic. Unfortunately, the current release workflow includes several manual steps (due to some legacy reasons) that should be automated one by one.

**Comment by sonicpro** [comment]
Same issue here
`[FileLoadException: Could not load file or assembly 'BenchmarkDotNet.Annotations' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]

[FileLoadException: Could not load file or assembly 'BenchmarkDotNet.Annotations, Version=0.13.4.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]
   System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0
   System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +232
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +113
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +23
   System.Reflection.Assembly.Load(String assemblyString) +35
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +49

[ConfigurationErrorsException: Could not load file or assembly 'BenchmarkDotNet.Annotations, Version=0.13.4.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +762
   System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +259
   System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai) +167
   System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +238
   System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies() +78
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +334
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +178
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +746

[HttpException (0x80004005): Could not load file or assembly 'BenchmarkDotNet.Annotations, Version=0.13.4.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +552
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +122
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +737`

Glad to see it fixed, but I can't wait for 0.13.5 to be released. @AndreyAkinshin @adamsitnik Could you please provide me with guidance how to build the current version or where can I get the nightly build?

**Comment by mawosoft** [comment]
@sonicpro See https://benchmarkdotnet.org/articles/guides/nuget.html#nightly

**Comment by sonicpro** [comment]
@mawosoft Thank you for your reply. How do I know the nightly build package name? I ran
the following, but it did not work

![InkedBenchmarkDotNet-nightly](https://user-images.githubusercontent.com/5416927/219311686-c89da0c0-90fd-4ae7-b375-65ecf7fe9047.jpg)

**Comment by sonicpro** [comment]
> @mawosoft Thank you for your reply. How do I know the nightly build package name? I ran the following, but it did not work
> 
> ![InkedInkedBenchmarkDotNet-nightly](https://user-images.githubusercontent.com/5416927/219312289-65f794f1-49ae-4683-9401-0de594425513.jpg)

Got it. Without specifying the package name it installed the signed version BenchmarkDotNet.0.13.4.2099.
