### ISSUE TITLE
Execute Benchmarks without SDK?

### ISSUE THREAD

**Issue by mattheweshleman** [dotnet/BenchmarkDotNet#2262]
Hello,

I would like to execute benchmarks on a Linux Debian 9 arm (armhf) target with .net5.0. There is no SDK available for this device/platform as best as I can determine at this time. We build on a host Ubuntu PC (x86) and deploy to the target arm device.

Is there a build option or execution option that skips SDK use (i.e. a way to run benchmarks on a platform with dotnet runtime only)?

Thank you very much,

Matthew

**Comment by adamsitnik** [comment]
Hi @mattheweshleman 

> Is there a build option or execution option that skips SDK use (i.e. a way to run benchmarks on a platform with dotnet runtime only)?

Yes, you can use the [InProcessToolchain](https://benchmarkdotnet.org/articles/samples/IntroInProcess.html) which does not run every benchmark in a dedicated process. It works well for benchmarks with no side-effects.

If you are using `BenchmarkSwitcher` and passing `args` to it like this:

https://github.com/dotnet/BenchmarkDotNet/blob/512413ceb24077154bdf6d6306138accffe64c7a/samples/BenchmarkDotNet.Samples/Program.cs#L7

then all you need to do is pass:

```cmd
--inProcess
```

or just:

```cmd
-i
```

An alternative is to update to .NET 6 or even .NET 7 which has [plenty of arm64 improvements](https://devblogs.microsoft.com/dotnet/arm64-performance-improvements-in-dotnet-7/). (.NET 5 is not supported anymore)

**Comment by mattheweshleman** [comment]
Worked great and massive improvements already made, much appreciated!
