### ISSUE TITLE
Non-attribute version docs.

### ISSUE THREAD

**Issue by 0xorial** [dotnet/BenchmarkDotNet#2273]
After 10 min of searching it is still unclear how to run a basic test without attribute-based class. This should be way simpler.
The example here is very confusing
```
ManualConfig.CreateEmpty() // A configuration for our benchmarks
    .AddJob(Job.Default // Adding first job
        .WithRuntime(ClrRuntime.Net472) // .NET Framework 4.7.2
        .WithPlatform(Platform.X64) // Run as x64 application
        .WithJit(Jit.LegacyJit) // Use LegacyJIT instead of the default RyuJIT
        .WithGcServer(true) // Use Server GC
    ).AddJob(Job.Default // Adding second job
        .AsBaseline() // It will be marked as baseline
        .WithEnvironmentVariable("Key", "Value") // Setting an environment variable
        .WithWarmupCount(0) // Disable warm-up stage
    );
```
The first thing and most important I expect to see is the way how the lib knows which code to run. But this is not specified anywhere, aside from what I can imply from a `BenchmarkAttribute`

**Comment by AndreyAkinshin** [comment]
@0xorial the current BenchmarkDotNet design assumes that you always provide a class with a set of methods marked with the `[Benchmark]` attribute (while other configuration options can be set via attributes or via the fluent API).

What's the problem with creating a separate class?

**Comment by AndreyAkinshin** [comment]
@0xorial ping

**Comment by 0xorial** [comment]
@AndreyAkinshin TBH, I think it jus triggers some kind of OCD here :) 
In my case, I wanted to benchmark a tiny piece of code in scope of a single process, which seems like a very easy subset of what this library is doing, so the API for that could be like

```
Benchmark.Run(() => Method1(), () => Method2(), b => b.WarmupIterations(2).Iterations(100).ExportConsole())
```

Having to figure out the processes, jobs, etc felt needlessly tedious..

**Comment by AndreyAkinshin** [comment]
@0xorial Thank you for your feedback and for expressing your concerns about the current API design of BenchmarkDotNet. I appreciate your input and understand that you're looking for a more straightforward way to benchmark small pieces of code.

However, at the current moment, I don't want to support the API you proposed for the following reasons:

* **Complexity of implementation and maintenance**: Implementing an additional set of APIs that allow running benchmarks without attribute-based classes would add a significant level of complexity to the codebase, making it harder to maintain, test, and evolve the library.
* **Limited feature scope**: Not all the features offered by BenchmarkDotNet, such as setup and cleanup methods, parameterization, and automatic iteration count determination, can be easily implemented with the proposed approach. This would lead to a fragmented and potentially confusing user experience.
* **Challenges with lambda expressions and closures**: Passing lambda expressions to a separate benchmarking process, especially in the case of closures, is tricky and error-prone. BenchmarkDotNet relies on a separate process to provide accurate measurements, and the current attribute-based design ensures that all necessary method calls and states are correctly transferred.
* **Validation difficulties**: Validating benchmarks with the proposed API is much harder compared to the default attribute-based API. There is a higher chance of mistakes, which could lead to inaccurate results or unexpected behavior. The attribute-based API provides a more structured and bulletproof way of defining benchmarks, reducing the likelihood of such issues.

While I understand that the current API may not be ideal for some specific scenarios, our priority is to maintain the robustness and reliability of BenchmarkDotNet. I believe that the trade-offs associated with implementing the proposed feature outweigh the potential benefits.

**Comment by 0xorial** [comment]
In either case thanks for taking time!
