### ISSUE TITLE
Add a way to skip certain benchmarks based on runtime conditions

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/BenchmarkDotNet#2281]
Having a way to skip certain benchmarks based on some runtime condition would be useful in some cases. I think it could look like this:
```C#
[Params(1, 2, 3)]
public int P;

public bool A => !Avx2.IsSupported || P = 1;

[GlobalSetup]
public void Setup()
{
    // ...
}

[Benchmark(SkipCondition = nameof(A))]
public void B()
{
    // ...
}
```

In this case, when either Avx2.IsSupported is false or P is 1, both the setup for the benchmark and the benchmark itself would be skipped. As for how it'd be displayed in the results, I'd say the table wouldn't contain rows for skipped benchmarks, but they'd be listed out as `Skipped:` under the table instead.

**Comment by adamsitnik** [comment]
Hi @MichalPetryka 

The filtering mechanism that BDN provides already has a way to achieve that by passing an instance of `IFilter`

You don't need to implement the interface, you can reuse the existing [SimpleFilter](https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/src/BenchmarkDotNet/Filters/SimpleFilter.cs) type.

and derive a class from [FilterConfigBaseAttribute](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Attributes/Filters/FilterConfigBaseAttribute.cs) if you want to have an attribute for that.

```cs
public class Avx2Attribute : FilterConfigBaseAttribute
{
    public Avx2Attribute() => : base(new SimpleFilter(_ => Avx2.IsSupported)) { }
}

[Benchmark, Avx2]
public void B()
```

**Comment by MichalPetryka** [comment]
@adamsitnik Does SimpleFilter also support filtering by value from [Params]?

**Comment by adamsitnik** [comment]
The input is `BenchmarkCase`, which contains all available information, including the arguments/parameters. 

https://github.com/dotnet/BenchmarkDotNet/blob/0772ce21aa32914050ccf4339514e9bc05563ec0/src/BenchmarkDotNet/Filters/IFilter.cs#L7
