### ISSUE TITLE
How to pass configuration to benchmark?

### ISSUE THREAD

**Issue by FreePhoenix888** [dotnet/BenchmarkDotNet#2291]
I use parser for CLI application which gets some data from user. How to make a benchmark use it?
How I see it: when I run benchmark with Run method I pass key-value dictionary which can be used inside benchmark

**Comment by AndreyAkinshin** [comment]
@FreePhoenix888 what about passing data via environment variables?

**Comment by AndreyAkinshin** [comment]
Yes, we do not have any additional APIs for passing data to a benchmark via the command line. However, we do support passing environment variables throw native BenchmarkDotNet args like this:

```sh
dotnet run -c Release -- --envVars VARIABLE_NAME:variable_value
```
