### ISSUE TITLE
Possibility for Di/Resolving Dependencies within the setup

### ISSUE THREAD

**Issue by TO-LGerber** [dotnet/BenchmarkDotNet#2308]
Hello,

I have question to the given example implementation.
I'm trying to access a property which is set in the Startup.cs. Then I'm trying to access that property, but this one returns null, due to being executed in a different process.
Is there a way to access these Kind of values? (This property is needed to create an instance, to get access to the methods i want to benchmark. It's basically functioning as a workaround for DI) or as an alternative, is it possible to have DI/some kind of workaround ?

```csharp
public class MyBenchmarkService: IBenchmarkService {
​
  public MyViewModel Execute() {
    var summary = BenchmarkRunner.Run<BenchmarkWrapper>();
    return r.ToMyViewModel();
  }
}
​
public partial class BenchmarkWrapper {
  private IMyProperty myProperty;
​
  public BenchmarkWrapper() {
    myProperty = StaticClassFromADifferentNameSpace.SomeProperty;
  }

// Benchmarks following here
}
```

**Comment by timcassell** [comment]
You correctly noted that it's ran in a separate process, so you have to create it again. You can use `[GlobalSetup]` to do it.

**Comment by adamsitnik** [comment]
https://stackoverflow.com/a/73189559/5852046
