### ISSUE TITLE
Bug: Getting an error loading BenchmarkDotNet.Diagnostics.Windows.dll for a benchmark that is not windows specific

### ISSUE THREAD

**Issue by asilverman** [dotnet/BenchmarkDotNet#2310]
Firstly, thank you so much to the maintainers of this project for the job that you do. My project is using this tool in order to benchmark our performance, It's an open source project found in https://github.com/Azure/bicep. This project is not windows specific and hence we want to only run benchmarks that are OS agnostic.

For this purpose we created this project [Bicep.Tools.Benchmark](https://github.com/Azure/bicep/tree/main/src/Bicep.Tools.Benchmark)  . I am very new to using  `BenchmarkDotNet` and tried to run the following command:

`dotnet run --configuration Release --project src/Bicep.Tools.Benchmark -- --filter *Compilation* --profiler EP`

It resulted in an error that was confusing because the benchmark kept running although the error was printed to the console and I am trying to figure out what I did wrong and what I am misunderstanding

```bash
dotnet run --configuration Release --project src/Bicep.Tools.Benchmark -- --filter *Compilation* --profiler EP
Error loading BenchmarkDotNet.Diagnostics.Windows.dll: FileNotFoundException - Could not load file or assembly 'BenchmarkDotNet.Diagnostics.Windows, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 1 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet  restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in C:\Users\asilverman\src\ms\bicep\src\Bicep.Tools.Benchmark\bin\Release\net7.0\cad93b85-0e3a-4cab-bfb6-0e4a746793b5
// command took 4.28s and exited with 0
...
```

## Screenshot of the error
![image](https://github.com/dotnet/BenchmarkDotNet/assets/9611108/db885e08-1760-4cdb-8b44-3cfc909202ed)

## Desired behavior

I would like to not be notified on errors that are non blocking, also a bit more context about why this error was thrown would be helpful

**Comment by adamsitnik** [comment]
`EventPipeProfiler` is one of our profiler plugins. When you have typed `--profiler EP` BDN tried to load all profilers specific for the current platform (Windows in your case), failed to find `BenchmarkDotNet.Diagnostics.Windows.dll` (not needed in your case), printed an error (which should have been a warning) and loaded and used `EventPipeProfiler`.

The best I can do for now is to mark it as up-for-grabs and hope that somebody will spend the time improving the behavior.

**Comment by MattFromRVA** [comment]
@adamsitnik To improve this behavior would adding a "Warning" logger extension to the Console Logger and apply it to this Exception suffice?

**Comment by adamsitnik** [comment]
> To improve this behavior would adding a "Warning" logger extension to the Console Logger and apply it to this Exception suffice?

It would be better to differentiate two situations: 

1. When we fail to load an assembly that contains the requested diagnoser: print an error (keep current behavior)
2. When we fail to load an assembly that does not contain the requested diagnoser: print nothing (new behavior)

**Comment by MattFromRVA** [comment]
> > To improve this behavior would adding a "Warning" logger extension to the Console Logger and apply it to this Exception suffice?
> 
> 
> 
> It would be better to differentiate two situations: 
> 
> 
> 
> 1. When we fail to load an assembly that contains the requested diagnoser: print an error (keep current behavior)
> 
> 2. When we fail to load an assembly that does not contain the requested diagnoser: print nothing (new behavior)
> 
> 
> 
> IIRC this method is invoked when we can not find the diagnoser: https://github.com/dotnet/BenchmarkDotNet/blob/40305b402ff795992ac9d926c8ad1aee853d8492/src/BenchmarkDotNet/Diagnosers/DiagnosersLoader.cs#L30 

Ok cool. I will work on this. Thanks @adamsitnik

**Comment by MattFromRVA** [comment]
@adamsitnik PR submitted. I hope this simple fix is what you are looking for. To test I forked Bicep and replaced the nuget package with my new code. The Bicep benchmarks ran without the error message as expected.
