### ISSUE TITLE
Delay between invocations for I/O-heavy tests

### ISSUE THREAD

**Issue by iblazhko** [dotnet/BenchmarkDotNet#2323]
I have created a benchmark that involves network requests. I realise that this does not fall into the main intended use case category of micro-benchmarking, but it is a great help.

The problem I see is that the test seems to be exhausting the OS TCP connections limit. I tried to increase those limits, and it helps, but only up to a point.

Workaround is to add a small delay in the benchmark itself after the main job is done:

```csharp
[Benchmark]
public async Task IOHeavyTest()
{
    // test itself

    await Task.Delay(TimeSpan.FromSeconds(1));
}
```

This removes the TCP connections limit problem, but it throws off the statistics.

I can mentally adjust `Mean` by subtracting the delay, but `Error`/`StdDev` would not make sense anymore if I understand this correctly. Or would they? I am not proficient in this area enough to tell what impact this delay causes exactly.

My suggestion is to add an option for a delay between `[Benchmark]` invocations, so that BenchmarkDotNet itself would pause for a while between consecutive invocations of the `[Benchmark]` function, and would not take that delay into account when calculating results.

**Comment by YegorStepanov** [comment]
From [docs](https://benchmarkdotnet.org/articles/features/setup-and-cleanup.html#sample-introsetupcleanupiteration):

> A method which is marked by the [[IterationSetup]](https://benchmarkdotnet.org/api/BenchmarkDotNet.Attributes.IterationSetupAttribute.html) attribute will be executed exactly once before each benchmark invocation, forcing UnrollFactor=1 and InvocationCount=1 (we have changed that in 0.11.0). It's not recommended to use this attribute in microbenchmarks because it can spoil the results. However, if you are writing a macrobenchmark (e.g. a benchmark which takes at least 100ms) and you want to prepare some data before each invocation, [[IterationSetup]](https://benchmarkdotnet.org/api/BenchmarkDotNet.Attributes.IterationSetupAttribute.html) can be useful.
