### ISSUE TITLE
How to benchmark operation executed on large set of data

### ISSUE THREAD

**Issue by kant2002** [dotnet/BenchmarkDotNet#2326]
I try to replicate https://lemire.me/blog/2023/06/08/parsing-ip-addresses-crazily-fast/ using SIMD intrinsics.
I successfully implemented method and want to benchmark it. I look at what Lemiere did and it create 20K random IP addresses and execute original function and new one on these dataset. So my question is how to do that properly using BDN. 
I implemented benchmark like this where `test` is test data.
```csharp
Random random = new Random();
int[] test = new int[20000];

public InetToString()
{
    for (var i = 0; i < test.Length; i++)
    {
        test[i] = random.Next();
    }
}
[Benchmark]
public void IpAddressToStringLemire()
{
    string s = "";
    for (var i = 0; i < test.Length; i++)
    {
        s = Lemiere.ipv4(test[i]);
    }
}
```

even if I don't care about value of `s`, I worry that maybe JIT will remove something or something else happens. I notice that there `Consumer` class exists from https://benchmarkdotnet.org/articles/samples/IntroDeferredExecution.html
But want to ask, should I use it? If yes, are this is proper way?
```csharp
[Benchmark]
public void IpAddressToStringLemireConsume()
{
    for (var i = 0; i < test.Length; i++)
    {
        var s = Lemiere.ipv4(test[i]);
        consumer.Consume(s);
    }
}
```

Difference is noticeable IMO

|                         Method |     Mean |
|------------------------------- |---------:|
|              IpAddressToString | 1.083 ms |
|        IpAddressToStringLemire | 1.006 ms |
|       IpAddressToStringConsume | 1.190 ms |
| IpAddressToStringLemireConsume | 1.091 ms |

**Comment by timcassell** [comment]
Consumer does have some small overhead, but if you return the value instead, the overhead will be captured in the overhead measurement.

You could try like this:

```cs
[Benchmark]
public string IpAddressToStringLemire()
{
    string s = "";
    for (var i = 0; i < test.Length; i++)
    {
        s = Lemiere.ipv4(test[i]);
    }
    return s;
}
```
