### ISSUE TITLE
NU1108 Cycle detected. BenchmarkDotnet -> BenchmarkDotNet (>= 0.13.5). BenchmarkDotnet

### ISSUE THREAD

**Issue by maxima120** [dotnet/BenchmarkDotNet#2327]
Created brand new console .NET7 app in VS 2022, trying to install nuget, getting: 

`NU1108 Cycle detected. BenchmarkDotnet -> BenchmarkDotNet (>= 0.13.5). BenchmarkDotnet`

tried to clean solution, restart VS etc. nothing works.

**Comment by AndreyAkinshin** [comment]
@maxima120 the name of your project could not be the same as a name of a NuGet package that you are referencing. It's a "feature" of NuGet, it has nothing to do with BenchmarkDotNet. Just use another name for your project (`BenchmarkDotNet` is reserved), and it will work fine.
