### ISSUE TITLE
`default(object)` takes more time than expected in net7.0

### ISSUE THREAD

**Issue by timcassell** [dotnet/BenchmarkDotNet#2366]
This looks like a runtime issue to me, but @AndreyAkinshin asked me to open an issue here for it.

I observed simply adding a `[GlobalSetup]` to a benchmark class causes `default(object)` to take more time than without it. I only observed this in net7.0 and net8.0, no other runtime, and not with default primitives.

```cs
public class WithGlobalSetup
{
    [GlobalSetup] public void Setup() { }

    [Benchmark] public object DefaultClass() => default;
}

public class WithoutGlobalSetup
{
    [Benchmark] public object DefaultClass() => default;
}
```

|               Type |       Method |      Mean |     Error |    StdDev |    Median |
|------------------- |------------- |----------:|----------:|----------:|----------:|
|    WithGlobalSetup | DefaultClass | 0.8907 ns | 0.1133 ns | 0.2340 ns | 0.8152 ns |
| WithoutGlobalSetup | DefaultClass | 0.0519 ns | 0.0560 ns | 0.0995 ns | 0.0000 ns |

OS is Windows 10 x64
CPU is AMD Phenom II X6 1055T @ 2.8 GHz

**Comment by timcassell** [comment]
> Add [MemoryRandomization] to both classes.

Adding `[MemoryRandomization]` brought the result to a more expected value, but the individual iterations were very sporadic (~4 cycles difference between max and min)

|               Type |       Method |      Mean |     Error |    StdDev | Median |
|------------------- |------------- |----------:|----------:|----------:|-------:|
|    WithGlobalSetup | DefaultClass | 0.1139 ns | 0.0686 ns | 0.1979 ns | 0.0 ns |
| WithoutGlobalSetup | DefaultClass | 0.2354 ns | 0.1322 ns | 0.3899 ns | 0.0 ns |

> Add different amounts of additional methods in the class with different signatures and method bodies (do not annotate them with attributes, just add additional methods to the target class).

Changing `[GlobalSetup]` to `[GlobalCleanup]` had no effect.

Removing `[GlobalSetup]` (still leaving the method, but un-attributed) brought the results more in line with expected.

|          Type |       Method |      Mean |     Error |    StdDev | Median | Code Size |
|-------------- |------------- |----------:|----------:|----------:|-------:|----------:|
| WithGlobalSetup | DefaultClass | 0.0689 ns | 0.0400 ns | 0.1178 ns | 0.0 ns |       3 B |
| WithoutGlobalSetup | DefaultClass | 0.0266 ns | 0.0435 ns | 0.0651 ns | 0.0 ns |       3 B |

Adding more un-attributed methods gave expected results.

|          Type |       Method |      Mean |     Error |    StdDev |    Median | Code Size |
|-------------- |------------- |----------:|----------:|----------:|----------:|----------:|
| ExtraMethods0 | DefaultClass | 0.1549 ns | 0.0814 ns | 0.1786 ns | 0.0834 ns |       3 B |
| ExtraMethods1 | DefaultClass | 0.0463 ns | 0.0545 ns | 0.1051 ns | 0.0000 ns |       3 B |
| ExtraMethods2 | DefaultClass | 0.0000 ns | 0.0000 ns | 0.0000 ns | 0.0000 ns |       3 B |
| ExtraMethods3 | DefaultClass | 0.0021 ns | 0.0054 ns | 0.0105 ns | 0.0000 ns |       3 B |
| ExtraMethods4 | DefaultClass | 0.0100 ns | 0.0242 ns | 0.0418 ns | 0.0000 ns |       3 B |
| ExtraMethods5 | DefaultClass | 0.0806 ns | 0.0616 ns | 0.1475 ns | 0.0000 ns |       3 B |
| ExtraMethods6 | DefaultClass | 0.0528 ns | 0.0553 ns | 0.1225 ns | 0.0000 ns |       3 B |
| ExtraMethods7 | DefaultClass | 0.0971 ns | 0.0606 ns | 0.1167 ns | 0.0834 ns |       3 B |
| ExtraMethods8 | DefaultClass | 0.0096 ns | 0.0211 ns | 0.0375 ns | 0.0000 ns |       3 B |

Changing `[GlobalSetup]` to a random attribute gave expected results.

```cs
public class JustAnAttributeAttribute : Attribute { }
```

|          Type |       Method |      Mean |     Error |    StdDev |    Median | Code Size |
|-------------- |------------- |----------:|----------:|----------:|----------:|----------:|
| ExtraMethods0 | DefaultClass | 0.1527 ns | 0.0768 ns | 0.1854 ns | 0.0822 ns |       3 B |
| ExtraMethods1 | DefaultClass | 0.0454 ns | 0.0431 ns | 0.0831 ns | 0.0000 ns |       3 B |
| ExtraMethods2 | DefaultClass | 0.1311 ns | 0.0733 ns | 0.1826 ns | 0.0425 ns |       3 B |

> Increase the UnrollFactor to 32, 64, 128.

I'm not sure what conclusions can be gleaned from this.

|               Type |       Method | UnrollFactor |      Mean |     Error |    StdDev |    Median | Code Size |
|------------------- |------------- |------------- |----------:|----------:|----------:|----------:|----------:|
|    WithGlobalSetup | DefaultClass |          128 | 0.1825 ns | 0.0833 ns | 0.1963 ns | 0.1205 ns |       3 B |
| WithoutGlobalSetup | DefaultClass |          128 | 0.0000 ns | 0.0000 ns | 0.0000 ns | 0.0000 ns |       3 B |
|    WithGlobalSetup | DefaultClass |           32 | 0.0275 ns | 0.0322 ns | 0.0837 ns | 0.0000 ns |       3 B |
| WithoutGlobalSetup | DefaultClass |           32 | 0.0000 ns | 0.0000 ns | 0.0000 ns | 0.0000 ns |       3 B |
|    WithGlobalSetup | DefaultClass |           64 | 0.2379 ns | 0.0885 ns | 0.1502 ns | 0.2275 ns |       3 B |
| WithoutGlobalSetup | DefaultClass |           64 | 0.0000 ns | 0.0000 ns | 0.0000 ns | 0.0000 ns |       3 B |
|    WithGlobalSetup | DefaultClass |           16 | 0.5273 ns | 0.1212 ns | 0.3554 ns | 0.5343 ns |       3 B |
| WithoutGlobalSetup | DefaultClass |           16 | 0.1955 ns | 0.0743 ns | 0.2070 ns | 0.1333 ns |       3 B |

**Comment by timcassell** [comment]
> Could you please share the actual memory addresses in disasm of the target benchmark methods and the starting addresses of the main benchmarking loops in the generated code?

@AndreyAkinshin How do I do that?

**Comment by adamsitnik** [comment]
I suspect that it's related to code alignment and there is nothing we can do about it. Please see https://github.com/dotnet/BenchmarkDotNet/issues/2138#issuecomment-1270446145

**Comment by AndreyAkinshin** [comment]
@timcassell 
> How do I do that?
The easiest way is to open BenchmarkDotNet solution in Visual Studio, run the target benchmark, attach VS to the benchmarking process, put a breakpoint on the relevant line, and check out the disassembly view.

**Comment by timcassell** [comment]
> The easiest way is to open BenchmarkDotNet solution in Visual Studio, run the target benchmark, attach VS to the benchmarking process, put a breakpoint on the relevant line, and check out the disassembly view.

That doesn't seem useful. I have to use a debug build to do that, and that changes the results.

**Comment by adamsitnik** [comment]
You could also create a custom `DisassemblyDiagnoserConfig` with `printInstructionAddresses: true` and filters set to disassemble the desired method.

https://github.com/dotnet/BenchmarkDotNet/blob/fd2639ff7b9e8353bb48c0eb6668c8bf32d19792/src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoserConfig.cs#L28

https://github.com/dotnet/BenchmarkDotNet/blob/fd2639ff7b9e8353bb48c0eb6668c8bf32d19792/src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoserConfig.cs#L12

**Comment by timcassell** [comment]
That got this result.

## .NET 7.0.7 (7.0.723.27404), X64 RyuJIT SSE3
```assembly
; Benchmarks.WithGlobalSetup.DefaultClass()
       7FF9CD18A120 xor       eax,eax
       7FF9CD18A122 ret
; Total bytes of code 3
```

## .NET 7.0.7 (7.0.723.27404), X64 RyuJIT SSE3
```assembly
; Benchmarks.WithoutGlobalSetup.DefaultClass()
       7FF9CD16A1E0 xor       eax,eax
       7FF9CD16A1E2 ret
; Total bytes of code 3
```

**Comment by timcassell** [comment]
I found the issue and sent a fix. #2374
