### ISSUE TITLE
Multiple MarkdownExporters not possible

### ISSUE THREAD

**Issue by bstordrup** [dotnet/BenchmarkDotNet#2394]
I'm testing BenchmarkDotNet and would like to have the benchmark results exported to both GitHub markdown and Atlassian markdown. But I get the error

```
The exporter BenchmarkDotNet.Exporters.MarkdownExporter is already present in configuration. There may be unexpected results.
```

Is that by intention - and why is it not possible to export to both markdown formats in the same run?

**Comment by adamsitnik** [comment]
> Is that by intention 

I really doubt that, it's most likely a bug on our side.

**Comment by bstordrup** [comment]
The issue is as far as I can see in the `ImmutableConfigBuilder.GetExporters` method. It makes a mergeDictionary by the System.Type - and that will be the same for both the GitHub MarkdownExporter and the Atlassian MarkdownExporter.

If the purpose is to avoid having for example GitHub MarkdownExporter twice in the merged list, I see the logic in going through the lists of exporters and remove duplicates. But it has to be on something else or more that just the System.Type.
