### ISSUE TITLE
How to add data to custom column in iteration cleanup?

### ISSUE THREAD

**Issue by johannesmols** [dotnet/BenchmarkDotNet#2396]
Hi, I have been struggling with creating a custom column for a while now. It seems the only documentation on this is [here](https://benchmarkdotnet.org/articles/configs/columns.html), but that only describes adding a `TagColumn`, which is not very helpful.

My use case is that I am writing to a new file each iteration and want to measure the file size afterwards, displaying it in a column in the summary just like the execution time. However, I had no success in this. It seems like a `MetricColumn` would make most sense, but how do I even add values to that? It takes the values from the summary object, but I don't have access to that in the iteration cleanup?

Help with this would be very appreciated. It seems like a simple thing, but yet the documentation doesn't say anything about it as far as I can tell.

**Comment by adamsitnik** [comment]
Hi @johannesmols 

I am sorry, but it's simply not supported out of the box. PTAL at https://github.com/dotnet/BenchmarkDotNet/issues/784 where some workarounds have been provided and the issue explained in detail.

Closing as duplicate.
