### ISSUE TITLE
Custom MarkdownExporter

### ISSUE THREAD

**Issue by nietras** [dotnet/BenchmarkDotNet#2399]
I'm trying to avoid the GitHub MarkdownExporter highlighting certain rows using Bold. Looking at source code there is an option:

https://github.com/dotnet/BenchmarkDotNet/blob/d058c7b6ff2434e96f177f976a0ce06e1a1643b7/src/BenchmarkDotNet/Exporters/MarkdownExporter.cs#L81

However, there is no way to set this or override. Additionally, one cannot simple create a sub-class for customization as the ctor is private.

https://github.com/dotnet/BenchmarkDotNet/blob/d058c7b6ff2434e96f177f976a0ce06e1a1643b7/src/BenchmarkDotNet/Exporters/MarkdownExporter.cs#L89

Could this not be opened up? So one can reuse these parts?

Are there other ways of avoiding the bolding, and how can I in code get the file names of exported reports?

**Comment by timcassell** [comment]
Making the ctor protected (as well as the Dialect) to make it extensible seems reasonable to me.

**Comment by adamsitnik** [comment]
We could also introduce a method that creates a copy of the current exporter with given strategy, so the users would not need to derive a custom type just to change one thing:

```cs
config.AddExporter(MarkdownExporter.GitHub.With(MarkdownHighlightStrategy.None))
```

**Comment by nietras** [comment]
That could perhaps be a supplemental issue/proposal.
