### ISSUE TITLE
Should StreamLogger be TextWriterLogger?

### ISSUE THREAD

**Issue by nietras** [dotnet/BenchmarkDotNet#2400]
StreamLogger is for some reason (other than name) tied to only being useable with `StreamWriter`, which is just a `TextWriter`, as far as I can tell there is no reason for the implementation to tie into it being a `StreamWriter` and one could easily refactor to `TextWriter` or extracting a base class `TextWriterLogger` with all code, but which allows using a `TextWriter` instead. This would allow exporting to in-memory `StringWriter` instead of having to go through a `MemoryStream`.

https://github.com/dotnet/BenchmarkDotNet/blob/d058c7b6ff2434e96f177f976a0ce06e1a1643b7/src/BenchmarkDotNet/Loggers/StreamLogger.cs#L7-L28

**Comment by timcassell** [comment]
I think it's reasonable to add a `TextLogger` class. Don't rename `StreamLogger`, though, just make it inherit `TextLogger`. Feel free to send a PR.

In the meantime, you can implement your own `ILogger` to do whatever you want.
