### ISSUE TITLE
Dependecy Injection

### ISSUE THREAD

**Issue by fpuglap** [dotnet/BenchmarkDotNet#2401]
Hi, I'm trying to use BenchmarkDotnet to measure the performance of some methods. 

For that, I created a console project and add the necessary dependencies to be able to call those methods of other projects within it.

I am getting the following error:

```
// Build Error: Standard output:
standard error:
MSBuild version 17.5.1+f6fdcf537 for .NET
error CS7036: There is no argument given that corresponds to the required parameter 'class' of 'BenchmarkProject.MyBenchMarkClass(IClass)'
Build FAILED.
     0 Warning(s)
     1 Error(s)
Time Elapsed 00:00:06.51
// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html
```

Does anyone know how I could fix this error?

I'm injecting the dependencies by constructor, but maybe I'm doing something wrong. 

There is any proper way to do this with BenchmarkDotnet?

I wasn't able to find an example in the docs showing how to handle DI, but maybe there are some guidelines covering this scenario.

```
private readonly IClass _class;

public MyBenchMarkClass(IClass class)
    {
        _class = class;
    }
```
    
Thanks!

**Comment by timcassell** [comment]
BenchmarkDotNet does not support dependency injection in the traditional sense. If you want to measure different implementations of `IClass`, you can do so like this:

```cs
[ParamsSource(nameof(IClassSource))]
public IClass _class;

public IEnumerable<object> IClassSource()
{
    yield return new MyClass1();
    yield return new MyClass2();
}
```

Benchmark classes must have a public parameterless constructor. I'm surprised our validators aren't already catching that before starting the build.

**Comment by fpuglap** [comment]
Hey @timcassell, thank you for your fast reply.

The way I found to handle this is as following:

```
[GlobalSetup]
public void Setup()
{
    var services = new ServiceCollection();

    services.AddTransient<IHashesService, HashesService>();
    services.AddTransient<IExternalService, ExternalService>();

    _container = services.BuildServiceProvider();
    _hashesService = _container.GetRequiredService<IHashesService>();
}
```

Where HashesService belongs to another project, and ExternalService is a dependency of the HashesService.

Wasn't able to do the DI by constructor though.

The [GlobalSetup] way solves this issue, but could become messy when you want to measure the performance of a method that is a member of a class with many dependencies.

**Comment by timcassell** [comment]
Since you're dynamically building your dependency graph (at least that's what it looks like to me), then that is the way to do it. Benchmarks are ran in a separate process by default, so it would have to be re-built for every benchmark. You can't inject a dependency from a different process.

**Comment by adamsitnik** [comment]
https://stackoverflow.com/a/73189559/5852046
