### ISSUE TITLE
BenchmarkDotNet requires dotnet cli to be installed (Mac OS)

### ISSUE THREAD

**Issue by jamescrosswell** [dotnet/BenchmarkDotNet#2431]
When running a project with benchmarks in it on macOS 13.5.2, I'm getting:
```
// Validating benchmarks:
// Benchmark TransactionBenchmarks.'Creates a Transaction': Job-NUHUDD(Runtime=.NET 7.0) [SpanCount=1]
//    * BenchmarkDotNet requires dotnet cli to be installed or path to local dotnet cli provided in explicit way using `--cli` argument, benchmark 'TransactionBenchmarks.'Creates a Transaction': Job-NUHUDD(Runtime=.NET 7.0) [SpanCount=1]' will not be executed
```

Running `which dotnet` returns `/usr/local/share/dotnet/dotnet` so I've also tried:
```
dotnet run -c Release --cli /usr/local/share/dotnet/dotnet   
```

Same result there though. 

Some additional info:
```
> dotnet --version
7.0.306

> dotnet --list-sdks
6.0.411 [/usr/local/share/dotnet/sdk]
7.0.306 [/usr/local/share/dotnet/sdk]

> dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by jamescrosswell** [comment]
OK curious... So this doesn't work:
```
dotnet run -c Release -f net7.0 
```

But this does:
```
dotnet build -c Release -f net7.0 
dotnet bin/Release/net7.0/Sentry.Benchmarks.dll
```

I'm not sure what the difference is between the two. Even ` dotnet run -c Release -f net7.0 --no-launch-profile` doesn't work. In any case, that gives me a way to use the tool for the time being. Would be great to understand why `dotnet run` fails though.

**Comment by AndreyAkinshin** [comment]
@jamescrosswell thanks for the report! This problem looks strange. Could you please check if the following code is able to get the .NET SDK version:
```cs
using System.Diagnostics;

using var process = new Process
{
    StartInfo = new ProcessStartInfo
    {
        FileName = "dotnet",
        WorkingDirectory = "",
        Arguments = "--version",
        UseShellExecute = false,
        CreateNoWindow = true,
        RedirectStandardError = true,
        RedirectStandardOutput = true,
        RedirectStandardInput = false
    }
};

try
{
    process.Start();
}
catch (Exception e)
{
    Console.WriteLine(e);
}

var output = process.StandardOutput.ReadToEnd();
process.WaitForExit();
Console.WriteLine(output);
```

**Comment by jamescrosswell** [comment]
Hi @AndreyAkinshin, sorry for the delay and thanks for getting back to me. 

It is indeed yes - currently that spits bacxk `8.0.100-rc.1.23463.5` for me... although when I had the issue originally, I didn't have .NET 8 installed. 

Unfortunately now I'm no longer able to reproduce the issue. Maybe something about installing .NET did it but it could have been other stuff as well (I recently installed the .NET Core 3.1 SDK on my machine as well, for example). It might have to stay a cold case for a while 🤷🏻

**Comment by luismanez** [comment]
Same issue for me on MacOS Sonoma 14.2.1 (MacBook Air M2). Also, when running the snippet provided above, is not working for me:

> System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/Users/my_user/temp/TokenizerBenchmark/dotnet' with working directory '/Users/my_user/temp/TokenizerBenchmark'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Program.<Main>$(String[] args) in /Users/my_user/temp/TokenizerBenchmark/Program.cs:line 23
Unhandled exception. System.InvalidOperationException: StandardOut has not been redirected or the process hasn't started yet.
   at System.Diagnostics.Process.get_StandardOutput()
   at Program.<Main>$(String[] args) in /Users/my_user/temp/TokenizerBenchmark/Program.cs:line 30

These are all my SDKs installed:

> 6.0.403 [/usr/local/share/dotnet/sdk]
6.0.405 [/usr/local/share/dotnet/sdk]
6.0.406 [/usr/local/share/dotnet/sdk]
7.0.100 [/usr/local/share/dotnet/sdk]
7.0.102 [/usr/local/share/dotnet/sdk]
8.0.100 [/usr/local/share/dotnet/sdk]

Also tried this in the command line, but didn't work either:
```dotnet run  -c Release --cli /usr/local/share/dotnet/dotnet```

Thanks!

**Comment by Syphonphilter** [comment]
I get this issue with .NET 8 
 * BenchmarkDotNet requires dotnet SDK to be installed or path to local dotnet cli provided in explicit way using `--cli` argument, benchmark 'LINQBenchmarks.MyMethodToBenchmark: DefaultJob' will not be executed

**Comment by JimmyCushnie** [comment]
For anyone else who stumbles across this thread: for some reason this issue fixed itself for me when I simply created a new benchmark project and used that. The new one worked while the old one didn't. I replaced the old project with the new one. Git reported no changes, but that fixed it. No idea what's going on but hopefully this helps someone else.
