### ISSUE TITLE
BenchmarkDotNet Access Denied Error on WSL2 when Writing to '/mnt/c/DumpStack.log.tmp'

### ISSUE THREAD

**Issue by MeulenG** [dotnet/BenchmarkDotNet#2436]
When running benchmarks using BenchmarkDotNet on WSL2, I encountered an "Access Denied" error. This error prevents the benchmark from completing successfully. The error is:
`Generate Exception: Access to the path '/mnt/c/DumpStack.log.tmp' is denied.`

Additional information:
- Running on Ubuntu 22.04.3 LTS(Jammy Jellyfish) via WSL2.
- Using BenchmarkDotNet v0.13.8.
- .NET SDK version 7.0.111.
- Encountered a warning about running the benchmarks in a DEBUG configuration, but the main concern is the access denied error.`

Logs/output:
![err](https://github.com/dotnet/BenchmarkDotNet/assets/77005584/d5257879-f343-4c73-a332-16becedda56b)
My understanding is that WSL2 doesn't have permissions to read the Dump Stack logging. Is it possible to make it work on WSL2?

**Comment by AndreyAkinshin** [comment]
@MeulenG thanks for the report! Unfortunately, I wasn't able to reproduce the issue. Could you please install BenchmarkDotNet `0.13.9-nightly.20231003.76` from https://www.myget.org/F/benchmarkdotnet/api/v3/index.json , reproduce the problem, and share the new log? (this version reports full stacktrace for this exception).

---
Related: https://stackoverflow.com/questions/73291475/unable-to-use-benchmarkdotnet-on-wsl2-access-to-the-path-mnt-c-dumpstack-log

**Comment by MeulenG** [comment]
Hi, 

Thank you for your answer! Following your instructions, I've installed version `0.13.9-nightly.20231003.76` from `https://www.myget.org/F/benchmarkdotnet/api/v3/index.json` as you instructed! 

After updating my project, I re-ran my benchmarks and encountered the following output:
![logsoutput](https://github.com/dotnet/BenchmarkDotNet/assets/77005584/642ec276-1995-4591-a88b-3d3cc863f240)

I hope this helps, and do tell me if I need to provide more information!

**Comment by AndreyAkinshin** [comment]
@MeulenG thanks for the update!

One more question: do you have a solution file (*.sln) that contains your project or do you have a standalone project without a solution?

**Comment by AndreyAkinshin** [comment]
@MeulenG I hope that I have fixed the issue. Could you please check if `0.13.10-nightly.20231016.88` works for you?

**Comment by MeulenG** [comment]
@AndreyAkinshin I have installed the `0.13.10-nightly.20231016.88` version, and I do get one more warning/error? Although, I'm not quite sure if that's a fault on my end? Here is the logs:
![loggy](https://github.com/dotnet/BenchmarkDotNet/assets/77005584/72445999-5d4b-4c0f-98cb-5d3eb5ec27aa)
But other than this, it runs and does produce the benchmarks!

**Comment by adamsitnik** [comment]
BDN tries to set the process priority to high, when it fails (on Linux it requires to run as root) it prints an error. You can simply ignore it or run as root

**Comment by AndreyAkinshin** [comment]
@adamsitnik what do you think about changing this error to a warning? Motivation:
1. This doesn't prevent benchmarks from running.
2. This is a typical and expected situation.
3. A red line in logs starting with "Failed" looks too confusing and frustrating

**Comment by MeulenG** [comment]
@adamsitnik @AndreyAkinshin  Awesome! It works like a charm now. Thanks for all the assistance!

**Comment by adamsitnik** [comment]
> what do you think about changing this error to a warning?

It's good idea. Moreover we could print it just once, not for every benchmark.
