### ISSUE TITLE
Issue with Params attribute

### ISSUE THREAD

**Issue by chester89** [dotnet/BenchmarkDotNet#2450]
I started benchmarking some code and found that Params attribute doesn't always pick up the values.
To be more specific - it understand that I supplied the values, but fails to inject those into my property.
My benchmark refuse to pick up the values for some reason, which crashes the application.
I generate random numbers to fill an array and use ParamsAttribute to supply different values for array length (I expected `ElementCount` property to have the value). Since it's always 0 => array is always empty - dividing by its length throws DivideByZeroException.
I use .NET 7.0.7 with BenchmarkDotNet 0.13.9. Tried downgrading to 0.13.0 - same issue.
Any ideas how to make it work? 

```
using System.Numerics;
using BenchmarkDotNet.Attributes;

namespace NumericBenchmarks;

[MemoryDiagnoser]
public class RegularMathvsSimd
{
    [Params(100, 1000)] 
    public int ElementCount { get; set; }

    private Random _random = Random.Shared;

    private int[] _arrayOne;
    private int[] _arrayTwo;
    
    public RegularMathvsSimd()
    {               
        _arrayOne = new int[ElementCount];
        _arrayTwo = new int[ElementCount];
        for (int i = 0; i < ElementCount; i++)
        {
            _arrayOne[i] = _random.Next(1, 3000);
            _arrayTwo[i] = _random.Next(1, 3000);
        }
    }
    
    [Benchmark]
    public int RegularAverage()
    {
        var number = 0;
        for (int i = 0; i < _arrayOne.Length; i++)
        {
            number += _arrayOne[i] + _arrayTwo[i];
        }

        return number / (_arrayOne.Length * 2);
    }
    
    [Benchmark]
    public int SimdAverage()
    {
        var vectSize = Vector<int>.Count;
        var sum = 0;

        var index = 0;
        for (index = 0; index < _arrayOne.Length - vectSize; index += vectSize)
        {
            var va = new Vector<int>(_arrayOne, index);
            var vb = new Vector<int>(_arrayTwo, index);
            
            sum += Vector.Sum(va + vb);
        }

        if (index != _arrayOne.Length)
        {
            for (int j = index; j < _arrayOne.Length; j++)
            {
                sum += _arrayOne[j] + _arrayTwo[j];
            }
        }
        
        return sum / (_arrayOne.Length * 2);
    }
}
```

**Comment by chester89** [comment]
Here's a relevant [part of the output](https://github.com/dotnet/BenchmarkDotNet/files/13060528/bm-net-issue.txt)

**Comment by timcassell** [comment]
You're reading the initial value in the constructor. That's not going to work. Use `[GlobalSetup]` instead.

**Comment by chester89** [comment]
I knew I missed something! Thanks a lot, I'll make sure to study the docs more diligently next time
