### ISSUE TITLE
[Feature] Allow copy to generated project InternalsVisibleTo 

### ISSUE THREAD

**Issue by workgroupengineering** [dotnet/BenchmarkDotNet#2454]
If I add InternalsVisibleTo to the benchmark project like this:

```xml
  <ItemGroup Label="InternalsVisibleTo">
    <InternalsVisibleTo Include="Avalonia.Base.UnitTests, PublicKey=$(AvaloniaPublicKey)" />
  </ItemGroup>
```

It should be copied into the generated project

**Comment by timcassell** [comment]
I don't think that would work without the `$(AvaloniaPublicKey)` property also being copied. Perhaps we should expose an API to add custom csproj elements?
