### ISSUE TITLE
Option to write all results to a single file?

### ISSUE THREAD

**Issue by jskeet** [dotnet/BenchmarkDotNet#247]
Having an output file per test is useful for examining the results by hand, but it makes it harder to process by machine - you have to find all the relevant files, make sure you don't bring in any from previous runs etc. It would be nice to have a "single result file" mode. Admittedly not all exporter formats may support this - but JSON certainly would...

**Comment by AndreyAkinshin** [comment]
I have the following thoughts here. Now `BenchmarkSwitcher` returns `IEnumerable<Summary>`. It could return some kind of `MergedSummary` which is an `inheritor` of usual `Summary` (it provides merged Benchmarks, Reports, and so on) and contains an additional property with a list of child summaries. If you have `MergedSummary`, you could apply any kind of exporters for this. For example:
```cs
var mergedSummary = new BenchmarkSwitcher(typeof(Program).GetTypeInfo().Assembly).Run(args);
JsonExporter.FullCompressed.ExportToFiles(mergedSummary);
```
@jskeet, Is it ok for you? We could try to come up with a default wait to export it, but it's not obvious how to merge exporters it because different benchmark types could have different sets of specified exporters.

**Comment by jskeet** [comment]
@AndreyAkinshin: I think it would be good to be able to specify this on the command line - if you specify a merged exporter, that's what gets used; if you specify an individual one, it exports to individual files. I'd rather not hard-code the output into the `Main` method, basically. But aside from that, it sounds fine.

**Comment by AndreyAkinshin** [comment]
> if you specify a merged exporter, that's what gets used; if you specify an individual one, it exports to individual files. 

Make sense to me. So, we could create `MergedSummary` internally and export it automatically using only exporters from the config which was constructed based on `args`. Right?

**Comment by AndreyAkinshin** [comment]
> if you specify a merged exporter, that's what gets used; if you specify an individual one, it exports to individual files. 

Make sense to me. So, we could create `MergedSummary` internally and export it automatically using only exporters from the config which was constructed based on `args`. Right?

**Comment by jskeet** [comment]
Um, maybe? I don't know any of the internals :)

**Comment by GeertvanHorrik** [comment]
I've built something like that:

https://github.com/Catel/Catel.Benchmarks

It allows you to create a project per target version and it will generate 1 big summary for all runs:

https://github.com/Catel/Catel.Benchmarks/blob/develop/results/summary.md

It's all MIT so take whatever you need ;-) Would be even better if BenchmarkDotNet would have this as an xplat console runner so everyone could use it. Happy to contribute, just not sure if they are interested in such a thing, but I think the summaries are extremely useful.

**Comment by Kavignon** [comment]
I could take it!

**Comment by adamsitnik** [comment]
It's possible to export to a single file by using `--join`:

https://benchmarkdotnet.org/articles/samples/IntroJoin.html#sample-introjoin
