### ISSUE TITLE
Issue with Benchmark.Net

### ISSUE THREAD

**Issue by Syphonphilter** [dotnet/BenchmarkDotNet#2486]
Hi Andrey, Thanks for your Work on Benchmark.net, 🔥 when running a benchmark i get the following issue.

```BenchmarkDotNet requires dotnet SDK to be installed or path to local dotnet cli provided in explicit way using `--cli` argument, benchmark 'LINQBenchmarks.MyMethodToBenchmark: DefaultJob' will not be executed```

I use  dotnet version ```8.0.100```

Why so?

Thanks!

_Originally posted by @Syphonphilter in https://github.com/dotnet/BenchmarkDotNet/issues/2431#issuecomment-1865383120_

**Comment by Syphonphilter** [comment]
Hey, Andrey.

I found the solution to issue #2486
In my vs code, including ``` "dotnet.path": "/usr/local/share/dotnet/dotnet",``` fixed my problem.

Thanks

**Comment by isthistechsupport** [comment]
Hi @Syphonphilter,

I'm also having this issue. Could you please elaborate on what steps did you take to fix it? Where did you include the referenced string?

Thanks a lot

**Comment by Syphonphilter** [comment]
In your VS Code, Open settings.json and add this line  `"dotnet.path": "/usr/local/share/dotnet/dotnet",`

**Comment by JimmyCushnie** [comment]
For anyone else who stumbles across this thread: for some reason this issue fixed itself for me when I simply created a new benchmark project and used that. The new one worked while the old one didn't. I replaced the old project with the new one. Git reported no changes, but that fixed it. No idea what's going on but hopefully this helps someone else.
