### ISSUE TITLE
error CS1061:

### ISSUE THREAD

**Issue by dr007** [dotnet/BenchmarkDotNet#250]
/Users/ahsanulhaq/src/EmptyWeb1/Program.cs(16,18): error CS1061: 'ConfigurationBuilder' does not contain a definition for 'AddCommandLine' and no extension method 'AddCommandLine' accepting a first argument of type 'ConfigurationBuilder' could be found (are you missing a using directive or an assembly reference?)
/Users/ahsanulhaq/src/EmptyWeb1/Startup.cs(24,27): error CS1061: 'ILoggerFactory' does not contain a definition for 'AddConsole' and no extension method 'AddConsole' accepting a first argument of type 'ILoggerFactory' could be found (are you missing a using directive or an assembly reference?)
/Users/ahsanulhaq/src/EmptyWeb1/Startup.cs(28,21): error CS1061: 'IApplicationBuilder' does not contain a definition for 'UseDeveloperExceptionPage' and no extension method 'UseDeveloperExceptionPage' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)

Compilation failed.
    0 Warning(s)
    3 Error(s)

Time elapsed 00:00:01.2566764

Ahsans-MacBook-Pro:src ahsanulhaq$

**Comment by AndreyAkinshin** [comment]
Hi @dr007,

How does these errors relate to BenchmarkDotNet?
