### ISSUE TITLE
Add MsBuildArguments command line option

### ISSUE THREAD

**Issue by VA-01** [dotnet/BenchmarkDotNet#2509]
Is there any additional documentation on how to set the PackagesRestorePath? Is it possible to pass it as a command line argument or adjust the runner options without having to configure an entire Job? Thanks.

**Comment by timcassell** [comment]
Currently, no. The only way is to configure a job with MsBuildArguments. We do support `--wasmArgs` as a command line argument, but no support for MsBuild atm. It could be added.

**Comment by timcassell** [comment]
Sorry, I just checked and saw we do support `--packages` command line option for this purpose.

```
The directory to restore packages to (optional).
```
