### ISSUE TITLE
Add validation warning for `sealed` classes containing benchmarks

### ISSUE THREAD

**Issue by JeppeSN** [dotnet/BenchmarkDotNet#2516]
It is easy to create benchmarks, for example as shown in [README.md](https://github.com/dotnet/BenchmarkDotNet/blob/master/README.md):
```
// attributes here
public class Md5VsSha256
{
  // setups and benchmarks here
}
```

However, if I choose to *seal* my class, as in:
```
public sealed class Md5VsSha256
```
then if I use `BenchmarkSwitcher.FromAssemblies(...).Run(...)` to run my benchmarks, then the class is no longer discovered.

Is there any technical reason for this behavior?

It seems that if you go to [src/BenchmarkDotNet/Extensions/ReflectionExtensions.cs line 159](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Extensions/ReflectionExtensions.cs#L159) and remove the `.IsSealed` criterion, then this should work?

In the project I am working in, we prefer to make all types `sealed` unless they are specifically designed to be base classes, and this practice improves performance in general, so it is a shame if classes containing benchmarks cannot also be `sealed`.

**Comment by timcassell** [comment]
> Is there any technical reason for this behavior?

Your benchmark class cannot be sealed because BDN generates a class that inherits it in order to actually run the benchmarks. https://github.com/dotnet/BenchmarkDotNet/blob/e6fdc6b3c4d540983641f5aeca9c93308dc0da7a/src/BenchmarkDotNet/Templates/BenchmarkType.txt#L2

**Comment by timcassell** [comment]
Perhaps it would be better to display a warning rather than ignore it silently.

**Comment by JeppeSN** [comment]
@timcassell, All right, my question was based on general ignorance, and this is clearly much more complex than I had imagined.

There are likely a variety of different ways BenchmarkDotNet could be used. In our use, it seems the template was _not_ used. But then I did not actually have the attribute `[SimpleJob]` on my class (called `Md5VsSha256` in the example).

After having seen the template `Templates/BenchmarkType.txt`, if I do include `[SimpleJob]`, and also introduce an evil member like:
```csharp
public int BenchmarkDotNet { get; set; }
```
to make sure the code in the template will not compile, I do see output indicating the compile-time error, so I can see that a template is used then. However (removing the evil `BenchmarkDotNet` property), if I make a check in the constructor:
```csharp
public Md5VsSha256()
{
    if (GetType() != typeof(Md5VsSha256))
    {
        throw new InvalidOperationException("See, template type is instantiated.");
    }
}
```
then I do not see any indication that the line 6 from the template, `BenchmarkDotNet.Autogenerated.Runnable_$ID$ instance = new BenchmarkDotNet.Autogenerated.Runnable_$ID$(); // do NOT change name "instance" (used in SmartParamameter)`, is run, _in my use_.

Anyway, this is probably not worth pursuing further. Thank you for your answer.

**Comment by adamsitnik** [comment]
We should reconsider writing the code analyzers for BDN, similar to what xUnit provides.

**Comment by timcassell** [comment]
@ketanpkolte Sure, I assigned you.

**Comment by ketanpkolte** [comment]
I was looking into BenchmarkDotnet>Analysers, 
I found "AnalyserBase" should i use this over DiagnosticAnalyzer
if yes will Conclusion.CreateWarning create a warming in console or at IDE GUI level?

**Comment by timcassell** [comment]
I think the logic for this should be added to `CompilationValidator`.

We don't currently have analyzers for IDE. That would be #389.

**Comment by ketanpkolte** [comment]
Hi,

I’ve written code to check for unsupported class modifiers, but I need some help with testing.

- For "IsNotPublic", passing a private class throws an exception. Could you guide me on how to handle this?
- How should I test the "IsRunnableGenericType"?

The tests are in CompilationValidatorTests > Benchmark_Class_Modifiers. 
You can check the code here: [https://github.com/ketanpkolte/BenchmarkDotNet/tree/2516](url)

Also, I'm monitoring the console for errors while using Benchmark, but I’m unsure when this compilation error will be displayed. Could you clarify when this occurs?

**Comment by timcassell** [comment]
> * For "IsNotPublic", passing a private class throws an exception. Could you guide me on how to handle this?

I need more details to be able to answer that.

> * How should I test the "IsRunnableGenericType"?

```cs
[InlineData(typeof(BenchmarkClass<PublicClass>), false)]
[InlineData(typeof(BenchmarkClass<>), true)]
```

Also, you should separate the validations for each of those cases and provide a specific error message.

**Comment by ketanpkolte** [comment]
While testing private and generic classes I am getting **InvalidBenchmarkDeclarationException**

For **Private**: BenchmarkDotNet.Running.InvalidBenchmarkDeclarationException: 'BenchmarkDotNet.Tests.Validators.CompilationValidatorTests+MyPrivateClass containing Benchmark method NonStaticMethod has incorrect access modifiers.
Declaring type must be public.'

For **Generic**: InvalidBenchmarkDeclarationException($"{type.Name} is generic type definition, use BenchmarkSwitcher for it");

**Comment by timcassell** [comment]
For the private exception, you can just remove it. That predated the validators. Actually, most of those asserts can probably be moved to the validator, but it doesn't all need to be done at once.

For the generic exception, what code are you using to hit that?

**Comment by timcassell** [comment]
Maybe just leave the generics as they are. It looks much more complicated, as it could be valid to pass a closed generic type without type attributes to `BenchmarkRunner`. So just do the `IsSealed` and `IsPublic` validation.
