### ISSUE TITLE
Reference assemblies are searched in the wrong location

### ISSUE THREAD

**Issue by msedi** [dotnet/BenchmarkDotNet#2524]
Currently our reference assemblies are created in 

```
obj\<assemblyName>\x64\Release\ref
obj\<assemblyName>\x64\Release\refint
```
when running BDN I get following error

`CSC : error CS0006: Metadata file 'E:\TFS\IPIPE\_Build\obj\ipipe.Cuda.Benchmarks\Release\ref\ipipe.Cuda.Benchmarks.dll' could not be found [E:\TFS\IPIPE\_Build\Release\Assemblies\ipipe.Cuda.Benchmarks\a772d8c0-9905-4479-adf3-caf4dad0684c\BenchmarkDotNet.Autogenerated.csproj]`

Is there any hint why BDN looks in this location? We are using our own Directory.Build.props with a rerouting of the output, could this be a reason?

**Comment by timcassell** [comment]
> We are using our own Directory.Build.props with a rerouting of the output, could this be a reason?

Yes, this is the reason. This will be fixed in the next release. In the meantime, you can use the latest [nightly](https://benchmarkdotnet.org/articles/guides/nuget.html#nightly) version.
