### ISSUE TITLE
Unable to use `wasm` or `monoaotllvm` as runtime

### ISSUE THREAD

**Issue by caaavik-msft** [dotnet/BenchmarkDotNet#2540]
With the recent change from https://github.com/dotnet/BenchmarkDotNet/pull/2523, we are unable to use `wasm` or `monoaotllvm` in the `--runtimes` argument like we could previously because the DotNetSdkValidator does not support it. Instead we have to use one which has the .NET version in it such as `wasmnet9.0` or `monoaotllvmnet9.0`. I am not sure what the correct fix for this should be, but the dotnet/performance repo uses these two values for our WASM and Mono AOT LLVM runs, so this is blocking our ability to merge in the latest BDN.

**Comment by LoopedBard3** [comment]
Put up a PR that should fix the issue for both wasm and monoaotllvm: https://github.com/dotnet/BenchmarkDotNet/pull/2541
