### ISSUE TITLE
How to change the time display mode from microseconds to seconds or milliseconds?

### ISSUE THREAD

**Issue by GooDgRaF** [dotnet/BenchmarkDotNet#2544]
For example, I have the following part of the table from Benchmark. Could I change 'us' to 'ms' or 's'?
![image](https://github.com/dotnet/BenchmarkDotNet/assets/53288934/63d21176-2d0f-4402-9e1f-e81c39387585)

Or, if the method took a long (not 'ns') time to run, then I should not use benchmarks and just use Stopwatch?

**Comment by timcassell** [comment]
It usually scales to the smallest result. You can force it to use whatever unit you want via summary style in the config. `config.WithSummaryStyle(SummaryStyle.Default.WithTimeUnit(TimeUnit.<WhateverYouWant>))`
