### ISSUE TITLE
Add support for dotnet-script

### ISSUE THREAD

**Issue by nczsl** [dotnet/BenchmarkDotNet#2550]
I ran the csx file with dotnet-script and the test results reported an error? Is CS scripting supported now?

```
Unable to find scriptAssembly in E:\netenv\apps\ways2024\ways2024.Support and its subfolders. Most probably the name of output exe is different than the name of the .(c/f)sproj
```

**Comment by timcassell** [comment]
BenchmarkDotNet does not currently support dotnet-script tool for the default toolchain. Contributions are welcome. You could probably make it work with [InProcess](https://benchmarkdotnet.org/articles/configs/toolchains.html#sample-introinprocess) toolchain.
