### ISSUE TITLE
Question about visibility of DotTraceDiagnoser's second constructor

### ISSUE THREAD

**Issue by ricsiLT** [dotnet/BenchmarkDotNet#2554]
Hi,

Not sure how to formulate the question, but I was trying to attach the following attribute to benchmark class:

```
[DotTraceDiagnoser]
public class SqliteDbReadBenchmark
```

This defaults to default nuget portal and that is firewalled away for me. `DotTraceDiagnoser` has a secondary constructor that takes `Uri` as first arg - that would work, but this is invalid C#:

```
[DotTraceDiagnoser(new Uri(""))]
public class SqliteDbReadBenchmark
```

Shouldn't this constructor be hidden? Or `DotTraceDiagnoserAttribute` updated to not take in `Uri`? Or is that just mandatory when creating `Attribute`?

**Comment by gassanosh** [comment]
Probably the type of the parameter could be changed to string. In that case it will possible to specify the url of nuget mirror: https://github.com/dotnet/BenchmarkDotNet/issues/2554
