### ISSUE TITLE
How can I obtain the addition result of two int variables without using a loop for testing?

### ISSUE THREAD

**Issue by ooosan** [dotnet/BenchmarkDotNet#2576]
[Benchmark]
        public void IntAddition()
        {
            int a = 10;
            int b = 20;
            int c = a + b;
        }

The running result displays an average of 0.0043ns, which is too small.

**Comment by timcassell** [comment]
Currently not possible. See #1802.

Also, the code you pasted is likely constant-optimized, so a zero result would be expected. You would need to arguments or fields to prevent constant-optimizations.
