### ISSUE TITLE
Not possible to compute the (Ratio, RatioSD)

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#2591]
### Discussed in https://github.com/dotnet/BenchmarkDotNet/discussions/2584

<div type='discussions-op-text'>

<sup>Originally posted by **sastru** July  2, 2024</sup>
![image](https://github.com/dotnet/BenchmarkDotNet/assets/171028164/89ca5709-83d2-46f0-b54d-bb79ac193e59)

I get the warning
> // * Warnings *
BaselineCustomAnalyzer
  Summary -> A question mark '?' symbol indicates that it was not possible to compute the (Ratio, RatioSD) column(s) because the baseline value is too close to zero.

I suspect it is because somehow all my benchmarks are separated by a line, why? how can I fix that?

Program.cs
```
BenchmarkRunner.Run<Benchmarks>(DefaultConfig.Instance
    .AddJob(Job.InProcess
        .WithStrategy(RunStrategy.Monitoring)
        .DontEnforcePowerPlan()
        .WithToolchain(new InProcessEmitToolchain(true))
    ), args);
```

Benchmarks.cs
```
...
[Benchmark(Baseline = true)]
[Arguments(1028, 1028, false, OutsideQueryVariation.Default, false, null, 30)]
public async Task Baseline(int limit, int totalCount, bool includeOutsidePoints, OutsideQueryVariation useOutsideQueryVariation, bool useMaxOutsideInterval, int? status, int timeSpanInMin) { .. }

[Benchmark]
[Arguments(1028,  1028,  false, OutsideQueryVariation.Default,  false, 192,  30)]
[Arguments(1028,  1030,  true,  OutsideQueryVariation.Default,  false, null, 30)]
public async Task Benchmark(int limit, int totalCount, bool includeOutsidePoints, OutsideQueryVariation useOutsideQueryVariation, bool useMaxOutsideInterval, int? status, int timeSpanInMin) { .. }
```</div>

**Comment by timcassell** [comment]
Let's use this issue to track fixing the warning message. Use #2596 to track improving the usability of baselines with arguments.
