### ISSUE TITLE
Cannot build Native AOT 8.0 on all platforms

### ISSUE THREAD

**Issue by swtrse** [dotnet/BenchmarkDotNet#2593]
This is in terms of the issue a copy of https://github.com/dotnet/BenchmarkDotNet/issues/2548.

However, since I run into this problem on windows, Linux and mac and based on my code review this would be a problem for all platforms.
Since all platforms are affected, I created this issue because it should be taken care of with higher priority.

**Comment by swtrse** [comment]
AOT 9.0 do also fail with the same reason

**Comment by swtrse** [comment]
As a workaround. Since the Attribute is not working but if you put that logic into a customConfig it will work.
Just for example
```
public IEnumerable<Job> GetJobs()
{
	Runtime[] runtimes = [CoreRuntime.Core80, CoreRuntime.Core90, NativeAotRuntime.Net80, NativeAotRuntime.Net90];
	foreach (var runtime in runtimes)
	{
		//var sourceJob = Job.LongRun;
		var sourceJob = Job.ShortRun;
		var baseJob = sourceJob.WithRuntime(runtime).WithId($"{sourceJob.Id}-{runtime.Name}").WithToolchain(new InProcessEmitToolchain(TimeSpan.FromHours(24D), true));
		yield return baseJob;
	}
}
```

**Comment by timcassell** [comment]
Is it working on v0.14.0? (https://github.com/dotnet/BenchmarkDotNet/issues/2548#issuecomment-2347074191)

**Comment by swtrse** [comment]
Seems to be working now
