### ISSUE TITLE
Difference of ShortRunJob, MediumRunJob, LongRunJob, VeryLongRunJob

### ISSUE THREAD

**Issue by swtrse** [dotnet/BenchmarkDotNet#2595]
Hello,

I did not find any documentation on that matter.
What is the difference between this Jobs?
When should I choose a specific Attribute based on Execution time?

Is there an option to choose one of these according to params of the benchmark?
The reason I ask is that I have a set of Benchmarks Adding 1, 10, 100, 1000.....,100000000 items to a collection, to get the performance impact regarding the number of items hold in the collection.
However, this is one Benchmark class with one method and a parameter getting these values.
Currently the Class is marked with ShortRunJob.
However at least with 10.000 items I would not consider this Benchmark a ShortRunJob.
Or does it even matter? Maybe it is more important to run all Benchmarks with the same JobType for comparison?

**Comment by swtrse** [comment]
Ok, forget, I did miss the real meaning.
As I found out the difference in in the predefined IterationCount, LaunchCount, WarmupCount settings

**Comment by adamsitnik** [comment]
> As I found out the difference in in the predefined IterationCount, LaunchCount, WarmupCount settings

When it comes to these settings you can find the explanation here: https://benchmarkdotnet.org/articles/guides/how-it-works.html
