### ISSUE TITLE
Suggestion: use GLAD for memory diagnostics.

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#261]
As Maoni Stephens [just announced](https://blogs.msdn.microsoft.com/maoni/2016/09/19/556/), the GLAD is available as open source and it's looks like it's going to support .net core. Sadly there's no nuget package, but I've created [issue for it](https://github.com/Microsoft/perfview/issues/121).

[Long story](https://blogs.msdn.microsoft.com/maoni/2015/11/20/are-you-glad/) short, the GLAD is a subset of  [perfiew](https://github.com/Microsoft/perfview) tool API that uses ETW and provides info about GCs, allocations and much more.
This should simplify the `MemoryDiagnoser`'s code and should enable more diagnosers in future (in fact, anything that can be analysed by perfView, disk IO and JIT events as example).

**Comment by goldshtn** [comment]
Not sure why this is interesting. It's basically the TraceEvent library but with some additional parsing on top (and the existing MemoryDiagnoser already uses TraceEvent). All Windows kernel and CLR ETW events can be processed with TraceEvent without any of the new code that just got published on GitHub, AFAICT.

**Comment by ig-sinicyn** [comment]
@goldshtn yep, GLAD just provides a typed API for the ETW events but there's a lot of it:) For example, here's [GC stats](https://github.com/Microsoft/perfview/blob/master/src/TraceEvent/Computers/TraceManagedProcess.cs#L3408), [inlining failures](https://github.com/Microsoft/perfview/blob/master/src/TraceEvent/Computers/TraceManagedProcess.cs#L3304) or [JIT info](https://github.com/Microsoft/perfview/blob/master/src/TraceEvent/Computers/TraceManagedProcess.cs#L3315) available out-of-the-box.

**Comment by AndreyAkinshin** [comment]
@mattwarren, what do you think?

**Comment by goldshtn** [comment]
AFAIK most of this stuff is natively available in TraceEvent's CLR parser.

**Comment by mattwarren** [comment]
My understanding is that other than a slightly higher level C# object model, the main thing that the GLAD API gives you is more info about GC pauses. If you just use the Trace Event parser you have to do the calculations yourself, as I did in my post [Visualising the .NET Garbage Collector](http://mattwarren.org/2016/06/20/Visualising-the-dotNET-Garbage-Collector/)

So I agree with @goldshtn, I'm not sure what this buys us over what we already have, but I probably need to look at GLAD a bit more to see where it differs from TraceEvents CLR parser?
