### ISSUE TITLE
Wrong Measurements and Warnings

### ISSUE THREAD

**Issue by swtrse** [dotnet/BenchmarkDotNet#2615]
After Running an Benchmark I got This Warnings at the end
```
// * Warnings *
ZeroMeasurement
  BenchmarkFlatPrefill10000<UInt256>.SortedList: ShortRun-.NET 9.0      -> The method duration is indistinguishable from the empty method duration
  BenchmarkFlatPrefill10000<UInt256>.SortedList: ShortRun-NativeAOT 8.0 -> The method duration is indistinguishable from the empty method duration
  BenchmarkFlatPrefill10000<UInt256>.SortedList: ShortRun-.NET 8.0      -> The method duration is indistinguishable from the empty method duration
```

However when looking at the benchmark exports
![image](https://github.com/user-attachments/assets/966cd734-d741-405f-8e64-21d1feb29f4d)
This are hardly the values of an empty method.

I can provide the whole solution for analysis if that helps just not publicly.

**Comment by adamsitnik** [comment]
> I can provide the whole solution for analysis if that helps just not publicly.

**Comment by swtrse** [comment]
Just give me a few days I have to rerun the benchmark since I deleted the logs while adding new benchmarks and the benchmark needs roughly 3 days to complete

**Comment by timcassell** [comment]
3 days?! Can't you just filter the benchmark to repro?

**Comment by swtrse** [comment]
3 days is the filtered version. It is not my fault that preparation for the benchmark takes this long. The Benchmark itself only takes nanoseconds ;).
To be clear I do not now what exactly took so long. All my custom code runs in quick (GlobalSetup and IterationSetup), even with debugger hooked. The time is lost somewhere inside BenchmarkDotNet.

**Comment by timcassell** [comment]
Maybe it's the NativeAOT builds? They can take a very long time. Try removing those. Even then, 3 days is excessive.

**Comment by swtrse** [comment]
I'll try that. This will at leas half the benchmarks I do run

**Comment by swtrse** [comment]
Ok. I was unable to reproduce the warning. I will close this issue and open a new one including the log files if I ever run into it again.

**Comment by AndreyAkinshin** [comment]
Theoretically, such situations may emerge in the bimodal case when a significant number of measurements are around zero, but not all of them. It's not easy to handle them properly since we can't distinguish the true bimodality and situations when several measurements are corrupted due to activities by OS or other processes.

I plan to make the logic behind this warning more sophisticated and properly handle such bimodal states.
