### ISSUE TITLE
Runtime knobs

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#262]
In CoreCLR, we have a [list of knobs](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md) which can be specified.

In Mono, we can set some command line arguments (like `--optimize=OPT` or `--gc=[sgen,boehm]`) and environment variables (like `GC_DONT_GC` or `MONO_GAC_PREFIX`, see also https://linux.die.net/man/1/mono).

I think, it would be cool to have an ability to specify some of knobs/arguments as a part of `Job`.

**Comment by adamsitnik** [comment]
Good idea!

It could be a list of process arguments and a dictionary of environment variables.

Hint for potential contributors: we have an Executor class that is responsible for creating and starting the process. Currently the list of extra arguments for mono is set [here](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Toolchains/Executor.cs#L111)

**Comment by adamsitnik** [comment]
Done ;)

You can specify env variables or mono arguments per job now.

Example:

```cs
public class IntroCustomMonoArguments
{
    public class ConfigWithCustomArguments : ManualConfig
    {
        public ConfigWithCustomArguments()
        {
            // --optimize=MODE , -O=mode
            // MODE is a comma separated list of optimizations. They also allow
            // optimizations to be turned off by prefixing the optimization name with a minus sign.

            Add(Job.Mono.With(new[] { new MonoArgument("--optimize=inline") }).WithId("Inlining enabled"));
            Add(Job.Mono.With(new[] { new MonoArgument("--optimize=-inline") }).WithId("Inlining disabled"));
        }
    }

    [Benchmark]
    public void Sample()
    {
        ShouldGetInlined(); ShouldGetInlined(); ShouldGetInlined();
        ShouldGetInlined(); ShouldGetInlined(); ShouldGetInlined();
        ShouldGetInlined(); ShouldGetInlined(); ShouldGetInlined();
    }

    void ShouldGetInlined() { }
}
```

``` ini

BenchmarkDotNet=v0.10.9.20170903-develop, OS=Windows 10 Redstone 1 (10.0.14393)
Processor=Intel Core i7-6600U CPU 2.60GHz (Skylake), ProcessorCount=4
Frequency=2742190 Hz, Resolution=364.6720 ns, Timer=TSC
  [Host]            : .NET Framework 4.7 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2101.1
  Inlining disabled : Mono 5.0.1 (Visual Studio), 32bit 
  Inlining enabled  : Mono 5.0.1 (Visual Studio), 32bit 

Runtime=Mono  
```

 | Method |               Job |          Arguments |       Mean |     Error |    StdDev |
 |------- |------------------ |------------------- |-----------:|----------:|----------:|
 | Sample | Inlining disabled | --optimize=-inline | 19.4252 ns | 0.4406 ns | 0.4525 ns |
 | Sample |  Inlining enabled |  --optimize=inline |  0.0000 ns | 0.0000 ns | 0.0000 ns |

**Comment by adamsitnik** [comment]
For variables it's very similar:

```cs
var variables = new [] { new EnvironmentVariable("VeryNiceKey", "VeryNiceValue") }
Add(job.With(variables));
```

``` ini
BenchmarkDotNet=v0.10.9.20170903-develop, OS=Windows 10 Redstone 1 (10.0.14393)
Processor=Intel Core i7-6600U CPU 2.60GHz (Skylake), ProcessorCount=4
Frequency=2742190 Hz, Resolution=364.6720 ns, Timer=TSC
  [Host]     : .NET Framework 4.7 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.2101.1
  Job-HXYYII : .NET Framework 4.7 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.2101.1

EnvironmentVariables=VeryNiceKey=VeryNiceValue  LaunchCount=1  RunStrategy=ColdStart  
TargetCount=1  UnrollFactor=1  WarmupCount=1  
```

**Comment by adamsitnik** [comment]
@AndreyAkinshin I will add the docs tomorrow. And I will most probably also add .NET Core 2.0 target to BenchmarkDotNet. The problem is that `ProcessStartInfo.EnvironmentVariables` is available for .NET Core 2.0+. Our goal is to set runtime knobs for .NET Core, without support for .NET Core it makes less sense ;)

**Comment by AndreyAkinshin** [comment]
Awesome!
