### ISSUE TITLE
Unable to run benchmark from unit test (using R# test runner) if shadow copy enabled

### ISSUE THREAD

**Issue by m08pvv** [dotnet/BenchmarkDotNet#263]
I run benchmarks from unit tests (it's more convenient for me) and I faced one issue.
After ReSharper update I got "shadow copy" option enabled silently and it was quite surprise to see BenchmarkDotNet exploding.
Steps to reproduce:
- create a simple benchmark and an unit test to run it
- enable "Shadow-copy assemblies being tested" in ReSharper
- run the benchmark from the unit test via ReSharper test runner (or RIDER test runner as well)

Expected behavior:
- benchmark runs successfully or shows some errors

Actual behavior:
- BDN.Auto.exe fails to load assemblies like BenchmarkDotNet.Core and other

**Comment by adamsitnik** [comment]
I am sorry but as the person that is responsible for the compilation toolchains in BenchmarkDotNet I can't see any way to fix this issue. Using the folder of the current exe gives us a lot of benefits (we can take advantage of copyToOutput, we have all required dlls copied by msbuild for us so we don't have loading issues). With shadow copy enabled it's not possible ;/ I must close it and mark as "wontfix"

**Comment by dbogatov** [comment]
I also want to run (some) benchmarks from unit tests, but I can confirm that `InProcess` toolchain works well for this case.
