### ISSUE TITLE
[Documentation] console-args.md is out of date

### ISSUE THREAD

**Issue by keegan-caruso** [dotnet/BenchmarkDotNet#2654]
I believe this article is out of date: 

https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/guides/console-args.md

For using a local build of ILC packages it recommends `ilcPath` instead of `ilcPackages`. As far as I can tell, `ilcPath` isn't a command line option anymore.

**Comment by timcassell** [comment]
Looks like that was changed in #1997.

**Comment by 5AIPAVAN** [comment]
as a beginner to opensource can i take this @timcassell @keegan-caruso :-)

**Comment by timcassell** [comment]
@5AIPAVAN Sure, I assigned you.
