### ISSUE TITLE
Details - add table for min/max/median/quartiles

### ISSUE THREAD

**Issue by fandrei** [dotnet/BenchmarkDotNet#2659]
It would be much more convenient to read and analyze data from the single table rather than multiple lists of values.

**Comment by timcassell** [comment]
You can manually add the columns via config. Example:

https://github.com/dotnet/BenchmarkDotNet/blob/af8bde44bc1b108444bdea9ee61c2975b3a2dffd/tests/BenchmarkDotNet.IntegrationTests/StatResultExtenderTests.cs#L24-L37

**Comment by fandrei** [comment]
Cool, thanks. However, it would be better with less jumping through the hoops.

**Comment by timcassell** [comment]
You could try adding `[AllStatisticsColumn]` to your benchmark class.
