### ISSUE TITLE
Create a tail call diagnoser

### ISSUE THREAD

**Issue by neoeinstein** [dotnet/BenchmarkDotNet#273]
The implementation should mirror the `InlineDiagnoser` pretty closely, but use the facilities for hooking into JIT Tail Call optimization events. These events are described on MSDN and referenced below.
- [Description of Inlining and Tail Call ETW JIT events](https://blogs.msdn.microsoft.com/clrcodegeneration/2009/05/11/jit-etw-tracing-in-net-framework-4/)
- [Event DTOs](https://msdn.microsoft.com/en-us/library/ff356158%28v=vs.110%29.aspx)

This diagnoser would be extremely helpful for developers of F# code to verify that returns that are function calls are properly in tail position or that recursive functions are properly tailed as well.

**Comment by GeorgePlotnikov** [comment]
Hi guys, is it case still actual? If yes, I'd like to grab it.

**Comment by adamsitnik** [comment]
@GeorgePlotnikov Great! Please let me know if you need any help.

**Comment by GeorgePlotnikov** [comment]
Hi, I've pulled #573

**Comment by adamsitnik** [comment]
@neoeinstein do you know all scenarios which should be covered by the Tail Call Diagnoser?

When F# compiler can use goto? When tail call opt?

**Comment by adamsitnik** [comment]
@GeorgePlotnikov I asked on twitter for some help and @tpetricek provided [this](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1011-warn-on-recursive-without-tail-call.md) link

**Comment by GeorgePlotnikov** [comment]
@adamsitnik it's awesome, sincerely appreciate you

**Comment by adamsitnik** [comment]
@GeorgePlotnikov big thanks for doing this! I checked your new diagnoser and it work very well!

Fixed by #573 and #598

**Comment by GeorgePlotnikov** [comment]
@adamsitnik great, many thanks!
