### ISSUE TITLE
Custom path for mono and dotnet cli

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#306]
Sometimes I want to compare performance between different installation of mono. It would be cool to implement an API like this:
```cs
// The first argument is a title which will be printed in the summary
[MonoJob("mono-4.2", "C:/Program Files/Mono-4.2/bin/mono.exe")]
[MonoJob("mono-4.4", "C:/Program Files/Mono-4.4/bin/mono.exe")]
[MonoJob("mono-4.6", "C:/Program Files/Mono-4.6/bin/mono.exe")]
```
The same feature requests for `dotnet.exe`.

@adamsitnik, what to you think?

**Comment by adamsitnik** [comment]
Good idea, should not be hard to implement (just change the way we call Process.Start?)

**Comment by AndreyAkinshin** [comment]
> just change the way we call Process.Start?

 + API + SummaryColumn

**Comment by zabulus** [comment]
I think this is good candidate for migrating to .config file. It depends on run-time, and shouldn't affect compilation time.

**Comment by adamsitnik** [comment]
Sample usage:

```cs
[ClrJob, CoreJob]
[MonoJob("Mono 4.8.0", @"C:\Program Files\Mono\bin\mono.exe")]
[MonoJob("Mono 4.6.2", @"C:\Program Files (x86)\Mono\bin\mono.exe")]
public class Algo_Md5VsSha256
{
   /* benchmarks removed for brevity */
}	
```

sample results:

```
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   Algo_Md5VsSha256.Md5: Clr(Runtime=Clr)
//   Algo_Md5VsSha256.Sha256: Clr(Runtime=Clr)
//   Algo_Md5VsSha256.Md5: Core(Runtime=Core)
//   Algo_Md5VsSha256.Sha256: Core(Runtime=Core)
//   Algo_Md5VsSha256.Md5: Mono 4.6.2(Runtime=Mono 4.6.2)
//   Algo_Md5VsSha256.Sha256: Mono 4.6.2(Runtime=Mono 4.6.2)
//   Algo_Md5VsSha256.Md5: Mono 4.8.0(Runtime=Mono 4.8.0)
//   Algo_Md5VsSha256.Sha256: Mono 4.8.0(Runtime=Mono 4.8.0)
```

``` ini

BenchmarkDotNet=v0.10.2.0-develop, OS=Microsoft Windows 10.0.14393
Processor=Intel(R) Core(TM) i7-6600U CPU 2.60GHz, ProcessorCount=4
Frequency=2742190 Hz, Resolution=364.6720 ns, Timer=TSC
dotnet cli version=1.0.0-rc4-004771
  [Host]     : .NET Core 4.6.24628.01, 64bit RyuJIT
  Clr        : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1586.0
  Core       : .NET Core 4.6.24628.01, 64bit RyuJIT
  Mono 4.6.2 : Mono 4.6.2 (Visual Studio built mono), 32bit 
  Mono 4.8.0 : Mono 4.8.0 (Visual Studio built mono), 64bit 


```
| Method |        Job |    Runtime |        Mean |     StdDev |      Median | Scaled | Scaled-StdDev | Allocated |
|------- |----------- |----------- |------------ |----------- |------------ |------- |-------------- |---------- |
|    Md5 |        Clr |        Clr |  23.2459 us |  0.9337 us |  23.3425 us |   1.00 |          0.00 |     112 B |
| Sha256 |        Clr |        Clr | 111.8421 us |  2.4760 us | 110.6653 us |   4.82 |          0.21 |     188 B |
|    Md5 |       Core |       Core |  21.4333 us |  0.5074 us |  21.1727 us |   1.00 |          0.00 |      80 B |
| Sha256 |       Core |       Core |  50.1553 us |  1.2729 us |  49.7332 us |   2.34 |          0.08 |     114 B |
|    Md5 | Mono 4.6.2 | Mono 4.6.2 |  45.1584 us |  1.0023 us |  45.5757 us |   1.00 |          0.00 |       N/A |
| Sha256 | Mono 4.6.2 | Mono 4.6.2 | 168.4400 us |  3.7425 us | 170.4372 us |   3.73 |          0.11 |       N/A |
|    Md5 | Mono 4.8.0 | Mono 4.8.0 |  40.4432 us |  0.9094 us |  40.2218 us |   1.00 |          0.00 |       N/A |
| Sha256 | Mono 4.8.0 | Mono 4.8.0 | 155.5073 us | 12.9351 us | 151.4520 us |   3.85 |          0.33 |       N/A |
```

**Comment by adamsitnik** [comment]
@AndreyAkinshin I implemented only the Mono part. If people want to use custom .NET Core version they can use our `ProjectJsonCoreToolchain.NetCoreApp20` or `CsProjCoreToolchain.NetCoreApp12` or just create the toolchain by calling `toolchain.From(settings)`

**Comment by AndreyAkinshin** [comment]
@adamsitnik, thanks! Lookg great!
Could you also add a few examples in our documentation?

**Comment by adamsitnik** [comment]
@AndreyAkinshin I added the docs + disabled the Memory Diagnoser by default. It was the last thing for me for `0.10.3` (I am ready for the release).

**Comment by AndreyAkinshin** [comment]
Great, thanks! Then I will check all the environment and project types again and release new version soon.
@adamsitnik, one last thing: could you also update the changelog in our wiki?

**Comment by adamsitnik** [comment]
@AndreyAkinshin I updated the changelog.
