### ISSUE TITLE
Diagnosers don't export data to the measurements.csv files

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/BenchmarkDotNet#309]
Below a short discussion on gitter:

@GeertvanHorrik 

> Nov 27 22:05
> @adamsitnik been adding this to my benchmarking solution. I can see the output in the console, but am interested in this on disk somewhere. I checked out the code for the diagnoser implementations, but it only outputs to the log? I would especially be interested to have these values in measurements.csv

 
@adamsitnik 

> 12:04
> @GeertvanHorrik you are right, this is a bug. I just checked and the list of columns for CsvMeasurementsExporter is hardcoded.

The solution is not to hard-code the columns :-)

If needed, I am happy to provide a PR.

**Comment by adamsitnik** [comment]
@GeertvanHorrik thanks for the report, I have fixed that, should be on our CI soon

**Comment by GeertvanHorrik** [comment]
@adamsitnik thanks for the fast fix. For me this works fine, but it's a bit inconsistent. For other columns whitespaces are replaced by _, for these 4 columns they are not. I can work with them, but just wanted to let you know.

**Comment by adamsitnik** [comment]
@GeertvanHorrik good catch! I have pushed another commit with the fix for spaces vs '_'

**Comment by GeertvanHorrik** [comment]
Running the first benchmarks with memory pressure comparison amongst versions as well, thanks for implementing this, much appreciated 👍
