### ISSUE TITLE
RuntimeInformation can be made static and internal

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/BenchmarkDotNet#312]
I was looking for a way to view the specs of the system benchmarks are run on for my multi-version-comparison. During this search, I stumbled upon 

https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Portability/RuntimeInformation.cs#L20

I think the class can be internal static?

Or public static and all members could be static. Then I can re-use this functionality :-)

**Comment by AndreyAkinshin** [comment]
@GeertvanHorrik, thanks for the report. I'm working on this class right now, the API will be improved soon.

**Comment by GeertvanHorrik** [comment]
I was able to use the HostEnvironmentInfo.ToFormattedString which uses this class, so no need to make it public (at least for me).
