### ISSUE TITLE
Missing method System.Collections.Immutable.ImmutableArray when running from F# repl

### ISSUE THREAD

**Issue by hoonzis** [dotnet/BenchmarkDotNet#316]
I am using BenchmarkDotNet to benchmark F# code. Everything works fine if I run the benchmark from console aplication:

    [<EntryPoint>]
    let main argv = 
        let summary = BenchmarkRunner.Run<BinomialBenchmark>();

For some quick tests, I wanted to run the benchmark from F# interactive window and here I get the following exception:

    System.MissingMethodException: Method not found: 'System.Collections.Immutable.ImmutableArray`1<Byte> System.Reflection.Metadata.MetadataReader.GetBlobContent(System.Reflection.Metadata.BlobHandle)'.

It seems that historically this constructor was removed and added back into Collections.Immutable library, but I am using the latest version (1.3) and it should be in. See: http://stackoverflow.com/questions/29273466/where-is-immutablearray

Furthermore this works fine when running the console application. I thought the issue might be in the versions of referenced libraries, so I went over all BenchmarkDotNet related references in my console application and check that I reference the same ones in FSX:

    #r "../packages/BenchmarkDotNet/lib/net45/BenchmarkDotNet.dll"
    #r "../packages/BenchmarkDotNet.Core/lib/net45/BenchmarkDotNet.Core.dll"
    #r "../packages/BenchmarkDotNet.Toolchains.Roslyn/lib/net45/BenchmarkDotNet.Toolchains.Roslyn.dll"
    #r "../packages/BenchmarkDotNet.Diagnostics.Windows/lib/net45/BenchmarkDotNet.Diagnostics.Windows.dll"
    
    #r "../packages/Microsoft.CodeAnalysis.CSharp/lib/net45/Microsoft.CodeAnalysis.CSharp.dll"
    #r "../packages/Microsoft.CodeAnalysis.Common/lib/net45/Microsoft.CodeAnalysis.dll" 
    
    #r "../packages/System.Reflection.Metadata/lib/netstandard1.1/System.Reflection.Metadata.dll"
    #r "../packages/System.Collections.Immutable/lib/netstandard1.0/System.Collections.Immutable.dll"
    #r "../packages/System.Threading.Tasks.Extensions/lib/netstandard1.0/System.Threading.Tasks.Extensions.dll"

I made sure the exact versions are used in the console application. It seems that the some libraries used by the F# interactive runtime are not the same as the once used by the console application.

It seems that similar issue occurs with LinqPad:
https://github.com/dotnet/BenchmarkDotNet/issues/66

**Comment by AndreyAkinshin** [comment]
@adamsitnik, could you take a look?

**Comment by AndreyAkinshin** [comment]
@adamsitnik ?

**Comment by AndreyAkinshin** [comment]
@adamsitnik, is it still an issue?

**Comment by adamsitnik** [comment]
We have dependency to Roslyn, it has dependency to ImmutableCollections, which was already loaded by the parent process (VS). But different version, which was missing some ctor. If VS had updated the dependency to it, it should work. I don't think that it was on our side.

@AndreyAkinshin I think that we can close it and reopen if somebody reports it.

**Comment by hoonzis** [comment]
Sorry for the lack of feedback. Previously I was on net45. I have updated all to net461.

The issue was fixed by my upgrading to net461 and VS referencing the same version of ImmutableCollections as you do. On the other hand I still can't run BenchMarkDotnet inside fsx, you can see the details lower, stacked on a different issue. 

Generally I assume it's not a good idea to run Benchmarking inside F# scripts. I am now using the **#time** directive for quick timing and keep benchmarkdotnet for real benchmarking. Probably not worth your time, checking the error, but if you still wish to just check the two following files:

- benchmark definition
https://github.com/hoonzis/Pricer/blob/master/Pricer.Benchmark/BinomialBenchmark.fs
- scripts that runs it
https://github.com/hoonzis/Pricer/blob/master/Pricer.Benchmark/Benchmarking.fsx

```
// *** Execute ***
// Launch: 1 / 1
// Execute: C:\Users\jfajfr\AppData\Local\assembly\dl3\P8W4T97O.O3Z\ATMG3XP4.WV3\138fedb3\f9d0b1f2_ed61d301\964a1a0e-ec70-4aa5-90fd-2c1c9f479962.exe 
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

// Run, Diagnostic
// Execute: C:\Users\jfajfr\AppData\Local\assembly\dl3\P8W4T97O.O3Z\ATMG3XP4.WV3\138fedb3\f9d0b1f2_ed61d301\964a1a0e-ec70-4aa5-90fd-2c1c9f479962.exe diagnoserAttached
// Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Execute(ILogger logger, Benchmark benchmark, IToolchain toolchain, BuildResult buildResult, IConfig config, IResolver resolver, GcStats& gcStats)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.RunCore(Benchmark benchmark, ILogger logger, ReadOnlyConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver, List`1 artifactsToCleanup)
```
