### ISSUE TITLE
[Raw idea]: Share pseudo-random seed for same run benchmarks?

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#317]
_DISCLAIMER_
I'm not sure the thing is required at all and I have no good thoughs on how to implement it.
So, I just leave it there:)

Okay,  back to topic. We have some benchmarks we run constantly and we want to ensure that results are accurate for wide range of data.

We're doing it via generating random seed, logging it to test output and then creating a new random to be used across rest of the code. Something like this:
```c#
		[Setup]
		public void Setup()
		{
			// Rnd seed to get repeatable results
			var rndSeed = new Random().Next();
			Console.WriteLine($"// ! Rnd seed: {rndSeed}.");

			var rnd = new Random(rndSeed); // using the seed
			_arrayA = Enumerable.Range(0, 128).Select(i => (byte)rnd.Next()).ToArray();

			// ...
		}
```
The issue is, each benchmark method uses its own random seed and it's very tricky to reproduce run with same seeds.
* You have to read large portion of the log to restore mapping from logged rnd seed to the target method (there's `IOrderProvider` so execution order and summary order may differ).
* There's no API to determine target method the setup method is called for. This means you have to create separate set of fields per each method in benchmark, and to init each set using its own rnd seed.

The proposal is, there should be a way to share same pseudo-random rnd seed for all methods in benchmark.

**Simplest possible solution**
Just add a static field to be filled with seed during codegen.
The code will use it like this:
```c#
		[Setup]
		public void Setup()
		{
			// Rnd seed to get repeatable results
			var rndSeed = BenchmarkContext.RndSeed; // name is preliminary
			var rnd = new Random(rndSeed); // using the seed
			_arrayA = Enumerable.Range(0, 128).Select(i => (byte)rnd.Next()).ToArray();

			// ...
		}
```

**Robust solution**
* Add an API to obtain current Job (and current target method), these should be stored as AsyncLocal.
* Add an characteristic to Job to store the rnd seed (have no idea where to put it exactly. `Job.Run.RndSeed`, maybe?).
* Init the characteristic in `BenchmarkConverter.GetFullConfig()` if it was not set earlier.

and the result will be:
```c#
		[Setup]
		public void Setup()
		{
			// Rnd seed to get repeatable results
			var rndSeed = BenchmarkContext.CurrentJob.Run.RndSeed; // name is preliminary
			var rnd = new Random(rndSeed); // using the seed
			_arrayA = Enumerable.Range(0, 128).Select(i => (byte)rnd.Next()).ToArray();

			// ...
		}
```

**Comment by adamsitnik** [comment]
@ig-sinicyn I always hardcode the initial seed, and as far as I know every n-th call to Next will give the same result. Sth like

```cs
void Main()
{
	const int seed = 123456;
	var random1 = new Random(seed);
	var random2 = new Random(seed);
	
	for(int i = 0; i < 1000; i++)
	{
		if(random1.Next() != random2.Next())
		{
			Console.WriteLine("WRONG");
		}
	}
	Console.WriteLine("OK");
}
```

**Comment by ig-sinicyn** [comment]
@adamsitnik 
yep, we're hardcoding seeds on inital stages too. 

But after the code is getting mature we're more interested in good case coverage, not on repeatability. And it works... until it fails:) And then it's pretty tricky to repeat the same run with same seeds.

**Comment by ig-sinicyn** [comment]
Just to clarify: on normal tests we're generating a random seed and write it to the test output.

If the test fails I replace generated seed with logged one and then reproduce the failure.

With benchmarks there's no single place to store generated seed. Each methods runs in separate process so ther's no easy way to pass the seed to it.

**Comment by AndreyAkinshin** [comment]
Sometimes, I use the following approach:
```cs
[Params(1, 2, 3, 4, 5)]
public int RndSeed;
```
It allows:
1. Share the same seed between all the benchmark methods.
2. Check performance on different random sets of input data.
3. Easily view the results for each seed.
4. Introduce several independent seeds.

@ig-sinicyn, does it solve your problem?

Some additional thoughts: Probably it makes sense to implement own `Random` class with a rich set of methods and additional attributes. An example:
```cs
[RndSeeds(1, 2, 3)] // Global seeds
public class MyBench
{
    [Setup]
    public void Setup()
    {
        var rnd = BenchmarkRandom.Create(); // will use specific seed
        array =  rnd.GenerateArray<byte>(128);
    }
    
    [RndSeeds(4, 5, 6)] // Specific set of seeds for this method
    public void Method1()
    {
    }

    // There is no the RndSeeds attribute here, the global values (1, 2, 3) will be chosen
    public void Method2()
    {
    }
}
```
@ig-sinicyn, @adamsitnik, @mattwarren, what do you think?

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin

>@ig-sinicyn, does it solve your problem?

Nope, as I'd expect to use random seed to provide more randomness:)
But the  `BenchmarkRandom.Create()`  will do 👍 

> Some additional thoughts: Probably it makes sense to implement own Random class with a rich set of methods and additional attributes. 

Yep, this will work, if the default `BenchmarkRandom.Create()` will use the same seed for all methods in benchmark and the seed will be logged.

P.S. To be honest, I do not see any point in setting RndSeeds on per-method level, but it's just me : )

**Comment by AndreyAkinshin** [comment]
> I do not see any point in setting RndSeeds on per-method level

An example: it's ok to use a single seed for almost all methods, but we have one tricky methods which we want to run against several seeds.

**Comment by adamsitnik** [comment]
> Probably it makes sense to implement own Random class with a rich set of methods and additional attributes. An example:

@AndreyAkinshin I am not a fan of this idea in general. For in-process BenchmarkRunner it would be simple to implement, but for the regular one not. State management + persistence? + passing it to other process = code complication for a thing that imho is not a part of benchmarking framework.

**Comment by ig-sinicyn** [comment]
@adamsitnik 
I see your point. Will it look better if the seed will be threated as a part of the configuration (like Job, Params, ops per invoke and so on)?

**Comment by AndreyAkinshin** [comment]
@ig-sinicyn, could you explain once again why you don't like a case when the `Seed` is a field with the `Params` attribute?

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin 
Well, the problem is not about how the seed is stored, the problem is about seed randomness.

As far as I understand, your proposal with `[RndSeeds(1, 2, 3)]` assumes the list of seeds is finite and is hardcoded in sources. It's not a good thing as it increases chance that some random combination of the values will not be covered at all.

The second approach with `BenchmarkRandom.Create()` is much better as it allows you to use a new seed for each run of the benchmark and to share the seed for all methods in benchmark (to guarantee that all methods are using the same setup values).

 If the benchmarks are run constantly (exactly our case, we have something like half thousand builds since perftest addition) the chances to catch some corner case increase with each new build.

**Comment by AndreyAkinshin** [comment]
Ok, now I get it. I have the following opinion here: a benchmark should be repeatable. If you run a benchmark 100000 times, you have to get 100000 same results. Repeatability is a fundamental property of a benchmark and we will not provide any legal API which allows to get randomized results.

However, now I'm also working on so-called `ParamsProviders` — special methods which provides params values in runtime. If you are really want to have randomized benchmarks, you will be able to generate random values for `RndSeed`.

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin 
Ok, thanks! The solution with `ParamsProvider` will work for me.

**Comment by adamsitnik** [comment]
Closing, will be tracked as part of #350
