### ISSUE TITLE
[Request] some API to public?

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#319]
Hi!

Can you make the `GcStats` and `Net46Toolchain` internal members public?

Need them to support GC stats in custom engine and to run out-of-process benchmarks using BenchmarkDotNet.Core only, respectively.

**Comment by adamsitnik** [comment]
sure, give me a minute

**Comment by AndreyAkinshin** [comment]
I don't have any objections. The only reason of the internal visibility of some API is the following: we don't want to have public API which no one will use. If you need it for some purpose,s it's definitely should be public.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, mark them with the `PublicAPI` attribute (from `JetBrains.Annotations`). This ensures that someone (probably me =) ) will not make it internal again.

**Comment by adamsitnik** [comment]
@AndreyAkinshin ups I have already pushed the commit. I will add this adnotations other time, most probably I should review the Toolchains and apply it where needed

**Comment by AndreyAkinshin** [comment]
Ok, LGTM. Once I want to publish API reference (based on the xml documentation) and do a visibility review (probably, a lot of method will be internal eventually). `[PublicAPI]` will allow to keep the `public` modifier where it's required.
