### ISSUE TITLE
Add Filling possibility

### ISSUE THREAD

**Issue by zabulus** [dotnet/BenchmarkDotNet#328]
My benchmarks are written to measure time of working with object. The object is mutable, so I need new object every operation run. Currently I've work around this limitation by including construction of an object in operation. Workaround adds time for each operation but because object construction the same in all operations, all operations have the same "added time".
Proposed Filling ability it is new FillAttribute, that works similarly to SetupAttrbiute, but the filling method runs before operation instead before iteration, and filling method run time not affects operation time measurement.

**Comment by AndreyAkinshin** [comment]
Hey @zabulus, sorry for the late response. Could you write a minimal example with the proposed attribute?

**Comment by zabulus** [comment]
I've implemented this in my experiment branch re-using SetupAction:
https://github.com/zabulus/BenchmarkDotNet/blob/experiment/src/BenchmarkDotNet.Core/Templates/UapBenchmarkProgram.txt#L191
https://github.com/zabulus/BenchmarkDotNet/blob/experiment/src/BenchmarkDotNet.Core/Templates/UapBenchmarkProgram.txt#L199
https://github.com/zabulus/BenchmarkDotNet/blob/experiment/src/BenchmarkDotNet.Core/Templates/UapBenchmarkProgram.txt#L209
https://github.com/zabulus/BenchmarkDotNet/blob/experiment/src/BenchmarkDotNet.Core/Templates/UapBenchmarkProgram.txt#L217

Something like that.

More formal propose is something like following:

```
public class ProfileRun
{
    private IItemUnderTesting itemUnderTesting;

    [FillingAction]
    public void FillMethod()
    {
        itemUnderTesting = new ItemUnderTestingImpl();
    }

    [Benchmark]
    {
        itemUnderTesting.MethodForBenchmarking();
    }
}
```

**Comment by AndreyAkinshin** [comment]
I have some additional questions:
1. What the average time of `MethodForBenchmarking` (approximately)?
2. Why you don't want to put `itemUnderTesting = new ItemUnderTestingImpl();` inside the benchmark method?

**Comment by zabulus** [comment]
> inside the benchmark method?

Because I don't want to count time of initialization, only by ```MethodForBenchmarking```

> What the average time of MethodForBenchmarking (approximately)?

For different experiments, different time. For fastest experiment it is about 100-200 ms. 
For more longer could be 1-2 s.

**Comment by AndreyAkinshin** [comment]
And what the approximated average time of the constructor?

Anyway, we will not introduce an additional attribute because users easily can design wrong benchmarks with the help of such API. Probably, [this feature](https://github.com/dotnet/BenchmarkDotNet/issues/325#issuecomment-266531489) (it will be implemented soon) will help you.

**Comment by zabulus** [comment]
> users easily can design wrong benchmarks with the help of such API

Yep, I understand, there are restrictions for such method.

>Anyway, we will not introduce an additional attribute 

I've implemented this in my branch and used for my project, so no problem.

> Probably, this feature (it will be implemented soon) will help you.
Good, I'll take a look
