### ISSUE TITLE
default color of terminal is changed after the run is completed

### ISSUE THREAD

**Issue by tugberkugurlu** [dotnet/BenchmarkDotNet#332]
After running the benchmark, it failed to set the terminal color back to its original color. See the below image (the terminal window at the top shows the original color):

![image](https://cloud.githubusercontent.com/assets/328122/21456522/8dac48e2-c920-11e6-992b-6e19a8cfb844.png)

`dotnet --info`:

```
Tugberks-MBP:workers tugberk$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

This is the code, I have seen this under debug run (which I know is not ideal): https://github.com/tugberkugurlu/DotNetSamples/blob/d7208b396381cdc4516c977c1028889060dc307e/CyberDojo/NumberOfDistinct/BenchmarkTests.cs#L32-L37

**Comment by AndreyAkinshin** [comment]
@tugberkugurlu, thank you for the bug report. Will be fixed.
