### ISSUE TITLE
Support netcoreapp1.0 as well as 1.1

### ISSUE THREAD

**Issue by jskeet** [dotnet/BenchmarkDotNet#334]
Updating to release 0.10.1 broke the Noda Time benchmarking project because the target platform changed to netcoreapp1.1. Did we actually need to do this? netcoreapp1.1 is more of a bleeding edge target, with 1.0 being the long-term support one. I think it would be worth supporting users who don't want to use the bleeding-edge version.

**Comment by adamsitnik** [comment]
@jskeet the main reason for switching to 1.1 was the new `GC.GetAllocatedBytesForCurrentThread` api. Thanks to that we now have  [cross-platform, build-in and very accurate MemoryDiagnoser](https://github.com/dotnet/BenchmarkDotNet/pull/284). I really encourage you to try it ;)

What we recommend to our users is to keep their's libraries targeting 1.0 and update only their benchmarks to 1.1.  I know that this is not a perfect solution, however it lets us keep the code, testing and releases simple.

**Comment by jskeet** [comment]
The downside is that if a user is running their *actual application* using 1.0, then the enhancements in 1.1 are going to give them invalid results, basically. It's great to be able to use `MemoryDiagnoser`, but I think it's more important to allow users to run their code in an environment close to their real one. (As a point of comparison, if there were a great feature which was only available on x86, would we ditch the ability to run under x64? I very much doubt it.)

**Comment by adamsitnik** [comment]
@jskeet I agree with you. Honestly I did not expect any of our .NET Core users to stay with 1.0. Kestrel team/RavenDb guys updated the same day.

Our users can still use 0.10.0 version which had 1.0 support. I am not sure if we should re-add the 1.0 support. This would complicate our code with all the #if defines, testing and releases process and rather very few users would actually use it.

**Comment by halex2005** [comment]
@adamsitnik I offer you to give different version number like 0.11.0 to netapp1.1 release in case the backward compatibility was broken. Do you use [semver for versioning](http://semver.org)?

**Comment by adamsitnik** [comment]
@halex2005 You are right. The problem is that we have already shipped this version, so it's too late. But I have noted this, will avoid it the future.

**Comment by AndreyAkinshin** [comment]
@halex2005, hopefully, we will use semver after 1.0.
