### ISSUE TITLE
Support benchmarking startup performance

### ISSUE THREAD

**Issue by cwensley** [dotnet/BenchmarkDotNet#335]
I am attempting to determine the startup performance of my library ([Portable.Xaml](https://github.com/cwensley/Portable.Xaml)), but it seems there's no option to only run the benchmark a _single_ time.

I've tried using `Job.Dry.With(RunStrategy.ColdStart)` in my Config, but it still is running the benchmark twice.

Investigating the issue, it appears that [this line](https://github.com/dotnet/BenchmarkDotNet/blob/2596471b01083580889b2e8b2de3d8644fb75d55/src/BenchmarkDotNet.Core/Templates/BenchmarkProgram.txt#L89) in the generated benchmark calls the [Engine.Jitting()](https://github.com/dotnet/BenchmarkDotNet/blob/f1f2317dafc663a2fa854ea566ede8befc68ea6d/src/BenchmarkDotNet.Core/Engines/Engine.cs#L77) method, which calls the benchmark, before running the benchmark.

Is there a way to get around this that I'm not seeing?  If not, I think a config option to omit the Jitting() phase would be extremely useful.

Thanks for any help!

**Comment by adamsitnik** [comment]
Hi @cwensley 

I like your idea, I had the same problem few times.

@AndreyAkinshin maybe we should just ommit the jitting for ColdStart? What do you think? Or rather a new strategy? `Once` ?

**Comment by AndreyAkinshin** [comment]
@cwensley, thanks for the report. The bug will be fixed in the next version of BenchmarkDotNet.
@adamsitnik, I will fix it. I almost finished a new `RunStrategy` (which solves one-time Setup/Cleanup) problem. So, I will also disable jitting for ColdStart and the new strategy. Hopefully, will be done on holidays.

**Comment by cwensley** [comment]
Hey guys!

Thanks for the quick response, this will be really useful.  I look forward to the next release to test it out!

Cheers,
Curtis.

**Comment by AndreyAkinshin** [comment]
@cwensley, fixed, will be released soon. Also see [IntroColdStart](https://github.com/dotnet/BenchmarkDotNet/blob/master/samples/BenchmarkDotNet.Samples/Intro/IntroColdStart.cs).
