### ISSUE TITLE
Support Netstandard2.0

### ISSUE THREAD

**Issue by redknightlois** [dotnet/BenchmarkDotNet#336]
Hi guys,

I have some benchmark code that I need to try using the new JIT changes on the development branch for 2.0. Keeping up on the development branches is usual for us  since reporting performance issues later means that we have to wait until future versions arrive (which can take months). For us is more beneficial to pinpoint those issues while they are still developing that version.

Do you see viable to at least provide binaries that can recognize they are running in netstandard2.0 and dont fail (even if I run the benchmark by hand)?

EDIT: BTW this is the actual error (which makes sense :D)

```
An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.

Additional information: Could not load file or assembly 'System.Collections, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Because our dependencies look like this:

```
    "netstandard2.0": {
      "dependencies": {
        "Microsoft.CSharp": "4.4.0-beta-*",
        "Microsoft.Win32.Primitives": "4.4.0-beta-*",
        "System.Collections": "4.4.0-beta-*",
        "System.Collections.Concurrent": "4.4.0-beta-*",
        "System.Console": "4.4.0-beta-*",
        "System.Diagnostics.Contracts": "4.4.0-beta-*",
        "System.Diagnostics.Debug": "4.4.0-beta-*",
        "System.IO.FileSystem": "4.4.0-beta-*",
        "System.Linq": "4.4.0-beta-*",
        "System.Net.WebSockets": "4.4.0-beta-*",
        "System.Reflection.Extensions": "4.4.0-beta-*",
        "System.Reflection.TypeExtensions": "4.4.0-beta-*",
        "System.Resources.ResourceManager": "4.4.0-beta-*",
        "System.Runtime.Extensions": "4.4.0-beta-*",
        "System.Runtime.InteropServices": "4.4.0-beta-*",
        "System.Text.Encoding.Extensions": "4.4.0-beta-*",
        "System.Threading": "4.4.0-beta-*",
        "System.Threading.Thread": "4.4.0-beta-*",
        "System.Threading.Timer": "4.4.0-beta-*",
        "System.Runtime.InteropServices.RuntimeInformation": "4.4.0-beta-*"
      }
    },
```

**Comment by adamsitnik** [comment]
Which framework is targeting the application that is consuming this netstandard2.0 library? .NET 4.6.1 or .NET Core (if so which version)?

Do you have any minimum working example?

**Comment by redknightlois** [comment]
This is all CoreCLR and we are targetting myget development branch for this. 

Hardly minimal, but this is the actual PR to enable the ```Voron.Benchmarks``` assembly to run on 2.0.
https://github.com/ravendb/ravendb/pull/1266/commits/28ed2606ba4fa272cfe3d979637387c319043731

Then we changed the ```Voron.Benchmark``` dependencies to look like this:

```
  "frameworks": {
    "netcoreapp2.0": {
      "dependencies": {
        "BenchmarkDotNet": "0.10.1",
        "Microsoft.CSharp": "4.4.0-beta-*",
        "Microsoft.NETCore.App": {
          "type": "build",
          "version": "1.2.0-*"
        },
        "Voron": "4.0.0-*"
      }
    }
  },
```

**Comment by adamsitnik** [comment]
I have cloned your fork and reproduced the problem. Now working on a fix ;)

**Comment by adamsitnik** [comment]
Ok @redknightlois 

I was not sure what `netcoreapp1.6` was, so I asked on twitter. The reply was:

![image](https://cloud.githubusercontent.com/assets/6011991/21638071/f55a4352-d269-11e6-9cd3-68da157b624f.png)

How to run your benchmarks: please change `netcoreapp1.6` to `netcoreapp1.1` in your `project.json` files.  Keep in mind that `netstandard2.0` should remain unchanged.

My sample results:

``` ini

BenchmarkDotNet=v0.10.1, OS=Windows
Processor=?, ProcessorCount=8
Frequency=2338339 Hz, Resolution=427.6540 ns, Timer=TSC
dotnet cli version=1.0.0-preview2-1-003177
  [Host]     : .NET Core 4.6.24628.01, 64bit RyuJIT [AttachedDebugger]
  Job-WRBCEG : .NET Core 4.6.24628.01, 64bit RyuJIT

Jit=RyuJit  Platform=X64  Runtime=Core  
InvocationCount=1  LaunchCount=1  TargetCount=1  
UnrollFactor=1  WarmupCount=1  

                         Method | KeyLength | RandomSeed | NumberOfTransactions | NumberOfRecordsPerTransaction |      Mean |    StdErr |    StdDev |       Min |        Q1 |    Median |        Q3 |       Max |      Op/s |  Gen 0 | Allocated |
------------------------------- |---------- |----------- |--------------------- |------------------------------ |---------- |---------- |---------- |---------- |---------- |---------- |---------- |---------- |---------- |------- |---------- |
       FillRandomOneTransaction |       100 |         -1 |                 1000 |                          1000 | 3.9902 us | 0.0000 us | 0.0000 us | 3.9902 us | 3.9902 us | 3.9902 us | 3.9902 us | 3.9902 us | 250610.87 | 0.3040 |   1.33 kB |
 FillRandomMultipleTransactions |       100 |         -1 |                 1000 |                          1000 | 9.9671 us | 0.0000 us | 0.0000 us | 9.9671 us | 9.9671 us | 9.9671 us | 9.9671 us | 9.9671 us | 100329.94 | 0.2220 |   1.88 kB |
```

**Comment by redknightlois** [comment]
Are you running that with netstandard2? About netcoreapp1.6 probably I screw up there, our targetting was a mess and unified everything. Highly probable fat finger issue

**Comment by adamsitnik** [comment]
@redknightlois I am not sure if we have the same understanding of what .NET Standard is. It's a set of APIs, that framework can support by implementing all methods from the given api.

[Description](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard) _.NET Standard 2.0 will be implemented by .NET Framework, .NET Core, and Xamarin. For .NET Core, this will add many of the existing APIs that have been requested._

So libraries target netstandard2.0, they use provided APIs but don't know the implementation details. The applications target frameworks (classic .NET, .NET Core, Xamarin) which implement the standard. That's why if you want to benchmark some netstandard2.0 library you have to do this for every framework that implements it.

I know that .NET Standard will be mostly a public api surface of .NET 4.6.1, so there will be no change in classic .NET (only in nuget client). In your case if you want to check the latest JIT changes you should create `netcoreapp1.1` app and add a dependency to the latest version of `Microsoft.NETCore.App` avaiable at the coreclr dev nuget feed. If you mark your benchmark class with `[KeepBenchmarkFiles]` attribute you can analyze the produced executable and see which version it is using.

**Comment by redknightlois** [comment]
Great, will test that. I was under the impression that CoreCLR 2.0 would target ```netstandard2.0``` exclusively.

**Comment by redknightlois** [comment]
Ok, apparently not so easy.
```
warn : Detected package downgrade: System.Text.Encoding from 4.4.0-beta-24904-01 to 4.3.0 
warn :  Voron.Benchmark (>= 4.0.0) -> BenchmarkDotNet (>= 0.10.1) -> BenchmarkDotNet.Core (>= 0.10.1) -> Microsoft.NETCore.App (>= 1.1.0) -> System.Net.Requests (>= 4.3.0) -> System.Net.Http (>= 4.3.0) -> System.IO.FileSystem (>= 4.3.0) -> runtime.win.System.IO.FileSystem (>= 4.4.0-beta-24904-01) -> System.Text.Encoding (>= 4.4.0-beta-24904-01) 
warn :  Voron.Benchmark (>= 4.0.0) -> BenchmarkDotNet (>= 0.10.1) -> BenchmarkDotNet.Core (>= 0.10.1) -> Microsoft.NETCore.App (>= 1.1.0) -> System.Net.Requests (>= 4.3.0) -> System.Net.Http (>= 4.3.0) -> System.Text.Encoding (>= 4.3.0)
```

**Comment by benaadams** [comment]
Have a similar issue when trying to run https://github.com/aspnet/KestrelHttpServer/tree/dev/test/Microsoft.AspNetCore.Server.Kestrel.Performance

```
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0-*",
          "type": "platform"
        }
      }
```
Errors with
> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.2.0-*",
          "type": "platform"
        }
      }
```
Gets a bit further; then errors with
> // *** Execute ***
// Launch: 1 / 3

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Missing a required constructor. (Exception from HRESULT: 0x8013143B)
   at System.Reflection.PseudoCustomAttribute._GetSecurityAttributes(RuntimeModule module, Int32 token, Boolean assembly, Object[]& securityAttributes)
   at System.Reflection.PseudoCustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType, Boolean includeSecCa, Int32& count)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Boolean inherit)
   at BenchmarkDotNet.Extensions.AssemblyExtensions.GetDebuggableAttribute(Assembly assembly)
   at BenchmarkDotNet.Portability.RuntimeInformation.GetConfiguration()
   at BenchmarkDotNet.Environments.BenchmarkEnvironmentInfo..ctor()
   at BenchmarkDotNet.Autogenerated.Runnable.Run(Boolean isDiagnoserAttached) in D:\Work\GitHub\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.Performance\BDN.Generated\BDN.Generated.notcs:line 62
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args) in D:\Work\GitHub\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.Performance\BDN.Generated\BDN.Generated.notcs:line 44

Ok, if flip to fullframework

**Comment by benaadams** [comment]
Fixed with this change https://github.com/aspnet/KestrelHttpServer/commit/10fe5e6fa25e95ab9acd2b3bd733e78be4315a37

**Comment by adamsitnik** [comment]
@redknightlois @benaadams 

Changes: user can influence the auto-generated project.json file now. This is possible by using the custom configs.

Use `.With(CoreToolchain.NetCoreApp12)`   to get: 

```json
"frameworks": {
  "netcoreapp1.2": {
    "dependencies": {
      "Microsoft.NETCore.App": {
        "type": "platform",
        "version": "1.2-*"
      },
```

Use `.With(CoreToolchain.NetCoreApp20)`   to get: 

```json
"frameworks": {
  "netcoreapp2.0": {
    "dependencies": {
      "Microsoft.NETCore.App": {
        "type": "platform",
        "version": "2.0-*"
      },
```

if this is not enough you can use:
`.With(CoreToolchain.From(new NetCoreAppSettings($targetFrameworkMoniker, $microsoftNetCoreAppVersion)));`

**Comment by AndreyAkinshin** [comment]
@adamsitnik, could you also update the documentation?
