### ISSUE TITLE
Problematic mechanism/docs for locating Rscript.exe

### ISSUE THREAD

**Issue by roji** [dotnet/BenchmarkDotNet#337]
The [documentation](http://benchmarkdotnet.org/Configs/Exporters.htm#plots) instructs users to define %R_HOME%. However, the RPlotExporter expects to find Rscript.exe directly in that directory, where it seems more standard for a variable called R_HOME to point to the installation directory (as opposed to something like R_BIN). In addition, this triggers a Win32Exception with the error "The system cannot find the file specified", which isn't very explicit.

I'll be happy to submit a PR for this. IMHO RPlotExporter should be changed to look for RScript.exe under a bin directory in %R_HOME%, but that would be a somewhat breaking change.

**Comment by AndreyAkinshin** [comment]
Hi @roji,

> I'll be happy to submit a PR for this.

Great!

> that would be a somewhat breaking change.

Probably, we could just print a warning message (if we didn't find `Rscript.exe`) with useful information. Also it makes sense to update the documentation.
