### ISSUE TITLE
What the report title and value means?

### ISSUE THREAD

**Issue by kkbruce** [dotnet/BenchmarkDotNet#349]
I don't understand report title and value means?

Example:
http://benchmarkdotnet.org/GettingStarted.htm#step-4.-view-results

Mean, StdDev means?
Mean, StdDev, Gen 0, Allocted 'xxx us' value  means? 

Thanks

**Comment by AndreyAkinshin** [comment]
* **Mean**: Average time of all the meaningful measurements
* **StdDev**: [Standard deviation](https://en.wikipedia.org/wiki/Standard_deviation) of these measurements
* **Gen 0**: Amount of garbage collections in generation 0
* **Allocated**: Allocated memory
* **us**: [Microseconds](https://en.wikipedia.org/wiki/Microsecond)

In the future, I want to add a legend for each column under the summary table.

**Comment by kkbruce** [comment]
Hi Andrey

Is big or small us is good?

Example:

Mean | StdDev

1.23 us is good?
or
2.34 us is good?

Thanks your reply.

**Comment by AndreyAkinshin** [comment]
What do your mean?

A method with `Mean = 1.23 us` works ~ 2 times faster than a method with `Mean = 2.34 us`.

**Comment by kkbruce** [comment]
I got it, thanks.

**Comment by AndreyAkinshin** [comment]
@kkbruce, yes. See also: http://benchmarkdotnet.org/HowItWorks.htm

**Comment by kkbruce** [comment]
I see.
Thanks.

**Comment by AndreyAkinshin** [comment]
@kkbruce,
It seems that the `us` notation confuses a lot of people (see also https://github.com/dotnet/BenchmarkDotNet/issues/459). I decided to add a hint line about time units in the legend section (see https://github.com/dotnet/BenchmarkDotNet/commit/f14e508e44b510a26cc3ec5aed30ee7843a92baf). So, you will get a line like this:
```
  1 us  : 1 Microsecond (0.000001 sec)
```
