### ISSUE TITLE
Fix OS Version in Summary for Windows 10

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#351]
Now I have the following `Environment.OSVersion` on my laptop with WIndows 10: `Microsoft Windows NT 6.2.9200.0` (instead of `Microsoft Windows NT 10.0.14393.0` which is the correct version for me). It seems that we should do some manifest file magic, see:

https://gist.github.com/devlead/d41763d293e5c6cc5f88
https://johnkoerner.com/csharp/what-does-environment-osversion-return-on-windows-10/
http://stackoverflow.com/questions/32121110/net-app-returning-different-os-version-to-powershell-on-windows-10

**Comment by AndreyAkinshin** [comment]
@adamsitnik, could you take a look at this issue? Is it possible to use `app.manifest` somehow for our library? I also have an universal way to get the Windows version via `ver` (and we already use it in CORE), but it requires more time because of the call to external program. So, it would be great if we will be able to get the correct version via `Environment.OSVersion`.

**Comment by adamsitnik** [comment]
@AndreyAkinshin I am afraid I won't have any time to take a look at this soon.

**Comment by adamsitnik** [comment]
@AndreyAkinshin I just noticed that dotnet cli prints the right version and took a look what they use.

It seems to be the `Microsoft.DotNet.PlatformAbstractions` package and the `Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.OperatingSystemVersion` property. Could you try it out and check if meets your requirements?

**Comment by AndreyAkinshin** [comment]
It works great. The source code:
```cs
Console.WriteLine(Environment.OSVersion);
Console.WriteLine(Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.OperatingSystem);
Console.WriteLine(Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.OperatingSystemPlatform);
Console.WriteLine(Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.OperatingSystemVersion);
```
The output:
```
Microsoft Windows NT 6.2.9200.0
Windows
Windows
10.0.14393
```
