### ISSUE TITLE
Troubles with CoreJob on Linux

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#352]
If we try to run a benchmark with CoreJob on Linux, we will get the following exception (Kubuntu 16.10, mono 4.6.2):
```
Unhandled Exception:
System.ComponentModel.Win32Exception (0x80004005): ApplicationName='/home/akinshin/RiderProjects/ClassLibrary1/ConsoleApplication1/bin/Release/BDN.Generated', CommandLine='', CurrentDirectory='', Native error= Access denied
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x001ee] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ComponentModel.Win32Exception (0x80004005): ApplicationName='/home/akinshin/RiderProjects/ClassLibrary1/ConsoleApplication1/bin/Release/BDN.Generated', CommandLine='', CurrentDirectory='', Native error= Access denied
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x001ee] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 
```
Expected behaviour: BenchmarkDotNet should print a nice warning (like "It is impossible to run CoreJob on Linux").

**Comment by AndreyAkinshin** [comment]
It seems that [this approach](http://stackoverflow.com/a/2279346/184842) allows to fix `FATAL UNHANDLED EXCEPTION` (but we still have to print a warning).

**Comment by adamsitnik** [comment]
@AndreyAkinshin  What was your setup here? I mean what was the host process runtime and what were the jobs you have used? + Did you use project.json?

**Comment by AndreyAkinshin** [comment]
If I remember correctly, it was a classic csproj application. I have a huge amount of solutions for my benchmarks and accidentally run `[CoreJob]` from the csproj project instead of project.json.

**Comment by adamsitnik** [comment]
Ok, I understand now. I will try to find a way to tell if we can check if the host project supports .NET Core so we can run CoreJob or not. Thanks!
