### ISSUE TITLE
BenchmarkRunner throws NullReferenceException when trying to run benchmarks in assemblies that do not have a DLL file extension

### ISSUE THREAD

**Issue by dfch** [dotnet/BenchmarkDotNet#354]
I encountered the following error when running a benchmark inside an assembly that does not have a DLL file extension:

```
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   MyBenchmarks.MyBenchmark: DefaultJob

// Validating benchmarks:
Assembly hywsbvq0.onp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null which defines benchmarks is non-optimized
// **************************
// Benchmark: MyBenchmarks.MyBenchmark: DefaultJob
// *** Generate ***
// Result = Success
// BinariesDirectoryPath = C:\src\biz.dfch.CS.Commons\src\biz.dfch.CS.Commons.Benchmarks\bin\Debug

// *** Build ***
BuildScript: C:\src\biz.dfch.CS.Commons\src\biz.dfch.CS.Commons.Benchmarks\bin\Debug\BDN.Generated.bat
// Result = Success

// *** Execute ***
// Launch: 1 / 1
System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args)
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

// Run, Diagnostic
// BeforeAnythingElse
System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args)
Sequence contains no elements
  + System.Linq.Enumerable.Last<TSource>(IEnumerable<TSource>)
  + BenchmarkDotNet.Running.BenchmarkRunnerCore.Execute(BenchmarkDotNet.Loggers.ILogger, BenchmarkDotNet.Running.Benchmark, BenchmarkDotNet.Toolchains.IToolchain, BenchmarkDotNet.Toolchains.Results.BuildResult, BenchmarkDotNet.Configs.IConfig, BenchmarkDotNet.Characteristics.IResolver, out BenchmarkDotNet.Engines.GcStats)
  + BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkDotNet.Running.Benchmark, BenchmarkDotNet.Loggers.ILogger, BenchmarkDotNet.Configs.IConfig, string, Func<BenchmarkDotNet.Jobs.Job, BenchmarkDotNet.Toolchains.IToolchain>, BenchmarkDotNet.Characteristics.IResolver)
  + BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkDotNet.Running.Benchmark[], BenchmarkDotNet.Loggers.ILogger, string, BenchmarkDotNet.Configs.IConfig, string, Func<BenchmarkDotNet.Jobs.Job, BenchmarkDotNet.Toolchains.IToolchain>, BenchmarkDotNet.Characteristics.IResolver)
  + BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(BenchmarkDotNet.Running.Benchmark[], BenchmarkDotNet.Configs.IConfig, Func<BenchmarkDotNet.Jobs.Job, BenchmarkDotNet.Toolchains.IToolchain>)
```

When I change the file extension from (in my case **`hywsbvq0.onp`** to **`hywsbvq0.onp.dll`** the BenchmarkRunner will complete without error.

I am using BenchmarkDotNet v0.10.2.

Steps to reproduce:

1. I am compiling some code inside CSI via Roslyn into an assembly where the file name is created via `Path.GetRandomFileName()`.
2. I load the assembly and start the BenchmarkRunner
3. I get the error message above

see [CompileAndRunBenchmarkWillFail.csx](https://github.com/dfensgmbh/biz.dfch.CS.Commons/blob/224248a7bd1b0e5d796bcbcb0981b7f76889923c/src/biz.dfch.CS.Commons.Benchmarks/CompileAndRunBenchmarkWillFail.csx)

The same script as before (just adding a `.DLL` extension to the file name) succeeds, see
[CompileAndRunBenchmark.csx](https://github.com/dfensgmbh/biz.dfch.CS.Commons/blob/224248a7bd1b0e5d796bcbcb0981b7f76889923c/src/biz.dfch.CS.Commons.Benchmarks/CompileAndRunBenchmark.csx)

Of course I might not represent the most common use case and I can really live with the workaround, however I was first surprise by the error message (`NullReferenceException`). Just wanted to let you know and maybe (*low* priority) this message could be improved some time.

**Comment by adamsitnik** [comment]
Hello @dfch ! Thanks for a well described bug report. I'll fix it

**Comment by adamsitnik** [comment]
We have not made any progress since 2017 and I consider it an edge case so I am closing the issue.
