### ISSUE TITLE
[Need help] InProcessToolchain PR, some design questions

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#358]
**UPD** [Completed](https://github.com/ig-sinicyn/BenchmarkDotNet/tree/feature-inprocess/src/BenchmarkDotNet.Core/Toolchains/InProcess), will do PR after #356 merged. 
 
I'm preparing PR of the InProcess toolchain that allows to run benchmark code without compiling binaries / running another process.

The main benefit of it is ability to run a lot of tests very quickly in cost of less accurate results. In practice we're getting stable results with 2-3 seconds per benchmark time limit (fast enough if compared to typical 20-60 secs for outofproc toolchain).

I'm going to keep implementation in sync with the code in `BenchmarkProgram.txt` but I want to clarify some moments at first.

1. Codegen. Currently I'm using Reflection.Emit for loop unroll and there is fallback code that uses `Delegate.Combine()` instead of emitting the code. It produces less accurate results due to additional overhead but it works fine with .Net Native. Is it ok to have both?

2. `Consumer.Consume()` call for non-void methods. Is it ok to emit stfld instead of calling the method? Should the return value be stored each time the target method is invoked or it will be better to save the return value for last call only?

3. `Dummy()` methods. Is the `@DummyUnroll@` number a constant? If it is not - is it ok to fallback to method with hardcoded 64 lines of `dummyVar++;` for cases when `Reflection.Emit` is unavailable?
Should be there three different dummy methods or it's enough to have just one?

---

**UPD, More questions:**

**BenchmarkProgram.txt**
* Setup/Cleanup method are invoked by Runnable. Shouldn't it be responsibility of the Engine?
* `Target.AdditionalLogic` is unused for now. Should it be removed? 
  If not - is it ok if InProcessValidator will warn when AdditionalLogic is not empty?
* `InvokeMultiple` loop does not cache mainAction/consumer in local variables. Is this intentional?

**Diagnosers**
* Shouldn't notification signals for diagnosers include a native thread id?
* `Diagnoser.BeforeCleanup()` has no args - is it ok?

**Current impl drawbacks**
* Current implementation redirects output directly into the logger so there's nothing to pass into 
`ExecuteResult.ExtraOutput`. Is it ok? Should I use intermediate buffer (`AccumulationLogger`) instead?
* Thread.SetApartmentState() and Thread.Priority are not avalable in .net core FW (at least until netstandard 2), so there's no way to set up them.
* DummyAction [is hardcoded](https://github.com/ig-sinicyn/BenchmarkDotNet/blob/feature-inprocess/src/BenchmarkDotNet.Core/Toolchains/InProcess/%5BBenchmnarkActions%5D/BenchmarkActionFactory_Dummy.cs). Not sure if this is a good idea.

**Comment by adamsitnik** [comment]
> Setup/Cleanup method are invoked by Runnable. Shouldn't it be responsibility of the Engine?

I am not 100% sure. Perhaps we should introduce a new class that does all the necessary things? I just don't have a good idea now.

> Shouldn't notification signals for diagnosers include a native thread id?
> Diagnoser.BeforeCleanup() has no args - is it ok?Diagnoser.BeforeCleanup() has no args - is it ok?

Currently, the diagnosers don't need anything else. As soon as there is a good reason for adding new parameters we just add it.

> Current implementation redirects output directly into the logger so there's nothing to pass into
ExecuteResult.ExtraOutput. Is it ok? Should I use intermediate buffer (AccumulationLogger) instead?

It's ok. As far as I remember we only use ExtraOutput to parse some extra data about benchmark environment which is unavailable from the same process. With InProcess there is no need to do that.

> Thread.SetApartmentState() and Thread.Priority are not available in .net core FW (at least until netstandard 2), so there's no way to set up them.

Your current solution is the best we can do now. Personally, I don't expect these specific methods to come back with .NET Core 2.0

**Comment by adamsitnik** [comment]
I am closing since the PR was closed. @ig-sinicyn please reopen if I am wrong
