### ISSUE TITLE
Support for new CSProj Format?

### ISSUE THREAD

**Issue by niemyjski** [dotnet/BenchmarkDotNet#359]
I get tons of errors about dotnet restore and other failures when running (https://github.com/exceptionless/Foundatio/tree/master/test/Foundatio.Benchmarks) under VS2017 RC4. Is this a known issue?

**Comment by adamsitnik** [comment]
> Is this a known issue?

Yes, we are working on that. Please follow #357 for further updates

**Comment by adamsitnik** [comment]
@niemyjski It's done. Could you give it a try and let me know if it works? The package `0.10.2.333` is available at `<add key="appveyor-bdn" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />`

**Comment by niemyjski** [comment]
@adamsitnik I haven't had a chance, I've been on vacation. I can check when I get some more downtime :)
