### ISSUE TITLE
[FeatureRequest] Custom IColumn category

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#361]
Subj:)

I'm playing with custom analysers for IO / Sql stats and it looks like a good idea to have a way to group related stats together. `string IColumn.CustomCategory { get; }`, maybe?

**Comment by AndreyAkinshin** [comment]
LGTM, will think about API.

**Comment by adamsitnik** [comment]
No progress since 2017, closing.
