### ISSUE TITLE
Why installation of BenchmarkDotNet requires a lot of disk space?

### ISSUE THREAD

**Issue by Mirandatz** [dotnet/BenchmarkDotNet#362]
Greetings!
I was messing around with a Visual Studio 2015 project (a C# 6 Console Application) when I decided to do some benchmarking. So I googled around and found this project.
I decided to install it using the NuGet Package Manager. 10 seconds, 2 clicks and bang: installed.
I loved it. This packge/project is really, really powerful, easy to use and accurate.
But... The size of my solution increased by 300 mega bytes.

I asked on StackOverflow if I did something wrong / installed unnecessary stuff.
I didn't get a any answer (but did get two negative votes) and a suggestion: to ask you guys if its possible to create 'lightweight' version just for desktop apps.

**Comment by AndreyAkinshin** [comment]
Hey @Mirandatz,

What do you mean by the "size of my solution"? Could you tell me where exactly did you find 300MB?

I installed BenchmarkDotNet 0.10.2 in a new console application. Yeah, the package has some installed size overhead: the `packages` folder takes about 110MB. Internally, BenchmarkDotNet uses Roslyn ([BenchmarkDotNet.Toolchains.Roslyn](https://www.nuget.org/packages/BenchmarkDotNet.Toolchains.Roslyn/) references [Microsoft.CodeAnalysis.CSharp](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/)) which is big because it contains binary not only for `net45` but also for `netstandard` and `portable` target frameworks. Unfortunately, it's impossible to install only part of a package. Also, Roslyn is the only way to implement xplat benchmark compilation. In the future, we want to support InProcess benchmark, so it will be possible to run it (with some limitations) without Roslyn. For now, it's impossible to decrease the `packages` folder size without many additional problems.

**Comment by Mirandatz** [comment]
Hello Andrey, thanks for the reply.
By "the size of my solution increased" I meant: after installing BenchmarkDotNet a new directory called packages was created in my solution.
Maybe it was there before, but being smaller I didn't notice it.
It's size is 294 mb. 311 on disk.
It contains the following subs directories:
packages\System.Diagnostics.Debug.4.0.11"
packages\System.Diagnostics.FileVersionInfo.4.0.0"
packages\System.Diagnostics.StackTrace.4.0.1"
packages\System.Diagnostics.Tools.4.0.1"
packages\System.Dynamic.Runtime.4.0.11"
packages\System.Globalization.4.0.11"
packages\System.IO.FileSystem.4.0.1"
packages\System.IO.FileSystem.Primitives.4.0.1"
packages\System.Linq.4.1.0"
packages\System.Linq.Expressions.4.1.0"
packages\System.Reflection.4.1.0"
packages\System.Reflection.Metadata.1.3.0"
packages\System.Reflection.Primitives.4.0.1"
packages\System.Resources.ResourceManager.4.0.1"
packages\System.Runtime.4.1.0"
packages\System.Runtime.Extensions.4.1.0"
packages\System.Runtime.Handles.4.0.1"
packages\System.Runtime.InteropServices.4.1.0"
packages\System.Runtime.Numerics.4.0.1"
packages\System.Security.Cryptography.Algorithms.4.2.0"
packages\System.Security.Cryptography.Encoding.4.0.0"
packages\System.Security.Cryptography.Primitives.4.0.0"
packages\System.Security.Cryptography.X509Certificates.4.1.0"
packages\System.Text.Encoding.4.0.11"
packages\System.Text.Encoding.CodePages.4.0.1"
packages\System.Text.Encoding.Extensions.4.0.11"
packages\System.Threading.4.0.11"
packages\System.Threading.Tasks.4.0.11"
packages\System.Threading.Tasks.Extensions.4.0.0"
packages\System.Threading.Tasks.Parallel.4.0.1"
packages\System.Threading.Thread.4.0.0"
packages\System.Xml.ReaderWriter.4.0.11"
packages\System.Xml.XDocument.4.0.11"
packages\System.Xml.XmlDocument.4.0.1"
packages\System.Xml.XPath.4.0.1"
packages\System.Xml.XPath.XDocument.4.0.1"
packages\BenchmarkDotNet.0.10.2"
packages\BenchmarkDotNet.Core.0.10.2"
packages\BenchmarkDotNet.Toolchains.Roslyn.0.10.2"
packages\Microsoft.CodeAnalysis.Analyzers.1.1.0"
packages\Microsoft.CodeAnalysis.Common.1.3.2"
packages\Microsoft.CodeAnalysis.CSharp.1.3.2"
packages\System.AppContext.4.1.0"
packages\System.Collections.4.0.11"
packages\System.Collections.Concurrent.4.0.12"
packages\System.Collections.Immutable.1.2.0"
packages\System.Console.4.0.0"

The weird thing is: I was using some of those assemblies before, like System.Collections and System.Task. So I thinking we were added

**Comment by AndreyAkinshin** [comment]
Could you try to create a new console application and install BenchmarkDotNet? Here is the list of packages on my computer:
```
BenchmarkDotNet.0.10.2/
BenchmarkDotNet.Core.0.10.2/
BenchmarkDotNet.Toolchains.Roslyn.0.10.2/
Microsoft.CodeAnalysis.Analyzers.1.1.0/
Microsoft.CodeAnalysis.CSharp.1.3.2/
Microsoft.CodeAnalysis.Common.1.3.2/
System.Collections.4.0.0/
System.Collections.Immutable.1.1.37/
System.Diagnostics.Debug.4.0.0/
System.Globalization.4.0.0/
System.Linq.4.0.0/
System.Reflection.Metadata.1.2.0/
System.Resources.ResourceManager.4.0.0/
System.Runtime.4.0.0/
System.Runtime.Extensions.4.0.0/
System.Threading.4.0.0/
System.Threading.Tasks.4.0.0/
System.Threading.Tasks.Extensions.4.0.0/
```

**Comment by Mirandatz** [comment]
Okay. Here's the output I got:

Attempting to gather dependency information for package 'BenchmarkDotNet.0.10.2' with respect to project 'ConsoleApplication1', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'BenchmarkDotNet.0.10.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'BenchmarkDotNet.0.10.2'
Resolved actions to install package 'BenchmarkDotNet.0.10.2'
Adding package 'Microsoft.CodeAnalysis.Analyzers.1.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'Microsoft.CodeAnalysis.Analyzers.1.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'Microsoft.CodeAnalysis.Analyzers.1.1.0' to 'packages.config'
Executing script file 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages\Microsoft.CodeAnalysis.Analyzers.1.1.0\tools\install.ps1'...
Successfully installed 'Microsoft.CodeAnalysis.Analyzers 1.1.0' to ConsoleApplication1
Adding package 'System.AppContext.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.AppContext.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.AppContext.4.1.0' to 'packages.config'
Successfully installed 'System.AppContext 4.1.0' to ConsoleApplication1
Adding package 'System.Collections.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Collections.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Collections.4.0.11' to 'packages.config'
Successfully installed 'System.Collections 4.0.11' to ConsoleApplication1
Adding package 'System.Collections.Concurrent.4.0.12' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Collections.Concurrent.4.0.12' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Collections.Concurrent.4.0.12' to 'packages.config'
Successfully installed 'System.Collections.Concurrent 4.0.12' to ConsoleApplication1
Adding package 'System.Collections.Immutable.1.2.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Collections.Immutable.1.2.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Collections.Immutable.1.2.0' to 'packages.config'
Successfully installed 'System.Collections.Immutable 1.2.0' to ConsoleApplication1
Adding package 'System.Console.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Console.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Console.4.0.0' to 'packages.config'
Successfully installed 'System.Console 4.0.0' to ConsoleApplication1
Adding package 'System.Diagnostics.Debug.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Diagnostics.Debug.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Diagnostics.Debug.4.0.11' to 'packages.config'
Successfully installed 'System.Diagnostics.Debug 4.0.11' to ConsoleApplication1
Adding package 'System.Diagnostics.FileVersionInfo.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Diagnostics.FileVersionInfo.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Diagnostics.FileVersionInfo.4.0.0' to 'packages.config'
Successfully installed 'System.Diagnostics.FileVersionInfo 4.0.0' to ConsoleApplication1
Adding package 'System.Diagnostics.StackTrace.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Diagnostics.StackTrace.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Diagnostics.StackTrace.4.0.1' to 'packages.config'
Successfully installed 'System.Diagnostics.StackTrace 4.0.1' to ConsoleApplication1
Adding package 'System.Diagnostics.Tools.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Diagnostics.Tools.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Diagnostics.Tools.4.0.1' to 'packages.config'
Successfully installed 'System.Diagnostics.Tools 4.0.1' to ConsoleApplication1
Adding package 'System.Dynamic.Runtime.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Dynamic.Runtime.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Dynamic.Runtime.4.0.11' to 'packages.config'
Successfully installed 'System.Dynamic.Runtime 4.0.11' to ConsoleApplication1
Adding package 'System.Globalization.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Globalization.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Globalization.4.0.11' to 'packages.config'
Successfully installed 'System.Globalization 4.0.11' to ConsoleApplication1
Adding package 'System.IO.FileSystem.Primitives.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.IO.FileSystem.Primitives.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.IO.FileSystem.Primitives.4.0.1' to 'packages.config'
Successfully installed 'System.IO.FileSystem.Primitives 4.0.1' to ConsoleApplication1
Adding package 'System.IO.FileSystem.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.IO.FileSystem.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.IO.FileSystem.4.0.1' to 'packages.config'
Successfully installed 'System.IO.FileSystem 4.0.1' to ConsoleApplication1
Adding package 'System.Linq.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Linq.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Linq.4.1.0' to 'packages.config'
Successfully installed 'System.Linq 4.1.0' to ConsoleApplication1
Adding package 'System.Linq.Expressions.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Linq.Expressions.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Linq.Expressions.4.1.0' to 'packages.config'
Successfully installed 'System.Linq.Expressions 4.1.0' to ConsoleApplication1
Adding package 'System.Reflection.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Reflection.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Reflection.4.1.0' to 'packages.config'
Successfully installed 'System.Reflection 4.1.0' to ConsoleApplication1
Adding package 'System.Reflection.Metadata.1.3.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Reflection.Metadata.1.3.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Reflection.Metadata.1.3.0' to 'packages.config'
Successfully installed 'System.Reflection.Metadata 1.3.0' to ConsoleApplication1
Adding package 'System.Reflection.Primitives.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Reflection.Primitives.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Reflection.Primitives.4.0.1' to 'packages.config'
Successfully installed 'System.Reflection.Primitives 4.0.1' to ConsoleApplication1
Adding package 'System.Resources.ResourceManager.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Resources.ResourceManager.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Resources.ResourceManager.4.0.1' to 'packages.config'
Successfully installed 'System.Resources.ResourceManager 4.0.1' to ConsoleApplication1
Adding package 'System.Runtime.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Runtime.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Runtime.4.1.0' to 'packages.config'
Successfully installed 'System.Runtime 4.1.0' to ConsoleApplication1
Adding package 'System.Runtime.Extensions.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Runtime.Extensions.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Runtime.Extensions.4.1.0' to 'packages.config'
Successfully installed 'System.Runtime.Extensions 4.1.0' to ConsoleApplication1
Adding package 'System.Runtime.Handles.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Runtime.Handles.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Runtime.Handles.4.0.1' to 'packages.config'
Successfully installed 'System.Runtime.Handles 4.0.1' to ConsoleApplication1
Adding package 'System.Runtime.InteropServices.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Runtime.InteropServices.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Runtime.InteropServices.4.1.0' to 'packages.config'
Successfully installed 'System.Runtime.InteropServices 4.1.0' to ConsoleApplication1
Adding package 'System.Runtime.Numerics.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Runtime.Numerics.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Runtime.Numerics.4.0.1' to 'packages.config'
Successfully installed 'System.Runtime.Numerics 4.0.1' to ConsoleApplication1
Adding package 'System.Security.Cryptography.Encoding.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Security.Cryptography.Encoding.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Security.Cryptography.Encoding.4.0.0' to 'packages.config'
Successfully installed 'System.Security.Cryptography.Encoding 4.0.0' to ConsoleApplication1
Adding package 'System.Security.Cryptography.Primitives.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Security.Cryptography.Primitives.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Security.Cryptography.Primitives.4.0.0' to 'packages.config'
Successfully installed 'System.Security.Cryptography.Primitives 4.0.0' to ConsoleApplication1
Adding package 'System.Security.Cryptography.Algorithms.4.2.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Security.Cryptography.Algorithms.4.2.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Security.Cryptography.Algorithms.4.2.0' to 'packages.config'
Successfully installed 'System.Security.Cryptography.Algorithms 4.2.0' to ConsoleApplication1
Adding package 'System.Security.Cryptography.X509Certificates.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Security.Cryptography.X509Certificates.4.1.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Security.Cryptography.X509Certificates.4.1.0' to 'packages.config'
Successfully installed 'System.Security.Cryptography.X509Certificates 4.1.0' to ConsoleApplication1
Adding package 'System.Text.Encoding.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Text.Encoding.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Text.Encoding.4.0.11' to 'packages.config'
Successfully installed 'System.Text.Encoding 4.0.11' to ConsoleApplication1
Adding package 'System.Text.Encoding.CodePages.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Text.Encoding.CodePages.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Text.Encoding.CodePages.4.0.1' to 'packages.config'
Successfully installed 'System.Text.Encoding.CodePages 4.0.1' to ConsoleApplication1
Adding package 'System.Text.Encoding.Extensions.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Text.Encoding.Extensions.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Text.Encoding.Extensions.4.0.11' to 'packages.config'
Successfully installed 'System.Text.Encoding.Extensions 4.0.11' to ConsoleApplication1
Adding package 'System.Threading.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Threading.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Threading.4.0.11' to 'packages.config'
Successfully installed 'System.Threading 4.0.11' to ConsoleApplication1
Adding package 'System.Threading.Tasks.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Threading.Tasks.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Threading.Tasks.4.0.11' to 'packages.config'
Successfully installed 'System.Threading.Tasks 4.0.11' to ConsoleApplication1
Adding package 'System.Threading.Tasks.Extensions.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Threading.Tasks.Extensions.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Threading.Tasks.Extensions.4.0.0' to 'packages.config'
Successfully installed 'System.Threading.Tasks.Extensions 4.0.0' to ConsoleApplication1
Adding package 'BenchmarkDotNet.Core.0.10.2' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'BenchmarkDotNet.Core.0.10.2' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'BenchmarkDotNet.Core.0.10.2' to 'packages.config'
Successfully installed 'BenchmarkDotNet.Core 0.10.2' to ConsoleApplication1
Adding package 'System.Threading.Tasks.Parallel.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Threading.Tasks.Parallel.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Threading.Tasks.Parallel.4.0.1' to 'packages.config'
Successfully installed 'System.Threading.Tasks.Parallel 4.0.1' to ConsoleApplication1
Adding package 'System.Threading.Thread.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Threading.Thread.4.0.0' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Threading.Thread.4.0.0' to 'packages.config'
Successfully installed 'System.Threading.Thread 4.0.0' to ConsoleApplication1
Adding package 'System.Xml.ReaderWriter.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Xml.ReaderWriter.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Xml.ReaderWriter.4.0.11' to 'packages.config'
Successfully installed 'System.Xml.ReaderWriter 4.0.11' to ConsoleApplication1
Adding package 'System.Xml.XDocument.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Xml.XDocument.4.0.11' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Xml.XDocument.4.0.11' to 'packages.config'
Successfully installed 'System.Xml.XDocument 4.0.11' to ConsoleApplication1
Adding package 'System.Xml.XmlDocument.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Xml.XmlDocument.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Xml.XmlDocument.4.0.1' to 'packages.config'
Successfully installed 'System.Xml.XmlDocument 4.0.1' to ConsoleApplication1
Adding package 'System.Xml.XPath.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Xml.XPath.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Xml.XPath.4.0.1' to 'packages.config'
Successfully installed 'System.Xml.XPath 4.0.1' to ConsoleApplication1
Adding package 'System.Xml.XPath.XDocument.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Xml.XPath.XDocument.4.0.1' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'System.Xml.XPath.XDocument.4.0.1' to 'packages.config'
Successfully installed 'System.Xml.XPath.XDocument 4.0.1' to ConsoleApplication1
Adding package 'Microsoft.CodeAnalysis.Common.1.3.2' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'Microsoft.CodeAnalysis.Common.1.3.2' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'Microsoft.CodeAnalysis.Common.1.3.2' to 'packages.config'
Successfully installed 'Microsoft.CodeAnalysis.Common 1.3.2' to ConsoleApplication1
Adding package 'Microsoft.CodeAnalysis.CSharp.1.3.2' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'Microsoft.CodeAnalysis.CSharp.1.3.2' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'Microsoft.CodeAnalysis.CSharp.1.3.2' to 'packages.config'
Successfully installed 'Microsoft.CodeAnalysis.CSharp 1.3.2' to ConsoleApplication1
Adding package 'BenchmarkDotNet.Toolchains.Roslyn.0.10.2' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'BenchmarkDotNet.Toolchains.Roslyn.0.10.2' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'BenchmarkDotNet.Toolchains.Roslyn.0.10.2' to 'packages.config'
Successfully installed 'BenchmarkDotNet.Toolchains.Roslyn 0.10.2' to ConsoleApplication1
Adding package 'BenchmarkDotNet.0.10.2' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'BenchmarkDotNet.0.10.2' to folder 'C:\Users\Trauer\Desktop\ConsoleApplication1\packages'
Added package 'BenchmarkDotNet.0.10.2' to 'packages.config'
Successfully installed 'BenchmarkDotNet 0.10.2' to ConsoleApplication1
========== Finished ==========

**Comment by adamsitnik** [comment]
@Mirandatz as @AndreyAkinshin answered the Roslyn dependency is space-expensive for BenchmarkDotNet. But it's a must have for us, so at least for now there is nothing we can do.
