### ISSUE TITLE
Benchmark just stops (Antivirus problem)

### ISSUE THREAD

**Issue by KonkLaw** [dotnet/BenchmarkDotNet#364]
First of all, thanks for great job.

I've got next problem: sometimes after running benchmark I've been geting this issue:
![error](https://cloud.githubusercontent.com/assets/22473930/23103774/c5050192-f6d1-11e6-9f10-4a2104148962.png)
Console benchmark is just stopping with standard system message: "Press any key to continue ...". No exceptions or warnings in console or log file. As I see it doesn't depends on particular test. I really spend a bunch of time trying to find an error on my side. And it seems like I've found out what was wrong.
The thing is, unfortunately, environment where we are running tests is not always depends on us. And I've got one with antivirus which is working on back-back-baground. It simply blocks running test on the halfway. And that's not real problem. Benchmarking with running antivirus is problem of developer. The real problem is that I just see no any errors or warnings at all. Just "Press any key to continue ...". And googling doen't help at all.
I realize that handling antivirus cases may be quite tough call. May be, at least some warning in documentation could help me.

**Comment by AndreyAkinshin** [comment]
Hey @KonkLaw, thanks for the report. You are absolutely right, we definitely should print a warning. Any clues how to detect we if have problems with antivirus (btw, may I ask which antivirus do you use)?

**Comment by KonkLaw** [comment]
Bitdefender Antivirus Free Edition (updating works)
on Win7 SP1 x64
In some cases antivirus hides gui, but still works (I see it in task manager), so it stops my benchmark with no warnings. If I will run its gui, I will see correspond message ("process is blocked" or like that).

I've prepared small test with bug in my draft repository: https://github.com/KonkLaw/Tests
Also text in log file (bin\Release\BenchmarkDotNet.Artifacts\) in faulty cases always is less that output in console.
The interesting fact is that if I run two tests (two methods with attributes, for example in test given above) test ends successfully. But, at least, three methods is enough to get a fault. May be it is connected with log file size.

**Comment by AndreyAkinshin** [comment]
Related issue: https://github.com/dotnet/BenchmarkDotNet/issues/390

**Comment by guidmaster** [comment]
Have the same problem. Running in a corp environment means that there is no way to disable AV :(

Getting the error by just running the Getting Started sample.

**Comment by adamsitnik** [comment]
Description for people interested in grabbing this issue:

- We generate, build and run new process for every benchmark
- Anti Virus is blocking this by default.
- My suggestion:
    - Detect the situation where our process is immediately killed
    - Print users the warning: Most probably your anti virus has killed benchmarking process. Don't turn off AV, add $BenchmarkCategory to the excludes list
    - Print users the workaround: use InProcessToolchain to avoid new process creation

**Comment by eitamal** [comment]
I had the same issue as in issue #390 , and even though I'm not running in a corporate environment, I was unable to disable my anti-virus and adding the folder to the exclusions list didn't help. 

Eventually, I was able to run the benchmark by opening a cmd instance as administrator changing directory to the executable's one and running it from there.

I know this isn't an ideal solution, but maybe it'll help someone else.

**Comment by lukasz-pyrzyk** [comment]
There is a possibility to list all antivirus software using [WMI](https://msdn.microsoft.com/en-us/library/aa384642(v=vs.85).aspx), however probably it won't work on .NET Core. Need to check it.

What do you think about adding warning about active antivirus to the [EnvironmentAnalyzer](https://github.com/dotnet/BenchmarkDotNet/blob/e31872d1e521da27d46a919a58fb29253562e56a/BenchmarkDotNet/Analysers/EnvironmentAnalyser.cs)?

**Comment by AndreyAkinshin** [comment]
A warning doesn't solve the problem, but it would be much better than incomprehensible crash. So, PR is welcome.

**Comment by lukasz-pyrzyk** [comment]
Totally agree, however i don't have enough knowledge about the project so i would like to do it in small steps. Thanks for comment, I will work on the PR

**Comment by adamsitnik** [comment]
Fixed with #512
