### ISSUE TITLE
Support the new .fsprojs targetting .NET Core (F# + .NET Core + MSBuild)

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#366]
I have implemented it based on the sample app available [here](https://raw.githubusercontent.com/dotnet/netcorecli-fsc/master/examples/rc4/console/console.fsproj) 

```xml
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <AssemblyTitle>BenchmarkDotNet.Samples.FSharp.Core</AssemblyTitle>
    <AssemblyName>BenchmarkDotNet.Samples.FSharp.Core</AssemblyName>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.NET.Sdk" Version="1.0.*" PrivateAssets="All" />
    <PackageReference Include="FSharp.Core" Version="4.1.*" />
    <PackageReference Include="BenchmarkDotNet" Version="0.10.2.341" />
  </ItemGroup>

</Project>
```

```fs
module Program

open System
open System.IO
open System.Collections.Concurrent
open BenchmarkDotNet.Attributes
open BenchmarkDotNet.Running

let getStrings len = Array.init len (fun _ -> Path.GetRandomFileName())

let lookup arr (dict:ConcurrentDictionary<string,bool>) =
    arr |> Array.iteri(fun idx elm -> 
        let mutable b = dict.[elm]
        b <- dict.[arr.[0]])


type StringKeyComparison () =
    let mutable arr : string [] = [||]
    let dict1 = ConcurrentDictionary<_,_>()
    let dict2 = ConcurrentDictionary<_,_>(StringComparer.Ordinal)

    [<Params (100, 500, 1000, 2000)>] 
    member val public DictSize = 0 with get, set

    [<Setup>]
    member self.SetupData() =
        dict1.Clear(); dict2.Clear()
        arr <- getStrings self.DictSize
        arr |> Array.iter (fun x -> dict1.[x] <- true ; dict2.[x] <- true)

    [<Benchmark>]
    member self.StandardLookup () = lookup arr dict1

    [<Benchmark>]
    member self.OrdinalLookup () = lookup arr dict2


let defaultSwitch () = BenchmarkSwitcher [| typeof<StringKeyComparison>  |]

[<EntryPoint>]
let Main args =
    let summary = defaultSwitch().Run args 
    0
```

Then:
```
dotnet restore
dotnet run -c Release
```

**Comment by neoeinstein** [comment]
I plan to consume this, so if there is anything that I can do to help with testing, let me know.

**Comment by adamsitnik** [comment]
@neoeinstein great! Could you give it a try? I have updated the description of the issue with sample app.

You will need to add our nuget CI feed to get the latest package `<add key="appveyor-bdn" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />`

**Comment by neoeinstein** [comment]
I've run the F# benchmarks using an existing F# project. Everything looks great.

One note: it is necessary to add `<DebugType>none</DebugType>` to the `.fsproj` in order to eliminate a warning at the end of the benchmark. The F# SDK adds `<DebugType>portable</DebugType>` by default.

I include the warning below for future visitors from search engines:

```
*** Warnings ***
Environment
  Benchmark.MyProject: Default -> Benchmark was built in DEBUG configuration. Please, build it in RELEASE.
  Benchmark.MyProject: Default -> Benchmark was built in DEBUG configuration. Please, build it in RELEASE.
```

**Comment by adamsitnik** [comment]
@neoeinstein I am very glad to hear that! thanks for finding the problem and giving the solution!

btw. our `EnvironmentAnalyser` which was producing the warning about DEBUG build was wrong. [It seems](http://stackoverflow.com/questions/7713514/should-i-compile-release-builds-with-debug-info-as-full-or-pdb-only?answertab=votes#tab-top) that a debug build can be optimized, so I am going to change the condition to look for the optimized flag only.
