### ISSUE TITLE
Params should provide the ability to use an IEnumerable (á la xUnit Theories)

### ISSUE THREAD

**Issue by redknightlois** [dotnet/BenchmarkDotNet#37]
This is important, because sometimes we need to be able to build huge lists or objects that cannot be expressed as constants.

**Comment by mattwarren** [comment]
yeah, I need to give `[Params]` a bit more love, it's too basic at the moment, but I just wanted to get something out there.

I agree, do you mean something like this:

``` csharp
[Params(typeof(ParamsData))]
public int Size = 1;

public class ParamsData : IEnumerable<int>
{
    public IEnumerator<int> GetEnumerator()
    {
        // Create the IEnumerable<int> however you want
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
    {
        return this.GetEnumerator();
    }    
}
```

also I was thinking of adding this, what do you think?

``` csharp
[ParamsWithSteps(start: 1, end: 1000, step: 10)]
public int Size = 1;
```
which would basically do the following:
``` csharp
for (int i = 1, i <= 1000; i += 10)
{
    // run benchmark with Size = i
}
```

**Comment by redknightlois** [comment]
I would go with a simplier interface with a method that returns ```IEnumerable<T>``` but yeah, that's the idea. 

With ParamsWithSteps I would go further and support inheritance and provide a few examples like:

```[ParamsWithStep(start: 1, end: 1000, step: 10, inclusive: true)```
```[ParamsQuadratic(start: 1, end: 1000, inclusive: false)```
```[ParamsPowerOf(start: 1, end: 1024, power: 2, inclusive: true)```

**Comment by mattwarren** [comment]
> I would go with a simplier interface with a method that returns `IEnumerable<T>` but yeah, that's the idea.

Yeah I agree, I've just seen that XUnit simplified everything, so you can now support method/fields or classes via `[MemberData(..)]`, see https://xunit.codeplex.com/SourceControl/changeset/628af664e521543c2c9d712b45d0d870f2a84d26

> With ParamsWithSteps I would go further and support inheritance and provide a few examples like:

Nice idea, I'd not thought about Quadratic/PowerOf

**Comment by adamsitnik** [comment]
It will be tracked as part of #256
