### ISSUE TITLE
Question/Discussion: Understanding "Baseline" Means

### ISSUE THREAD

**Issue by Mike-EEE** [dotnet/BenchmarkDotNet#371]
My performance jargon isn't up to, uh, speed yet, so you'll have to bear with me pawing at (was that two puns?! ugh it must be late) the concepts here.

Consider the following results:

```
MainTarget 1: 8192 op, 304908596.72 ns, 37.2203 us/op
MainTarget 2: 8192 op, 304534420.73 ns, 37.1746 us/op
MainTarget 3: 8192 op, 304506744.99 ns, 37.1712 us/op
MainTarget 4: 8192 op, 305622630.78 ns, 37.3075 us/op
MainTarget 5: 8192 op, 304935718.95 ns, 37.2236 us/op
MainTarget 6: 8192 op, 305433051.97 ns, 37.2843 us/op
MainTarget 7: 8192 op, 304625197.16 ns, 37.1857 us/op
MainTarget 8: 8192 op, 304718741.15 ns, 37.1971 us/op
MainTarget 9: 8192 op, 304524457.47 ns, 37.1734 us/op
MainTarget 10: 8192 op, 304462740.57 ns, 37.1659 us/op
MainTarget 11: 8192 op, 383271067.53 ns, 46.7860 us/op
MainTarget 12: 8192 op, 324828763.28 ns, 39.6519 us/op
MainTarget 13: 8192 op, 304541616.42 ns, 37.1755 us/op
MainTarget 14: 8192 op, 305634531.35 ns, 37.3089 us/op
MainTarget 15: 8192 op, 304706840.58 ns, 37.1957 us/op
```

You will notice that it has two outliers at `46.7860 us/op` and `39.6519 us/op`.  Now consider the same test ran just a few seconds later:

```
MainTarget 1: 8192 op, 271395767.77 ns, 33.1294 us/op
MainTarget 2: 8192 op, 270526749.57 ns, 33.0233 us/op
MainTarget 3: 8192 op, 270377300.58 ns, 33.0050 us/op
MainTarget 4: 8192 op, 270652950.94 ns, 33.0387 us/op
MainTarget 5: 8192 op, 271503149.64 ns, 33.1425 us/op
MainTarget 6: 8192 op, 270694741.31 ns, 33.0438 us/op
MainTarget 7: 8192 op, 271310249.74 ns, 33.1189 us/op
MainTarget 8: 8192 op, 270488833.81 ns, 33.0187 us/op
MainTarget 9: 8192 op, 270304513.39 ns, 32.9962 us/op
MainTarget 10: 8192 op, 270388924.39 ns, 33.0065 us/op
MainTarget 11: 8192 op, 270651013.64 ns, 33.0385 us/op
MainTarget 12: 8192 op, 270142333.56 ns, 32.9764 us/op
MainTarget 13: 8192 op, 270472505.12 ns, 33.0167 us/op
MainTarget 14: 8192 op, 270353776.2 ns, 33.0022 us/op
MainTarget 15: 8192 op, 271167442.93 ns, 33.1015 us/op
```

Again this is the same test.  You can see that both seem to have a "baseline" from which all values are derived from.  In the first test it is ~37.2 and in the second test it is ~33.0.  Even with the first with its outliers, once it deviates, it returns back to ~37.2.

What I am having trouble understanding is, this test is capable of running at either 37us/op or 33us/op.  So why aren't the values fluctuating between the two as they run?  It seems as if each run "locks" onto a particular "baseline" mean and will stick with that no matter what until the test is over.

Is this a threading issue?  As in some threads are given more priority than others?  I run an 8-core so that is my immediate thought.  Some threads are faster than others as they are given more priority from the core they are running from (or something like that).

Anyways, I thought I would throw this out there and see if one of the experts can assist here.  Thanks again for any assistance you can provide!

**Comment by AndreyAkinshin** [comment]
1. BenchmarkDotNet sets the highest available priority to the target process.
2. There are a huge amount of things which can affect your performance. Usually, you can have a problem because of other application (e.g., VS can easily add a few microseconds), If you want to have a repeatable result, make sure that you are running benchmarks in a sterile environment.
3. It's ok that some benchmarks have run-to-run variance. Sometimes you just can't control it. In this case, you have to increase `LaunchCount`; it will help you to get a repeatable result. Also, in your case it makes sense to manually specify `IterationTime` (e.g. `1 sec`), it should also help.

**Comment by Mike-EEE** [comment]
Awesome.  Thanks again for your continued assistance @AndreyAkinshin.  It is much appreciated.

To add, the values above are in a clean environment without Visual Studio.  I say clean and not sterile.  I do run a hyper-v server on my machine.  Perhaps I could dedicate a VM to benchmarking?  I would need an easy/effective/fast way of copying files to it with each build.  Something to look into, along with the `LaunchCount`, thank you.

So after thinking about this some more, it seems as if the significant jumps between 32 and 37 is due to a GC firing between the constructor and the benchmark method (to refresh, we are storing data in static `ConditionalWeakTable`s and GCs are the enemy in this case).  [Implementing this answer](http://stackoverflow.com/a/6005949/3602057) seems to yield 32s consistently now.  

However, this does add extra overhead to the constructor and also each benchmark method now.  So it would be great to know if there is anything further on BDN's side that could possibly address this that I should know about.  Otherwise, I think we're good here. 👍
