### ISSUE TITLE
Pick better background colors for output

### ISSUE THREAD

**Issue by davidfowl** [dotnet/BenchmarkDotNet#376]
![image](https://cloud.githubusercontent.com/assets/95136/23394968/d3b3a35e-fd40-11e6-8719-2247fe27b76e.png)

**Comment by AndreyAkinshin** [comment]
Makes sense. Usually, I use `cmd`. In PowerShell it doesn't look great. Any color recommendation?

**Comment by davidfowl** [comment]
Maybe always set the background color as well as foreground color? OR do something fancy like this https://github.com/Eilon/ProjectKIssueList/blob/5040df74b41dcd4f3bbf0470f851a6b924b0af06/src/Hubbup.Web/Utils/ColorMath.cs 😄

**Comment by AndreyAkinshin** [comment]
Looks interesting, I like an idea of adaptive colors. Is it possible to specify custom ConsoleColor for both `net45` and `netcoreapp1.1` (it should be xplat and work on Mono). Now we are using `Console.ForegroundColor` which should have values from [ConsoleColor](https://msdn.microsoft.com/en-us/library/system.consolecolor(v=vs.110).aspx) (this set is very poorly =( ).

**Comment by AndreyAkinshin** [comment]
I found this awesome library: [Colorful.Console](http://colorfulconsole.com/). Let me check how it works on different operation systems.

**Comment by AndreyAkinshin** [comment]
Colorful.Console doesn't work on Linux+Mono. =(
@davidfowl, will it be ok if we introduce advanced color schemes only for Windows?

**Comment by mattwarren** [comment]
BTW, even with `cmd` the output from the 'Outliers' is hard to read, e.g.

![image](https://cloud.githubusercontent.com/assets/157298/23400273/5c050022-fd9b-11e6-8081-537a0e1b0268.png)

**Comment by mattwarren** [comment]
FWIW, a while back I wrote some code that shows all the possible foreground/background colours when running on Windows, here's the screenshot:

![clr or net - console colours](https://cloud.githubusercontent.com/assets/157298/23400332/90791334-fd9b-11e6-8574-572fb74712e3.png)

**Comment by AndreyAkinshin** [comment]
Ok, I changed the hint color to DarkCyan, now it looks much better.

**Comment by adamsitnik** [comment]
I am closing since Andrey has already changed the colors
