### ISSUE TITLE
Problem running benchmark due to "could not copy" during build

### ISSUE THREAD

**Issue by neoeinstein** [dotnet/BenchmarkDotNet#380]
After upgrading to 0.10.3, I am getting the following error when attempting to run my benchmarks:

> C:\Program Files\dotnet\sdk\1.0.0-rc4-004842\Microsoft.Common.CurrentVersion.targets(3987,5): error MSB3021: Unable to copy file "obj\Release\netcoreapp1.1\Project.Benchmarks.dll" to "bin\Release\netcoreapp1.1\Project.Benchmarks.dll". The process cannot access the file 'C:\dev\github.com\org\project\benchmarks\Project.Benchmarks\bin\Release\netcoreapp1.1\Project.Benchmarks.dll' because it is being used by another process. [C:\dev\github.com\org\project\benchmarks\Project.Benchmarks\Project.Benchmarks.fsproj]

Any ideas as to what could be happening here? This is occurring off a fresh build after deleting bin and obj, running restore and build, and then attempting to execute the benchmark directly. I have also attempted to change into the project directory and use dotnet run.

The benchmarks being run have no additional configuration, and are being run under the default settings.

**Comment by neoeinstein** [comment]
Interesting development. It appears to be something to do with how my F# code was structured, and the name of my benchmark namespace.

Reductive example:
* Lib.fs
```fsharp
module Lib
let f x = f x
```
* Benchmark.fs
```fsharp
namespace Library.Benchmarks
type Bench () =
  [<Benchmark>]
  member __.BenchIt () =
    Library.f ()
```

I found that, after running `dotnet publish` against the benchmark project, I was able to get a different set of build errors:

> BDN.Generated.notcs(15,7): error CS0434: The namespace 'Library' in 'Library.Benchmarks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' conflicts with the type 'Library' in 'Library, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' [C:\dev\github.com\org\library\benchmarks\Library.Benchmarks\bin\Release\netcoreapp1.1\publish\BDN.Generated\BenchmarkDotNet.Autogenerated.csproj]

I found that changing either the root namespace for `Benchmark.fs` or making `Library` a namespace instead of a module fixes the problem. (Which means that I have a workaround for this issue.)

**Comment by adamsitnik** [comment]
Hello @neoeinstein !

It seems to be some dotnet cli/msbuild issue. If you apply `[KeepBenchmarkFile]` attribute to the class with benchmarks we are going to generate a separate folder for each benchmark and not remove it after executing it. If there is any problem with dotnet restore/build/run during your benchmark execution you can run the script that we put into the generated folder (.bat file). It will run exact same commands we do. You can run it to see the problem. If the output does not help, you need to modify the script to call all the commands with `--verbosity diagnostics` switch.
