### ISSUE TITLE
AssemblyInformationalVersion doesn't work

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#382]
In the `build\common.props` file, we have the following lines:
```xml
<AssemblyVersion>$(Major).$(Minor).$(Revision).$(BuildNumber)</AssemblyVersion>
<AssemblyFileVersion>$(Major).$(Minor).$(Revision).$(BuildNumber)</AssemblyFileVersion>
<AssemblyInformationalVersion>$(Major).$(Minor).$(Revision).$(BuildNumber)$(PrereleaseLabel)</AssemblyInformationalVersion>
```
However, in the generated AssemblyInfo file (e.g. `BenchmarkDotNet\src\BenchmarkDotNet\obj\Debug\net45\BenchmarkDotNet.AssemblyInfo.cs`) we have the following lines:
```cs
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.10.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.10.3.0")]
```
Thus, `AssemblyVersion` and `AssemblyFileVersion` attributes work fine, and `AssemblyInformationalVersion` doesn't.

**Comment by adamsitnik** [comment]
@AndreyAkinshin maybe we should report a bug to the msbuild team?

**Comment by AndreyAkinshin** [comment]
@adamsitnik, do you have a link to some kind of documentation for these new MSBuild properties? I didn't found anything related to the `AssemblyInformationalVersion` property. Are you sure that this property should work?

**Comment by adamsitnik** [comment]
>  do you have a link to some kind of documentation for these new MSBuild properties? Are you sure that this property should work?

I don't and I am not sure. I took the idea from [here](https://github.com/loresoft/EntityFramework.Extended/blob/afeee3ab66bb5f777253c4c7201239987423be99/Master.proj)

**Comment by AndreyAkinshin** [comment]
Hmm. Last commit in this file was made Sep 5, 2014. I guess it can be outdated. =)

**Comment by AndreyAkinshin** [comment]
Ok, I solve it! In the `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.GenerateAssemblyInfo.targets` file, I have the following lines:
```
<AssemblyAttribute Include="System.Reflection.AssemblyInformationalVersionAttribute" Condition="'$(InformationalVersion)' != '' and '$(GenerateAssemblyInformationalVersionAttribute)' == 'true'">
  <_Parameter1>$(InformationalVersion)</_Parameter1>
</AssemblyAttribute>
```
So, we have to use `InformationalVersion` instead of `AssemblyInformationalVersion`. Already check it, it works! We fix it in master soon!

**Comment by AndreyAkinshin** [comment]
Here is the source of `Microsoft.NET.GenerateAssemblyInfo.targets`: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets
