### ISSUE TITLE
Benchmark various builds of Roslyn

### ISSUE THREAD

**Issue by alrz** [dotnet/BenchmarkDotNet#383]
Related to #290 

This is particularly tricky because benchmarkdotnet itself has a dependency on Roslyn. This'll be extremely useful to benchmark Roslyn perf-targeted changes.

/cc @adamsitnik

**Comment by adamsitnik** [comment]
Hi @alrz thanks for reporting the issue.

I have an idea how we could handle that.
Today we build a new benchmark executable (with help of Roslyn) and then just run it. We reference all dlls that are used by the project that defines benchmarks. (`assembly.GetReferencedAssemblies()`)

My plan for #290 is to add a possibility to define a list of NuGet packages and versions to test against. With custom NuGet feeds (usually every project has CI that publishes new dev nuget package after each build) we could test various builds. Then our job would be to run nuget restore, get the desired version, build the executable with references to the desired dlls and run the benchmarks. The goal of this issue for me is to make sure that we don't add a dependency to any Roslyn dll by default.

Currently I need to prepare two presentations for my talks, but as soon as I find some free time  I will implement it.

**Comment by adamsitnik** [comment]
No progress since 2017, closing.
