### ISSUE TITLE
Print Vector<byte>.Count as part of machine info

### ISSUE THREAD

**Issue by davidfowl** [dotnet/BenchmarkDotNet#384]
Helps to know this when benchmarking SIMD operations

**Comment by AndreyAkinshin** [comment]
@davidfowl, I have the following suggestion: what if we add an attribute for custom machine info lines. Examples:
```cs
[CustomEnvironmentInfo]
public string VectorCountEnvInfo() => "Vector<byte>.Count = " + Vector<byte>.Count;

[CustomEnvironmentInfo]
public IEnumerable<string> MoreEnvInfoLines()
{
  // ...
}
```
* We want to keep the common env info as small as possible. If we add a lot of additional lines by default, people will just skip this part in their perf reports.
* `Vector<byte>.Count` is useful only for SIMD benchmarks and it's not relevant to other benchmarks.
* Probably in other kinds of benchmarks, it makes sense to print other additional env lines.

Thus, I believe it makes sense to provide a way to customize extra lines. @davidfowl, what do you think?

**Comment by davidfowl** [comment]
Sounds good.

**Comment by AndreyAkinshin** [comment]
@gsomix,
I suggest the following plan:
1. We should add a property for custom environment lines in `IConfig`
2. Add API in ManualConfig which allows adding new custom lines.
3. Implement the parsing of the `CustomEnvironmentInfo` attribute in `BenchmarkConverter`, extract custom lines and put them in the constructed config.
4. Introduce API in `Summary` which returns the "classic" part of the environment (`summary.HostEnvironmentInfo.ToFormattedString()`) plus custom lines.
5. Use the new Summary API in all exporters which print this information (`MarkdownExporter`, `HtmlExporter`, `AsciiDocExporter`)
6. Write tests.
7. Describe the new feature in the documentation and add an Intro example.

**Comment by roji** [comment]
Any progress on this ? It would be really nice to see this merged and released...

**Comment by AndreyAkinshin** [comment]
@roji here is the relevant PR: #924

**Comment by roji** [comment]
FYI, a good use case for this is when building a multi-version BDN suite - see https://github.com/aspnet/EntityFrameworkCore/pull/14624#issuecomment-461319553.

In a nutshell, it's common to want to compare current perf against the that of the latest released version, by using different MSBuild build configs (`Release` vs. `ReleaseLastVersion`), and conditionally depending on a published nuget. When doing this, it seems like a good idea to include the project version in the summary headers, to prevent any confusion on which version was used in a given report.

**Comment by MarekM25** [comment]
Is it still unsolved? @AndreyAkinshin assign me, please. In my spare time, I will give it a try.

**Comment by AndreyAkinshin** [comment]
@MarekM25 thanks! You are assigned.

**Comment by gsomix** [comment]
@MarekM25 hey, any news on it? Thanks!

**Comment by gsomix** [comment]
@MarekM25 Please let me know if you need any help. I'm going to review my old PR during #hacktoberfest, so don't hesitate to ask anything.

**Comment by MarekM25** [comment]
> 
> 
> @MarekM25 Please let me know if you need any help. I'm going to review my old PR during #hacktoberfest, so don't hesitate to ask anything.

Hi @gsomix!
I will get down to it this weekend. Thank you for your support! I don't have any questions for now, but I will remember about you.

**Comment by adamsitnik** [comment]
Fixed by https://github.com/dotnet/BenchmarkDotNet/pull/2051
