### ISSUE TITLE
Support default bootstrapper that can select and run a set of tests

### ISSUE THREAD

**Issue by davidfowl** [dotnet/BenchmarkDotNet#386]
Today all of our benchmark projects have code like this:

https://github.com/aspnet/KestrelHttpServer/blob/3c8ee39f1de441daf24c63943dc335af92bdf215/test/Microsoft.AspNetCore.Server.Kestrel.Performance/Program.cs#L13-L26

Which is pretty crappy to do. What we need is a default bootstrapper with command line args support to allow you to run, a single performance test, a group of all or all tests.

**Comment by AndreyAkinshin** [comment]
We already have such API: `BenchmarkSwitcher`. We use it in our `BenchmarkDotNet.Samples` (see https://github.com/dotnet/BenchmarkDotNet/blob/ae4cc8739844f99eaca0d0928b84c3109fc36fff/samples/BenchmarkDotNet.Samples/Program.cs#L10 and http://benchmarkdotnet.org/HowToRun.htm#benchmarkswitcher): it prints all available benchmark to console and allows to choose one (or several) benchmarks to run. Let me know if you miss any features.

**Comment by davidfowl** [comment]
👏

**Comment by pakrym** [comment]
It would be nice to have an easy way to run selected test method inline in main process for profiling. Right now we have to write a loop inside `Program.Main` to be able to profile one of the benchmarks method.

**Comment by AndreyAkinshin** [comment]
@pakrym, sounds interesting. Could you create a separate issue about that?
