### ISSUE TITLE
Precise Machine Counter Diagnoser

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#388]
Few days ago I saw a discussion at corefxlab regarding Spans and Benchmarking. It was clear to me that the developers struggle with a problems that BenchmarkDotNet solves in a very good way.

However when I mentioned BenchmarkDotNet as the cure, @KrzysztofCwalina [replied](https://github.com/dotnet/corefxlab/pull/1278#issuecomment-285082017):

> Yeah, we have. In general I love BenchmarkDotNet and use it in many cases. It does have better front end reporting capabilities and is more mature from reliability and statistical analysis perspective. But it seems like **BenchmarkDotNet does not support measuring instructions retired, cache misses, and branch mispredictions** that we often find very useful. Would be great to combine the efforts/features :-)

So I decided to implement this feature. I have analyzed the docs and mainly the code of xunit.performance, perfview and Microsoft.Diagnostics.Tracing.TraceEvent and with some luck found the way to get these PMC counters working for BenchmarkDotNet.

It would be great if some of our users could give me more suggestions and use cases. What do I mean by that? Following counters are available:

```
Timer
TotalIssues
BranchInstructions
CacheMisses
BranchMispredictions
TotalCycles
UnhaltedCoreCycles
InstructionRetired
UnhaltedReferenceCycles
LLCReference
LLCMisses
BranchInstructionRetired
BranchMispredictsRetired
```

Currently, I am using only:
```
BranchInstructions
CacheMisses
BranchMispredictions
InstructionRetired
```

and calculate Misspredict rate as `BranchMispredictions / BranchInstructions`. 

Should I include more counters? Is there anything more that we could calculate to make the tool more usefull? Reminder: the number of counters that can be used is limited and dependent on hardware. I can not simply record all of them (usually only 3 or 4).

/cc @goldshtn @benaadams @mattwarren @AndreyAkinshin @redknightlois 

Sample results:

```
 |             Method |        Mean |    StdDev | Misspredict rate |
 |------------------- |------------ |---------- |----------------- |
 |       SortedBranch |  22.9457 us | 1.4673 us |           0.03 % |
 |     UnsortedBranch | 147.0984 us | 2.8415 us |          23.32 % |
 |   SortedBranchless |  31.4378 us | 1.0527 us |           0.04 % |
 | UnsortedBranchless |  30.3965 us | 0.7525 us |           0.05 % |

**Comment by redknightlois** [comment]
Cache|Memory behavior is something we rely a lot on. So anything you can get from that (L1|L2|L3 Hit/Miss) is good to go on our side. Total vs. Unhalted is also important. Branch instructions vs. Branch missprediction is useful too but harder to make decisions from total numbers instead of specific location.

**Comment by AndreyAkinshin** [comment]
I love this idea! I'm not sure how it should be implemented eventually, but I have some thoughts about how it should look like.

1. We should have an API which allows customizing the set of hardware counters. An example:
```cs
[HardwareCounters(HardwareCounter.BranchMispredictions, 
                  HardwareCounter.InstructionRetired)]
public class MyBench
```

2. These APIs should be OS/TargetFramework-independent. Thus, we should have the `HardwareCounter.*` stuff in `BenchmarkDotNet.Core`. Next, we should implement different HardwareCounterProviders (for the Full Framework / CoreCLR; for Windows, Linux, and MacOS). If there are no providers for the current environment (or we don't support any of required counters), we should print a warning.

3. I agree with @redknightlois; it would be nice to have (L1|L2|L3 Hit/Miss) counters. However, I'm not sure that it's possible to do it on Windows via ETW, but we definitely have to implement it on Linux via `perf`.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, I tried to run the `Cpu_BranchPerdictor` sample, here is my result:
```
// Run, Diagnostic
// Execute: w:\Work\BenchmarkDotNet\samples\BenchmarkDotNet.Samples\bin\Release\net45\win7-x86\BDN.Generated.exe diagnoserAttached
// BeforeAnythingElse

Unhandled Exception: System.InvalidOperationException: Must be elevated (Admin) to run this program.
   at BenchmarkDotNet.Diagnostics.Windows.PmcDiagnoser.BeforeAnythingElse(Process process, Benchmark benchmark)
   at BenchmarkDotNet.Extensions.CommonExtensions.ForEach[T](IList`1 source, Action`1 command)
   at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
   at BenchmarkDotNet.Toolchains.Executor.Execute(Process process, Benchmark benchmark, SynchronousProcessOutputLoggerWithDiagnoser loggerWithDiagnoser, ILogger logger)
   at BenchmarkDotNet.Toolchains.Executor.Execute(Benchmark benchmark, ILogger logger, String exePath, String workingDirectory, String args, IDiagnoser diagnoser, IResolver resolver)
   at BenchmarkDotNet.Toolchains.Executor.Execute(BuildResult buildResult, Benchmark benchmark, ILogger logger, IResolver resolver, IDiagnoser compositeDiagnoser)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Execute(ILogger logger, Benchmark benchmark, IToolchain toolchain, BuildResult buildResult, IConfig config, IResolver resolver, GcStats& gcStats)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark benchmark, ILogger logger, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, ILogger logger, String title, IConfig config, String rootArtifactsFolderPath, Func`2 toolchainProvider, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerCore.Run(Benchmark[] benchmarks, IConfig config, Func`2 toolchainProvider)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunBenchmarks(String[] args)
   at BenchmarkDotNet.Samples.Program.Main(String[] args)
```
Could you add an additional check + warning?

**Comment by adamsitnik** [comment]
> We should have an API which allows customizing the set of hardware counters. An example:
```cs
[HardwareCounters(HardwareCounter.BranchMispredictions, 
                  HardwareCounter.InstructionRetired)]
public class MyBench
```

> These APIs should be OS/TargetFramework-independent. Thus, we should have the HardwareCounter.* stuff in BenchmarkDotNet.Core. Next, we should implement different HardwareCounterProviders (for the Full Framework / CoreCLR; for Windows, Linux, and MacOS). If there are no providers for the current environment (or we don't support any of required counters), we should print a warning.

I like this idea.  I will define a set of available hardware counters in our .Core package, and make it configurable via the attributes like you have just shown.

Then I will make it work for classic .NET on Windows by using the diagnoser that I implemented. As soon as `Microsoft.Diagnostics.Tracing.TraceEvent` is [ported to .NET Core](https://github.com/Microsoft/perfview/issues/165) I will implement it for .NET Core. 

> I agree with @redknightlois; it would be nice to have (L1|L2|L3 Hit/Miss) counters. However, I'm not sure that it's possible to do it on Windows via ETW, but we definitely have to implement it on Linux via perf.

I think that we should wait for the Microsoft to make the `Microsoft.Diagnostics.Tracing.TraceEvent` working on Linux. It's just too big for us now.

> Could you add an additional check + warning?

I assume that you read the info about exception but would like to have nicer error message? Consider it done ;)

**Comment by AndreyAkinshin** [comment]
> It's just too big for us now.

I don't think that it's too hard to implement. If you prepare an infrastructure for hardware counters, I could try to implement it on Linux via `perf`.

**Comment by eaexo** [comment]
Hi @adamsitnik  and @AndreyAkinshin 

I wonder if you plan to add support for IHardwareCountersDiagnoser on Linux systems?

**Comment by AndreyAkinshin** [comment]
@eaexo, I don't have any plans for that. If you'd like to work on it, pull requests are welcome.
