### ISSUE TITLE
BenchmarkSwitcher should take an optinal IConfig

### ISSUE THREAD

**Issue by ILMTitan** [dotnet/BenchmarkDotNet#391]
I wish to create a custom `Exporter` that sends benchmark data to Google BigQuery tables. The project I wish to use it on (NodaTime) currently uses `BenchmarkSwitcher` to run the benchmarks. `BenchmarkSwitcher` has no way to inject an external `Exporter`. A solution would be to have the `BenchmarkSwitcher` constructor or `Run()` method could take an `IConfig`.

I am willing to make a pull request to add this change. Would it be better for the constructor, the `Run()` method, or both?

**Comment by AndreyAkinshin** [comment]
Hey @ILMTitan. Great idea, a PR is welcome! I think it would be better to add an additional argument in the `Run` method. Also it would be great if you add a few tests and update the documentation.

**Comment by adamsitnik** [comment]
@ILMTitan thanks for your contribution! PR merge, I am closing the issue
