### ISSUE TITLE
Any chance in removing F# dependency

### ISSUE THREAD

**Issue by AcousticGuitar** [dotnet/BenchmarkDotNet#402]
Am considering the project for client VM work but don't like F# dependency.  Will review impact on DLL size and ease of use in using on remote VM clients and post back.

**Comment by AndreyAkinshin** [comment]
Hey @AcousticGuitar. Which dependency do you mean?

**Comment by AcousticGuitar** [comment]
Hi Andrey, when I cloned the project to my desktop and tried to build, it immediately forced a F# install to my Visual Studio Instance.  I think I know now why, there are F# samples and I don't have F# component installed.

**Comment by AndreyAkinshin** [comment]
> I think I know now why, there are F# samples and I don't have F# component installed.

Exactly.

Why do you want to build BenchmarkDotNet from source code on remote client VM? We have NuGet packages which can be installed to your project without any F# dependencies. If you want to develop new features in BenchmarkDotNet, you have to install the F# component (or unload F# projects).

**Comment by AcousticGuitar** [comment]
I'm a dummy.  When I saw the samples, I cloned and try to bring up in VS2015.   I just tried it again today in 2017 and it loaded just fine, samples and all.
