### ISSUE TITLE
Opening Project in VS2015 after installing F# dependencies

### ISSUE THREAD

**Issue by AcousticGuitar** [dotnet/BenchmarkDotNet#403]
All files show unloaded in project any attempt to reload show this error.

<img width="400" alt="benchmark" src="https://cloud.githubusercontent.com/assets/10676026/24368409/f3ac2748-12e5-11e7-8630-1bb30a12b277.PNG">

**Comment by adamsitnik** [comment]
You need Visual Studio 2017 to be able to compile and run our solution.

[More info](https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/guide/Contributing/Building.md). And also please use [our docs](http://benchmarkdotnet.org/) and [our gitter](https://gitter.im/dotnet/BenchmarkDotNet) next time.
