### ISSUE TITLE
Autoselecting amount of digits after the decimal point

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#404]
Right now the default is 4. So, the summary table column looks like that:
```
123.4567 ns
124.4567 ns
125.4567 ns
```
However, in general case, it doesn't make any sense to print so many digits because we don't have the appropriate precision level. Thus, we can reformat the above table in the following way:
```
123.4 ns
124.4 ns
125.4 ns
```
Profit: the column became narrower, we threw out insignificant numbers (0.0567 is on the random noise level).
Suggestion: in each column we choose the best time unit (as usual), next we choose the best amount of digits after the decimal point. The minimum value is 1 digits (because we have to show that values are fractional numbers). The best value can be calculated with the following rule: we should take the minimal number in the column and print at least 4 significant digits (e.g.: `1234.5`, `123.4`, `12.34`, `1.234`, `0.1234`).

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin 

We have [such feature](https://github.com/rsdn/CodeJam/blob/master/PerfTests/src/%5BL1_CompetitionApi%5D/Metrics/%5BMetricValues%5D/MetricValueHelpers.cs#L62) in our perftests project.

[Unit tests with example cases](https://github.com/rsdn/CodeJam/blob/master/PerfTests/tests/%5BL1_CompetitionApi%5D/MetricValueHelpersTests.cs#L60).

**Comment by AmadeusW** [comment]
> next we choose the best amount of digits after the decimal point
> The best value can be calculated with the following rule: we should take the minimal number in the column and print at least 4 significant digits (e.g.: 1234.5, 123.4, 12.34, 1.234, 0.1234)

Just to clarify; if the smallest value was 0.1234, then we will display 4 decimal digits for all values,
if the smallest value was 12.34, we will display 2 decimal digits for all values
if the smallest value was 12.3, we make it 12.30 because we want at least 4 digits. We display 2 decimal digits for all values
and if the smallest value was 12.34567, we will display 5 decimal digits for all values?

**Comment by AndreyAkinshin** [comment]
> if the smallest value was 0.1234, then we will display 4 decimal digits for all values,
if the smallest value was 12.34, we will display 2 decimal digits for all values
if the smallest value was 12.3, we make it 12.30 because we want at least 4 digits. We display 2 decimal digits for all values

Yes.

> and if the smallest value was 12.34567, we will display 5 decimal digits for all values?

No, we will display 2 decimal digits (12.34567 -> 12.34; 123 -> 123.00)

**Comment by AndreyAkinshin** [comment]
Hey @AmadeusW, any progress with the issue?

**Comment by AmadeusW** [comment]
I won't be able to work on it until after May 10th, and the code I got works per table, not per column. Feel free to label it as up for grabs
