### ISSUE TITLE
BenchmarkDotNet with netcoreapp2.0 requires using RuntimeFrameworkVersion directly in the project file

### ISSUE THREAD

**Issue by rynowak** [dotnet/BenchmarkDotNet#406]
See: https://github.com/aspnet/Mvc/pull/6056/files

We found that restore of the generated projects will fail without putting `<RuntimeFrameworkVersion>` directly in the `.csproj` with an error like:
```
error : Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0
```

We'd generally prefer to control `<RuntimeFrameworkVersion>` globally for the repo in a [shared `.props` file](https://github.com/aspnet/Mvc/blob/dev/build/dependencies.props) but this seems to default BenchmarkDotNet's detection of this value.

**Comment by adamsitnik** [comment]
@rynowak I have now added an option to check imported .props files for this setting. Please let me know if it works or not. You can grab the latest version from `<add key="appveyor-bdn" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />`
