### ISSUE TITLE
Generic classes with benchmarks

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/BenchmarkDotNet#417]
```c#
public class Foo<T>
{
    [Benchmark]
    public object Bar()
    {
        ...
    }
}
```
When running this the report is named Foo`1.
Would be nice if it was named Foo{Baz}

**Comment by adamsitnik** [comment]
Generic types are not supported by design.

The problem is that when we are constructing benchmarks we can't tell what `T` is. The behavior could be different for value and reference types.

You need to create type that derives from generic class, and then run benchmarks for it.

Sth like:
```cs
public class FooOfInt : Foo<int>
{
}
```

**Comment by JohanLarsson** [comment]
Ok, thanks
