### ISSUE TITLE
Make BenchmarkDotNet.Core runtime independent

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#420]
The goal is to have `BenchmarkDotNet.Core` without all the nasty `#if` defines, which should help with the UAP integration.

My initial idea:

1. Make `BenchmarkDotNet.Core` target lowest .NET standard possible
2. Move all things that require `#if` defines to runtime-specific packages
3. All these things should be injected by `BenchmarkDotNet` as interface implementations (for example IRuntimeInformation) to the runner.

@zabulus I have created new branch called [`uap`](https://github.com/dotnet/BenchmarkDotNet/tree/uap) for your PR. Once you have the tests script runnable please create a new PR to this branch. Then I will merge it and start the refactoring. Once we are all happy with the results of the refactor @AndreyAkinshin is going to merge it to master.

**Comment by adamsitnik** [comment]
@AndreyAkinshin I would like to make it work for 0.10.5

**Comment by AndreyAkinshin** [comment]
@adamsitnik, if we are going to change the NuGet package set, it makes sense to make it `0.11.0` instead of `0.10.5`.
I like your approach, here are some additional thoughts. Probably it makes sense to rename `BenchmarkDotNet.Core` because some people think that it's a BenchmarkDotNet version for .NET Core. Also, if we are going to introduce an additional package for core logic on .NET Core, it will be more confusing. For example, we can call it `BenchmarkDotNet.Logic` (`netstandard`). We can also introduce something like `BenchmarkDotNet.Logic.NetCore`, `BenchmarkDotNet.Logic.NetStandard`, `BenchmarkDotNet.Logic.Uap`. If you have better ideas for the naming style, I'm happy to hear it. =)

**Comment by adamsitnik** [comment]
> because some people think that it's a BenchmarkDotNet version for .NET Core. 

I agree. I will think of it. Maybe just `BenchmarkDotNet.Standard` or `BenchmarkDotNet.RuntimeIndependent` ? Ofc the namespaces will not change (`Benchmark.Attributes`)

**Comment by adamsitnik** [comment]
new idea for the packages:


- `BenchmarkDotNet.Runtime.Independent` - the core logic, .NET standard, no BDN dependencies
- `BenchmarkDotNet.Runtime.Classic` - desktop .NET framework implementation, dependency to `BenchmarkDotNet.Runtime.Independent` 
- `BenchmarkDotNet.Runtime.Core` - .NET Core implementation, dependency to `BenchmarkDotNet.Runtime.Independent` 
- `BenchmarkDotNet.Runtime.Uap` - UAP / .NET Native framework implementation, dependency to `BenchmarkDotNet.Runtime.Independent` 
- `BenchmarkDotNet` - the only one that end users install, dependencies per runtime as of today with .Roslyn package

**Comment by AndreyAkinshin** [comment]
I'm not sure about `Independent` but `BenchmarkDotNet.Runtime` looks like an option.

@ig-sinicyn, @mattwarren, what do you think?

**Comment by zabulus** [comment]
I suggest names regarding where the code runs: 
1. BDN.Host;
2. BDN.Host.Uap; <- Toolchain for UAP is here, for example
3. BDN.Target.Common;
4. BDN.Target.Core; <- .NET core runnable specific code
5. BDN.Target.Uap; <- Templates for UAP running placed here
and so on.
This will take more effort in separation, though.

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin 

I'm afraid this going to be too overbloated. What about this:
1. define an interface for platform-dependent api
2. include implementations but wrap entire implementation with `#if SOME_MONIKER`
3. expose implementation via static field/property.

Almost always there's only a smart part of code to be handled this way.

**Comment by adamsitnik** [comment]
@AndreyAkinshin do you have some big plans for development for the next 1-2 weeks? I don't want to get into huge merge conflict :D

**Comment by AndreyAkinshin** [comment]
@adamsitnik, no big plans, go ahead! Also, it would be great to come up with the new NuGet package set before you starts the big refactoring. I agree with @ig-sinicyn that "this going to be too overbloated." Of course, we have to introduce new packages (basically because of the Uap support), but it would be cool to keep the total amount of packages as small as possible.

**Comment by adamsitnik** [comment]
Sure, I want to keep things simple so we have no bugs, easy deployment and no big changes in our CI config.

**Comment by zabulus** [comment]
I have a spare time this week, and would like to participate in this refactoring.  How can I help?

**Comment by adamsitnik** [comment]
@zabulus thanks! currently I am trying to solve some problems that should not even exist..

For example:
We are using `assembly.Location` in a few places. The core BenchmarkDotNet lib was supposed to be .NET Standard now. This particular method is available for .NET Standard 1.5+ ([link with invalid https cert](https://apisof.net/catalog/System.Reflection.Assembly.Location)). .Net Standard 1.5 = .NET 4.6.1 ([link](https://docs.microsoft.com/en-us/dotnet/articles/standard/library)). 

Possible solutions ( @AndreyAkinshin I need your help with this):
* drop .NET 4.6 support, be 4.6.1 only
* stay low, use reflection to call the missing methods (2 in total) (it's not visible in contract, but its runnable via reflection)
* sth else? what?

**Comment by AndreyAkinshin** [comment]
I think we should stay low if possible.
A workaround: we can define an interface which contains tricky API methods; we also define a static TrickyApiProvider class which contains an instance of the interface. Our `net46`, `netcoreapp11`, `uap10` libraries statically add an implementation of this interface into the provider.
What do you think?

**Comment by zabulus** [comment]
As I see from search result:
https://github.com/dotnet/BenchmarkDotNet/search?utf8=%E2%9C%93&q=assembly.Location&type=

assembly.Location is used in following areas:
1. Generators and builders. Part of toolchains.
2. BenchmarkConverter. Part of Runner. Also used further in Toolchains.
3. Diagnosers.

All these areas are not used in target code. Reflection could be ok, here since this code won't be executed on any target.

**Comment by ig-sinicyn** [comment]
@adamsitnik 
> We are using assembly.Location in a few places

I've solved similar problems few times. We've ended with targeting to netstandard 1.4 and isolating platform-dependent things behind PAL api.

smth like this (pseudocode):

```
interface IPlatformDependent() { string GetAssemblyLocation(Assembly assembly); }

static class PlatformDependentExtensions
{
  private static readonly IPlatformDependent _impl =
#if NETFULL
   new NetFullImpl();
#else if ...
#else
   new StubImpl();
#endif

  public static string GetLocation( this Assembly assembly) => _impl.GetAssemblyLocation(assembly)
}
...
// NetFullImpl.cs
#if NETFULL
  // entire content of NetFullImpl is wrapped with #if
#endif
```

This way we were able to keep things simple, only one project => multiple platform-dependent assemblies => single package.

**Comment by adamsitnik** [comment]
@AndreyAkinshin @zabulus @ig-sinicyn thanks for a lot of good advices!

Now I got into more serious problem:
Let's say that we have IRuntimeInformation, which has runtime-specific implementations in .Classic, .Core  and .Uap packages. But so far RuntimeInformation used to be a static class. And there is a lot of references to it from static contexts (static field initialization mostly, some static ctors). Some of these things can be made non-static. But some, like [Resolvers](https://github.com/dotnet/BenchmarkDotNet/blob/3ac8923f6d1ba4a1210db71f5609fa9e02722a81/src/BenchmarkDotNet.Core/Environments/EnvResolver.cs#L15) rather not. Mostly, because they are referenced in many, many places.

So far I have came up only with one idea which works, but I don't like it. I wrote a class, that has a static property and loads the right IRuntimeInformation implementation by dynamically loading the right runtime-dependent .dll.

What do you guys think about it?

**Comment by zabulus** [comment]
Approach is fine by me, but I'd like to know how resolving is implemented.

**Comment by ig-sinicyn** [comment]
@adamsitnik 

First, are there any point to refactor IRuntimeInformation implementations into separate assemblies?
These tends to be very compact an therefore can be easily turned on and off via conditional symbols.

Second, I'd prefer to not expose PAL interfaces such as IRuntimeInformation as a public API as they are very fragile. What about storing IRuntimeInformation as a private static field and exposing it via public static methods/properties?

**Comment by adamsitnik** [comment]
@ig-sinicyn I should have started with this (I ask questions about the changes but don't argument the need for them). The goal of the refactor is following:

NuGet downloads all required files and all dependencies for all target framework monikers of given package. So if we target .NET 46, Core and Uap a new user would download 1GB+ of packages if we keep everything in single package. We want to support Uap, so we need to solve this problem, in order to do so we need to move it to different package and make our main package runtime-independent.

That's why we can't stay with `#if` in our main package as we did previously.

**Comment by ig-sinicyn** [comment]
@adamsitnik 
I've got it now, thanks!

**Comment by adamsitnik** [comment]
We are now supporting .NET Standard 2.0
