### ISSUE TITLE
Using BenchmarkDotNet with profilers (e.g. dotTrace/dotMemory)

### ISSUE THREAD

**Issue by JamesNK** [dotnet/BenchmarkDotNet#422]
It would be nice if it was possible to use profilers like dotTrace and dotMemory to get more in-depth information about a benchmark.

**Comment by adamsitnik** [comment]
Would you like us to use the profilers to get more data for the end user or just to generate .exe that is profiler friendly (#387)?

**Comment by AndreyAkinshin** [comment]
I think it's a good idea to generate a profiler friendly `.exe`. The main point of discussion is API because BenchmarkDotNet allows enumerating different jobs (includes runtime) and parameter sets. If we want to use a profiler, we should do under specified conditions.

**Comment by JamesNK** [comment]
You'll never be able to offer all the features and UI of a full profiler app. I think making it possible to use a profiler with the output of BenchmarkDotNet is the best course.

**Comment by adamsitnik** [comment]
@JamesNK I am going to close this as duplicate, please track #387 , I am going to implement it for 0.10.5
