### ISSUE TITLE
Make InliningDiagnoser filtering more flexible

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#424]
As a user I want to be able to toggle:

- filtering inlining events per namespace
- showing only inlining failures

**Comment by adamsitnik** [comment]
I was investigating some `ValueTask<T>` issues and I found out that our namespace filtering was too aggressive.

Now users can choose:
```cs
/// <param name="logFailuresOnly">only the methods that failed to get inlined. True by default.</param>
/// <param name="filterByNamespace">only the methods from declaring type's namespace. Set to false if you want to see all Jit inlining events. True by default.</param>
```

/cc @mattwarren

**Comment by mattwarren** [comment]
Yeah that's a nicer way of doing it than that original way, thanks for tidying this up!
