### ISSUE TITLE
Detect multimodal distributions

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#429]
Some benchmarks have several modes and `Mean`/`Median` don't provide useful information. It would be great to have an analyzer which detects such distributions and prints additional warnings (like "This benchmark has 3 modes: 10ms, 50ms, and 500ms").

**Comment by goldshtn** [comment]
Why not a histogram? I'd say a histogram is always more useful than mean/median or any computerized guesses at mode detection.

**Comment by AndreyAkinshin** [comment]
We already have nice distribution plots in RPlotExporter. I use it all the time, and it works perfect for me.
However, people are too lazy. Even if a user knows that it's a good idea to look at the distribution *each time*, he will not do it. It seems that 95% of our users look only at the summary table. Thus, it would be great to print a warning like "This particular benchmark has non-trivial distribution, check the plots."

**Comment by goldshtn** [comment]
If I read you correctly, plots are harder for users because they have to go elsewhere outside the console. So, put the histograms in the console (in ASCII art). Fairly easy.

**Comment by AndreyAkinshin** [comment]
I like the idea of ASCII histograms! However, in my opinion, it should be optional. Imagine that we have 50 benchmark methods. If we just print 50 ASCII histograms by default, nobody will look at it. A great thing about the summary: It's small and provides you an overview of benchmark results. If we add a few additional lines with warnings amount non-trivial distributions, it will be really useful; it will guide users to continue performance investigation in a specific direction. If we add 2000 extra lines with beautiful ASCII charts, users will just ignore it.

**Comment by goldshtn** [comment]
I'd try to think of a way to push the histogram into the summary table instead of all the statistics. It doesn't have to be more than 2-3 lines. Mockup:

```
Method      Mean    Distribution
MyMethod  4.32           _--_
                                 ___       -__
```

**Comment by goldshtn** [comment]
Well the ascii art didn't go as well as I thought from my phone, but I think you get the gist.

**Comment by goldshtn** [comment]
See https://github.com/holman/spark/blob/master/README.md as an example.

**Comment by AndreyAkinshin** [comment]
Sounds interesting, will think about it. Probably it will not be easy to implement (basically because we have a small amount of character and sometimes distributions look really crazy), but I'd like to have such option in *some* of my benchmarks.
However, I still don't think that we should print it *by default for all benchmarks*. Especially, if it requires 2-3 lines per benchmark instead of one in the summary table.
Anyway, we need an analyzer which detects that something wrong with a distribution and shows a warning. It's a rare situation when we really have a multimodal distribution. It doesn't make sense to provide additional information about the distribution when a user don't need it.
