### ISSUE TITLE
Allocation output suddenly is 0 GB

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/BenchmarkDotNet#434]
I'm not sure how far this can be reproduced, it currently happens with https://github.com/Tornhoof/RoaringBitmap/tree/struct (Desktop .NET 4.6.2, Benchmark.NET 0.10.4)
As soon as I comment out the other benchmarks (only one left) the output changes to the following:

 | Method |      Mean |     Error |    StdDev |    Gen 0 | Allocated |
 |------- |----------:|----------:|----------:|---------:|----------:|
 |     Or | 2.3295 ms | 0.0028 ms | 0.0026 ms | 891.4063 |      0 GB |

with more benchmarks it looks like this:

 |  Method |       Mean |     Error |    StdDev |    Gen 0 | Allocated |
 |-------- |-----------:|----------:|----------:|---------:|----------:|
 |      Or |  2.3559 ms | 0.0019 ms | 0.0017 ms | 888.2813 |   3.89 MB |
 |     Xor |  2.4366 ms | 0.0057 ms | 0.0054 ms | 904.9479 |   3.96 MB |
 |     And |  2.2280 ms | 0.0028 ms | 0.0025 ms | 273.9583 |   1.32 MB |
 |  AndNot |  2.3571 ms | 0.0045 ms | 0.0037 ms | 731.2500 |   3.22 MB |
 | Iterate | 88.9045 ms | 0.0479 ms | 0.0374 ms |        - |   0.05 MB |

I'm quite certain that the one test still allocates memory, as soon as I have more than one benchmark the allocated column is correct and as soon as I have only one, the allocated column is 0 GB.

**Comment by Tornhoof** [comment]
Smaller Repo (apparently it's unrelated to the one/more benchmark case):
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            BenchmarkRunner.Run<Benchmark>();
        }
    }

    [MemoryDiagnoser]
    public class Benchmark
    {
        [Benchmark]
        public int AllocateMemory()
        {
            var b = new byte[1<<20];
            return b.Length;
        }

        [Benchmark]
        public int AllocateMoreMemory()
        {
            var b = new byte[1 << 20];
            return b.Length;
        }
    }

Output is:

``` ini

BenchmarkDotNet=v0.10.4, OS=Windows 10.0.15063
Processor=Intel Core i7-4790K CPU 4.00GHz (Haswell), ProcessorCount=8
Frequency=3906245 Hz, Resolution=256.0003 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.7.2046.0
  DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.7.2046.0


```
 |             Method |       Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
 |------------------- |-----------:|----------:|----------:|---------:|---------:|---------:|----------:|
 |     AllocateMemory | 15.7494 us | 0.0490 us | 0.0459 us | 333.1451 | 333.1451 | 333.1451 |      0 TB |
 | AllocateMoreMemory | 15.7509 us | 0.0363 us | 0.0340 us | 333.1451 | 333.1451 | 333.1451 |      0 TB |

**Comment by AndreyAkinshin** [comment]
@Tornhoof, thanks for the bug report! The problem is in our size formatting, will fix it soon.
