### ISSUE TITLE
Add `DisassemblyDiagnoser` for outputting disassembled JITed code.

### ISSUE THREAD

**Issue by nietras** [dotnet/BenchmarkDotNet#437]
As in TryRoslyn (https://github.com/ashmind/TryRoslyn/issues/39 this uses https://github.com/spazzarama/SharpDisasm) but after each benchmark run for a given method get the disassembled x86/x64 (and ARM/ARM64 in the future) JITed code for a given benchmark method. Preferably to full or a certain prespecified call depth.

For example via attribute:
```csharp
using System;
using System.Security.Cryptography;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace MyBenchmarks
{
    [DisassemblyDiagnoser]
    public class Md5VsSha256
    {
        private const int N = 10000;
        private readonly byte[] data;

        private readonly SHA256 sha256 = SHA256.Create();
        private readonly MD5 md5 = MD5.Create();

        public Md5VsSha256()
        {
            data = new byte[N];
            new Random(42).NextBytes(data);
        }

        [Benchmark]
        public byte[] Sha256() => sha256.ComputeHash(data);

        [Benchmark]
        public byte[] Md5() => md5.ComputeHash(data);
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<Md5VsSha256>();
        }
    }
}
```
Output would then have a file per method i.e. `Sha256.asm` and `Md5.asm` for each JIT being benchmarked.

Naming and details regarding this needs to be carefully considered. I specifically chose not to call `AssemblyDiagnoser` as this could be confused with a .NET assembly. We are interested in the native code generated so this can be inspected for further optimization. 

Related to this I could suggest a `ILDiagnoser` that outputs IL for the functions too, for easy IL inspection too.

Ideally, this could also output a navigatable `html` file with asm in it so one could navigate calls easily.

**Comment by adamsitnik** [comment]
Hi @nietras 

I like this idea, we even used to have sth like this. @mattwarren [implemented](https://github.com/dotnet/BenchmarkDotNet/blob/clrmd/BenchmarkDotNet.Diagnostics.Windows/DiagnoserBase.cs) it some time ago.

I remember that the ClrMd api has changed and it just stopped working/compiling #160

**Comment by nietras** [comment]
Ah yeah I thought I had seen something like this being worked on.

Would be great if this could get working, perhaps @mattwarren can see how
the TryRoslyn does it and if anything from that can be used.

**Comment by nietras** [comment]
Saw @adamsitnik  blog post http://adamsitnik.com/Disassembly-Diagnoser/ this is absolutely awesome! 😃

**Comment by nietras** [comment]
Remember to close this with the PR when it gets in if not already. If already a link to PR would be good.

**Comment by adamsitnik** [comment]
@nietras thanks!

I am going to close this issue as soon as I write the documentation (should be this weekend)

btw [here](https://github.com/dotnet/BenchmarkDotNet/commit/647a6745da75bf3893f2e9b7ec35b3ff20a14caa) is the merge commit and [here](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Disassembler.x64/Program.cs) you can find the most important part.

**Comment by adamsitnik** [comment]
I added the docs, simplified installation process and added the navigable html exporter. I am done ;)

**Comment by nietras** [comment]
Awesome, great work! 👍
