### ISSUE TITLE
Need to Update Autogenerated csproj file

### ISSUE THREAD

**Issue by JasonBock** [dotnet/BenchmarkDotNet#438]
I'm trying to add my Rocks package (https://github.com/JasonBock/Rocks) to BenchmarkMockNet (https://github.com/stevedesmond-ca/BenchmarkMockNet). When I run the program, I get an error that contains this:

C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) [M:\JasonBock\Personal\Code Projects\BenchmarkMockNet\bin\Release\netcoreapp1.1\BDN.Generated\BenchmarkDotNet.Autogenerated.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.1. [M:\JasonBock\Personal\CodeProjects\BenchmarkMockNet\bin\Release\netcoreapp1.1\BDN.Generated\BenchmarkDotNet.Autogenerated.csproj]

This isn't that surprising as I found out from Microsoft that if I want to use the Compiler API in .NET Core, I need to add a line to my `<PropertyGroup>` .csproj file (see https://github.com/JasonBock/Rocks/wiki/.NET-Core-Support for details) to get rid of this error. But since BenchmarkDotNet generates the .csproj file, it's not added and the test run fails.

Is there a way to update the generated .csproj file before the tests are run?

**Comment by adamsitnik** [comment]
@JasonBock thanks for the well described report!

I have just pushed a fix. Once [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.5.160) build is done you should be able to download our `0.10.5.160` package with the fix. How it works: if the .csproj of the project that defines benchmarks contains `<PackageTargetFallback>xyz<PackageTargetFallback/>` line we are going to copy it to the generated .csproj.

**Comment by JasonBock** [comment]
I'll give it a whirl when it shows up in Nuget.

**Comment by adamsitnik** [comment]
I forgot to mention that it will show up on our CI feed `https://ci.appveyor.com/nuget/benchmarkdotnet`

**Comment by JasonBock** [comment]
@adamsitnik looks like the build was successful, does it automatically push the package to Nuget as well?

**Comment by adamsitnik** [comment]
@JasonBock yes, but I am not sure about the delays.

I can see it from my VS:

![image](https://cloud.githubusercontent.com/assets/6011991/25582994/31b5c344-2e90-11e7-89de-3c02c63d14df.png)

**Comment by JasonBock** [comment]
OK, I'm still seeing 0.10.5, so .... I'll keep checking throughout the day :)
![image](https://cloud.githubusercontent.com/assets/904213/25583073/d9af3da4-2e55-11e7-8aed-c100a8d43e18.png)

**Comment by adamsitnik** [comment]
@JasonBock You are most probably checking your default NuGet feed which should be nuget.org. You need to add ours to the list, and the select it in VS.

![image](https://cloud.githubusercontent.com/assets/6011991/25583134/c41b7c6a-2e90-11e7-97d5-10e9be80aef7.png)

Don't forget to add NuGet.config file to the BenchmarkMockNet repository so others can also restore this version. Sample [file](https://github.com/adamsitnik/Exceptionless.Net/blob/5e18e9f74a738d71cbe2cb3637675f5efaa83b47/NuGet.Config)

**Comment by JasonBock** [comment]
Ahhhhhh....I was wondering what "bdn-dev" was :)

**Comment by JasonBock** [comment]
This seems to be working - thanks!

**Comment by adamsitnik** [comment]
thanks for the confirmation!

**Comment by AndreyAkinshin** [comment]
@adamsitnik, maybe it makes sense to add the screenshot of VS NuGet Package Sources Window (probably with a few comments) to our docs? (http://benchmarkdotnet.org/NuGet.htm) It will help to explain how to install our nightly builds with one link! What do you think?

By the way, please use `bdn-nightly` as a feed name instead of `bdn-dev` (it will be more consistent because these builds have the `-nightly` suffix in the version).

**Comment by adamsitnik** [comment]
@AndreyAkinshin yes, screen shot would be nice to have. However I think that "bdn-CI-feed" would be a better name than "bdn-dev" and "bdn-nightly". This is our CI feed which contains both develop and nightly packages. What do you think?
