### ISSUE TITLE
Is it possible to configure benchmark to assign rank for runtime?

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/BenchmarkDotNet#442]
I have presented benchmark for "string aggregation" there:
http://stackoverflow.com/questions/799446/creating-a-comma-separated-list-from-iliststring-or-ienumerablestring/43783708#43783708

But rank was assigned ranking all list without respecting the runtime information. I think rank is more correct when methods are grouped by runtime.

Thank you for your work!

**Comment by AndreyAkinshin** [comment]
Hey @rpokrovskij, the grouping is a big problem: different people expect different grouping policy for benchmark. And it's not only about the `Rank` column: the `Scaled` column has the same problem.
And Runtime is not the only property which can be invloved in the grouping feature: we also have other Job properties (like `Jit`, `Platform`, and so on), and `Params`.

Thus, I think it would be better to introduce an API which defines how the results should be grouped. It will affect all the columns which use results from different benchmarks at once (like Rank and Scaled).
@rpokrovskij, @adamsitnik, @mattwarren, @ig-sinicyn  any ideas about good API?

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin 

AFAIR we have a `IOrderProvider` for custom ordering. 

Also, I'd prefer the Rank column to follow same grouping logic the `Scaled` column uses (grouped by { Job, Params } pairs), 
```
                Method |  Job | Runtime |     Mean | Rank |  Gen 0 | Allocated |
---------------------- |----- |-------- |---------:|-----:|-------:|----------:|
            StringJoin |  Clr |     Clr | 28.24 us |    4 | 4.9969 |   16.3 kB |
 SeparatorSubstitution |  Clr |     Clr | 17.90 us |    3 | 4.9296 |  16.27 kB |
     SeparatorStepBack |  Clr |     Clr | 16.81 us |    1 | 4.9459 |  16.27 kB |
            Enumerable |  Clr |     Clr | 17.27 us |    2 | 4.9377 |  16.27 kB |
            StringJoin | Core |    Core | 27.51 us |    4 | 5.0296 |  16.26 kB |
 SeparatorSubstitution | Core |    Core | 17.37 us |    3 | 4.9622 |  16.22 kB |
     SeparatorStepBack | Core |    Core | 15.65 us |    1 | 4.9622 |  16.22 kB |
            Enumerable | Core |    Core | 17.00 us |    2 | 4.9622 |  16.22 kB |
```

If someone wants to use global ranking there's should be another one, GlobalRank.

**Comment by AndreyAkinshin** [comment]
@rpokrovskij,
In BenchmarkDotNet v0.10.12, you can mark a job as a baseline (see http://benchmarkdotnet.org/Advanced/Baseline.htm#example-3-jobs). In this case, the Rank column will be calculated for a set of jobs/runtimes.
