### ISSUE TITLE
Implement ColoredLogger for LinqPad

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#447]
Original discussion: https://github.com/dotnet/BenchmarkDotNet/issues/445#issuecomment-300695708

**Comment by bgrainger** [comment]
As an avid BDN and LINQPad user, I'm interested in implementing this (for Hacktoberfest). My understanding of the requirements is:

* Add the code from the linked comment
  * Use Reflection to call `Util.WithStyle` to avoid taking a dependency
  * Detect LINQPad Dark Mode and use alternate colour scheme
* Detect whether running under LINQPad (either using `AppDomain.CurrentDomain.FriendlyName` or assembly location)
* Automatically add a `LinqPadLogger` to the default configuration if running under LINQPad? (Not sure about this)

Out-of-scope (unless easy):

* Add a `ToDump()` method to dump the Summary in a formatted way

Without objection, I'll start working on this.

**Comment by AndreyAkinshin** [comment]
Hey @bgrainger! The plan looks good to me.

**Comment by bgrainger** [comment]
#903 implemented `LinqPadLogger`; this issue should now be closed.
