### ISSUE TITLE
Cannot run BenchmarkDotNet

### ISSUE THREAD

**Issue by spixy** [dotnet/BenchmarkDotNet#454]
Hi, I tried to run example code in VS 2017 with .NET 4.6 and .NET 4.6.1, it compiles but in runtime I am getting System.IO.FileLoadException.

![image](https://cloud.githubusercontent.com/assets/4542110/26497960/a1d6b952-422d-11e7-8eaa-488117af25d8.png)

[Md5VsSha256.txt](https://github.com/dotnet/BenchmarkDotNet/files/1032041/Md5VsSha256.txt)

**Comment by adamsitnik** [comment]
Hi @spixy 

Have you created a new solution and just copied the example or compiled our master branch and run samples?

**Comment by spixy** [comment]
I created a new solution.

**Comment by adamsitnik** [comment]
@spixy Could you upload your whole solution? The most important things for me are .csproj and App.config files.

It's weird because your error says `Could not load file or assembly 'BenchmarkDotNet, Version=1.0.0.0`, we did not publish such a version to NuGet yet ;)

**Comment by AndreyAkinshin** [comment]
@spixy 
Am I right that the name of your new solution is BenchmarkDotNet? If it's true, you probably have to rename your solution because this name is already taken by our package.

**Comment by spixy** [comment]
@AndreyAkinshin 
Yes that fixed it 😃
