### ISSUE TITLE
[Question] What does the unit of measurement us stand for 

### ISSUE THREAD

**Issue by d-saravanan** [dotnet/BenchmarkDotNet#459]
I am a bit unaware of what does the unit of measurement "us" stand for. I have seen the timing values in the reports as 654.6 us / 139.0 us. Can you please let me know what does "us" stand for. 

"ns" stands for nano seconds and "ms" for milliseconds. but "us" is a bit unclear. Can anyone help clarify me

**Comment by AndreyAkinshin** [comment]
@d-saravanan, `us` means [Microsecond](https://en.wikipedia.org/wiki/Microsecond). In fact, it should be `μs`, but `us` is a common replacement of `μs` (some terminals doesn't support the `μ` symbol).

**Comment by d-saravanan** [comment]
Thanks a lot

**Comment by AndreyAkinshin** [comment]
It seems that the `us` notation confuses a lot of people (see also https://github.com/dotnet/BenchmarkDotNet/issues/349). I decided to add a hint line about time units in the legend section (see https://github.com/dotnet/BenchmarkDotNet/commit/f14e508e44b510a26cc3ec5aed30ee7843a92baf). So, you will get a line like this:
```
  1 us  : 1 Microsecond (0.000001 sec)
```
