### ISSUE TITLE
Review interface IConfig

### ISSUE THREAD

**Issue by Backs** [dotnet/BenchmarkDotNet#463]
Look at defenition of IConfig:

    public interface IConfig
    {
        IEnumerable<IColumnProvider> GetColumnProviders();
        IEnumerable<IExporter> GetExporters();
        IEnumerable<ILogger> GetLoggers();
        IEnumerable<IDiagnoser> GetDiagnosers();
        IEnumerable<IAnalyser> GetAnalysers();
        IEnumerable<Job> GetJobs();
        IEnumerable<IValidator> GetValidators();
        IEnumerable<HardwareCounter> GetHardwareCounters();
        IEnumerable<IFilter> GetFilters();        

        IOrderProvider GetOrderProvider();
        ISummaryStyle GetSummaryStyle();

        ConfigUnionRule UnionRule { get; }

        /// <summary>
        /// determines if all auto-generated files should be kept or removed after running benchmarks
        /// </summary>
        bool KeepBenchmarkFiles { get; }
    }

As we see, many methods return IEnumerable<T>. In some cases, I see, it's better to return IReadOnlyCollection to prevent excessive ToList or ToArray calls.
Examples:

https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Running/BenchmarkConverter.cs#L36

`var rawJobs = config?.GetJobs().ToArray() ?? Array.Empty<Job>();`
Collection is better.

https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Running/BenchmarkConverter.cs#L49

`var filters = config.GetFilters().ToList();`
Can be replaced with Collection.

https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Configs/ConfigExtensions.cs#L15
Alse, I think `CompositeLogger`, `CompositeExporter` and others should have constructors that accept IReadOnlyCollection.

https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Diagnostics.Windows/PmcDiagnoser.cs#L166
`var stats = new PmcStats(parameters.Config.GetHardwareCounters().ToArray());`
`PmcStats` constructor accepts IReadOnlyCollection.

Internal implementation of ManualConfig is based on List<T>, so it can be simple replaced with:
`public IReadOnlyCollection<ILogger> GetLoggers() => loggers.AsReadOnly();`

Some changes are required in `DefaultConfig` class.

What do you think?

**Comment by adamsitnik** [comment]
I agree. Personally I don't like `IEnumerable<T>` and I almost never use it. I prefer to use `ImmutableArray<T>` everywhere where I can, but I know that it would require some more work that what you suggest.

**Comment by AndreyAkinshin** [comment]
`IEnumerable` properies were introduces when BenchmarkDotNet was a .NET 4.0 project. Now we target .NET 4.6+, so we can migrate to `IReadOnlyCollection` or `ImmutableArray`.
However, it's a big braking change (it can brake a lot of custom user configs), so I suggest to do it in v0.11.0.

**Comment by adamsitnik** [comment]
> However, it's a big braking change (it can brake a lot of custom user configs), so I suggest to do it in v0.11.0.

good point, we can review the api for `v0.11.0` and make everything what we return truly immutable

**Comment by Backs** [comment]
As I understand, the issue is a little bigger than changing one interface :)
What do you think about pull-requests for this issue? Can I try to fix something?

**Comment by AndreyAkinshin** [comment]
@Backs, we are already working on v0.11.0, see https://github.com/dotnet/BenchmarkDotNet/pull/440 We will be happy to accept your PR after v0.11.0 is released. Right now it's not a good moment because it will be really hard to merge all the changes.

**Comment by Backs** [comment]
@AndreyAkinshin oh, I see really lot of changes :) ok, let's wait v0.11.0

**Comment by adamsitnik** [comment]
Fixed by #912

**Comment by adamsitnik** [comment]
Important: I did not change the interface itself, it would be a very breaking change + VS struggles a lot with code that references Immutable collections (invalid binding redirects)
