### ISSUE TITLE
Iteration setup / cleanup should not be called for Idle()

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#464]
[Engine.RunIteration](https://github.com/dotnet/BenchmarkDotNet/blob/5fe5647a158b41d0c2c949b6e04bca44ec5ff1d7/src/BenchmarkDotNet.Core/Engines/Engine.cs#L150-L161):
```c#
            var action = data.IterationMode.IsIdle() ? IdleAction : MainAction;

            IterationSetupAction(); // no check for IterationMode.IsIdle()
            GcCollect();

            // Measure
            var clock = Clock.Start();
            action(invokeCount / unrollFactor);
            var clockSpan = clock.Stop();

            IterationCleanupAction(); // no check for IterationMode.IsIdle()
            GcCollect();
```

P.S. The warning "Be careful: if you allocate any objects in the [IterationSetup] method, the MemoryDiagnoser results can also be spoiled." in docs should be bold. And the same note should be for iteration cleanup method. Learned it the hard way:)

**Comment by AndreyAkinshin** [comment]
@ig-sinicyn, thanks for another helpful bug reports. Sorry about it, `[IterationSetup]` is a recent feature, and I checked how it works only for `RunStrategy.Monitoring` (`1 iteration` = `1 method invocation`; idle iterations are skipped).
May I ask why do you use `[IterationSetup]/[IterationCleanup]` with the default `RunStrategy`? What's your use case?

This opportunity confuses people (see also: https://github.com/dotnet/BenchmarkDotNet/issues/470), so I'm thinging about disable it (`[IterationSetup]/[IterationCleanup]` will be available for `Monitoring` only).
@ig-sinicyn, @adamsitnik, what do you think?

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin

I have no real use case for inetation / setup cleanup now. I've tried to use it with old test written before Monitoring strategy arrived. Well, not the best idea:)

Have no strong opinion about disabling IterationSetup for default strategy, though. What about reporting a warning instead?

**Comment by adamsitnik** [comment]
@AndreyAkinshin I don't have any opinion here.

So far I have used the IterationSetup once: when I wanted to benchmark .NET allocators.

```cs
[IterationSetup]
public void IterationSetup()
{
    GC.TryStartNoGCRegion(MaxNoGcRegion, disallowFullBlockingGC: true);
}

[IterationCleanup]
public void IterationCleanup()
{
    if (GCSettings.LatencyMode == GCLatencyMode.NoGCRegion)
        GC.EndNoGCRegion();
}

[Benchmark(Description = "new", Baseline = true)]
public void Allocate() => DeadCodeEliminationHelper.KeepAliveWithoutBoxing(new byte[SizeInBytes]);
```

So I was able to tell GC to not cleanup memory for the iteration, to measure how long allocation takes, without GC interruptions. If we disable this feature for non Monitoring benchmarks, I would be able  to use it, but I would need to manually set the iteration count?
