### ISSUE TITLE
MSBuild parameters are not passed to generated benchmark project

### ISSUE THREAD

**Issue by xplicit** [dotnet/BenchmarkDotNet#466]
I run the following command to build and run benchmarks:

```csharp
dotnet restore /p:BASELINE=1
dotnet build /p:BASELINE=1 -c Release
dotnet exec -c Release -f netcoreapp1.1 bin/Release/netcoreapp1.1/benchmarks.dll
```
But BenchmarkDotNet creates its own wrapping project and does not pass `/p:BASELINE=1` to msbuild. Here is content of  `BDN.Generated.sh`

```
call dotnet restore --no-dependencies
call dotnet build --framework netcoreapp1.1 --configuration Release
```

while it should be

```
call dotnet restore /p:BASELINE=1 --no-dependencies
call dotnet build /p:BASELINE=1 --framework netcoreapp1.1 --configuration Release
```

**Comment by adamsitnik** [comment]
Hello @xplicit !

Thanks for a very well described problem!

We have a feature that allows using parameters in our benchmarks. It's called params, [here](http://benchmarkdotnet.org/Advanced/Params.htm) you can find full description.

Could you explain me your motivation behind passing custom parameters as console app parameters to the generated process? Or maybe our `[Params]` feature can be enough for you?

**Comment by xplicit** [comment]
The idea of passing msbuild params is to make benchmarks for different assembly versions of the same library. When I pass `/p:BASELINE=1` I compile and run benchmarks  with baseline version of lib, when I did not pass it I compile  and run benchmarks with current code of library.

So the high-level idea is to run `v1` of `mylib.dll` and `v2` of `mylib.dll` and see if there are performance regressions during the code changes.

**Comment by AndreyAkinshin** [comment]
In the future, I want to implement a feature which allows setting custom environment variable in each job, it will help to support features like this: https://github.com/dotnet/BenchmarkDotNet/issues/262
@adamsitnik, maybe it makes sense to introduce also an ability to setting build arguments?

**Comment by adamsitnik** [comment]
@xplicit the idea sounds very cool! But I can't find any information about this parameter. Could you provide me some link? I would like to implement and test it.

**Comment by xplicit** [comment]
@adamsitnik `BASELINE` is custom property which I define from msbuild command line using `/p` parameter (see https://msdn.microsoft.com/ru-ru/library/ms164311.aspx `/property` parameter).  Then I use it in conditional csproj. Something like that:

```xml
  <Choose>
    <When Condition=" '$(BASELINE)' == '' ">
      <ItemGroup>
        <ProjectReference Include="..\..\src\ServiceStack.Text\ServiceStack.Text.csproj" Version="1.0.*" />
      </ItemGroup>
    </When>
    <When Condition=" '$(BASELINE)' != '' ">
      <ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
        <PackageReference Include="ServiceStack.Text" Version="4.5.8" />
      </ItemGroup>
      <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.1' ">
        <PackageReference Include="ServiceStack.Text.Core" Version="1.0.38" />
      </ItemGroup>
    </When>
  </Choose>
```
So when I pass `/p:BASELINE=1` into msbuild I link with "baseline" version of library, when I do not pass it I link with current developing project.

**Comment by adamsitnik** [comment]
@xplicit now I get it, thanks! I will try to implement it this week

my long term plan is to add similar feature to BenchmarkDotNet. It could be sth like this:

```cs
Job.Default.WithReferences(new PackageReference("PackageName", "1.0.0"));
Job.Default.WithReferences(new PackageReference("PackageName", "2.0.0"));
Job.Default.WithReferences(new ProjectReference("pathToCsProj"));
```

I wanted to implement it a long time ago, but then project.json was being abandoned and I wanted to wait.

**Comment by adamsitnik** [comment]
@xplicit sorry for the delay, here it is:

It's possible now, with new thing called `Arguments`. MsBuild argument does exactly what you need. Sample config:

```cs
public class ConfigWithCustomArguments : ManualConfig
{
    public ConfigWithCustomArguments()
    {
        Add(Job.Core.With(new[] { new MsBuildArgument("/p:BASELINE=1") }).WithId("Baseline=1"));
        Add(Job.Core.WithId("No baseline"));
    }
}

[Config(typeof(ConfigWithCustomArguments))]
public class Sample
{
    [Benchmark]
    public void Benchmark() { }
}
```

With such config the `Benchmark` is going to be executed for both jobs.

As soon as [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.9.296) build finishes, you should be able to grab the latest NuGet package from our CI feed `https://ci.appveyor.com/nuget/benchmarkdotnet`

I am closing it right now, please feel free to reopen if something does not work as expected

**Comment by bluetentacle** [comment]
I'm trying to benchmark the difference between the current and past versions of a library, using the MSBuildArgument command.

I couldn't make it work.

Here's my config:

```csharp
Add(Job.Core.With(new[] { new MsBuildArgument("/p:PREVIOUS_VERSION=1.1.5")}).WithId("Before").AsBaseline());
Add(Job.Core.WithId("Now"));
```

And here's my benchmark csproj:

```xml
  <ItemGroup >
    <ProjectReference Include="..\..\src\MyAssembly.Hosting\MyAssembly.csproj" Condition=" '$(PREVIOUS_VERSION)' == '' " />
    <PackageReference Include="MyAssembly.Hosting" Version="$(PREVIOUS_VERSION)" Condition=" '$(PREVIOUS_VERSION)' != '' " />
  </ItemGroup>
```

It builds but at runtime it craps out. The "Before" job complains that it can't find the version 1.1.6 of MyAssembly, even though the PREVIOUS_VERSION MSBuild parameter instructs it to use version 1.1.5.

It seems that this is because the benchmark project (the one I define the benchmarks) is only built once--without the MSBuild parameter. Indeed, when I look at the temporary folders that BenchmarkDotNet generates, all of the benchmark assemblies are the same.

Any suggestions on how I can actually make my comparison benchmark work?

**Comment by adamsitnik** [comment]
Hi @bluetentacle 

I am afraid that you need to wait until we make some progress with #805
