### ISSUE TITLE
[Bug] IterationSetup not run before every test

### ISSUE THREAD

**Issue by BlueRaja** [dotnet/BenchmarkDotNet#470]
I'm encountering an issue with my benchmarks because `IterationSetup` is not run before every test.

I'm using `IterationSetup` to fill out a data-structure, but sometimes it's not filled out. This causes an exception, which halts all subsequent tests.

Minimal repro:

```
    public class Benchmarks
    {
        public bool HasRunIterationSetup;

        [GlobalSetup]
        public void GlobalSetup()
        {
            HasRunIterationSetup = false;
        }

        [IterationSetup]
        public void IterationSetup()
        {
            HasRunIterationSetup = true;
        }

        [Benchmark]
        public void MyBenchmark()
        {
            if (!HasRunIterationSetup)
            {
                throw new Exception("Iteration Setup was not run");
            }

            Thread.Sleep(5);
            HasRunIterationSetup = false;
        }
    }
```

**Comment by AndreyAkinshin** [comment]
@BlueRaja, `[IterationSetup]` should be executed once before *an iteration* which can contain a lot of method invocation. Please, check out the documentation: http://benchmarkdotnet.org/Advanced/SetupAndCleanup.htm It was designed for `RunStrategy` = `Monitoring` (`1 iteration` = `1 invocation` by default). I'm sorry if the documentation is unclear about it, it's a recent feature.

If you know how to improve documentation (or have any ideas how to make this more obvious for users), pull requests are welcome!

**Comment by BlueRaja** [comment]
What is the distinction between a method invocation and an iteration?  I thought they were equivalent.

**Comment by adamsitnik** [comment]
iteration contains of 1 to many invocations

**Comment by BlueRaja** [comment]
I see. What possible use-case is there for `[IterationSetup]`?

**Comment by AndreyAkinshin** [comment]
`[IterationSetup]` and `[IterationCleanup]` were designed for macrobenchmarks which have a single invocation in each iteration. They can have some logic which should be executed before and after the benchmark method, but it shouldn't be included in the time measurements.

**Comment by BlueRaja** [comment]
Right, I get that now.  My question is, in what situation would it be useful to run code before each iteration (rather than before each invocation), when you don't even know how many invocations will be in an iteration.
