### ISSUE TITLE
PlatformNotSupportedException when reading ProcessorAffinity on non-Windows platforms

### ISSUE THREAD

**Issue by Ky7m** [dotnet/BenchmarkDotNet#474]
*InProcessExecutor* throws an exception on non-Windows platforms (target framework: `netcoreapp1.1`). Specifically, it throws an error when try to get ProcessorAffinity [InProcessExecutor.cs#L95](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Toolchains/InProcess/InProcessExecutor.cs#L95):
```
var oldAffinity = process.ProcessorAffinity;
```
exception:
```
Unhandled Exception: System.PlatformNotSupportedException: Processor affinity for processes or threads is not supported on this platform.
```
I found similar issue #298, but it is closed.

**Comment by AndreyAkinshin** [comment]
Hey @Ky7m, thanks for the report, should be fixed now.

You can check it in BenchmarkDotNet 0.10.8.226 (https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.8.226) from our appveyor feed (see http://benchmarkdotnet.org/Guides/NuGet.htm#nightly)

**Comment by Ky7m** [comment]
Thank you @AndreyAkinshin for prompt response and quick fix. I have verified with new source and issue is gone now. 
Also it was much needed to continue work on #426 . Thanks again!
