### ISSUE TITLE
MEF stops working like 2.0 in benchmark

### ISSUE THREAD

**Issue by kayanme** [dotnet/BenchmarkDotNet#477]
I migrated from BDN 0.9.4 to 0.10.8 recently.
After that I found, that resolving an open generic export in benchmark (declared with [InheritedExport]) cannot be discovered anymore. Looking for some info  ([here](https://stackoverflow.com/questions/18147371/open-generic-types-wont-register-in-the-catalog) for example, the similar problem, but another site of origin) I found, that there is some issue with MEF to detect it's calling runtime (thus it starts to behave like 1.0 from .net 4.0 instead of 2.0 from .net 4.5 and later). 
I couldn't influence that behavior in any way.
Actually I tried different project  target platform (from 4.5 to 4.6.1), various app.config options,  an older (.net 4.5.1) version of BDN (0.10.3).
Code example is below, it crushes with ImportCardinalityMismatch which is surely an incorrect behavior for MEF in 4.5:
```
  class Program
    {
        static void Main(string[] args)
        {
            BenchmarkDotNet.Running.BenchmarkRunner.Run<BadBench>();
            Console.ReadLine();
        }
    }

    [InheritedExport]
    public class E<T>
    {

    }

  
    public class BadBench
    {
        [Benchmark]
        public void Test()
        {
            new CompositionContainer(new AssemblyCatalog(typeof(Program).Assembly).GetExportedValue<E<int>>();
        }
    }
```
This works fine with BDN 0.9.4 (under the same project targets).

**Comment by adamsitnik** [comment]
No progress since 2017, I am closing the issue.
