### ISSUE TITLE
Invalid C# code generated for valid F# identifiers

### ISSUE THREAD

**Issue by inosik** [dotnet/BenchmarkDotNet#479]
If a benchmark method name contains characters, which are invalid in C# for identifiers, BenchmarkDotNet generates invalid C# code for those methods [in the constructor][src] of the generated `Runnable` class. This code doesn't compile, when the benchmark is run.

  [src]: https://github.com/dotnet/BenchmarkDotNet/blob/afa803d0e38c0e11864b2e4394d4a85d3801d944/src/BenchmarkDotNet.Core/Templates/BenchmarkProgram.txt#L144

This benchmark written in F# reproduces the bug with 0.10.8 of the BenchmarkDotNet NuGet package:

``` fsharp
module Program

open System
open BenchmarkDotNet.Attributes
open BenchmarkDotNet.Running

type StringConcatenationBenchmark () =
    [<Params("string", "another string", "yet another string")>]
    member val String = "" with get, set

    [<Benchmark>]
    // This is OK:
    // member this.String_Concat_method () =
    // This generates invalid code:
    member this.``String.Concat method`` () =
        String.Concat ("{{ ", this.String, " }}")

[<EntryPoint>]
let main argv =
    BenchmarkRunner.Run<StringConcatenationBenchmark> () |> ignore
    0
```

``` xml
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.NET.Sdk" Version="*" />
    <PackageReference Include="FSharp.Core" Version="*" />
    <PackageReference Include="BenchmarkDotNet" Version="*" />
  </ItemGroup>
</Project>
```

**Comment by adamsitnik** [comment]
Thanks for a very well described bug report!

I am going fix it soon. But the fix will be a nice warning telling what is wrong and how to get the custom display name.

**Comment by inosik** [comment]
Would be nice if we'd get the warning *before* any benchmark runs.

**Comment by inosik** [comment]
What if we changed the [code template][template] from this:

  [template]: https://github.com/dotnet/BenchmarkDotNet/blob/afa803d0e38c0e11864b2e4394d4a85d3801d944/src/BenchmarkDotNet.Core/Templates/BenchmarkProgram.txt#L144

``` csharp
mainAction = $TargetMethodDelegate$;
```

to this:

``` csharp
mainAction = ($TargetMethodDelegateType$)typeof(Runnable).GetMethod("$TargetMethodDelegate$").CreateDelegate(typeof($TargetMethodDelegateType$), this);
```

Would this impact the performance and distort the results? It doesn't seem to make much of a difference:

``` fsharp
module Program

open System
open System.Reflection
open BenchmarkDotNet.Attributes
open BenchmarkDotNet.Running

type Subject () =
    member __.Add () = 2 + 2

type MethodCallBenchmark () =
    let target = Subject ()
    let addF = Func<_>(target.Add)
    let addF2 = target.GetType().GetMethod("Add").CreateDelegate(typeof<Func<int>>, target) :?> Func<int>

    [<Benchmark>]
    member this.``Direct_method_call`` () =
        for i in 0..99 do
            ignore (target.Add ())

    [<Benchmark>]
    member this.``Call_via_directly_created_delegate`` () =
        for i in 0..99 do
            ignore (addF.Invoke ())

    [<Benchmark>]
    member this.``Call_via_reflection_delegate`` () =
        for i in 0..99 do
            ignore (addF2.Invoke ())

[<EntryPoint>]
let main argv =
    ignore (BenchmarkRunner.Run<MethodCallBenchmark> ())
    0
```

``` ini
BenchmarkDotNet=v0.10.8, OS=Windows 7 SP1 (6.1.7601)
Processor=Intel Xeon CPU W3550 3.07GHz, ProcessorCount=8
Frequency=2987353 Hz, Resolution=334.7445 ns, Timer=TSC
dotnet cli version=1.0.1
  [Host]     : .NET Core 4.6.25009.03, 64bit RyuJITDEBUG
  DefaultJob : .NET Core 4.6.25009.03, 64bit RyuJIT
```

 |                             Method |        Mean |     Error |    StdDev |      Median |
 |----------------------------------- |------------:|----------:|----------:|------------:|
 |                 Direct_method_call |   0.0443 ns | 0.0334 ns | 0.0478 ns |   0.0188 ns |
 | Call_via_directly_created_delegate | 253.2337 ns | 1.0233 ns | 0.7989 ns | 253.2810 ns |
 |       Call_via_reflection_delegate | 258.8067 ns | 5.1467 ns | 5.9270 ns | 255.6654 ns |

**Comment by adamsitnik** [comment]
It's unfortunately [impossible](https://stackoverflow.com/a/22514528/5852046) to workaround due to C# compiler limitations. We are going to display very nice error, before running any of the benchmarks. 

But you can still get the whitespaces printed in the results instead of just the method name. You can do this by using  `Description` property of our `BenchmarkAttribute`.

Example error message:
```
 Benchmarked method `Standard Lookup` contains illegal characters (whitespaces). Please use `[<Benchmark(Description = "Custom name")>]` to set custom display name.
```

As soon as [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.8.237) CI build ends you should be able to download our [dev package](http://benchmarkdotnet.org/Guides/NuGet.htm#nightly).
