### ISSUE TITLE
Benchmark hangs when defining a configuration for runner 

### ISSUE THREAD

**Issue by kayanme** [dotnet/BenchmarkDotNet#482]
Reproducing previous issue I've got the strange hang in this situation (with different configuration numbers). Benchmark does not even start:
```
 class Program
    {

        static void Main(string[] args)
        {
            var c = new ManualConfig();
            c.Add(Job.Clr.WithTargetCount(2).WithLaunchCount(1).WithWarmupCount(1));
            BenchmarkDotNet.Running.BenchmarkRunner.Run<BadBench>(c);
            Console.ReadLine();
        }
    }

   

    
    public class BadBench
    {
        [Benchmark]
        public void Test()
        {
            Console.WriteLine("Test");
            Thread.Sleep(1000);
        }


        [IterationSetup]
        public void Init()
        {
            Console.WriteLine("Init");
        }

        [IterationCleanup]
        public void Clean()
        {
            Console.WriteLine("Clean");
        }
    }
```
Version 0.10.8

**Comment by adamsitnik** [comment]
Hello @kayanme !

In this case you have not configured any logger, so the benchmark runs but prints nothing to the standard output. I know that it's very confusing, I am adding a fix now that will warn the users.

Please use following code to set loggers, exporters and columns for empty manual config:
```cs
c.Add(DefaultConfig.Instance.GetExporters().ToArray());
c.Add(DefaultConfig.Instance.GetLoggers().ToArray());
c.Add(DefaultConfig.Instance.GetColumnProviders().ToArray());
```

**Comment by adamsitnik** [comment]
Example:
![image](https://user-images.githubusercontent.com/6011991/27708869-85335e2e-5d1a-11e7-9045-b42c9011002e.png)

I hope that you did not waste too much time on this. I took me some time to figure out what is going on here ;)

**Comment by kayanme** [comment]
Everything is ok, I've just stumbled upon it when I was reproducing another bug. :) Thank's a lot anyway!
