### ISSUE TITLE
Broken HTTPS on site

### ISSUE THREAD

**Issue by haf** [dotnet/BenchmarkDotNet#484]
There is https://benchmarkdotnet.org/ but I get cert error when I browse it.

Having HTTPS is important nowadays.

**Comment by adamsitnik** [comment]
Hello @haf ! 

Thanks for reporting the problem. @AndreyAkinshin who maintains our website is on holidays, he should be back within a week.

Until we fix it you can use our [http://benchmarkdotnet.org/](http://benchmarkdotnet.org/) address.

**Comment by AndreyAkinshin** [comment]
BenchmarkDotNet uses GitHub pages with a custom domain. The `Enforce HTTPS` option is unavailable for our site because we have a custom domain configured.
The domain owner is .NET Foundation, so we need some help from @jongalloway here.

**Comment by AndreyAkinshin** [comment]
HTTPS is finally available for custom domains: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
@jongalloway could you please configure DNS records? (I don't have an access), see https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by jongalloway** [comment]
Done - https://benchmarkdotnet.org/ is set up.

**Comment by AndreyAkinshin** [comment]
@jongalloway, thanks! It works now!
![image](https://user-images.githubusercontent.com/2259237/39563571-6a99a3b6-4eb9-11e8-80b4-0ae38ab07b57.png)
