### ISSUE TITLE
Documentation page broken link

### ISSUE THREAD

**Issue by snalesso** [dotnet/BenchmarkDotNet#489]
In [Wiki > People using BenchmarkDotNet > Projects](https://github.com/dotnet/BenchmarkDotNet/wiki/People-using-BenchmarkDotNet#projects) list, the link for the "CacheManager" entry is broken, I think:

it points to
> http://cachemanager.net/Documentation/Index/cachemanager_readme

instead of
> https://github.com/MichaCo/CacheManager

**Comment by adamsitnik** [comment]
Hello @snalesso 

Thanks for the bug report. I have updated the link.
