### ISSUE TITLE
BDN.Generated.exe is locking files when killed with ctrl+c

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#490]
As reported by @Horusiath in our Gitter:

> do any of you have problem with BDN.Generated.exe process? Sometimes when I hit Ctrl+F5 on my benchmark console project I got BenchmarkDotNet stopped working error window. Then I cannot rebuild my project because BDN.Generated.exe is locking files. Moreover I cannot stop that process, because it resurrects immediately afterwards... like virus 

1. VS2017 Solution with console app running BenchmarkSwitcher.FromAssembly(Assembly.GetExecutingAssembly()).RunAll()(console app project set as startup project)
2. Solution build set on Release
3. Hit Ctrl+F5 (run project without debugger)
4. Here I got immediate crash with error window.
5. When I'm trying to rebuild solution, it cannot be done since another process is locking files from build directory.
6. Ctrl+Shift+Esc (open Task window) + stop BDN.Generated.exe task
7. This task reappear in Task Manager again after a second.
8. Go to 6

**Comment by adamsitnik** [comment]
@Horusiath fixed! please let me know if you ever run into this problem again

**Comment by gdoron** [comment]
I came because of the same issue.
It seems like `0.10.8` is the latest version on nuget.
Is there a different repo with the latest bits or do we need to compile from the source code?

Thanks a ton!

**Comment by adamsitnik** [comment]
Hi! @gdoron 

You can check it now by downloading `0.10.8.242` package from our CI NuGet feed:
```
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```
