### ISSUE TITLE
Slower timings with every MainTarget execution - what does it mean?

### ISSUE THREAD

**Issue by kentcb** [dotnet/BenchmarkDotNet#493]
Hi,

If my MainTarget executions get slower with every iteration, what does that generally mean? Example output:
```
MainTarget  1: 1000 op, 2744353414.13 ns, 2.7444 ms/op
MainTarget  2: 1000 op, 3036748756.83 ns, 3.0367 ms/op
MainTarget  3: 1000 op, 3617546645.23 ns, 3.6175 ms/op
MainTarget  4: 1000 op, 4027509054.81 ns, 4.0275 ms/op
MainTarget  5: 1000 op, 4917915183.06 ns, 4.9179 ms/op
MainTarget  6: 1000 op, 4909949646.05 ns, 4.9099 ms/op
MainTarget  7: 1000 op, 5262096180.13 ns, 5.2621 ms/op
MainTarget  8: 1000 op, 5646517306.62 ns, 5.6465 ms/op
MainTarget  9: 1000 op, 5892855996.74 ns, 5.8929 ms/op
MainTarget 10: 1000 op, 6275679493.89 ns, 6.2757 ms/op
```

**Comment by AndreyAkinshin** [comment]
Hi @kentcb,

It means that your benchmark doesn't have s steady state: each run affects the following runs.
By default, BenchmarkDotNet assumes that all method invocations are independent and doesn't affect each other.
Probably I have to write a analysis for such situations.

**Comment by kentcb** [comment]
Thanks @AndreyAkinshin. Is a valid example of that a memory leak? i.e. each run is consuming more and more memory via the leak, thereby affecting the overall perf?

**Comment by AndreyAkinshin** [comment]
Yep, it can be a memory leak, but you have to profile it for sure.

**Comment by AndreyAkinshin** [comment]
Yep, it can be a memory leak, but you have to profile it for sure.

**Comment by kentcb** [comment]
Understood - thanks again, @AndreyAkinshin.
