### ISSUE TITLE
Wrong placement of Frequency?

### ISSUE THREAD

**Issue by PatrickvL** [dotnet/BenchmarkDotNet#494]
https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Horology/FrequencyUnit.cs#L16 references the Frequency type from within the FrequencyUnit type; Shouldn't that be moved to a more appropriate place?

**Comment by AndreyAkinshin** [comment]
@PatrickvL, I don't see a problem here. Where do you want to move it?

**Comment by PatrickvL** [comment]
Nevermind, I overlooked it uses `this`
