### ISSUE TITLE
Integration with TravisCI

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#496]
We need Linux and MacOS agent.
See also: https://github.com/dotnet/BenchmarkDotNet/issues/426, https://github.com/dotnet/BenchmarkDotNet/pull/475

**Comment by jongalloway** [comment]
I'm looking for the Travis access request but haven't found it yet. Also, AppVeyor just added Linux build support yesterday in case that's useful: https://www.appveyor.com/blog/2018/03/06/appveyor-for-linux/

**Comment by jongalloway** [comment]
Found the Travis request and granted access - please verify.

**Comment by AndreyAkinshin** [comment]
@jongalloway, the request is approved, thanks! I will finish the integration soon.

> Also, AppVeyor just added Linux build support yesterday in case that's useful

It's awesome! Will try to set up Linux AppVeyor build as well.

**Comment by AndreyAkinshin** [comment]
Hooray, the Travis integration works: https://travis-ci.org/dotnet/BenchmarkDotNet/jobs/350499537

Unfortunately, currently, the build is red because of troubles with VisualBasic compilation.
@Ky7m, could you help us to solve this problem?

**Comment by Ky7m** [comment]
@AndreyAkinshin I'll check it

**Comment by Ky7m** [comment]
PR #683 is created but it is not ready to be merged due to failed test #684
