### ISSUE TITLE
Opting into app-compat switches in a benchmark doesn't work

### ISSUE THREAD

**Issue by davkean** [dotnet/BenchmarkDotNet#499]
It appears that I can't opt into app-compat switches within a benchmark:

``` C#
public class GetFullPath
{
    [Benchmark]
    public void GetFullPath_Fast()
    {
        AppContext.SetSwitch("Switch.System.IO.UseLegacyPathHandling", false);

        System.IO.Path.GetFullPath(" ");
    }
}
```

**Expected:**
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.**NewNormalizePath**(String path, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)

**Actual:**
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.**LegacyNormalizePath**(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at GetFullPath.GetFullPath_Fast() in C:\Users\davkean\Source\Repos\PathHelpers\PathHelpers\Program.cs:line 138
   at BenchmarkDotNet.Autogenerated.Runnable.MainMultiAction(Int64 invokeCount)
   at BenchmarkDotNet.Engines.Engine.Jitting()
   at BenchmarkDotNet.Autogenerated.Runnable.Run(IHost host)

Not sure how you generate the process, or run the benchmark - have you seen this before?

**Comment by davkean** [comment]
Even via app.config isn't respected:

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <AppContextSwitchOverrides value="Switch.System.IO.UseLegacyPathHandling=false" />
  </runtime>
</configuration>
```

**Comment by davkean** [comment]
@JeremyKuhne @AlexGhiondea I'm trying to benchmark the new normalization paths, do you know under what circumstances we wouldn't respect a switch on above? If I manually run the code without BenchmarkDotNet it works fine - so there's something about how it setups up the appdomain/process that is causing us to skip the AppCompat settings.

**Comment by davkean** [comment]
I stumbled on:
```
        BenchmarkDotNet.Running.BenchmarkRunner.Run<GetFullPath>(ManualConfig.Create(DefaultConfig.Instance)
                                                .With(Job.InProcess));
```

With still doesn't let me flip app compat switches, but does head me down the new path. There's something about how this AppDomain is launched that prevents me from flipping the switches.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, could you take a look?

**Comment by adamsitnik** [comment]
Hi @davkean 

Thanks for trying BenchmarkDotNet!

We generate new process and we also copy and modify the app.config file. For example we support comparing different JITs performance by setting:

```xml
<runtime>
  <useLegacyJit enabled="1" />
</runtime>
```

in the app.config file.

To keep the copying simple, so far we were [removing](https://github.com/dotnet/BenchmarkDotNet/blob/2596471b01083580889b2e8b2de3d8644fb75d55/src/BenchmarkDotNet.Core/Toolchains/AppConfigGenerator.cs#L49) everything from the source app.config file except of assembly binding redirects.

I am going to change it right now, so we will remove only the things that we can set (gcMode, Jit etc)

**Comment by adamsitnik** [comment]
@davkean 

I have changed our default behavior, all custom `<runtime>` setting are rewritten by default from now. As soon as [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.8.252) build finishes you should be able to download new package `0.10.8.252` from our CI feed.

```xml
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

But we still have no answer why `AppContext.SetSwitch("Switch.System.IO.UseLegacyPathHandling", false);` fails. Let's wait for the response from @JeremyKuhne @AlexGhiondea

**Comment by AndreyAkinshin** [comment]
@adamsitnik, can we close this issue now?
