### ISSUE TITLE
[bug] Bug in GetTargetedMatchingMethod() logic

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#511]
BDN 0.10.9.

The `BenchmarkConverter.GetTargetedMatchingMethod()` [method](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Running/BenchmarkConverter.cs#L93-L102) depends on order of methods passed to it, first match wins.

The issue is, there is no warranty that setup/cleanup method with matching `Target` will be enumerated before  setup/cleanup method with empty target. As a proof:
```cs
		[GlobalSetup]
		public static void SetupAlwaysWins() { ... }

		[GlobalSetup(Target = nameof(MyMethod))]
		public static void SetupNeverCalled() { ... }
```

**Comment by ipjohnson** [comment]
I hadn't gone down the road of Targeted and non Targeted in the same benchmark.

It seems like there are two ways to handle this
1) throw an exception as not supported (go one way or the other)
2) treat it as a fallback like what @ig-sinicyn filled a bug on.

Let me know which behavior is preferred and I can put in a pr in the coming days

**Comment by AndreyAkinshin** [comment]
I think that benchmarks which have Target and NonTarget setups at the same time look confusing. So, I suggest to show error about invalid configuration and don't run any of benchmarks.
@ig-sinicyn, @adamsitnik, what do you think?

**Comment by ig-sinicyn** [comment]
I'd prefer to follow standard approach: most specific setup wins.
This way there will be no need to include 10 setup/cleanup methods if there are 10 benchmark methods, 9 methods reuse same logic and only one needs special handling.

**Comment by AndreyAkinshin** [comment]
> This way there will be no need to include 10 setup/cleanup methods if there are 10 benchmark methods, 9 methods reuse same logic and only one needs special handling.

Ok, makes sense.

> Also, there may be more than one targeted attribute applied to the setup/cleanup method.

It looks too strange.

**Comment by ipjohnson** [comment]
@AndreyAkinshin to summarize I'll put together a PR that allows a targeted setup/cleanup to override a non targeted. 

To make things more deterministic I'll add code to throw an exception if there are to many setup/cleanup methods found.

**Comment by adamsitnik** [comment]
I believe that:

1. More than one targeted setup/cleanup matches the benchmark = fail with error
2. One targeted and one general setup/cleanup matches the benchmark = choose the targeted

@ipjohnson we have thing called validators that you can reuse. They are being run before benchmark execution and if you return a critical validation error no benchmark is being executed. [Example](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Validators/BaselineValidator.cs)

**Comment by ipjohnson** [comment]
@adamsitnik I should create a new validator, something like SetupCleanupValidator apply the logic you just outlined. Should this validator be added to DefaultConfig and CompositeValidator?

**Comment by adamsitnik** [comment]
@ipjohnson exactly. Thanks for doing this!!

**Comment by adamsitnik** [comment]
fiex by #525
