### ISSUE TITLE
Support async Setup/Cleanup

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#521]

**Comment by AndreyAkinshin** [comment]
Related issue: https://github.com/dotnet/BenchmarkDotNet/issues/517

**Comment by dlemstra** [comment]
@adamsitnik I already started working on the async `GlobalCleanup` part because the `GlobalSetup` will be merged soon. Is there a reason why `ExecutionValidatorBase` does not check the `GlobalCleanup`?

**Comment by adamsitnik** [comment]
@dlemstra I have merged #892

>  Is there a reason why ExecutionValidatorBase does not check the GlobalCleanup?

no, it must be a bug. It would be great if you could fix it

**Comment by dlemstra** [comment]
Will try to put that in a new PR then.
