### ISSUE TITLE
No namespace in export filenames can lead to data loss

### ISSUE THREAD

**Issue by jskeet** [dotnet/BenchmarkDotNet#529]
Yesterday I added benchmarks to NodaTime for a type, NodaTime.TimeZones.StandardDaylightAlternatingMap. I put the benchmarks in  the NodaTime.Benchmarks.NodaTimeTests.TimeZones namespace.

As it happens, I already *had* some benchmarks for that type, in the NodaTime.Benchmarks.NodaTimeTests namespace. When I looked at the results of my overnight run, only the new tests existed. That's because the JSON file that's generated only includes the short type name, with no namespace.

That's probably great for cases when you're looking at results by hand and don't want long filenames, but in my case I'd rather have long filenames (which are being consumed automatically anyway) and no loss of data.

Perhaps this should be an exporter option?

**Comment by AndreyAkinshin** [comment]
Hey @jskeet, thanks for the report.

I think we always should use fully qualified names for all benchmarks without additional exporter options.

**Comment by Teknikaali** [comment]
I dug around the code and this is what I discovered about exported files' naming conventions:

`Summary.Title` property is being used for **both** the _filename_ and the actual _title of the benchmark_.
Currently `Summary.Title` is generated by using `Type.Name`, but it could be change to `Type.FullName` to enable fully qualified filenames. 

This change would cause a small side effect to the actual output data by making the `Title` value a bit longer. If this is a wanted result then it's ok and nothing to worry about.. The results of this change would look like this:

Property used | Filename | Example JSON output snip
---------- | ---------- | ------
**Type.Name** | IntroExporters-report-brief.json | `"Title":"IntroExporters",` 
**Type.FullName** | BenchmarkDotNet.Samples.Intro.IntroExporters-report-brief.json | `"Title":"BenchmarkDotNet.Samples.Intro.IntroExporters",`

I can start fixing this, if these changes look good to you!

**Comment by adamsitnik** [comment]
@Teknikaali IMHO the best option would be to leave the `Summary.Title` untouched and use the `benchmar.Target.FullName` when creating files

@AndreyAkinshin what do you think?

**Comment by Teknikaali** [comment]
@adamsitnik I think you're right, it should work nicely without any side effects if the `Benchmark.Target.Type.FullName` property would be used. I totally missed this this one!

This then leaves only one more question about the filename handling inside the `ExporterBase` class:
` BenchmarkRunnerCore.GetTitle(...)` is a method that parses the title from a _collection_ of `Benchmark`s.
If only targets of a same type exists in the collection, that type's name will be used as the title.
But if **multiple types** of `Benchmark`s exists, then a custom title will be returned instead:
```csharp
return $"BenchmarkRun-{benchmarkRunIndex:##000}-{DateTime.Now:yyyy-MM-dd-hh-mm-ss}";
```

That custom title is apparently also being used as the filename when exporting, so should I include some kind of check like this inside `ExporterBase` ?
```
if (multiple benchmark types)
    use custom title from Summary.Title
else
    use fully qualified type name from Benchmarks-collection's first benchmark.Target.Type.FullName
```

**Comment by adamsitnik** [comment]
@Teknikaali yes, this looks like the best option

big thanks for doing this!

**Comment by AndreyAkinshin** [comment]
@Teknikaali, LGTM
