### ISSUE TITLE
When I clone, build, and run BenchmarkDotNet.Samples I get an error

### ISSUE THREAD

**Issue by dls314** [dotnet/BenchmarkDotNet#533]
Hi,

I am having trouble getting started on a project of my own, and I decided to clone, build, and run BenchmarkDotNet.Samples.

I get a similar error in the output log for this as I get for the project of my own.

I think the relevant error is this one:

```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'b7741934-05a7-4539-a38e-d696668ef08d.dll'. An attempt was made to load a program with an incorrect format.
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!
```

The whole log is here:
[Algo_BitCount.log.txt](https://github.com/dotnet/BenchmarkDotNet/files/1252569/Algo_BitCount.log.txt)

**Comment by adamsitnik** [comment]
hi @dls314 

Thanks for a well described bug report!

I have spotted the problem. You are running the latest SDK which by default targets **32 bit RyuJit** for .NET Core. It's very new thing, we supported only the 64 bit RyuJit so far.

I will download it and see what I can do.

**Comment by adamsitnik** [comment]
Ok, I am able to reproduce.

Steps to reproduce:

1. [Install](https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x86.exe) x86 .NET Core Sdk
2. [Install](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x86.exe) x86 dotnet cli
2. Change the `Path` variable, make x86 one the default dotnet

![image](https://user-images.githubusercontent.com/6011991/29740713-f1483d36-8a5c-11e7-8ce8-d1d5219f11fa.png)

**Comment by adamsitnik** [comment]
@dls314 Before I get more into the details and have the fix ready you can install x64 SDK and make it the defualt one (move it up in the Path variable)

**Comment by dls314** [comment]
Thanks! I'll do that, I don't need to be using the x86 sdk

**Comment by adamsitnik** [comment]
@dls314 I have added the support for x86 RyuJit. As soon as [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.9.286) build finishes you can download package with the fix from our CI feed:

```xml
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```
