### ISSUE TITLE
No way to set RuntimeFrameworkVersion in multiple-version config

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/BenchmarkDotNet#535]
I'm interested in comparing disassembly from specific preview drops of .NET Core against each other and .NET Core 2.0, so I tried using a config like this:

```c#
    public class MyConfig : ManualConfig
    {
        public MyConfig()
        {
            // RyuJit for .NET Core 2.0
            Add(Job.ShortRun.With(Jit.RyuJit).With(Platform.X64).With(Runtime.Core).With(CsProjCoreToolchain.NetCoreApp20));
            // RyuJit for .NET Core 2.1
            Add(Job.ShortRun.With(Jit.RyuJit).With(Platform.X64).With(Runtime.Core).With(CsProjCoreToolchain.From(new NetCoreAppSettings("netcoreapp2.1", "2.1.0-preview2-25628-01", ".NET Core 2.1"))));

            Add(DisassemblyDiagnoser.Create(new DisassemblyDiagnoserConfig(printAsm: true, recursiveDepth: 2)));
        }
    }
```

Then when running the benchmark, I see this:

```
  [Host]     : .NET Core 2.0.0 (Framework 4.6.00001.0), 64bit RyuJIT
  Job-XQOYPV : .NET Core 2.0.0 (Framework 4.6.00001.0), 64bit RyuJIT
  Job-XHPTDD : .NET Core 2.1.0-preview2-25616-02 (Framework 4.6.00001.0), 64bit RyuJIT
```

`Job-XHPTDD` ran on a different preview build of NET Core 2.1 than what I requested (I have both installed).

It seems the `MicrosoftNETCoreAppVersion` set on the `NetCoreAppSettings` object isn't actually used in the .NET Core csproj toolchain; what I'd need is a `<RuntimeFrameworkVersion>2.1.0-preview2-25628-01</RuntimeFrameworkVersion>` element inserted in the generated csproj, but I can't seem to find an extensibility point that would make it easy for me to add one.

That element does get copied over from the found csproj to the generated csproj in [`GetSettingsThatNeedsToBeCopied`](https://github.com/dotnet/BenchmarkDotNet/blob/3c1f099aa6c1d90bb063309cea04a173266ac8b8/src/BenchmarkDotNet.Core/Toolchains/CsProj/CsProjGenerator.cs#L78-L81), and if I put it in my csproj and target the csproj against 2.1, then the 2.1 run does indeed work with the desired version, but I can't do the cross-version comparison runs.

It would be great to have an easy way to target specific versions.  (Or, if I'm just overlooking one, then it would be great to have a more easily discoverable way :)  )

**Comment by adamsitnik** [comment]
Hi @JosephTremoulet 

I have just pushed the fix. The two fields of `NetCoreAppSettings` that were previously used to generate `project.json`  got now removed. I just forgot to remove them after `project.json` abandon.

I have added new property, called `RuntimeFrameworkVersion` which generates the right thing.

You should be able to try it in 30 minutes when [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.9.288) build finishes.

Please let me know if it works now.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, thanks for the quick fix. Could you also update the docs and describe the new property? It can be useful for other people who try to work with different .NET Core versions.

**Comment by JosephTremoulet** [comment]
@adamsitnik, yes, it works just like I'd hoped, thanks!

**Comment by adamsitnik** [comment]
@AndreyAkinshin I added the docs for toolchains, [link](https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/guide/Configs/Toolchains.md)

**Comment by AndreyAkinshin** [comment]
@adamsitnik, awesome, thanks!
I guess it makes sense to release `v0.10.10` on the next week.

**Comment by adamsitnik** [comment]
> I guess it makes sense to release v0.10.10 on the next week.

Good idea!
