### ISSUE TITLE
Duplicate using causing benchmark not to work

### ISSUE THREAD

**Issue by CheloXL** [dotnet/BenchmarkDotNet#538]
I know this is an edge case, but...
I have a solution wide Directory.build.props in the root folder where all the solution projects are stored. One specific setting that the props file is changing is the `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`.
Now, if I try to run my benchmarks, they fail as there are duplicate usings in the autogenerated .cs files. Those duplications are usually shown as warning but because of my settings, they are now errors and everything else fails.
So, my solution is to change that setting, run the benchmark and have to remember to switch it back again...

Example code from one autogenerated file:
```c#
#define RETURNS_CONSUMABLE
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Reflection;
using System.Runtime.CompilerServices;
using BenchmarkDotNet;
using BenchmarkDotNet.Characteristics;
using BenchmarkDotNet.Environments;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Extensions;
using BenchmarkDotNet.Helpers;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Engines;
using Benchmark.Dotnet;
using Benchmark.Dotnet;



namespace BenchmarkDotNet.Autogenerated
{
    public class Program
    {
        
        public static int Main(string[] args)
        {
            // this method MUST NOT have any dependencies to BenchmarkDotNet and any other external dlls!
            // otherwise if LINQPad's shadow copy is enabled, we will not register for AssemblyLoading event
            // before .NET Framework tries to load it for this method
            HelpAssemblyResolving();
            return AfterAssemblyLoadingAttached(args);
        }
```

**Comment by adamsitnik** [comment]
Fixed, you owe me a beer ;)

**Comment by CheloXL** [comment]
I would gladly invite you more than one, if you come near where I live.. In the meanwhile, 🍺

**Comment by lukasz-pyrzyk** [comment]
It looks like [beerware license](https://pl.wikipedia.org/wiki/Beerware) :beers:
