### ISSUE TITLE
Run Disassembly Diagnoser without extra run

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#543]
- [ ] Implement reliable diagnoser synchronization
- [ ] Attach Dissasembly Diagnoser after we are done benchmarking

**Comment by adamsitnik** [comment]
I implemented the synchronization in very simple way.

Initially I was thinking about using some fancy stuff like Mutex. But Mutex throws `NotSupportedException` for .NET Core on MacOS and Linux. So it was not an option.

Then I realized that I can just write to std out and read std in in blocking way. It just works. So one process is writing signal and waiting for response by reading in blocking way from console.

This allowed to attach DissasemblyDiagnoser after benchmarks are done, without spawning new process. It also allows to get disassembly for `Job.Dry` (#542)

**Comment by AndreyAkinshin** [comment]
I like how it looks now!

**Comment by nietras** [comment]
@adamsitnik I have this issue in a benchmark I am doing (where I need IterationSetup and hence dry run), when will this be released?

**Comment by adamsitnik** [comment]
It's going to be part of the official `0.10.12` release, but we don't have any release date yet.

But it's available now on our CI feed:

```xml
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

The latest package contains also parallel build, so overall performance should be improved.

**Comment by nietras** [comment]
@adamsitnik thanks that worked, however I am having issues with the disassembler. I've opened a separate issue for that https://github.com/dotnet/BenchmarkDotNet/issues/543
