### ISSUE TITLE
Synthesizing labels for jump targets

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#546]
From private conversation with @JosephTremoulet

> synthesizing labels for jump targets, emitting them in the instr stream and annotating which one each jump references; it makes the structure of the method apparent in a way that the flat list obscures, it’s always the first transform I do by hand when looking at disasm that hasn’t done it automatically

This should be easy ;)

**Comment by adamsitnik** [comment]
I implemented new exporter, which prints a pretty output.

Sample input:

```cs
public static bool LoopGoto_(String strA, String strB)
{
    int length = strA.Length;

    fixed (char* ap = strA) fixed (char* bp = strB)
    {
        char* a = ap;
        char* b = bp;

        while (length != 0)
        {
            int charA = *a;
            int charB = *b;

            if (charA != charB)
                goto ReturnFalse;

            a++;
            b++;
            length--;
        }

        return true;

        ReturnFalse:
        return false;
    }
}
```

Before (raw output exporter kept to show the source asm code in case my implementation breaks something):

![image](https://user-images.githubusercontent.com/6011991/33692900-fd43a22c-daef-11e7-8cbb-9455d8e4c04f.png)

After:

![image](https://user-images.githubusercontent.com/6011991/33692902-03910674-daf0-11e7-8af4-5087b6392b20.png)

@JosephTremoulet would you like to give it a try and provide some feedback? The package should be available after [0.10.11.362](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.11.362) build finishes.

**Comment by JosephTremoulet** [comment]
Big improvement, thanks!

A couple stray thoughts:

1. It would be cool if there were some easier way to find references to a given label other than scanning the listing for them visually.  I don't really have ideas for how to do that, though.  I've seen dumps that include reference counts next to labels, but not convinced that would be an improvement.  An explicit predecessor list might be nice, but to make that clear you'd probably want the labels to identify basic blocks, which would mean inject labels after conditional branches so blocks are single-exit, which in turn would mean you'd have zero-ref labels that are confusing without the ref counts...
    I guess you could do something like label the branches, e.g.

    ```
        jne    M01_L04   ; jcc#3
    ...
    M01_L04  ; refs: jcc#3, jcc#7
    ```
    (the idea being that the jcc#s would be sorted by where the branch is, making them easier to find)
    but I'm probably over-thinking this...


2.  You've suppressed the encoded bytes as well as the addresses.  That's probably for the best, though it's not uncommon to make changes whose primary benefit is to use shorter encodings for things.  So it would maybe (?) be nice to bring back some indication of the size of each instruction, perhaps in a trailing comment, but I'd guess that would probably just clutter things more than would be worth it...

**Comment by redknightlois** [comment]
Agree on 2. At least being able to turn them on somehow.

**Comment by adamsitnik** [comment]
@JosephTremoulet @redknightlois thanks for feedback!

speaking of 2. Would a tooltip with raw value would be enough? So anytime user mouse over the pretty text, the tool tip appears?

![image](https://user-images.githubusercontent.com/6011991/33726352-10d6e062-db75-11e7-94c3-d70cfffd116b.png)

I have no good idea for the search, except of pressing `Ctrl+F` in browser and going with `F3` to next occurence

**Comment by ilabutin** [comment]
> I have no good idea for the search, except of pressing Ctrl+F in browser and going with F3 to next occurence
You produce HTML, so what about including a small bit of JS into it which will handle mouse hovering the label and highlighting all places where it is used?
I can offer some help if needed.

**Comment by adamsitnik** [comment]
@ilabutin thanks for a good hint!

What I implemented:

1. When user hovers over a label, the mouse cursor changes to pointer and label get's highlighted
2. When user clicks a label, all usages gets highlighted
3. When user presses F3, we jump to next usage of given label

Small demo:

![labelssample](https://user-images.githubusercontent.com/6011991/33799205-7074cf6c-dd27-11e7-827c-c2f58ef69a79.gif)
