### ISSUE TITLE
List of structs and OutOfMemoryException

### ISSUE THREAD

**Issue by FSou1** [dotnet/BenchmarkDotNet#551]
I've tried to measure difference between lists with default and predefined capacity with next benchmark declaration:

```
public class GrowingListVsGrowedList
    {
        private List<Point> growingList;
        private List<Point> growedList;
        private int ElementsCount = 1000 * 1000;

        [IterationSetup]
        public void IterationSetup()
        {
            growingList = new List<Point>();
            growedList = new List<Point>(ElementsCount);
        }

        [IterationCleanup]
        public void IterationCleanup()
        {
            growingList.Clear();
            growedList.Clear();
        }

        [Benchmark]
        public void PopulateGrowingList()
        {
            for (var i = 0; i < ElementsCount; i++)
            {
                growingList.Add(new Point()
                {
                    X = i,
                    Y = i,
                    Color = Color.Blue
                });
            }
        }

        [Benchmark]
        public void PopulateGrowedList()
        {
            for (var i = 0; i < ElementsCount; i++)
            {
                growedList.Add(new Point()
                {
                    X = i,
                    Y = i,
                    Color = Color.Blue
                });
            }
        }
    }
```

`Point` is declared as struct:

```
    public struct Point
    {
        public int X { get; set; }
        public int Y { get; set; }
        public Color Color { get; set; }
    }
```
Could you please clarify what is the root cause of next behavior:

> // Benchmark Process Environment Information:
> // Runtime=.NET Framework 4.7 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.2102.0
> // GC=Concurrent Workstation
> // Job: Job-DDZFVF(LaunchCount=1, TargetCount=1, WarmupCount=1)
> 
> Pilot  1: 16 op, 166181809.22 ns, 10.3864 ms/op
> Pilot  2: 32 op, 355943855.49 ns, 11.1232 ms/op
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.Collections.Generic.List`1.set_Capacity(Int32 value)
>    at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
>    at System.Collections.Generic.List`1.Add(T item)
>    at ListBenchmarks.GrowingListVsGrowedList.PopulateGrowedList() in c:\users\maxim_zhukov\documents\visual studio 2017\Projects\ListBenchmarks\ListBenchmarks\Program.cs:line 73
>    at BenchmarkDotNet.Autogenerated.Runnable.MainMultiAction(Int64 invokeCount)
>    at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
>    at BenchmarkDotNet.Engines.EngineStage.RunIteration(IterationMode mode, Int32 index, Int64 invokeCount, Int32 unrollFactor)
>    at BenchmarkDotNet.Engines.EnginePilotStage.RunAuto()
>    at BenchmarkDotNet.Engines.EnginePilotStage.Run()
>    at BenchmarkDotNet.Engines.Engine.Run()
>    at BenchmarkDotNet.Autogenerated.Runnable.Run(IHost host)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at BenchmarkDotNet.Autogenerated.Program.AfterAssemblyLoadingAttached(String[] args)
> ExitCode != 0
> No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

The usage of `[SimpleJob(launchCount: 1, warmupCount: 1, targetCount: 1)]` didn't affect at all.

**Comment by AndreyAkinshin** [comment]
@FSou1, by default your benchmark shouldn't have any side effects because BenchmarkDotNet does a lot of iterations of the target methods. An iteration can include several invocations of the target method. If you don't specify the exact number, BenchmarkDotNet tries to choose the best number on the pilot stage.
The first iteration is 16 invocation which took 166181809ns. If you use the default config, it's too small value. Next iteration contains 32 invocations which took 355943855ns, it's also very small. The next iteration should contain 64 invocations, but we don't have enough memory for it. You can find more information in the documentation:
* http://benchmarkdotnet.org/Configs/Configs.htm
* http://benchmarkdotnet.org/Configs/Jobs.htm
* http://benchmarkdotnet.org/Internals/HowItWorks.htm

**Comment by FSou1** [comment]
@AndreyAkinshin this makes sense, but i haven't still figured out what should be the correct configuration/benchmark for the current example?
