### ISSUE TITLE
Change filename of generated reports to allow for generic types

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/BenchmarkDotNet#554]
## Steps to reproduce:
1. Create benchmark with abstract generic base class
2. Create benchmark types at runtime via ``MakeGenericType()`` (e.g. ``BaseClass<ClassA>``)
3. Run benchmark
## Expected result:
Filenames of the individual benchmarks are different
## Current result:
All filenames start with e.g. ``BaseClass`1`` and overwrite themselves.

Reason:
Currently Type.FullName is used for naming the files, they don't look nice for generic base classes.

As suggested by @adamsitnik on gitter it is possible to change the filenames to use Type.GetCorrectTypeName().
Additionally it's necessary to remove all invalid characters (e.g. <> from) the output.
I currently replace them with '.' Any Suggestions for a better invalid char replacement?
I don't think it's possible to create invalid file names out of correct type names otherwise.

I will provide a pull request as soon as I get it working.

This issue partially overlaps with https://github.com/dotnet/BenchmarkDotNet/issues/529 and the associated pull request to fix it.

**Comment by Tornhoof** [comment]
Ok, short update from my side. '.' is a bad idea for a separator and atleast for my classes I run into path and file length problems.
Additionally the Title calculation needs to be adapted to also use GetCorrectTypeName().
I'll still provide the pull request for it, if you want it, otherwise it's way easier to simply create individual types for my generic types and apparently the problem does not occure often enough, as nobody has yet asked for it.
I think it's too much churn for a rare problem.

**Comment by Tornhoof** [comment]
I'll close this.

**Comment by adamsitnik** [comment]
@Tornhoof thanks for trying! I had no idea that `MakeGenericType` could work ;p
