### ISSUE TITLE
Test "CanDisassembleAllMethodCalls" fails on Ubuntu 

### ISSUE THREAD

**Issue by Ky7m** [dotnet/BenchmarkDotNet#555]
Test `CanDisassembleAllMethodCalls` with (jit: RyuJit, platform: X64, runtime: Core) parameters fails on Ubuntu
```
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```
with following stacktrace:
```
System.InvalidOperationException : Sequence contains no elements
Stack Trace:
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
at BenchmarkDotNet.IntegrationTests.DisassemblyDiagnoserTests.<CanDisassembleAllMethodCalls>g__AssertDisassembled3_0(IDisassemblyDiagnoser diagnoser, String calledMethodName)
at BenchmarkDotNet.IntegrationTests.DisassemblyDiagnoserTests.CanDisassembleAllMethodCalls(Jit jit, Platform platform, Runtime runtime)
```
More details:
https://travis-ci.org/Ky7m/BenchmarkDotNet/jobs/279612017#L5287

Issue is connected to [this code](https://github.com/dotnet/BenchmarkDotNet/blob/master/tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs#L79):
```csharp
Assert.True(diagnoser.Results.Single().Value
.Methods.Any(method => method.Name.Contains(calledMethodName) && method.Maps.Any(map => map.Instructions.Any())),
$"{calledMethodName} is missing");
```
but I am not sure about root of the problem. Is it possible to have empty Results collection?

**Comment by adamsitnik** [comment]
hello @Ky7m 

it fails because the disassembler does not support non-Windows OS. So the fix would be to make the test run only on Windows
