### ISSUE TITLE
DisassemblyDiagnoser crashes on overloaded benchmark

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/BenchmarkDotNet#562]
Trying to use the DisassemblyDiagnoser on the benchmark referenced [here](https://github.com/dotnet/coreclr/issues/9692#issue-209058529), I'm getting 

```
Failed to disassemble with following exception:
Sequence contains more than one matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at BenchmarkDotNet.Disassembler.Program.Disassemble(Settings settings, ClrRuntime runtime, State state)
   at BenchmarkDotNet.Disassembler.Program.Handle(Settings settings)
   at BenchmarkDotNet.Disassembler.Program.Main(String[] args)
```

Presumably that's coming from this code: https://github.com/dotnet/BenchmarkDotNet/blob/a7578addd708367adbdecffff460420aa51192eb/src/BenchmarkDotNet.Disassembler.x64/Program.cs#L98-L99

so maybe, while only one overload can be the [Benchmark] we're looking for, the presence of other, non-[Benchmark] overloads cause a problem, and the test needs to also verify that it's getting a parameterless method?  The benchmark in question includes this:

```c#
        [Benchmark]
        public bool LoopReturn()
        {
            return LoopReturn(test1, test2);
        }

        public bool LoopReturn(String strA, String strB)
        {
```

and renaming one of the methods allows disassembly to succeed.

**Comment by adamsitnik** [comment]
@JosephTremoulet thanks for another good bug report!

You are one step away from writing your first PR to BenchmarkDotNet ;)
