### ISSUE TITLE
[Do you need any of these?] Backport some features to BDN

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#570]
During my work on perftests project I have to add some stuff that look like a good candidate to be added to BDN (at least for me:) )

If you're interested in any of these, will do a PR. Here they are:

1. [`IFlushableLogger`, synchronized lazy logger](https://github.com/rsdn/CodeJam/tree/master/PerfTests/src/%5BL0_PortToBenchmerkDotNet%5D/Loggers). Interface enables log flushing on benchmark completion, lazy logger allows to defer file opening until first write.
2. [AttributeValue{T}](https://github.com/rsdn/CodeJam/blob/master/PerfTests/src/%5BL0_PortToBenchmerkDotNet%5D/Helpers/AttributeValue.cs). A lazy wrapper for XxxSource attributes (`IConfigSource`  etc). Allows to defer heavy logic (such as [Activator.CreateInstance call](https://github.com/dotnet/BenchmarkDotNet/blob/0231157fb11d054fcb99474fbba999be22aa7fc2/src/BenchmarkDotNet.Core/Attributes/ConfigAttribute.cs#L12-L14)) until it is really needed. For example, type.GetAttributes() does not trigger config creation. [Example of usage](https://github.com/rsdn/CodeJam/blob/34d67d51238eceea7cc512e06d6e638321b89378/PerfTests/src/%5BL4_Configuration%5D/%5BAttributes%5D/CompetitionModifierAttribute.cs).

3. [Benchmark-related extensions](https://github.com/rsdn/CodeJam/blob/master/PerfTests/src/%5BL0_PortToBenchmerkDotNet%5D/Helpers/BenchmarkHelpers.cs#L33-L103). Save a lot of time for custom analysers.

4. Wrappers over QueryXxxCycleTime: [ProcessCycleTimeClock and ThreadCycleTimeClock](https://github.com/rsdn/CodeJam/tree/master/PerfTests/src/%5BL0_PortToBenchmerkDotNet%5D/Horology). Windows-only, **very imprecise** for anything except CPU-bound code. To be honest, I'm not sure if they can be used for anything except "here's why you should not use `QueryXxxCycleTime`()" benchmarks.

**Comment by AndreyAkinshin** [comment]
Hey, @ig-sinicyn, sorry for the late reply, I was very busy lately (as usual =) ). I'm going to review these APIs soon.

**Comment by adamsitnik** [comment]
No progress since 2017, I think that it's OK to close this issue.
