### ISSUE TITLE
Unable to run. Dependency failing in BenchmarkDotNet v0.10.10

### ISSUE THREAD

**Issue by ENikS** [dotnet/BenchmarkDotNet#578]
I am evaluating BenchmarkDotNet for company's CI integration. I am behind pretty strict firewall and can't install packages from NuGet directly. So I am doing it by hand. After downloading all packages recommended [here](http://benchmarkdotnet.org/Guides/NuGet.htm) I am getting this error:
>An unhandled exception of type 'System.IO.FileNotFoundException' occurred in BenchmarkDotNet.Core.dll

>Additional information: Could not load file or assembly 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

#### Question One: 
Why depend on external package for ``Tuple`` when these are available in standard library?

#### Question Two: 
Why the package depends on [unlisted](https://www.nuget.org/packages/System.ValueTuple) and quite outdated NuGet package which is impossible to download?

**Comment by ENikS** [comment]
This too:

>// Result = Failure
// Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral,
ublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at BenchmarkDotNet.Code.CodeGenerator.GetDeclarationsProvider(Target target)
   at BenchmarkDotNet.Code.CodeGenerator.Generate(Benchmark benchmark)
   at BenchmarkDotNet.Toolchains.GeneratorBase.GenerateCode(Benchmark benchmark, ArtifactsPaths artifactsPaths)
   at BenchmarkDotNet.Toolchains.GeneratorBase.GenerateProject(Benchmark benchmark, ILogger logger, String rootArtifactsFolderPath, IConfig config, I
esolver resolver)

The version is not listed in NuGet either.

**Comment by adamsitnik** [comment]
> Why depend on external package for Tuple when these are available in standard library?

as far as I know `ValueTuple` is not part of the .NET 4.6 framework which we support. It's part of newer .NET

> Why the package depends on unlisted and quite outdated NuGet package which is impossible to download?

If it was impossible we would have tons of bug reports about it. So far it worked for everybody else. You are doing this manually and most probably this is the reason why it does not work. IDE would try to download it, if failed download newer version and emit the correct assembly binding.

I recommend you to install BDN somewhere outside your VPN and just copy-paste everything. It should save you some time and trouble.

**Comment by ENikS** [comment]
> If it was impossible we would have tons of bug reports about it.

You've got your first one. Considering that you have your download count still in low thousands I would assume more is coming when fire-walled corporations will try to adopt it.

Could you create self-contained package which includes all required assemblies?

**Comment by ENikS** [comment]
Well, I guess not.

**Comment by adamsitnik** [comment]
To me as a maintainer, it's not a common use case. We have a lot of other, very common problems, which consume 100% of our OSS time.

I can create an issue, make it as up-for-grabs and test the solution if somebody sends a PR.

I am sorry but this is all I can do for you.

**Comment by ENikS** [comment]
Thank you. I would try to solve this by creating project outside of firewall but it would be nice if this is addressed one day.
