### ISSUE TITLE
Should benchmarks run if a dependency is a debug release

### ISSUE THREAD

**Issue by KevM** [dotnet/BenchmarkDotNet#579]
I was spiking setting up a bench mark and could not get any results. The benchmark validator complains that one of my libraries is a debug build. This was great to figure out and I will fix it, but for now I don't have control over this. Is there any way to skip this validation step?

I tried creating a config where validations do not fail on error `ExecutionValidator.DontFailOnError` but had the same problem.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, I think we should describe a proper way to run assemblies without optimizations in our docs. What do you think?

P.S. The original issue where we have decided to turn off the possibility to benchmark debug assemblies: https://github.com/dotnet/BenchmarkDotNet/issues/561

**Comment by adamsitnik** [comment]
Hello @KevM 

Thanks for reporting your problem. I have just changed the error message and added the solution to our FAQ. Which is following:

* **Q** I have failed to run my benchmarks, I am getting following errors about non-optimized dll. What can I do?  

```
Assembly BenchmarkDotNet.Samples which defines benchmarks references non-optimized BenchmarkDotNet
        If you own this dependency, please, build it in RELEASE.
        If you don't, you can create custom config with DontFailOnError to disable our custom policy and allow this b
Assembly BenchmarkDotNet.Samples which defines benchmarks is non-optimized
Benchmark was built without optimization enabled (most probably a DEBUG configuration). Please, build it in RELEASE.
```

**A** You should always run your benchmarks in RELEASE mode with optimizations enabled (default setting for RELEASE). However if you have to use non-optimized 3rd party assembly you have to create custom config to disable our default policy.

```cs
public class AllowNonOptimized : ManualConfig
{
    public AllowNonOptimized()
    {
        Add(JitOptimizationsValidator.DontFailOnError); // ALLOW NON-OPTIMIZED DLLS

        Add(DefaultConfig.Instance.GetLoggers().ToArray()); // manual config has no loggers by default
        Add(DefaultConfig.Instance.GetExporters().ToArray()); // manual config has no exporters by default
        Add(DefaultConfig.Instance.GetColumnProviders().ToArray()); // manual config has no columns by default
    }
}

[Config(typeof(AllowNonOptimized)]
public class Benchmarks { }

or:

BenchmarkRunner.Run(assembly, new AllowNonOptimized());
```

**Comment by KevM** [comment]
Yay. Thank you.

**Comment by MaximKitsenko** [comment]
I still get this error. I use release build. What i'm doing wrong? 
My config:
```
[MarkdownExporter, AsciiDocExporter, HtmlExporter, CsvExporter, RPlotExporter]
	[Config(typeof(Config))]
	[MedianColumn]
	public partial class MyBench
	{
		public class Config : ManualConfig
		{
			public Config()
			{
				Add(CsvMeasurementsExporter.Default);
				Add(RPlotExporter.Default);
				Add(JitOptimizationsValidator.DontFailOnError); // ALLOW NON-OPTIMIZED DLLS`

```
Error message:
`// Validating benchmarks:
Assembly PerfTest which defines benchmarks references non-optimized GenFu
        If you own this dependency, please, build it in RELEASE.
        If you don't, you can create custom config with DontFailOnError to disable our custom policy and allow this benchmark to run.`

**Comment by babin93** [comment]
The documentation could be updated since I encountered the same issue.
