### ISSUE TITLE
Print amount of logical and physical core

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#582]
Right now (v0.10.10) we only print the amount of logical cores (via `Environment.ProcessorCount`). It would be nice to also print the amount of physical cores and amount of physical processors. Since there are no managed API for it, we need 3 different implementations (for Windows, Linux, and macOS).

**Comment by AndreyAkinshin** [comment]
We can use this for Windows: https://stackoverflow.com/a/2670568/184842

**Comment by morgan-kn** [comment]
@AndreyAkinshin could you please assign me on this issue?

**Comment by AndreyAkinshin** [comment]
@morgan-kn, I added you to the collaborators list. Please, accept the invitation, then I will be able to assign you.

**Comment by AndreyAkinshin** [comment]
The feature is implemented (PR #607)
