### ISSUE TITLE
BenchmarkDotNet.Samples refactoring

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#583]
In the early versions of BenchmarkDotNet, the Samples project had two purposes:
1. It was our set of manual integration tests (we didn't have real integration tests)
2. It contained a lot of "cool" benchmarks.

Right now we have good integration tests and the community have a lot of new awesome BenchmarkDotNet-based benchmarks. The most precious piece of BenchmarkDotNet.Samples is the Intro folder. My suggestion:

1. All Intro samples which can be useful for users as a demonstration of our API (like `IntroParamsSource` or `IntroRankColumn`) should be well-documented and should be a part of the official documentation. Right now we are copying parts of these samples into documentation manually; we should do it automatically.
2. If we still have some interesting samples which should be executed manually (they can be useful for diagnostics), but we don't want to move it into IntegrationTests projects (because they take too much time), we should move it into a separate project (like `ManualIntegrationTests`). An example: `IntroEmpty`.
3. All other samples which are not useful for users or BenchmarkDotNet developers (like `Framework_SelectVsConvertAll` or `IL_Loops`) should be removed from the source code. These samples were useful in the past, but they are not useful now.

**Comment by ENikS** [comment]
I would suggest making [this project](https://github.com/benchmarks/csharp) a showcase for the library as well as good reference source for the C-Sharp implementation.
