### ISSUE TITLE
IParam interface improvement

### ISSUE THREAD

**Issue by ENikS** [dotnet/BenchmarkDotNet#586]
Currently **ToSourceCode** returns string: 
```C#
public string ToSourceCode();
```
It would be nice if there was a way to specify same thing using lambda expressions:
```C#
public Expression ToSourceCode();
```
So it would be possible to use something like this in implementation:
```C#
public Expression ToSourceCode() => new SomeType(....);
```
You could also compile these expressions much easier...

**Comment by adamsitnik** [comment]
@ENikS I have fixed this issue in #754, you no longer need to implement `IParam`, you can use complex types for `ParamsSource` and `ArgumentsSource` and we are going to generate the right code for you.
