### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/BenchmarkDotNet#600]
```cs
public class UnitVectorBenchmarks
{
    [Benchmark(Baseline = true)]
    public double CreateUnitVectorReturnX()
    {
        return new UnitVector(1, 2).X;
    }

    [Benchmark]
    public double CreateCheckedUnitVectorReturnX()
    {
        return new CheckedUnitVector(1, 2).X;
    }

    [Benchmark]
    public double CreateCheckedUnitVectorNullableReturnX()
    {
        return new CheckedUnitVectorNullable(1, 2).X;
    }

    [Benchmark]
    public double Return1()
    {
        return 1;
    }

    public struct UnitVector
    {
        public readonly double X;
        public readonly double Y;

        public UnitVector(double x, double y)
        {
            X = x;
            Y = y;
        }
    }

    public struct CheckedUnitVector
    {
        private readonly double  x;
        private readonly double  y;

        public CheckedUnitVector(double x, double y)
        {
            this.x = x;
            this.y = y;
        }

        public double X
        {
            get
            {
                ThrowIfZero();
                return this.x;
            }
        }

        public double Y
        {
            get
            {
                ThrowIfZero();
                return this.y;
            }
        }

        private void ThrowIfZero()
        {
            if (this.x == 0 && this.y == 0)
            {
                throw new InvalidOperationException("Unitvector has zero length.");
            }
        }
    }

    public struct CheckedUnitVectorNullable
    {
        private readonly double? x;
        private readonly double? y;

        public CheckedUnitVectorNullable(double x, double y)
        {
            this.x = x;
            this.y = y;
        }

        public double X => this.x.Value;

        public double Y => this.y.Value;
    }
}
```

Results in:

```
|                                 Method |       Mean |     Error |    StdDev | Scaled | ScaledSD | Allocated |
|--------------------------------------- |-----------:|----------:|----------:|-------:|---------:|----------:|
|                CreateUnitVectorReturnX |  0.0088 ns | 0.0128 ns | 0.0236 ns |      ? |        ? |       0 B |
|         CreateCheckedUnitVectorReturnX |  2.7895 ns | 0.1140 ns | 0.3343 ns |      ? |        ? |       0 B |
| CreateCheckedUnitVectorNullableReturnX | 14.7826 ns | 0.4761 ns | 0.3717 ns |      ? |        ? |       0 B |
|                                Return1 |  0.1331 ns | 0.0262 ns | 0.0644 ns |      ? |        ? |       0 B |
```

**Comment by AndreyAkinshin** [comment]
We print `?` in the Scaled column when the baseline value is too close to zero, and it's impossible to calculate the scaled value properly. I agree that it's not obvious, so we should add info about it in the legend (one additional line which is shown only when we have `?` marks in the Scaled column).

**Comment by AndrewGumenyuk** [comment]
@AndreyAkinshin . I've just read this issue. I'm trying to investigate. Unfortunately, I don't understand why you wanna to hide values that are too close to zero.

**Comment by encrypt0r** [comment]
Hi, I want to work on this. But I have a few questions:

1. Is this issue still relevant? Since it seems like `BaselineScaledColumn` is obsoleted. If yes, should I do that for `BaselineRatioColumn`?

2. Seems like both `BaselineRatioColumn` and  `BaselineScaledColumn` already provide a legend, what's the recommended way of having two entries in the legend?

cc @adamsitnik

**Comment by adamsitnik** [comment]
Hello @encrypt0r !

Thanks for looking at this!

1. If possible please fix both.
2. I think that the best fix would be to extend the existing legend with one sentence shortly describing what `?` means.

**Comment by encrypt0r** [comment]
@adamsitnik I don't think `Legend` can handle conditional logic in a clean way, because it doesn't have access to `Summary`. The only way I can think of is to have some kind of flag that's set by `GetValue`. But I don't like it for 2 reasons: 
1.  `GetValue` will have side effects even though it returns a value.
2. Creates a hidden dependency between `GetValue` and `Legend` where`GetValue` must always be called before getting the value of `Legend`.

What do you think about doing it in an analyser and showing it as a warning (or hint) instead? I have already written the code for the analyzer and it seems to be working.

What are your thoughts?

P.S: I am really struggling with what a good message should be 😅, Any ideas?

**Comment by adamsitnik** [comment]
> What do you think about doing it in an analyser and showing it as a warning (or hint) instead? I have already written the code for the analyzer and it seems to be working.

You mean a `Validator` ? Sounds good to me.

@AndreyAkinshin do you have better idea? I think that `?` is rare enough that a validator should be ok (and keep the legend simple by default).

**Comment by encrypt0r** [comment]
@adamsitnik according to [here](https://benchmarkdotnet.org/articles/configs/validators.html), 
> A validator can validate your benchmarks before they are executed and produce validation errors

But I have understood it correctly, you don't actually know if the result will be invalid until **after** the benchmarks are complete.

On the other hand, [Analyzers ](https://benchmarkdotnet.org/articles/configs/analysers.html)seem to be more fit for the problem:
> An analyser can analyse summary of your benchmarks and produce some useful warnings.

**Comment by adamsitnik** [comment]
@encrypt0r you are 100% right, please excuse me for misleading you

**Comment by encrypt0r** [comment]
@adamsitnik it's totally ok, cool... I will submit a PR then
