### ISSUE TITLE
Release Setup Info ?

### ISSUE THREAD

**Issue by jayonsoftware** [dotnet/BenchmarkDotNet#604]
Here is my setting looks 

![image](https://user-images.githubusercontent.com/1304943/33779867-a069aa50-dc1c-11e7-9027-4e254f99f54d.png)

But I do still get the follwing error

![image](https://user-images.githubusercontent.com/1304943/33779901-bdee9694-dc1c-11e7-913b-4e75b6150a39.png)

**Comment by adamsitnik** [comment]
Hi @jayonsoftware 

How are you running the benchmarks from command line? The default configuration for dotnet cli is DEBUG.

So to run in release mode you need to run either: `run -configuration Release` or `run -c Release`

**Comment by jayonsoftware** [comment]
, I have been pressing F5 with our realizing it runs in debug mode...16 years of .net devs and this :-)
