### ISSUE TITLE
Properly escaping generated markdown

### ISSUE THREAD

**Issue by ENikS** [dotnet/BenchmarkDotNet#608]
I have descriptions containing symbols ``<>``. Something like this:
```
[Benchmark(Description = "Benchmarking Container.Resolve<SomeType>()")]
```
When displayed in console the descriptions are correct but generated markdown is invalid. Anything that is included in these brackets is ignored ending up with something like this: ``Container.Resolve()``.

 Could you please add extra step to properly escape markdown?

**Comment by AndreyAkinshin** [comment]
@Chrisgozd do you want to implement it?

**Comment by ENikS** [comment]
@AndreyAkinshin @Chrisgozd 

Any progress on this one? 
I'd like to update benchmarks...

**Comment by AndreyAkinshin** [comment]
@ENikS, we don't typically need html escaping for our most popular markdown dialect like GitHub or StackOverflow. So, I added another dialect which is called `HtmlReady`. Now you can mark your benchmark class with `[MarkdownExporterAttribute.HtmlReady].` In the `result` folder, you should find the `*-report-htmlready.md` file with properly escaped text.

**Comment by ENikS** [comment]
You **DO** need escaping for GitHub dialect. Check [this](https://raw.githubusercontent.com/unitycontainer/benchmarks/master/README.md) page and compare how it looks when [viewed in GitHub](https://github.com/unitycontainer/benchmarks/blob/master/README.md). Can you see the difference?

**Comment by ENikS** [comment]
@AndreyAkinshin ``Container.Resolve<Container>()`` becomes ``Container.Resolve()``

**Comment by ENikS** [comment]
@AndreyAkinshin 
Actually, if you enclose method name in 'quotes' as I did with last two names it would solve the problem

**Comment by AndreyAkinshin** [comment]
Sorry, I checked a wrong example. Probably, I have to sleep more. =)
Now GitHub dialect uses html escaping.
