### ISSUE TITLE
Trying to run a project targeting net471 using the new style prof file/sdk results in eventual crash 

### ISSUE THREAD

**Issue by lambdakris** [dotnet/BenchmarkDotNet#613]
## Description
Trying to run a project targeting net471 using the new style prof file/sdk results in eventual crash and weird environment side effects such as losing access to dotnet.exe and git.exe

## Steps to reproduce
Create a new style sdk proj file via
```
dotnet new console -o Repro
cd repro
code .
```
Change target framework in Repro.csproj to net471
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>

</Project>
```
Install BenchmarkDotNet package
```
dotnet add package BenchmarkDotNet
```
Copy paste Program.cs code from [Getting Started](http://benchmarkdotnet.org/Guides/GettingStarted.htm)
```
using System;
using System.Security.Cryptography;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace MyBenchmarks
{
    public class Md5VsSha256
    {
        private const int N = 10000;
        private readonly byte[] data;

        private readonly SHA256 sha256 = SHA256.Create();
        private readonly MD5 md5 = MD5.Create();

        public Md5VsSha256()
        {
            data = new byte[N];
            new Random(42).NextBytes(data);
        }

        [Benchmark]
        public byte[] Sha256() => sha256.ComputeHash(data);

        [Benchmark]
        public byte[] Md5() => md5.ComputeHash(data);
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<Md5VsSha256>();
        }
    }
}
```
Finally, build and run the Repro project with Release configuration in one of the following ways:
1. run `dotnet build -c Release` then run `bin\Release\net471\Repro.exe`
2. run `dotnet publish -c Release -o temp` then run `temp\Repro.exe`
3. run `dotnet run -c Release`
4. or avoid the command line by browsing to where the desired release version of Repro.exe is and double clicking on it

## Expected outcome
The benchmarks run to completion and the application doesn't crash/terminate unexpectedly

## Actual outcome
1. The application crashes/terminates unexpectedly, and seems to affect the environment in some way
2. Many times, the terminal/console/shell as a whole might crash/disappear 
3. Many times, after the application crashes, you will find that trying to build the project in Release configuration will produce the following error message
```
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for C:\Users\lambdakris\Code\Repro\Repro.csproj...
  Generating MSBuild file C:\Users\lambdakris\Code\Repro\obj\Repro.csproj.nuget.g.props.
C:\Program Files\dotnet\sdk\2.1.3\NuGet.targets(103,5): error : Access to the path is denied. [C:\Users\lambdakris\Code\Repro\Repro.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\2.1.3\NuGet.targets(103,5): error : Access to the path is denied. [C:\Users\lambdakris\Code\Repro\Repro.csproj]
    0 Warning(s)
    1 Error(s)
```
4. Many times, after the application crash, you will find that you have lost access to the dotnet.exe tool from the command line and will need to repair it to use it again (however, you will need to restart to repair because trying to uninstall or repair after the application crash fails because dotnet.exe seems to be locked or something)
5. And you might even lose access to git.exe

## Workarounds
Use an old style project 

## Environment information
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff

## Conclusion
I hope someone else can repro this because the erratic behavior I am describing has me even doubting myself. However, if it is reproducible by others, due to how dotnet.exe and Repro.exe are sometimes locked or inaccessible, it might suggest that something is still executing even after the what appears to be a crash. If others can reproduce this issue, I would then point out that there are two separate things to considered:
1) Whether the scenario of benchmarking net471 projects using the new style proj files should be supported
2) If the answer is no to 1, then at least consideration should be given to putting in some safeguards to prevent this scenario from affecting the environment in such a way as to lose access to dotnet.exe (and possibly git.exe)

## Attachments
* Here is a zip of my repro project
[Repro.zip](https://github.com/dotnet/BenchmarkDotNet/files/1602493/Repro.zip)

**Comment by lambdakris** [comment]
Ok, right after I hit the 'Comment' button, I lightbulb flashed in my head and it looks like this could be the issue. What seems to be happening is that my AV (Bitdefender) is classifying anything involved in the execution of the app as a threat and quarantining it (thus explaining the disappearance of dotnet.exe and Repro.exe, while at the same time not being able to overwrite/replace them). However, it is curious that the exact same project, retargeted to netcoreapp2.0, then run the exact same way(s), does not raise any sort of issues with the AV. Also, having some issues figuring out how to whitelist things in such a way that I don't have to explicitly whitelist each net471 project exe...

**Comment by adamsitnik** [comment]
hello @lambdakris 

Thanks for very well described report.

Unfortunatelly there is very little that we can do. As far as I know you should get a warning from us in the summary that you have some AV running. Did you get something?

It's also strange that AV blocked `dotnet restore` and `dotnet run`. Usually AV blocks only the execution of the benchmarked exe, not the MSBuild ;)

**Comment by lambdakris** [comment]
Yeah, ultimately it is not an issue with BenchmarkDotNet. Regarding the warning about the AV, I did not see the warning with the netcore summary, and of course, there is no summary when targeting netfx because it crashes/gets killed of. Still, I find it curious that this only happens when targeting netfx and not netcore. I'll go ahead and close.

**Comment by adamsitnik** [comment]
> I find it curious that this only happens when targeting netfx and not netcore

For .NET Core a `.dll` is being created, for classic .NET an `.exe`. I suspect that this could be the issue.
