### ISSUE TITLE
Examples of running BenchmarkDotNet from TeamCity

### ISSUE THREAD

**Issue by erick-thompson** [dotnet/BenchmarkDotNet#627]
I have a set of benchmarks I would like to run under TeamCity. I can run the benchmarks easily enough (command line runner, PowerShell runner, etc), but I'd like to have the build fail when the benchmark results vary a great deal. Does anyone have any examples of BenchmarkDotNet + TeamCity?

**Comment by adamsitnik** [comment]
Hello @erick-thompson 

Unfortunatelly we don't have anything like that. It would be great to have it, but we just did not find the time to implement it.

Please follow #54 , I am closing this one (it's a duplicate)

**Comment by AndreyAkinshin** [comment]
@erick-thompson, [performance testings](http://aakinshin.net/blog/post/reflecting-on-performance-testing/) is a complicated feature. I'm working on it right now. Hopefully, it will be available later this year.

**Comment by erick-thompson** [comment]
Thanks for the information. I agree it is a tough problem. Let me know if there are any efforts I can help with.

**Comment by abelbraaksma** [comment]
For posterity, I think the "duplicate" would now be #155.
