### ISSUE TITLE
Question on Architecture 

### ISSUE THREAD

**Issue by ENikS** [dotnet/BenchmarkDotNet#629]
I am trying to create benchmark site with performance comparison of [Unity versions](https://github.com/unitycontainer/benchmarks) against each other as well as other IoC containers. I also would like to compare performance on different platforms and .NET frameworks. Create a matrix so to speak. 
It would be nice if the results could be published to a web site automatically.

I was wondering if you could help me with proper architecture or point me to a sample project?

**Comment by AndreyAkinshin** [comment]
@ENikS, BenchmarkDotNet allows comparing different platforms and runtime. Results can be exported to different formats (xml, json, csv, and so on) or handle programmatically (BenchmarkRunner returns a Summary which contains detailed information about all iterations).
Thus, you can transform results into a matrix as you want. Making a web site and auto-deploy are our of the scope of BenchmarkDotNet. There are too many ways and technologies which can help you. I guess that the easiest way is a script which runs benchmarks on your CI server and push results to [GitHub pages](https://pages.github.com)

**Comment by ENikS** [comment]
Do you know any continuous integration platform which would allow running these tests? These take forever to run...
