### ISSUE TITLE
ParamsSource no longer sorted in results

### ISSUE THREAD

**Issue by nietras** [dotnet/BenchmarkDotNet#632]
As can be seen in the following 0.10.12 no longer seems to sort `Length` by value, `2`, `3` no longer come first in the list.

``` ini

BenchmarkDotNet=v0.10.12, OS=Windows 10 Redstone 2 [1703, Creators Update] (10.0.15063.877)
Intel Core i5-3475S CPU 2.90GHz (Ivy Bridge), 1 CPU, 4 logical cores and 4 physical cores
Frequency=2840374 Hz, Resolution=352.0663 ns, Timer=TSC
.NET Core SDK=2.1.4
  [Host] : .NET Core 2.0.5 (Framework 4.6.26020.03), 64bit RyuJIT

Platform=X64  Runtime=Core  Toolchain=InProcessToolchain  
LaunchCount=1  RunStrategy=Monitoring  TargetCount=11  
UnrollFactor=1  WarmupCount=3  

```
|    Method |               Filler |  Length |      Mean |     Error |    StdDev | Scaled | ScaledSD |
|---------- |--------------------- |-------- |----------:|----------:|----------:|-------:|---------:|
| **ArraySort** |             **Constant** |      **10** |  **16.54 ms** | **0.2181 ms** | **0.1577 ms** |   **1.00** |     **0.00** |
|  SpanSort |             Constant |      10 |  12.63 ms | 0.1283 ms | 0.0928 ms |   0.76 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |             **Constant** |     **100** |  **18.40 ms** | **0.5425 ms** | **0.3923 ms** |   **1.00** |     **0.00** |
|  SpanSort |             Constant |     100 |  20.26 ms | 0.3414 ms | 0.2468 ms |   1.10 |     0.03 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |             **Constant** |   **10000** |  **37.68 ms** | **0.4053 ms** | **0.2931 ms** |   **1.00** |     **0.00** |
|  SpanSort |             Constant |   10000 |  39.42 ms | 0.5671 ms | 0.4101 ms |   1.05 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |             **Constant** | **1000000** |  **53.05 ms** | **0.9799 ms** | **0.7086 ms** |   **1.00** |     **0.00** |
|  SpanSort |             Constant | 1000000 |  49.21 ms | 0.8263 ms | 0.5974 ms |   0.93 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |             **Constant** |       **2** |  **44.09 ms** | **0.4798 ms** | **0.3470 ms** |   **1.00** |     **0.00** |
|  SpanSort |             Constant |       2 |  34.34 ms | 0.4404 ms | 0.3184 ms |   0.78 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |             **Constant** |       **3** |  **33.16 ms** | **0.8517 ms** | **0.6159 ms** |   **1.00** |     **0.00** |
|  SpanSort |             Constant |       3 |  24.30 ms | 0.1930 ms | 0.1395 ms |   0.73 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Decrementing** |      **10** |  **37.37 ms** | **0.4361 ms** | **0.3153 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Decrementing |      10 |  26.45 ms | 0.5276 ms | 0.3815 ms |   0.71 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Decrementing** |     **100** |  **24.97 ms** | **0.4573 ms** | **0.3307 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Decrementing |     100 |  27.35 ms | 0.4018 ms | 0.2905 ms |   1.10 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Decrementing** |   **10000** |  **49.80 ms** | **0.4504 ms** | **0.3257 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Decrementing |   10000 |  47.22 ms | 0.9602 ms | 0.6943 ms |   0.95 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Decrementing** | **1000000** |  **73.08 ms** | **1.5220 ms** | **1.1005 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Decrementing | 1000000 |  61.32 ms | 0.7870 ms | 0.5691 ms |   0.84 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Decrementing** |       **2** |  **44.21 ms** | **0.5556 ms** | **0.4017 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Decrementing |       2 |  34.53 ms | 0.5925 ms | 0.4284 ms |   0.78 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Decrementing** |       **3** |  **34.03 ms** | **0.8673 ms** | **0.6271 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Decrementing |       3 |  24.01 ms | 0.3853 ms | 0.2786 ms |   0.71 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Incrementing** |      **10** |  **16.27 ms** | **0.3809 ms** | **0.2754 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Incrementing |      10 |  12.61 ms | 0.2066 ms | 0.1494 ms |   0.78 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Incrementing** |     **100** |  **16.51 ms** | **0.4467 ms** | **0.3230 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Incrementing |     100 |  19.20 ms | 0.2857 ms | 0.2065 ms |   1.16 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Incrementing** |   **10000** |  **30.49 ms** | **0.6392 ms** | **0.4622 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Incrementing |   10000 |  33.05 ms | 0.4405 ms | 0.3185 ms |   1.08 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Incrementing** | **1000000** |  **39.49 ms** | **0.7695 ms** | **0.5564 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Incrementing | 1000000 |  37.66 ms | 0.5212 ms | 0.3768 ms |   0.95 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Incrementing** |       **2** |  **43.58 ms** | **0.6992 ms** | **0.5056 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Incrementing |       2 |  34.33 ms | 0.7276 ms | 0.5261 ms |   0.79 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |         **Incrementing** |       **3** |  **32.78 ms** | **0.2690 ms** | **0.1945 ms** |   **1.00** |     **0.00** |
|  SpanSort |         Incrementing |       3 |  23.03 ms | 0.4079 ms | 0.2950 ms |   0.70 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |  **MedianOfThreeKiller** |      **10** |  **20.71 ms** | **0.3319 ms** | **0.2400 ms** |   **1.00** |     **0.00** |
|  SpanSort |  MedianOfThreeKiller |      10 |  15.85 ms | 0.4264 ms | 0.3083 ms |   0.77 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |  **MedianOfThreeKiller** |     **100** |  **30.57 ms** | **0.5708 ms** | **0.4127 ms** |   **1.00** |     **0.00** |
|  SpanSort |  MedianOfThreeKiller |     100 |  31.27 ms | 0.5795 ms | 0.4190 ms |   1.02 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |  **MedianOfThreeKiller** |   **10000** |  **97.84 ms** | **1.3203 ms** | **0.9547 ms** |   **1.00** |     **0.00** |
|  SpanSort |  MedianOfThreeKiller |   10000 |  89.54 ms | 1.7667 ms | 1.2774 ms |   0.92 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |  **MedianOfThreeKiller** | **1000000** | **165.40 ms** | **3.2341 ms** | **2.3384 ms** |   **1.00** |     **0.00** |
|  SpanSort |  MedianOfThreeKiller | 1000000 | 140.55 ms | 1.9253 ms | 1.3922 ms |   0.85 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |  **MedianOfThreeKiller** |       **2** |  **43.92 ms** | **0.3150 ms** | **0.2277 ms** |   **1.00** |     **0.00** |
|  SpanSort |  MedianOfThreeKiller |       2 |  34.25 ms | 0.4342 ms | 0.3140 ms |   0.78 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |  **MedianOfThreeKiller** |       **3** |  **33.45 ms** | **1.3535 ms** | **0.9787 ms** |   **1.00** |     **0.00** |
|  SpanSort |  MedianOfThreeKiller |       3 |  23.03 ms | 0.4048 ms | 0.2927 ms |   0.69 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** | **PartialRandomShuffle** |      **10** |  **24.55 ms** | **0.6442 ms** | **0.4658 ms** |   **1.00** |     **0.00** |
|  SpanSort | PartialRandomShuffle |      10 |  20.43 ms | 0.3972 ms | 0.2872 ms |   0.83 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** | **PartialRandomShuffle** |     **100** |  **62.84 ms** | **1.3926 ms** | **1.0069 ms** |   **1.00** |     **0.00** |
|  SpanSort | PartialRandomShuffle |     100 |  63.82 ms | 0.5488 ms | 0.3968 ms |   1.02 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** | **PartialRandomShuffle** |   **10000** | **107.77 ms** | **0.9427 ms** | **0.6816 ms** |   **1.00** |     **0.00** |
|  SpanSort | PartialRandomShuffle |   10000 | 109.12 ms | 1.9813 ms | 1.4326 ms |   1.01 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** | **PartialRandomShuffle** | **1000000** | **157.25 ms** | **2.4090 ms** | **1.7418 ms** |   **1.00** |     **0.00** |
|  SpanSort | PartialRandomShuffle | 1000000 | 156.00 ms | 2.1233 ms | 1.5353 ms |   0.99 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** | **PartialRandomShuffle** |       **2** |  **46.76 ms** | **0.9070 ms** | **0.6558 ms** |   **1.00** |     **0.00** |
|  SpanSort | PartialRandomShuffle |       2 |  36.44 ms | 0.4650 ms | 0.3362 ms |   0.78 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** | **PartialRandomShuffle** |       **3** |  **36.89 ms** | **0.8397 ms** | **0.6072 ms** |   **1.00** |     **0.00** |
|  SpanSort | PartialRandomShuffle |       3 |  26.83 ms | 0.4346 ms | 0.3142 ms |   0.73 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |               **Random** |      **10** |  **42.55 ms** | **0.5290 ms** | **0.3825 ms** |   **1.00** |     **0.00** |
|  SpanSort |               Random |      10 |  38.07 ms | 0.3865 ms | 0.2795 ms |   0.89 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |               **Random** |     **100** |  **81.09 ms** | **1.7038 ms** | **1.2320 ms** |   **1.00** |     **0.00** |
|  SpanSort |               Random |     100 |  82.68 ms | 0.9337 ms | 0.6752 ms |   1.02 |     0.02 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |               **Random** |   **10000** | **154.94 ms** | **1.8913 ms** | **1.3675 ms** |   **1.00** |     **0.00** |
|  SpanSort |               Random |   10000 | 160.96 ms | 2.6909 ms | 1.9457 ms |   1.04 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |               **Random** | **1000000** | **229.81 ms** | **3.6416 ms** | **2.6331 ms** |   **1.00** |     **0.00** |
|  SpanSort |               Random | 1000000 | 233.81 ms | 1.5483 ms | 1.1195 ms |   1.02 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |               **Random** |       **2** |  **51.34 ms** | **0.7614 ms** | **0.5505 ms** |   **1.00** |     **0.00** |
|  SpanSort |               Random |       2 |  40.61 ms | 0.5410 ms | 0.3912 ms |   0.79 |     0.01 |
|           |                      |         |           |           |           |        |          |
| **ArraySort** |               **Random** |       **3** |  **43.75 ms** | **1.3119 ms** | **0.9486 ms** |   **1.00** |     **0.00** |
|  SpanSort |               Random |       3 |  32.83 ms | 0.6544 ms | 0.4732 ms |   0.75 |     0.02 |

**Comment by nietras** [comment]
E,g, for code like:
```csharp
        [ParamsSource(nameof(Lengths))]
        public int Length { get; set; }

        public IEnumerable<int> Lengths { get; }
```

**Comment by AndreyAkinshin** [comment]
@nietras, could you please provide the full repro?
I tried the following code:
```cs
[DryJob]
public class Bench
{
    [ParamsSource(nameof(Lengths))]
    public int Length { get; set; }

    public IEnumerable<int> Lengths => new[] {1, 2, 3, 10, 100, 1000};

    [Benchmark]
    public void Foo()
    {
    }
}
```
It produces the correct result in v0.10.12:
```
BenchmarkDotNet=v0.10.12, OS=macOS 10.13.2 (17C88) [Darwin 17.3.0]
Intel Core i7-4870HQ CPU 2.50GHz (Haswell), 1 CPU, 8 logical cores and 4 physical cores
.NET Core SDK=2.0.0
  [Host] : .NET Core 2.0.0 (Framework 4.6.00001.0), 64bit RyuJIT
  Dry    : .NET Core 2.0.0 (Framework 4.6.00001.0), 64bit RyuJIT

Job=Dry  LaunchCount=1  RunStrategy=ColdStart  
TargetCount=1  UnrollFactor=1  WarmupCount=1  

 Method | Length |     Mean | Error |
------- |------- |---------:|------:|
    Foo |      1 | 443.0 us |    NA |
    Foo |      2 | 431.0 us |    NA |
    Foo |      3 | 500.0 us |    NA |
    Foo |     10 | 417.0 us |    NA |
    Foo |    100 | 509.0 us |    NA |
    Foo |   1000 | 480.0 us |    NA |
```

**Comment by nietras** [comment]
@AndreyAkinshin you can try the following https://github.com/DotNetCross/Sorting/tree/bcb793438f2038ea3f3ab1a9fc0efbb97de1fed9
e.g. run https://github.com/DotNetCross/Sorting/blob/bcb793438f2038ea3f3ab1a9fc0efbb97de1fed9/tests/DotNetCross.Sorting.Benchmarks/Program.cs#L106

The only difference is that this uses `{ get;}` and sets it in ctor. But I doubt that is the issue... but it happened when I updated BDN, I think... :)

**Comment by AndreyAkinshin** [comment]
@nietras, I can't build this revision:
```
W:\Sandbox\Sorting (HEAD detached at bcb7934)
λ dotnet build
W:\Sandbox\Sorting\tests\DotNetCross.Sorting.Benchmarks\DotNetCross.Sorting.Benchmarks.csproj : warning NU1701: Package 'BenchmarkDotNet.Diagnostics.Windows 0.10.12' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [W:\Sandbox\Sorting\Sorting.sln]
W:\Sandbox\Sorting\tests\DotNetCross.Sorting.Benchmarks\DotNetCross.Sorting.Benchmarks.csproj : warning NU1701: Package 'BenchmarkDotNet.Toolchains.Roslyn 0.10.12' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [W:\Sandbox\Sorting\Sorting.sln]
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

W:\Sandbox\Sorting\tests\DotNetCross.Sorting.Benchmarks\DotNetCross.Sorting.Benchmarks.csproj : warning NU1701: Package 'BenchmarkDotNet.Diagnostics.Windows 0.10.12' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
W:\Sandbox\Sorting\tests\DotNetCross.Sorting.Benchmarks\DotNetCross.Sorting.Benchmarks.csproj : warning NU1701: Package 'BenchmarkDotNet.Toolchains.Roslyn 0.10.12' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
SpanHelpers.Sort.cs(531,76): error CS1525: Invalid expression term 'ref' [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,76): error CS1003: Syntax error, ':' expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,76): error CS1002: ; expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,90): error CS1001: Identifier expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,101): error CS1001: Identifier expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,106): error CS1001: Identifier expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,106): error CS1026: ) expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,106): error CS1002: ; expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,109): error CS1002: ; expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,109): error CS1513: } expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,123): error CS1001: Identifier expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
  DotNetCross.Sorting.Sequences -> W:\Sandbox\Sorting\src\DotNetCross.Sorting.Sequences\bin\Debug\netstandard2.0\DotNetCross.Sorting.Sequences.dll

Build FAILED.

W:\Sandbox\Sorting\tests\DotNetCross.Sorting.Benchmarks\DotNetCross.Sorting.Benchmarks.csproj : warning NU1701: Package 'BenchmarkDotNet.Diagnostics.Windows 0.10.12' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
W:\Sandbox\Sorting\tests\DotNetCross.Sorting.Benchmarks\DotNetCross.Sorting.Benchmarks.csproj : warning NU1701: Package 'BenchmarkDotNet.Toolchains.Roslyn 0.10.12' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
SpanHelpers.Sort.cs(531,76): error CS1525: Invalid expression term 'ref' [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,76): error CS1003: Syntax error, ':' expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,76): error CS1002: ; expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,90): error CS1001: Identifier expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,101): error CS1001: Identifier expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,106): error CS1001: Identifier expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,106): error CS1026: ) expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,106): error CS1002: ; expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,109): error CS1002: ; expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,109): error CS1513: } expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
SpanHelpers.Sort.cs(531,123): error CS1001: Identifier expected [W:\Sandbox\Sorting\src\DotNetCross.Sorting\DotNetCross.Sorting.csproj]
    2 Warning(s)
    11 Error(s)

Time Elapsed 00:00:03.04
```

**Comment by nietras** [comment]
Language support for `ref` is missing, are you using VS2017?

**Comment by AndreyAkinshin** [comment]
I tried it on a machine with .NET Core SDK 2.0.3, MSBuild 15.4 (VS 15.4.1). It seems that I need some updates.

**Comment by nietras** [comment]
Hmm, well you need language support for C# 7.2 and that was introduced in VS 15.5 I think. So yes, you have to upgrade, hope that is not an issue 😄

**Comment by AndreyAkinshin** [comment]
.NET Core SDK 2.1.4 solved the problem and I reproduced the issue. Will fix it in Benchmark v0.10.13.

**Comment by nietras** [comment]
@AndreyAkinshin sounds great, thank you very much.

**Comment by nietras** [comment]
@AndreyAkinshin if you have any suggestions regarding these Benchmarks I would also welcome them. They are a bit special due to Sort being in-place, so only 1 iteration per measurement can be done. Also there are so many cases that running it InProcess is a must for reasonable feedback.

**Comment by nietras** [comment]
@AndreyAkinshin how is the fix for this going? It's annoying me a bit ;)

**Comment by AndreyAkinshin** [comment]
@nietras, should be fixed now. v0.10.13 will be released in February. Meanwhile, you can use nightly builds.

**Comment by nietras** [comment]
Thanks!
