### ISSUE TITLE
Searching docs leads to 404 page

### ISSUE THREAD

**Issue by LordMike** [dotnet/BenchmarkDotNet#649]
On the docs (http://benchmarkdotnet.org/), searching in the topleft searchbar goes to (http://benchmarkdotnet.org/Docnet_search.htm) - but searching on that page (the large search bar) goes to (http://benchmarkdotnet.org/docnet_search.htm) (lowercase "d").

**Comment by AndreyAkinshin** [comment]
@LordMike, thanks for the report!

**Comment by adamsitnik** [comment]
@AndreyAkinshin was this fixed by #781?

**Comment by AndreyAkinshin** [comment]
Yes, it's fixed.
