### ISSUE TITLE
How do you use InProcessToolchain?

### ISSUE THREAD

**Issue by jnm2** [dotnet/BenchmarkDotNet#650]
From the [FAQ](https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/guide/FAQ.md#faq-frequently-asked-questions):

> * **Q** My benchmark unexpectedly stopped and I saw the information about error code. What can I do? 
> **A** BenchmarkDotNet generates, builds and runs new process for every benchmark. This behavior is sometimes interpreted by anti-virus as dangerous, and the process is killed. Use `EnvironmentAnalyser` to detect antivirus software and configure your benchmark to use `InProcessToolchain`.

As a noob, I'm searching the internet and looking at your code and can't figure out how to specify `InProcessToolchain` for `BenchmarkRunner.Run<SomeBenchmarks>();`

**Comment by adamsitnik** [comment]
Hello @jnm2 !

I described it in our [docs](http://benchmarkdotnet.org/Configs/Toolchains.htm#inprocesstoolchain)

If something is not clear please feel free to reopen the issue

**Comment by jnm2** [comment]
Oh, perfect! Thank you! Wonder why the docs were so hard to find.
