### ISSUE TITLE
Question: is it possible to access method, mean and scale programmatically once the benchmarks have ran?

### ISSUE THREAD

**Issue by Matthew-Bonner** [dotnet/BenchmarkDotNet#656]
Is it possible to access method, mean and scale programmatically once the benchmarks have ran?

**Comment by Matthew-Bonner** [comment]
Use case being I would like to run the benchmarks on the commandline as part of an automatic build system, and I'd like to flag up when the benchmarks are too slow, so would like to programmatically parse the results to then indicate on the build system summary page whether the build has passed or failed.

**Comment by Matthew-Bonner** [comment]
Use case being I would like to run the benchmarks on the command line as part of an automatic build system, and I'd like to flag up when the benchmarks are too slow, so would like to programmatically parse the results to then indicate on the build system summary page whether the build has passed or failed.

I couldn't see anywhere in the docs which specified I could and I took a look at the Summary class and it wasn't immediately apparent if I could access this data via the API or not.

**Comment by Matthew-Bonner** [comment]
I know artifacts are created which contain this information, but I was hoping to programmatically parse the Summary class but can't see how to. Should I parse the artifacts after the benchmarks have ran or is there another way?

**Comment by adamsitnik** [comment]
```cs
var summary = BenchmarkRunner.Run<Program>();

foreach (var report in summary.Reports)
{
    report.ResultStatistics.Mean // ResultStatistics has all you need
}
```

**Comment by Matthew-Bonner** [comment]
ResultStatistics is private.

**Comment by Matthew-Bonner** [comment]
Ah cool got to loop the reports first. Got it thanks.
