### ISSUE TITLE
[Params] for enums should include all values by default

### ISSUE THREAD

**Issue by svick** [dotnet/BenchmarkDotNet#658]
I think that with `[Params]` properties whose type is some `enum`, a fairly common situation is that I want all values of that `enum` to be included. It would be nice if doing this didn't require listing all those values in the attribute. I.e., instead of having to write:

```c#
[Params(CurrentCulture, CurrentCultureIgnoreCase, InvariantCulture, InvariantCultureIgnoreCase, Ordinal, OrdinalIgnoreCase)]
public StringComparison StringComparison { get; set; }
```

I could write just:

```c#
[Params]
public StringComparison StringComparison { get; set; }
```

Do you think this would be a useful feature? Would this be considered a breaking change? (If yes, something like `[EnumParams]` could be added instead.)

**Comment by adamsitnik** [comment]
I like this idea, but I am not sure how we make it more intuitive. Our users are used to providing all values.

Maybe something like:

```cs
[AllEnumValues]
public StringComparison StringComparison { get; set; }
```

@svick what do you think?

**Comment by svick** [comment]
@adamsitnik Yeah, I think that's reasonable (and it's what I meant by `[EnumParams]`).

Regarding naming, I think that since it's a variation on `Params` (just like `ParamsSource`), I think the name should include "Params". But I'm not sure what exactly would be the right name: `EnumParams` is too cryptic and something like `ParamsAllEnumValues` is too long.

**Comment by adamsitnik** [comment]
@svick so maybe `EnumAllParam` ?

Naming is hard ;p

**Comment by gsomix** [comment]
Hey, @svick, @adamsitnik, @AndreyAkinshin, do you mind if I reopen #664 with additional changes (tests, validator)?

**Comment by svick** [comment]
@gsomix Feel free to go ahead. I don't know when I would have the time to do it myself.
