### ISSUE TITLE
How can I pass information between the benchmark project and the dll generated by BenchmarkDotNet to run the benchmarks?

### ISSUE THREAD

**Issue by Matthew-Bonner** [dotnet/BenchmarkDotNet#661]
How can I pass information between the benchmark project and the dll generated by BenchmarkDotNet to run the benchmarks?

I have a problem whereby I need to set the ContentRoot in the WebBuilder in an ASP.NET Core application so that my integration tests that are being benchmarked can find the required files in order to execute correctly.

The ContentRoot path is known to the benchmark project, but passing this information to the code running in the dll generated by BenchmarkDotNet is seemingly impossible as the dll is running under another process.

Are there any solutions to this problem?

**Comment by adamsitnik** [comment]
Hi @Matthew-Bonner 

There are at least two ways.

1. `App.config` By default, we copy the app.config file content to the app which we generate
2. You can also pass the variables as environment variables to the process which we spawn. You can find more in our [docs](http://benchmarkdotnet.org/Advanced/EnvironmentVariables.htm)

**Comment by Matthew-Bonner** [comment]
2 works perfect, should probably specify how WithId works in the docs as it isn't clear. I just assumed I didn't need it and everything is working as expected. Thanks for your help with this.
