### ISSUE TITLE
If multiple benchmarks run simultanously are the results still accurate?

### ISSUE THREAD

**Issue by Matthew-Bonner** [dotnet/BenchmarkDotNet#662]
If multiple benchmarks run simultanously are the results still accurate?

The reason I ask is that if something programmatically triggers the running of benchmarks and one is running when another is triggered, I'm wondering if the first benchmark that is running will cause the second to indicate the benchmarks ran slower than they would have otherwise.

**Comment by adamsitnik** [comment]
They are not, and this is why we don't run benchmarks in parallel in BenchmarkDotNet.

However, we don't prevent this (so for example xunit test runner can run multiple `BenchmarkRunner.Run` at the same time).

If you want to save the time it takes to run the benchmarks you can use `Job.ShortRun`.  More about it [here](http://benchmarkdotnet.org/FAQ.htm). If you have to run them in parallel you can set the processor affinity per benchmark ([docs](http://benchmarkdotnet.org/Configs/Jobs.htm#env)).
