### ISSUE TITLE
Run Linux builds on AppVeyor

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#677]
AppVeyor supports Linux now: https://www.appveyor.com/blog/2018/03/06/appveyor-for-linux/
It would be nice to run our tests on AppVeyor Linux as well.
Related TravisCI issue: https://github.com/dotnet/BenchmarkDotNet/issues/496

**Comment by Ky7m** [comment]
Update. GA for Linux https://www.appveyor.com/blog/2018/05/15/appveyor-for-linux-is-generally-available/
I will take care a bit later (sorry, this month is very busy).

**Comment by adamsitnik** [comment]
@AndreyAkinshin @Ky7m I am going to close this one, I think that we should be fine with Linux build on TravisCI and Azure DevOps we have today.
