### ISSUE TITLE
Implement adapters to xunit-performance

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#679]
The [original idea](https://github.com/dotnet/corefx/pull/27164#issuecomment-366046669) by @AndyAyersMS:
> How hard would it be for BDN to consume and do reasonable things with tests that contain xunit-performance attributes? That way we could still author perf tests like we do now but run them under either perf harness.

It should not be hard. In fact, the implementation of `BenchmarkRunner.Run` is pretty simple:
```cs
public static Summary Run<T>(IConfig config = null) =>
    BenchmarkRunnerCore.Run(BenchmarkConverter.TypeToBenchmarks(typeof(T), config), ToolchainExtensions.GetToolchain);

public static Summary Run(Type type, IConfig config = null) =>
    BenchmarkRunnerCore.Run(BenchmarkConverter.TypeToBenchmarks(type, config), ToolchainExtensions.GetToolchain);

public static Summary Run(Type type, MethodInfo[] methods, IConfig config = null) =>
    BenchmarkRunnerCore.Run(BenchmarkConverter.MethodsToBenchmarks(type, methods, config), ToolchainExtensions.GetToolchain);
```
`BenchmarkConverter` just takes method attributes and transform it to `BenchmarkRunInfo` which contains information about how to run the benchmarks without any knowledge about original attributes (see source code:
https://github.com/dotnet/BenchmarkDotNet/blob/v0.10.12/src/BenchmarkDotNet.Core/Running/BenchmarkConverter.cs)
It's pretty easy to make it pluggable and write `XunitPerformanceBenchmarkConverter` which transforms `xunit-performance` attributes to the BenchmarkDotNet represtnation.
I like this idea because it will allow to run all existed xunit benchmarks on BenchmarkDotNet without massive modifications of the source code.

**Comment by AndreyAkinshin** [comment]
This issue depends on https://github.com/dotnet/BenchmarkDotNet/issues/678

**Comment by adamsitnik** [comment]
I did some research and it seems that it's not doable.

Why: In `xunit-performance` you don't just add `[Benchmark]` attribute, you also need to run the iterations in explicit way.

An example of empty benchmark from the xunit-performance [docs](https://github.com/Microsoft/xunit-performance):

```cs
[Benchmark]
void EmptyBenchmark()
{
    foreach (var iteration in Benchmark.Iterations)
        using (iteration.StartMeasurement())
            ; //do nothing
}

[Benchmark]
void EmptyBenchmark()
{
    Benchmark.Iterate(() => { /*do nothing*/ });
}
```

while in BenchmarkDotNet we do it out of the box for the user

**Comment by AndreyAkinshin** [comment]
@adamsitnik, =(
