### ISSUE TITLE
Implement [Arguments] support for InProcessToolchain

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#687]

**Comment by adamsitnik** [comment]
Fixed in #921

**Comment by adamsitnik** [comment]
Hi @melanchall 

The `InProcessToolchain` has been [obsoleted](https://github.com/dotnet/BenchmarkDotNet/blob/12fdbe20430b534bb390d758df821e5b437245d9/src/BenchmarkDotNet/Toolchains/InProcess/InProcessToolchain.cs#L13-L14) (you should get a warning about that) in favour of [InProcessEmitToolchain](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Toolchains/InProcess.Emit/InProcessEmitToolchain.cs):

Please switch to `InProcessEmitToolchain` and arguments are going to work.

**Comment by melanchall** [comment]
Hi @adamsitnik,

I use `InProcessNoEmitToolchain` as you've suggested [here](https://github.com/dotnet/BenchmarkDotNet/issues/1136#issuecomment-571214047). Is `InProcessNoEmitToolchain` obsolete too?

Also from the message of `[Obsolete]` attribute I see

> [Obsolete("Please use BenchmarkDotNet.Toolchains.InProcess.NoEmit.* classes")]

so it looks like `InProcessNoEmitToolchain` is the recommended way and should not prevent me of using all the BenchmarkDotNet features.

**Comment by adamsitnik** [comment]
Hi @melanchall 

Please excuse me for the confusion.

The `InProcessEmitToolchain` is the recommended and best in-process toolchain we have.
If for some reason it does not work on your target .NET Runtime (AOT .NET Runtimes etc) please use `InProcessNoEmitToolchain`.  `InProcessToolchain` is deprecated, we are going to remove it soon.

**Comment by melanchall** [comment]
@adamsitnik So `InProcessNoEmitToolchain` is bad choice and doesn't support some features by design?

**Comment by adamsitnik** [comment]
> So InProcessNoEmitToolchain is bad choice and doesn't support some features by design?

I would not say it's bad. The `InProcessEmitToolchain` is generating `IL` on the fly and produces the same code-gen as the out-proc-toolchains. However, generating IL is not always supported (some AOT runtimes) and this is why `InProcessNoEmitToolchain ` exists which as far as I remember uses `Delegate.Combine` to generate the boilerplate code, but the generated code is different than other toolchains and some features might not work. @ig-sinicyn is the best person to answer this question.

BTW since the original issue has been solved (#1136) you can use latest BDN from our CI and stop using the in-process toolchains at all:

```xml
<packageSources>
  <add key="bdn-CI" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

The default toolchains run every benchmark in a new process, just to avoid the side effects of the previous benchmark to affect the next one

**Comment by papafe** [comment]
I am having the same kind of issue with `Arguments are not supported by the InProcessToolchain yet, see #687 for more details` on Xamarin.iOS with Forms. 
I have tried using the latest BDN from CI with the same results, and I have managed to reproduce the error using the sample Xamarin.Forms project in the repo by trying to run the `IntroArguments` benchmarks.  
The problem with Xamarin.iOS is that:

- `InProcessEmitToolchain` cannot be used because it uses reflection and it's not supported on iOS
- `InProcessNoEmitToolchain` as well as the default toolchain (I am not sure which one is it) give the `Arguments are not supported...` error

Maybe running in a new process is not supported on Xamarin.Forms?

**Comment by adamsitnik** [comment]
@papafe I am afraid that this is by design (see #1360 for full details):

> Default to InProcess for Xamarin platforms. Since we can't find a
mono binary, we have to run in-process. Xamarin.iOS also shouldn't
use System.Reflection.Emit until the interpreter is more stable.
Users of BDN can experiment with the interpreter by configuring
their benchmarks manually.

 and we don't rather plan to fix it as it would require a non-trivial investment in the `InProcessNoEmitToolchain` or a brand new toolchain that would be implementing full Xamarin compilation

**Comment by papafe** [comment]
> @papafe I am afraid that this is by design (see #1360 for full details):
> 
> > Default to InProcess for Xamarin platforms. Since we can't find a
> > mono binary, we have to run in-process. Xamarin.iOS also shouldn't
> > use System.Reflection.Emit until the interpreter is more stable.
> > Users of BDN can experiment with the interpreter by configuring
> > their benchmarks manually.
> 
> and we don't rather plan to fix it as it would require a non-trivial investment in the `InProcessNoEmitToolchain` or a brand new toolchain that would be implementing full Xamarin compilation

@adamsitnik Well, it's at least good to know that this is the case and that it's not due to something that I have missed/misconfigured.

Thanks a lot for the answer!
