### ISSUE TITLE
DisassemblyDiagnoser for Mono does not work on Windows and Linux

### ISSUE THREAD

**Issue by dvorn** [dotnet/BenchmarkDotNet#689]
MonoDisassembler.OutputParser.Parse seems to be looking for the string "(__TEXT,__text) section" to find the beginning of disassembled code ([see](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Diagnosers/MonoDisassembler.cs#L56)).  However this string is seemingly produced by the otool on Mac.  On Windows and Linux, the objdump tool is used and the assembly in the log is prepended  by the string "Disassembly of section .text:".

Thus, OutputParser does not find the beginning of assembly and then crashes with NullReferenceException.

**Comment by AndreyAkinshin** [comment]
@morgan-kn, please take a look.

**Comment by AndreyAkinshin** [comment]
@dvorn, thanks for the report! The fix will be available in v0.10.14.
