### ISSUE TITLE
Performance Counters

### ISSUE THREAD

**Issue by omariom** [dotnet/BenchmarkDotNet#69]
Another idea to queue! :muscle: 
Add ability to gather performance counters during benchmark runs. Process specific counters would be the most useful but system wide ones  like Memory\ Page Reads /sec is important to have as well.

**Comment by mattwarren** [comment]
Thanks, another nice idea. When I get a chance, I'm going to be doing some more work on the "diagnostic" side of thing (see #56) and this fits in with that.

I also added your idea to the "Roadmap", see https://github.com/PerfDotNet/BenchmarkDotNet/wiki#roadmap

**Comment by omariom** [comment]
Thanks :+1:

**Comment by LeeCampbell** [comment]
+1 would be good to have the GC0,1 & 2 collection counts in the output. I find often this is a leading indicator as to why two implementations are performing differently.

**Comment by mattwarren** [comment]
> +1 would be good to have the GC0,1 & 2 collection counts in the output. I find often this is a leading indicator as to why two implementations are performing differently.

@LeeCampbell we already have Gen 0/1/2 Collection Counts **and** *Memory Traffic per Op*, via the BenchmarkDotNet [Diagnostics/Diagnoser](https://github.com/PerfDotNet/BenchmarkDotNet/tree/master/BenchmarkDotNet.Diagnostics) plugin. (Currently you need to compile it from source, there's no NuGet package)

See [my blog post](http://mattwarren.github.io/2016/02/17/adventures-in-benchmarking-memory-allocations/) for more info, but here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/157298/14498885/0f5d4eae-0194-11e6-955f-0a10794c461d.png)

**Comment by LeeCampbell** [comment]
Thanks @mattwarren. Will there be a [roadmap](https://github.com/PerfDotNet/BenchmarkDotNet/wiki/Roadmap)/[milestone ](https://github.com/PerfDotNet/BenchmarkDotNet/milestones)with the Diagnostics being available on nuget? 

The output above looks brilliant.

**Comment by mattwarren** [comment]
Hopefully soon, we are just chatting about that over in gitter, see https://gitter.im/PerfDotNet/BenchmarkDotNet?at=570e6335b4ace1d62ba237d6

**Comment by MartinJohns** [comment]
@mattwarren The link to the "Diagnostics/Diagnoser plugin" leads to a 404. Could you re-post the correct link?

**Comment by mattwarren** [comment]
@MartinJohns it's now here https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Diagnostics.Windows/MemoryDiagnoser.cs

**Comment by Kavignon** [comment]
So what’s the status here?

**Comment by adamsitnik** [comment]
Performance Counters are Windows-specific. .NET has become cross-platform since the issue was created (2016!) and we rather don't intend to add this feature as we have plenty of existing diagnosers that provide this + more information.
