### ISSUE TITLE
Local DLL dependencies

### ISSUE THREAD

**Issue by aalmada** [dotnet/BenchmarkDotNet#690]
I'm testing a p/invoke scenario on .NET Core 2.1 Preview 1 so my benchmark depends on a local native DLL. 
The DLL is in the bin folder but the benchmark can't find it.
Is there any way to make this work locally?
Thanks!

**Comment by adamsitnik** [comment]
hello @aalmada 

how do you reference this native dll on the `.csproj` level?

**Comment by aalmada** [comment]
hi @adamsitnik 
I was using just a post-build event command but, when I read your question, realized a reference with 'build action' set to 'none' and 'copy to output directory' set to 'copy if newer' could do the trick. It does!
Thanks!
