### ISSUE TITLE
Improve local CoreCLR support

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#700]
What we have today works, but is vulnerable to [this problem](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingDotNetCli.md#update-coreclr-using-runtime-nuget-package)

I want to use dotnet restore to install everything in a temp folder (not in the user/.nuget) to avoid this problem. But it takes a LOT of time so I need to implement #699 first.

Also part of the task is to verify that it works for all the OSes/

**Comment by AndreyAkinshin** [comment]
> Also part of the task is to verify that it works for all the OSes

@adamsitnik, what do you think, is it possible to write a test for it? I'm not sure that it should be one of our integration tests (because it takes to much time), but it would be nice to have an automatic way to test on any OS.

/cc @Ky7m

**Comment by adamsitnik** [comment]
@AndreyAkinshin it's a great idea! I will implement such test and try it with our CI. If it takes too long (more than 5 minutes) I remove it.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, I think that we can introduce new project with integration tests which should be run manually.

**Comment by adamsitnik** [comment]
@AndreyAkinshin another good idea!

**Comment by adamsitnik** [comment]
It took me a LOT of time to get it working and tested for ALL OSes, but it is finally **done**.
