### ISSUE TITLE
ExitCode != 0 error with local CoreFX and CoreCLR builds

### ISSUE THREAD

**Issue by stilettk** [dotnet/BenchmarkDotNet#702]
Hello! I'm trying to benchmark my changes with locally built CoreFX and CoreCLR. I follow [this](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/benchmarking.md) guide, by no success by far. Below I'll explain steps that I have taken. Please tell me what I'm doing wrong! I have also marked as **bold** the steps which, in my opinion, may be misleading in the docs - but I might be wrong of course :)

This is my configuration:

    public class LocalCoreClrConfig : ManualConfig
    {
        public LocalCoreClrConfig()
        {
            Add(Job.Default
                .With(new CustomCoreClrToolchain(
                    "before",
                    coreClrNuGetFeed: @"C:\Users\nbatov\Source\Repos\ListTest\Windows_NT.x64.Release_Old\.nuget\pkg",
                    coreClrVersion: "2.1.0-preview3-26419-0",
                    coreFxNuGetFeed: @"C:\Users\nbatov\Source\Repos\ListTest\corefx_new\packages\Release",
                    coreFxVersion: "4.5.0-preview3-26420-0",
                    targetFrameworkMoniker: "netcoreapp2.1"
                ))
            );

            Add(DefaultColumnProviders.Instance);
            Add(MarkdownExporter.GitHub);
            Add(new ConsoleLogger());
        }
    }

Here is what I have done:

1. Built CoreCLR repo according to it's guide.
2. Built CoreFX repo according to it's guide.
3. Downloaded and extracted daily build of .NET SDK from [this](https://github.com/dotnet/cli/blob/master/README.md#installers-and-binaries) link (notice that in the [documentation](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/benchmarking.md#benchmarking-net-core-21-applications) there is a **link to runtime, not SDK**).
4. Created a new console application for .NET Core 2.0, added BenchmarkDotNet nuget package. Added benchmark code. Copied builds of .NET SDK, CoreFX and CoreCLR folders to the same folder.
5. Tried to run the benchmark and got this error (full log here: https://pastebin.com/1rT4p1dq):

> error NU1101: Unable to find package Microsoft.NETCore.App. No packages exist with this id in source(s): CoreClrNuGetFeed, CoreFxNuGetFeed

6. I added `[KeepBenchmarkFiles]` attribute to see what's going wrong. I noticed that generated NuGet.config file is missing MyGet feeds:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />

    <add key="CoreClrNuGetFeed" value="C:\Users\nbatov\Source\Repos\ListTest\Windows_NT.x64.Release_Old\.nuget\pkg" />
    <add key="CoreFxNuGetFeed" value="C:\Users\nbatov\Source\Repos\ListTest\corefx_new\packages\Release" />
  </packageSources>
</configuration>
```
7. So I have added `<add key="myget.dotnetcore" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />` manually. Notice that even if I have added them globally as described [in the dogfooding guide](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#install-prerequisites), they will be ignored by the `<clear />` tag. **Is this correct**?
8. Now I need this packages to restore. So I executed .bat file in the autogenerated folder (I had to specify full path to dotnet.exe from extracted .NET SDK daily build).
9. This have restored nuget packages, but resulted in another error (full log here: https://pastebin.com/jUeXncPQ):

> C:\Users\nbatov\source\repos\ListTest\dotnet\sdk\2.1.300-preview3-008391\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(128,5): error : Cannot find project info for 'C:\Users\nbatov\Source\repos\ListTest\ListInsertRangeBenchmark\ListInsertRangeBenchmark\ListInsertRangeBenchmark.csproj'. This can indicate a missing project reference.

10. This is strange, because generated .csproj file has correct path. Anyway, now when running benchmarks I have this error (full log here: https://pastebin.com/8eXPSGXP):

> // *** Execute ***
> // Launch: 1 / 1
> ExitCode != 0
> No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

I don't know where to find the error which caused this exit code, nor I know what to do next.  There are no errors in benchmark code, because in runs normally with `DefaultConfig.Instance`.

Here is .zip with autogenerated files: [InsertRangeBench_InsertRange_Job-RMZSTB.zip](https://github.com/dotnet/BenchmarkDotNet/files/1841700/InsertRangeBench_InsertRange_Job-RMZSTB.zip)

Please help me, I'm out of ideas!

**Comment by stilettk** [comment]
It seems I have found the problem. I forgot to build CoreFX repo using my local CoreCLR repo by setting `/p:CoreCLROverridePath`. This way I got CoreFX repo with my updated CoreCLR, changed config to `CustomCoreClrToolchain.CreateForLocalCoreFxBuild` and now everything works!

Hovewer, looking back at my experience I want to raise some questions about the process. Aside from me understanding it better, maybe it can help to improve the project in the future :)

1. If CoreFX can be built using custom CoreCLR build and benchmark it, why would one use thew `CustomCoreClrToolchain`?
2. Still, in [documentation](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/benchmarking.md#benchmarking-net-core-21-applications) there is a link to **runtime, not SDK**. When I installed it, error about using .NET Core 2.0 was shown.
3. When running benchmark for the first time, I get the following error (as shown in step 5 in issue):
> error NU1101: Unable to find package Microsoft.NETCore.App. No packages exist with this id in source(s): CoreClrNuGetFeed, CoreFxNuGetFeed

My workaround was to set `[KeepBenchmarkFiles]` attribute, add `<add key="myget.dotnetcore" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />` line to generated NuGet.config and run `dotnet publish` again. This needs to be done only one time. This sounds like a bug to me.

4. It's strange that benchmarks completed with ExitCode != 0 without any message. Is it normal?

Anyway, thanks for the amazing tool!

**Comment by adamsitnik** [comment]
Hello @stilettk !

BIG thanks for giving it a try!

I have been working for the last two weeks on improving this toolchain. It's more flexible now, but the API has changed. The official realease for this is going to be `0.11.0`

> 1. If CoreFX can be built and benchmarked using custom CoreCLR build, why would one use the CustomCoreClrToolchain?

I am not sure if I understand correctly, but BDN builds a new exe to have a process isolation. So BDN needs to know how to build stuff. The toolchain is responsible for that.

> 2. Still, in documentation there is a link to runtime, not SDK. When I installed it instead of SDK, I got The current .NET SDK does not support targeting .NET Core 2.1 error.

Sorry for the inconvenience, I am going to correct this.

> 3. When running benchmark for the first time, I get the following error (as shown in step 5 in issue):

You now need to call `UseNuGetClearTag(false)` on the builder to prevent BDN from emitting the clear tag.

```cs
Job.ShortRun.With(
	CustomCoreClrToolchain.CreateBuilder()
		.DisplayName("local builds")
		.UseCoreClrLocalBuild("2.1.0-preview2-26313-0", @"C:\Projects\forks\coreclr\bin\Product\Windows_NT.x64.Release\.nuget\pkg", @"C:\Projects\coreclr\packages")
		.UseCoreFxLocalBuild("4.5.0-preview2-26313-0", @"C:\Projects\forks\corefx\bin\packages\Release")
		.UseNuGetClearTag(false)
		.ToToolchain())
```

> 4. It's strange that benchmark has completed with ExitCode != 0 without any error message. Is it nor

No, it was most probably a segmentation fault. But I have fixed this issue.

Please see #700 for more.


If you want to give it a try please update to `0.10.13.501` from our CI NuGet feed:

```xml
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

**Comment by adamsitnik** [comment]
Edit: I decided to not emit the clear tag by default for local builds and added a possibility to define an extra NuGet feed.

**Comment by adamsitnik** [comment]
I am closing since #700 fixes the problems mentioned here.
