### ISSUE TITLE
Support private builds of .NET Runtime 

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#706]
It would be great if we could benchmark private builds of .NET Runtime.

All we need to do is not to copy `supportedRuntime` node from `app.config` :

```xml
<startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
 </startup>
```

Sample code:

```cs
Job.Default.With(new ClrRuntime(version: "4.0"))
```

This sends the provided version as `COMPLUS_Version` env var to the benchmarked process.

**Comment by vitek-karas** [comment]
Thanks a lot Adam. Just tried this out and it works like a charm.
