### ISSUE TITLE
Native dependencies

### ISSUE THREAD

**Issue by shargon** [dotnet/BenchmarkDotNet#707]
My program require native libraries loaded in runtime from
`[ProgramPath]\Windows\x64\Library.dll`

How can i made for copy this libraries to the temporary folder?
How can i set native dependecies?

`Bin\Release\[Guid]\[ProgramPath]\Windows\x64\Library.dll`

**Comment by adamsitnik** [comment]
hi @shargon 

how do you reference your native dependencies in the `.csproj` file?

We generate a new executable in the same folder where your `.dll` which defines benchmarks is.

**Comment by shargon** [comment]
My native dependencies only are in a folder, and is copy to this folder using build events

**Comment by adamsitnik** [comment]
Please refer to a great blog post by @WojciechNagorski https://wojciechnagorski.com/2019/09/using-native-dll-and-resource-files-in-benchmarkdotnet-projects/
