### ISSUE TITLE
Can not run DisassemblyDiagnoser for CoreJob Benchmark

### ISSUE THREAD

**Issue by AndreyAvakyan** [dotnet/BenchmarkDotNet#711]
This is my code:

[DisassemblyDiagnoser(printAsm : true, printSource : true)] 
    [CoreJob]
    [RankColumn]
   [ShortRunJob]
    public class SyncMethods {     
      [Benchmark]
        public void SumMethod() {
           // Console.WriteLine(Vector.IsHardwareAccelerated);
            var sum = 0;
            for(var i = 0; i < 100_000; i++) {
                sum += i;
            }
        }
    }

In Main method I just do this BenchmarkRunner.Run<SyncMethods>()

In the output I've got an error

Failed to disassemble with following exception:
Unable to load DLL 'dbgeng.dll': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)
   at Microsoft.Diagnostics.Runtime.NativeMethods.DebugCreate(Guid& InterfaceId, Object& Interface)
   at Microsoft.Diagnostics.Runtime.DbgEngDataReader.CreateIDebugClient()
   at Microsoft.Diagnostics.Runtime.DbgEngDataReader..ctor(Int32 pid, AttachFlag flags, UInt32 msecTimeout)
   at Microsoft.Diagnostics.Runtime.DataTarget.AttachToProcess(Int32 pid, UInt32 msecTimeout, AttachFlag attachFlag)
   at BenchmarkDotNet.Disassembler.Program.Handle(Settings settings)
   at BenchmarkDotNet.Disassembler.Program.Main(String[] args)

Unhandled Exception: System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()

I use Version 0.10.13. 
I remember you've got already the same issue earlier #542, #543. But the issues are closed.
Thanks

**Comment by adamsitnik** [comment]
Hi @AndreyAvakyan 

#542, #543 are totally different things...

How do you run the benchmarks? From VS in debug? From console? As admin?

Could you also provide your `.csproj` file? I have never seen such behavior and I simply need more data.

**Comment by AndreyAvakyan** [comment]
Hi @adamsitnik 

I run in from JetBrains Rider in Realease mode.

This .csproj content of the main project:
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.10.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AsyncModule\AsyncModule.csproj" />
    <ProjectReference Include="..\AsyncSimdModule\AsyncSimdModule.csproj" />
    <ProjectReference Include="..\SyncModule\SyncModule.csproj" />
    <ProjectReference Include="..\SyncSimdModule\SyncSimdModule.csproj" />
  </ItemGroup>
</Project>

**Comment by adamsitnik** [comment]
Hmm it looks like it's a Windows issue ;) https://github.com/Microsoft/clrmd/issues/29

Could you try with following settings:

```xml
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
```

and if it fails then try for x64:
```xml
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
```

@AndreyAkinshin what is the default platform when running processes from Rider? I know that VS runs everything as 32bit by default.

**Comment by AndreyAvakyan** [comment]
It works if I run it from console:
dotnet run -c Release

**Comment by adamsitnik** [comment]
I don't have any idea how to fix the issue since it's a Windows issue so I am closing this issue and adding the #wontfix label.

It works from console, so I hope it's not a big problem for anyone.
