### ISSUE TITLE
[Params] with arrays as params throws System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by JCBurnside** [dotnet/BenchmarkDotNet#712]
It has innerException of System.MissingMethodException: No parameterless constructor defined for this object.

gist of code used to discover this: [https://gist.github.com/JCBurnside/c4d5ee6ee75f78f23167fe116ea9890b](https://gist.github.com/JCBurnside/c4d5ee6ee75f78f23167fe116ea9890b)

**Comment by JCBurnside** [comment]
UPDATE: It appears to be a problem with instance props  changing the prop to static allowed it to run normally.
I have tracked it down to one of a few possible spots:
[BenchmarkConverter#306](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Running/BenchmarkConverter.cs#L306)
or [BenchmarkConverter#314](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Running/BenchmarkConverter.cs#L314)

**Comment by adamsitnik** [comment]
@JCBurnside thanks for the bug report!

I had no idea that an array of primitive types can be an argument of an attribute constructor in C#.

I added support, from now this scenario is supported
