### ISSUE TITLE
How to specify the invocation/launch count per type when using Config for multiple runtimes?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#713]
@vitek-karas asked me this question today and honestly, I am not sure if we have a good solution for that case.

Background: The user has a few types with benchmarks and wants to run all of them for different runtimes **and** have a different invocation/iteration count per type.

The problem: when I set a `SimpleJob` attribute per type and I configure custom jobs in the config class I pass to runner, the settings don't get merged, but instead the jobs gets added:

```cs
class Program
{
    static void Main(string[] args) =>
        BenchmarkSwitcher.FromAssembly(typeof(Program).GetTypeInfo().Assembly).Run(args,
            DefaultConfig.Instance.With(Job.Clr).With(Job.Core));
}

[SimpleJob(runStrategy: RunStrategy.Monitoring, warmupCount: 1, targetCount: 10, invocationCount: 1)]
public class First
{
    [Benchmark] public void Nothing() { }
}

[SimpleJob(runStrategy: RunStrategy.Monitoring, warmupCount: 1, targetCount: 1, invocationCount: 1)]
public class Second
{
    [Benchmark] public void Nothing() { }
}
```

|  Method |     Job | Runtime | RunStrategy | TargetCount | UnrollFactor | WarmupCount |          Mean |     Error |    StdDev |
|-------- |-------- |-------- |------------ |------------ |------------- |------------ |--------------:|----------:|----------:|
| Nothing | Default |     Clr |  Monitoring |           1 |            1 |           1 | 3,421.2400 ns |        NA | 0.0000 ns |
| Nothing |     Clr |     Clr |     Default |     Default |           16 |     Default |     0.9211 ns | 0.0075 ns | 0.0063 ns |
| Nothing |    Core |    Core |     Default |     Default |           16 |     Default |     0.0000 ns | 0.0000 ns | 0.0000 ns |

I got it working by having a dedicated config type per type with benchmarks, but this idea sucks because it requires too much code.

```cs
class Program
{
    static void Main(string[] args)
    {
        BenchmarkSwitcher.FromAssembly(typeof(Program).GetTypeInfo().Assembly).Run(args);
    }
}

public class MyConfig : ManualConfig
{
    public MyConfig()
    {
        Add(GetPerTypeSettings(Job.Clr));
        Add(GetPerTypeSettings(Job.Core));
    }

    protected virtual Job GetPerTypeSettings(Job runtimeJob) => runtimeJob;
}

    
public class MyConfigFirst : MyConfig
{
    protected override Job GetPerTypeSettings(Job runtimeJob) => runtimeJob.With(RunStrategy.Monitoring).WithInvocationCount(1).WithTargetCount(1);
}

[Config(typeof(MyConfigFirst))]
public class First
{
    [Benchmark] public void Nothing() { }
}

public class MyConfigSecond : MyConfig
{
    protected override Job GetPerTypeSettings(Job runtimeJob) => runtimeJob.With(RunStrategy.Monitoring).WithInvocationCount(1).WithTargetCount(10);
}

[Config(typeof(MyConfigSecond))]
public class Second
{
    [Benchmark] public void Nothing() { }
}
```

``` ini

BenchmarkDotNet=v0.10.13.20180409-develop, OS=Windows 10.0.16299.309 (1709/FallCreatorsUpdate/Redstone3)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
Frequency=3507503 Hz, Resolution=285.1031 ns, Timer=TSC
  [Host]     : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2633.0
  Job-LKIZOH : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2633.0
  Job-BINUMK : .NET Core 1.1.7 (CoreCLR 4.6.26201.01, CoreFX 4.6.24705.01), 64bit RyuJIT

InvocationCount=1  RunStrategy=Monitoring  TargetCount=1  

```
|  Method | Runtime |     Mean | Error |
|-------- |-------- |---------:|------:|
| Nothing |     Clr | 827.1 us |    NA |
| Nothing |    Core | 290.2 us |    NA |

@AndreyAkinshin @ig-sinicyn do you guys have a better idea how to get it work with less code? Or maybe I will have to change the way we merge configs? Sth like: if two different jobs configure different settings merge them into one instead of adding all of them. ?

**Comment by AndreyAkinshin** [comment]
In the past, I had an idea of "JobMutators", see https://github.com/dotnet/BenchmarkDotNet/issues/257#issuecomment-247278726, https://github.com/dotnet/BenchmarkDotNet/issues/279#issuecomment-252823761

To be honest, I don't remember why it's still not implemented. The infrastructure is ready, it should be easy to implement this feature. `JobMutator` looks like a usual job, but it affects all existed jobs intead of introducing a new one.
Thus, in your case, it can look as follows:
```cs
[SimpleJobMutator(runStrategy: RunStrategy.Monitoring, warmupCount: 1, targetCount: 10, invocationCount: 1)]
public class First
{
    [Benchmark] public void Nothing() { }
}

[SimpleJobMutator(runStrategy: RunStrategy.Monitoring, warmupCount: 1, targetCount: 1, invocationCount: 1)]
public class Second
{
    [Benchmark] public void Nothing() { }
}
```
Also we can introduce some predefined mutators. E.g., `DryJobMutator` will switch all defined job to the "Dry" mode (it should be a useful feature for config debugging).

If it solves the original problem, I can implement it.

**Comment by ig-sinicyn** [comment]
Summary:
1. Add mutable config (ManualConfig looks like a good candidate)
2. Add interface with method that accepts ManualConfig and updates it
3. Collect interface implementations from attributes and run them over a copy of original config.
...
5. Win)

**Comment by ig-sinicyn** [comment]
P.S. The mutator may add a new job or update existing ones, so both old and new behavior may be implemented on top of the mutator attribute.

**Comment by adamsitnik** [comment]
@vitek-karas I needed to implement it for CoreCLR purpose, now it's:

```cs
class Program
{
    static void Main(string[] args) =>
        BenchmarkSwitcher.FromAssembly(typeof(Program).GetTypeInfo().Assembly).Run(args,
            DefaultConfig.Instance.With(Job.Clr).With(Job.Core));
}

[TargetCount(10)]
public class First
{
    [Benchmark] public void Nothing() { }
}

[TargetCount(1)]
public class Second
{
    [Benchmark] public void Nothing() { }
}
```

**Comment by vitek-karas** [comment]
@adamsitnik  Thanks a lot!
