### ISSUE TITLE
If fail to build in Parallel due to file access issues, try to build sequentially

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#719]

**Comment by martincostello** [comment]
Is there an ETA on a version with this fix being published to NuGet? I'm having this problem with `0.10.14` with a branch of a project using preview 2 of .NET Core 2.1. It's fine with 2.0.

**Comment by adamsitnik** [comment]
hello @martincostello 

I don't have ETA for `0.11.0`, but you can use our preview package from our CI feed today:

```xml
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

**Comment by martincostello** [comment]
Thanks, I’ll use that for now. My 2.1 branch of my project is going to stay as something experimental until it reaches final non-preview/rc release anyway.

**Comment by martincostello** [comment]
I've tried using `0.10.14.524` from the AppVeyor feed, but I'm still getting errors about files being in use when trying to run my normal benchmarks:

```
// Build Exception: Microsoft (R) Build Engine version 15.7.145.53551 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452

C:\Program Files\dotnet\sdk\2.1.300-preview2008530\Microsoft.Common.CurrentVersion.targets(4343,5): warning MSB3026: Could not copy "C:\Coding\Thing\src\Thing\bin\Release\netcoreapp2.1\Thing.dll" to "bin\Release\netcoreapp2.1\Thing.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\Coding\Thing\tests\Thing.Benchmarks\bin\Release\netcoreapp2.1\Thing.dll' because it is being used by another process  [C:\Coding\Thing\tests\Thing.Benchmarks\Thing.Benchmarks.csproj]
```

**Comment by adamsitnik** [comment]
@martincostello have you tried killing all `dotnet` processes before running the benchmarks?

**Comment by martincostello** [comment]
@adamsitnik I didn't explicitly try that, no. I'll give that a try and get back to you.

**Comment by martincostello** [comment]
I checked no instances of `dotnet` were running and then did `dotnet run` to run my benchmark project. It does the initial compilation for the run fine, but then the internal compilations for the benchmarks themselves fail.

**Comment by adamsitnik** [comment]
@martincostello If it works fine for 2.0 but not for 2.1 it must be a `dotnet cli` bug ;(

My only idea for now is try to set `<UseSharedCompilation>false</UseSharedCompilation>` in your `.csproj` file

**Comment by AndreyAkinshin** [comment]
> it must be a dotnet cli bug ;(

@adamsitnik is there an issue for this bug? It would be nice to fix it in 2.1 RTM.

**Comment by martincostello** [comment]
I've managed to get the benchmark compilation to work by setting:

```xml
<UseSharedCompilation>false</UseSharedCompilation>
<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
```

For context, I'm benchmarking a self-hosted MVC application via its HTTP endpoints.

**Comment by AndreyAkinshin** [comment]
@martincostello, thanks for the information.
@adamsitnik, I guess it makes sense to add this information to the documentation. What do you think?

**Comment by martincostello** [comment]
FYI I'm not having this issue with RC1 of the .NET Core 2.1.300 SDK.
