### ISSUE TITLE
Add scaled column for Allocated Memory

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#722]
Suggested by @stephentoub

> There's also no equivalent for the memory columns that I could find, which makes things inconsistent in the results, since some of these benchmarks are more about memory than they are about throughput.

Side note: The column should be visible when one of the benchmarks is marked as baseline

**Comment by gsomix** [comment]
I'm on it.

**Comment by adamsitnik** [comment]
@gsomix could you wait until I merge #878 ? I should merge it in 24h. It contains some things that would break your PR for sure (it's touching the columns for diagnosers)

**Comment by gsomix** [comment]
@adamsitnik OK, I'm just reading code for now. :)

**Comment by gsomix** [comment]
@adamsitnik I'm looking for some guidance for this issue. There are classes for baselines (e.g. `BaselineCustomColumn`) that tightly coupled with `Statistics`. We don't have any statistics for memory usage, only raw numbers of allocated bytes or gc operations. Should I somehow reuse and refactor exist baseline columns, or just to create new one (like `MetricScaledColumn`)?

**Comment by adamsitnik** [comment]
@gsomix I think that you could detect if any of the Benchmarks have a basline, if so MemoryDiagnoser could return one more metric - scaled allocated bytes

**Comment by Kavignon** [comment]
I’ll take this if that’s ok!
