### ISSUE TITLE
MemoryDiagnoser should include memory allocated by all Threads that were live during benchmark execution

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#723]
Suggested by @stephentoub

> Another issue I have with the memory columns is the allocation one.  For async methods, it's usually very misleading, since it's only measuring the calling thread.
So I'm manually removing that from the results where it doesn't make sense.
I'd suggest the memory diagnoser by default remove it as well when the benchmark returns Task
But have some way to turn it back on
Or something like that

Current problem: there is no API available for .NET Core that we could use. As of today BDN is using `System.GC.GetAllocatedBytesForCurrentThread()` for .NET Core. There is no way to iterate through all the threads and get this value. Moreover, some threads could have exited in the meantime.

The problem does not occur for .NET  framework, where we use `AppDomain.CurrentDomain.MonitoringTotalAllocatedMemorySize`

**Comment by haf** [comment]
This is an issue for me when trying to benchmark Logary, because all GC happens on Hopac threads. However, these threads are known at runtime during setup: https://github.com/Hopac/Hopac/blob/master/Libs/Hopac.Platform/Init.fs#L13

**Comment by NickCraver** [comment]
I've fired up the API discussion in https://github.com/dotnet/corefx/issues/30644

**Comment by hpbieker** [comment]
It would be nice to get this fixed so that we could get proper memory numbers for async code where some of the callbacks ends up on some other thread.

**Comment by adamsitnik** [comment]
This issue has been fixed in #1155 but it's going to work only with .NET Core 3.0 preview6+.

The .NET Team does not plan to backport the new API to older versions of .NET Core.

**Comment by gfoidl** [comment]
Should https://github.com/dotnet/performance/blob/master/docs/benchmarkdotnet.md (L233)

> - **For .NET Core the Allocated Memory is only for the current thread**, see [#723](https://github.com/dotnet/BenchmarkDotNet/issues/723) for more.

be updated to reflect this?

**Comment by adamsitnik** [comment]
@gfoidl yes, good catch! Could you please send a PR?

**Comment by gfoidl** [comment]
Yes, will send one.
