### ISSUE TITLE
Allocated Memory results are not scaled with OperationPerInvoke

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#724]
As reported by @stephentoub

```cs
[MemoryDiagnoser]
[ShortRunJob]
public class WithOperationsPerInvokeBenchmarks
{
    [Benchmark(OperationsPerInvoke = 4)]
    public void WithOperationsPerInvoke()
    {
        DotInline(new object(), new object());
        DotInline(new object(), new object());
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private void DotInline(object left, object right) { }
}
```

returns `96` instead of `96/4`

/cc @valenis

**Comment by adamsitnik** [comment]
@benaadams are you sure? We have an [integration test](https://github.com/dotnet/BenchmarkDotNet/blob/8a2eecd9297fa01d4639d952f3dd6c43a646b66c/tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs#L174) to make sure it does not come back. I can't repo it.

**Comment by benaadams** [comment]
Not sure but the allocations in the benchmark in this PR are showing 40KB for the pre-allocations; when I'd expect it more of 40B https://github.com/aspnet/AspNetCore/pull/5688

**Comment by adamsitnik** [comment]
Have you tried to check if with Memory Profiler? Could you share the log?

What I am interested in is the line that starts with `GC:`

```log
WorkloadResult   1: 12690704 op, 214321145.00 ns, 16.8880 ns/op
(...)
WorkloadResult  18: 12690704 op, 208072645.00 ns, 16.3957 ns/op
GC:  0 0 0 0 12690704
```
