### ISSUE TITLE
Improve building guideline

### ISSUE THREAD

**Issue by Rizzen** [dotnet/BenchmarkDotNet#726]
I guess that it is worth adding some instructions to [Building section in Contribution guideline](http://benchmarkdotnet.org/Contributing/Building.htm) cause since https://github.com/dotnet/BenchmarkDotNet/commit/7173f7de21de269193baf624d04cb5504cc5a298 developer have to install NET Core 2.1 Preview 1 to build solution.

Downloads
• https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview1
• https://www.microsoft.com/net/download/dotnet-core/runtime-2.1.0-preview1

**Comment by AndreyAkinshin** [comment]
@Rizzen, it makes sense. Do you want to send a pull request?

**Comment by Rizzen** [comment]
@AndreyAkinshin , sure. https://github.com/dotnet/BenchmarkDotNet/pull/727

**Comment by adamsitnik** [comment]
Fixed by #727
