### ISSUE TITLE
Handle missing Mono runtime more gracefully

### ISSUE THREAD

**Issue by Zhentar** [dotnet/BenchmarkDotNet#734]
Loosely following the overview documentation, I added `[CoreJob, ClrJob, MonoJob]` to my test class. It ran through my two test cases in Core, CLR, and then crashed because I don't have Mono installed.

It would be nice to notify me about missing prerequisites before I waited through running four tests cases, but barring that it would at least be nicer if I got the results for those test cases.

**Comment by AndreyAkinshin** [comment]
@Zhentar, it's a good idea, thanks.

**Comment by adamsitnik** [comment]
@Zhentar good point, fixed
