### ISSUE TITLE
Reduce number of initial pilot ops to 1 or make it configurable

### ISSUE THREAD

**Issue by surban** [dotnet/BenchmarkDotNet#736]
Currently piloting always starts with 4 ops. This can take an unnecessary long time if the function to benchmark is long running.

Thus I suggest to reduce the number of initial pilot ops to 1. This will not reduce accuracy for short-running functions, since it is just an initial value and will be increased automatically to match the specified IterationTime.

Probably this can be done by simply changing `MinInvokeCount` in `Engine.cs`.

**Comment by adamsitnik** [comment]
I will solve it soon, will be part of `0.11.0`
