### ISSUE TITLE
Possible Bug with InProcessAttribute

### ISSUE THREAD

**Issue by Mike-EEE** [dotnet/BenchmarkDotNet#739]
Hey there BenchmarkDotNet Community and Team,

Please see a very simple project I have created here:
https://github.com/Mike-EEE/BenchmarkDotNet.InProcess/

I am encountering a weird issue that occurs when the `InProcess` attribute is used, and when the `BenchmarkDotNet.Artifacts` folder exists.

On my non-VM (host machine), when I run the above benchmark for the first time and `BenchmarkDotNet.Artifacts` does _not_ exist or if I run it subsequent times while deleting this folder beforehand, I get results such as this:

```
  Method |     Mean |     Error |    StdDev |
-------- |---------:|----------:|----------:|
 ToArray | 18.61 us | 0.1818 us | 0.1518 us |
```

When `BenchmarkDotNet.Artifacts` _does_ exist, I get the following results consistently:

```
  Method |     Mean |     Error |    StdDev |
-------- |---------:|----------:|----------:|
 ToArray | 20.64 us | 0.1354 us | 0.1267 us |
```

Please note the 2us difference.

On my VM (I know there are differences in results, but work with me here), I get the opposite behavior.  On the first run when `BenchmarkDotNet.Artifacts` does _not_ exist, I get the following results:

```
  Method |     Mean |     Error |    StdDev |
-------- |---------:|----------:|----------:|
 ToArray | 21.55 us | 0.4923 us | 0.5268 us |
```

When `BenchmarkDotNet.Artifacts` _does_ exist, I get the following results:

```
  Method |     Mean |     Error |    StdDev |
-------- |---------:|----------:|----------:|
 ToArray | 19.13 us | 0.3791 us | 0.3361 us |
```

To add to the mix here, if I [comment out this line](https://github.com/Mike-EEE/BenchmarkDotNet.InProcess/blob/71536fb0f686136666f4374a1b74256b9e2b6458/BenchmarkDotNet.InProcess/Program.cs#L31), I get the `19.xx` consistently _every_ time on my VM, regardless of `BenchmarkDotNet.Artifacts` exists.  This line does not impact my non-VM host machine.

Please also note that running this benchmark w/o the `InProcess` attribute results in a consistent `19.xx` result on my VM, regardless on if I comment out the offending line above or not.  So it would seem the quirkiness I am experiencing here has to do with running in-process.

To add more context on the difference between my VM and host (non-VM machine), I am performing a "Publish..." from the right-click of the project in the above solution, and then copying/pasting the contents of this to a folder on my host (non-VM) machine.  If there is another accepted/expected way of publishing BDN contents to another machine, this would be great to know.  Otherwise, the publish profile has been added to the solution above for your convenience.

I hope all of this makes sense.  Please let me know if there is something I have misunderstood here and/or if you have any questions.  For my side, it would be nice to know if is it considered good or bad practice to "seed" the calls to the benchmarks as outlined in the differentiating line above?  That would help clarify things, but outside of that I feel there is some inconsistent behavior here that might be due to a latent bug and/or further misunderstanding on my part.

Thank you for any assistance/guidance you can provide!

**Comment by AndreyAkinshin** [comment]
@Mike-EEE, thanks for the report! Could you please share the full environment info?

I tried you results with the `[InProcess, CoreJob, MemoryDiagnoser]` attributes. Here are my results:

```
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.16299.371 (1709/FallCreatorsUpdate/Redstone3)
Intel Core i7-7700K CPU 4.20GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=2.1.300-preview2-008533
  [Host] : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT
  Core   : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT

Runtime=Core  

  Method |       Job |          Toolchain |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
-------- |---------- |------------------- |---------:|----------:|----------:|-------:|----------:|
 ToArray |      Core |            Default | 14.17 us | 0.2670 us | 0.2498 us | 9.5215 |  39.13 KB |
 ToArray | InProcess | InProcessToolchain | 14.28 us | 0.2239 us | 0.1870 us | 9.5215 |  39.13 KB |
```

**Comment by Mike-EEE** [comment]
Cool, thank you for the prompt reply @AndreyAkinshin.  I guess I forgot the most important part huh? 😆 

Here is my host (non-VM) machine:
```
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.14393.2189 (1607/AnniversaryUpdate/Redstone1)
Intel Core i7-4820K CPU 3.70GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
Frequency=3613269 Hz, Resolution=276.7577 ns, Timer=TSC
.NET Core SDK=2.1.300-preview2-008533
  [Host] : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT

Job=InProcess  Toolchain=InProcessToolchain
```

Here is my VM machine:
```
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.16299.371 (1709/FallCreatorsUpdate/Redstone3)
Intel Core i7-4820K CPU 3.70GHz (Haswell), 1 CPU, 8 logical and 8 physical cores
.NET Core SDK=2.1.300-preview2-008533
  [Host] : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT

Job=InProcess  Toolchain=InProcessToolchain
```

Please note that the project in the repo above does not use the `CoreJob` or `MemoryDiagnoser` attributes, and I have not tried to reproduce it as such just yet.

Were you able to reproduce the discrepancy in times with subsequent runs by deleting the `BenchmarkDotNet.Artifacts` folder between, by chance?

To be sure, the steps for reproduction here are:

1. Run the benchmark. (will be some number, `14.28` it looks like in your case.
1. Run the benchmark again. (should be another number ~2us in differential -- subsequent runs should also yield this same number).
1. Delete the `BenchmarkDotNet.Artifacts` folder.
1. Run benchmark once again, and it should be the same result from the first run.

**Comment by AndreyAkinshin** [comment]
@Mike-EEE, could you please try again *without* the `BenchmarkDotNet.Artifacts` folder and *with* `[KeepBenchmarkFiles]`?

**Comment by Mike-EEE** [comment]
Ah alright... I see the `KeepBenchmarkFiles` attribute @AndreyAkinshin ... but when you say without `BenchmarkDotNet.Artifacts` do you mean deleting the folder?  I am still getting the same results if that is what you mean.  Please let me know if there is another configuration I should be using.

**Comment by Mike-EEE** [comment]
Ah!  Scratch that @AndreyAkinshin ... I am indeed able to get a consistent ~21us on my host machine when using `KeepBenchmarkFiles` attribute.  Is this a known issue, then?

**Comment by Mike-EEE** [comment]
I agree with that @adamsitnik.  That is my impression as well.  However, I am getting files generated into the `BenchmarkDotNet.Artifacts` folder when using the `InProcess` atttribute.  `.md`, `.cvs`, and `.html` files all get generated along with the `.log` file in the directory above them.  Is this not expected behavior?

I am also wondering if anyone is able to reproduce my results using the steps outlined above.

**Comment by adamsitnik** [comment]
@Mike-EEE the files you mention are files with the results, we generate them after running the benchmarks

Can you repeat this behavior over the time?

this is why the out-proc is our default setting - good process-level isolation, process running as high priority and few other things to make sure the results are stable and repeatable.

**Comment by AndreyAkinshin** [comment]
@Mike-EEE, could you please try the following config (with and without existed `BenchmarkDotNet.Artifacts` folder):
```cs
        private class Config : ManualConfig
        {
            public Config()
            {
                Add(StatisticColumn.Min);
                Add(StatisticColumn.Max);
                foreach (var unrollFactor in new[] {1, 16, 64})
                foreach (var invocationCount in new[] {32768, 65536})
                    Add(Job.InProcess
                        .WithLaunchCount(1)
                        .WithWarmupCount(5)
                        .WithTargetCount(10)
                        .WithInvocationCount(invocationCount)
                        .WithUnrollFactor(unrollFactor)
                    );
            }
        }
```
This behaviour is not a known issue, but it's definitely not OK. On my local machine, I can observe several stable levels (a multimodal distribution across all runs), but I don't know why do we have such situation.

**Comment by Mike-EEE** [comment]
Ah! OK that makes sense @adamsitnik ... the benchmark files being the COMPILED benchmark files.  And yes this is completely reproducible on my side on both VM and non-VM host.  I would agree with you that out of process is a better environment, but my concern here is of course there might be a latent, unknown issue that might be skewing results in-process and maybe who knows what else.

@AndreyAkinshin here are the results from running with your provided configuration.

Here is my host, with the first run w/o the artifacts folder:

```
  Method | InvocationCount | UnrollFactor |     Mean |     Error |    StdDev |      Min |      Max |
-------- |---------------- |------------- |---------:|----------:|----------:|---------:|---------:|
 ToArray |           32768 |            1 | 20.92 us | 0.2057 us | 0.1360 us | 20.66 us | 21.16 us |
 ToArray |           32768 |           16 | 20.77 us | 0.2000 us | 0.1323 us | 20.59 us | 20.94 us |
 ToArray |           32768 |           64 | 20.78 us | 0.2046 us | 0.1217 us | 20.63 us | 21.01 us |
 ToArray |           65536 |            1 | 20.75 us | 0.2170 us | 0.1292 us | 20.51 us | 20.96 us |
 ToArray |           65536 |           16 | 20.89 us | 0.0892 us | 0.0466 us | 20.81 us | 20.94 us |
 ToArray |           65536 |           64 | 20.89 us | 0.2255 us | 0.1342 us | 20.69 us | 21.13 us |
```

2nd run with the artifacts folder:

```
  Method | InvocationCount | UnrollFactor |     Mean |     Error |    StdDev |      Min |      Max |
-------- |---------------- |------------- |---------:|----------:|----------:|---------:|---------:|
 ToArray |           32768 |            1 | 20.72 us | 0.2716 us | 0.1616 us | 20.48 us | 21.02 us |
 ToArray |           32768 |           16 | 20.80 us | 0.3246 us | 0.2147 us | 20.53 us | 21.21 us |
 ToArray |           32768 |           64 | 20.77 us | 0.2353 us | 0.1400 us | 20.50 us | 21.02 us |
 ToArray |           65536 |            1 | 20.98 us | 0.2771 us | 0.1833 us | 20.69 us | 21.26 us |
 ToArray |           65536 |           16 | 20.91 us | 0.2402 us | 0.1589 us | 20.70 us | 21.14 us |
 ToArray |           65536 |           64 | 20.97 us | 0.3537 us | 0.2105 us | 20.72 us | 21.32 us | 
```

1st run on my VM without artifacts folder:

```
  Method | InvocationCount | UnrollFactor |     Mean |     Error |    StdDev |      Min |      Max |
-------- |---------------- |------------- |---------:|----------:|----------:|---------:|---------:|
 ToArray |           32768 |            1 | 20.85 us | 0.4489 us | 0.2969 us | 20.37 us | 21.42 us |
 ToArray |           32768 |           16 | 20.81 us | 0.3712 us | 0.2455 us | 20.54 us | 21.34 us |
 ToArray |           32768 |           64 | 20.97 us | 0.5519 us | 0.3650 us | 20.59 us | 21.60 us |
 ToArray |           65536 |            1 | 20.79 us | 0.1567 us | 0.0932 us | 20.61 us | 20.90 us |
 ToArray |           65536 |           16 | 20.82 us | 0.2733 us | 0.1626 us | 20.58 us | 21.16 us |
 ToArray |           65536 |           64 | 20.91 us | 0.1899 us | 0.1256 us | 20.70 us | 21.09 us |
```

2nd run on my VM with artifacts folder:

```
  Method | InvocationCount | UnrollFactor |     Mean |     Error |    StdDev |      Min |      Max |
-------- |---------------- |------------- |---------:|----------:|----------:|---------:|---------:|
 ToArray |           32768 |            1 | 21.33 us | 0.6255 us | 0.3271 us | 20.72 us | 21.71 us |
 ToArray |           32768 |           16 | 20.98 us | 0.2157 us | 0.1284 us | 20.72 us | 21.16 us |
 ToArray |           32768 |           64 | 20.84 us | 0.2791 us | 0.1846 us | 20.55 us | 21.12 us |
 ToArray |           65536 |            1 | 21.38 us | 0.9191 us | 0.6080 us | 20.74 us | 22.40 us |
 ToArray |           65536 |           16 | 21.06 us | 0.3072 us | 0.2032 us | 20.84 us | 21.42 us |
 ToArray |           65536 |           64 | 20.76 us | 0.1804 us | 0.1193 us | 20.63 us | 20.97 us | 
```

Upon running the benchmarks with your configuration and seeing the issue clear (that is, no differentiated results in the range of ~19us), I noticed that I was able to "fix" this issue by using the following configuration for my host non-VM:

```
	class Config : ManualConfig
	{
		public Config()
		{
			Add(Job.InProcess);
		}
	}
```

and the following configuration for my VM:

```
	class Config : ManualConfig
	{
		public Config()
		{
			Add(Job.InProcess
			       .WithLaunchCount(1)
			       .WithWarmupCount(5));

		}
	}
```

So it would seem that the root of this issue stems from using the `InProcess` attribute for the host non-VM and some additional factors for the VM.

**Comment by adamsitnik** [comment]
>  would agree with you that out of process is a better environment, but my concern here is of course there might be a latent, unknown issue that might be skewing results in-process and maybe who knows what else.

I am glad that you reported this problem, I just wanted to say why it's not our default behavior. Many people ask me for that every day ;)

**Comment by Mike-EEE** [comment]
OK @AndreyAkinshin I have been digging through this and have some more data points for you.  I have created 5 more branches in my repo that show off different result times that are reproducible.  Each one of these should be run first without the `BenchmarkDotNet.Artifacts` and then simply run again with the `BenchmarkDotNet.Artifacts` as it exists on disk.  They demonstrate different types of results of what I call lower bound (~19us in the benchmark results found in the branch's `README`), and upper bound (~21us in the results).

In the list below, I provide a link to the example branch, followed by the results of the first run and then the second run, each denoted by their resulting bounds, if that makes sense.  Please note that the "second run" is also consistent with further subsequent runs as well. 

- [Example 1](https://github.com/Mike-EEE/BenchmarkDotNet.InProcess/tree/TheWeird_01): lower bound -> upper bound
- [Example 2](https://github.com/Mike-EEE/BenchmarkDotNet.InProcess/tree/TheWeird_02): upper bound -> upper bound
- [Example 3](https://github.com/Mike-EEE/BenchmarkDotNet.InProcess/tree/TheWeird_03): lower bound -> lower bound
- [Example 4](https://github.com/Mike-EEE/BenchmarkDotNet.InProcess/tree/TheWeird_04): upper bound -> lower bound
- [Example 5](https://github.com/Mike-EEE/BenchmarkDotNet.InProcess/tree/TheWeird_05): lower bound -> lower bound

The final fifth example there is to demonstrate that a different result was achieved simply by adding a `System.ComponentModel.DescriptionAttribute` to the benchmark class as seen in the previous branch (fourth example).  I know, very very weird here.

As such, it does seem that when a new component of some sort (attribute, variable, etc), the "state" of the results change.  This is very similar to what I experienced in my VM last year, but luckily (and happily) I have managed to capture it here running on my host non-VM machine.

Please let me know if you have any questions around this.

**Comment by AndreyAkinshin** [comment]
Could you repeat these experiments against LegacyJIT-x86 on full .NET Framework?

**Comment by Mike-EEE** [comment]
Ah does that involve compiled toolchain?  The only toolchain I am able to work on my non-VM host machine is the in-process.  I have not had any luck with the other toolchains as of yet.  I did try on my VM and was able to get a `LegacyJIT-x86` job running.  However it is difficult to know what to look for just yet as out of the gate the performance times seem to be 4x (~80us) of .NET Core. 😆 

I also have not found a good reproducible candidate scenario on my VM yet as it seems more volatile than my non-VM host.  I can look further into this though and see what I can find now that I am a little more oriented.

Are you able to reproduce any of the above examples, @AndreyAkinshin?  Or are you saying that you have and you think you have reduced it to being a RyuJit issue?

**Comment by Mike-EEE** [comment]
I had the **biggest** durp over this and realized that I could simply publish this as an .exe and run it old skool.  I have clearly been mesmerized by all the .NET Core awesome and have already forgotten the past. 😆 

So I did get a chance to try both `x86` and `x64` on my host non-VM machine and was not able to reproduce any of the examples on either architecture.  That is, I was not able to reproduce this issue with _consistent_ disparity upon deleting the artifacts folder.  

So, this seems to be an issue with .NET Core, then, I am thinking.

**Comment by Mike-EEE** [comment]
FWIW @AndreyAkinshin ... I have been digging into this, and this seems to be a .NET Core 2.0.7 problem.  Or at least, that is the runtime that I am able to reproduce this on.  I have been using .NET Core 2.1 RC1 released yesterday along with Visual Studio 2017 15.7 (also released yesterday) and while I can no longer reproduce this problem there, the performance times are actually WORSE now with RC1 vs. 2.0.  I think that will get some attention somewhere. :)  Additionally, this problem still manifests, but in a much more subtle way and not as easily reproducible.

So, the good news is that this does not appear to be a BDN issue but a .NET Core tooling/SDK issue.  The question is... is this a runtime or SDK problem?  I am trying to lock down a simple repro issue to report, but thought I would contact you to see if you could direct me to the appropriate place to see if we can track this thing down and I can get out of your hair. 😄

**Comment by Mike-EEE** [comment]
FWIW x2 (😆): I have created an issue on .NET Core's repo here: https://github.com/dotnet/core/issues/1524

Also worthy to note that I did try to repro this on my Surface laptop but it worked consistently without a problem there.  So, this appears to be an issue with Windows Server specifically.  I will close this issue for now and re-open it if for some reason it turns out that this is a BDN-issue.  Thanks again for your assistance here!

**Comment by Mike-EEE** [comment]
Hey @AndreyAkinshin and @adamsitnik I wanted to check back in here with an update. 

FWIW this item has been identified as a possible code alignment issue in .NET Core CLR:
https://github.com/dotnet/coreclr/issues/17932

I have since created a simple project (along with an alternate version) that clearly demonstrates this problem via a `BenchmarkSwitcher`:

- [https://github.com/Mike-EEE/DotNetCore.CodeAlignment](https://github.com/Mike-EEE/DotNetCore.CodeAlignment)
- [https://github.com/Mike-EEE/DotNetCore.CodeAlignment.Alternate](https://github.com/Mike-EEE/DotNetCore.CodeAlignment.Alternate) (Same as previous but with additional cases)

I am about to throw in the towel here but thought I would provide an update to let you know of the findings.  

Even though this has been identified as a possible CLR issue (not 100% confirmed until it's fixed, of course 😄), I wanted to send out a ping here to see if there might be anything that could be done to possibly mitigate this issue until there is a fix (currently slated for .NET Core 2.2).

Any consideration and possible suggestions would be most appreciated.  Thanks again for all your great work here.
