### ISSUE TITLE
It should be possible to specify the generic arguments by using attributes

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#745]
Let's consider

```cs
public class Bench<T>
{
   [Benchmark] public T Create() => Activator.CreateInstance<T>();
}
```

As of today, to run it for given `T` the users needs to define `T` when running the benchmarks from `BenchmarkRunner` or `BenchmarkSwitcher` level. Example: `BenchmarkRunner.Run<Bench<int>>()`;

It would be nice if this could be defined via attributes, like:

```cs
[GenericBenchmark(typeof(int))]
[GenericBenchmark(typeof(char))]
public class Bench<T>
{
   [Benchmark] public T Create() => Activator.CreateInstance<T>();
}
```

/cc @ahsonkhan

**Comment by Rizzen** [comment]
Possible solution introduced in https://github.com/dotnet/BenchmarkDotNet/pull/758

Also, there is a question - should BenchmarkDotNet allows users to use non-single generic parameter classes as benchmarks?
E.g:
```C#
[GenericBenchmark(typeof(int), typeof(char))]
[GenericBenchmark(typeof(char), typeof(string))]
public class GenericBenchmarks<T, K>
{
    [Benchmark] public T CreateT() => Activator.CreateInstance<T>();

    [Benchmark] public K CreateK() => Activator.CreateInstance<K>();
}
```

**Comment by adamsitnik** [comment]
@Rizzen I changed the naming from `GenericBenchmark` to `GenericTypeArguments` to make it more intuitive.
