### ISSUE TITLE
Better docs that explain what is target/launch/iteration/invocation count

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#747]
Last week we run a hackathon to port corefxlab to BDN and it was hard to explain what all our "counts" mean.

I think that pseudo code will be the best.

**Comment by adamsitnik** [comment]
@AndreyAkinshin I added some pseudo code to make it easier to understand our terminology. I hope this will be enough ;)

**Comment by mattwarren** [comment]
@adamsitnik I really like the 'pseudo-code', such a great way of explaining how BDN works!!

**Comment by mattwarren** [comment]
BTW, great job you're doing, getting other people at Microsoft to use BDN. I've seen it being mentioned more frequently since you joined!
