### ISSUE TITLE
Few questions related to understanding of results

### ISSUE THREAD

**Issue by ddobric** [dotnet/BenchmarkDotNet#775]
### 1. What is a difference between DryCore and Core?
Result in Core:   0.2182 ns
Result in DryCore: 647,800.0000 ns

### 2. What is the meaning of histograms?

[-0.002 ns ; 0.074 ns) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 0.074 ns ; 0.178 ns) | @@@@@@@@@@@@@@@@@@
[ 0.178 ns ; 0.280 ns) | @@@@@@@@
[ 0.280 ns ; 0.355 ns) | @@@@@@@@@@@@@@@@@
[ 0.355 ns ; 0.444 ns) | @@@@@@@@
[ 0.444 ns ; 0.528 ns) | @@@
[ 0.528 ns ; 0.604 ns) | @@@@@
[ 0.604 ns ; 0.651 ns) |
[ 0.651 ns ; 0.727 ns) | @@
[ 0.727 ns ; 0.797 ns) |
[ 0.797 ns ; 0.873 ns) | @

**Comment by adamsitnik** [comment]
Hi @ddobric 

1. `DryJob` runs the benchmark exactly once, without any warmup. You can use it to measure the JIT overhead or to test your benchmark if it works

2. Each `@` represents a single iteration
`[ 0.444 ns ; 0.528 ns) | @@@` - means that there were 3 iterations for which the average time of benchmark execution was between 0.444 ns to 0.528 ns

**Comment by ddobric** [comment]
thanks
