### ISSUE TITLE
Broken AppVeyor build

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#776]
See: https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.14.572
```
Cake.exe : It was not possible to find any compatible framework version
At line:1 char:1
+ & "C:\projects\benchmarkdotnet\tools\Cake.0.26.1\Cake.exe" "build.cak ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (It was not poss...amework version:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
T
he specified framework '
M
icrosoft.NETCore.App'
,
 version '
2
.
1.0-
rc1' was not found.
  - Check application dependencie
s
 
a
nd target a f
r
amework 
v
ers
ion installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are ins
t
```
Commit: https://github.com/dotnet/BenchmarkDotNet/commit/f6372665ba0c2a14b6c1fafb60fbe49f8bf63ab2
It seems that we don't have 2.1.0-rc1 support on AppVeyor.
/cc @adamsitnik @Ky7m

**Comment by Ky7m** [comment]
will take a look.

**Comment by adamsitnik** [comment]
The first commit that broke the build was [this one](https://github.com/dotnet/BenchmarkDotNet/commit/97ddd6e997f923c44630adca262ffa1d8e6fc71f)

I suspect that appveyor installed 2.1 bits globally and our preview stuff stopped working. I tried to update everything to `rc1` but it did not help

**Comment by adamsitnik** [comment]
It looks like setting `DOTNET_MULTILEVEL_LOOKUP=0` might [work](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.14.573). Afaik it tells the dotnet cli to search locally only (what we have in .dotnet folder_
