### ISSUE TITLE
Error when running on Ubuntu at PI

### ISSUE THREAD

**Issue by ddobric** [dotnet/BenchmarkDotNet#782]
Have benchmarks, which run fine on Windows. 
Then I have published the project and moved the output to PI.
When starting with following command, process stops with errors:

`dotnet projectname.dll`

Error:

> // Generate Exception: Unable to find *projectname* in /home/myusername/out and its subfolders

**Comment by adamsitnik** [comment]
hi @ddobric 

Did you publish the app on one machine and copy it to another?

Or did you copy the code, build and run on other machine?

**Comment by ddobric** [comment]
It was published and then copied.

**Comment by adamsitnik** [comment]
BDN generates a new project, with reference to the `.csproj` file which defines the benchmarks.

So to run the  benchmarks on the other machine  you also need to copy the code ;)

If you don't/can't do that they you can use our `[InProcessToolchain]` ([docs](http://benchmarkdotnet.org/Configs/Toolchains.htm#cs)) which does everything inside the same process.

You can find more here #498
