### ISSUE TITLE
Detect correct version of .NET Core in Docket container

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#788]
Original [request](https://github.com/dotnet/BenchmarkDotNet/issues/448#issuecomment-361027977) by @IvanFarkas:

Unfortunately **GetNetCoreVersion()** is not working when used in **Ubuntu** **Docker** container images, since the assembly.CodeBase is ```file:///app/System.Private.CoreLib.dll```

Is there a reliable way to get the **.NET Core runtime version number** at runtime that works in **Docker containers as well**, please?

**Code:** ```RuntimeInformation.FrameworkDescription```
**Output:** ```.NET Core 4.6.00001.0```

**Code:** ```typeof(GCSettings).GetTypeInfo().Assembly.CodeBase```
**Output:** ```file:///app/System.Private.CoreLib.dll```

**Comment by Rizzen** [comment]
There is a post in Scott Hanselman's blog that might be helpful.
https://www.hanselman.com/blog/DetectingThatANETCoreAppIsRunningInADockerContainerAndSkippableFactsInXUnit.aspx

**Comment by Rizzen** [comment]
So, we can get the current .NET Core version from runtime docker image enviroment variables.
There is two cases - dotnet runtime and ASP.NET runtime, both has its own variable. We can check it from Dockerfile: 
https://github.com/dotnet/dotnet-docker/blob/master/2.1/sdk/bionic/amd64/Dockerfile
https://github.com/dotnet/dotnet-docker/blob/master/2.1/aspnetcore-runtime/stretch-slim/amd64/Dockerfile
@AndreyAkinshin I believe I can provide PR for that issue soon.

**Comment by IvanFarkas** [comment]
That would be awesome. Thx, Ivan
