### ISSUE TITLE
Trend Micro OfficeScan kills benchmarks

### ISSUE THREAD

**Issue by IanKemp** [dotnet/BenchmarkDotNet#792]
Yup, another antivirus interference issue. The aforementioned piece of software doesn't cause issues at the start of a run, what instead happens is that every benchmark run is forcibly killed resulting in output that looks like the following:

```
// *** Execute ***
// Launch: 1 / 1
// Execute: C:\Working\Console2\Console2\bin\Release\c1ade94b-1692-440e-b99d-f59afb449f83.exe
// BeforeAnythingElse
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.Activator.CreateInstance[T]()
   at BenchmarkDotNet.Autogenerated.Runnable.Run(IHost host)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!
```

It seems that `EnvironmentAnalyser` doesn't pick this up, so no warnings about antivirus software are emitted on subsequent runs. I've worked around this with the `InProcessAttribute`, so this issue is more to have a discussion on how to handle AVs  going forward.

Personally, I think you should drop the AV check in `EnvironmentAnalyser` (not only is it a very rudimentary check, it's not present for .NET Core at all) and add a blurb to the "Getting Started" guide regarding AVs and using the `InProcessAttribute`.

In fact, is there any reason why in-process is **not** the default? I assume because any stability issues would bring down the whole run, and/or because results could theoretically be affected, but I feel like that won't be an issue for 99.9% of people, while many more will run into AV issues...

**Comment by AndreyAkinshin** [comment]
Agree with @adamsitnik: benchmark isolation is very important. It's pretty easy to "spoil" environment in one benchmark and affect the performance of another benchmark.
