### ISSUE TITLE
Broken BenchmarkSwitcher

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#795]
Repro:
```
dotnet BenchmarkDotNet/samples/BenchmarkDotNet.Samples/bin/Release/netcoreapp2.1/BenchmarkDotNet.Samples.dll IntroBasic
```
BenchmarkSwitcher doesn't parse `IntroBasic` from arguments and prints the list of available benchmarks.

**Comment by adamsitnik** [comment]
Now you need to specify it in an explicit way: `--class=IntroBasic`

@AndreyAkinshin is that ok?

**Comment by AndreyAkinshin** [comment]
Yes, it's OK. However, it's a breaking change. Could we print a warning if we can't parse some arguments?

**Comment by AndreyAkinshin** [comment]
Also, it would be nice to print a few examples in our prompt message. Currently, we have this:

```
You should select the target benchmark(s). Please, print a number of a benchmark (e.g. '0') or a contained benchmark caption (e.g. 'Algo_Md5VsSha256'):
If you want to select few, please separate them with space ` ` (e.g. `1 2 3`)
```
