### ISSUE TITLE
Binding Redirects not working from a netcoreapp2.1 runner with Clr benchmarks

### ISSUE THREAD

**Issue by NickCraver** [dotnet/BenchmarkDotNet#803]
I've got a repro up here with simple run instructions: https://github.com/mgravell/Pipelines.Sockets.Unofficial/pull/2 ([specific commit](https://github.com/mgravell/Pipelines.Sockets.Unofficial/pull/2/commits/dae4efd5b3af3336611d3c63f0700909f57caa8b))

To run:
```ps
dotnet run -p .\tests\Benchmarks\ -c Release -f netcoreapp2.1 Basic
```

This has both `Clr` and `CoreClr` jobs, but the binding redirects present for `System.Buffers` from 4.0.2 to 4.0.3 just aren't working...and I can't see why. Is there some behavior in BenchmarkDotNet that's not apparent here? I've added `[KeepBenchmarkFiles]` for debugging, but the redirect appears to be there. And yet, at runtime:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Buffers.ArrayMemoryPool`1.ArrayMemoryPoolBuffer..ctor(Int32 size)
```

I elaborated on what's already been tried in that PR as well. Am I an idiot? Or have I come across a bug? Please send help!

**Comment by AndreyAkinshin** [comment]
@NickCraver thanks for the bug report!
@adamsitnik could you take a look?

**Comment by adamsitnik** [comment]
I am able to reproduce, I am starting the investigation

**Comment by adamsitnik** [comment]
It's not BenchmarkDotNet issue, I have provided a workaround https://github.com/mgravell/Pipelines.Sockets.Unofficial/pull/4 and reported the bug in CoreFx https://github.com/dotnet/corefx/issues/30642
