### ISSUE TITLE
What is the point of BuildScriptFilePath ?

### ISSUE THREAD

**Issue by Shazwazza** [dotnet/BenchmarkDotNet#804]
I'm in the process of attempting to implement #290 and noticed that the Generators create a `.bat` build script which seems quite handy, but then the Builders don't actually use the build script generated.

For example the `DotNetCliBuilder` runs it's own `restore` and `build` commands and doesn't use the generated build script to do the building.  The Roslyn Builder outputs a log entry for the `BuildScriptFilePath` but then doesn't use it at all.

This might be intentional, so sorry if I'm being naive (the solution is quite a learning curve :)

**Comment by adamsitnik** [comment]
Hi @Shazwazza 

It's a very good question!

BDN used to generate **and run** this script. At some point of time, we moved from doing this to calling Roslyn API directly. The script was preserved for situations when we fail to build the benchmark project, apply `[KeepBenchmarkFiles]` attribute and run it manually to reproduce the problem. So we keep it only for eventual troubleshooting.

You can ignore it if you are developing a custom toolchain.

**Comment by Shazwazza** [comment]
Ah, ok thanks :) I might add some code docs to those classes in my PR.
