### ISSUE TITLE
When will the next release be available on NuGet?

### ISSUE THREAD

**Issue by IanKemp** [dotnet/BenchmarkDotNet#812]
Current version of BenchmarkDotNet on NuGet is 0.10.14 which was released in April. This is an issue because I want to benchmark code that uses types introduced in Framework 4.7.2 (`Span<T>` and `MemoryMarshal` to be precise), and 0.10.14 doesn't support 4.7.2. There isn't a prerelease package either. :(

Is there any intention to release an updated version anytime soon?

**Comment by adamsitnik** [comment]
> This is an issue because I want to benchmark code that uses types introduced in Framework 4.7.2 (Span<T> and MemoryMarshal to be precise), and 0.10.14 doesn't support 4.7.2.

What do you mean by that? 0.10.14 targets .NET 4.6 which can be installed and consumed by .NET 4.7.2 app.

> Is there any intention to release an updated version anytime soon?

1-2 weeks
