### ISSUE TITLE
Error message for wrong command line filter

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#829]
Currently, if I made a typo in the filter (`--filter *BenchmarkNameWithTypo*`), I will get only one line in the output:
```
Global total time: 00:00:00 (0.19 sec), executed benchmarks: 0
```
It's pretty frustrating. I think BenchmarkDotNet should print an error message and the full list of found benchmarks.

**Comment by adamsitnik** [comment]
> I think BenchmarkDotNet should print an error message and the full list of found benchmarks.

@AndreyAkinshin there is a problem with full list, if somebody has a lot of benchmarks then the console output would be too long to understand anything (example: error text + few screens of full benchmark names).

I can add error message with single example like we do for BenchmarkSwitcher. Example:

`Given filter returned zero results. Please remember that the filter is applied to full benchmark name, example: System.Buffers.ArrayPool<byte>.Rent`

@AndreyAkinshin what do you think?

**Comment by AndreyAkinshin** [comment]
@adamsitnik, I like the idea with a few screens. I agree that we shouldn't print thousands of names, but it would be nice to print the full list for a small number of benchmarks (e.g., <50 or <100).

**Comment by brentarias** [comment]
Perhaps the "mispelled" filter name could be passed through a [Soundex query](https://www.techrepublic.com/blog/software-engineer/how-do-i-implement-the-soundex-function-in-c/) so that a list potential matches could be provided, and then that list is further limited to at most N - as @AndreyAkinshin suggested.

**Comment by adamsitnik** [comment]
![image](https://user-images.githubusercontent.com/6011991/42821395-c0cc9ba8-89d8-11e8-8347-ba6b09e1495d.png)

**Comment by adamsitnik** [comment]
![image](https://user-images.githubusercontent.com/6011991/42821445-dafe156a-89d8-11e8-90de-a3840db20900.png)

**Comment by adamsitnik** [comment]
@AndreyAkinshin using trial and error approach I have determined the limit to first 40 benchmarks ;)

**Comment by AndreyAkinshin** [comment]
> I have determined the limit to first 40 benchmarks ;)
LGTM

**Comment by AndreyAkinshin** [comment]
> Perhaps the "mispelled" filter name could be passed through a Soundex query so that a list potential matches could be provided

@brentarias, nice idea, thanks. However, I think it would be better to use the classic Levenshtein distance here. I created an issue for it: https://github.com/dotnet/BenchmarkDotNet/issues/834
