### ISSUE TITLE
Feature requests :)

### ISSUE THREAD

**Issue by jskeet** [dotnet/BenchmarkDotNet#83]
Here's a dump of some feature requests, coming to BenchmarkDotNet for the first time - admittedly with the bias of MiniBench. It's obvious that BenchmarkDotNet does a lot more than MiniBench in terms of the measurement - which is fab! - but I could do with more features to use it on a day-to-day basis.

I'm filing this as a single issue as various of them are sort of related, or may be rejected. I'd suggest that any that strike a chord with others are then expanded into separate, fuller feature requests.

(**edit**: made this into a Task list, so it's easier to track - MattW)
- [ ] More machine-readable output... CSV is a start, but I'd expect JSON and/or XML output formats too
- [ ] Finer-grained test selection. From the command line, it would be helpful to select:
  - Individual test methods
  - Types in an attribute-based category
  - Methods in an attribute-based category
  - Individual test classes (already implemented)
  - Test classes/methods matching a pattern (regex or globbing?)
- [X] Execution-time JIT selection. It's not clear why I'd want to specify all the environments I'm interested in within the code... it's repetitive and limited. Why not just assume we want to run everything, but specify the environment with command-line switches? (**Update**: can now be done, i.e. you can specify `jobs=Clr` or `jobs=LegacyX86,LegacyX64,RyuJitX64` this is the [current list of supported jobs](https://github.com/PerfDotNet/BenchmarkDotNet/blob/de337116a0c1b84b90e20353b6a70eadba834f82/BenchmarkDotNet/Jobs/JobExtensions.cs#L136-L151))
- [x] Dry-run mode... it would be nice to be able to check that all the tests in a run will actually execute, without any configuration etc errors. No measurement required, just build etc, running with a single iteration each time. (**Update**: can now be done via `[DryConfig]` or `jobs=dry` on the cmd line)

I'm sure that I'll have more later :)

**Comment by AndreyAkinshin** [comment]
No problem, we will implement all these features. Can you write some examples of command line syntax for selections and switches which will be ok for you?

**Comment by jskeet** [comment]
Sure, can do... as a thought, it might be worth looking at the new [dotnet CLI](https://github.com/dotnet/cli) for syntax style.

Of course, I'd expect any of this to be available programmatically, too... but an easy way of constructing a program with a "conventional" set of command line arguments is important as well :)

**Comment by AndreyAkinshin** [comment]
Yes, of course, command line support is important, we definitely will implement this feature. We should just choose good names for all of commands that we want to support.

See also: https://github.com/PerfDotNet/BenchmarkDotNet/issues/78, https://github.com/PerfDotNet/BenchmarkDotNet/issues/27.

**Comment by AndreyAkinshin** [comment]
Another issues:
* Export: https://github.com/PerfDotNet/BenchmarkDotNet/issues/75, https://github.com/PerfDotNet/BenchmarkDotNet/issues/84
* Dry-run mode: https://github.com/PerfDotNet/BenchmarkDotNet/issues/85

**Comment by mattwarren** [comment]
>  Finer-grained test selection. From the command line, it would be helpful to select:
- Individual test methods
- Types in an attribute-based category
- Methods in an attribute-based category
- Individual test classes (already implemented)
- Test classes/methods matching a pattern (regex or globbing?)

This is now being tracked in #130

**Comment by adamsitnik** [comment]
We have recently added json and xml support, #130  has been closed a long time ago. I am closing this one.
