### ISSUE TITLE
Better list of suggested benchmarks for wrong filter

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#834]
If we make a typo in a benchmark filter expression, BenchmarkDotNet will print the first 40 known benchmark names (see https://github.com/dotnet/BenchmarkDotNet/issues/829). It will be better to show names which are similar to the filter value (in the case of a typo, it will be easy to fix it). We can use [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) for this feature.

**Comment by adamsitnik** [comment]
Fixed by #957
