### ISSUE TITLE
Generated csproj can't find snk with relative path

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/BenchmarkDotNet#836]
I have [some benchmarks](https://github.com/getsentry/sentry-dotnet/tree/master/benchmarks/Sentry.Benchmarks) on a solution which is strong named.
I'm trying to benchmark some internal classes and for that I made `InternalsVisibleTo` the benchmark project. For that reason, I also had to strong name the benchmark project.

Although the overall solution builds fine, running the benchmarks doesn't.
The problem is with the generated `csproj` files which can't find the `snk` file:

```shell
// Build Exception: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Sentry -> C:\Users\bruno\git\sentry-dotnet\src\Sentry\bin\Release\netstandard2.0\Sentry.dll
  Sentry.Benchmarks -> C:\Users\bruno\git\sentry-dotnet\benchmarks\Sentry.Benchmarks\bin\Release\netcoreapp2.1\Sentry.Benchmarks.dll
CSC : error CS7027: Error signing output with public key from file '../../.assets/Sentry.snk' -- File not found. [C:\Users\bruno\git\sentry-dotnet\benchmarks\Sentry.Benchmarks\bin\Release\netcoreapp2.1\ce1f53d3-5f8a-4230-926a-52c4cf739c35\BenchmarkDotNet.Autogenerated.csproj]

Build FAILED.

CSC : error CS7027: Error signing output with public key from file '../../.assets/Sentry.snk' -- File not found. [C:\Users\bruno\git\sentry-dotnet\benchmarks\Sentry.Benchmarks\bin\Release\netcoreapp2.1\ce1f53d3-5f8a-4230-926a-52c4cf739c35\BenchmarkDotNet.Autogenerated.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.80
```

I've defined the `AssemblyOriginatorKeyFile` and `SignAssembly` at the [Directory.Build.props](https://github.com/getsentry/sentry-dotnet/blob/master/Directory.Build.props#L6)

The code on [master has strong naming disabled](https://github.com/getsentry/sentry-dotnet/blob/master/benchmarks/Directory.Build.props#L9) for the benchmark, but I have a PR where I'm attempting this:

https://github.com/getsentry/sentry-dotnet/pull/61

What would be the advise in this case? Is there a way to specified the signing key's path somehow?

**Comment by adamsitnik** [comment]
Hi @bruno-garcia 

The problem here is that we generate new csproj in `sentry-dotnet\benchmarks\Sentry.Benchmarks\bin\Release\netcoreapp2.1\ce1f53d3-5f8a-4230-926a-52c4cf739c35\BenchmarkDotNet.Autogenerated.csproj`

and MSBuild can't resolve the key path because the generated `.csproj` file is elsewhere.

The only idea I have right now is following workaround:

```xml
<AssemblyOriginatorKeyFile>../../.assets/Sentry.snk</AssemblyOriginatorKeyFile>
<AssemblyOriginatorKeyFile Condition="EXISTS('./../../../../../.assets/Sentry.snk')">../../../../../../.assets/Sentry.snk</AssemblyOriginatorKeyFile>
```
Please let me know if it helps.

**Comment by bruno-garcia** [comment]
Nice work around, works like a charm.
Thanks @adamsitnik!
