### ISSUE TITLE
Can I Pass args to BenchmarkRunner for constructor of my class?

### ISSUE THREAD

**Issue by kanepenley** [dotnet/BenchmarkDotNet#844]
For example, say I have a class called MyClass like the following (assume the class also has a method with a [Benchmark] attribute):

`public class MyClass
    {
        private int _myInt;
        public MyClass(int myInt)
        {
            _myInt= myInt;
        }
     }`
Is there a way to pass an argument to the constructor when I call `BenchmarkRunner.Run<MyClass>()` or is this not supported?

EDIT: It may be worth noting that I am open to a solution that doesn't pass this value though a constructor, but for reasons regarding the way my project is structured I cannot define the value I'm wanting to pass as a Parameter or Argument attributes. I am calling BenchmarkRunner from a separate project that references the project defining the Benchmark Class.

**Comment by AndreyAkinshin** [comment]
Currently, we don't support such feature, but we can discuss it. @adamsitnik did huge console argument refactoring recently, probably he has some thoughts on this (Adam will be available next week).

**Comment by adamsitnik** [comment]
Hi @kanepenley 

Such scenario is not supported, I can offer only some workarounds. 

Can this value be obtained via some static property? If so, you should be able to use [ParamsSource](https://benchmarkdotnet.org/articles/features/parameterization.html#sample-introparamssource) to get it working.

Some pseudo code:

```cs
public class ParamsFromAgs
{
    public static IEnumerable<int> Values()
    {
        foreach(string arg in SomeType.GetValuesFromStaticMethod())
            yield return int.Parse(arg);
    }

    [ParamsSource(nameof(Values))]
    public int Value;
    
    [GlobalSetup]
    public void Setup()
    {
        // Value is not set in ctor, but it's accessible from a [GlobalSetup] method
    }

    [Benchmark]
    public void Benchmark() => Thread.Sleep(Value);
}
```

**Please keep in mind that the Param has no value in ctor and you need to use a `[GlobalSetup]` method**

**Comment by jeff-brooks** [comment]
Thanks for this workaround @adamsitnik . I have similar needs and believe I can make this work via the approach you provided.

Did want to check if this approach has any updates since it was posted?

**Comment by adamsitnik** [comment]
> Did want to check if this approach has any updates since it was posted?

No updates, sorry.

**Comment by jeff-brooks** [comment]
> > Did want to check if this approach has any updates since it was posted?
> 
> No updates, sorry.

No problem. Again, thanks for sharing that workaround.

**Comment by javedali-dev** [comment]
Any update on this feature?

**Comment by CesarD** [comment]
I've just stumbled upon this same requirement and found out that it's not supported 😞

**Comment by adamsitnik** [comment]
We don't plan to implement it, but you can always contribute: fork the library, create a new branch, implement this feature and send a PR. That is always welcomed.

**Comment by tymtam2** [comment]
I used a derived class as a workround:

```
public class BInt: B<int>
{
    public BInt() : base((Random r) => r.Next()) {}
}

public class BString: B<string>
{
    public BString() : base((Random r) => r.Next().ToString()) {}
}

public class B<T>
{
    protected readonly Func<Random, T> f;

    public B(Func<Random, T> f)
    {
        this.f = f;
    }

    [GlobalSetup]
    public void GlobalSetup()
    {
       // Use f here 
```
