### ISSUE TITLE
Multiple frameworks support and conditional defines

### ISSUE THREAD

**Issue by nickbabcock** [dotnet/BenchmarkDotNet#845]
How does one use conditional compilation in benchmarkdotnet?

Let's say our benchmark project has the following conditional dependencies

```xml
  <ItemGroup Condition="'$(TargetFramework)' == 'net461'">
    <PackageReference Include="CityHash.Net" Version="1.0.1" />
    <PackageReference Include="xxHashSharp" Version="1.0.0" />
  </ItemGroup>
```

and the following conditional benchmarks

```csharp
#if NET461
    [Benchmark]
    public uint XXHash() => xxHashSharp.xxHash.CalculateHash(data);

    [Benchmark]
    public uint CityHashNet() => CityHash.CityHash.CityHash32(dataStr);
#endif
```

with the config

```csharp
public class BaseConfig : ManualConfig
{
    public BaseConfig()
    {
        Add(new Job("core-64bit", EnvironmentMode.Core)
            .With(CsProjCoreToolchain.NetCoreApp21));

        Add(new Job("net-legacy-64bit", EnvironmentMode.LegacyJitX64));
    }
}
```

Running

```
dotnet run -c release -f net461 -p Benchmarks -- --filter "*"
```

Results in the .net core project trying to include dependencies slotted for the main framework (and thus errors as those dependencies aren't compatible)

```
28589984-ea55-4546-a944-abe2834f079c.notcs(61441,32): error CS0103: The name 'CityHashNet' does not exist in the current context [C:\projects\hashing\bench\bin\release\net461\28589984-ea55-4546-a944-abe2834f079c\BenchmarkDotNet.Autogenerated.csproj]
28589984-ea55-4546-a944-abe2834f079c.notcs(61753,24): error CS0103: The name 'CityHashNet' does not exist in the current context [C:\projects\hashing\bench\bin\release\net461\28589984-ea55-4546-a944-abe2834f079c\BenchmarkDotNet.Autogenerated.csproj]
28589984-ea55-4546-a944-abe2834f079c.notcs(5413,32): error CS0103: The name 'CityHashNet' does not exist in the current context [C:\projects\hashing\bench\bin\release\net461\28589984-ea55-4546-a944-abe2834f079c\BenchmarkDotNet.Autogenerated.csproj]
28589984-ea55-4546-a944-abe2834f079c.notcs(4769,32): error CS0103: The name 'XXHash' does not exist in the current context [C:\projects\hashing\bench\bin\release\net461\28589984-ea55-4546-a944-abe2834f079c\BenchmarkDotNet.Autogenerated.csproj]

...
```

I've been fiddling more with [toolchains](https://benchmarkdotnet.org/articles/configs/toolchains.html) and `MsBuildArgument` but nothing has solved the case

And it case it helps, I get the intended results when I constrain benchmarks to the runtime filtered to

```
dotnet run -c release -f net461 -p Benchmarks-- -r clr --filter "*"
dotnet run -c release -f netcoreapp2.1 -p Benchmarks-- -r core --filter "*"
```

But this is not desirable as I'd like to run the benchmark suite once and have all the data combined into a single output.

**Comment by adamsitnik** [comment]
hi @nickbabcock 

This scenario (conditional compilation) is not supported.

When the parent process builds the benchmarks projects it is using reflection to search for `[Benchmark]` methods. If you run your example as net461 it finds both `XXHash` and `CityHashNet` methods and builds the project which is using them for net461 and .NET Core. It has no idea that the code is inside `#if NET461`

A workaround:

```cs
    [Benchmark]
    public uint XXHash()  
#if NET461
       => xxHashSharp.xxHash.CalculateHash(data);
#else
       => 0;
#endif
```

It will make the code compile for .NET Core, but the results are going to be 0s.

Another idea: try to reference the desktop .NET packages without `Condition="'$(TargetFramework)' == 'net461'"` and remove `#if NET461`. If the code is using APIs available in .NET Core it might work on Windows (however the compiler will produce some warnings).

**Comment by nickbabcock** [comment]
Thank you for your guidance. I will opt for `0s` and subsequently filter them out. Feel free to close at your discretion (ie. this is a feature that won't / can't be implemented for the foreseeable future).
