### ISSUE TITLE
ArgumentsSource containing IFormattable leads to Compile Exceptions

### ISSUE THREAD

**Issue by alueck** [dotnet/BenchmarkDotNet#853]
Hi,

I wrote a benchmark and assigned an ArgumentsSource which contains objects of classes that implement IFormattable, you could just use DateTime for reproduction purposes. 

Example:
```C#
		public IEnumerable<object> DateTimeValues()
		{
			yield return new DateTime(2018, 8, 15);
		}

		[Benchmark]
		[ArgumentsSource(nameof(DateTimeValues))]
		public void Test(DateTime dt) => dt.ToString();
```

This leads to the following generated constructor by BenchmarkDotnet that contains an obviously invalid assignment in the last line:

```C#
        public Runnable_0()
        {
            globalSetupAction = () => { };
            globalCleanupAction = () => { };
            iterationSetupAction = () => { };
            iterationCleanupAction = () => { };
            overheadDelegate = __Overhead;
            workloadDelegate = Test;
            __argField0 = 08/15/2018 00:00:00;
        }
```

I found the following fix: 

In the method `Create(ParameterDefinition[], object, MemberInfo, int, int)` of the class `SmartParamBuilder` the line `if (SourceCodeHelper.IsCompilationTimeConstant(value))` returns true for objects that implement IFormattable, which in turn leads to the wrongly generated output, because `SourceCodeHelper.ToSourceCode(object)` is used for the code generation and calls `formattable.ToString(null, CultureInfo.InvariantCulture)` in case of IFormattable.

**Comment by adamsitnik** [comment]
@alueck hi! big thanks for the bug report, I am going to fix it right now.

**Comment by adamsitnik** [comment]
@alueck you can download `0.11.0.724` with the fix from our CI feed:

```xml
<packageSources>
  <add key="bdn-ci" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

**Comment by alueck** [comment]
@adamsitnik Thanks
