### ISSUE TITLE
Can't Run Test with .NET 4.7.2

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#861]
I just started using BenchmarkDotNet from a .NET Core 2.1 console app. The benchmarks work great for .NET Core, but I also have it set to benchmark .NET Framework, but I am getting this error:

// Build Exception:   Restoring packages for S:\src\git\dotnetTips\dotNetTips.CodePerf.Example.App\PerfBin\netcoreapp2.1\fde8c2e5-2096-446b-aae9-96dc703f5245\BenchmarkDotNet.Autogenerated.csproj...
S:\src\git\dotnetTips\dotNetTips.CodePerf.Example.App\PerfBin\netcoreapp2.1\fde8c2e5-2096-446b-aae9-96dc703f5245\BenchmarkDotNet.Autogenerated.csproj : error NU1201: Project dotNetTips.CodePerf.Example.App is not compatible with net472 (.NETFramework,Version=v4.7.2). Project dotNetTips.CodePerf.Example.App supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)
S:\src\git\dotnetTips\dotNetTips.CodePerf.Example.App\PerfBin\netcoreapp2.1\fde8c2e5-2096-446b-aae9-96dc703f5245\BenchmarkDotNet.Autogenerated.csproj : error NU1201: Project dotNetTips.CodePerf.Example.App is not compatible with net472 (.NETFramework,Version=v4.7.2) / win7-x64. Project dotNetTips.CodePerf.Example.App supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)
  Generating MSBuild file S:\src\git\dotnetTips\dotNetTips.CodePerf.Example.App\PerfBin\netcoreapp2.1\fde8c2e5-2096-446b-aae9-96dc703f5245\obj\BenchmarkDotNet.Autogenerated.csproj.nuget.g.props.
  Generating MSBuild file S:\src\git\dotnetTips\dotNetTips.CodePerf.Example.App\PerfBin\netcoreapp2.1\fde8c2e5-2096-446b-aae9-96dc703f5245\obj\BenchmarkDotNet.Autogenerated.csproj.nuget.g.targets.
  Restore failed in 168.46 ms for S:\src\git\dotnetTips\dotNetTips.CodePerf.Example.App\PerfBin\netcoreapp2.1\fde8c2e5-2096-446b-aae9-96dc703f5245\BenchmarkDotNet.Autogenerated.csproj.

I'm not sure how to fix this?
Thanks,
David McCarter

**Comment by adamsitnik** [comment]
Hi @RealDotNetDave 

> Project dotNetTips.CodePerf.Example.App is not compatible with net472 (.NETFramework,Version=v4.7.2). Project dotNetTips.CodePerf.Example.App supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)

Your benchmark project needs to target .NET 4.7.2 as well. Your `.csproj` should look like:

`<TargetFrameworks>ne472;netcoreapp2.1</TargetFrameworks>`

**Comment by adamsitnik** [comment]
@RealDotNetDave I am closing, if my answer did not solve the issue please feel free to reopen.

**Comment by RealDotNetDave** [comment]
I changed my csproj to:

<TargetFramework>netcoreapp2.1;net472</TargetFramework>

But keep getting this new build error:
 "ResolvePackageAssets" task failed unexpectedly.
NuGet.Frameworks.FrameworkException: Invalid framework identifier ''.

Any ideas?
David

**Comment by RealDotNetDave** [comment]
Never mind. I figured it out. Thanks.

**Comment by phonglt7** [comment]
> Never mind. I figured it out. Thanks.

Hi, do you mind sharing how you figured it out? The "Invalid framework identifier '' " issue,

**Comment by adamsitnik** [comment]
> The "Invalid framework identifier '' " issue,

@phonglt7  I have seen this issue once or twice, but only when building the project in VS. Did you try to run `dotnet restore` and `dotnet build -c Release` from the console?
