### ISSUE TITLE
Don't print parse errors to the output

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#862]
Some benchmarks need to print to the console. An example: ML.NET 

![image](https://user-images.githubusercontent.com/6011991/44681813-fb450200-aa41-11e8-81b3-7643c49177b9.png)

But when we notify the user with red color about parsing error typically users just get confused

![image](https://user-images.githubusercontent.com/6011991/44681861-1e6fb180-aa42-11e8-94d0-5262e0d8f7c1.png)

@AndreyAkinshin I am going to change it to display parser error only in `DEBUG` (it's usefull for us, not the users)

**Comment by AndreyAkinshin** [comment]
@adamsitnik, I guess it makes sense to introduce a debug mode in our logger which can be enabled via Config or command line arguments. With the `#if DEBUG` directive, it's impossible to get these logs in the release version of the library.
Also, it would be nice to add debug logs in some classes. Right now, I'm playing with StopCriterions (https://github.com/dotnet/BenchmarkDotNet/issues/786) and it's pretty hard to find bugs in such classes during a benchmark.

**Comment by adamsitnik** [comment]
@AndreyAkinshin maybe we should introduce log levels? Info, Warning, Error, and Verbose?

I would like to have more logs when it comes to the toolchains, especially when crazy things happen when we use MSBuild ;)
