### ISSUE TITLE
Expose case insensitive filter via command line args

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#864]
It's driving me crazy sometimes, I am going to expose it via `--cif`

/cc @jorive @valenis

**Comment by AndreyAkinshin** [comment]
@adamsitnik, do we really need case sensitive filter? I guess it makes sense to make it case insensitive by default. (I'm not a huge fan of additional options.)

**Comment by adamsitnik** [comment]
@AndreyAkinshin I was thinking about this. The problem is that C# is case sensitive and here we filter by C# things: namespace, type name and method name.

Honestly I am not sure what we should do: have it case insensitive by default and sensitive on demand? Or the opposite?

**Comment by AndreyAkinshin** [comment]
@adamsitnik could you describe a situation when you really need case sensitive filter?

**Comment by AndreyAkinshin** [comment]
@adamsitnik, are you still going to resolve it in the `v0.11.2` scope?

**Comment by adamsitnik** [comment]
@AndreyAkinshin I made case-insensitive, you were right ;)
