### ISSUE TITLE
How To Run Job using x86 and x64

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/BenchmarkDotNet#873]
I've been trying to for days to figure out how to run a job as x86 & x64 for a Run. My latest attempt was running it like this:

            BenchmarkRunner.Run<PerfTestRunner>(ManualConfig
            .Create(DefaultConfig.Instance)
            .With(Job.Core.With(Platform.X86))
            .With(Job.Core.With(Platform.X64))
            .With(ExecutionValidator.FailOnError));

But the x86 is not tested:

BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17134.228 (1803/April2018Update/Redstone4), VM=Hyper-V
Intel Xeon CPU E5-2673 v4 2.30GHz, 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=2.1.401
  [Host]  : .NET Core 2.1.2 (CoreCLR 4.6.26628.05, CoreFX 4.6.26629.01), 64bit RyuJIT  [AttachedDebugger]
  Core    : .NET Core 2.1.2 (CoreCLR 4.6.26628.05, CoreFX 4.6.26629.01), 64bit RyuJIT
  LongRun : .NET Core 2.1.2 (CoreCLR 4.6.26628.05, CoreFX 4.6.26629.01), 64bit RyuJIT

Is not possible to run both with the same Run?
David

**Comment by adamsitnik** [comment]
Hello @RealDotNetDave 

Yes, you can, but to make it work you need to tell BenchmarkDotNet which dotnet cli to use. Every dotnet cli can run the benchmarks only for one architecture.

An example is described in our [docs](https://benchmarkdotnet.org/articles/configs/toolchains.html?q=toolchains#custom-dotnet-cli-path)

In your case it could be something like this:

```cs
var dotnetCli32bit = NetCoreAppSettings
    .NetCoreApp21
    .WithCustomDotNetCliPath(@"C:\Program Files (x86)\dotnet\dotnet.exe", "32 bit cli");

var dotnetCli64bit = NetCoreAppSettings
    .NetCoreApp21
    .WithCustomDotNetCliPath(@"C:\Program Files\dotnet\dotnet.exe", "64 bit cli");
    
BenchmarkRunner.Run<PerfTestRunner>(ManualConfig
    .Create(DefaultConfig.Instance)
    .With(Job.Core.With(Platform.X86).With(CsProjCoreToolchain.From(dotnetCli32bit))
    .With(Job.Core.With(Platform.X64).With(CsProjCoreToolchain.From(dotnetCli64bit))
    .With(ExecutionValidator.FailOnError));
```

Please feel free to reopen if this does not answer the question
