### ISSUE TITLE
[DevOps] Run builds on Linux, macOS, and Windows using Azure Pipelines

### ISSUE THREAD

**Issue by Ky7m** [dotnet/BenchmarkDotNet#875]
https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

**Comment by Ky7m** [comment]
feel free to assign it to me, I am returning to the normal work mode:)

**Comment by Ky7m** [comment]
@AndreyAkinshin, can we create Azure DevOps project and setup extension https://github.com/marketplace/azure-pipelines ?
Just let me know if you need any guidance for these steps

**Comment by AndreyAkinshin** [comment]
@Ky7m it seems that I do not have permission to modify this app on the dotnet organization.
@jongalloway could you help us?

**Comment by Ky7m** [comment]
There are some failed tests with the following exception:

> Wrong CoreFx version: was 4.6.26629.01, should be 4.6.26531.02

Any ideas, @adamsitnik?

**Comment by adamsitnik** [comment]
@Ky7m the `CustomCoreClrToolchain` is heavily dependent on the `dotnet cli` behavior which is following: you can restore custom `Runtime/NetCoreApp` package if it's newer than the one in the `dotnet cli` sdk folder.

Did you update `dotnet cli`? The solution would be to bump the version numbers in these tests.

**Comment by Ky7m** [comment]
Thank you @adamsitnik , will take a look.
By the way, there is a view of tests https://dev.azure.com/ky7m/BenchmarkDotNet/_build/results?buildId=15&view=ms.vss-test-web.test-result-details (looks better in comparison with Travis CI)

**Comment by adamsitnik** [comment]
Currently this test:

https://github.com/dotnet/BenchmarkDotNet/blob/1e62355f209a25c7a33f9ab7e7e03b0afe7d851f/tests/BenchmarkDotNet.IntegrationTests/CustomCoreClrToolchainTests.cs#L18-L33

Is using: https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp/4.5.0-rtm-26531-02

Could you try to change `4.5.0-rtm-26531-02` to `4.5.0-servicing-26703-08` and `4.6.26531.02` to `4.6.26703.08` ?

**Comment by Ky7m** [comment]
@adamsitnik, I reverted back version of dotnet cli and it solved the issue. Thanks!

**Comment by AndreyAkinshin** [comment]
@adamsitnik, do you know someone who has permissions to setup Azure DevOps in a project of the dotnet organization?

**Comment by jongalloway** [comment]
Thanks, I'll on getting you added and update here.

**Comment by onovotny** [comment]
The app is already in the org, can you grant the pipeline app access? I think there’s a configure option that let’s you grant it permission.

**Comment by jongalloway** [comment]
I just created the app and added @adamsitnik. https://dev.azure.com/dotnet/BenchmarkDotNet

I need e-mail addresses for anyone else that should be added. I'll add pipeline app access now.

**Comment by jongalloway** [comment]
Pretty sure pipelines are enabled, but not an expert on this. Can you verify?

**Comment by AndreyAkinshin** [comment]
@jongalloway, thanks!
Could you also add @Ky7m and me (andrey.akinshin@gmail.com)
@Ky7m could you write your email?

**Comment by jongalloway** [comment]
@AndreyAkinshin Added, you should have an invitation e-mail

**Comment by jongalloway** [comment]
@AndreyAkinshin I re-sent it. Maybe in your spam folder? If you browse to https://dev.azure.com/dotnet/BenchmarkDotNet and click sign in, maybe that will show an invite?

**Comment by AndreyAkinshin** [comment]
@jongalloway now it works, thanks!

**Comment by Ky7m** [comment]
@jongalloway my email is ky7m@hotmail.com

**Comment by jongalloway** [comment]
@Ky7m Added - you can delete your comment if you want.

**Comment by Ky7m** [comment]
@jongalloway thank you! I am still waiting for an invitation email to accept it.

**Comment by jongalloway** [comment]
@Ky7m Can you go to https://dev.azure.com/dotnet/BenchmarkDotNet and try to sign in? Hopefully that will show you the invitation.

**Comment by Ky7m** [comment]
@jongalloway, I've tried and no success. The page shows an error:
> Sorry, but Igor Fesenko <email@hotmail.com> (Microsoft account) is not authorized to access this page because they have not yet accepted the .NET Foundation organization invitation email.

**Comment by Ky7m** [comment]
@jongalloway can you send an invitation one more time plese

**Comment by Ky7m** [comment]
thank you @onovotny and @jongalloway, got the invitation!

**Comment by Ky7m** [comment]
It seems to me I don't have permissions to create/edit pipelines 

> Access denied. Igor Fesenko needs Edit build pipeline permissions for path \ in team project BenchmarkDotNet to perform the action. For more information, contact the Azure DevOps Server administrator.

cc @onovotny @jongalloway

**Comment by onovotny** [comment]
You're all regular team members. Should you all be admins in the project or only some of you?

**Comment by Ky7m** [comment]
would be great to have admin role for all of us (@AndreyAkinshin @adamsitnik @Ky7m ).
For me it might be temporarily assignment, just to setup all pipelines.

**Comment by onovotny** [comment]
Okay, should be all set now.

**Comment by Ky7m** [comment]
great, it works now! Appreciate a lot!!!

**Comment by AndreyAkinshin** [comment]
@onovotny thanks!

**Comment by Ky7m** [comment]
I've created a new PR #929 and see that checks related to Azure Pipelines are not configured. Can someone please check the configuration for the repository (Settings -> Integration and Services -> Azure Pipelines)?

**Comment by AndreyAkinshin** [comment]
I don't have enough permissions. =(
@jongalloway @onovotny can you please enable the Azure Pipeline integration?
