### ISSUE TITLE
Console app Benchmark self-contained and configure inprocess faile because dotnet cli toolchain is not installed

### ISSUE THREAD

**Issue by germandb** [dotnet/BenchmarkDotNet#883]
Hi, I have a Benchmark console app that need to run in diferent machines, that machines could or could not have the .net core installed so I publish the console app using the self-contained configuration.
I read that you use the dotnet cli to build the app and try to run it, but also that the inprocess toolchain configuration omit that step. So I try to config my benchmark to use inprocess my code is like this:

```
public MainConfig() : ManualConfig
{ 
    Add(Job.InProcess
           .With(InprocessToolChain.Instance)
           .With(Platform.X64)
           .With(CsProjCoreToolchain.NetCoreApp21)
           .WithTargetCount(4)
           .WithId("InProcess"));

   Add(new ConsoleLogger);
}
```

When I try to run the benchmark in a machine without dotnet I get the following error:
BenchmarkDotNet requires dotnet cli toolchain to be installed, benchmark 'BenchmarkBI.'Get all rows from table test.': InProcess(Platform=X64, Toolchain=.NET Core 2.1, IterationCount=4)' will not be executed

Any Idea if I need to change anything in the config?

**Comment by AndreyAkinshin** [comment]
@germandb, try to remove `.With(CsProjCoreToolchain.NetCoreApp21)` from your config (if you want to run the benchmark *in process*, you can't configure the version of .NET Core). It's impossible to use two different toolchains at the same time.
