### ISSUE TITLE
Closing application dot't stop benchmark

### ISSUE THREAD

**Issue by isaikin** [dotnet/BenchmarkDotNet#885]
I closed console application, but benchmark still running.

I have used sample "Showtime" for console application.

**Comment by adamsitnik** [comment]
@wojtpl2 would you like to take a look into this issue? It should be impossible, but who knows?

**Comment by wojtpl2** [comment]
Ok. I'll take a look.

**Comment by wojtpl2** [comment]
I have solution for it. I'll push PR.
