### ISSUE TITLE
Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies

### ISSUE THREAD

**Issue by sandersaares** [dotnet/BenchmarkDotNet#895]
Installing BenchmarkDotNet with DependencyBehavior=Lowest results in a broken install in some situation. See https://github.com/dotnet/corefx/issues/32610

Perhaps BenchmarkDotNet should require higher version of the dependency?

**Comment by adamsitnik** [comment]
Hi @sandersaares 

I updated this dependency two days ago in #887. We are soon going to release the `0.11.2` with the new version.

As for now just please remove the binding redirects and it should work fine.

**Comment by adamsitnik** [comment]
This was one big PITA, fixed by using some ugly workarounds in #1032
