### ISSUE TITLE
filesToCopy replacement after removal?

### ISSUE THREAD

**Issue by Wraith2** [dotnet/BenchmarkDotNet#897]
I'm trying to follow the [corefx benchmarking guide](https://github.com/dotnet/corefx/blob/969541fb79ccacbe07965e08e3b32a9d5ecb19bb/Documentation/project-docs/benchmarking.md) which indicates I can use the filesToCopy to get my altered assemblies into a benchmark to directly compare the result against the local nuget version. 

Unfortunately the guide needs updating (which I can do once I get this working), most things I've translated into the new format but I can't find what replaces filesToCopy to get my new build version into the "after" toolchain configuration. Can you tell me how to do this?

**Comment by adamsitnik** [comment]
Hi @Wraith2 

You are using a link to old version of the docs.

You should try the latest one from master branch: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/benchmarking.md

Please let me know if it works for you. It should be much simpler now.

**Comment by Wraith2** [comment]
Ah, I looked directly for filesToCopy because I remembered that detail and didn't realise it was an old blob. Sorry about that.

The shorter setup in the docs runs two jobs for some reason, default and shortjob, i'm not sure if should.
```cs
BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly)
	.Run(args, DefaultConfig.Instance.With(
		Job.ShortRun.With(
		new CoreRunToolchain(
			new FileInfo(@"E:\Programming\csharp7\corefx\bin\testhost\netcoreapp-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\9.9.9\CoreRun.exe")
			)
		)
	)
);
```
returns:
```ini
.NET Core SDK=2.1.402
  [Host]     : .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT  [AttachedDebugger]
  Job-WAHYKS : .NET Core 6d13a1cf-8c0f-4504-9ec8-05b907e18790 (CoreCLR 4.6.27004.04, CoreFX 4.6.27103.0), 64bit RyuJIT
  ShortRun   : .NET Core 9c2ba8ee-36ad-496b-902d-7b3e7b3332c4 (CoreCLR 4.6.27004.04, CoreFX 4.6.27103.0), 64bit RyuJIT
```
