### ISSUE TITLE
Implement `--info`

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#904]
Some of our users really like the info we print about hardware and OS.

An idea: add `--info` console line argument which does not run the benchmarks, but simply prints the info.

```
BenchmarkDotNet=v0.11.1.786-nightly, OS=Windows 10.0.17134.285 (1803/April2018Update/Redstone4)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
Frequency=3507500 Hz, Resolution=285.1033 ns, Timer=TSC
.NET Core SDK=3.0.100-alpha1-009642
  [Host] : .NET Core 3.0.0-preview1-27004-04 (CoreCLR 4.6.27003.04, CoreFX 4.6.27003.02), 64bit RyuJIT
```

/cc @eerhardt

**Comment by AndreyAkinshin** [comment]
It would be also nice to have a public API for it.

**Comment by lahma** [comment]
I could try to implement this in the next days. Could you please clarify what do you mean by public API? Get the same information as string? If there's any pointers where this API would reside and under what name that would also help.
