### ISSUE TITLE
Calling GetType() in ParamsSource method causes unexpected behavior, exceptions

### ISSUE THREAD

**Issue by BACONputing** [dotnet/BenchmarkDotNet#945]
I have a small project where I am benchmarking different implementations of the same interface.  Instead of having methods marked with `[Benchmark()]` that are identical except for the class implementing the interface, I thought I'd try using `[ParamsSource()]` to call a method that finds and instantiates all classes in the assembly that implement the interface.  All of my benchmarks keep failing with an `TargetInvocationException`, however.

Here is some code that demonstrates the issue I am seeing:

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Threading;
    using BenchmarkDotNet.Attributes;
    using BenchmarkDotNet.Running;

    namespace BDN_InterfaceParamsSource
    {
        public interface ISleeper
        {
            void Sleep();
        }

        public abstract class BaseSleeper : ISleeper
        {
            protected abstract int MillisecondsTimeout
            {
                get;
            }

            public void Sleep() => Thread.Sleep(MillisecondsTimeout);

            public override string ToString() => GetType().Name;
        }

        public class Sleeper50ms : BaseSleeper
        {
            protected override int MillisecondsTimeout => 50;
        }

        public class Sleeper100ms : BaseSleeper
        {
            protected override int MillisecondsTimeout => 100;
        }

        public class Sleeper200ms : BaseSleeper
        {
            protected override int MillisecondsTimeout => 200;
        }

        public class Benchmarks
        {
            [ParamsSource(nameof(CreateSleepersUsingAssemblyTypes_BenchmarksAssembly))]
            public ISleeper Sleeper
            {
                get; set;
            }

            // This correctly populates the Sleeper property
            public IEnumerable<ISleeper> CreateSleepersUsingConstructor()
            {
                yield return new Sleeper50ms();
                yield return new Sleeper100ms();
                yield return new Sleeper200ms();
            }

            // This correctly populates the Sleeper property
            public IEnumerable<ISleeper> CreateSleepersUsingFixedTypes()
            {
                return CreateSleeperInstances(
                    new[] {
                        typeof(Sleeper50ms),
                        typeof(Sleeper100ms),
                        typeof(Sleeper200ms)
                    }
                );
            }

            // This correctly populates the Sleeper property
            public IEnumerable<ISleeper> CreateSleepersUsingAssemblyTypes_ISleeperAssembly()
            {
                return CreateSleeperInstances(
                    EnumerateSleeperTypesFromAssembly(typeof(ISleeper).Assembly)
                );
            }

            // This correctly populates the Sleeper property
            public IEnumerable<ISleeper> CreateSleepersUsingAssemblyTypes_ExecutingAssembly()
            {
                return CreateSleeperInstances(
                    EnumerateSleeperTypesFromAssembly(Assembly.GetExecutingAssembly())
                );
            }

            // This fails to populate the Sleeper property
            public IEnumerable<ISleeper> CreateSleepersUsingAssemblyTypes_BenchmarksAssembly()
            {
                return CreateSleeperInstances(
                    // GetType() returns BenchmarkDotNet.Autogenerated.Runnable_x
                    // No ISleeper types are found
                    EnumerateSleeperTypesFromAssembly(GetType().Assembly)
                );
            }

            private IEnumerable<ISleeper> CreateSleeperInstances(IEnumerable<Type> types)
            {
                return types.Select(type => (ISleeper) Activator.CreateInstance(type));
            }

            private IEnumerable<Type> EnumerateSleeperTypesFromAssembly(Assembly assembly)
            {
                var sleeperInterfaceType = typeof(ISleeper);

                return assembly.GetTypes()
                    .Where(type => type.IsClass && !type.IsAbstract && sleeperInterfaceType.IsAssignableFrom(type));
            }

            [Benchmark()]
            public void SleeperBenchmark()
            {
                Sleeper.Sleep();
            }
        }

        public class Program
        {
            public static void Main(string[] args)
            {
                BenchmarkRunner.Run<Benchmarks>();
            }
        }
    }

Running the above produces output like the following for each benchmark parameter:

> // **************************
> // Benchmark: Benchmarks.SleeperBenchmark: DefaultJob [Sleeper=Sleeper100ms]
> // *** Execute ***
> // Launch: 1 / 1
> // BeforeAnythingElse
> 
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in C:\Users\User\Documents\Visual Studio 2017\Projects\BDN-InterfaceParamsSource\bin\Release\netcoreapp2.1\ffa41444-641d-43a1-adcd-5774686c14a1\ffa41444-641d-43a1-adcd-5774686c14a1.notcs:line 108
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\User\Documents\Visual Studio 2017\Projects\BDN-InterfaceParamsSource\bin\Release\netcoreapp2.1\ffa41444-641d-43a1-adcd-5774686c14a1\ffa41444-641d-43a1-adcd-5774686c14a1.notcs:line 62
> // AfterAll
> ExitCode != 0
> No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

Lines 103-109 of the `.notcs` file look like this:

    // the type name must be in sync with WindowsDisassembler.BuildArguments
    public class Runnable_0 : global::BDN_InterfaceParamsSource.Benchmarks
    {
        public static void Run(BenchmarkDotNet.Engines.IHost host, string benchmarkName)
        {
            Runnable_0 instance = new Runnable_0(); // do NOT change name "instance" (used in SmartParamameter)
            instance.Sleeper = (BDN_InterfaceParamsSource.Sleeper100ms)instance.CreateSleepersUsingAssemblyTypes_BenchmarksAssembly().ToArray()[1];;

After much testing, I determined that my call to `GetType().Assembly` in `CreateSleepersUsingAssemblyTypes_BenchmarksAssembly()` was problematic since, unexpectedly (at least to me), that returns an autogenerated assembly rather than my own; using `typeof(ISleeper).Assembly` or `Assembly.GetExecutingAssembly()` instead yields the assembly with my code.

It seems that the method referenced by `[ParamsSource()]` is called multiple times (four, in my case) over the course of a benchmark run, one of which `GetType()` does return `BDN_InterfaceParamsSource.Benchmarks` (and I'd note that the results table does show correct names in the `Sleeper` column) but the others it returns `BenchmarkDotNet.Autogenerated.Runnable_x`, and, of course, there are no `ISleeper` types found in that assembly.  Here's the summary from the end of the run:

> // * Summary *
> 
> BenchmarkDotNet=v0.11.2, OS=Windows 10.0.17134.285 (1803/April2018Update/Redstone4)
> Intel Core i7 CPU 860 2.80GHz (Nehalem), 1 CPU, 8 logical and 4 physical cores
> Frequency=2732434 Hz, Resolution=365.9741 ns, Timer=TSC
> .NET Core SDK=2.1.403
>   [Host] : .NET Core 2.1.5 (CoreCLR 4.6.26919.02, CoreFX 4.6.26919.02), 64bit RyuJIT
> 
> 
>            Method |      Sleeper | Mean | Error |
> ----------------- |------------- |-----:|------:|
>  SleeperBenchmark | Sleeper100ms |   NA |    NA |
>  SleeperBenchmark | Sleeper200ms |   NA |    NA |
>  SleeperBenchmark |  Sleeper50ms |   NA |    NA |
> 
> Benchmarks with issues:
>   Benchmarks.SleeperBenchmark: DefaultJob [Sleeper=Sleeper100ms]
>   Benchmarks.SleeperBenchmark: DefaultJob [Sleeper=Sleeper200ms]
>   Benchmarks.SleeperBenchmark: DefaultJob [Sleeper=Sleeper50ms]
> 
> Unhandled Exception: System.InvalidOperationException: List of measurements contains no elements
>    at BenchmarkDotNet.Extensions.ReportExtensions.GetStatistics(IReadOnlyCollection\`1 runs)
>    at BenchmarkDotNet.Analysers.ZeroMeasurementAnalyser.AnalyseReport(BenchmarkReport report, Summary summary)+MoveNext()
>    at BenchmarkDotNet.Analysers.AnalyserBase.Analyse(Summary summary)+MoveNext()
>    at System.Linq.Enumerable.SelectManySingleSelectorIterator\`2.MoveNext()
>    at System.Linq.Set\`1.UnionWith(IEnumerable\`1 other)
>    at System.Linq.Enumerable.DistinctIterator\`1.FillSet()
>    at System.Linq.Enumerable.DistinctIterator\`1.ToList()
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable\`1 source)
>    at BenchmarkDotNet.Running.BenchmarkRunner.PrintSummary(ILogger logger, IConfig config, Summary summary)
>    at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo[] benchmarkRunInfos, IConfig commonSettingsConfig)
>    at BenchmarkDotNet.Running.BenchmarkRunner.Run(BenchmarkRunInfo benchmarkRunInfo)
>    at BDN_InterfaceParamsSource.Program.Main(String[] args) in C:\Users\User\Documents\Visual Studio 2017\Projects\BDN-InterfaceParamsSource\Program.cs:line 121
> // * Artifacts cleanup *

**Comment by adamsitnik** [comment]
Hi @BACONputing 

We create a type which derives from the type which defines benchmarks. We do that to generate all the boilerplate code that prevents from benchmarking pitfalls. This is why calling a virtual method like `GetType` returns the auto-generated type. And I am afraid that as of today there is nothing we can do about this.
