### ISSUE TITLE
How to dynamically load BenchmarkDotNet.Diagnostics.Windows without NuGet hacks

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#955]
We have `BenchmarkDotNet.Diagnostics.Windows.dll` and `BenchmarkDotNet.dll`.  `BenchmarkDotNet.Diagnostics.Windows.dll` has dependency to `BenchmarkDotNet.dll`, not the opposite.

When the user specifies `--profiler ETW` we parse command line arguments in `BenchmarkDotNet.dll` and we try to load `BenchmarkDotNet.Diagnostics.Windows.dll` in a dynamic way using `Assembly.Load` and others:

https://github.com/dotnet/BenchmarkDotNet/blob/60ea1705d7d8e31eb1292e5bf785f818b9cbd0a2/src/BenchmarkDotNet/Diagnosers/DiagnosersLoader.cs#L97-L112

@eerhardt how can we load it without `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` in NuGet friendly way?

**Comment by eerhardt** [comment]
This is exactly the scenario that [`DependencyContext`](https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.Extensions.DependencyModel/DependencyContext.cs) is meant to solve.

You can find all the dependencies of the current application by looking in `DependencyContext.Default.RuntimeLibraries`.

Note this typically only works on .NET Core projects, which automatically create `.deps.json` files. It will work on .NET Framework projects, if the application is built to produce a `.deps.json` file (not the default on .NET Framework).

**Comment by wojtpl2** [comment]
I did this issue. I'll push PR in no time.

**Comment by wojtpl2** [comment]
@adamsitnik Do you have any other task that I can take care of? I can finish #912 if you want. Of course, I'll keep your history of changes. Or I can take something else.
