### ISSUE TITLE
AutoGenerated csproj fails to include <Reference> items from <ProjectReference>

### ISSUE THREAD

**Issue by russcam** [dotnet/BenchmarkDotNet#956]
I have a netcoreapp2.1 exe that runs benchmarks for different versions of the same assembly (IL rewritten to allow both versions to be referenced). The Autogenerated.csproj does not pull in the referenced assemblies. An example Autogenerated.csproj

```xml
<Project ToolsVersion="15.0">
  <PropertyGroup>
    <ImportDirectoryBuildProps>false</ImportDirectoryBuildProps>
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
  </PropertyGroup>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <AssemblyTitle>795b2211-bf3f-48a1-a38d-44554ea7c4e3</AssemblyTitle>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AssemblyName>795b2211-bf3f-48a1-a38d-44554ea7c4e3</AssemblyName>
    <OutputType>Exe</OutputType>
    <OutputPath>bin\Release</OutputPath>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="795b2211-bf3f-48a1-a38d-44554ea7c4e3.notcs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="C:\Users\russ\source\NestVersionBenchmark\NestVersionBenchmarkCore\NestVersionBenchmarkCore.csproj" />
  </ItemGroup>
  
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
```

where the project referenced at path `C:\Users\russ\source\NestVersionBenchmark\NestVersionBenchmarkCore\NestVersionBenchmarkCore.csproj` is

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.11.2.849" />
      <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.11.2.849" />
      <PackageReference Include="Utf8Json" Version="1.3.7" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Elasticsearch.Net, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d">
        <HintPath>C:\Users\russ\source\elasticsearch-net-master\build\output\Nest.JsonNetSerializer\netstandard2.0\Elasticsearch.Net.dll</HintPath>
      </Reference>
      <Reference Include="Elasticsearch.Net6x, Version=6.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d">
        <HintPath>C:\Users\russ\source\NestVersionBenchmark\References\6x\netstandard2.0\Elasticsearch.Net6x.dll</HintPath>
      </Reference>
      <Reference Include="Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d">
        <HintPath>C:\Users\russ\source\elasticsearch-net-master\build\output\Nest.JsonNetSerializer\netstandard2.0\Nest.dll</HintPath>
      </Reference>
      <Reference Include="Nest.JsonNetSerializer, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d">
        <HintPath>C:\Users\russ\source\elasticsearch-net-master\build\output\Nest.JsonNetSerializer\netstandard2.0\Nest.JsonNetSerializer.dll</HintPath>
      </Reference>
      <Reference Include="Nest.JsonNetSerializer6x, Version=6.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d">
        <HintPath>C:\Users\russ\source\NestVersionBenchmark\References\6x\netstandard2.0\Nest.JsonNetSerializer6x.dll</HintPath>
      </Reference>
      <Reference Include="Nest6x, Version=6.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d">
        <HintPath>C:\Users\russ\source\NestVersionBenchmark\References\6x\netstandard2.0\Nest6x.dll</HintPath>
      </Reference>
      <Reference Include="Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed">
        <HintPath>C:\Users\russ\source\elasticsearch-net-master\build\output\Nest.JsonNetSerializer\netstandard2.0\Newtonsoft.Json.dll</HintPath>
      </Reference>
      <Reference Include="Newtonsoft.Json6x, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed">
        <HintPath>C:\Users\russ\source\NestVersionBenchmark\References\6x\netstandard2.0\Newtonsoft.Json6x.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
```

I a long list of following kind of errors in standard output:

```
795b2211-bf3f-48a1-a38d-44554ea7c4e3.notcs(13131,25): error CS0246: The type or namespace name 'Nest' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\russ\sourc
e\NestVersionBenchmark\NestVersionBenchmarkCore\bin\Release\netcoreapp2.1\795b2211-bf3f-48a1-a38d-44554ea7c4e3\BenchmarkDotNet.Autogenerated.csproj]
```

I've tried the following:

1. Thinking it might be relative paths for the `<Reference>` items, I changed them to absolute ones, but still the same issue. 
2. All `<Reference>` items are netstandard2.0, so I thought I would also try setting `<PackageTargetFallback>netstandard2.0</PackageTargetFallback>` , then `<AssetTargetFallback>netstandard2.0</AssetTargetFallback>`, but still the same result with both (the former says to use `<AssetTargetFallback>`.

With an old csproj running net462 that runs benchmarks, the referenced assemblies are picked up by the Autogenerated.csproj and everything works great. The referenced assemblies are net46 and net461 in this case.

Am I missing something?

**Comment by adamsitnik** [comment]
Hi @russcam !

Does it complain only about the `Nest` namespace?
Do you have some `.target` files that should be included? (we exclude them by default)
Did the behaviour changed for `0.11.1` and `0.11.2`?

I am trying to narrow down the possible issues.

**Comment by russcam** [comment]
Hey @adamsitnik!

It complains about both `Nest` and `Nest6x`.
Not .target files.

I'll try with 0.11.1 now

**Comment by adamsitnik** [comment]
Also, could you upload the `using` blocks from the beginning of the auto-generated C# file? (`795b2211-bf3f-48a1-a38d-44554ea7c4e3.notcs`)

**Comment by russcam** [comment]
It looks like the `<ProjectReference>` in the autogenerated csproj is not including any of the `<Reference>`.

Just tried with 0.10.14; with this version, it complains about not finding the reference to `Nest` only.

**Comment by russcam** [comment]
If it would help diagnose, more than happy to upload a reproducible zip, just let me know 👍

**Comment by adamsitnik** [comment]
@russcam I think that we run into some MSBuild issue/limitation here. But before I go to some MSBuild experts I need some repro which does not involve BDN.

Could you add  a new console app project to your solution and reference the `NestVersionBenchmarkCore.csproj` project, consume something from `Nest` namespace and run dotnet build?

**Comment by russcam** [comment]
@adamsitnik I added a new .NET core console app to the solution with a ProjectReference to `NestVersionBenchmarkCore.csproj` to test. 

I can consume the benchmark classes defined in NestVersionBenchmarkCore in this new project, but I can't consume any types in the `Nest` namespace, or any types in any of the assemblies reference by `NestVersionBenchmarkCore.csproj` with a `<Reference>` item for that matter. The only way I can do so is by copying the `<Reference>` over. 

So, it does look like a limitation of MsBuild/Project system.

**Comment by adamsitnik** [comment]
Maybe you could use one of our latest features that allows you to specify NuGet packages that you want to use for perf comparison instead?

https://benchmarkdotnet.org/articles/samples/IntroNuGet.html

**Comment by russcam** [comment]
Neither of the set of versioned references are part of NuGet packages yet sadly, but I'll look at packing them into packages and reference that way. I'll let you know how it goes :smile:

**Comment by russcam** [comment]
@adamsitnik Adding `<Reference>` into nuget packages with different names, and referencing these using `<PackageReference>` from a local package source works. Thanks!

**Comment by adamsitnik** [comment]
@russcam I am glad you got it working!

I am going to close this issue as it seems to be more of a MsBuild limitation
