### ISSUE TITLE
snupkg

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#967]
https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html

@AndreyAkinshin what do you think? I sometimes have to debug BDN, it would be nice to have

**Comment by AndreyAkinshin** [comment]
Good idea, I like it.

**Comment by adamsitnik** [comment]
@wojtpl2 this might be an interesting issue to try and learn something new

**Comment by adamsitnik** [comment]
Fixed in #968
