### ISSUE TITLE
Histograms

### ISSUE THREAD

**Issue by gregoryyoung** [dotnet/BenchmarkDotNet#98]
I was looking at adding histogram support and ended up here: https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Mathematics/Statistics.cs

I have two questions. 

1) Would a PR with histogram support be accepted? It would seem to be pretty useful (much more so that mean + stddev)
2) As of now statistics is taking a full result set of doubles. This is probably not the best idea for fine grained runs where I might be wanting to run say 50m times this looks like a larger change to allow for incremental tracking, is there a reason its done in the current way?

**Comment by mattwarren** [comment]
I'll let @AndreyAkinshin comment about if this is a good fit for BenchmarkDotNet, he handles the parts of the code that do all the stats!

However `<shameless plug>` if we do this, consider using the [C# port of HdrHistogram](https://github.com/HdrHistogram/HdrHistogram.NET), I wrote a while back `</shameless plug>`. 

The original Java version was written by [Gil Tene](http://www.infoq.com/author/Gil-Tene), it's very low-overhead and doesn't allocate memory once you've created it. See the [Java README](https://github.com/HdrHistogram/HdrHistogram) for the full info.

**Comment by gregoryyoung** [comment]
HDRHistogram is exactly what I was planning on using :)

**Comment by AndreyAkinshin** [comment]
> I was looking at adding histogram support

Sounds good. However, I don't wont to have any dependencies in the core library. I can suggest the following plan:
1. On this weekend, I'm going to accept https://github.com/PerfDotNet/BenchmarkDotNet/pull/87 with DNX support. This PR has a rewritten project structure (xproj instead of csproj). Please, wait for this merge. Otherwise, we will have a lot of troubles with merging your histogram branch and master.
2. You create a separated project (e.g. `BenchmarkDotNet.HdrHistogram` with the HdrHistogram dependency via NuGet) and write own exporter (e.g. `HdrHistogramExporter`).
3. I create a separated NuGet package with your exporter.

What do you think?

> This is probably not the best idea for fine grained runs where I might be wanting to run say 50m times this looks like a larger change to allow for incremental tracking

Can you write an example that explains your idea?

**Comment by gregoryyoung** [comment]
"What do you think?

This is probably not the best idea for fine grained runs where I might be
wanting to run say 50m times this looks like a larger change to allow for
incremental tracking

Can you write an example that explains your idea?"


That you call per measurement not "here are all the results"

On Thu, Feb 25, 2016 at 2:40 PM, Andrey Akinshin <notifications@github.com>
wrote:

> I was looking at adding histogram support
>
> Sounds good. However, I don't wont to have any dependencies in the core
> library. I can suggest the following plan:
> 1. On this weekend, I'm going to accept #87
> <https://github.com/PerfDotNet/BenchmarkDotNet/pull/87> with DNX support.
> This PR has a rewritten project structure (xproj instead of csproj).
> Please, wait for this merge. Otherwise, we will have a lot of troubles with
> merging your histogram branch and master.
> 2. You create a separated project (e.g. BenchmarkDotNet.HdrHistogram with
> the HdrHistogram dependency via NuGet) and write own exporter (e.g.
> HdrHistogramExporter).
> 3. I create a separated NuGet package with your exporter.
>
> What do you think?
>
> This is probably not the best idea for fine grained runs where I might be
> wanting to run say 50m times this looks like a larger change to allow for
> incremental tracking
>
> Can you write an example that explains your idea?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PerfDotNet/BenchmarkDotNet/issues/98#issuecomment-188768801>
> .
>



-- 
Studying for the Turing test

**Comment by AndreyAkinshin** [comment]
Sorry, I still don't get it.

**Comment by gregoryyoung** [comment]
Right now it does measurements. Collects all results. Sends all results to
statistics. With many millions of runs on very tight code this can be very
expensive (think 100m runs). Instead it might be nice to be able to mark
runs one by one to statistics to avoid having to keep the entire run set in
memory (eg incremental)

On Thu, Feb 25, 2016 at 4:11 PM, Andrey Akinshin <notifications@github.com>
wrote:

> Sorry, I still don't get it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PerfDotNet/BenchmarkDotNet/issues/98#issuecomment-188799283>
> .
>



-- 
Studying for the Turing test

**Comment by AndreyAkinshin** [comment]
In fact, we don't have a lot of measurements. A measurement take at least 200ms. Thus, in the worst case, we have ~18'000 measurements per hour.

**Comment by gregoryyoung** [comment]
Ah ok

On Thu, Feb 25, 2016 at 5:01 PM, Andrey Akinshin <notifications@github.com>
wrote:

> In fact, we don't have a lot of measurements. A measurement take at least
> 200ms. Thus, in the worst case, we have ~18'000 measurements per hour.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PerfDotNet/BenchmarkDotNet/issues/98#issuecomment-188823145>
> .
>



-- 
Studying for the Turing test

**Comment by goldshtn** [comment]
It would be really nice to have histogram output. Eat to results. Average/min/stdev is nice but often won't tell the whole story for complex benchmarks, or long-running stuff.

**Comment by gregoryyoung** [comment]
I notice that this project does not have an up for grabs tag. This would be a great example of a relatively simple issue which is less than a few hours of work which could go there. Unless someone else does it first I will do it next week but having an up for grabs tag can be a good way to bring interested parties into the project.

**Comment by mattwarren** [comment]
>  notice that this project does not have an up for grabs tag. This would be a great example of a relatively simple issue which is less than a few hours of work which could go there. 

Done, @gregoryyoung thanks for the idea

**Comment by LeeCampbell** [comment]
Hey any objections if I try to put the [HdrHistogram](https://www.nuget.org/packages/HdrHistogram/) (rewrite) i.e. not the current official one? Interestingly I am just swapping out my hand rolled perf tests for this lib in the HdrHistogram project.

**Comment by mattwarren** [comment]
> Hey any objections if I try to put the HdrHistogram (rewrite) i.e. not the current official one?

I think that @gregoryyoung was going to do the same thing, so maybe check you aren't duplicating each other. And yes it would be much better to use your re-write, rather than my out-of-date version!

> Interestingly I am just swapping out my hand rolled perf tests for this lib in the HdrHistogram project.

Cool, once you're done we can add you to [the list](https://github.com/PerfDotNet/BenchmarkDotNet/wiki/People-using-BenchmarkDotNet)

**Comment by gregoryyoung** [comment]
I was going to use HdrHistogram though

On Wed, Apr 13, 2016 at 4:31 PM, Matt Warren <notifications@github.com>
wrote:

> Hey any objections if I try to put the HdrHistogram (rewrite) i.e. not the
> current official one?
>
> I think that @gregoryyoung <https://github.com/gregoryyoung> was going to
> do the same thing, so maybe check you aren't duplicating each other. And
> yes it would be much better to use your re-write, rather than my
> out-of-date version!
>
> Interestingly I am just swapping out my hand rolled perf tests for this
> lib in the HdrHistogram project.
>
> Cool, once you're done we can add you to the list
> <https://github.com/PerfDotNet/BenchmarkDotNet/wiki/People-using-BenchmarkDotNet>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/PerfDotNet/BenchmarkDotNet/issues/98#issuecomment-209511516>
>



-- 
Studying for the Turing test

**Comment by mattwarren** [comment]
> I was going to use HdrHistogram though

There's a few versions of HdrHistogram

My [old and out of date version](https://github.com/HdrHistogram/HdrHistogram.NET) which is "official" in as much as it lives under https://github.com/HdrHistogram.

Lee's [newer and actively maintained version](https://github.com/LeeCampbell/HdrHistogram.NET) which is also available as a [NuGet package](https://www.nuget.org/packages/HdrHistogram).

I'm pretty sure that Lee is going to move his code under https://github.com/HdrHistogram so that it can become the "official" version, @LeeCampbell is that correct?

**Comment by LeeCampbell** [comment]
As of today, my re-write will be moved to the common/official https://github.com/HdrHistogram organization under the https://github.com/HdrHistogram/HdrHistogram.net repo. ETA is a few weeks to get this done properly.

**Comment by mattwarren** [comment]
@LeeCampbell thanks for the update and thanks for all the work you've done on HdrHistogram, it's much further along that the version I did a year ago!

**Comment by AndreyAkinshin** [comment]
@adamsitnik I suggest closing this issue. Right now we have great histograms in RPlotExporter and it covers basic use cases. If someone will send a good PR with advanced histogram support, I'm happy to merge it, but I don't think that it makes sense to keep an open issue with it.
What do you think?

**Comment by adamsitnik** [comment]
@AndreyAkinshin I agree!
