### ISSUE TITLE
Invalid string representaiton of CPU Affinity on a machine with more than 32 cores

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#982]
On 48 CPU core machine for a benchmark with no explicit Affinity set, we display

`0000000000000011111111111111111111111111111111`

while it should be

`1111111111111111111111111111111111111111111111`

It's confusing to our users which can think that we have affinitized the benchmark to 32 out of 48 cores

/cc @AndyAyersMS

**Comment by adamsitnik** [comment]
I did read the BDN code and it looks perfectly fine. My suspicion is that System.Diagnostics.Process.GetCurrentProcess().ProcessorAffinity returns 2^32 instead of 2^48 here.

**Comment by adamsitnik** [comment]
https://github.com/dotnet/corefx/issues/33823 - it's not BDN fault

**Comment by adamsitnik** [comment]
I was able to verify that it was not a BDN fault, https://github.com/dotnet/corefx/pull/33825 fixed it

**Comment by AndreyAkinshin** [comment]
@adamsitnik Do I understand correctly that the fix will be available only in the future versions of .NET Core? Should we print a warning for developers who want to set 48-bit affinity on old versions of .NET Core?

**Comment by adamsitnik** [comment]
@AndreyAkinshin `Process.ProcessorAffinity` API was so far returning value not bigger than 2^32 on ARM on Linux. We use this API to print `ProcessorAffinity` value and because it had a bug we were also displaying wrong value. 

To add a warning we would have to detect that BDN is running on ARM on older .NET Core, call native OS API, compare the returned value with Process.ProcessorAffinity returned value and report a warning if the two values were different. I think it's an edge case and adding it to BDN is not worth it.
