### ISSUE TITLE
Give a warning when the [Benchmark] method is static

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#983]
BDN supports only instance methods, when our users try to do sth like:

```cs
public class Some
{
   [Benchmark]
   public static void This() { }
}
```

they get a silent error.

@AndreyAkinshin or maybe we should allow for static method calls?

**Comment by AndreyAkinshin** [comment]
@adamsitnik, I'm not sure that static benchmarks is a good idea. It will complicate our generation template and it can introduce some undesirable effects in nanobenchmarks (such a feature should be carefully checked). Let's just warn users about an incorrect signature.

**Comment by Rizzen** [comment]
I can do it.

**Comment by AndreyAkinshin** [comment]
@Rizzen thanks!
